### ISSUE TITLE
Ошибка установки параметра типа "Граница" в консоли запросов

### ISSUE THREAD

**Issue by Spakus** [tormozit/RDT1C#10]
Добрый день.
Невозможно установить значение параметра с типом "Граница" в консоли запросов.
При использовании в запросе параметра типа "Граница" невозможно установить значение Дата (поле недоступно для изменения, дата пустая). При попытке установить установить значение, используя кнопку "Исследовать", система выдает ошибку "Поле объекта недоступно для записи (Значение)". 

Платформа: 8.3.15.1830
Режим БД: клиент-серверный
Конфигурация. Название: ЕИС (3.1.124.28971)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Инструменты разработчика. Версия: Портативный 6.04.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 18363)

**Воспроизведение проблемы**
1. Открыть инструмент "Консоль запросов"
2. Написать запрос к виртуальной таблице остатков любого регистра накопления, задать "период" в качестве параметра
3. Установить параметр "Период" с типом "Граница"
4. Попробовать заполнить поле "Значение" любой датой

**Ожидаемое поведение**
Возможно установить значение даты параметра "Период" с типом "Граница"

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/931883

**Comment by tormozit** [comment]
Исправлено в 6.04.2
