### ISSUE TITLE
Редактор констант ИР. Связанный.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#100]
https://user-images.githubusercontent.com/87958986/134792711-70327f94-0297-4412-bfe8-ab5bf9b9b00e.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Редактор констант
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор констант ИР"
2. Нажал кнопку "Связанный"
3. Получил окно с ошибкой:

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(1798)}: Преобразование значения к типу Число не может быть выполнено
		ИмяТипа = СтрЗаменить(ПеревестиСтроку(Фрагменты[0]) + "." + Фрагменты[1], ".", Подтип + ".");

```

**Ожидаемое поведение**
Возможно открытие редактора объекта БД строки.

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.11.1
