### ISSUE TITLE
Колонки БД. Анализ данных.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#101]
https://user-images.githubusercontent.com/87958986/134819500-168d4684-1932-4c7b-9370-f30a0d348b37.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Колонки БД
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Колонки БД"
2. Нажал кнопку "Анализ данных"
3. Получил окно с ошибкой:

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(30670)}: Ошибка при вызове метода контекста (ВыполнитьПакет)
				РезультатПакета = Запрос.ВыполнитьПакет();
по причине:
{(198, 6)}: Ошибка обработки представления "КритерийОтбора.СсылкиНаПКО:Несоответствие типов (Параметр номер ""1"")"
FROM <<?>>КритерийОтбора.СсылкиНаПКО AS Т

```

**Ожидаемое поведение**
Анализ данных

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934610

**Comment by tormozit** [comment]
Исправлено в 6.11.2
