### ISSUE TITLE
Интерфейсная панель. Индекс находится за границами массива

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#102]
https://user-images.githubusercontent.com/87958986/134820516-0dce5e13-77b5-4f8c-8e44-d7551d002d2c.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Интерфейсная панель
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Интерфейсная панель"
2. Вызвал контекстное меню на "Обработки"
3. Вызвал команду "Открыть"
3. Получил окно с ошибкой:
`{ВнешняяОбработка.ирОбщий.МодульОбъекта(37269)}: Индекс находится за границами массива`

**Ожидаемое поведение**
Недоступность команды или отсутствие реакции. Сомневаюсь, что корень ветки "Обработки" можно исследовать через инструмент "Исследователь объектов ИР"

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.12.1
