### ISSUE TITLE
Интерфейсная панель. Значение не является значением объектного типа (Состав)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#103]
https://user-images.githubusercontent.com/87958986/134820693-8b28bc2b-0ce2-4684-8170-1ce7058d59b7.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Интерфейсная панель
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Интерфейсная панель"
2. Раскрыл "Константы", выбрал константу
3. Вызывал контекстное меню и выбрал "Подсистемы объекта"
4. Получил сообщение:

```
{Форма.ВыборПодсистемы.Форма(30)}: Значение не является значением объектного типа (Состав)
			Если НЕ МДПодсистема.Состав.Содержит(МДОбъект) Тогда

```

**Ожидаемое поведение**
Вероятно открытие списка подсистем в которую была включена константа.
![image](https://user-images.githubusercontent.com/87958986/134820786-5f6d8312-d897-46ae-9ed2-da7ba025f89f.png)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934609

**Comment by tormozit** [comment]
Исправлено в 6.11.2
