### ISSUE TITLE
Интерфейсная панель. Связанный динамический список.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#104]
https://user-images.githubusercontent.com/87958986/134821543-b6f50497-082f-4214-8a58-27b0509544ff.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Интерфейсная панель
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Интерфейсная панель"
2. Выбрал объект
3. Вызвал контекстное меню -> "Таблица БД" -> "Связанный динамический список"
4. Не закрывая ДС, выбрал другой объект в Интерфейсной панели.
3. Получил окно с ошибкой:

```
Поле объекта не обнаружено (ПолноеИмяОбъекта)
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(279)}:			мСвязанныйДинамическийСписок.УстановитьОбъектМетаданных(ТекущаяСтрока.ПолноеИмяОбъекта);
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(196)}:	СгенерироватьКомандыКонтекстногоМенюПоСтроке(ТабличноеПоле, ТекущаяСтрока);
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(2304)}:	СгенерироватьКомандыКонтекстногоМеню(Элемент);
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(1357)}:				ТабличноеПоле.ТекущаяСтрока = ТабличноеПоле.Значение[0];
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(1236)}:	ЗаполнитьСтатическиеВеткиДереваИнтерфейса(Ложь);
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(1119)}:			ЗаполнитьСтатическиеВетки();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(26687)}:		ФормаИнтерфейснойПанели.ДобавитьСтрокуВСтатическуюВетку(СтруктураЭлемента);
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(123)}:		ирОбщий.ДобавитьТаблицуВИзбранноеЛкс(фОбъект.ПолноеИмяТаблицы);
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(279)}:			мСвязанныйДинамическийСписок.УстановитьОбъектМетаданных(ТекущаяСтрока.ПолноеИмяОбъекта);
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(196)}:	СгенерироватьКомандыКонтекстногоМенюПоСтроке(ТабличноеПоле, ТекущаяСтрока);
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(185)}:	СгенерироватьКомандыКонтекстногоМеню(ЭлементыФормы.ДеревоИнтерфейса);
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(979)}:	СгенерироватьКомандыКонтекстногоМенюДерева();

```

**Ожидаемое поведение**
Ожидалось отсутствие реакции или пересоздание ДС с таблицей нового объекта.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934611

**Comment by tormozit** [comment]
Исправлено в 6.12.1
