### ISSUE TITLE
Консоль построителя отчетов. Изменить текущий элемент.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#105]
https://user-images.githubusercontent.com/87958986/134839546-78bab53d-fbc1-47c3-9cb0-ce619c0e2622.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Консоль построителей отчетов
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль построителя отчетов"
2. Нажал кнопку "Изменить"
3. Перешел на вкладку "Параметры"
4. Нажал кнопку "Добавить"
5. Поменял "Тип" на "Выражение"
6. Вызвал выбор на поле "Значение по умолчанию"
7. Получил окно с ошибкой:

```
{Форма.ФормаРедактированияЗапроса.Форма(371)}: Поле объекта не обнаружено (ОбработкаПолеТекстаПрограммы)
		ОбработкаВводаФормулы.ОбработкаПолеТекстаПрограммы.ДобавитьСловоЛокальногоКонтекста(
```

**Ожидаемое поведение**
Открытие редактора выражения

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934612

**Comment by tormozit** [comment]
Исправлено в 6.12.1
