### ISSUE TITLE
Консоль построителей отчетов. Отбор

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#106]
https://user-images.githubusercontent.com/87958986/134840038-08827e55-76b2-4a11-b9dd-2286d9607963.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Консоль построителей отчетов
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль построителей отчетов"
2. Нажал кнопку "Изменить"
3. Нажал кнопку "ОК"
4. Появилась вкладка "Отбор". Перешел на неё. Нажал кнопку "Добавить"
5. В открывшемся диалоге нажал "ОК"
6. Перешел на поле "Значение" и нажал F4
7. В открывшемся диалоге выбора типов выбрал тип "Дата"
3. Получил окно с ошибкой:

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10385)}: Ошибка при установке значения атрибута контекста (Значение)
					ДанныеСтроки[ПутьКДаннымКолонки] = Значение;
по причине:
Неверный тип значения

```

**Ожидаемое поведение**
Невозможность выбора типов без выбранного поля отбора, либо его обновление при выборе конкретного поля позже, если типы не совпадают.

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.12.1
