### ISSUE TITLE
Консоль запросов. УстановитьГраницыВыделения

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#11]
https://user-images.githubusercontent.com/87958986/129081947-94b68739-55b2-4670-a8e6-0735e34704ef.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.04.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

Ошибка происходит при нажатии на горячие клавиши Ctrl+/ в консоли запросов при включенном разрешении установки курсора за концом строки, если был захвачен лишний блок выделения.

```

Ошибка при вызове метода контекста (УстановитьГраницыВыделения)
{ВнешняяОбработка.ирОболочкаПолеТекста.МодульОбъекта(45)}:			ЭлементФормы.УстановитьГраницыВыделения(НачальнаяСтрокаИлиПозиция, НачальнаяКолонкаИлиКонечнаяПозиция, КонечнаяСтрока, КонечнаяКолонка);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1296)}:	ПолеТекста.УстановитьГраницыВыделения(ПерваяСтрока, 1, ПоследняяСтрока, ДлинаПоследнейСтроки);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1232)}:	ЗаменитьФрагментТекстаВПоле(ПолеТекста, ВыделенныйФрагмент, ДлинаПоследнейСтроки, ПерваяСтрока, ПоследняяСтрока, ПоследняяКолонка);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(940)}:			Закомментировать();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(891)}:	Результат = ВыполнитьКоманду(Команда);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(284)}:		Результат = ЭкземплярКомпоненты.Нажатие(Кнопка);
по причине:
Недопустимое значение параметра (параметр номер '4')

```

**Comment by tormozit** [comment]
какая то беда с форматированием инфо для тех. поддержки

**Comment by PerlAmutor** [comment]
> какая то беда с форматированием инфо для тех. поддержки

Поправил

**Comment by tormozit** [comment]
Не удалось воспроизвести. Нужен файл с текстом запроса.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/931932

**Comment by tormozit** [comment]
Исправлено в 6.04.2
