### ISSUE TITLE
Выгрузка/загрузка данных через файл. Открыть объект в Редакторе объекта БД.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#111]
https://user-images.githubusercontent.com/87958986/134842704-b327474e-46b7-462b-8ae9-483f16266de6.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Выгрузка/загрузка данных через файл
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Выгрузка/загрузка данных через файл"
2. Перешел на вкладку "Выгрузка" или "Загрузка" (ошибка на обеих вкладках)
3. Вызвал команду "Открыть объект в Редакторе объекта БД"
3. Получил окно с ошибкой:
```

{Форма.Форма.Форма(135)}: Поле объекта не обнаружено (РезультатЗагрузки)
	ТекущаяСтрока = ЭлементыФормы.РезультатЗагрузки.ТекущаяСтрока;
```

**Ожидаемое поведение**
Отстутствие реакции

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934613

**Comment by tormozit** [comment]
Исправлено в 6.12.1
