### ISSUE TITLE
Поиск битых ссылок. Конструктор запросов ИР. Загадочное окно.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#112]
https://user-images.githubusercontent.com/87958986/134939230-3d86a7e8-9362-4182-a773-00310545fc40.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Поиск битых ссылок
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Поиск битых ссылок"
2. Нажал кнопку " \ Командная панель \ Исполняемый запрос"
3. Нажал кнопку "Конструктор запросов ИР.
4. Получил окно:

![image](https://user-images.githubusercontent.com/87958986/134939301-76a9288c-8725-4102-bcc4-96d901dac234.png)

**Ожидаемое поведение**
Отсутствие такого окна

**Comment by tormozit** [comment]
Проблему воспроизвел https://www.hostedredmine.com/issues/934714

**Comment by tormozit** [comment]
Исправлено в 6.12.1
