### ISSUE TITLE
Поиск битых ссылок. Только регистраторы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#113]
https://user-images.githubusercontent.com/87958986/134939953-0c025f9f-18e5-4cf8-8209-bb24c80ebc7f.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Поиск битых ссылок
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Поиск битых ссылок"
2. Установил флажок "Только регистраторы"
3. Нажал кнопку " \ Командная панель \ Исполняемый запрос"
4. Получил окно с ошибкой:

`{ВнешняяОбработка.ирКонсольЗапросов.МодульОбъекта(61)}: Ошибка при вызове метода контекста (НайтиПараметры): {(1, 1)}: Ожидается выражение "ВЫБРАТЬ"`

В конфигурации "Конвертация данных 2.1" в принципе отсутствуют документы, видимо это связано с этим.

**Ожидаемое поведение**
Открытие текста запроса только с регистраторами?

**Comment by tormozit** [comment]
Ошибку воспроизвел. Консоль запросов в  этом случае открываться не должна.

**Comment by tormozit** [comment]
Исправлено в 6.12.1
