### ISSUE TITLE
Конструктор запросов ИР. Отбор

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#114]
https://user-images.githubusercontent.com/87958986/134946351-a1dd8911-0c7a-4bec-b179-7ff098142f47.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Вставил текст запроса:

```
ВЫБРАТЬ ПЕРВЫЕ 10
*
ИЗ
	РегистрНакопления.СебестоимостьТоваров КАК СебестоимостьТоваров
```

3. Вызвал Конструктор запросов ИР
4. Перешел на вкладку "Отбор", щелкнул 2 раза по "Отбор"
3. Получил окно с ошибкой:

```
Поле объекта не обнаружено (Представление)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(8803)}:	Если ВыбраннаяСтрока.Представление = "" Тогда
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2759)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(930)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(891)}:	Результат = ВыполнитьКоманду(Команда);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(284)}:		Результат = ЭкземплярКомпоненты.Нажатие(Кнопка);
```

**Ожидаемое поведение**
Отсутствие реакции.

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.12.1
