### ISSUE TITLE
Конструктор запросов ИР. ЕСТЬ NULL

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#115]
https://user-images.githubusercontent.com/87958986/134947153-625e20c3-dc07-4b2d-8571-b5373732c7e8.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Вставил текст запроса:

```
ВЫБРАТЬ ПЕРВЫЕ 10
*
ИЗ
	РегистрНакопления.СебестоимостьТоваров КАК СебестоимостьТоваров
```

3. Вызвал Конструктор запросов ИР
4. Перешел на вкладку "Отбор"
5. Вызвал команду "ЕСТЬ NULL"
6. Получил окно с ошибкой:

```
{Форма.КонструкторЗапроса.Форма(11463)}: Поле объекта не обнаружено (Представление)
	Если ЗначениеЗаполнено(ТекущаяСтрока.Представление) Тогда
```

**Ожидаемое поведение**
Отсутствие реакции.

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.12.1
