### ISSUE TITLE
Исследователь объектов. XML, XDTO, XDTO+, Внутр, Показать циклически ссылки внутри значения

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#116]
https://user-images.githubusercontent.com/87958986/134948178-735bd047-a6a5-4ea7-b006-d21d0e132cbf.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Исследователь объектов
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Исследователь объектов"
2. Нажал кнопку "XML" / "XDTO" / "XDTO+" / "Внутр" / "Показать циклически ссылки внутри значения"
3. Получил окно с ошибкой:

```
{Форма.ИсследовательОбъектов.Форма(731)}: Значение не является значением объектного типа (Значение)
	Значение = ЭтаФорма.ЭлементыФормы.ДеревоЗначений.ТекущаяСтрока.Значение;

```

**Ожидаемое поведение**
Отсутствие реакции

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.12.1
