### ISSUE TITLE
Конструктор регулярного выражения. Исполняемый файл RegexBuddy

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#117]
https://user-images.githubusercontent.com/87958986/134950557-df45a69c-ea64-4619-813b-d39b53b1f3a6.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Конструктор регулярного выражения
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Конструктор регулярного выражения"
2. Нажал кнопку " \ Командная панель \ Настройки"
3. Закрыл основную панель ИР
4. Ввел произвольные символы в оставшийся диалог
5. Нажал ОК
6. Получил окно с ошибкой:

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(29107)}: Значение не является значением объектного типа (ИмяПродукта)
			ХранилищеОбщихНастроек.Сохранить(ирКэш.ИмяПродукта(), КлючНастроек, Значение,, ИмяПользователя);

```

**Ожидаемое поведение**
Закрытие дочернего диалога вслед за родительской формой

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.12.1
