### ISSUE TITLE
Конструктор регулярного выражения. Вынести в параметр. Падение платформы

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#118]
https://user-images.githubusercontent.com/87958986/134951617-0def5376-d866-418a-8e62-1e41ee83ad3d.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Конструктор регулярного выражения
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Конструктор регулярного выражения"
2. Выбрал элемент "Начало строки" (^)
3. Нажал "Вынести в параметры"
4. Выбрал "Да"
5. Получил окно с ошибкой падения платформы

**Ожидаемое поведение**
Отсутствие падения платформы

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934715

**Comment by tormozit** [comment]
Исправлено в 6.12.1
