### ISSUE TITLE
Конструктор регулярного выражения. Операции сравнения на больше-меньше допустимы только для значений совпадающих примитивных типов

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#119]
https://user-images.githubusercontent.com/87958986/134953093-87f095c1-d88c-4feb-9bbd-475bd81f24d4.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Конструктор регулярного выражения
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Конструктор регулярного выражения"
2. Выбрал "Начало текста" (^)
3. Перешел на вкладку "Варианты"
4. Добавил вторую строку
5. Выставил флажок "Список"
6. Выбрал другую строку на вкладке "Варианты"
7. Выставил снова флажок "Список"
8. Выбрал первую строку
9. Получил окно с ошибкой:

```
Операции сравнения на больше-меньше допустимы только для значений совпадающих примитивных типов (Булево, Число, Строка, Дата)
{ВнешняяОбработка.ирКонструкторРегулярногоВыражения.Форма.Форма.Форма(1097)}:	Для ИндексРодителя = СтрокиПараметров.Найти(ТекущаяСтрока) По СтрокиПараметров.Количество() - 1 Цикл
{ВнешняяОбработка.ирКонструкторРегулярногоВыражения.Форма.Форма.Форма(1978)}:			РазвернутоеВыражениеВложенное = РазвернутоеВыражение(СтрокаПараметраСоСписком);
{ВнешняяОбработка.ирКонструкторРегулярногоВыражения.Форма.Форма.Форма(858)}:		Вхождения = ВычислитьВхождения();
{ВнешняяОбработка.ирКонструкторРегулярногоВыражения.Форма.Форма.Форма(744)}:		ОбновитьПроверочныйТекст();
{ВнешняяОбработка.ирКонструкторРегулярногоВыражения.Форма.Форма.Форма(700)}:	ОбновитьВыражениеПараметра();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(4964)}:			Переменная = Значение;
{ВнешняяОбработка.ирКонструкторРегулярногоВыражения.Форма.Форма.Форма(722)}:	ирОбщий.ПрисвоитьЕслиНеРавноЛкс(ЭлементыФормы.Параметры.ТекущаяСтрока, ЭлементыФормы.Варианты.ТекущаяСтрока);

```

**Ожидаемое поведение**
Отсутствие подобной ошибки

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934663

**Comment by tormozit** [comment]
Исправлено в 6.12.1
