### ISSUE TITLE
Консоль запросов. Временная таблица уже существует "_Т"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#12]
https://user-images.githubusercontent.com/87958986/129451216-2993cd63-2495-4fd1-b9c0-d5cfac629962.mp4

[_T.zip](https://github.com/tormozit/RDT1C/files/6986724/_T.zip)

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.04.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

При отложенной отладке запроса возникает ошибка:

`{ВнешняяОбработка.ирОбщий.МодульОбъекта(20840)}: Ошибка при вызове метода контекста (Выполнить): {(2, 23)}: Временная таблица уже существует "_Т"`

Запрос и файл отладки прикрепил.

**Comment by tormozit** [comment]
Проблему воспроизвел https://www.hostedredmine.com/issues/932012

**Comment by tormozit** [comment]
Исправлено в 6.04.2
