### ISSUE TITLE
Редактор объекта БД. Пометка удаления. Версия данных.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#121]
https://user-images.githubusercontent.com/87958986/135012228-5c4c3704-bbe3-4ce7-b175-5960a91804d7.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Выбрал документ
3. Нажал кнопку "Пометить на удаление"
4. Получил окно с ошибкой:

`Не удалось установить значение реквизита "ВерсияДанных": {ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1212)}: Object field is not writable (ВерсияДанных)`

**Ожидаемое поведение**
Пометка на удаление / Снятие пометки на удаление

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.12.1
