### ISSUE TITLE
Редактор объекта БД. При отмене проведения остаются движения.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#122]
https://user-images.githubusercontent.com/87958986/135014572-8f1779cf-86c8-4761-bf16-562805b88f19.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Выбрал документ
3. Поставил флажок "Вместе с движениями"
4. Нажал кнопку "Отменить проведение"
5. Нажал кнопку "Перечитать"
6. Получил распроведенный документ с движениями.

**Ожидаемое поведение**
Движения видимо не должны записываться при отмене проведения независимо от того стоит флажок "Вместе с движениями или нет". Если это не так то пользователь должен быть предупрежден об этом.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934662

**Comment by tormozit** [comment]
Исправлено в 6.12.1
