### ISSUE TITLE
Редактор объекта БД. Редактор строки.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#123]
https://user-images.githubusercontent.com/87958986/135127312-fc158e24-cf3e-4e94-a450-73d1c3c887c3.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Выбрал документ
3. Перешел на табличную часть
4. Выбрал запись табличной части
5. Вызвал команду "Редактор строки"
6. Очистил реквизит основной таблицы "Редактора Объекта БД"
7. Вернулся в редактор строки
8. Вызвал "Колонка" или "Строка"
9. Получил окно с ошибкой:

```
Object field not found (ТекущиеДанные)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(36275)}:			ДанныеСтроки = ТабличноеПоле.ТекущиеДанные;
{ВнешняяОбработка.ирПлатформа.Форма.СтрокаТаблицы.Форма(177)}:	ТекущаяСтрокаИсточника = ирОбщий.ДанныеСтрокиТабличногоПоляЛкс(ТабличноеПоле);

```

**Ожидаемое поведение**
Проверка на доступность объекта родителя или закрытие редактора строки вслед за документом.

**Comment by tormozit** [comment]
Ошибку воспроизвел
