### ISSUE TITLE
Редактор объекта БД. Очистка реквизита основной таблицы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#124]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Выбрал документ
3. Нажал кнопку очистки реквизита основной таблицы
4. После долгого зависания получил окно с ошибкой:

```
Таблица БД с именем ".ОбеспечениеМатериаламиИРаботами" не найдена
{ВнешняяОбработка.ирОбщий.МодульОбъекта(13337)}:		ВызватьИсключение "Таблица БД с именем """ + ПолноеИмяТаблицыБД + """ не найдена";
{ВнешняяОбработка.ирОбщий.МодульОбъекта(12559)}:	ТекстЗапроса = ПолучитьТекстЗапросаПолейТаблицыБДЛкс(ПолноеИмяТаблицыБД, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(12363)}:	ТаблицаРезультата = ПустаяТаблицаЗначенийИзТаблицыБДЛкс(ПолноеИмяТаблицыБД, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирКэш.МодульОбъекта(68)}:	Результат = ирОбщий.ПоляТаблицыБДЛкс(ПолноеИмяТаблицыБД, _ВызыватьИсключениеПриОтсутствииПрав, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3747)}:	ПоляТаблицыБД = ирКэш.ПоляТаблицыБДЛкс(ИмяТаблицыБД);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3738)}:	ОформитьЯчейкиПоМетаданным(Элемент, ИмяТаблицыБД, ОформлениеСтроки, Кнопки.Идентификаторы);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(5246)}:		ЭлементыФормы.ПанельТабличныеЧасти.Страницы.Удалить(ЭлементыФормы.ПанельТабличныеЧасти.Страницы["Страница" + СтрокаТаблицы.ИмяСтраницы]);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3153)}:	СохранитьНастройкиВсехТаблиц();

```
Ошибку повторно воспроизвести не удается. Она плавающая.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934685

**Comment by tormozit** [comment]
Исправлено в 6.12.1
