### ISSUE TITLE
Связанный динамический список. Связанный редактор объекта.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#125]
https://user-images.githubusercontent.com/87958986/135196966-740dfe48-b105-43b3-8855-7c05a1e07f09.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.2p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Интерфейсная панель"
2. Обновил статистику по количеству объектов
3. Выбрал документ
4. Нажал "Связанный динамический список"
5. Нажал "Связанный редактор объекта"
6. Получил окно с ошибкой:

```
Object field not found (ТабличнаяЧасть_Начисления)
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3633)}:	ТабличноеПолеДинамическойТаблицы = ЭлементыФормы[ИмяТабличногоПоля];
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3575)}:			ОбновитьЗаголовкиКолонокДинамическойТаблицы(фОбъект.мПолноеИмяМД + "." + ИмяТЧ, фОбъект.мПрефиксИмениТабличногоПоляТЧ + ИмяТЧ);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(17)}:	ИмяСинонимПриИзменении();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(25024)}:		ЭтаФорма.ЗагрузитьНастройкуВФорме(НастройкаФормы, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(25001)}:	ЗагрузитьНастройкуФормыЧерезОбработчикЛкс(ЭтаФорма, НастройкаФормы, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(24979)}:			ЗагрузитьНастройкуФормыПоУмолчаниюЛкс(ЭтаФорма, Истина, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(973)}:	ирОбщий.СоздатьМенеджерСохраненияНастроекФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(25614)}:		Форма.Открыть(); // В открытой форме платформа при этом тоже выполняет перерисовку табличных текущих страниц панелей формы
{ВнешняяОбработка.ирОбщий.МодульОбъекта(25591)}:	Форма_АктивироватьОткрытьЛкс(ФормаРедактора);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(25554)}:		ОткрытьРедакторОбъектаБДЛкс(ПолноеИмяТаблицы, ИмяКолонки, Связанный, КлючОбъекта, ОбъектыНаСервере, ТабличноеПоле.ТекущиеДанные, ТабличноеПоле.ТекущаяСтрока, ФормаРедактора);
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(586)}:	ирОбщий.ОткрытьТекущуюСтрокуТабличногоПоляТаблицыБДВРедактореОбъектаБДЛкс(ЭлементыФормы.ДинамическийСписок, фОбъект.ПолноеИмяТаблицы,, Истина, мСвязанныйРедакторОбъектаБД,, Ложь);
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(571)}:	ОткрытьСвязанныйРедакторОбъектаБДСтроки();

```
Воспроизводится иногда.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934682

**Comment by tormozit** [comment]
Исправлено в 6.12.1
