### ISSUE TITLE
Список инструментов и общие настройки. Разделитель

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#126]
https://user-images.githubusercontent.com/87958986/135701746-60c1d480-43cd-4d3d-95ac-756a99d278cc.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Обработка.ирПортативный.Форма.ФормаНастроек
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Список инструментов и общие настройки"
2. Выделил "Разделители" через Ctrl
3. Снял флажки видимость командой " \ Панель \ Инструменты \ Командная панель \ Снять видимость"

**Ожидаемое поведение**
Судя по тому, что мышкой и клавиатурой видимость разделителей снять нельзя, то поведение команды отличается от заложенной логики.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934833

**Comment by tormozit** [comment]
Исправлено в 6.12.1
