### ISSUE TITLE
Список инструментов и общие настройки. Информация о подсистеме.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#127]
https://user-images.githubusercontent.com/87958986/135701837-dcb34251-57af-4278-a602-535535a9e43a.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.11.1p
> Инструменты разработчика. Инструмент: Обработка.ирПортативный.Форма.ФормаНастроек
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Список инструментов и общие настройки"
2. Нажал кнопку "О подсистеме"
3. Получил окно с ошибкой:

`Описание инструмента Обработка.ирПортативный.Форма.ФормаНастроек не найдено`

**Ожидаемое поведение**
Если описания инструмента не должно быть, то и ошибки быть не должно.

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.14
