### ISSUE TITLE
Список инструментов и общие настройки. Текст запросов.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#128]
https://user-images.githubusercontent.com/87958986/135702130-a0361d1d-9826-4671-9f79-14802e2b7943.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.2p
> Инструменты разработчика. Инструмент: Обработка.ирПортативный.Форма.ФормаНастроек
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Список инструментов и общие настройки"
2. Нажал кнопку "Поиск по интерфейсам"
3. Нажал кнопки Ctrl+Break для прерывания поиска
4. Получил окно с ошибкой:

```
Значение не является значением объектного типа (ТекстЗапроса)
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(504)}:	КомпонентаТекстаЗапроса = ПолеТекстаПрограммы.ТекстЗапроса;
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(326)}:	ЭкземплярКомпоненты = ПолучитьТекущуюКомпонентуКонтекстнойПодсказки();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(217)}:		РезультатФормы = ФормаНастроек.ОткрытьМодально();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(196)}:		ОткрытьФормуНастроек();
```
После перезапуска ИР, ошибка осталась и продолжила всплывать до перезапуска клиентского приложения

**Ожидаемое поведение**
Прерывание без ошибки.

**Comment by tormozit** [comment]
Опять на твоем видео не видно важной в данном случае части окна - строки состояния.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934832

**Comment by PerlAmutor** [comment]
> Опять на твоем видео не видно важной в данном случае части окна - строки состояния.

У меня видно. Сначала при разворачивании в полноэкранный режим там серый фон снизу, но потом он уходит открывая все содержимое, если мышкой не двигать.

**Comment by tormozit** [comment]
Да. Увидел строку состояния на видео. Просто я там постоянно двигаю мышкой и жму паузу.

**Comment by tormozit** [comment]
Исправлено в 6.12.1
