### ISSUE TITLE
Список инструментов и общие настройки. Фильтр по названию.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#129]
https://user-images.githubusercontent.com/87958986/135702286-fd334124-818a-4bc7-9854-65e5012d73d0.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.2p
> Инструменты разработчика. Инструмент: Обработка.ирПортативный.Форма.ФормаНастроек
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Список инструментов и общие настройки"
2. Нажал ввел фильтр по неизвестному "По наименованию"
3. Нажал кнопку " \ Панель \ Инструменты \ Командная панель \ Открыть"
3. Получил окно с ошибкой:

```
Value is not of object type (ПолноеИмя)
{ВнешняяОбработка.ирПортативный.Форма.ФормаНастроек.Форма(280)}:	ПолноеИмя = ЭлементыФормы.СписокИнструментов.ТекущиеДанные.ПолноеИмя;
{ВнешняяОбработка.ирПортативный.Форма.ФормаНастроек.Форма(339)}:	ОткрытьТекущийИнструмент();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(217)}:		РезультатФормы = ФормаНастроек.ОткрытьМодально();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(196)}:		ОткрытьФормуНастроек();

```

**Ожидаемое поведение**
Отсутствие реакции

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.14
