### ISSUE TITLE
Консоль запросов. Поле не найдено "Т.МоментВремени_ЗначениеДляТипа3463.МоментВремени"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#13]
https://user-images.githubusercontent.com/87958986/129465713-547c2345-dc5f-490e-b1fe-c57fc976d829.mp4

[МоментВремени2.zip](https://github.com/tormozit/RDT1C/files/6987445/2.zip)

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.04.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

При загрузке .deb файла в консоль запросов возникает ошибка:
```
Ошибка восстановления временной таблицы "ВТДвиженияСебестоимостиДляПартийНДС": {ВнешняяОбработка.ирОбщий.МодульОбъекта(20840)}: Ошибка при вызове метода контекста (Выполнить): {(62, 44)}: Поле не найдено "Т.МоментВремени_ЗначениеДляТипа3463.МоментВремени"
ИНАЧЕ Т.МоментВремени_ЗначениеДляТипа3463.<<?>>МоментВремени
```

Я как-то сразу не заметил, что ошибок две, поэтому запрос тот же самый, что и в этой ишузе https://github.com/tormozit/RDT1C/issues/12

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932018

**Comment by tormozit** [comment]
Исправлено в 6.04.2
