### ISSUE TITLE
Список инструментов и общие настройки. Структура формы. Менеджер табличного поля. Дубли

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#130]
https://user-images.githubusercontent.com/87958986/135702634-3bbf6482-8bc9-4d58-b0bb-5028e753aa87.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.2p
> Инструменты разработчика. Инструмент: Обработка.ирПортативный.Форма.ФормаНастроек
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Список инструментов и общие настройки"
2. Вижу 2 одинаковых инструмента в списке "Структура формы" и "Менеджер табличного поля"

![image](https://user-images.githubusercontent.com/87958986/135702720-0cf75145-0c30-4d09-99ec-1813b4d481af.png)

**Ожидаемое поведение**
По одному элементу

**Comment by tormozit** [comment]
Воспроизвести не удалось. Похоже у тебя испортились настройки списка инструментов.
Опиши, если возможно, воспроизведение, начиная с запуска приложения и открытия в нем базовой формы ИР из свеже распакованной папки портативного варианта (без сохраненных настроек).

**Comment by PerlAmutor** [comment]
Распаковал ИР в новую папку. Все настройки из "Хранилища настроек" удалил, клиент перезапустил. Открыл из новой папки.

Так выглядит под пользователем "Администратор (ОрловАВ)":

![image](https://user-images.githubusercontent.com/87958986/135717214-47866d15-5441-4f03-85a6-9d1bf07545da.png)

А так, тот же инструмент из новой папки, но под пользователем "Administrator":

![image](https://user-images.githubusercontent.com/87958986/135717355-7506260f-b97f-4f73-8344-2e9aade0ec9b.png)

Для интереса убил папку кэша базы. Перезапустил. Не помогло. Обрати внимание на разный текст заголовка второй вкладки. В одной месте "Настройки" в другом "Настройки и отладка".

Почему разные заголовки разобрался:
![image](https://user-images.githubusercontent.com/87958986/135718349-6589941b-dddf-4f01-a346-df2ab0b957df.png)

**Comment by PerlAmutor** [comment]
У тебя в макете их тоже по две штуки. Видимо алгоритм перестал группировать данные, т.к. содержимое каких-то полей таблицы значений теперь отличается:

![image](https://user-images.githubusercontent.com/87958986/135719422-0a125b3f-c45b-4519-9b94-361ca99d138c.png)

Похоже нашел причину. В Табличный документ, как оказалось можно засунуть в одну ячейку сразу несколько данных на разных языках:

![image](https://user-images.githubusercontent.com/87958986/135719504-6611871f-5177-4449-82c6-679961aee40e.png)

![image](https://user-images.githubusercontent.com/87958986/135719637-02c81a9b-9cfa-479d-8304-0f03f4469634.png)

Засада при копировании... )

**Comment by tormozit** [comment]
Понятно. Значит я это уже исправил. Но подобные проблемы будут регулярно возникать снова, т.к. в платформе не предусмотрен нейтральный язык и мне приходится нерусские языки вручную обновлять периодически. https://partners.v8.1c.ru/forum/topic/1965918

**Comment by tormozit** [comment]
Исправлено в 6.12.1
