### ISSUE TITLE
Тестирование метаданных. ИгнорируемыеСигнатуры

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#131]
https://user-images.githubusercontent.com/87958986/135702765-cd039055-c6f6-4467-bcab-713d8f393fd4.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.2p
> Инструменты разработчика. Инструмент: Тестирование метаданных
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Тестирование метаданных"
2. Получил окно с ошибкой:

```
Object field is not writable (ИгнорируемыеСигнатуры)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(25066)}:			ЭтаФорма[КлючИЗначение.Ключ] = ЗначениеСвойства;
{ВнешняяОбработка.ирТестированиеМетаданных.Форма.Форма.Форма(14)}:	ирОбщий.ЗагрузитьНастройкуФормыЛкс(ЭтаФорма, НастройкаФормы); 
{ВнешняяОбработка.ирОбщий.МодульОбъекта(25024)}:		ЭтаФорма.ЗагрузитьНастройкуВФорме(НастройкаФормы, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(25001)}:	ЗагрузитьНастройкуФормыЧерезОбработчикЛкс(ЭтаФорма, НастройкаФормы, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(24974)}:		ЗагрузитьНастройкуФормыПоУмолчаниюЛкс(ЭтаФорма, Не ЗагружатьСохранятьНастройкуПоУмолчанию, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирТестированиеМетаданных.Форма.Форма.Форма(816)}:	ирОбщий.СоздатьМенеджерСохраненияНастроекФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(186)}:		Форма.Открыть();
{ВнешняяОбработка.ирПортативный.Форма.ФормаНастроек.Форма(291)}:		БазоваяФорма.ОткрытьИнструмент(ЭлементыФормы.СписокИнструментов.ТекущиеДанные);
{ВнешняяОбработка.ирПортативный.Форма.ФормаНастроек.Форма(273)}:		ОткрытьТекущийИнструмент();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(217)}:		РезультатФормы = ФормаНастроек.ОткрытьМодально();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(196)}:		ОткрытьФормуНастроек();

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934831

**Comment by tormozit** [comment]
Исправлено в 6.12.1
