### ISSUE TITLE
Конструктор запросов ИР. Агрегировать

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#132]
![image](https://user-images.githubusercontent.com/87958986/135738069-d03a1392-e3b0-4423-ae1f-0de0033159ec.png)

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.2p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Конструктор запросов ИР"
2. Выбрал таблицу и все поля
3. Перешел на закладку "Выбор полей"
4. Увидел пустое подменю с пустыми именами команд

**Ожидаемое поведение**
Видимо в английском варианте не заполнены синонимы для команд подменю "Агрегировать":

![image](https://user-images.githubusercontent.com/87958986/135738115-4137d9aa-9f73-4780-afcd-0527acff6f7e.png)

**Comment by tormozit** [comment]
Как я уже писал, нерусские тексты интерфейсов я заполняю периодически https://www.hostedredmine.com/issues/934716 . Способа автоматизировать это я пока не нашел.

**Comment by PerlAmutor** [comment]
Возможности этой штуки ограничены?

![image](https://user-images.githubusercontent.com/87958986/135753637-dffe9a02-f57c-4303-8c34-4f71174855c0.png)

**Comment by tormozit** [comment]
Вопрос непонятен. Ты почти показал на картинке единственный способ относительно быстро копировать тексты между языками. Правильная картинка вот

![изображение](https://user-images.githubusercontent.com/11896251/135758687-7054300a-c37d-448b-a3d9-6e2801d84c9a.png)

Под автоматизацией я подразумевал выполнение этого программно, т.е. без участия пользователя.

**Comment by PerlAmutor** [comment]
Может это поможет. Вроде как бесплатен: https://its.1c.ru/db/metod8dev#content:5173:hdoc

**Comment by tormozit** [comment]
> Может это поможет

Маловероятно. Интересуют скорее готовые решения, чем полуфабрикаты. Тут опять становятся не соразмерны цель и средства ее достижения во всяком случае на текущий момент, когда на не русских языках инструменты используют очень редко. Например соразмерным цели средством мог бы стать параметр пакетного запуска конфигуратора для копирования текстов интерфейса между языками.

**Comment by PerlAmutor** [comment]
Можно конечно написать скрипт на AutoHotKey, но это тоже не соразмерная цель. Ключей для пакетного запуска я не нашел. Зато нашел полезную статью, которая может помочь в переводе текстов интерфейсов (выгрузка и загрузка mxl файлов). https://infostart.ru/1c/articles/328635/

**Comment by tormozit** [comment]
Перевод текстов инструментов на другие языки не планирую. Речь идет исключительно про копирование текстов на другие языки.
