### ISSUE TITLE
Конструктор запросов ИР. Все поля. Агрегировать.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#133]
https://user-images.githubusercontent.com/87958986/135738229-907bbba0-e9e0-4065-975b-86a961f7ca26.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.2p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Конструктор запросов ИР"
2. Выбрал таблицу
3. Установил флажок "Все поля"
4. Перешел на вкладку "Выбор полей"
5. Использовал функцию "Агрегировать"
6. Вернулся на "Выбор таблиц"
7. Снял флажок "Все поля"
8. Перешел на вкладку "Выбор полей"
9. Вызвал команду "Автополе"
3. Получил окно с ошибкой:

```
Value is not of object type (ВсеПоля)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(10453)}:	СтрокаТаблицы.ВсеПоля = Ложь;
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2759)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(930)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(891)}:	Результат = ВыполнитьКоманду(Команда);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(284)}:		Результат = ЭкземплярКомпоненты.Нажатие(Кнопка);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934953

**Comment by tormozit** [comment]
Исправлено в 6.11.3
