### ISSUE TITLE
Конструктор запросов ИР. Копирование полей. Неожиданное поведение

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#134]
https://user-images.githubusercontent.com/87958986/135738757-b3be18d4-f203-4400-8e73-980db8c30a1d.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.11.2p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Конструктор запросов ИР"
2. Выбрал таблицу и одно поле
2. Перешел на вкладку "Выбор полей"
3. Скопировал поле.
4. Выбрал функцию агрегации для нового поля
5. В зависимости от того было ли скопированное поле агрегировано получаю различный результирующий запрос. Иногда просто NULL, а иногда второе поле отсутствует вообще

**Comment by tormozit** [comment]
Ошибки воспроизвел https://www.hostedredmine.com/issues/934954

**Comment by tormozit** [comment]
Исправлено в 6.11.3
