### ISSUE TITLE
Ошибка при открытии "подбор и обработка объектов" при восстановлении сохраненных значений формы.

### ISSUE THREAD

**Issue by MigalAndrew** [tormozit/RDT1C#135]
Платформа: 8.3.18.1289
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия предприятия, редакция 3.0 (3.0.103.12)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.12.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. EF_00_00384800_6 ()
Расширения. EF_00_00381028_9 ()
Расширения. EF_00_00365551 ()
Клиент. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru_RU
Клиент. От имени администратора Windows: Да
Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 14393)

У обработки "подбор и обработка объектов" есть сохраненные значения формы допустим "Основные".
Где стоит отбор по реквизиту справочника со значением какого то перечисления. Если удалить это перечисление из конфигурации и попробовать открыть эту обработку, значения пытаются восстановиться автоматом и обработка падает при восстановлении значений.
До удаления перечисления:
![image](https://user-images.githubusercontent.com/51985559/136201334-bd72e558-9ffb-4a0d-a38f-658c63a1857d.png)
После удаления:
![image](https://user-images.githubusercontent.com/51985559/136201376-7dba4513-d162-47f5-b4cd-b10e8fa1c52f.png)

**Comment by tormozit** [comment]
Нужен текст ошибки

**Comment by MigalAndrew** [comment]
{ВнешняяОбработка.ирОбщий.МодульОбъекта(29060)}: Ошибка при вызове метода контекста (Загрузить)
			Результат = ХранилищеОбщихНастроек.Загрузить(ирКэш.ИмяПродукта(), КлючНастроек,, ИмяПользователя);
по причине:
Ошибка формата объекта настроек
по причине:
Ошибка формата потока
по причине:
Ошибка преобразования данных XDTO:
Значение: НалоговыйАгентНДСБеларусь	Тип: {http://v8.1c.ru/8.1/data/enterprise/current-config}EnumRef.ВидыЦенностей
по причине:
Ошибка отображения типов:
Отображение лексического значения 'НалоговыйАгентНДСБеларусь' в значение типа 'ПеречислениеСсылка.ВидыЦенностей'

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/935176

**Comment by tormozit** [comment]
Исправлено в 6.13.1
