### ISSUE TITLE
Анализ техножурнала. Полное имя.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#136]
https://user-images.githubusercontent.com/87958986/136315797-f1f3e363-f58e-43db-a35e-870ec23cc50f.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.12.1p
> Инструменты разработчика. Инструмент: Анализ техножурнала
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Анализ техножурнала"
2. Нажал кнопку "Загрузить"
3. Кликнул на поле "Строка модуля"
4. Получил окно с ошибкой:

```
Value is not of object type (ПолноеИмя)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(37908)}:		ОписаниеМодуля.ИмяФайлаМодуля = ОписаниеМодуля.Метаданные.ПолноеИмя() + "." + ТипМодуля;
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(3111)}:	ОписаниеМодуля = ирОбщий.ОписаниеМодуляПоИмениЛкс(ИмяМодуля);
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(1483)}:		СтрокаСтека.Метод = мПлатформа.НайтиИмяМетодаСтрокиМодуля(СтрокаСтека.Модуль, СтрокаСтека.НомерСтроки, СтрокаСтека.СтрокаМодуля);
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(1444)}:			ОбновитьТаблицуКонтекста(ЗначениеПоля);
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(1416)}:	ОбновитьТекущуюСтраницуПанелиЭлемента();

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/935177

**Comment by tormozit** [comment]
Исправлено в 6.13.1
