### ISSUE TITLE
Таблица значений. Число(0,0)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#137]
https://user-images.githubusercontent.com/87958986/136436668-a4724320-dccf-4f0f-8745-afd272c6ed7b.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.12.1p
> Инструменты разработчика. Инструмент: Таблица значений
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: en
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Таблица значений"
2. Добавил поле с типом Число(0,0)
3. Попытался ввести число "0.5". Вместо "0.5" получилось 5. Если вводить целые числа до запятой, то все работает нормально. Числа меньше 1 вводятся только через калькулятор.

**Ожидаемое поведение**
Возможность ввода числе меньше 1, т.к. Число(0,0) в терминах SQL сервера преобразуется в 38,9.

**Comment by tormozit** [comment]
Это - ошибка платформы 8.3 (в 8.2 ее нет) у поля ввода в табличном поле обычной формы (похожая тема https://partners.v8.1c.ru/forum/topic/779816 ). Насколько я помню, ее уже регистрировали, но исправлять видимо уже не будут. На прикладном уровне повлиять на это нельзя.
Такую колонку кстати нельзя создать редактором типа в конфигураторе, а можно только программно.
Способ обхода 1 - вводи ненулевую целую часть с дробной частью и затем заменяй целую часть на ноль.
Способ обхода 2 - задай квалификатор.
Непонятно, зачем ты упомянул SQL сервер. Таблица значений - чисто 1Сный объект и не связан с типами СУБД.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/935332 . Но исправлять ее можно только в платформе. В 1С отправил.

**Comment by tormozit** [comment]
Ошибку платформы опубликовали https://bugboard.v8.1c.ru/error/000115314 . Вероятно ее таки исправят в обозримом будущем.

**Comment by tormozit** [comment]
Исправлено в платформе 8.3.21
