### ISSUE TITLE
Анализ техножуранала. План запросов.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#138]
https://user-images.githubusercontent.com/87958986/136728403-84de876d-30be-49f9-b83f-b3ab2f2cc4c3.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.13.1p
> Инструменты разработчика. Инструмент: Анализ техножурнала
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Анализ техножурнала"
2. Загрузил лог ТЖ.
3. Выбрал события DMSSQL
4. Нажал 2 раза мышкой на значение ячейки "План СУБД"
5. В открывшейся форме нажал стрелочку "Вниз"
6. Получил окно с ошибкой:

```
Object method not found (Индекс)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10427)}:		Позиция = ТабличноеПоле.Значение.Индекс(ВыделеннаяСтрока);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(38302)}:				ТабличноеПолеСдвинутьВыделенныеСтрокиЛкс(ИсточникДействий, +1);
{ВнешняяОбработка.ирАнализТехножурнала.Форма.ПланЗапросаMSSQL.Форма(174)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);

```

**Comment by tormozit** [comment]
Ошибку подтверждаю

**Comment by tormozit** [comment]
Исправлено в 6.24
