### ISSUE TITLE
Анализ техножурнала. Конвертор текста БД.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#139]
https://user-images.githubusercontent.com/87958986/136728718-433f0d12-4328-4702-8107-0e79844d7f12.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.13.1p
> Инструменты разработчика. Инструмент: Анализ техножурнала
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Анализ техножурнала"
2. Загрузил лог ТЖ
3. Выбрал событие DMSSQL
4. Два раза кликнул на значение поля "Текст СУБД"
5. Открылась форма "Конвертор текста СУБД"
6. Перешел на вкладку "Параметры"
7. Два раза кликнул на значение поля "Значение 1С"
8. Получил окно с ошибкой:

```
Object field not found (Значение)
{ВнешняяОбработка.ирАнализТехножурнала.Форма.КонверторТекстаСУБД.Форма(110)}:	Если Колонка = Элемент.Колонки.Значение И ЗначениеЗаполнено(ВыбраннаяСтрока.Метаданные) Тогда

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/936100

**Comment by tormozit** [comment]
Исправлено в 6.14
