### ISSUE TITLE
Консоль кода. Не происходит выход из ИР

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#14]
https://user-images.githubusercontent.com/87958986/129465916-ebd0c22d-3b48-4e2f-953f-b91255cbc93f.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.04.1p
> Инструменты разработчика. Инструмент: Консоль кода
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

При открытом окне подсказки ввода не происходит выхода из ИР.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932015

**Comment by tormozit** [comment]
Исправлено в 6.05.1
