### ISSUE TITLE
Динамический список. Две картинки.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#140]
https://user-images.githubusercontent.com/87958986/136729692-5cd192f2-7b11-4fff-b78b-b6b183d3f5ca.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.13.1p
> Инструменты разработчика. Инструмент: Динамический список
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Динамический список"
2. Выбрал таблицу документов
3. На форме списка обнаружил 2 картинки "Проведен"

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.14
