### ISSUE TITLE
Редактор пользователей БД. Анализ прав доступа

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#141]
https://user-images.githubusercontent.com/87958986/136730101-64c31184-9dca-4ee3-8af3-0298524cf88c.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.13.1p
> Инструменты разработчика. Инструмент: Редактор пользователей
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор пользователей БД"
2. Два раза кликнул на выбранного пользователя
3. Нажал кнопку "Анализ прав доступа"
3. Получил окно с ошибкой:

```
Object field not found (Роль)
{ВнешняяОбработка.ирРедакторПользователей.Форма.ПользовательИнфобазы.Форма(497)}:	ФормаОтчета.Роль = ЭлементыФормы.РолиПользователя.ТекущаяСтрока.Роль;

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/935533

**Comment by tormozit** [comment]
Исправлено в 6.14
