### ISSUE TITLE
В "Удаление объектов с контролем ссылок" команда "В кандидаты" тормозит при большом числе ссылок на кандидаты

### ISSUE THREAD

**Issue by VGHOST** [tormozit/RDT1C#142]
Доброго дня.

Проблема в множественном копировании упомянутого списка и его перезагрузке в форму в конце из-за ненужной смены позиции в списке кандидатов.
Во вложении подправленная версия на основе "ИР Портативный 1С 8.2+ V6.13.1p". Изменения помечены "MOD#".
Также исправлен мелкий баг - ненужная перезагрузка ссылок при интерактивном изменении текущего кандидата, когда фильтр по кандидату отключен - при 250к ссылок это почти смертельно.

ЗЫ:
Через час пришлось вспоминать где у компа Reset, потому как 1С выжрал всю оперативу и перестал даже прерывания отрабатывать.))
Вообще, не плохо бы её отпрофилировать, при удалении организации в хорошо наполненной базе, например. Меня, к сожалению, хватило только на точечную правку...

[ирУдалениеОбъектовСКонтролемСсылок+.zip](https://github.com/tormozit/RDT1C/files/7337613/%2B.zip)

**Comment by VGHOST** [comment]
Переоптимизировал колонку "Есть в кандидатах"...
Лучше так:

```
ДобавитьМассивОбъектовВУдаляемыеОбъекты()
...
	//MOD#F: Для Каждого Объект Из МассивОбъектов Цикл
	НеМассив = ТипЗнч(МассивОбъектов) <> Тип("Массив"); // передана коллекция строк ТЧ СсылкиНаКандидата
	Для Каждого Строка Из МассивОбъектов Цикл
		Объект = ?(НеМассив, Строка.Данные, Строка);
			
	//EOM#F:
		Если ирОбщий.ЛиТипСсылкиБДЛкс(ТипЗнч(Объект)) Тогда
			СтрокаОбъекта = ТаблицаОбъектов.Добавить();
			СтрокаОбъекта.Ссылка = Объект;
			Если СтрокаОбъекта.Ссылка <> Объект Тогда
				// Это тип из расширения конфигурации http://www.hostedredmine.com/issues/886337
				ТаблицаОбъектов.Удалить(СтрокаОбъекта);
			ИначеЕсли НеМассив Тогда//MOD#F+
				Строка.ЕстьВКандидатах = Истина;//MOD#F+
			КонецЕсли; 
		КонецЕсли; 
	КонецЦикла;
```
Не тестил, комп до ночи будет ссылки проверять.

**Comment by tormozit** [comment]
Желательно предоставить замер производительности в виде файла pff и информацию для тех. поддержки.

**Comment by tormozit** [comment]
В целом я принял твои правки. Спасибо за ценные замечания.
https://www.hostedredmine.com/issues/935587
https://www.hostedredmine.com/issues/935589

**Comment by VGHOST** [comment]
Благодарю. И за оперативность тоже))

**Comment by tormozit** [comment]
Реализовано в 6.14

**Comment by tormozit** [comment]
Как стало теперь?

**Comment by VGHOST** [comment]
Ну, на натуре не проверял - такая натура к счастью редко попадается.
Базу обрабатывал моим вариантом, производительность была приемлемой.
С твоей реализацией 2 существенных расхождения:

1. Зачем оставил бессмысленное обновление ссылок на кандидата при выводе ссылок на всех?
```
Процедура УдаляемыеОбъектыПриАктивизацииСтроки(Элемент)
	ирОбщий.ТабличноеПолеПриАктивизацииСтрокиЛкс(ЭтаФорма, Элемент);
	Если ОтборПоТекущемуКандидату Тогда вПоказатьСсылкиНаУдаляемыйОбъект() КонецЕсли;//MOD#B: вПоказатьСсылкиНаУдаляемыйОбъект() // Дико тормозит при смене строк при большом числе ссылок!!!
КонецПроцедуры
```

2. Не могу согласиться с выносом обновления ЕстьВКандидиатах из ДобавитьМассивОбъектовВУдаляемыеОбъекты(). Типа унификация, но при большом массиве помеченных или кандидатов повторный перебор выделенных вполне может задвоить время обработки. ИМХО, достаточно пометить этот момент в описании ДобавитьМассивОбъектовВУдаляемыеОбъекты(), да и так понятно, что при передаче массива значений одной колонки модификация остальных невозможна и нужен внешний код либо колонки ЕстьВКандидиатах в исходных данных вообще нет.
```
Процедура КП_СсылкиНаУдаляемыеОбъектыДобавитьВКандидаты(Кнопка)
	
	ДобавитьМассивОбъектовВУдаляемыеОбъекты(ЭлементыФормы.СсылкиНаКандидата.ВыделенныеСтроки, ЭтаФорма,, Истина);
	Для Каждого ВыбраннаяСтрока Из ЭлементыФормы.СсылкиНаКандидата.ВыделенныеСтроки Цикл
		ОбновитьПризнакЕстьВКандидиатахСсылкиНаКандидата(ВыбраннаяСтрока);
	КонецЦикла;
	
КонецПроцедуры
```

**Comment by tormozit** [comment]
1. Согласен. Упустил эту правку. https://www.hostedredmine.com/issues/936876
2. Несколько раз перечитал, но не смог до конца понять, что ты предлагаешь. Обновление признака ЕстьВКандидиатах необходимо в обоих местах, где оно вызывается сейчас.

**Comment by VGHOST** [comment]
2. Цикл:
```
	Для Каждого ВыбраннаяСтрока Из ЭлементыФормы.СсылкиНаКандидата.ВыделенныеСтроки Цикл
		ОбновитьПризнакЕстьВКандидиатахСсылкиНаКандидата(ВыбраннаяСтрока);
	КонецЦикла;
```
в моем варианте выглядит как
```
			ИначеЕсли НеМассив Тогда
				Строка.ЕстьВКандидатах = Истина;

```
в коде ДобавитьМассивОбъектовВУдаляемыеОбъекты(), который и так перебирает выделенные ссылки, да к тому же там нет необходимости искать по списку кандидатов, так как кандидат только что добавлен. Смотри сообщение от 13.10.2021 16:56GMT+4.

**Comment by tormozit** [comment]
Теперь понял. Да, я в этом месте предпочитаю оставить текущий вариант. Он конечно более затратный чем предложенный тобой, но и более гибкий, т.е. я могу в ДобавитьМассивОбъектовВУдаляемыеОбъекты() поменять логику фильтрации добавления кандидатов и не бояться, что сломается обновление связанного признака.

**Comment by VGHOST** [comment]
Так и подумал. Хотя, строчка комментария к ДобавитьМассивОбъектовВУдаляемыеОбъекты() могла бы решить эту страшную проблему без потери производительности ))
