### ISSUE TITLE
Отладка обработок БСП Ошибка при открытии

### ISSUE THREAD

**Issue by progromaking** [tormozit/RDT1C#143]
Захожу Подсистема Инструменты разработчика - Отладка внешних обработк БСП
Сразу ошибка

Индекс находится за границами массива
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(37271)}:	Если Истина
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(39782)}:		Форма = ПолучитьФормуЛкс(ПолноеИмяФормы, Параметры, Владелец, Уникальность, Окно);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(39629)}:	ОткрытьФормуЛкс("ОбщаяФорма.ирОтладкаВнешнихОбработокБСП");
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Команда.ОткрытьОтладкаВнешнихОбработокБСП.МодульКоманды(5)}:	ирОбщий.ОткрытьОтладкаВнешнихОбработокБСПЛкс();

В переменную ПолноеИямФормы приходит "ОбщаяФорма.ирОтладкаВнешнихОбработокБСП"
А в условии идет обращение по индексу: Фрагменты[2]

Версия Конфигурация 6.13.1e (та же ошибка на 6.11.2е. Но в 6.09.1е ошибки не было)
Конфигурация ЕРП 2.4
Режим запуска Толстый клиент управляемое приложение

**Comment by tormozit** [comment]
https://www.hostedredmine.com/issues/935552

**Comment by tormozit** [comment]
исправлено в 6.13.2
