### ISSUE TITLE
Редактор ограничения доступа. Порядок параметров

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#144]
https://user-images.githubusercontent.com/87958986/137778595-8de14a84-9afb-42fa-a3d2-1b066e3d5040.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.14.1p
> Инструменты разработчика. Инструмент: Редактор ограничения доступа
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор ограничения доступа"
2. Обновил кэш ролей
3. Выбрал роль "ДобавлениеИзменениеРеализацийТоваровУслуг"
4. Выбрал шаблон "ПоЗначениям"
5. В табличной части "Параметры" вижу некорректную сортировку, которая выполняется лексикографически. Видимо из-за того, что значение номера параметра - строковый тип.

**Ожидаемое поведение**
Сортировка порядка параметров от 1 до 35 в порядке возрастания.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/936137

**Comment by tormozit** [comment]
Исправлено в 6.15
