### ISSUE TITLE
Редактор ограничений доступа. Выбор ролей

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#146]
В "Редакторе ограничения доступа" крайне тяжело найти необходимую роль, если их слишком много. Отсутствуют какие-либо инструменты поиска или отбора. Приходится искать глазами.

https://user-images.githubusercontent.com/87958986/137781617-9204cfe4-5bb6-4d0f-b395-5f98da432e60.mp4

Нашел пока только такой "необычный" способ:

https://user-images.githubusercontent.com/87958986/137782197-a833025d-97af-40a1-862d-7722c9857b7f.mp4

**Comment by tormozit** [comment]
Пока не работает поиска по колонке "Значение" рекомендую использовать поиск по колонке "Представление"

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/936140

**Comment by tormozit** [comment]
Реализовано в 6.15
