### ISSUE TITLE
Ошибка метода ирОбщий.ПерЛкс(ТекстПрограммы?) на сервере

### ISSUE THREAD

**Issue by 9815444** [tormozit/RDT1C#147]
Выполнение функции ирОбщий.ПерЛкс() на сервере вызывает ошибку
{ОбщийМодуль.ирОбщий.Модуль(12136)}: Метод объекта не обнаружен (ИнициализироватьНеинтерактивно)
	ПолеВстроенногоЯзыка.ИнициализироватьНеинтерактивно();
http://joxi.ru/zAN3zQvu1KGMZr

**Comment by 9815444** [comment]
Воспроизводится во всех вариантах поставки Ир

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/936250

**Comment by tormozit** [comment]
Исправлено в 6.15
