### ISSUE TITLE
Ошибка запуска фонового задания в обычном приложении

### ISSUE THREAD

**Issue by Lion-killer** [tormozit/RDT1C#148]
При выполнении метода "ФоновыеЗадания.Выполнить()" на клиенте в обычном приложении, фоновое задание завершается с ошибкой "Неверный формат хранилища данных"

Платформа: 8.3.9.2170
Режим БД: клиент-серверный
Конфигурация. Название: Управление производственным предприятием для Украины, редакция 1.3 (ret.20180820.17.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: НеИспользовать
Конфигурация. Версия БСП: 102
Инструменты разработчика. Версия: Конфигурация 6.14.1
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. ОС: Microsoft Windows Server 2019 Datacenter 64-bit НеРусский-0422
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Microsoft Windows Server 2008 R2 Standard  64-bit НеРусский-0422
Сервер. Процесс: 32б
Сервер. Отладка: http

![image](https://user-images.githubusercontent.com/22013083/139390977-07f819df-24ec-4675-afea-719b8d1fce0b.png)

Неверный формат хранилища данных ''

**Comment by tormozit** [comment]
А причем тут инструменты? Опиши подробнее в каком инструменте с какими настройками какое действие выполняешь.

**Comment by Lion-killer** [comment]
Ошибку удалось повторить на демонстрационной конфигурации:
![image](https://user-images.githubusercontent.com/22013083/139314435-fac0df57-e6ba-425d-9b43-0d50d358219b.png)
![image](https://user-images.githubusercontent.com/22013083/139314488-ef3f8d81-08f1-431d-84d5-a2a3c5e8fdd8.png)
Тестирование выполнялось в клиент-серверном вариант
[Demo839.zip](https://github.com/tormozit/RDT1C/files/7436578/Demo839.zip)

**Comment by Lion-killer** [comment]
> А причем тут инструменты? Опиши подробнее в каком инструменте с какими настройками какое действие выполняешь.

Ошибка проявилась после обновления инструментов при использовании обработки "Консоль заданий":
![image](https://user-images.githubusercontent.com/22013083/139316493-76dc0d20-7698-49e3-8525-7c0467fbdbe8.png)
{Обработка.ирКонсольЗаданий.Форма.ФормаКонсоли.Форма(391)}: Поле объекта не обнаружено (ТаблицаЗаданий)
		ТаблицаЗаданий = РезультатЗапуска.ТаблицаЗаданий;
![image](https://user-images.githubusercontent.com/22013083/139393335-00c58016-81d1-4242-b5bb-13b6d1662c63.png)
А это причина ошибки:
![image](https://user-images.githubusercontent.com/22013083/139317210-bc2a6661-0d1c-485a-b380-c12f7bc1bd96.png)
[ирОбщий_мод.zip](https://github.com/tormozit/RDT1C/files/7436669/_.zip)
Переписал модуль "ирОбщий" и вызываю "ФоновыеЗадания.Выполнить()" принудительно на сервере. В таком виде работает.

**Comment by tormozit** [comment]
Нужен полный текст ошибки и желательно в первом сообщении.

**Comment by Lion-killer** [comment]
> Нужен полный текст ошибки и желательно в первом сообщении.

Дополнил первое сообщение

**Comment by tormozit** [comment]
А, там нет указания строки исходного кода. Теперь понял.
Еще тут https://github.com/tormozit/RDT1C/issues/148#issuecomment-954111455 ты показал ошибку, но без текста.

**Comment by Lion-killer** [comment]
> А, там нет указания строки исходного кода. Теперь понял. Еще тут [#148 (comment)](https://github.com/tormozit/RDT1C/issues/148#issuecomment-954111455) ты показал ошибку, но без текста.

Дополнил комментарий текстом ошибки

**Comment by tormozit** [comment]
Переносить этот код на сервер пока не готов.
Кстати в твоей правке есть обращение к БСП. Поэтому в таком виде оно не подходит.
Пока сделаю наверное для версии платформы 8.3.9 в коде отключение асинхронности (использования фоновых заданий) https://www.hostedredmine.com/issues/936748

**Comment by tormozit** [comment]
Попробуй перезапустить кластер 1С на всякий случай. Может проблема в его испорченном состоянии.
Также ты можешь отключить асихронность, запустив приложение с параметром запуска (/C) - ЗапретитьАсинхронностьИР.

**Comment by Lion-killer** [comment]
> Переносить этот код на сервер пока не готов. Кстати в твоей правке есть обращение к БСП. Поэтому в таком виде оно не подходит. Пока сделаю наверное для версии платформы 8.3.9 в коде отключение асинхронности (использования фоновых заданий) https://www.hostedredmine.com/issues/936748

Фоновое задание все равно выполняется на сервере или я не до конца разобрался в вопросе?

**Comment by Lion-killer** [comment]
> Попробуй перезапустить кластер 1С на всякий случай. Может проблема в его испорченном состоянии. Также ты можешь отключить асихронность, запустив приложение с параметром запуска (/C) - ЗапретитьАсинхронностьИР.

Перезапуск делал и пробовал на разных серверах и в разных базах - специально для этого развернул демку - проблемма скорее всего таки в платформе. С моими правками пока работает нормально. С асинхронными вызовами инструменты все же работают веселее ))

**Comment by tormozit** [comment]
Исправлено в 6.16
