### ISSUE TITLE
Ошибка при открытии ирКонсольЗаданий при существовании зависшего или спящего фонового задания

### ISSUE THREAD

**Issue by Lacoste4life** [tormozit/RDT1C#149]
Платформа: 8.3.17.2306
Режим БД: клиент-серверный
Конфигурация. Название: Управление торговлей, редакция 10.3 (10.3.13.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: АвтоматическийИУправляемый
Конфигурация. Режим совместимости: Версия8_3_6
Инструменты разработчика. Версия: Портативный 6.16.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru_RU
Клиент. От имени администратора Windows: Да

Заметил такую фичу - если существует зависшее фоновое задание, то обработка "Консоль заданий" открывается с ошибкой "Значение не является значением объектного типа (УникальныйИдентификатор)".

Обработка "ирКонсольЗаданий", ФормаКонсоли, строка 110. Лечится простой проверкой:
СтрокаСеанса.ФоновоеЗадание = ?(Сеанс.ПолучитьФоновоеЗадание() <> Неопределено, Сеанс.ПолучитьФоновоеЗадание().УникальныйИдентификатор, "");

**Comment by tormozit** [comment]
Хорошо бы привести полный текст ошибки в начальном сообщении

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/936854

**Comment by Lacoste4life** [comment]
Ошибку завтра попробую найти и обязательно сюда укажу

**Comment by tormozit** [comment]
Исправлено в 6.16.2
