### ISSUE TITLE
Консоль кода. При выходе не закрывается форма настройки компоненты "Поле текста программы"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#15]
https://user-images.githubusercontent.com/87958986/129465972-6242e030-fc54-4a9d-9ac9-917912e3c676.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.04.1p
> Инструменты разработчика. Инструмент: Консоль кода
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

При выполнении кода:

`Сообщить("Тест");`

В консоли кода, в фоне открывается окно настройки "Поле текста программы", если при этом выйти из ИР, то оно автоматически не закрывается, что приводит к ошибкам.

```
Значение не является значением объектного типа (ЛиСеансТолстогоКлиентаЛкс)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(40352)}:	Если ирКэш.ЛиСеансТолстогоКлиентаЛкс() Тогда 
{ВнешняяОбработка.ирОбщий.МодульОбъекта(38978)}:	Если Не ПроверитьЧтоСеансТолстогоКлиентаЛкс() Тогда
{ВнешняяОбработка.ирОбщий.МодульОбъекта(37510)}:		ОткрытьСправкуПоПодсистемеЛкс(ЭтаФорма);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ФормаНастройки.Форма(109)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.05.1
