### ISSUE TITLE
Группировка таблицы. Установка флажка

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#150]
https://user-images.githubusercontent.com/87958986/140466096-a5652ace-f62a-40c4-ba63-8b2fb40480f1.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.16.1e
> Инструменты разработчика. Инструмент: Обработка.ирПлатформа.Форма.ГруппировкаТаблицы
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Асинхронность запрещена: Нет
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.16.1e)
> Расширения. УниверсальныеИнструменты (1.4.11)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: tcp

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Выполнил запрос:

```
ВЫБРАТЬ
	АвансовыйОтчет.Ссылка КАК Ссылка,
	АвансовыйОтчет.Проведен КАК Проведен
ИЗ
	Документ.АвансовыйОтчет КАК АвансовыйОтчет
```

3. Выполнил команду " \ Панель \ Результат-коллекция(6) \ Командная панель \ Группировка таблицы"
4. В секции "Отбор" попытался установить флажок одинарным кликом. Не получилось.

**Ожидаемое поведение**
Установка флажка одинарным кликом

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/937009

**Comment by tormozit** [comment]
Исправлено в 6.17
