### ISSUE TITLE
Конструктор запросов ИР. ЕСТЬ NULL

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#151]
https://user-images.githubusercontent.com/87958986/140469302-ca20f976-f0cc-495a-a828-529e996aac4b.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1C:ERP 2 (Enterprise Resource Management) (2.5.6.261)
> Конфигурация. Основной режим запуска: Managed application
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.16.1p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Yes
> Инструменты разработчика. Объекты на сервере: Yes
> Инструменты разработчика. Серверный модуль: Yes
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Ordinary application 64б
> Клиент. Проверка модальных вызовов: No
> Клиент. Язык интерфейса конфигурации: en
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: No
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Ввел запрос:

```
ВЫБРАТЬ
	Т.Поле1 КАК Поле1
ИЗ
	(ВЫБРАТЬ
		1 КАК Поле1,
		2 КАК Поле2) КАК Т

```

3. Вызвал "Конструктор запросов ИР"
4. Перешел на вкладку "Отбор"
5. Вызвал команду "ЕСТЬ NULL" и ничего не произошло

**Ожидаемое поведение**
Автоматическая установка признака "Произвольное" и измененное условие отбора на текст "Т.Поле1 ЕСТЬ NULL"

**Comment by tormozit** [comment]
https://www.hostedredmine.com/issues/936853

**Comment by tormozit** [comment]
Исправлено в 6.16.2
