### ISSUE TITLE
Не срабатывает трансляция запроса 1С в MS SQL

### ISSUE THREAD

**Issue by progromaking** [tormozit/RDT1C#152]
Конфигурация ЕРП 2.4.13.243
Расширение ИР 6.16.1

Настраиваю Параметры СУБД: Имя сервера, Имя базы, Логин, Пароль, Собирать трассу = Истина
Из Консоли кода ИР вызываю код:
```
Запрос = Новый Запрос("выбрать 1");
Запрос.Выполнить();
```

Получаю ошибку
```
Значение не является значением объектного типа (State)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(28858)}:	Результат = Ложь
{ИнструментыРазработчикаTormozit Обработка.ирАнализТехножурнала.МодульОбъекта(1531)}:		И ирОбщий.ВосстановитьЗначениеЛкс("ирПараметрыСоединенияСУБД.СобиратьТрассу") = Истина
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(495)}:		мАнализТехножурнала.НачатьТрассу("КонсольКода");
{(1)}:КонтекстВыполнения.ВыполнитьЛокально(ТекстДляВыполнения, ЛиСинтаксическийКонтроль)
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(5588)}:		ИнформацияОбОшибке = Вычислить("КонтекстВыполнения." + МетодВыполнения + "(ТекстДляВыполнения, ЛиСинтаксическийКонтроль)");
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2027)}:		мПлатформа.ВыполнитьПрограммныйКодВКонтексте(КонтекстВыполнения, МетодВыполнения, ТекстДляВыполнения);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(957)}:			ВыполнитьПрограммныйКод();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(890)}:	Результат = ВыполнитьКоманду(Команда);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(57)}:	ПолеТекстаАлгоритма.Нажатие(Кнопка);
```

Аналогичную ошибку получаю при попытке выполнить тот же запрос запрос из Консоли запросов ИР.
```
Значение не является значением объектного типа (State)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(28858)}:	Результат = Ложь
{ИнструментыРазработчикаTormozit Обработка.ирАнализТехножурнала.МодульОбъекта(1531)}:		И ирОбщий.ВосстановитьЗначениеЛкс("ирПараметрыСоединенияСУБД.СобиратьТрассу") = Истина
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(2127)}:	мАнализТехножурнала.НачатьТрассу("КонсольЗапросов",, выхДатаНачалаВыполнения);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(1818)}:			ПометитьНачалоВыполненияЗапроса(ДатаНачалаВыполнения);
```

Из обработки  PUBID_1175954-ТрансляторЗапросовИз1СвSQL.epf при тех же настройках СУБД данный запрос выполняется

**Comment by tormozit** [comment]
Ошибки подтверждаю
https://www.hostedredmine.com/issues/937008
https://www.hostedredmine.com/issues/937007

**Comment by tormozit** [comment]
Но эти ошибки являются следствием неуспеха подключения к СУБД. Попробуй в инструменте "Структура хранения БД" включить флажок "Показывать размеры" и проверить корректность подключения к СУБД таким образом.

**Comment by progromaking** [comment]
Попробовал через получить размеры таблиц.
Заполнились колонки размеров таблиц и индексов, а также количества строк.
После этого из консоли кода ставлю галку Собирать трассу. И опять возникает ошибка как в посте

SQL Server 2016 (13.0.5865.1)

**Comment by progromaking** [comment]
Прогнал отладчиком при нажатии кнопки ОК в форме Параметры соединения СУБД (MSSQL):
1. Сначала вызывается функция ирОбщий.ПроверитьСоединениеADOЭтойБДЛкс() в которую передается параметр выхСоединение.
2. Из нее вызывается функция ирСервер.ПроверитьСоединениеADOЭтойБДЛкс(), в которую этот параметр не передается
3. В п.2 снова вызывается ирОбщий.ПроверитьСоединениеADOЭтойБДЛкс(), но туда уже не передается выхСодинение. Однако именно в этот момент в выхСоединение присваивается COM объект.
 
И получается что выхСоединение присваивается, но теряется (не возвращается), т.к. стоит галка На сервере.
Однако если эту галку не ставить, тогда вообще не заходит в метод ирОбщий.ПроверитьСоединениеADOЭтойБДЛкс()

**Comment by progromaking** [comment]
![image](https://user-images.githubusercontent.com/12782277/140617956-0a657702-440a-4ea4-847d-5c5ff10956b5.png)

**Comment by tormozit** [comment]
Если есть возможность подключения с клиента, попробуй отключить флажок "На сервере" в параметрах соединения с СУБД.

**Comment by tormozit** [comment]
Выявил следующую проблему https://www.hostedredmine.com/issues/937007

**Comment by progromaking** [comment]
Пробовал отключать галку На сервере. Но ошибка возникает так же самая в том же месте.

Выполнил поиск где могла бы присваиваться переменная ПроверочноеСоединениеАДО. 
Нашел единственное место: ПроверитьСоединениеADOЭтойБДЛкс(,,,,, Ложь, Истина, мПлатформа.ПроверочноеСоединениеАДО);

Так вот, если отключена галка На сервере, то в эту процедуру код вообще не попадает.
И даже не попадает в ирОбщий.ИнициироватьФормуЛкс(), из которой вызывается ПроверитьСоединениеADOЭтойБДЛкс()

**Comment by tormozit** [comment]
Первые 2 ошибки исправлены в 6.16.2

**Comment by tormozit** [comment]
Последняя ошибка исправлена в 6.17

**Comment by progromaking** [comment]
Проверил на расширении ИР 6.17.1
Ошибки ушли. Удалось собрать трассу как с флагом На сервере, так и без него
