### ISSUE TITLE
Конструктор запросов ИР. Порядок

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#153]
https://user-images.githubusercontent.com/87958986/140679890-df1e72ad-d0bd-44eb-ab3a-ba2019acd79d.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.17.1p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов ИР"
2. Ввел запрос:
```
ВЫБРАТЬ
	АвансовыйОтчет.Ссылка КАК Ссылка,
	АвансовыйОтчет.Проведен КАК Проведен
ИЗ
	Документ.АвансовыйОтчет КАК АвансовыйОтчет
```
3. Открыл инструмент "Конструктор запросов ИР"
4. Перешел на вкладку "Порядок"
5. Нажал кнопку "Добавить" и ничего не происходит. Элементы порядка также не копируются через команду "Копировать". Работает только перетаскивание элементов и добавление по двойному клику.

Похожая ситуация наблюдается также на вкладках "Итоги" и "Построитель"

**Ожидаемое поведение**
Добавление нового произвольного элемента порядка.

**Comment by tormozit** [comment]
По порядку создал задачу https://www.hostedredmine.com/issues/937049 .
По итогам такая возможность кажется будет не полезна, т.к. они проецируются в выбранные поля и потому всегда удобнее добавлять перетаскиванием.

**Comment by tormozit** [comment]
По порядку исправлено в 6.18
