### ISSUE TITLE
Менеджер табличного поля. Элемент Автопорядка

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#154]
**Программное окружение**

https://user-images.githubusercontent.com/87958986/140680956-3c55d404-79b1-4527-9c3c-b8e6665a733f.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.17.1p
> Инструменты разработчика. Инструмент: Менеджер табличного поля
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл "Менеджер табличного поля" в Конструкторе запросов в Параметрах
2. Добавил "Элемент Автопорядка"
3. Вызвал команду "Применить"
4. Получил окно с ошибкой:

```
Поле объекта не обнаружено (Поле)
{ВнешняяОбработка.ирПлатформа.Форма.МенеджерТабличногоПоля.Форма(146)}:		Если ЭлементПорядка.Поле = СтароеТекущееПолеПорядка Тогда
{ВнешняяОбработка.ирПлатформа.Форма.МенеджерТабличногоПоля.Форма(273)}:		НастроитьПостроительОтчета();
{ВнешняяОбработка.ирПлатформа.Форма.МенеджерТабличногоПоля.Форма(579)}:	Если Не УстановитьСвязь() Тогда 
```

Также, если 2 раза кликнуть на поле "Направление сортировки" элемента Автопорядка, то возникает ошибка:

```
Поле объекта не обнаружено (ТипУпорядочивания)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(26659)}:		Если ВыбраннаяСтрока.ТипУпорядочивания = НаправлениеСортировкиКомпоновкиДанных.Возр Тогда
{ВнешняяОбработка.ирПлатформа.Форма.МенеджерТабличногоПоля.Форма(687)}:	ирОбщий.ТабличноеПолеПорядкаКомпоновкиВыборЛкс(Элемент, ВыбраннаяСтрока, Колонка, СтандартнаяОбработка);

```

**Comment by tormozit** [comment]
Ошибки воспроизвел

**Comment by tormozit** [comment]
исправлено в 6.18
