### ISSUE TITLE
Заполнить коллекцию по списку навигационных ссылок.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#155]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.17.1p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Периодически поступают задачи по обработке списка документов, которые присылают в виде навигационных ссылок. Иногда списки довольно большие, 50 документов например.

Хотелось бы иметь возможность добавлять ссылки в коллекции не выбирая каждую отдельно. Например есть список:

```
e1cib/data/Документ.АвансовыйОтчет?ref=92f10050568b35ac11e4f578a813faa2
e1cib/data/Документ.АвансовыйОтчет?ref=92f10050568b35ac11e4ecd091f310ae
e1cib/data/Документ.АвансовыйОтчет?ref=92f10050568b35ac11e4ecd21ff77d60
e1cib/data/Документ.АвансовыйОтчет?ref=92f10050568b35ac11e4f97b98b611b6
e1cib/data/Документ.АвансовыйОтчет?ref=a22cbcaec56cc14411e6ec3ca5a20561
e1cib/data/Документ.АвансовыйОтчет?ref=a22cbcaec56cc14411e6ec3ca5a20563
```
В Консоли Запросов добавляем Параметр с Видом "Список", затем в форме заполнения вызываем команду "Получить->Из текста". Вставляем ссылки, определяем разделитель данных EOL. В этой форме хотелось бы как-нибудь сообщить ИР, что загружаются навигационный ссылки, чтобы произошло автоматическое преобразование того, что возможно.

https://user-images.githubusercontent.com/87958986/140790130-ff3f874a-c9a3-4e54-9d6b-e1c6730cb171.mp4

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/937135

**Comment by tormozit** [comment]
реализовано в 6.18

**Comment by PerlAmutor** [comment]
А как теперь преобразовать навигационные ссылки? Добавлять в поле "Алгоритм" на подобии этого? https://helpf.pro/faq8/view/1469.html

**Comment by tormozit** [comment]
Алгоритм писать не нужно. Преобразование выполняется автоматически.

**Comment by tormozit** [comment]
Получилось?

**Comment by PerlAmutor** [comment]
Да, спасибо!
