### ISSUE TITLE
Анализ техножурнала. Управляемые блокировки. Ссылки.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#156]
https://user-images.githubusercontent.com/87958986/141603130-5a57ae41-81e9-405c-9baa-ffd997afc8fa.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.17.1p
> Инструменты разработчика. Инструмент: Анализ техножурнала
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Анализ техножурнала"
2. Загрузил журнал
3. Перешел на вкладку "Блокировки упр."
4. Открыл одну из записей, где накладываются блокировки на измерения
5. Вижу, что в событии ТЖ есть ссылки на объекты, но во второй сверху справа ТЧ ссылочные поля не заполняются

**Ожидаемое поведение**
Преобразование ссылок, если это возможно, и заполнение "полей мета" с возможностью перехода к объектам
[logs.zip](https://github.com/tormozit/RDT1C/files/7531282/logs.zip)

[bdscheme.zip](https://github.com/tormozit/RDT1C/files/7532125/bdscheme.zip)

**Comment by tormozit** [comment]
Нужна схема БД. Ее нужно выгружать одноименной кнопкой в этом же инструменте.

**Comment by PerlAmutor** [comment]
> Нужна схема БД. Ее нужно выгружать одноименной кнопкой в этом же инструменте.

Прикрепил к первому сообщению.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/937601

**Comment by tormozit** [comment]
исправлено в 6.18
