### ISSUE TITLE
Анализ техножурнала. Найти событие в таблице Журнала.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#157]
https://user-images.githubusercontent.com/87958986/141645527-e7f46d25-ea08-4fc6-b8a2-9cb624e9ef70.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.17.1p
> Инструменты разработчика. Инструмент: Анализ техножурнала
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Анализ техножурнала"
2. Загрузил ТЖ
3. Открыл вкладку "Блокировки упр."
4. Выбрал событие блокировки и открыл двойным кликом.
5. В открывшейся форме вызвал команду "Событие"
6. В открывшейся форме описания события вызвал команду "Найти строку события в таблице журнала"
7. И ничего не произошло.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/937602

**Comment by tormozit** [comment]
исправлено в 6.18
