### ISSUE TITLE
Загрузка табличных данных. Невозможно выбрать контекст выполнения.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#158]
https://user-images.githubusercontent.com/87958986/141719042-ec8d8878-9b74-45cf-a1f6-05416862a10f.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.18.1p
> Инструменты разработчика. Инструмент: Консоль кода
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Добавил параметр вида "Список"
3. Открыл форму списка значений
4. Вызвал команду "Получить из текста"
5. Добавил текст
6. Нажал "ОК"
7. Открылась форма "Загрузка табличных данных"
8. Перешел на вкладку "Конвертация значений"
9. Открыл поле "Алгоритм"
10. Попытался сменить контекст выполнения с Клиент на Сервер, но в меню все элементы не доступные.

**Ожидаемое поведение**
Смена контекста как и в обычной Консоли Кода с возможностью вызова серверных общих модулей.

**Comment by tormozit** [comment]
Консоль кода тут открывается в режиме редактора чужого алгоритма. Поэтому она не может менять контекст выполнения. Контекст выполнения определяется в том инструменте, который будет выполнять алгоритм. В данном случае - "Загрузка табличных данных".
