### ISSUE TITLE
Консоль кода. HTML редактор падение платформы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#159]
https://user-images.githubusercontent.com/87958986/141815308-2c339f0d-acf0-4dc8-aa4a-e6683a06f088.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.18.1e
> Инструменты разработчика. Инструмент: Консоль кода
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Асинхронность запрещена: Нет
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.18.1e)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль кода"
2. Переключился в HTML редактор
3. Начал вводить "Сообщить(ПредопределенноеЗначение("Документ.АвансовыйОтчет."
4. После набора символа точки - платформа падает.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/937635

**Comment by tormozit** [comment]
Исправлено в 6.19
