### ISSUE TITLE
Редактор объекта БД. Мигающее отображение ключей записей регистров.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#16]
https://user-images.githubusercontent.com/87958986/129466247-8dcfdb3d-bbd3-45ec-a633-7a40bdbf0985.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.04.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

В результатах поиска ссылок на объект БД интересным образом меняется представление ключей регистров сведений при активизации строк.

**Comment by tormozit** [comment]
Это задуманное поведение. Так сделано для сильного снижения затрат на перерисовку строк табличного поля. https://www.hostedredmine.com/issues/922850
