### ISSUE TITLE
Подбор и обработка объектов БД. Не меняется тип параметра в произвольном алгоритме.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#160]
https://user-images.githubusercontent.com/87958986/141817415-6c13776d-86f9-4ab9-abaf-213024b1fdea.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.18.1p
> Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Подбор и обработка объектов БД"
2. Сделал отбор по документу
3. Открыл "Произвольный алгоритм"
4. Добавил свой параметр с типом документ ссылка.
5. Тип в поле "Тип значения" так и остался "Строка"

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/938185

**Comment by tormozit** [comment]
Исправлено в 6.21
