### ISSUE TITLE
Общие методы. Перейти в открытый конфигуратор. Опечатка

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#161]
![image](https://user-images.githubusercontent.com/87958986/141818600-a0691919-a125-4064-8e98-2bf4e84048d6.png)

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.18.1p
> Инструменты разработчика. Инструмент: Поле текста программы
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Общие методы" из "Подбор и обработка объектов БД->Произвольный алгоритм"
2. Навел мышкой на команду  "\ Командная панель \ Определение (F12)"
3. Получил подсказку с опечаткой "Перейти в открытый конфтигуратор к определению метода"

![image](https://user-images.githubusercontent.com/87958986/141819011-d72c4a31-9cf2-409a-84a5-671a30a13f26.png)

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.19
