### ISSUE TITLE
Общие методы. Очистка параметра отбора.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#162]
https://user-images.githubusercontent.com/87958986/141819595-e8ae02e9-6977-45fa-a042-6ff6cf69c813.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.18.1p
> Инструменты разработчика. Инструмент: Поле текста программы
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Общие методы"
2. В ТЧ отбора выбрал параметр "Экспорт", два раза кликнул, нажал кнопку Очистки
3. Получил окно с ошибкой:

```
Ошибка при вызове метода контекста (Выполнить)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(20745)}:		МакетКомпоновки = КомпоновщикМакета.Выполнить(СхемаКомпоновки, НастройкаКомпоновки, ДанныеРасшифровки, СвойМакетОформления, ТипГенератора, ПроверятьДоступностьПолей);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(20643)}:	МакетКомпоновки = СобратьМакетКомпоновкиЛкс(СхемаКомпоновки, НастройкаКомпоновки, ВнешниеНаборыДанных, ОтключитьОбщиеИтоги, РежимОтладки, ПроверятьДоступностьПолей, ВыбратьВсеДоступныеПоля);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ОбщиеМетоды.Форма(266)}:	НоваяТаблица = ирОбщий.СкомпоноватьВКоллекциюЗначенийПоСхемеЛкс(СхемаКомпоновки, НастройкаКомпоновки,, СтруктураТаблиц,,,,, РежимОтладки,,,, Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ОбщиеМетоды.Форма(463)}:			ОбновитьДанные();
по причине:
Ошибка компоновки макета
по причине:
Ошибка в элементе отбора: глобальные элементы отбора обязательно должны использовать поля " Содержит Да"
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/937636

**Comment by tormozit** [comment]
Исправлено в 6.19
