### ISSUE TITLE
Подбор и обработка объектов БД. Странное поведение при выстраивание цепочки обработок.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#163]
https://user-images.githubusercontent.com/87958986/141821547-d694563f-4368-4dc8-9bb2-bb3f44fc129c.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.18.1p
> Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Подбор и обработка объектов БД"
2. Перешел к списку обработок
3. Попытался выстроить цепочку обработок командой " \ Панель \ Обработки \ <ДобавитьВВыбранные>" (у которой странная подсказка "Добавить настройку в выбранные обработки")
4. Переносятся лишь некоторые обработки
5. Мышкой возможно перетащить гораздо больше

**Comment by tormozit** [comment]
Перетаскивание срабатывает незапланированно для нескольких типов обработок. Без просмотра параметров их выполнять опасно.
