### ISSUE TITLE
В консоли запросов не заполняется список автоподстановки для значений перечислений

### ISSUE THREAD

**Issue by Tushkan** [tormozit/RDT1C#164]
**Программное окружение**

<details> 
  <summary>Информация для технической поддержки</summary>
Платформа: 8.3.17.1851
Режим БД: клиент-серверный
Конфигурация. Название: Комплексная автоматизация, редакция 1.0 (1.0.12.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_3_5
Инструменты разработчика. Версия: Портативный 6.18.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru_RU
Клиент. От имени администратора Windows: Нет
</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. При нажатии Ctrl+Пробел в список автоподстановки перестали попадать предопределенные значения справочников  и перечислений
![image](https://user-images.githubusercontent.com/213098/141984112-9446204b-c8f7-4cad-adbd-9e3ae17ed4ec.png)

В продолжение проблемы: у меня стоит вызов калькулятора на кнопку NumLock и при открытии окна автоподстановки он стал постоянно показываться. В версии 6.13.1 такого не наблюдалось.
P.S. При закрытом калькуляторе  список автоподставноки так же не заполняется

В версии 6.13.1 - этот функционал работал
![image](https://user-images.githubusercontent.com/213098/141984996-8dc0c951-a596-4c30-904a-45859c1af7cc.png)

**Comment by tormozit** [comment]
По NumLock нужно сделать отдельную заявку.
Прошу поправить переносы строк в "Информация для технической поддержки"

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/937661

**Comment by tormozit** [comment]
Исправлено в 6.18.2

**Comment by Tushkan** [comment]
Проблема не корректного заполнения списка автодополнения устранена
