### ISSUE TITLE
Редактор объекта БД. Поиск ссылок на объект. Различные значения колонок.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#165]
https://user-images.githubusercontent.com/87958986/142016866-a26b2985-e0d9-4099-97a9-46983419664a.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.18.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Выбрал редактируемый документ
3. Перешел на вкладку "Ссылки на объект"
4. Вызвал команду "Найти"
5. Нажал комбинацию клавиш Alt+F (команда "Текущая таблица"->"Различные значения колонок")
6. Получил окно с ошибкой:

```
Значение не является значением объектного типа (ИсточникДействий)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(38579)}:			ИсточникДействий = КоманднаяПанельКнопкиЛкс(ЭтаФорма, Кнопка).ИсточникДействий;
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3884)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка, ТекущееТабличноеПоле());

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/937663

**Comment by tormozit** [comment]
Исправлено в 6.19
