### ISSUE TITLE
Редактор объекта БД. Установить значения колонок. Сортировать

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#166]
https://user-images.githubusercontent.com/87958986/142020591-f0e80daa-c2a1-4076-a056-f14ff3c00e27.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.18.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Вызвал команду " \ Командная панель \ Текущая таблица \ Установить значение в колонке"
3. На вкладке "Менеджера табличного поля." - "Порядок применяемый" выбрал поле "Подсказка"
4. Вызвал команду "Применить"
5. Получил окно с ошибкой:

```
Ошибка при вызове метода контекста (Сортировать)
{ВнешняяОбработка.ирПлатформа.Форма.МенеджерТабличногоПоля.Форма(593)}:				ЗначениеТабличногоПоля.Сортировать(СтрокаПорядка);
по причине:
Недопустимое значение параметра (параметр номер '1')

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/937864

**Comment by tormozit** [comment]
Исправлено в 6.19
