### ISSUE TITLE
Настройка Журнала Регистрации. Управление доступом. Регистр бухгалтерии.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#167]
https://user-images.githubusercontent.com/87958986/142031090-6cf63859-1e62-4920-bf1c-0b39c2da24db.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.18.1p
> Инструменты разработчика. Инструмент: Настройка журнала регистрации
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Настройка Журнала Регистрации"
2. Открыл ветку "Доступ"
3. Вижу, что существует настроенный 1 доступ
4. Однако в форме выбора метаданных отсутствует РегистрБухгалтерии как объект метаданных
5. При попытке добавить через "Плюс" РегистрБухгалтерии выдается ошибка:

`Для объекта метаданных РегистрБухгалтерии.Хозрасчетный невозможна настройка доступа`

6. Тем не менее через этот код возможно настроить доступ к РегистрамБухгалтерии:

```
// Событие Доступ

ОписанияДоступ = Новый Массив;    

ПоляРегистрации = Новый Массив;
ПоляРегистрации.Добавить("Регистратор");

ПоляДоступа = Новый Массив;
ПоляДоступа.Добавить("Сумма");

Доступ = Новый ОписаниеИспользованияСобытияДоступЖурналаРегистрации;
Доступ.Объект = "РегистрБухгалтерии.Хозрасчетный";
Доступ.ПоляРегистрации = ПоляРегистрации;
Доступ.ПоляДоступа = ПоляДоступа;
ОписанияДоступ.Добавить(Доступ);
    
ИспользованиеСобытия = Новый ИспользованиеСобытияЖурналаРегистрации;
ИспользованиеСобытия.Использование = Истина;
ИспользованиеСобытия.ОписаниеИспользования = ОписанияДоступ;

УстановитьИспользованиеСобытияЖурналаРегистрации(
                                            "_$Access$_.Access",
                                            ИспользованиеСобытия);
```
Работа которого подтверждается тем, что при открытии списка проводок в ЖР регистрируются события доступа.

**Ожидаемое поведение**
Возможность настраивать доступы к Регистрам бухгалтерии.

**Comment by tormozit** [comment]
Проблему воспроизвел https://www.hostedredmine.com/issues/939737

**Comment by tormozit** [comment]
Исправлено в 6.23
