### ISSUE TITLE
Не произвольное срабатывание NumLock после выбора автодополнения в Консоли запросов

### ISSUE THREAD

**Issue by Tushkan** [tormozit/RDT1C#168]
**Программное окружение**

<details> 
  <summary>Информация для технической поддержки</summary>

Платформа: 8.3.17.1851
Режим БД: клиент-серверный
Конфигурация. Название: Комплексная автоматизация, редакция 1.0 (1.0.12.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_3_5
Инструменты разработчика. Версия: Портативный 6.18.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
</details>

**Воспроизведение проблемы**
1. Есть калькулятор запускаемый по горячей клавише NumLock [The Calc](http://thecalc.narod.ru/)
2. Открыл "Консоль запросов"
2. По Ctrl+Пробел открывается список автодополнений значения
3. По окончанию выбора происходит открытие калькулятора

**Comment by tormozit** [comment]
Это происходит из-за использования моим кодом функции WinAPI.SendKeys, которая на время выполнения отключает и после выполнения восстановливает состояние всех клавиш-переключателей. Использовать ее мне пришлось после того, как все остальные методы борьбы с ошибками платформы в поле текстового документа обычной формы я перепробовал. Я и сам страдаю из-за этого - у меня экранный индикатор от Logitech SetPoint каждый раз появляется при этом.

**Comment by tormozit** [comment]
Создал задачу на добавление опции отключения этого приема https://www.hostedredmine.com/issues/937865

**Comment by tormozit** [comment]
Опция добавлена в 6.19

**Comment by Tushkan** [comment]
Спасибо. Все работает
