### ISSUE TITLE
Консоль заданий. Ошибка при наличии зависшего фонового задания

### ISSUE THREAD

**Issue by DJRelax** [tormozit/RDT1C#169]
**Программное окружение**

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.18.1563
> Режим БД: клиент-серверный
> Конфигурация. Название: Учет печатной продукции (1.1.21.320)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_3_15
> Инструменты разработчика. Версия: Конфигурация 6.07.1
> Инструменты разработчика. Инструмент: Консоль заданий
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Разрешены имитаторы: Да
> Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: нет

</details>

**Воспроизведение проблемы**
1. При открытии инструмента "Консоль заданий".
2. Получил окно с ошибкой:
```
{Обработка.ирКонсольЗаданий.Форма.ФормаКонсоли.Форма(112)}: Значение не является значением объектного типа (УникальныйИдентификатор)
					СтрокаСеанса.ФоновоеЗадание = Сеанс.ПолучитьФоновоеЗадание().УникальныйИдентификатор;
```
3. Далее инструмент открывается пустым.
4. Анализ выявил что ошибка происходит в сеансе пользователя, у которого зависло фоновое задание.

Задание не удаляется через консоль кластера. Что бы его удалить нужно рестартовать службу кластера, а это не всегда удобно в рабочее время.
Может данную строку кода поместить в Попытку - Исключение.

**Comment by tormozit** [comment]
В актуальной версии проблема исправлена https://www.hostedredmine.com/issues/936854
