### ISSUE TITLE
Редактор объекта БД. Поле объекта не обнаружено "Метаданные"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#17]
https://user-images.githubusercontent.com/87958986/129466409-a5416f97-4517-48d9-81c5-91150da7e740.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.04.1p
> Инструменты разработчика. Инструмент: Консоль кода
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

При двойном клике на любую не редактируемую колонку (кроме "Подсказка" и "Функциональные опции") в инструменте "Редактор объекта БД" появляется ошибка:

```
Поле объекта не обнаружено (Метаданные)
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4107)}:	ИначеЕсли Колонка = ЭлементыФормы.РеквизитыТаблица.Колонки.Метаданные Тогда

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932013

**Comment by tormozit** [comment]
Исправлено в 6.04.2
