### ISSUE TITLE
Невозможно отключить компактный режим.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#171]
https://user-images.githubusercontent.com/87958986/142897200-e7b8609c-ff53-4364-a709-6603bfc2d09d.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.19.1p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
Баг старый.

1. Открыл конфигуратор
2. Запустил отладку "Обычное приложение"
3. Открыл ИР
4. Открылся диалог с рекомендацией перезапуска сеанса, где можно выбрать "Компактный режим"
5. Если выставить флажок "Компактный режим" и запустить Толстый клиент, то открывается УП в компактном режиме
6. Если проделать все те же самые действия с первого пункта, но на второй раз снять флажок "Компактный режим", то он все равно остается навсегда.
7. Лечится ручным удалением настройки через хранилище системных настроек.

**Ожидаемое поведение**
Зачистка настройки компактного режима у пользователя при снятом флажке "Компактный режим"

**Comment by tormozit** [comment]
Похоже подсказку элемента управления ты не читал.
