### ISSUE TITLE
Конструктор запросов ИР. Ломается запрос

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#173]
https://user-images.githubusercontent.com/87958986/144786046-5f8f9c43-36d7-4ce9-b363-a45617ebced4.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.20.1p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Ввел запрос:
```
ВЫБРАТЬ ПЕРВЫЕ 1
	ИСТИНА
ИЗ
	РегистрНакопления.РасчетыСКлиентами КАК Т
ГДЕ
	Т.Сумма ЕСТЬ NULL
	И (Т.Регистратор <> &Документ
				И Т.ОбъектРасчетов = НЕОПРЕДЕЛЕНО
				И Т.СуммаРегл > 0
			ИЛИ ТИПЗНАЧЕНИЯ(Т.ОбъектРасчетов) В (&ТипыПлатежныхДокументов)
				И Т.АналитикаУчетаПоПартнерам.Договор = &Договор
				И Т.АналитикаУчетаПоПартнерам.НаправлениеДеятельности = &НаправлениеДеятельности
				И Т.Валюта = &ВалютаВзаиморасчетов
				И (ТИПЗНАЧЕНИЯ(&ОбъектРасчетов) В (&ТипыНакладных)
					ИЛИ НАЧАЛОПЕРИОДА(ЕСТЬNULL(Т.Период, ДАТАВРЕМЯ(3000, 1, 1)), ДЕНЬ) >= &ДатаДокумента))

```
3. Открыл инструмент "Конструктор запросов ИР"
4. Нажал "ОК" и получил не работоспособный запрос:

```
ВЫБРАТЬ ПЕРВЫЕ 1
	ИСТИНА КАК Поле1
ИЗ
	РегистрНакопления.РасчетыСКлиентами КАК Т
ГДЕ ИСТИНА
	И Т.Сумма ЕСТЬ NULL
	И (ЛОЖЬ
		ИЛИ (ИСТИНА
			И Т.Регистратор <> &Документ
			И Т.ОбъектРасчетов = НЕОПРЕДЕЛЕНО
			И Т.СуммаРегл > 0)
		ИЛИ (ИСТИНА
			И ТИПЗНАЧЕНИЯ(Т.ОбъектРасчетов) В (&ТипыПлатежныхДокументов)
			И Т.АналитикаУчетаПоПартнерам.Договор = &Договор
			И Т.АналитикаУчетаПоПартнерам.НаправлениеДеятельности = &НаправлениеДеятельности
			И Т.Валюта = &ВалютаВзаиморасчетов
			И (ЛОЖЬ
				ИЛИ ТИПЗНАЧЕНИЯ(ПараметрыДанных.ОбъектРасчетов) В (&ТипыНакладных)
				ИЛИ НАЧАЛОПЕРИОДА(ЕСТЬNULL(Т.Период, ДАТАВРЕМЯ(3000, 1, 1)), ДЕНЬ) >= &ДатаДокумента)))

```

**Ожидаемое поведение**
Какая реакция программы ожидалась?

Видимо Конструктор ИР плохо отрабатывает такие условия:

`ТИПЗНАЧЕНИЯ(&ОбъектРасчетов) В (&ТипыНакладных)`

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/938659

**Comment by tormozit** [comment]
Исправлено в 6.21
