### ISSUE TITLE
Консоль запросов. Вывод в таблицу значений.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#174]
https://user-images.githubusercontent.com/87958986/145246896-a9c31085-70fe-46c5-904d-01560ec16cc6.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.21.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Ввел текст запроса:
```
ВЫБРАТЬ
	АвансовыйОтчет.Ссылка КАК Ссылка,
	АвансовыйОтчет.Номер КАК Номер,
	АвансовыйОтчет.Дата КАК Дата
ИЗ
	Документ.АвансовыйОтчет КАК АвансовыйОтчет
```
3. Выполнил. Вызвал команду " \ Панель \ Результат-коллекция(6) \ Командная панель \ Вывести строки"
4. В открывшемся диалоге поставил флажок "Вывод в таблицу значений"
5. Снял флажок с поля "№"
6. Нажал "ОК". Получил ошибку:

```
Поле объекта не обнаружено (НомерСтроки3463)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10455)}:				ОбластьСтроки[Колонка.Имя] = ОформлениеЯчейки.Текст;
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10091)}:			ВывестиСтрокиТабличногоПоляСОформлениемЛкс(КоллекцияСтрок,, Результат, ТабличноеПоле,, ПараметрыВывода.ВстроитьЗначенияВРасшифровки);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(9925)}:	Результат = ВывестиСтрокиТабличногоПоляЛкс(ТабличноеПоле, ФормаНастройки,, выхТекущаяСтрока, НастройкиСписка);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10475)}:	Результат = ВывестиСтрокиТабличногоПоляСНастройкойЛкс(ТабличноеПоле, ВыводБезОформления, НастройкиСписка, ТекущаяСтрока);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(38828)}:				ВывестиСтрокиТабличногоПоляИПоказатьЛкс(ИсточникДействий);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(9629)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/938861

**Comment by tormozit** [comment]
Исправлено в 6.22.1
