### ISSUE TITLE
Тестирование метаданных. Прошу предоставить версию для тестирования релиза.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#175]
Прошу предоставить версию ИР для тестирования доработки: https://www.hostedredmine.com/issues/938924
Как раз есть на чем прогнать (ERP). О найденных ошибках сообщу.

**Comment by tormozit** [comment]
[ИР 6.22.0e.zip](https://github.com/tormozit/RDT1C/files/7714408/6.22.0e.zip)

**Comment by PerlAmutor** [comment]
Спасибо.
Ошибка осталась. Т.е. пока не учитывает флажок "Объекты на сервере" ?


https://user-images.githubusercontent.com/87958986/146128351-061841bd-ce98-49a9-8ad6-640cac3a2b67.mp4

**Comment by tormozit** [comment]
Флажок работает только для объектов данных. Обработки к ним не относятся.

**Comment by PerlAmutor** [comment]
Есть надежда, что все-таки можно будет тестировать в различных режимах (на сервере, на клиенте) вообще все объекты?
