### ISSUE TITLE
Не загружаются шаблоны текста из файла шаблонов

### ISSUE THREAD

**Issue by potoyalo** [tormozit/RDT1C#176]
**Программное окружение**
<details>
  <summary>Информация для технической поддержки</summary>
Платформа: 8.3.16.1148<br/>
Режим БД: клиент-серверный<br/>
Конфигурация. Название: Нетиповая<br/>
Конфигурация. Основной режим запуска: Управляемое приложение<br/>
Конфигурация. Вариант встроенного языка: Русский<br/>
Конфигурация. Режим управления блокировкой данных: Управляемый<br/>
Конфигурация. Режим совместимости: Версия8_3_14<br/>
Конфигурация. Версия БСП: 301<br/>
Инструменты разработчика. Версия: Расширение 6.10.1e<br/>
Инструменты разработчика. Инструмент: Консоль кода<br/>
Инструменты разработчика. Перехват клавиатурного ввода: Нет<br/>
Инструменты разработчика. Объекты на сервере: Да<br/>
Инструменты разработчика. Разрешены имитаторы: Да<br/>
Расширения. РасширениеБСП (0.3.1)<br/>
Расширения. РасширениеБПО (0.3.0)<br/>
Расширения. ИнструментыРазработчикаTormozit (6.10.1e)<br/>
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский<br/>
Клиент. Приложение: Обычное приложение 32б<br/>
Клиент. Проверка модальных вызовов: Нет<br/>
Клиент. Язык интерфейса конфигурации: ru<br/>
Клиент. Язык интерфейса системы: ru_RU<br/>
Клиент. От имени администратора Windows: Нет<br/>
Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский<br/>
Сервер. Процесс: 64б<br/>
Сервер. Отладка: tcp<br/>
</details>

**Воспроизведение проблемы**
1. Открыл инструмент _Консоль кода_.
2. Открыл окно _Настройка компоненты "Поле текста программы"_ (Меню Поле программы -> Настройка).
3. В поле _Файл шаблонов текста_ выбрал файл шаблона. Файл тот же самый, который использую в конфигураторе. [Пример файла шаблонов](https://gist.github.com/potoyalo/2f8c8ee7480ad552c2adeda63feceeee)
4. Нажал кнопку **ОК**.
5. Получил окно с ошибкой «**Указан неправильный файл шаблонов "ИмяФайла.st"**».

**Ожидаемое поведение**
Ожидалось, что файл шаблонов загрузится без ошибок.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/939601

**Comment by tormozit** [comment]
Исправлено в 6.23
