### ISSUE TITLE
Ошибка в консоли запросов

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#177]
**Программное окружение**
        Платформа: 8.3.17.1851  
        Режим БД: клиент-серверный  
        Конфигурация. Название: Очередная нетленка  
        Конфигурация. Основной режим запуска: Обычное приложение   
        Конфигурация. Вариант встроенного языка: Русский   
        Конфигурация. Режим управления блокировкой данных: Управляемый   
        Конфигурация. Режим совместимости: Версия8_3_12   
        Инструменты разработчика. Версия: Портативный 6.22.1p   
        Инструменты разработчика. Инструмент: Прочее   
        Инструменты разработчика. Перехват клавиатурного ввода: Нет   
        Инструменты разработчика. Объекты на сервере: Нет   
        Инструменты разработчика. Серверный модуль: Нет  
        Клиент. ОС: Microsoft Windows Server 2008 R2 Standard  64-bit Русский  
        Клиент. Приложение: Обычное приложение 32б  
        Клиент. Проверка модальных вызовов: Нет  
        Клиент. Язык интерфейса конфигурации: ru  
        Клиент. Язык интерфейса системы: ru_RU  
        Клиент. От имени администратора Windows: Нет  

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Ввел текст запроса:
```
ВЫБРАТЬ
	1 КАК Поле1
ПОМЕСТИТЬ вт1
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	вт1.Поле1 КАК Поле1
ИЗ
	вт1 КАК вт1
ГДЕ
	вт1.Поле1 = &Поле1
```
3. Перешел на вкладку Параметры и нажал на кнопку Из запроса
2. Нажал кнопку Выполнить
3. Получил окно с ошибкой:
```
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(988)}: Поле объекта не обнаружено (Значение)
					Если ТипЗнч(СтрокаПараметра.Значение) = Тип("ТаблицаЗначений") Тогда

```

**Ожидаемое поведение**
Ожидал, что запрос выполниться.

**Comment by tormozit** [comment]
Воспроизвести не удалось. Нужна полная картинка окна инструмента и желательно стек. Попробуй повторить с новым файлом запросов.

**Comment by antonsm2011** [comment]
В новом файле запросов не воспроизводится.
В файле запросов было несколько запросов, у которых иконка была не SQL, а в виде папки.
Если все запросы-папки поочередно выбрать, то иконки меняются на SQL и ошибка исчезает.
Методом тыка я нашел, что какая-то проблема была в запросе 15.
Я приложил файл консоли с этим запросом.
Может будет полезно.
[cts_PharmaBase для ИР.zip](https://github.com/tormozit/RDT1C/files/7783581/cts_PharmaBase.zip)

А в целом проблема решена.

**Comment by antonsm2011** [comment]
> полная картинка окна инструмента
![2021-12-28_11-05-30 (2)](https://user-images.githubusercontent.com/12731230/147544613-1414ca4c-f1b1-467d-88cc-e4bf0c83c8c9.png)

**Comment by tormozit** [comment]
Когда и в какой консоли запросов создавался оригинальный файл? Кажется что это файл от другой консоли запросов или очень старой версии консоли запросов ИР.

**Comment by antonsm2011** [comment]
Это файл от ИР версии 5.75.
