### ISSUE TITLE
Опечатка в меню Передать в таблице значений

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#178]
**Программное окружение**

Платформа: 8.3.17.1851
Режим БД: файловый
Конфигурация. Название: 1C:Drive, версия 1.3 (1.3.6.5)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: English
Конфигурация. Режим управления блокировкой данных: Managed
Конфигурация. Режим совместимости: Version8_3_14
Инструменты разработчика. Версия: Расширение 6.10.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. cx_Доработки ()
Расширения. cx_ТолькоНекритичноеВместоСКонтролем ()
Расширения. ИнструментыРазработчикаTormozit (6.10.1e)
Клиент. ОС: Майкрософт Windows 10 Домашняя для одного языка 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru_RU
Клиент. От имени администратора Windows: Нет

**Воспроизведение проблемы**
1. Открыл инструмент Таблица значений из результат-коллекция консоли запросов
2. Нажал кнопку Передать 
3. Вижу опечатку "в буфера сравнения"
![изображение](https://user-images.githubusercontent.com/12731230/147542422-76beea70-a26a-49e5-a8e5-93425afcb8d5.png)

**Ожидаемое поведение**
Скорее всего пункт меню должен называться "в буфер сравнения"

**Comment by tormozit** [comment]
Ошибку подтверждаю

**Comment by tormozit** [comment]
исправлено в 6.23
