### ISSUE TITLE
Очистка таблицы СУБД - ошибка вызова

### ISSUE THREAD

**Issue by Pufilov** [tormozit/RDT1C#179]
**Программное окружение**

<details> 
  <summary>Информация для технической поддержки</summary>
Платформа: 8.3.16.1502
Режим БД: клиент-серверный
Конфигурация. Название: My
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_2_16
Инструменты разработчика. Версия: Портативный 6.22.1p
Инструменты разработчика. Инструмент: Структура хранения БД
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл: Структура хранения БД
2. Нажал кнопку Очистка таблицы СУБД...
3. Получил окно с ошибкой "Слишком много фактических параметров"
4. Детально: {ВнешняяОбработка.ирСтруктураХраненияБД.Форма.Форма.Форма(473)}: Слишком много фактических параметров
		ирОбщий.ПеревестиКолонкиСтруктурыХраненияБДТаблицыЛкс(СтрокиТаблиц, НуженПеревод);

**Ожидаемое поведение**
Вызов окна с кодом очистки таблицы СУБД. откатился до 14 релиза - все ок

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/939638

**Comment by tormozit** [comment]
Исправлено в 6.23
