### ISSUE TITLE
Конструктор запросов ИР. Обрезание псевдонима. Автополе.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#18]
https://user-images.githubusercontent.com/87958986/129591289-390e3a48-cf05-4d72-a12d-84c93b4cfba6.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.05.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

Конструктор запросов ИР обрезает псевдонимы полей полученных при отключении кнопки "Автополе", что делает запрос более не работоспособным. Пример запроса демонстрирующего проблему:

```
//{Запрос: 0, -2 ////////////////////////////////////////
ВЫБРАТЬ ПЕРВЫЕ 1
	Т.ПФРЗаЗанятыхНаПодземныхИВредныхРаботахБезСпецОценки КАК ПФРЗаЗанятыхНаПодземныхИВредныхРаботахБезСпецОценки
ПОМЕСТИТЬ ВтДанные
ИЗ
	Документ.ОтражениеЗарплатыВФинансовомУчете.НачисленнаяЗарплатаИВзносы КАК Т
;
//{Запрос: 1, -1 ////////////////////////////////////////
ВЫБРАТЬ ПЕРВЫЕ 1
	Т.Ссылка КАК Ссылка
ИЗ
	Документ.ОтражениеЗарплатыВФинансовомУчете.НачисленнаяЗарплатаИВзносы КАК Т
	ВНУТРЕННЕЕ СОЕДИНЕНИЕ (ВЫБРАТЬ ПЕРВЫЕ 1
			*
		ИЗ
			ВтДанные КАК Т) КАК Т2
	ПО Т.ПФРЗаЗанятыхНаПодземныхИВредныхРаботахБезСпецОценки = Т2.ПФРЗаЗанятыхНаПодземныхИВредныхРаботахБезСпецОценки
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932061

**Comment by tormozit** [comment]
исправлено в 6.05.2
