### ISSUE TITLE
Конструктор запросов ИР. Объединение таблиц

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#180]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

Есть пожелание добавить команду или функционал для объединения выбранных таблиц за один раз в Конструкторе Запросов ИР. Не сделать соединение, а именно сформировать пакет из объединений. Пример того как сейчас это происходит прилагаю:

https://user-images.githubusercontent.com/87958986/149827949-363aa694-80fd-43fa-9d7f-c72f905947e8.mp4

**Comment by tormozit** [comment]
Для информации 
![изображение](https://user-images.githubusercontent.com/11896251/149832215-a1c9ba6b-e6a8-475b-a410-b7823c9799ed.png)

**Comment by PerlAmutor** [comment]
Пробовал. Через неё невозможно объединить табличные части.

**Comment by tormozit** [comment]
Задача очень редкая. Сейчас ее можно решить через инструмент "Подбор и обработка объектов БД". Там нужно включить режим многотабличной выборки, в форме выбора отфильтровать и пометить нужные таблицы, открыть исполняемый текст запроса. 

![изображение](https://user-images.githubusercontent.com/11896251/150010990-7548baea-67a8-4b27-a7e7-5557c8cf0b7f.png)
