### ISSUE TITLE
Редактор объекта: добавить возможность указания простого отбора с выбором значения из справочника

### ISSUE THREAD

**Issue by prog-1c** [tormozit/RDT1C#181]
Добавить возможность простого отбора в выбранной табличной части с выбором значения.

_кейс: Есть табличная часть с большим количеством строк. Сейчас можно по F3 найти нужное значение и нажать кнопку Alt+W_
А можно сделать выбор одного значения из справочника и чтоб его установить в отбор?

**Comment by tormozit** [comment]
Команда "Различные значения колонки (ALT+F)" решает примерно ту же задачу. Попробуй ее.
