### ISSUE TITLE
Интерфейсная панель. Значение не является значением объектного типа (Имя)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#183]
https://user-images.githubusercontent.com/87958986/150683090-b1c1235a-7749-4c8d-9b2d-fc6bbe3d0433.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Интерфейсная панель
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Интерфейсная панель"
2. Перетащил в "Избранное" - справочник.
3. Вызвал команду "Удалить" на справочнике в избранном
4. Получил окно с ошибкой:

```
Значение не является значением объектного типа (Имя)
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(2298)}:	Если мКлючиТекущихСтрок[Элемент.Имя] = Элемент.ТекущаяСтрока.Имя Тогда

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/940231

**Comment by tormozit** [comment]
Исправлено в 6.24
