### ISSUE TITLE
Интерфейсная панель. Избранное. Найти в дереве.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#184]
https://user-images.githubusercontent.com/87958986/150683221-be38eb58-ea1b-4e9b-bbfc-484a0481e6fd.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Интерфейсная панель
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Интерфейсная панель"
2. Вызвал команду "Найти в дереве" в ТЧ "Избранное"
3. Получил окно с ошибкой

```
Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств)
{ВнешняяОбработка.ирИнтерфейснаяПанель.Форма.Форма.Форма(2334)}:	ЗаполнитьЗначенияСвойств(КлючПоиска, ЭтаФорма.ТекущийЭлемент.ТекущаяСтрока); 
по причине:
Недопустимое значение параметра (параметр номер '2')

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.24
