### ISSUE TITLE
Консоль построителей отчетов. ВыбТипДиаграммы

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#185]
https://user-images.githubusercontent.com/87958986/150683898-c394bf13-7aea-4d94-b8e0-4b3cfb003677.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Консоль построителей отчетов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль построителей отчетов"
2. Удалил "Отчет" из структуры
3. Добавил новый отчет.
4. Ничего не меняя, в открывшемся диалоге нажал "ОК"
5. Получил окно с ошибкой

```
Значение не является значением объектного типа (ВыбТипДиаграммы)
{ВнешняяОбработка.ирКонсольПостроителейОтчетов.Форма.Форма.Форма(1414)}:	ТекущаяСтрока.ВыбТипДиаграммы         = ВыбТипДиаграммы;
{ВнешняяОбработка.ирКонсольПостроителейОтчетов.Форма.Форма.Форма(2326)}:			СохранитьТекущиеНастройкиВСтроку();
{ВнешняяОбработка.ирКонсольПостроителейОтчетов.Форма.ФормаРедактированияЗапроса.Форма(82)}:	ОповеститьОВыборе(КлючУникальности);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/940232

**Comment by tormozit** [comment]
Исправлено в 6.24
