### ISSUE TITLE
Исследователь объектов ИР. Итератор для значения не определен.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#186]
https://user-images.githubusercontent.com/87958986/150684618-5d77819a-92bb-4670-be5e-b7a336d4261d.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Исследователь объектов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Исследователь объектов"
2. Встал на поле ввода выражения, нажал Ctrl+Shift+F4
3. Выдалась ошибка вычисления выражения
4. Вызвал команду  "\ Командная панель \ Авто контекстная помощь"
5. Выбрал мышкой строку с ошибкой вычисления выражения
6. Получил окно с ошибкой:
```
Итератор для значения не определен
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(1051)}:		Для Каждого СтруктураТипаКонтекста Из СтруктураЦикла[СтрокаЭлементаЦикла.Представление] Цикл
{ВнешняяОбработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(712)}:		мПлатформа.ВыбратьСтрокуОписанияИзМассиваСтруктурТипов(СтруктураЦикла, , ЭтаФорма);
{ВнешняяОбработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(421)}:		КоманднаяПанельДереваСправка();

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.24
