### ISSUE TITLE
Исследователь объектов. Значение не является значением объектного типа (Конструктор)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#187]
https://user-images.githubusercontent.com/87958986/150684860-66976b4c-fd87-42b7-ad3b-8ba52a2f52d0.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Исследователь объектов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Исследователь объектов"
2. Встал на строку вычисления выражения. Нажал Ctrl+Shift+F4
3. Получить ошибку вычисления выражения
4. Встал на строку с ошибкой вычисления выражения
5. Вызвал команду " \ Командная панель \ Обновить"
6. Получил окно с ошибкой:

```
Значение не является значением объектного типа (Конструктор)
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(1425)}:	Если РодительскаяСтруктураТипа.Конструктор Тогда
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(3972)}:	ТаблицаСвойств = СвойстваТипаПредопределенные(СтруктураТипа, Слово, ТипСлова,, ЯзыкПрограммы, Конфигурация, ВычислятьТипы, ЛиСерверныйКонтекст);
{ВнешняяОбработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(352)}:	ВнутренняяТаблицаСлов = мПлатформа.ПолучитьТаблицуСловСтруктурыТипа(СтрокаДерева.СтруктураТипа);
{ВнешняяОбработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(1128)}:	ЗаполнитьДочерниеСтроки(ТекущийРодитель);
```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.24
