### ISSUE TITLE
Редактор констант. Значение не является значением объектного типа (ИдентификаторКонстанты)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#188]
https://user-images.githubusercontent.com/87958986/150685545-6ca5c150-5d61-4264-ad9e-1372b563f22f.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Редактор констант
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор констант"
2. Вызвал команду " \ Командная панель \ Связанный"
3. Установил отбор "Имя типа значения = """
4. Получил окно с ошибкой:

```
Значение не является значением объектного типа (ИдентификаторКонстанты)
{ВнешняяОбработка.ирРедакторКонстант.Форма.Форма.Форма(506)}:	ирОбщий.ОткрытьТекущуюСтрокуТабличногоПоляТаблицыБДВРедактореОбъектаБДЛкс(ЭлементыФормы.ТаблицаКонстант, "Константа." + ЭлементыФормы.ТаблицаКонстант.ТекущаяСтрока.ИдентификаторКонстанты,, Истина, мСвязанныйРедакторОбъектаБД,, Ложь);
{ВнешняяОбработка.ирРедакторКонстант.Форма.Форма.Форма(481)}:		ОткрытьСвязанныйРедакторОбъектаБДСтроки();

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.24
