### ISSUE TITLE
Редактор объекта БД. Не закрывается форма ФункциональнойОпции при выходе из ИР.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#19]
https://user-images.githubusercontent.com/87958986/129657501-81ee29dc-f872-43e1-bf55-d67e486ea73b.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.05.2p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

При выходе из ИР автоматически не закрывается ранее открытая форма функциональной опции из Редактора Объекта БД.

**Comment by tormozit** [comment]
исправлено в 6.06.1
