### ISSUE TITLE
Консоль заданий. Недопустимое значение параметра (параметр номер '1')

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#190]
https://user-images.githubusercontent.com/87958986/150686814-6b25d0a7-bc25-4c9b-a991-b01c4df66db7.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Консоль заданий
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль заданий"
2. Выбрал строку с именем "<Фоновые задания запущенные из кода>"
3. Вызвал команду " \ Панель \ Регламентные задания(116) \ Командная панель \ Обработать в консоли кода"
4. Получил окно с ошибкой:

```
Ошибка при вызове конструктора (УникальныйИдентификатор)
{ВнешняяОбработка.ирКонсольЗаданий.Форма.ФормаКонсоли.Форма(1888)}:		ВыделенныеРегламентныеЗадания.Добавить(РегламентныеЗадания.НайтиПоУникальномуИдентификатору(Новый УникальныйИдентификатор(ВыделеннаяСтрока.Идентификатор)));
по причине:
Недопустимое значение параметра (параметр номер '1')

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.24
