### ISSUE TITLE
Полнотекстовый поиск данных. Размер выборки 2000.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#191]
https://user-images.githubusercontent.com/87958986/150687588-9fe1b2b2-d4e2-414d-a643-3725c2f0b996.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Полнотекстовый поиск данных
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Полнотекстовый поиск данных"
2. Выбрал из выпадающего списка размер порции "2000"
3. Получил окно с ошибкой "В поле введены некорректные данные"

**Ожидаемое поведение**
Установка размера выборки "2000", либо отсутствие этого пункта среди вариантов.

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.24
