### ISSUE TITLE
Полнотекстовый поиск. ПерваяЧасть

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#192]
https://user-images.githubusercontent.com/87958986/150687787-73d19c80-c359-44fd-8274-bdf55cb86c3c.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Полнотекстовый поиск данных
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Полнотекстовый поиск данных"
2. Ввел слово для поиска
3. Нажал "Найти"
4. Получил результат. Вызвал команду " \ Панель \ Страница1 \ Командная панель \ НовоеОкно"
5. Ввел слово для поиска
6. Нажал "Найти"
7. Получил окно с ошибкой

```
Ошибка при вызове метода контекста (ПерваяЧасть)
{ВнешняяОбработка.ирПолнотекстовыйПоискДанных.Форма.Форма.Форма(31)}:	мПорцияРезультата.ПерваяЧасть();
{ВнешняяОбработка.ирПолнотекстовыйПоискДанных.Форма.Форма.Форма(235)}:	НачатьПоиск();
по причине:
Несоответствие типов (параметр номер '1')

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/940233

**Comment by tormozit** [comment]
Исправлено в 6.24
