### ISSUE TITLE
Анализ журнала регистрации. Отбор по пользователю.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#193]
https://user-images.githubusercontent.com/87958986/150688152-69331b5d-41d6-4870-81e7-525a83a30325.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Анализ журнала регистрации
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Анализ журнала регистрации"
2. Отсутствует возможность выбора других пользователей. Которые могут быть в другом выбранном периоде
3. При работе с диалогом выбора пользователя в поле "Полное имя" непонятный идентификатор вместо имени
4. Если открыть инструмент "Редактор пользователей" и вызвать команду " \ Командная панель \ Журнал регистрации"
то в "Анализ журнала регистрации" передается непонятный идентификатор вмести представления выбранного пользователя

**Comment by tormozit** [comment]
В списке доступных для отбора пользователей отображаются только пользователи, по которым есть хотя бы одно событие в журнале регистрации. Такой принцип применяется здесь для всех элементов отбора со списком доступных значений.
По некорректному отображению остальных пользователей создал задачу https://www.hostedredmine.com/issues/940313

**Comment by tormozit** [comment]
Исправлено в 6.24
