### ISSUE TITLE
Анализ техножурнала. ПодключитьОбработчикОжидания

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#194]
https://user-images.githubusercontent.com/87958986/150830149-78625a37-0be3-45a4-97ea-6357acb14958.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Анализ техножурнала
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Анализ техножурнала"
2. Выбрал каталог с данными ТЖ
3. Выбрал периодичность автообновления "30" секунд
4. Получил окно с ошибкой:

```
Ошибка при вызове метода контекста (ПодключитьОбработчикОжидания)
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(272)}:			ПодключитьОбработчикОжидания("ОбновитьТаблицуЖурнала", Автообновление, Истина);
{(1)}:ЭтаФормаИлиОбработка.ЗагрузитьЖурналЗавершение(, Результат)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(31361)}:			Выполнить("ЭтаФормаИлиОбработка." + ОбработчикЗавершения + "(, Результат)");
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(215)}:	ирОбщий.ВыполнитьЗаданиеФормыЛкс("ПрочитатьЖурнал", ПараметрыЗадания, ЭтаФорма, "ЗагрузкаТехножурнала",, Кнопка, "ЗагрузитьЖурналЗавершение", Не РежимТрассы,,,, Истина);
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(917)}:		ОбновитьТаблицуЖурнала();
по причине:
Недопустимое значение параметра (параметр номер '1') (Процедура, указанная в качестве обработчика события, имеет неверное количество параметров)

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/940306

**Comment by tormozit** [comment]
Исправлено в 6.24
