### ISSUE TITLE
Настройка техножурнала. Значение не является значением объектного типа (Значение)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#195]
https://user-images.githubusercontent.com/87958986/150831512-a6ecc761-66f3-4b4f-a280-d4dfb7848bf2.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Настройка техножурнала
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Настройка техножурнала"
2. Выбрал существующую настройку
3. Вызвал команду " \ Панель \ Журналы (log) \ Командная панель \ &Изменить (F2)"
4. В открывшейся форме перешел на вкладку "Детальный"
5. Нажал кнопку "Шаблон по таблице БД"
6. Получил окно с ошибкой:

```
Значение не является значением объектного типа (Значение)
{ВнешняяОбработка.ирНастройкаТехножурнала.Форма.НастройкаКаталога.Форма(382)}:	ИмяТаблицыХранения = СтрЗаменить(ТекущаяСтрока.Значение, "%", "");

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.24
