### ISSUE TITLE
Настройка техножурнала. Указан недопустимый префикс или URI пространства имен

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#196]
https://user-images.githubusercontent.com/87958986/150832415-8a2de9e4-473a-4988-a822-940eb0bf4a79.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Настройка техножурнала
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Настройка техножурнала"
2. Выбрал настройку
3. Нажал кнопку " \ Панель \ Журналы (log) \ Командная панель \ &Изменить (F2)"
4. В открывшейся форме перешел на вкладку "Детальный"
5. В табличной части "Группа-И текущей строки слева" добавил строку (Ins)
6. Очистил поле "Сравнение" и щелкнул мышкой в пустое пространство
7. Получил окно с ошибкой:

```
Ошибка при вызове метода контекста (СоздатьЭлемент)
{ВнешняяОбработка.ирНастройкаТехножурнала.МодульОбъекта(863)}:	ЭлементДОМ = Документ.СоздатьЭлемент(Документ.ЭлементДокумента.URIПространстваИмен, Документ.ЭлементДокумента.Префикс + ":" + ЛокальноеИмяЭлемента);
{ВнешняяОбработка.ирНастройкаТехножурнала.Форма.НастройкаКаталога.Форма(78)}:		ЭлементДОМ = СоздатьЭлементДОМ(Строка.Сравнение);
{ВнешняяОбработка.ирНастройкаТехножурнала.Форма.НастройкаКаталога.Форма(964)}:	УстановитьЭлементОтбораСобытий(РедактированиеУсловийСобытия, мТекущийИндексУзлаСобытия, ЭлементыФормы.ТабличноеПолеСписокСобытий.ТекущаяСтрока);
по причине:
Указан недопустимый префикс или URI пространства имен

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.24
