### ISSUE TITLE
Колонки БД. Недопустимые типы параметров 1, 2

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#197]
https://user-images.githubusercontent.com/87958986/150836075-59f3842a-8364-48d3-9bd8-6019ebec4c9e.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

>  Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Колонки БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Колонки БД"
2. Выбрал строку константы
3. Вызвал команду " \ Командная панель \ Данные колонки БД \ Различные значения"
4. Получил окно с ошибкой:

```
Недопустимые типы параметров 1, 2
{ВнешняяОбработка.ирОбщий.МодульОбъекта(4587)}:		ВызватьИсключение "Недопустимые типы параметров 1, 2";
{ВнешняяОбработка.ирРазличныеЗначенияКолонки.Форма.Форма.Форма(479)}:		ирОбщий.СкопироватьОтборЛюбойЛкс(НастройкаКомпоновки.Отбор, Отбор);
{ВнешняяОбработка.ирРазличныеЗначенияКолонки.Форма.Форма.Форма(939)}:	Если Не ОбновитьДанные(, Истина) Тогда 
{ВнешняяОбработка.ирКолонкиБД.Форма.Форма.Форма(203)}:	Форма.ОткрытьМодально();

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/940311

**Comment by tormozit** [comment]
Исправлено в 6.24
