### ISSUE TITLE
Поиск дублей и замена ссылок. Значение не является значением объектного типа (ЭлементУправления)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#199]
https://user-images.githubusercontent.com/87958986/150839861-10bea542-c2d7-4b38-b865-8b64730780f8.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.23.1p
> Инструменты разработчика. Инструмент: Поиск дублей и замена ссылок
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Поиск дублей и замена ссылок"
2. Перешел на вкладку "Группы дублей"
3. Нажал кнопку " \ Панель \ Группы дублей(1) \ Командная панель \ Поиск зависимых"
4. Фокус перешел на вкладку "Поиск зависимых". Поставил флажок у нижней ТЧ.
5. Получил окно с ошибкой:

```
Значение не является значением объектного типа (ЭлементУправления)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(23047)}:	Если Истина
{ВнешняяОбработка.ирОбщий.МодульОбъекта(9632)}:		КолонкаПометки = КолонкаПометкиТабличногоПоляЛкс(ТабличноеПоле);
{ВнешняяОбработка.ирПоискДублейИЗаменаСсылок.Форма.Форма.Форма(3237)}:	ирОбщий.ИзменитьПометкиВыделенныхИлиОтобранныхСтрокЛкс(ЭлементыФормы.НайденныеЗависимыеСсылки, , Истина);

```
6. Снял флажок в нижней ТЧ
7. Получил окно с ошибкой:
```
Ошибка при вызове метода контекста (ЗаполнитьЗначения)
{ВнешняяОбработка.ирПоискДублейИЗаменаСсылок.Форма.Форма.Форма(3224)}:	НайденныеЗависимыеСсылки.ЗаполнитьЗначения(Ложь, "Пометка");
по причине:
Неверное имя колонки

```

**Comment by tormozit** [comment]
Ошибки воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.24
