### ISSUE TITLE
Консоль запросов. Вывод Булево в ТабличныйДокумент не отображается представление

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#200]
https://user-images.githubusercontent.com/87958986/153696804-61aac32b-82d9-4ed1-a09b-136890ce3534.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.24.1p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Выполнил запрос:

```
ВЫБРАТЬ
	ИСТИНА КАК Поле1,
	ЛОЖЬ КАК Поле2
```

3. Вызвал команду " \ Панель \ Результат-коллекция(1) \ Командная панель \ Вывести строки"
4. Установил параметры вывода как в видео
5. В ТабличномДокументе не видно значений ИСТИНА типа Булево .

**Ожидаемое поведение**
Отображение значения представления по-умолчанию для типов Булево (Да/Нет, Истина/Ложь), либо графического представления в виде Флажка.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/940908

**Comment by tormozit** [comment]
Исправлено в 6.25
