### ISSUE TITLE
Различные значения колонки. Сортировка по флажку.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#201]
https://user-images.githubusercontent.com/87958986/153898125-db50770d-1e90-4a4a-ad15-945d3ba47c14.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.24.1p
> Инструменты разработчика. Инструмент: Различные значения колонки
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Выполнил запрос:

```
ВЫБРАТЬ
	1 КАК Поле1

ОБЪЕДИНИТЬ ВСЕ

ВЫБРАТЬ
	2
```

3. Вызвал команду " \ Панель \ Результат-коллекция(2) \ Командная панель \ Значения колонки (Alt+F)"
4. Выделил ячейку с полем флажка
5. Вызвал команду " \ Командная панель \ Сортировать по убыванию"
6. Получил окно с ошибкой:

```
Ошибка при вызове метода контекста (Сортировать)
{ВнешняяОбработка.ирРазличныеЗначенияКолонки.Форма.Форма.Форма(1208)}:	ЗначенияРасширенные.Сортировать(ирОбщий.ТабличноеПолеСортироватьЛкс(ЭтаФорма, ЭлементыФормы.Значения, Ложь));
{ВнешняяОбработка.ирОбщий.МодульОбъекта(38476)}:	РезультатФормы = Форма.ОткрытьМодально();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(38944)}:				ОткрытьРазличныеЗначенияКолонкиЛкс(ИсточникДействий,,, ЭтаФорма);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(9632)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
по причине:
Неверное имя колонки

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/941239

**Comment by tormozit** [comment]
Исправлено в 6.25
