### ISSUE TITLE
Конструктор запросов ИР. "Бьется" текст запроса.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#202]
https://user-images.githubusercontent.com/87958986/154097135-e04db2b7-1677-436f-8c7f-fb8018d031d4.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.24.1p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Ввел запрос:

```
ВЫБРАТЬ
    ИСТИНА
ГДЕ
    (ИСТИНА,ИСТИНА) В
            (ВЫБРАТЬ
				Т.Поле1,
				Т.Поле2
            ИЗ
                ВтТест2 КАК Т
            СГРУППИРОВАТЬ ПО
            	Т.Поле1,
            	Т.Поле2

            ИМЕЮЩИЕ
                КОЛИЧЕСТВО(Т.Поле1) > 1)
;

ВЫБРАТЬ
    ИСТИНА КАК МоёИмяПоляНеЗаменятьНаПоле1
ПОМЕСТИТЬ ВтТаблица1

 
```

3. Открыл запрос через "Конструктор запросов ИР"
4. Перешел на вкладку " \ Панель \ Текст запроса/пакета"
5. Вижу, что у временной таблицы отсутствует имя. А у поля, где раньше было имя, теперь просто "Поле1".

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/941451

**Comment by tormozit** [comment]
Исправлено в 6.25
