### ISSUE TITLE
Редактор объекта БД. Отбор по регистратору

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#203]
https://user-images.githubusercontent.com/87958986/160251321-e21bf4f7-8527-41ff-a31e-e13bd2b8bb76.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.26.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Выбрал РегистрСведений.ОтражениеДокументовВРеглУчете
3. В качестве отбора по Регистратору попытался использовать навигационную ссылку на документ 
4. Получил окно с ошибкой:

```
Значение не является значением объектного типа (Имя)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(41332)}:			выхПутьКДанным = Элемент.Имя;
{ВнешняяОбработка.ирОбщий.МодульОбъекта(33274)}:			ЗначениеПоля = ДанныеЭлементаФормыЛкс(ПолеВводаИлиЭлементОтбора);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3429)}:	ирОбщий.ПолеВводаСИсториейВыбора_ПриИзмененииЛкс(Элемент, КлючИсторииВыбораЗначенияИзмерения());
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4159)}:		ТаблицаОтбораЗначениеПриИзменении(); // Восстановить неудобные типы (МоментВремени, УникальныйИдентификатор)

```

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/942691

**Comment by tormozit** [comment]
Исправлено в 6.27
