### ISSUE TITLE
Консоль запросов. Особенность поведения команды "Структура"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#204]
Часто приходится использовать комплексные пакеты запросов (пример ниже). Если использовать команду "Структура", затем выбрать какой-то блок запроса и вызвать на нем Конструктор запросов, то неявно для пользователя включается режим редактирования запроса, который блокирует отключение кнопки "Структура" для возврата к полному тексту запросов. Если пользователь этого не заметил и не нажал отмену редактирования переключившись на другой блок, то у него может сложится впечатление, что команда не стала доступной из-за ошибки. Если он догадается в чем причина, то может уйти немало времени на поиск нужного блока на котором включено редактирование. Предлагаю пересмотреть поведение кнопки "Структура", например оставить доступной для отжатия, но проверять при этом, что есть блоки запросов открытые для редактирования и предлагать пользователю отменить или сохранить эти изменения.

https://user-images.githubusercontent.com/87958986/160251884-15bd6f9e-641c-483d-a888-21bf370ccf9c.mp4

```
ВЫБРАТЬ ПЕРВЫЕ 1
	АвансовыйОтчет.Ссылка КАК Ссылка
ИЗ
	Документ.АвансовыйОтчет КАК АвансовыйОтчет
	
ОБЪЕДИНИТЬ ВСЕ

ВЫБРАТЬ ПЕРВЫЕ 1
	АвансовыйОтчет.Ссылка КАК Ссылка
ИЗ
	Документ.АвансовыйОтчет КАК АвансовыйОтчет
	
ОБЪЕДИНИТЬ ВСЕ

ВЫБРАТЬ ПЕРВЫЕ 1
	АвансовыйОтчет.Ссылка КАК Ссылка
ИЗ
	Документ.АвансовыйОтчет КАК АвансовыйОтчет
	
ОБЪЕДИНИТЬ ВСЕ

ВЫБРАТЬ ПЕРВЫЕ 1
	АвансовыйОтчет.Ссылка КАК Ссылка
ИЗ
	Документ.АвансовыйОтчет КАК АвансовыйОтчет
	
ОБЪЕДИНИТЬ ВСЕ

ВЫБРАТЬ ПЕРВЫЕ 1
	АвансовыйОтчет.Ссылка КАК Ссылка
ИЗ
	Документ.АвансовыйОтчет КАК АвансовыйОтчет
```

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/943295

**Comment by tormozit** [comment]
Реализовано в 6.27
