### ISSUE TITLE
Ошибка инициализации модуля: Обработка.ирПлатформа.МодульОбъекта

### ISSUE THREAD

**Issue by OlegBushev** [tormozit/RDT1C#205]
Объединял конфигурацию
скачивал с http://devtool1c.ucoz.ru/load/osnovnye/actualsubsystem/1-1-0-1

В режиме предприятия появилась подсистема Инструменты разработчика 6.27.1 и в меню только один пункт "Адаптация расширения". При нажатии ошибка:

Ошибка инициализации модуля: Обработка.ирПлатформа.МодульОбъекта
через:
{Обработка.ирПлатформа.МодульОбъекта(163,7)}: Переменная не определена (ТаблицаКонтекстов)
	Если <<?>>ТаблицаКонтекстов.Количество() > 0 Тогда
{Обработка.ирПлатформа.МодульОбъекта(239,16)}: Переменная не определена(ТаблицаКонтекстов)
	НоваяСтрока = <<?>>ТаблицаКонтекстов.Добавить();
{Обработка.ирПлатформа.МодульОбъекта(1010,19)}: Переменная не определена(ТаблицаКонтекстов)
	СтрокиЗначений = <<?>>ТаблицаКонтекстов.НайтиСтроки(Новый Структура("ТипКонтекста, ТипСлова", "ПеречислениеМетаданных: " + ИмяТипаИлиТипЗначения, "Свойство"));
{Обработка.ирПлатформа.МодульОбъекта(1016,20)}: Переменная не определена(ТаблицаКонтекстов)
		СтрокиЗначений = <<?>>ТаблицаКонтекстов.НайтиСтроки(Новый Структура("ТипКонтекста, ТипСлова", ИмяТипаПеречисления, "Свойство"));
{Обработка.ирПлатформа.МодульОбъекта(1018,19)}: Переменная не определена(ТаблицаКонтекстов)
	СтрокиЗначений = <<?>>ТаблицаКонтекстов.Скопировать(СтрокиЗначений);
{Обработка.ирПлатформа.МодульОбъекта(1516,23)}: Переменная не определена(ТаблицаКонтекстов)
				НайденныеСтроки = <<?>>ТаблицаКонтекстов.НайтиСтроки(СтруктураКлюча);
{Обработка.ирПлатформа.МодульОбъекта(1535,38)}: Переменная не определена(ТаблицаКонтекстов)
			ирОбщий.ДобавитьИндексВТаблицуЛкс(<<?>>ТаблицаКонтекстов, СтруктураКлюча);  // спасает в случае языка запросов, где ТипСлова не используется
{Обработка.ирПлатформа.МодульОбъекта(1536,22)}: Переменная не определена(ТаблицаКонтекстов)
			НайденныеСтроки = <<?>>ТаблицаКонтекстов.НайтиСтроки(СтруктураКлюча);
{Обработка.ирПлатформа.МодульОбъекта(5202,6)}: Переменная не определена(ТаблицаКонтекстов)
			И <<?>>ТаблицаКонтекстов.НайтиСтроки(СтруктураКлюча).Количество() = 0

**Comment by tormozit** [comment]
Устанавливал по инструкции http://devtool1c.ucoz.ru/index/ustanovka_i_obnovlenie/0-7 ?

**Comment by OlegBushev** [comment]
да, причем в обычном приложении панель открывается, но при вызове любой из обработок тоже ругается на таблицу контекстов

**Comment by tormozit** [comment]
Оформляй как положено http://devtool1c.ucoz.ru/forum/2-2-1

**Comment by OlegBushev** [comment]
так не могу запустить ни одно окно из инструментов

**Comment by OlegBushev** [comment]
запустил портативными

Платформа: 8.3.16.1690
Режим БД: клиент-серверный
Конфигурация. Название: Business automation software for integrated enterprise management (2.1.20.1)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_6
Конфигурация. Версия БСП: 203
Инструменты разработчика. Версия: Портативный 5.97.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. ОС: Майкрософт Windows Server 2019 Datacenter 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Windows x86-64 version 10.0  (Build 17763)

**Comment by tormozit** [comment]
Создай новую базу на том же сервере приложений и загрузи туда оригинальную конфигурацию инструментов. Проблема повторяется?

**Comment by tormozit** [comment]
Пробуй на другой версии платформы в файловой базе с твоей конфигурацией.

**Comment by tormozit** [comment]
Удалось?
