### ISSUE TITLE
Редактор изменений на узлах. Регистры накопления.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#206]
https://user-images.githubusercontent.com/87958986/163705686-81791099-7fbe-4a6b-a72d-52c5ba2342e4.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

>  Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.7.383)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.27.1p
> Инструменты разработчика. Инструмент: Редактор изменений на узлах
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19044)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор изменений на узлах"
2. Выбрал план обмена
3. Выбрал узел
4. Выбрал объект метаданных "РегистрыНакопления"
5. Получил окно с ошибкой:

```
Ошибка при вызове конструктора (ПостроительЗапроса)
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(1117)}:	Построитель = Новый ПостроительЗапроса(ТекстЗапроса);
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(1213)}:		Построитель = ПостроительЗапросаДляТаблицыИзменений();
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(970)}:		КП_ТаблицаИзмененийОбновить();
по причине:
{(4, 88)}: Поле не найдено "_ТО.ОбластьДанныхОсновныеДанные"
ПО ИСТИНА		И _Т.Регистратор = _ТО.Регистратор		И _Т.ОбластьДанныхОсновныеДанные = _ТО.<<?>>ОбластьДанныхОсновныеДанные

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/944145

**Comment by tormozit** [comment]
Исправлено в 6.27.3
