### ISSUE TITLE
Статистика по запросам СУБД. Query Timeout Expired

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#207]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.7.383)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.27.1p
> Инструменты разработчика. Инструмент: Статистика по запросам СУБД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19044)

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Статистика по запросам СУБД"
2. Снял отборы
3. Запустил формирование
4. Через некоторое время получил окно с ошибкой:

![photo_2022-04-17_11-00-30](https://user-images.githubusercontent.com/87958986/163706093-b0f0488e-68fe-4cfe-80b4-f8a6384195ff.jpg)

**Ожидаемое поведение**
Требуется новая настройка подключения к SQL серверу для увеличения таймаута запросов, например сюда:

![image](https://user-images.githubusercontent.com/87958986/163706135-1007e8ac-abcb-4d40-b5e2-2c4df1602c77.png)

**Comment by tormozit** [comment]
К сожалению общего удобного во всех случаях значения макс. времени ожидания задать не получится. В одних местах слишком большое значение будет приводить к очень долгим ожиданиям, а в других слишком короткое - к не дожиданию результата. Поэтому укажи реалистичные параметры отбора в отчете и попробуй снова. Если ошибка повторится, покажи полные настройки отчета (сейчас не видно параметров).

**Comment by tormozit** [comment]
Также нужен текст полный ошибки. На твоей версии платформы он обрезан (очевидно нет строки кода с вызовом метода Open) из-за ошибки платформы https://www.hostedredmine.com/issues/941533 . Чтобы увидеть полный текст ошибки, нужно смотреть в журнал регистрации или окно "О программе".
