### ISSUE TITLE
Различные значения колонки. Выбор типа в поле фильтра.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#208]
https://user-images.githubusercontent.com/87958986/163706893-54c2aba1-2adf-4b1e-97d5-87cf05c4c95c.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1549
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.7.383)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.27.1p
> Инструменты разработчика. Инструмент: Различные значения колонки
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19044)

</details>

**Воспроизведение проблемы**
1. Открыл консоль запросов, выполнил запрос, вызвал команду " \ Панель \ Результат-коллекция(31) \ Командная панель \ Значения колонки (Alt+F)"
2. В открывшейся форме нажал на кнопку очистки у поля ввода " \ <ФильтрПоПодстроке>"
3. После этого стало невозможно что либо вводить в поле. Оказалось, что поле стало составного типа и второй тип "Список значений" несколько обескураживает.

**Ожидаемое поведение**
Если второй тип "Список значений" должен присутствовать в поле, то ожидается изменение кнопки "Очистка" на кнопку "Т" в поле ввода фильтра. В противном случае необходимо установить ограничение типа при очистке поля или исправить составной тип.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/944146

**Comment by tormozit** [comment]
Исправлено в 6.27.3
