### ISSUE TITLE
Ошибка. Отложенная отладка.

### ISSUE THREAD

**Issue by Sergsqvo** [tormozit/RDT1C#209]
**Программное окружение**

<details>  
  <summary>Информация для технической поддержки</summary>  

Платформа: 8.3.19.1522
Режим БД: клиент-серверный
Конфигурация. Название: Гознак РУиО (301.7.63.1)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.27.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИсправлениеОшибокРелиз_3_1_7_63 (0.0.0.9)
Расширения. НеФункциональныеТребования (0.0.0.5)
Расширения. ИнструментыРазработчикаTormozit (6.27.2e)
Клиент. ОС: Майкрософт Windows Server 2019 Datacenter Evaluation 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Linux x86-64
Сервер. Процесс: 64б
</details>

**Воспроизведение проблемы**
Работаю в режиме RDP, не могу запустить отложенную отладку запроса в конфигураторе:
ВнешниеОбработки.Создать("C:\Users\sskvortsov\_1C\_Инструменты\6_5.74.1\ирПортативный.epf", Ложь).От(Запрос)
ВнешниеОбработки.Создать("\\Gzn-dmz-03\c$\Users\sskvortsov\_1C\_Инструменты\ирПортативный.epf", Ложь).От(Запрос)
Пробовал указывать и локальный и сетевой путь.
Возникает ошибка:
{<Неизвестный модуль>(1)}: Ошибка при вызове метода контекста (Создать)
![ИнструментыРазработчикаОшибка](https://user-images.githubusercontent.com/104561346/165723124-71c24561-18b7-4c23-b774-6e68e6e77a1d.jpg)

**Ожидаемое поведение**
Реакция ожидалась как в описании: https://www.youtube.com/watch?v=hiw_aYVOvFc&t=0s

**Comment by tormozit** [comment]
Ты используешь вариант поставки "Расширение". А ролик смотришь для варианта "Портативый".
Вот правильный ролик для варианта "Расширение" https://www.youtube.com/watch?v=-NJJP79TccI
