### ISSUE TITLE
Редактор хранилищ настроек. При выходе из ИР не закрывается форма Сериализации XDTO

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#21]
https://user-images.githubusercontent.com/87958986/129659540-bd1142b5-db27-451a-ba1b-276316625f3a.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

Платформа: 8.3.19.1229
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.05.2p
Инструменты разработчика. Инструмент: Редактор хранилищ настроек
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

</details>

При выходе из ИР автоматически не закрывается ранее открытая форма Сериализации XDTO из Редактора Хранилищ Настроек.

**Comment by tormozit** [comment]
исправлено в 6.06.1
