### ISSUE TITLE
Консоль запросов. Структура. Коррелирующий подзапрос.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#212]
https://user-images.githubusercontent.com/87958986/168119317-cfc0bc8d-f56f-41d8-a982-0ea04e9645c5.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.28.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Написал запрос с коррелирующим подзапросом (пример в .sel файле)
[КоррелирующийПодзапрос.zip](https://github.com/tormozit/RDT1C/files/8680827/default.zip)

3. Нажал кнопку " \ Командная панель \ Структура" 
4. Выбрал команду контекстного меню "Выполнить подзапросы"
5. Получил ошибку:

```
Текст запроса: Строка кода 5: {(5,13)}: Поле не найдено "Т1.Объект"
Объект = <<?>>Т1.Объект
```
Команда "Обозначить зависимые запросы" не работает, или я не знаю как ей пользоваться.

**Ожидаемое поведение**
Не выделять в отдельную ветку подзапросы секции "ГДЕ" оставляя на родительском уровне, либо не считать такие подзапросы отдельными и не пытаться их выполнить в разрыве от родительского запроса, либо починить команду "Обозначить зависимые запросы", если она должна делать то о чем я думаю.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/945201
Команда "Обозначить зависимые запросы" ошибочно доступна для подзапросов. Исправлю.

**Comment by tormozit** [comment]
Касаемо понимания, что должна делать интересующая команда. К сожалению для пунктов подменю платформа не отображает всплывающую подсказку, а для контекстного меню еще и пояснение не отображает. Поэтому нужно смотреть в структуре формы подсказку в кнопке. 

![изображение](https://user-images.githubusercontent.com/11896251/168382821-b6e25d4e-e9e6-4a42-83fb-ed675d468dad.png)

**Comment by tormozit** [comment]
Исправлено в 6.29
