### ISSUE TITLE
Консоль запросов. Ошибка при разборе структуры

### ISSUE THREAD

**Issue by Morkhe** [tormozit/RDT1C#213]
**Программное окружение**

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1789
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.7.394)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.28.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.28.1e)
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-bit Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp
</details>

**Воспроизведение проблемы**
1. Создать реквизит справочника или значение перечисления с именем `Полное`
2. Открыть инструмент Консоль запросов
3. Установить текст запроса
`ВЫБРАТЬ ЗНАЧЕНИЕ(Перечисление.Перечисление1.Полное)`
или
`ВЫБРАТЬ Т.Полное Из Справочник.Справочник1 КАК Т`
4. Нажать кнопку Структура
5. Получить ошибку
`Текст запроса: Строка 1: {(1,72)}: Синтаксическая ошибка "Полное", ожидается: <(>, <ALL>, <ALLOWED>, <AND>, <AS>, <ASC>, <AUTOORDER>, <AVG>, <BadID>, <BEGINOFPERIOD>, <BETWEEN>, <BIGINT>, <CASE>, <CAST>, <CHAR>, <COUNT>, <DATASIZE>, <DATE>, <DATEADD>, <DATEDIFF>, <DATETIME>, <DAY>, <DAYOFYEAR>, <DECIMAL>, <DESC>, <DISTINCT>, <DOUBLE>, <DROP>, <ELSE>, <EMPTYTABLE>, <END>, <ENDOFPERIOD>, <ESCAPE>, <FALSE>, <FLOAT>, <FOR>, <FROM>, <GROUP>, <HIERARCHY>, <HIERARCHYIN>, <HIERARCHYON>, <HOUR>, <id>, <IN>, <INNER>, <INT>, <INT64>, <INTEGER>, <INTO>, <IS>, <ISNULL>, <JOIN>, <LEFT>, <LIKE>, <LONGTEXT>, <MAX>, <MEDIUMTEXT>, <MIN>, <MINUTE>, <MONEY>, <MONTH>, <NCHAR>, <NOT>, <NTEXT>, <NULL>, <NUMBER>, <NUMERIC>, <NVARCHAR>, <OF>, <ON>, <ONLY>, <OR>, <ORDER>, <OUTER>, <PERIODS>, <PRESENTATION>, <PRESENTATIONREFS>, <QUARTER>, <REAL>, <REF>, <REFS>, <RIGHT>, <ROUND>, <SECOND>, <SELECT>, <SMALLINT>, <STRFIND>, <STRING>, <STRINGLENGTH>, <STRLEFT>, <STRREPLACE>, <STRRIGHT>, <SUBSTRING>, <SUM>, <TABLE>, <TEXT>, <THEN>, <TIME>, <TIMESTAMP>, <TINYTEXT>, <TOP>, <TOTALS>, <TRIMALL>, <TRIML>, <TRIMR>, <TRUE>, <TYPE>, <UNDEFINED>, <UNION>, <UPDATE>, <VALUE>, <VALUETYPE>, <VARCHAR>, <WEEK>, <WEEKDAY>, <WHEN>, <WHERE>, <YEAR>`

**Ожидаемое поведение**
Корректный разбор структуры запроса.
В ERP ломается на типовом перечислении `ЗНАЧЕНИЕ(Перечисление.ВариантыПримененияЦелевогоФинансирования.Полное)`

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/945196

**Comment by tormozit** [comment]
Исправлено в 6.29
