### ISSUE TITLE
Выгрузка/Загрузка отдельных объектов в/из XML

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#214]
Есть предложение добавить команду выгрузки и загрузки объекта метаданных конфигурации в инструмент "Интерфейсная панель". 

![image](https://user-images.githubusercontent.com/87958986/169358817-a2cf8d85-38c3-418d-b67d-b006600ff334.png)

В конфигураторе нет визуальных средств для выполнения этой процедуры, однако эти процедуры доступы в пакетном режиме конфигуратора. Вот примеры:

// Выгрузка в XML:
`"C:\Program Files\1cv8\8.3.17.1851\bin\1cv8.exe" DESIGNER /IBName "erp24554_demo (ord)" /N "Администратор (ОрловАВ)" /P"" /DumpConfigToFiles "D:\test\xml" -listFile "d:\test\listfiles.txt" -Format Hierarchical`

Пример файла listfiles.txt:

`ОбщаяФорма.ФормаОтчета`

// Загрузка из XML:
`"C:\Program Files\1cv8\8.3.17.1851\bin\1cv8.exe" DESIGNER /IBName "erp24554_demo (ord)" /N "Администратор (ОрловАВ)" /P"" /LoadConfigFromFiles "D:\test\xml" -listFile "d:\test\listfiles.txt" -Format Hierarchical`

Пример файла listfiles.txt:

`CommonForms\ФормаОтчета.xml`

Команда позволит не использовать буфер обмена при копировании объектов из тестовой базы в продуктовую. А также позволит исправлять проблемы объединения форм через такие инструменты как git (дублирование id элементов)

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/945517

**Comment by PerlAmutor** [comment]
А можно сделать опцию отображения других объектов метаданных в дереве Интерфейсной панели, таких как модули (общие модули, модули объектов, модули общих форм, внешние объекты), а то их получается выгрузить будет невозможно?

**Comment by tormozit** [comment]
Нет. Делать альтернативный конфигуратор я не планирую. Инструмент имеет другое назначение как следует из названия. А предложенная тобой функция у него побочная.

**Comment by PerlAmutor** [comment]
А "Хранилища настроек" и "Критерии отборов"? У них тоже есть свои формы. Перечисления есть, а хранилищ настроек и критериев отборов - нет.

**Comment by tormozit** [comment]
Думаю нехорошо валить все пожелания по этому инструменту в одну заявку.

**Comment by tormozit** [comment]
Реализовано в 6.29

**Comment by PerlAmutor** [comment]
Выгрузка происходит в формате Plain вместо Hierarchical и формы документов не выгружаются, пробовал на документе ERP РеализацияТоваровУслуг.

**Comment by tormozit** [comment]
Выгрузку форм добавлю https://www.hostedredmine.com/issues/946131
Плоский формат выбран умышленно. Он больше подходит для небольших выгрузок. Его слабым местом является только превышение длины имени файла в 256 символов в NTFS.

**Comment by tormozit** [comment]
добавил формы в 6.31

**Comment by tormozit** [comment]
Теперь всегда используется иерархический формат https://www.hostedredmine.com/issues/1008090
