### ISSUE TITLE
Редактор объекта БД. Редактор строки. Значение не является значением объектного типа

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#215]
https://user-images.githubusercontent.com/87958986/169860806-68cfe286-7168-4616-bfdf-6075798a3f5a.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.28.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Выбрал документ
3. Выбрал галочку "Вместе с движениями"
4. Перешел на вкладку "Движения"
5. Выбрал движения, вызвал команду "Редактор строки"
6. Выбрал реквизит и попробовал изменить его через "три точки"
7. Получил окно с ошибкой:

```
Значение не является значением объектного типа (Метаданные)
{ВнешняяОбработка.ирПлатформа.Форма.СтрокаТаблицы.Форма(208)}:			МетаРеквизит = ПоляТаблицыБД.Найти(ИмяПоляТаблицы, "Имя").Метаданные;
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/945600

**Comment by PerlAmutor** [comment]
> Ошибку воспроизвел https://www.hostedredmine.com/issues/937134

Эта ссылка ведет на другую проблему

**Comment by tormozit** [comment]
ссылку на задачу исправил

**Comment by tormozit** [comment]
Исправлено в 6.29
