### ISSUE TITLE
Консоль запросов. Параметр ВидДвижения. Странное поведение.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#216]
https://user-images.githubusercontent.com/87958986/170083182-61ad1bc5-6130-4aeb-80e0-76df79e80e46.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.28.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Сформировал текст запроса:
```
ВЫБРАТЬ ПЕРВЫЕ 1
	ТоварыНаСкладах.Регистратор КАК Регистратор
ИЗ
	РегистрНакопления.ТоварыНаСкладах КАК ТоварыНаСкладах
ГДЕ
	ТоварыНаСкладах.ВидДвижения = &ВидДвижения
```
3. Перешел на вкладку Параметры и начал выбирать ВидДвижения
4. Окно выпадающего списка иногда отображается в верхнем левом углу экрана
5. Значение параметра иногда приходится выбирать по два раза, т.к. выпадающий список не закрывается после выбора значения

**Ожидаемое поведение**
Как и для остальных параметров

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/945657

**Comment by tormozit** [comment]
Исправлено в 6.29
