### ISSUE TITLE
Проблема открытия текстового поля с текстом в JSON

### ISSUE THREAD

**Issue by TOLCOM31** [tormozit/RDT1C#217]
**Программное окружение**
Портативный 6.29.1p Microsoft Windows [Version 10.0.14393] server 2016
<details><summary>Информация для технической поддержки</summary>

!!!Не удалять пустую строку выше.
Платформа: 8.3.13.1644
Режим БД: клиент-серверный
Конфигурация. Название: Управление торговым предприятием для Украины, редакция 1.2 (1.2.37.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_2_13
Инструменты разработчика. Версия: Портативный 6.29.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. В консоли кода
2. При нажатии на значение переменной(тип строка, по факту json), открылась форма "Редактор текста"
3. Получил окно с ошибкой {ВнешняяОбработка.ирПлатформа.Форма.Текст.Форма(402)}: Метод объекта не обнаружен (Init)
	мРедакторJSON = Элемент.Документ.defaultView.Init();
[визуал проблемы](https://es8estro.s3.eu-central-1.amazonaws.com/marketingPromo/20220608091747_33.jpg)

**Ожидаемое поведение**
Какая реакция программы ожидалась?
возможность редактирования или просмотра текста или структури json

**Comment by tormozit** [comment]
Нужна информация для тех. поддержки

**Comment by tormozit** [comment]
Нужно сообщать отдельным сообщением в заявке об исправлении замечаний. Иначе сайт не отправит уведомление.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/946350

**Comment by tormozit** [comment]
исправлено в 6.31

**Comment by tormozit** [comment]
Если протестировал, закрывай заявку
