### ISSUE TITLE
Поиск объекта по идентификатору

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#218]
Столкнулся с ошибкой в ЖР типа "Ошибка при попытке вставки записи с неуникальным значением ссылки", где был указан идентификатор объекта. С ходу понять, что именно за объект скрывается в идентификаторе типа "a813faa2-f578-11e4-92f1-0050568b35ac" не получится. Думал ИР справится и попытался сделать подобное как на видео

https://user-images.githubusercontent.com/87958986/173213633-98c1d0a4-0c28-4d17-8bc4-2a040627cb08.mp4

Как видно, не зная объект метаданных - идентификатор бесполезен. Однако в БСП есть функция, которая распознает штрих-коды печатных форм только по идентификатору, перебирая в запросе все таблицы метаданных в попытке найти нужный объект по всей базе.

Предложение заключается в том, чтобы сделать аналог такого же поиска в обработке Редактор Объекта БД, если в качестве основной таблицы ничего не выбрано. Сначала предупредить пользователя, что поиск может длится долго и хочет ли он продолжать. Поиск делать не одним запросом (на ERP это приведет к ошибке SQL о "Too complex query", а запросами в цикле с возможностью его прервать. Если результат поиска даст больше одного найденного объекта - открывать список значений с результатами, чтобы пользователь сам решил какой объект он хочет открыть или хочет ли он сохранить полученный список куда-нибудь.

**Comment by tormozit** [comment]
Нужен скриншот события журнала регистрации. Не понял, почему там тип объекта нельзя понять.

**Comment by tormozit** [comment]
Нашел похожую ошибку MSSQL http://1cprovse.blogspot.com/2015/03/blog-post.html . Из нее можно однозначно идентифицировать тип ссылки.

**Comment by tormozit** [comment]
Это будет затратная и часто неоправданно затратная операция. Думаю, пользователь будет ею злоупотреблять, т.е. использовать без веской причины и решать задачу дольше чем можно было бы. На мой взгляд в подавляющем большинстве случаев тип ссылки можно понять по контексту.

Нашел похожие ошибки MSSQL и там вроде можно однозначно идентифицировать тип ссылки:
http://1cprovse.blogspot.com/2015/03/blog-post.html - _Reference99
https://forum-1c.ru/index.php?topic=68997.0 - dbo._Chrc477

Также в комментариях в к похожему на желаемый тобой инструмент я задавал вопрос, когда он необходим https://infostart.ru/public/547261/

**Comment by PerlAmutor** [comment]
> Нужен скриншот события журнала регистрации. Не понял, почему там тип объекта нельзя понять.

```
Команда КомандаОбработки: Ошибка выполнения:
Запись с такими ключевыми полями существует! : dbo_data1C: 2022-06-10, a1d65366-3c71-11ec-8e9d-020036000392, 04.06.2022, 2 (Таблица: dbo_data1C; Номер строки: 3053)
{ВнешняяОбработка.ВыгрузкаДанныхДляВнешнегоИсточника.МодульОбъекта(1215)}:        ЗаписиД.Записать();
{ВнешняяОбработка.ВыгрузкаДанныхДляВнешнегоИсточника.МодульОбъекта(1176)}:        ВыгрузитьДанныеНаSQL(Выб, ДатаОтсчета);
{ВнешняяОбработка.ВыгрузкаДанныхДляВнешнегоИсточника.МодульОбъекта(32)}:            ВыгрузитьДанныхНаДатуНаСервере(ТекущаяДатаСеанса());
{ОбщийМодуль.ДополнительныеОтчетыИОбработки.Модуль(1978)}:		ВнешнийОбъект.ВыполнитьКоманду(ИдентификаторКоманды);
{ОбщийМодуль.ДополнительныеОтчетыИОбработки.Модуль(2047)}:		ВыполнитьКомандуДополнительногоОтчетаИлиОбработки(
{ОбщийМодуль.ДополнительныеОтчетыИОбработки.Модуль(337)}:	РезультатВыполнения = ВыполнитьКомандуВнешнегоОбъекта(ВнешнийОбъект, ИдентификаторКоманды, ПараметрыКоманды, АдресРезультата);
{ОбщийМодуль.ДополнительныеОтчетыИОбработки.Модуль(1725)}:		ВыполнитьКоманду(Новый Структура("ДополнительнаяОбработкаСсылка, ИдентификаторКоманды", ВнешняяОбработка, ИдентификаторКоманды), Неопределено);

по причине:
Запись с такими ключевыми полями существует! : dbo_data1C: 2022-06-10, a1d65366-3c71-11ec-8e9d-020036000392, 04.06.2022, 2 (Таблица: dbo_data1C; Номер строки: 3053)
```

**Comment by tormozit** [comment]
Вроде это в коде внешней обработки. Значит явно доработки под конкретного заказчика. Что мешает доработать код выгрузки и сообщать тип объекта в исключении или писать его в журнал? Не считаю, что такой пример часто встречается. Написать на коленке можно много всяких проблем. Я все таки хочу опираться на распространенные проблемы, которые действительно неэффективно или невозможно решать существующими способами.

Изначально ты писал про ошибку "Ошибка при попытке вставки записи с неуникальным значением ссылки". Вот она действительно относительно широко распространена. Думал ты именно по ней приведешь пример.
