### ISSUE TITLE
Сравнивать объекты, переданные из редактора объекта, по аналогии с командой "сравнить строки" в дин.списке

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#219]
Совсем недавно узнал, что есть возможность сравнивать две ссылки в дин.списке.
https://www.hostedredmine.com/issues/946610
Я очень часто делаю нечто похожее: открываю два объекта в двух разных редакторах объектов, вывожу в таб.документы списки реквизитов со значениями и сравниваю эти таб.документы.
Инструмент "сравнение объектов" делает тоже самое только лучше и быстрее.

Мое пожелание - добавить возможность прямо из редактора объекта или из глобально меню передавать для сравнения ссылки в инструмент "сравнение объектов".

Что-то похожее очень удобно сделано для таблиц значений и их буферов сравнения/обмена.
Передать в буфер сравнения можно много откуда, а потом вызывается сравнение переданных таблиц.
Аналогичный механизм для сравнения ссылок и их внутренностей был бы очень полезным.

**Comment by tormozit** [comment]
Часть пожелания покроет задача по окну "Сравнение объектов" https://www.hostedredmine.com/issues/946637

**Comment by tormozit** [comment]
Создал задачу по редактору объекта БД https://www.hostedredmine.com/issues/946642

**Comment by tormozit** [comment]
Также создал задачи по сравнению объектов БД через глобальное меню
https://www.hostedredmine.com/issues/946669
https://www.hostedredmine.com/issues/946674

**Comment by tormozit** [comment]
Реализовано в 6.33
