### ISSUE TITLE
Консоль запросов. Параметр типа Список, невозможно выбрать тип

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#22]
https://user-images.githubusercontent.com/87958986/130102641-b3aaa057-7784-46d1-ac3b-e9c61a874f28.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.05.2p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

При выставлении типа параметра "Список" в консоли запросов невозможно выбрать тип из-за ошибки:

```
Индекс находится за границами массива
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(6506)}:			СтрокиДляКопирования.Добавить(мТаблицаРедактируемыхТипов.НайтиСтроки(КлючПоиска)[0]);
{ВнешняяОбработка.ирПлатформа.Форма.ВыборРедактируемыхТипов.Форма(124)}:	РедактируемыеТипы.Загрузить(мПлатформа.ТаблицаРедактируемыхТиповИзОписанияТипов(ОграничениеТипа));
{ВнешняяОбработка.ирОбщий.МодульОбъекта(24005)}:	РезультатВыбора = ФормаРедактора.ОткрытьМодально();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(21833)}:		НовыйТипИлиЗначение = ВыбратьРедактируемыйТипЛкс(ОграничениеТипа);
{ВнешняяОбработка.ирПлатформа.Форма.СписокЗначений.Форма(236)}:	ирОбщий.ПолеВводаКолонкиРасширенногоЗначения_НачалоВыбораЛкс(ЭтаФорма, ЭлементыФормы.Таблица, СтандартнаяОбработка, ЭлементыФормы.Таблица.ТекущаяСтрока.Значение, Истина);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(21231)}:			РезультатВыбора = ФормаРедактирования.ОткрытьМодально();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(21723)}:		Результат = ОткрытьЗначениеЛкс(РасширенноеЗначение, РедактированиеРазрешено, СтандартнаяОбработка,,, ПринудительноВОтдельнойФорме,, ТабличноеПоле);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(21853)}:			ЗначениеИзменено = ЯчейкаТабличногоПоляРасширенногоЗначения_ВыборЛкс(ЭтаФорма, ТабличноеПоле, СтандартнаяОбработка, РасширенноеЗначение, Истина, Истина, Данные) Или ЗначениеИзменено;
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(3579)}:	Если ирОбщий.ПолеВводаКолонкиРасширенногоЗначения_НачалоВыбораЛкс(ЭтаФорма, ЭлементыФормы.Параметры, СтандартнаяОбработка, , ИспользоватьОграничениеТипа) Тогда 
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932235

**Comment by tormozit** [comment]
Исправлено в 6.05.3
