### ISSUE TITLE
Редактор объекта БД. Ошибка при вызове редактора строки

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#220]
https://user-images.githubusercontent.com/87958986/175557470-f91b0e99-58e2-4af0-a2db-05cb74fba90d.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.32.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Редактор объекта БД
2. Выбрал документ с движениями, перешел на вкладку движений
3. Нажал кнопку Редактор строки
4. Получил окно с ошибкой:

```
Значение не является значением объектного типа (СвязиПараметровВыбора)
{ВнешняяОбработка.ирПлатформа.Форма.СтрокаТаблицы.Форма(53)}:			СтрокаСвойства.СвязиПараметровВыбора = ирОбщий.ПредставлениеСвязейПараметровВыбораЛкс(МетаРеквизит.СвязиПараметровВыбора);
{ВнешняяОбработка.ирПлатформа.Форма.СтрокаТаблицы.Форма(11)}:	ОбновитьСоставСвойств(Истина);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(22367)}:	Форма.Открыть();
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4542)}:	ирОбщий.ОткрытьРедакторСтрокиТаблицыЛкс(ЭтаФорма, ТабличноеПоле, ИмяТаблицыБДТабличногоПоля, фОбъект.СвязиИПараметрыВыбора);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/946797

**Comment by tormozit** [comment]
Исправлено в 6.33
