### ISSUE TITLE
Редактор объекта БД. Имя/Синоним не применяется сразу после загрузки движений

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#221]
https://user-images.githubusercontent.com/87958986/175558647-e3f4c3a8-b330-4a6e-9229-3f0d8d0a038f.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.32.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Редактор объекта БД
2. Установил флажок "Имя/Синоним"
3. Вижу, что в табличных частях вместо имен стал отображаться синоним
4. Установил флажок "Вместе с движениями"
5. Вижу, что в движениях флажок "Имя/Синоним" не применилось. Применяется только при переустановке флажка.

**Ожидаемое поведение**
При загрузке движений учитывать флажок "Имя/Синоним" и применять настройку

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/946798

**Comment by tormozit** [comment]
Исправлено в 6.33
