### ISSUE TITLE
Редактор объекта БД. Показывает ложную информацию в проводках.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#222]
https://user-images.githubusercontent.com/87958986/175560399-ba7a7283-a8dc-4d45-9dde-be11e81ef824.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.32.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Редактор объекта БД
2. Выбрал документ с проводками
3. Вижу, что на Счете отключен признак "Валютного учета"
4. При этом вижу, что в ячейках строки "ВалютаДт/Кт" установлено пустое значение ссылки типа "СправочникСсылка.Валюта"
5. Проверочный запрос показывает, что в действительности там установлено значение null

**Ожидаемое поведение**
При проверке состояния учета данное поведение инструмента может ввести в заблуждение о некорректном формировании проводок

**Comment by tormozit** [comment]
Понимаю, что это несколько неудобно. Но это - задуманное поведение. Одна из главных задач редактора - редактирование. А для редактирования нужны чистые типы у колонок. Движения читаются запросом, который всегда в описание типов каждой колонки добавляет тип NULL и таким образом делает его составным. Для редактирования это очень неудобно. Поэтому я удаляю тип NULL в считанных таблицах движений. При записи же значения NULL у меня всегда устанавливаются в соответствии с признаками учета счетов.
