### ISSUE TITLE
Редактор объекта БД. Не работает "Переключить активность всех строк"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#223]
https://user-images.githubusercontent.com/87958986/175562586-f4ce8d6f-6c7d-43eb-bb36-b63d435c0006.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.32.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Редактор объекта БД
2. Выбрал документ, установил признак "Вместе с движениями"
3. Перешел на вкладку движений
4. Вызвал команду "Переключить активность всех строк"
5. И ничего не произошло

**Ожидаемое поведение**
Снятие/Установка признака "Активность"
+ не давать переключать Активность одной строки без переключения других строк в этот же признак, т.к. платформа все равно не даст записать документ в пределах которого имеются строки движений с разными значениями активности

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/946799

**Comment by tormozit** [comment]
Исправлено в 6.33
