### ISSUE TITLE
Редактор объекта БД. Исследовать при пустой таблице формы регистра

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#224]
https://user-images.githubusercontent.com/87958986/175569264-d5032ec7-eab9-4bb6-8e03-7faea9b7943a.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.32.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Редактор объекта БД
2. Выбрал документ с движениями
3. Установил флажок "Вместе с движениями", перешел на вкладку с движениями, снял флажок "Вместе с движениями"
4. Вызвал команду " \ Командная панель \ Прочее \ Исследовать"
5. Получил окно с ошибкой:

```
Значение не является значением объектного типа (ТипРегистра)
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1845)}:		лНаборЗаписей = Новый (ТекущаяСтрока.ТипРегистра + "НаборЗаписей." + ТекущаяСтрока.Имя);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.33
