### ISSUE TITLE
Тотальный крэш толстого клиента при попытке изменить текст запроса в консоли запросов ИР

### ISSUE THREAD

**Issue by agithubber2** [tormozit/RDT1C#225]
**Программное окружение**

<details>  
<summary>Информация для технической поддержки</summary>  

!!!Не удалять пустую строку выше.
Получить эту информацию можно по кнопке "Информация для технической поддержки"
в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1

Платформа: 8.3.19.1522
Режим БД: файловый
Конфигурация. Название: Бухгалтерия для Беларуси, редакция 2.1 (2.1.42.10)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.32.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. Адаптация1 ()
Расширения. ИнструментыРазработчикаTormozit (6.32.1e)
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru_RU
Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов ИР"
2. Открыл сохранённый файл .sel (прилагаю)
3. Нажал кнопку "Структура--> Изменить--> Попытался изменить (удалить) любой символ текста запроса" 
4.  Далее мгновенно ошибка :
"Значение не является значением объектного типа (ПараметрыПодключенияПО)"
Жму "подробно"
Пишет:
"Значение не является значением объектного типа (ПараметрыПодключенияПО)
{ОбщийМодуль.МенеджерОборудованияКлиент.Модуль(2084)}: ПараметрыПодключенияПО = глПодключаемоеОборудование.ПараметрыПодключенияПО; //Массив Из Структура, где: *Параметры - Структура - .
{МодульУправляемогоПриложения(157)}: Результат = МенеджерОборудованияКлиент.ОбработатьСобытиеОтУстройства(ОписаниеСобытия, ОписаниеОшибки);"
И все - тотальный крэш толстого клиента только перезапуск.
Перепробовал кучу последних версий ИР - везде эта ошибка
Раньше никогда ничего такого не было
[контрольОтрицатОстатков.sel.zip](https://github.com/tormozit/RDT1C/files/8983844/sel.zip)

**Comment by agithubber2** [comment]
Догадался, в чём дело.
Проблема во включённых по умолчанию в ИР (абсолютно лично мне не нужных) функций: "Использовать эмуляцию нажатия клавиш" и (тоже выключил на всяк. случ. ) "Перехват клавиатурного ввода в обычном приложении".
Стоило на х.. выключить эти навороты - и проблема исчезла.
Стоило бы, возможно, придумать два варианта работы расширения: "базовый" и "расширенный". 
Базовый , в идеале, чтобы мог работать в тонком клиенте, или, как минимум, не содержал 60%-80% редких "экзотических"  опций и кнопок в интерфейсе, а "Расширенный" - ну пусть и дальше поражает нас мощью и пестрит десятками загадочных кнопочек в интерфейсе.

**Comment by tormozit** [comment]
Флажок "Перехват клавиатурного ввода в обычном приложении" как следует из названия должен применяться только в обычном приложении. А у тебя проблема возникает в управляемом приложении. Прошу проверить еще раз влияние чисто этого флажка на поведение управляемого приложения.

**Comment by agithubber2** [comment]
Отвечаю: 
1) Флажок "Перехват клав. ввода в ОБЫЧНОМ приложении" я выключил тогда на всякий случай, так как действительно я же работаю в управляемом. Однако ВКЛючение обратно этого флажка мгновенно ВЕРНУЛО проблему!
2) Включение/Выкл флажка "Использовать эмуляцию нажатия клавиш" НЕ приводит , не влияет на появление проблемы

**Comment by tormozit** [comment]
>     1. Флажок "Перехват клав. ввода в ОБЫЧНОМ приложении" я выключил тогда на всякий случай, так как действительно я же работаю в управляемом. Однако ВКЛючение обратно этого флажка мгновенно ВЕРНУЛО проблему!

Ошибку некорректной работы флажка воспроизвел https://www.hostedredmine.com/issues/946810

**Comment by tormozit** [comment]
По поводу основной проблемы. Очень похоже, что в твоей конфигурации имеется ошибка. Она заключается в том, что обработчик события  ОбработкаВнешнегоСобытия() в модуле управляемого приложения обращается к глобальной переменной глПодключаемоеОборудование, которая не была инициирована. Исправить это можно оборачиванием тела этого обработчика в условие "глПодключаемоеОборудование <> Неопределено"

**Comment by tormozit** [comment]
Если исправить конфигурацию возможности нет, то временно можно использовать запуск сеанса с параметром ОтключитьПерехватКлавиатурыИР. Сам перехват клавиатуры, как следует из описания, нужен для многих удобств. В частности для глобального меню https://infostart.ru/1c/articles/1273456 . Отключив его, они станут тебе недоступны.

**Comment by tormozit** [comment]
Если в конфигурации не включена возможность изменения, то можно создать свое расширение конфигурации и в нем исправить ошибку заместив метод на его условный вызов.

**Comment by agithubber2** [comment]
> Если в конфигурации не включена возможность изменения, то можно создать свое расширение конфигурации и в нем исправить ошибку, заместив метод на его условный вызов.

Конечно, расширение у меня есть, оно всегда подключено к конф., в него можно добавить.

**Comment by agithubber2** [comment]
В общем, по твоей (а то в телеграме обращался по привычке на Вы, но потом вспомнил, что ты просил не "выкать")) рекомендации добавил в расширение такой код:

	&ИзменениеИКонтроль("ОбработкаВнешнегоСобытия")
	Процедура Адапт1_ОбработкаВнешнегоСобытия(Источник, Событие, Данные)
		#Вставка
		Если глПодключаемоеОборудование = Неопределено Тогда
			Возврат;	
		КонецЕсли;
		#КонецВставки

		// ПодключаемоеОборудование
		// Подготовить данные

		ОписаниеСобытия = Новый Структура();
		ОписаниеОшибки  = "";

		ОписаниеСобытия.Вставить("Источник", Источник);
		ОписаниеСобытия.Вставить("Событие",  Событие);
		ОписаниеСобытия.Вставить("Данные",   Данные);

		глПодключаемоеОборудованиеСобытиеОбработано = Ложь;

		// Передать на обработку данные.
		Результат = МенеджерОборудованияКлиент.ОбработатьСобытиеОтУстройства(ОписаниеСобытия, ОписаниеОшибки);
		Если Не Результат Тогда
			ОбщегоНазначенияКлиентСервер.СообщитьПользователю(НСтр("ru='При обработке внешнего события от устройства произошла ошибка.'")
			+ Символы.ПС + ОписаниеОшибки);
		КонецЕсли;
		// Конец ПодключаемоеОборудование

	КонецПроцедуры


Надеюсь, код такой, какой примерно ты имел в виду.
Только после этого ошибка пропала и без отключения опции "перехват клав. ввода в обычном приложении" (без этого кода в расширении последняя версия ИР по-прежнему выдавала ту же ошибку

**Comment by tormozit** [comment]
Если проблема решена, закрывай заявку
