### ISSUE TITLE
Консоль кода. Сломалось выполнение кода на сервере.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#226]
https://user-images.githubusercontent.com/87958986/175773005-ffa2023c-e30f-44e2-9485-e97827f40e5e.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.32.1p
> Инструменты разработчика. Инструмент: Консоль кода
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Консоль кода
2. Ввел код:
`т = ТекущаяДатаСеанса();`
3. Переключил контекст на "Сервер"
4. Вызвал команду Выполнить
5. Получил сообщение с ошибкой:

`Редактор встроенный: Строка кода 1: {(1,44)}: Переменная не определена (ирОбщий)`

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/946813

**Comment by tormozit** [comment]
Исправлено в 6.33
