### ISSUE TITLE
Редактор объекта БД. Редактор строки. Метаданные

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#228]
https://user-images.githubusercontent.com/87958986/175783252-9843d878-6f5a-4714-9799-06a2cc460001.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.32.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Редактор объекта БД
2. Выбрал документ с движениями
3. На вкладке с движениями регистра выполнил команду "Редактор набора"
4. В открывшемся инструменте выполнил команду "Редактор строки"
5. Получил окно с ошибкой:

```
Значение не является значением объектного типа (Метаданные)
{ВнешняяОбработка.ирПлатформа.Форма.СтрокаТаблицы.Форма(52)}:			МетаРеквизит = ПоляТаблицыБД.Найти(ИмяКолонкиДанных, "Имя").Метаданные;
{ВнешняяОбработка.ирПлатформа.Форма.СтрокаТаблицы.Форма(11)}:	ОбновитьСоставСвойств(Истина);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(22367)}:	Форма.Открыть();
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4542)}:	ирОбщий.ОткрытьРедакторСтрокиТаблицыЛкс(ЭтаФорма, ТабличноеПоле, ИмяТаблицыБДТабличногоПоля, фОбъект.СвязиИПараметрыВыбора);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел. Технически это та же ошибка https://github.com/tormozit/RDT1C/issues/220

**Comment by tormozit** [comment]
Инструмент тут все тот же - "Редактор объекта БД". А кнопка называется "Редактор набора" для придания ей отличия от кнопки открытия объекта из ячейки.

**Comment by tormozit** [comment]
Исправлено в 6.33

**Comment by PerlAmutor** [comment]
У меня ошибка продолжает проявляться на версии 6.33p.

**Comment by tormozit** [comment]
Проверил еще раз на том же регистре с той же текущей колонкой. Ошибка не воспроизводится.

**Comment by tormozit** [comment]
Т.к. ты вручную обновлял портативный вариант, то допускаю что мог нарушить правило - перезапускать сеанс.
После запуска нового сеанса ошибка воспроизводится СТРОГО по видео?

**Comment by PerlAmutor** [comment]
Перезапустил, не помогло.


https://user-images.githubusercontent.com/87958986/175983528-f35a5601-e89c-46b5-8aa4-13c4d21e9c6f.mp4

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/946859

**Comment by tormozit** [comment]
Исправлено в 6.34
