### ISSUE TITLE
Редактор объекта БД. Не определяется тип значения.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#229]
https://user-images.githubusercontent.com/87958986/175783351-2a8dabe2-5c78-45c6-ba65-1ac4dc5fc915.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.32.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД" кнопкой "Редактор набора"
2. В таблице формы отбора остаются пустыми колонки "Тип значения" и "Имя типа значения"

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/946814

**Comment by tormozit** [comment]
Исправлено в 6.33
