### ISSUE TITLE
Колонки БД. Ошибка при закрытии ИР.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#23]
https://user-images.githubusercontent.com/87958986/130321143-6a5740e0-0676-4c6d-8ef1-b4caba758d03.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.05.2p
> Инструменты разработчика. Инструмент: Колонки БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

Автоматически не закрывается форма "Колонки БД" при закрытии ИР, что приводит к ошибкам

```
Значение не является значением объектного типа (ЛиСеансТолстогоКлиентаЛкс)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(40525)}:	Если ирКэш.ЛиСеансТолстогоКлиентаЛкс() Тогда 
{ВнешняяОбработка.ирОбщий.МодульОбъекта(39151)}:	Если Не ПроверитьЧтоСеансТолстогоКлиентаЛкс() Тогда
{ВнешняяОбработка.ирОбщий.МодульОбъекта(37681)}:		ОткрытьСправкуПоПодсистемеЛкс(ЭтаФорма);
{ВнешняяОбработка.ирКолонкиБД.Форма.Форма.Форма(130)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);

```

**Comment by tormozit** [comment]
исправлено в 6.06.1
