### ISSUE TITLE
Редактор набора. Активность

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#230]
https://user-images.githubusercontent.com/87958986/175783614-ec29e6ad-a049-44b4-adbf-48b6889ae7be.mp4
<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.32.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор набора"
2. Снял флажок активности у одной строки
3. Записал набор
4. Получил окно с ошибкой:

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(16570)}: Ошибка при вызове метода контекста (Записать): Запись не верна! Не совпадает активность записей (Регистр накопления: Движения Денежные средства - Доходы/Расходы; Номер строки: 2)
МенеджерВременныхТаблиц: МенеджерВременныхТаблиц
{ВнешняяОбработка.ирОбщий.МодульОбъекта(16646)}:						ВызватьИсключение НовоеОписаниеОшибки;
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1286)}:		ирОбщий.ЗаписатьОбъектЛкс(СтруктураОбъекта.Методы, , РежимЗаписи);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1459)}:				НоваяСсылка = ЗаписатьОбъект(?(ТипЗнч(РежимЗаписи) = Тип("Строка"), РежимЗаписиДокумента.Запись, РежимЗаписи), ОбратимаяЗапись);
```

**Ожидаемое поведение**
Требуется сделать аналогичный запрет на интерактивное изменение признака активность для строк, чтобы активность переключалась для всех строк сразу.

**Comment by tormozit** [comment]
Кажется это примерно то же https://github.com/tormozit/RDT1C/issues/223 и там я уже на картинке в задаче показал что построчное изменение будет недоступно.

**Comment by tormozit** [comment]
Исправлено в 6.33

**Comment by PerlAmutor** [comment]
При изменении активности строк не обновляются флажки в связанном открытом редакторе строки.

**Comment by tormozit** [comment]
По редактору строки проблема старая, т.е. точно не связана с исправлением проблемы заявки. Поэтому кажется логичным ее оформлять отдельной заявкой. Исправлю.
