### ISSUE TITLE
Редактор объекта БД. Переключение активности строк не обновляет связанную форму редактора строки

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#231]
https://user-images.githubusercontent.com/87958986/175986978-80afc256-2842-426a-8f54-200b8d77f8f7.mp4
<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.33.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Редактор объекта БД
2. Открыл документ и загрузил его движения
3. Вызвал команду "Редактор строки"
4. Вызвал команду переключения Активности строк
5. В открытом окне "Редактора строки" активность строки осталась с прежним значением

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/946852

**Comment by tormozit** [comment]
Исправлено в 6.34
