### ISSUE TITLE
Редактор изменений на узлах. Проблема производительности

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#232]
https://user-images.githubusercontent.com/87958986/177005306-25f1d247-d75a-420c-8cdb-d734df558228.mp4
<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.33.1p
> Инструменты разработчика. Инструмент: Редактор изменений на узлах
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор изменений на узлах"
2. Выставил 2 флажка: "Вычислять количество" и "Только с наличием изменений"
3. При установке и снятии пометки строк каждый раз вызывается вычисление типов метаданных. На больших конфигурациях типа ERP в клиент-серверной базе это может выполняться около минуты.

**Ожидаемое поведение**
Возможно присутствует избыточное вычисление метаданных для конфигурации каждый раз, если они могут измениться лишь при реструктуризации (обновлении).

**Comment by tormozit** [comment]
В этой ситуации индикатор в строке состояния показывает прогресс построения дерева таблиц изменений, отображаемого пользователю. Скорость выполнения этой операции не должна зависеть от сервера 1С или СУБД. В твоем ролике она приемлемая. Продемонстрируй ситуацию, когда она не приемлемая, и желательно сразу с замером производительности.

**Comment by tormozit** [comment]
Ускорить эту операцию можно путем указания конкретного плана обмена. Также отключение отладки сеанса немного ускорит ее.

**Comment by tormozit** [comment]
Сделал небольшую оптимизацию построения дерева https://www.hostedredmine.com/issues/947010

**Comment by tormozit** [comment]
Оптимизация реализована в 6.34.1
