### ISSUE TITLE
Редактор объекта БД. Команда Колонка не переходит к нужной колонке.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#233]
https://user-images.githubusercontent.com/87958986/177184886-03d40674-0b40-478d-bbbb-e4ea4200369b.mp4
<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.34.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Выбрал документ с движениями.
3. Открыл "Редактор набора"
4. Вызвал команду "Редактор строки"
5. Установил курсор на нужную колонку в Редакторе строки
6. Вызвал команду "Колонка"
7. Вместо перехода курсора к выбранной ячейки с колонкой в табличном поле строк движений, курсор просто перескакивает на другую колонку в Редакторе строки
8. Аналогично, команда "Строка" не выбирает нужно строку и выбранную колонку в Табличном поле движений. Вместо этого курсор просто перескакивает на колонку, неважно на какую строку при этом был установлен курсор.

**Comment by tormozit** [comment]
У команд есть подсказки. Работает как там обещано.
