### ISSUE TITLE
Консоль запроса. Выгрузка таблицы "Свойства"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#234]
https://user-images.githubusercontent.com/87958986/177186308-5341863a-c268-4934-a645-9aec473cd44e.mp4
<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.34.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. В результате запроса выделил колонку в таблице формы "Свойства"
3. Нажал комбинацию Ctrl+~
4. В форме диалога выбрал "Вывести строки"
5. В Таблицу Значений попадает только колонка "Свойство". Колонка "Значение" - отсутствует, хотя флажок выбора был установлен

**Comment by tormozit** [comment]
В окне "Параметры вывода строк" в строке колонки "Значение" не заполнено свойство "Данные". Это означает что колонка не отображает данные источника и текст в нее подставляется динамически. Содержимое таких колонок можно выводить только с выключенным флажком "Без оформления", т.е. при выводе строк "с оформлением", о чем сообщается в подсказке к этому флажку.
Кстати системная команда "Вывести строки" всегда выводит "с оформлением". А в моей форме этот флажок запоминается.
Попробую сделать интерфейс настройки в этой ситуации более удобным.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/947074

**Comment by tormozit** [comment]
Реализовано в 6.35
