### ISSUE TITLE
Новые функции для получения описания параметров и возвращаемого значения для процедур и функций

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#236]
Некоторое время назад я стал активно делать описания процедур и функций, как это указано по стандарту - https://its.1c.ru/db/v8std/content/453/hdoc.
Я создаю заготовку описания через Рефакторинг - Создать описание процедуры/функции.
Потом в начале процедуры/функции ставлю точку останова, вычисляю по очереди значения всех параметров и копирую их типы в описание.
Если это функция, то останавливаюсь точкой останова на Возврат, и аналогично "Вычислить выражение" и копирую в блок описания для возвращаемого значения.
Еще вместо вычислить выражение можно табло задействовать.

Одновременно в ИР уже есть, например, функция ирОбщий.ОтЛкс() тоже для режима отладки.

В итоге мое пожелание - сделать две новых функции, которые можно было бы применять в режиме отладки для получения описаний параметров и возвращаемых значений в нужном формате.
Чтобы результат этих функций можно было бы сразу вставлять в блок с описаниями параметров/возвращаемого значения.

Примеры, как это могло бы приблизительно выглядеть.

Есть процедура и функция с описанием:

    // Процедура - Проц1
    //
    // Параметры:
    //  П1	 - 	 - 
    //  П2	 - 	 - 
    //  П3	 - 	 - 
    //
    Процедура проц1(П1, Знач П2, Знач П3 = Неопределено)
    КонецПроцедуры

    // Функция - Функ1
    //
    // Параметры:
    //  П1	 - 	 - 
    //  П2	 - 	 - 
    //  П3	 - 	 - 
    // 
    // Возвращаемое значение:
    //   - 
    //
    Функция функ1(П1, Знач П2, Знач П3 = Неопределено)
    	Структура = Новый Структура;
    	Структура.Вставить("Ключ1", Неопределено);
    	Структура.Вставить("Ключ2", "Строка");
    	Структура.Вставить("Ключ3", 123);
    	Возврат Структура;
    КонецФункции

Вызов в режиме отладки для получения описания параметров:

    ОписаниеПараметровПроцедурыИлиФункции("П1, Знач П2, Знач П3 = Неопределено", П1, П2, П3)

Что в итоге получается (что можно скопировать и вставить в описание):
// Параметры:
//  П1	 - СправочникСсылка.Номенклатура - 
//  П2	 - ТаблицаЗначений - 
//  П3	 - Булево - 

Вызов в режиме отладки для получения описания возвращаемого значения:

    ОписаниеВозвращаемогоЗначенияФункции(Структура)

Что в итоге получается (что можно скопировать и вставить в описание):
// Возвращаемое значение:
//   Структура:
//     * Ключ1 - Неопределено - 
//     * Ключ2 - Строка - 
//     * Ключ3 - Число -

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/957274

**Comment by tormozit** [comment]
Реализовано в 6.62

**Comment by antonsm2011** [comment]
Спасибо!
Получается, даже не нужна отдельная функция для возвращаемого значения функции.
Можно переменную, которую функция возвращает, добавить в Текст с параметрами.
И после вычисления перенести параметр-возвращаемое значение в раздел "Возвращаемое значение".
Только останется удалить само имя переменной, т.к. в возвращаемом значении немного другой вариант записи.
// Параметры:
//  Структура - Структура - :
// Возвращаемое значение:
//  Структура

**Comment by antonsm2011** [comment]
А можно добавить еще один момент, чтобы меньше править руками для описания возвращаемого значения функции приходилось?

Сейчас выводится такая секция всегда:
// Возвращаемое значение:
//  <Тип> - 
Можно в нее добавить все то, что сейчас выводиться в раздел Параметры:, но в том формате, как надо для описания возвращаемого значения?

Приблизительно так для примера:
// Параметры:
//  Структура - Структура - :
//    * ВывестиРодительскиеДокументы - Булево - 
//    * ВывестиПодчиненныеДокументы - Булево - 
//    * ТолькоРазрешенные - Булево - 
//    * ВместеСДокументом - Булево - 
// Возвращаемое значение:
//  Структура
//    * ВывестиРодительскиеДокументы - Булево - 
//    * ВывестиПодчиненныеДокументы - Булево - 
//    * ТолькоРазрешенные - Булево - 
//    * ВместеСДокументом - Булево - 

На мой взгляд удалить скопом лишние строки проще, чем точечно в строке что-то удалять.

**Comment by tormozit** [comment]
нет
