### ISSUE TITLE
Не запускается ИР 6.34.2p.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#237]
https://user-images.githubusercontent.com/87958986/177676709-73ccf206-b839-4b00-ae98-d168b67aa1cd.mp4
<details>  
<summary>Информация для технической поддержки</summary>  

Версия ИР: 6.34.2p

</details>

**Воспроизведение проблемы**
1. Открыл портативные инструменты разработчика 6.34.2p
2. Получил окно с ошибкой:

```
Значение не является значением объектного типа (мВопросОтключенияПроверкиМодальностиЗадавался)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(29684)}:		Или ирКэш.НомерИзданияПлатформыЛкс() = "82"
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(53)}:	ирОбщий.ИнициироватьФормуЛкс(ЭтаФорма, "Обработка.ирПортативный.Форма.Форма"); // Нельзя выполнять в разделе инциализации, т.к. будет рекурсия

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/947201

**Comment by tormozit** [comment]
Исправлено в 6.34.3
