### ISSUE TITLE
Вывод в Таблицу Значений из динамического списка типовой формы. ЦветФонаШапки

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#238]
https://user-images.githubusercontent.com/87958986/178157464-bb9a7b16-2d5c-4fbf-b0a7-86311f7ed401.mp4
<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.35.1p
> Инструменты разработчика. Инструмент: Глобальное меню
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл типовую форму списка документов
2. Нажал комбинацию клавиш Ctrl+~
3. Вызвал команду "Вывести строки"
4. Получил окно с ошибкой:

```
Поле объекта не обнаружено (ЦветФонаШапки)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10326)}:			ОбластьЗаголовков.ЦветФона = ТабличноеПоле.ЦветФонаШапки;
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10152)}:	Результат = ВывестиСтрокиТабличногоПоляЛкс(ТабличноеПоле, ФормаНастройки,, выхТекущаяСтрока, НастройкиСписка);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10707)}:	Результат = ВывестиСтрокиТабличногоПоляСНастройкойЛкс(ТабличноеПоле, ВыводБезОформления, НастройкиСписка, ТекущаяСтрока);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(40634)}:		ирОбщий.ВывестиСтрокиТабличногоПоляИПоказатьЛкс(ТекущийЭлемент);
{ВнешняяОбработка.ирПортативный.МодульОбъекта(425)}:	ирОбщий.ОткрытьТаблицуЗначенийИзАктивнойУправляемойФормыЛкс(Параметры.Форма);
{(1)}:ирПортативный.ОткрытьТаблицуАктивнойФормыЛкс(ПараметрыВызова)
{ВнешняяОбработка.ирПлатформа.Форма.ГлобальноеМеню.Форма(642)}:	Выполнить("ирПортативный." + ЭлементыФормы.Команды.ТекущаяСтрока.Имя + "(ПараметрыВызова)"); // Так окно в управляемом приложении откроется в режиме блокирования владельца
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/947292

**Comment by tormozit** [comment]
Исправлено в 6.36
