### ISSUE TITLE
Автоматизированная проверка конфигурации. Прошелся по расширению.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#24]
Прошелся по расширению версии 6.05.2 Автоматизированной Проверкой Конфигураций. Большинство несущественных сообщений из отчета удалил. Пробегись взглядом, может там есть что-то критическое.
[AAC_ИР.zip](https://github.com/tormozit/RDT1C/files/7027013/AAC_.zip)

**Comment by tormozit** [comment]
Ты предлагаешь 2000 строк анализировать. А для чего? 
В ИР применено много нетрадиционных подходов, которые такие автоматизированные проверки считают "ошибками".
Вероятность найти там возможность улучшить работу программы очень мала.  Это будет очень неэффективная трата моего времени.

**Comment by PerlAmutor** [comment]
Не анализировать, я предложил лишь "пробежаться", может за что-то подозрительное глаз зацепится. 2000 строк это не те десятки тысяч, которые я отфильтровал. Если скажешь какие еще ошибки можно в игнор отправить, то могу и их исключить, список еще больше уменьшится.

**Comment by tormozit** [comment]
Не буду тратить время на анализ этой кучи. Но готов дать комментарии по 3-м выбранным тобой типам проверок, оформленным каждая в виде отдельной темы.
