### ISSUE TITLE
"Крякозябры" при запуске от имени пользователя

### ISSUE THREAD

**Issue by NikitaBolsunovskii** [tormozit/RDT1C#240]
**Программное окружение**

<details>
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1789
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия КОРП МСФО (3.1.16.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.35.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. РасшДоработкаФункционала (1.0.0.165)
Расширения. РасширениеПроверкаЗапрещенныхКонтрагентов (1.0.0.1)
Клиент. ОС: Майкрософт Windows 11 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 17763)
</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор пользователей"
2. Выбрал в списке пользователя любого с именем содержащим кириллицу.
3. Нажал кнопку "Запуск от имени".
4. Отобразилось окно с вводом логина и пароля, в логине "крякозябры".
![2022-07-12_07h31_57](https://user-images.githubusercontent.com/41104234/178409160-7ead869e-c3fe-449a-b427-176b1580c85b.gif)

**Ожидаемое поведение**
Какая реакция программы ожидалась?

Ожидается, что на шаге 4 будет запущен сеанс пользователя без дополнительного запроса логина и пароля.

**Comment by tormozit** [comment]
Очень неудобно смотреть на GIF анимацию, т.к. остановить простым путем ее невозможно. Приходится делать снимки экрана. Было бы здорово иметь обычное видео.

![изображение](https://user-images.githubusercontent.com/11896251/178410615-855ceb27-a524-48cc-a4b4-2ad5eb0f2536.png)

**Comment by tormozit** [comment]
В отладичке в модуле ирОбщий установи точку останова в методе ЗапуститьСеансПодПользователемЛкс на строке
`ЗапуститьСистему(ПараметрыЗапуска)`
Покажи значение переменной ПараметрыЗапуска

**Comment by NikitaBolsunovskii** [comment]
Насчёт gif - принято. Буду видео вставлять на будущее.

Значение переменной ПараметрыЗапуска:
 ENTERPRISE /IBConnectionString"Srvr=""RUMOW04-WIS908"";Ref=""RFL_MSFO"";" /N"АндреевР" /P"08312915372!_qQ" /UC"" /DEBUGGERURL"tcp://10.224.30.213:1561"   /DEBUG -tcp /TechnicalSpecialistMode /UseHwLicenses+ /Lru /VLru /UC 466572" 

Но запуск осуществляется через вызов:
ЗапуститьСкрытоеПриложениеИДождатьсяЗавершенияЛкс(СтрокаЗапуска,,,, Ложь, Элевация);

Строка запуска: 
"C:\Program Files\1cv8\8.3.20.1789\bin\1cv8c.exe"  ENTERPRISE /IBConnectionString"Srvr=""RUMOW04-WIS908"";Ref=""RFL_MSFO"";" /N"АндреевР" /P"08312915372!_qQ" /UC"" /DEBUGGERURL"tcp://10.224.30.213:1561"   /DEBUG -tcp /TechnicalSpecialistMode /UseHwLicenses+ /Lru /VLru /UC 466572"

**Comment by tormozit** [comment]
Выполни в консоли кода, указав удобное имя файла
```
ПолноеИмяФайла = "C:\Temp\1.bat";
ТекстовыйДокумент = Новый ТекстовыйДокумент;
ТекстовыйДокумент.УстановитьТекст("Абрам");
ТекстовыйДокумент.Записать(ПолноеИмяФайла, КодировкаТекста.OEM); 
```
Затем запусти в окне CMD этот файл. Покажи результат.

**Comment by NikitaBolsunovskii** [comment]
![image](https://user-images.githubusercontent.com/41104234/178420006-e5720607-6f22-4fdf-a3cf-4e81f8810953.png)

**Comment by tormozit** [comment]
Попробуй заставить отображаться текст корректно в этом примере.

**Comment by NikitaBolsunovskii** [comment]
Удалось побороть. Оказалось, что у меня по умолчанию использовалась кодовая страница в cmd 1251.

Удалил из реестра эту запись (может кому пригодится):
[HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe]
**"CodePage"=dword:000004e3**
"FaceName"="Lucida Console"
"FontFamily"=dword:00000036
"FontSize"=dword:000c0000
"FontWeight"=dword:00000190

"Крякозябры" пропали.

Благодарю за оперативную помощь!

**Comment by tormozit** [comment]
Cделал автоматическую установку 866-й кодовой страницы на сессию CMD https://www.hostedredmine.com/issues/947398

**Comment by tormozit** [comment]
Исправлено в 6.36
