### ISSUE TITLE
Консоль запросов. Выгрузка в ТЗ с наложенным отбором.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#241]
https://user-images.githubusercontent.com/87958986/179358675-98e0a86e-fd86-462f-a718-b7d5464b3d5a.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.35.2p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Выполнил запрос
3. Через комбинацию Alt+W установил отбор по значению в колонке
4. Вызвал команду " \ Панель \ Результат-коллекция(9) \ Командная панель \ Открыть копию"
5. Получил окно с ошибкой:

```
Индекс находится за границами массива
{ВнешняяОбработка.ирОбщий.МодульОбъекта(24309)}:					выхТекущаяСтрока = ВыгрузкаРезультата[ИндексТекущейСтроки];
{ВнешняяОбработка.ирОбщий.МодульОбъекта(39912)}:				КопияКоллекции = ТаблицаИлиДеревоЗначенийИзТаблицыФормыСКоллекциейЛкс(ИсточникДействий,,, Ложь,,, ЭтаФорма);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(9678)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/947605

**Comment by tormozit** [comment]
Исправлено в 6.36
