### ISSUE TITLE
Установка флага "Активность" при загрузке из таблицы значений

### ISSUE THREAD

**Issue by Absolemus** [tormozit/RDT1C#242]
**Программное окружение**

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.18.1779
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия для Казахстана, редакция 3.0 (3.0.40.1)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.35.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.35.2e)
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru_RU
Клиент. От имени администратора Windows: Да
Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp
</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Установил ссылку документа, который проведен и у него есть движения по регистру бухгалтерии
3. Установил флаг "Вместе с движениями" в истину
4. Перешел во вкладку "Движения"
5. Нажал на кнопку "Текущая таблица" -> "Менеджер табличного поля"
6. В форме "Менеджер табличного поля" нажал на кнопку "Открыть данные связанного табличного поля в отдельном окне"
7. Открывшуюся таблицу значений сохранил в файл с расширением ".VT"
8. В форме "Редактор объекта БД" на вкладке "Движения" нажал на кнопку "Текущая Таблица" -> "Загрузить строки"
9. В открывшемся окне нажимаю "Получить" -> "Из файла" и выбираю файл созданный в п.7
10. Вижу колонку "Активность" с флагом "Истина"
11. Нажал на кнопку "ОК"
12. На вопрос "Очистить строки таблицы" ответил "Да"
13. Вижу в загруженных строках колонку "Активность" и что во всех строках установлено значение "Ложь"

**Ожидаемое поведение**
13. Вижу в загруженных строках колонку "Активность" и что во всех строках установлено значение "Истина"

**Comment by tormozit** [comment]
Изначально в твоем обращении я понял под "загрузкой" загрузку в таблицу БД, т.е. запись. 
Для команды "Загрузить строки..." табличного поля такое поведение к сожалению является задуманным, т.к. она очень универсальная и потому эмулирует выбор значений пользователем. А колонка "Активность" недоступна для редактирования и потому для загрузки этой командой. Это можно кстати понять по списку колонок эталонной таблицы значений. 
Кажется что большого неудобства тут нет, т.к.
1. Серый цвет текста позволяет не забывать, что строки не активны
2. Нажатие переключателя активности сразу включает активность
Как считаешь?

**Comment by tormozit** [comment]
Думаю еще немного снизит неудобство такая проверка https://www.hostedredmine.com/issues/947789

**Comment by tormozit** [comment]
Добавил включение активности после загрузки https://www.hostedredmine.com/issues/947796

**Comment by tormozit** [comment]
реализовано в 6.37

**Comment by Absolemus** [comment]
Благодарю, воспроизвел проблему, по окончании увидел ожидаемое поведение
