### ISSUE TITLE
Добавить колонку с порядковым номером временной таблицы в консоли запросов

### ISSUE THREAD

**Issue by Tushkan** [tormozit/RDT1C#243]
Списка временных таблиц запроса упорядочен по имени таблицы, что не удобно при при отладке запроса с большим количеством временных таблиц.
В своей копии в файле ирКонсольЗапросов в таблице значений "ВременныеТаблицы" добавил колонку "НомерТаблицы" тип число

И внес исправления в процедуру:

```
Функция ДобавитьОписаниеВременнойТаблицы(Знач ИмяВременнойТаблицы)
	
	СтрокаТаблицы = ВременныеТаблицы.Найти(Нрег(ИмяВременнойТаблицы), "НИмя");
	Если СтрокаТаблицы = Неопределено Тогда 
		СтрокаТаблицы = ВременныеТаблицы.Добавить();
		СтрокаТаблицы.Имя = ИмяВременнойТаблицы;
		СтрокаТаблицы.НомерТаблицы = ВременныеТаблицы.Количество();
		ирОбщий.ОбновитьКопиюСвойстваВНижнемРегистреЛкс(СтрокаТаблицы);
		//ВременныеТаблицы.Сортировать("НИмя");
		ВременныеТаблицы.Сортировать("НомерТаблицы");
	КонецЕсли; 
	Возврат СтрокаТаблицы;

КонецФункции
```

Возможно это не оптимально, но инструмент сильно не курил
Проделано на версии Инструменты разработчика. Версия: Портативный 6.36.1p

**Comment by tormozit** [comment]
Табличное поле "Временные таблицы" показывает текущее содержимое менеджера временных таблиц удерживаемого клиентским приложением. Список этих таблиц мог стать результатом последовательного выполнения многих запросов создания/удаления временных таблиц. Поэтому изменять там порядок отображения таблиц не планирую.

Для работы с временными таблицами выполненного запроса служат 2 других скрытых по умолчанию табличных поля. Показал на картинке ниже.

![изображение](https://user-images.githubusercontent.com/11896251/180479789-b147fded-3c6e-4c1e-9bfd-59e8f24d18cc.png)

**Comment by tormozit** [comment]
В следующей версии добавлю подсказку для начинающих пользователей, т.к. подобные твоему вопросы/предложения поступают уже не первый раз.

Насколько помогла бы тебе новая подсказка  на картинке ниже?

`Менеджер временных таблиц. Для просмотра временных таблиц запроса используй кнопки "Структура" или "Пакет".`

![изображение](https://user-images.githubusercontent.com/11896251/180483342-fb943535-ed3f-49b5-8d98-1fd6959df7c7.png)

**Comment by Tushkan** [comment]
Подсказка - это хорошо.
Структура: может имеет смысл при показе структуры убирать с экрана "Временные таблицы", т.к. сама структура занимает много места
Пакет:  не обращал раньше внимания на этот раздел
