### ISSUE TITLE
Редактор остатков: ошибка при изменении поля Дата

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#244]
**Программное окружение**

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.15.1887
Режим БД: клиент-серверный
Конфигурация. Название: Управление торговым предприятием для Украины, редакция 1.2 (1.2.56.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_6
Инструменты разработчика. Версия: Портативный 6.38.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Редактор остатков
2. Нажал кнопку Выбрал регистр РегистрБухгалтерии.Хозрасчетный
3. Ввел дату 01.06.2022
4. Получил окно с ошибкой. При нажатии кнопки получить остатки - работает как и ожидается

{ВнешняяОбработка.ирРедакторОстатков.Форма.Форма.Форма(508)}: С помощью встроенной функции Новый (New) не могут создаваться значения примитивных типов (Неопределено)
ЭтаФорма.Регистратор = Новый (ТипЗнч(Регистратор));

![image](https://user-images.githubusercontent.com/81148850/182109506-fee2cae8-4ee0-4310-983c-47e37cf4aefe.png)

**Ожидаемое поведение**

**Comment by tormozit** [comment]
Нужен полный текст ошибки

**Comment by marv-ua** [comment]
> Нужен полный текст ошибки

{ВнешняяОбработка.ирРедакторОстатков.Форма.Форма.Форма(508)}: С помощью встроенной функции Новый (New) не могут создаваться значения примитивных типов (Неопределено)
	ЭтаФорма.Регистратор = Новый (ТипЗнч(Регистратор));

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/948013

**Comment by tormozit** [comment]
Исправлено в 6.39
