### ISSUE TITLE
Ошибка консоли запросов

### ISSUE THREAD

**Issue by LordSenya** [tormozit/RDT1C#245]
**Программное окружение**
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.13.1926
Режим БД: клиент-серверный
Конфигурация. Название: ASSOL_Рабочая ()
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_3_11
Инструменты разработчика. Версия: Портативный 6.39.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru_RU
Клиент. ОС: Microsoft Windows Server 2008 R2 Enterprise  64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Добавил параметр
3. Выбрал вид параметра "Список"
4. Двойным кликом на ячейке "Значение" открыл форму редактирования списка, добавил в него элементы, нажал кнопку ОК

**Ожидаемое поведение**
Должен был в окошке параметра быть список а там пусто. Если сначала был вид параметра "Значение"  и был выбран параметр, потом меняю на "список" то первой строкой значение, оно одно и остается. Если сразу выбрать список, то там пусо
Какая реакция программы ожидалась?
![ошибка](https://user-images.githubusercontent.com/23116313/184374571-6d24371d-a81f-4d1f-8910-346635796f68.png)

**Comment by LordSenya** [comment]
http://devtool1c.ucoz.ru/forum/2-2085-1

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/948448

**Comment by tormozit** [comment]
Исправлено в 6.40
