### ISSUE TITLE
Расширение функционала инструмента "Структура хранения БД" для работы с СУБД PostgresSQL

### ISSUE THREAD

**Issue by MelenchukEvgeniy** [tormozit/RDT1C#246]
Для клиент-серверного варианта работы хочется иметь возможность указывать параметры подключения не только к СУБД MSSQL, но и к PostgreSQL. Соответственно, при работе с PostgreSQL, хочется видеть реальные размеры таблиц - колонки "Размер данные", "Размер индексы" и "Размер общие".

**Comment by tormozit** [comment]
Какая у тебя клиентская ОС?

**Comment by MelenchukEvgeniy** [comment]
Windows 10 Pro.

**Comment by tormozit** [comment]
Открой консоль запросов ИР, выбери тип запроса ADO, на странице ADO выбери драйвер Postgre, заполни параметры. Добейся тут подключения к СУБД и выполнения простейшего запроса. Если на этом пути ты будет устанавливать какие то программы/драйверы или делать настройки в ODBC (например как тут https://infostart.ru/public/978816/ ), то фиксируй их, чтобы я потом их подсказывал пользователю.
В итоге мне нужна твоя успешная строка соединения, которую сообщает кнопка "Проверка подключения". Очень надеюсь что стандартная подойдет.

**Comment by MelenchukEvgeniy** [comment]
Сделаю. Я ограничен по времени? На работе у меня нет прав на установку любого ПО.

**Comment by tormozit** [comment]
Время не критично. Но какая то экономия времени конечно была бы, если бы я знал некоторые вещи про Postrge сразу.

**Comment by MelenchukEvgeniy** [comment]
Дома у меня почти такой же контур развёрнут. Вечером постараюсь сделать, а завтра повторить на работе вместе с админом.

**Comment by tormozit** [comment]
Когда подключишь консоль, проверь такой запрос
SELECT * FROM _CommonSettings WHERE _SettingsKey = '1'

**Comment by MelenchukEvgeniy** [comment]
Подключился.
Соединение установлено. Фактическая строка соединения:
Provider=MSDASQL.1;Persist Security Info=False;User ID=postgres;Data Source=PostgreSQL35W;Initial Catalog=upp
Запрос, который ты мне прислал, выполнился, но не дал никаких результатов. В следующем комментарии распишу свои шаги. Запрос по таблице документа, где есть одна запись, вывел одну строку в результат с данными этой самой записи.

**Comment by tormozit** [comment]
Проверь вариант со стандартным для консоли провайдером PostgreSQL OLE DB Provider. [Это ](https://ftp.postgresql.org/pub/projects/pgFoundry/oledb/PgOleDb/1.0.0.20/PgOleDb-1.0.0.20.zip) - вроде бы его бесплатный вариант. Он не требует создания DSN ("квест" который проходят немногие).
Далее цитата из его документации:
In order to install this software, copy PGOLEDB.DLL and LIBPQ.DLL into your system
directory. Next, as administrator, run "regsvr32 PGOLEDB.DLL". You should get a dialog
message saying "registration succeeded".

Проверь такой запрос
```
SELECT
	pretty_sizes.table_name AS TableName,
	pretty_sizes.tabname AS tabname,
	pretty_sizes.tabschema AS tabschema,
	pretty_sizes.table_size AS DataKB,
	pretty_sizes.indexes_size AS IndexKB,
	pretty_sizes.total_size AS total_size,
	c.reltuples::integer AS Rows,
	'' as IndexType,
	0 as ReservedKB,
FROM
	(SELECT
		all_tables.table_name AS table_name,
		all_tables.tabname AS tabname,
		all_tables.tabschema AS tabschema,
		pg_table_size(table_name) AS table_size,
		pg_indexes_size(table_name) AS indexes_size,
		pg_total_relation_size(table_name) AS total_size
	FROM
		(SELECT
			('"'
				OR table_schema
				OR '"."'
				OR table_name
				OR '"') AS table_name,
			table_name AS tabname,
			table_schema AS tabschema
		FROM
			information_schema.tables AS tables
		WHERE table_schema LIKE 'public') AS all_tables) AS pretty_sizes
	LEFT JOIN pg_class AS c
	ON c.oid = tabname::regclass::oid

```

**Comment by MelenchukEvgeniy** [comment]
1. Через утилиту "Application Stack Builder" установил сначала драйвер "psqlODBC (64 bit)". Эффекта не дало - проверял через "Администратор источника данных ODBC" (исполняемый файл "odbcad32.exe" в директории "C:\Windows\SysWOW64"). В этом "Администраторе" нажимал "Добавить" на закладке "Пользовательский DSN" - в списке доступных драйверов не было PostgreSQL.
2. Повторил шаг 1, только с установкой 32-разрядного драйвера "psqlODBC (32 bit)". В "Администраторе источника данных" добавил новый источник с указанием драйвера "PostgreSQL ODBC Driver (Unicode)". Настройки источника показать бы скриншотом, но я не могу понять, как их здесь прикреплять!?
3. В консоли запросов выбрал платформу "PostgreSQL ч/з OLEDB", указал сервер БД, имя базы, пользователя и пароль. Стандартную строку соединения заменил на "Driver={PostgreSQL Unicode};Server=host;Port=port;Database=db_name;Uid=user;Pwd=password;STMT=utf8" - взял отсюда: https://1c-programmer-blog.ru/programmirovanie/postgresql-iz-1s.html
4. После шага 3 нажал троеточие в реквизите "Строка соединения".
5. Открылось окно "Свойства канала передачи данных". На закладке "Поставщик данных" выбрал "Microsoft OLE DB Providers for ODBC Drivers", на закладке "Соединение" выбрал источник, созданный в шаге 2, указал пользователя, пароль, начальный каталог (имя БД). После нажатия "ОК" сформировалась нужная строка соединения.

**Comment by tormozit** [comment]
> показать бы скриншотом, но я не могу понять, как их здесь прикреплять

Просто вставляй из буфера обмена

**Comment by MelenchukEvgeniy** [comment]
С указанным провайдером сделаю, но уже завтра (вернее, сегодня). Как раз на работе с чистого листа. Сейчас спать пойду, иначе утром не встану.

**Comment by tormozit** [comment]
Добавил поддержку Postgre с указанным мной [провайдером](https://github.com/tormozit/RDT1C/issues/246#issuecomment-1218492799), которого надо вручную устанавливать.
Пробуй новое расширение https://drive.google.com/file/d/1rsnuX8ALaxLILqHbeGwK1584SHptoQvl/view?usp=sharing

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/942055

**Comment by MelenchukEvgeniy** [comment]
Жду, пока скачают. У меня нет доступа к облачным хранилищам. А то, что ты вчера писал, пробовать надо? Я с утра ещё пока админов не смог застать.

**Comment by tormozit** [comment]
Указанный мной провайдер устанавливается только с правами администратора и делать это пока надо вручную.

**Comment by MelenchukEvgeniy** [comment]
Да, я уже осознал. Тогда дай мне чуть времени. Без админов ничего не могу.

**Comment by MelenchukEvgeniy** [comment]
У меня не взлетело. Библиотеки скопировал, регистрация прошла успешно. Даже перезагрузился. Ошибка "Не удаётся найти указанный поставщик".

**Comment by tormozit** [comment]
> У меня не взлетело. Библиотеки скопировал, регистрация прошла успешно. Даже перезагрузился. Ошибка "Не удаётся найти указанный поставщик".

Вероятно у тебя провайдер зарегистрирован в разделе реестра одной разрядности, а клиентское приложение ты используешь другой разрядности. У меня этот провайдер обнаруживается при использовании в 32-разрядном клиентском приложении 1С.
Также после регистрации COM компонент достаточно перезапускать приложение, т.к. эта ветка реестра кэшируется в процессе ОС. Перезагрузка ОС не требуется.

**Comment by MelenchukEvgeniy** [comment]
Попробую поставить 32-разрядную платформу и проверить ещё раз.

**Comment by MelenchukEvgeniy** [comment]
Результаты после установки 32-разрядной платформы.
1. Настройка подключения к СУБД в расширении:
![настройка в расширении](https://user-images.githubusercontent.com/110177488/185364441-caee1889-44bd-46c8-b524-0a294f435a27.jpg)
2. Ошибка в расширении:
[ошибка в расширении.docx](https://github.com/tormozit/RDT1C/files/9372377/default.docx)
3. Успешное подключение через консоль:
![успех в консоли](https://user-images.githubusercontent.com/110177488/185364634-423289f0-3b51-412d-9abf-8e541d5bd982.jpg)
4. Ошибка при попытке открыть конструктор запроса в консоли:
[ошибка в консоли.docx](https://github.com/tormozit/RDT1C/files/9372387/default.docx)

**Comment by MelenchukEvgeniy** [comment]
DLL файлы скопировал в папку C:\Windows\SysWoW64. Регистрировал утилитой regsvr32.exe из папки C:\Windows\System32

**Comment by tormozit** [comment]
Попробуй выполнить в консоли запрос
`SELECT * FROM _CommonSettings LIMIT 1`
для обоих методов соединения (OLEDB и ODBC).
Похоже у OLEDB какие то проблемы с преобразованием типов данных.

**Comment by MelenchukEvgeniy** [comment]
Для OLEDB:
Ошибка ADO: Произошла исключительная ситуация (PgOleDB): Query returned unhandled type 16425

**Comment by tormozit** [comment]
А такой OLEDB выполняет?
`SELECT 1, 'Федя'`

**Comment by MelenchukEvgeniy** [comment]
ODBC драйвер у меня дома установлен. Здесь его для начала установить нужно. Я вроде вчера такой запрос выполнял, он вернул пустую таблицу.

**Comment by MelenchukEvgeniy** [comment]
> А такой OLEDB выполняет? `SELECT 1, 'Федя'`

Да, выполняется. Одна строка с колонками "_column_" (значение 1) и "_column_1"(значение Федя)

**Comment by tormozit** [comment]
Найди в моем расширении конфигурации в общем модуле ирОбщий строку
`SELECT * FROM _CommonSettings WHERE _SettingsKey`
И замени в ней звездочку на 1.

**Comment by MelenchukEvgeniy** [comment]
Это ты про расширение, которое прислал?

**Comment by MelenchukEvgeniy** [comment]
Небольшой перерыв и я вернусь.

**Comment by tormozit** [comment]
Выходит этот OLEDB провайдер не умеет BINARY типы обрабатывать. Для самых полезных задач в ИР это не проблема. 
А вот для исследования данных в таблицах СУБД прямыми запросами из консоли запросов ИР - конечно будет проблемой. Но тот кто до этого дойдет, сможет и источник ODBC настроить и подключить.

**Comment by tormozit** [comment]
По поводу конструктора запроса ИР. Этот провайдер OLEDB скорее всего не предоставляет нужной функциональности, т.к. у него в описании упомянуто про это. Но можешь попробовать в точке останова на проблемной строке показать свойства переменной "Конфигурация".

**Comment by MelenchukEvgeniy** [comment]
> Найди в моем расширении конфигурации в общем модуле ирОбщий строку `SELECT * FROM _CommonSettings WHERE _SettingsKey` И замени в ней звездочку на 1.

Сделал. Настройки соединения с СУБД проглатывает. При установке реквизита "Показывать размеры" - ошибка:
SQL Server не существует, или доступ запрещён.

**Comment by tormozit** [comment]
Пробуй новое расширение https://drive.google.com/file/d/1A0TDj7ppieD5oySNMlQC762Yyc5bTMgw/view?usp=sharing

**Comment by MelenchukEvgeniy** [comment]
> По поводу конструктора запроса ИР. Этот провайдер OLEDB скорее всего не предоставляет нужной функциональности, т.к. у него в описании упомянуто про это. Но можешь попробовать в точке останова на проблемной строке показать свойства переменной "Конфигурация".

[Переменная Конфигурация.xls](https://github.com/tormozit/RDT1C/files/9373569/default.xls)

![Ошибочное место при открытии конструктора](https://user-images.githubusercontent.com/110177488/185388661-aadec218-23e0-4b31-b2aa-875f15a074c5.jpg)

**Comment by MelenchukEvgeniy** [comment]
Новое расширение скачал и установил. Ошибка при открытии инструмента "Структура хранения БД":
![ошибка нового расширения](https://user-images.githubusercontent.com/110177488/185391159-9cf94c85-d575-49dc-aab8-870ed24cee04.jpg)

[Текст запроса в новом расширении.xls](https://github.com/tormozit/RDT1C/files/9373666/default.xls)

**Comment by tormozit** [comment]
Ты не тот запрос отловил. Эта строка кода выполняет ВСЕ запросы к ADO. Ты отловил первый запрос, но мы уже его ранее проверили. И в нем меньше 100 символов. А в ошибке указано на 301-й символ, т.е. точно другой запрос.

**Comment by tormozit** [comment]
Нашел ошибку. Убери лишнюю запятую 

![изображение](https://user-images.githubusercontent.com/11896251/185394086-42850d4a-5e2b-49b1-a665-f535650476c4.png)

**Comment by MelenchukEvgeniy** [comment]
Да, я тоже нашёл. Долго соображал, где текст запроса у тебя находится. Теперь ошибка на символе 584:
 ...
FROM
   (SELECT
      ('"'
         OR...

invalid input syntax for type boolean: """
Это 21 строка запроса - ('"'
Тут у меня не хватает соображалки, что это за конструкция и как должно быть.

**Comment by tormozit** [comment]
Тут идет соединение частей строки. Замени все OR на ||. В оригинале там || было. А замена произошла при форматировании моим конструктором.

**Comment by MelenchukEvgeniy** [comment]
Взлетело. Размеры таблиц показываются.

**Comment by tormozit** [comment]
Единицы измерения размера адекватные?
Команду "Очистка таблиц СУБД" хорошо бы тоже протестировать.

**Comment by MelenchukEvgeniy** [comment]
Не, рано радовался. Погоди, я скрины сделаю.

**Comment by MelenchukEvgeniy** [comment]
В списке таблиц сначала идёт такой блок, где указаны размеры, но нет "человеческих" имён таблиц:

![структура хранения 1](https://user-images.githubusercontent.com/110177488/185405264-d1ac0c79-5400-46fe-b48a-f8c8a797f11e.jpg)

Потом идёт блок с "человеческими" названиями, но без размеров:
![структура хранения 2](https://user-images.githubusercontent.com/110177488/185405361-0241cc91-71ea-44d1-9b2a-418edcba8145.jpg)

**Comment by tormozit** [comment]
Попробуй такой запрос
```
SELECT
	pretty_sizes.table_name AS fullTableName,
	pretty_sizes.tabname AS TableName,
	pretty_sizes.tabschema AS tabschema,
	pretty_sizes.table_size/1024 AS DataKB,
	pretty_sizes.indexes_size/1024 AS IndexKB,
	pretty_sizes.total_size/1024 AS TotalKB,
	c.reltuples::integer AS Rows,
	'' as IndexType,
	0 as ReservedKB
FROM
	(SELECT
		all_tables.table_name AS table_name,
		all_tables.tabname AS tabname,
		all_tables.tabschema AS tabschema,
		pg_table_size(table_name) AS table_size,
		pg_indexes_size(table_name) AS indexes_size,
		pg_total_relation_size(table_name) AS total_size
	FROM
		(SELECT
			('"'||table_schema||'"."'||table_name||'"') AS table_name,
			table_name AS tabname,
			table_schema AS tabschema
		FROM
			information_schema.tables AS tables
		WHERE table_schema LIKE 'public') AS all_tables) AS pretty_sizes
	LEFT JOIN pg_class AS c
	ON c.oid = tabname::regclass::oid
```

**Comment by MelenchukEvgeniy** [comment]
> Единицы измерения размера адекватные? Команду "Очистка таблиц СУБД" хорошо бы тоже протестировать.

Ты же вроде в обёртку pretty_size оборачивал? Должно быть адекватно. Я посмотрю чуть позже. Очистка таблиц сделает базу пустой?

**Comment by tormozit** [comment]
Для очистки ТАБЛИЦ просто выбери пустую таблицу. Хочется проверить что сгенерированный запрос корректно выполнится. Выбранную таблицу он очистит, если получится.

**Comment by MelenchukEvgeniy** [comment]
Не очищает.
![очистка таблиц 1](https://user-images.githubusercontent.com/110177488/185412378-85cb2b80-e7f5-4595-a8fb-7e4ea3a91771.jpg)
![очистка таблиц 2](https://user-images.githubusercontent.com/110177488/185412407-8efd3f8f-b491-4a2e-8af1-fc66d672279d.jpg)
![очистка таблиц 3](https://user-images.githubusercontent.com/110177488/185412452-9a0e5eab-ce00-41e9-a001-af941c0badfc.jpg)
Сформированный текст запроса для очистки таблиц:
![очистка таблиц 4](https://user-images.githubusercontent.com/110177488/185412552-e185ac12-0826-4b0e-8746-3d8f0f74ef87.jpg)

**Comment by MelenchukEvgeniy** [comment]
> Попробуй такой запрос
> 
> ```
> SELECT
> 	pretty_sizes.table_name AS fullTableName,
> 	pretty_sizes.tabname AS TableName,
> 	pretty_sizes.tabschema AS tabschema,
> 	pretty_sizes.table_size/1024 AS DataKB,
> 	pretty_sizes.indexes_size/1024 AS IndexKB,
> 	pretty_sizes.total_size/1024 AS TotalKB,
> 	c.reltuples::integer AS Rows,
> 	'' as IndexType,
> 	0 as ReservedKB
> FROM
> 	(SELECT
> 		all_tables.table_name AS table_name,
> 		all_tables.tabname AS tabname,
> 		all_tables.tabschema AS tabschema,
> 		pg_table_size(table_name) AS table_size,
> 		pg_indexes_size(table_name) AS indexes_size,
> 		pg_total_relation_size(table_name) AS total_size
> 	FROM
> 		(SELECT
> 			('"'||table_schema||'"."'||table_name||'"') AS table_name,
> 			table_name AS tabname,
> 			table_schema AS tabschema
> 		FROM
> 			information_schema.tables AS tables
> 		WHERE table_schema LIKE 'public') AS all_tables) AS pretty_sizes
> 	LEFT JOIN pg_class AS c
> 	ON c.oid = tabname::regclass::oid
> ```

Теперь хорошо. И размеры теперь похожи на правду. До этого было неправильно. На той же таблице Reference53 проверил. В твоём инструменте - 51 928 КБ, в PgAdmin запрос показывает 51 МБ по этой таблице. Сходится)

**Comment by MelenchukEvgeniy** [comment]
Колонка "Размер общий" пустая по всем строкам! Не обратил внимания на неё сразу, извини.

**Comment by tormozit** [comment]
> Не очищает.

Нужен полный текст ошибки.

**Comment by MelenchukEvgeniy** [comment]
> > Не очищает.
> 
> Нужен полный текст ошибки.

Ошибка при получении значения атрибута контекста (DefaultDatabase)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(39020)}:	ИмяБД = ПолучитьСоединениеСУБД().DefaultDatabase;
{ИнструментыРазработчикаTormozit Обработка.ирСтруктураХраненияБД.Форма.Форма.Форма(445)}:		Если Не ирОбщий.ПодтверждениеОперацииСУБДЛкс() Тогда
по причине:
Произошла исключительная ситуация (ADODB.Connection): Поставщик не поддерживает это свойство.

**Comment by tormozit** [comment]
> Колонка "Размер общий" пустая по всем строкам

Исправил
```
SELECT
	pretty_sizes.table_name AS fullTableName,
	pretty_sizes.tabname AS TableName,
	pretty_sizes.tabschema AS tabschema,
	pretty_sizes.table_size/1024 AS DataKB,
	pretty_sizes.indexes_size/1024 AS IndexKB,
	pretty_sizes.total_size/1024 AS ReservedKB,
	c.reltuples::integer AS Rows,
	'' as IndexType
FROM
	(SELECT
		all_tables.table_name AS table_name,
		all_tables.tabname AS tabname,
		all_tables.tabschema AS tabschema,
		pg_table_size(table_name) AS table_size,
		pg_indexes_size(table_name) AS indexes_size,
		pg_total_relation_size(table_name) AS total_size
	FROM
		(SELECT
			('"'||table_schema||'"."'||table_name||'"') AS table_name,
			table_name AS tabname,
			table_schema AS tabschema
		FROM
			information_schema.tables AS tables
		WHERE table_schema LIKE 'public') AS all_tables) AS pretty_sizes
	LEFT JOIN pg_class AS c
	ON c.oid = tabname::regclass::oid
```

**Comment by MelenchukEvgeniy** [comment]
В колонке "Количество строк" есть значения "-1".

**Comment by tormozit** [comment]
Старайся тексты ошибок вставлять непосредственно в текст сообщения. Потом может быть полезно их искать. А по вложенным файлам найти не получится.

**Comment by MelenchukEvgeniy** [comment]
> SELECT
> 	pretty_sizes.table_name AS fullTableName,
> 	pretty_sizes.tabname AS TableName,
> 	pretty_sizes.tabschema AS tabschema,
> 	pretty_sizes.table_size/1024 AS DataKB,
> 	pretty_sizes.indexes_size/1024 AS IndexKB,
> 	pretty_sizes.total_size/1024 AS ReservedKB,
> 	c.reltuples::integer AS Rows,
> 	'' as IndexType
> FROM
> 	(SELECT
> 		all_tables.table_name AS table_name,
> 		all_tables.tabname AS tabname,
> 		all_tables.tabschema AS tabschema,
> 		pg_table_size(table_name) AS table_size,
> 		pg_indexes_size(table_name) AS indexes_size,
> 		pg_total_relation_size(table_name) AS total_size
> 	FROM
> 		(SELECT
> 			('"'||table_schema||'"."'||table_name||'"') AS table_name,
> 			table_name AS tabname,
> 			table_schema AS tabschema
> 		FROM
> 			information_schema.tables AS tables
> 		WHERE table_schema LIKE 'public') AS all_tables) AS pretty_sizes
> 	LEFT JOIN pg_class AS c
> 	ON c.oid = tabname::regclass::oid

Да, общий размер тоже работает. Через PgAdmin такой же результат получаю.

**Comment by MelenchukEvgeniy** [comment]
> Старайся тексты ошибок вставлять непосредственно в текст сообщения. Потом может быть полезно их искать. А по вложенным файлам найти не получится.

Хорошо.

**Comment by tormozit** [comment]
> Ошибка при получении значения атрибута контекста (DefaultDatabase)

В общем модуле ирОбщий замени функцию

```
Функция ПодтверждениеОперацииСУБДЛкс() Экспорт 
	
	Если ПолучитьСоединениеСУБД() = Неопределено Тогда 
		Возврат Ложь;
	КонецЕсли; 
	ИмяБД = ПараметрыСоединенияADOЭтойБДЛкс().ИмяБД;
	Возврат Вопрос("Вы осознаете риски и ответственность за использование прямого доступа к данным базы """ + ИмяБД + """ и нарушение лицензионного соглашения 1С?", РежимДиалогаВопрос.ДаНет) = КодВозвратаДиалога.Да;

КонецФункции

```

**Comment by MelenchukEvgeniy** [comment]
> > Ошибка при получении значения атрибута контекста (DefaultDatabase)
> 
> В общем модуле ирОбщий замени функцию

Заменил. Эта проблема ушла. Но очистка не происходит. Первая ошибка - не хватает ; после каждого truncate, кроме последнего. Проверил в запроснике постгреса.

```
truncate table _Reference33; --Справочник.БанковскиеСчета.Основная
truncate table _Reference33_VT3869; --Справочник.БанковскиеСчета.ТабличнаяЧасть.ДополнительныеРеквизиты.ТабличнаяЧасть
truncate table _ReferenceChngR3874 --Справочник.БанковскиеСчета.РегистрацияИзменений
```

Но в инструменте очистки таблиц появилась следующая ошибка:

```
Ошибка при вызове метода контекста (Open)
{ИнструментыРазработчикаTormozit Обработка.ирСтруктураХраненияБД.Форма.Форма.Форма(452)}:		РезультатЗапроса.Open(ТекстЗапроса, СоединениеADO, adOpenStatic, adLockOptimistic, adCmdText);
по причине:
Произошла исключительная ситуация (PgOleDb): ERROR:  cannot insert multiple commands into a prepared statement
```

**Comment by tormozit** [comment]
> cannot insert multiple commands into a prepared statement
Видимо провайдер не поддерживает пакетные запросы

**Comment by MelenchukEvgeniy** [comment]
> В колонке "Количество строк" есть значения "-1".

С этим можно что-то сделать? Похоже, что эти значения соответствуют пустым таблицам.

**Comment by tormozit** [comment]
> С этим можно что-то сделать?

Уберу отрицательный диапазон у колонки.

**Comment by tormozit** [comment]
В консоли запросов ИР подключенной к СУБД проверь запрос
```
SELECT 1;
SELECT 1
```

**Comment by MelenchukEvgeniy** [comment]
> В консоли запросов ИР подключенной к СУБД проверь запрос
> 
> ```
> SELECT 1;
> SELECT 1
> ```

Такая же ошибка:
`Произошла исключительная ситуация (PgOleDb): ERROR:  cannot insert multiple commands into a prepared statement`

**Comment by MelenchukEvgeniy** [comment]
Кстати, если в консоли на закладке "ADO" нажимаю кнопку "Эта БД", то автоматически заполняются реквизиты "Сервер БД", "Имя базы", "Пользователь" и "Пароль" (заполняются если я перед этим пользовался инструментом "Структура хранения БД" и указывал там параметры подключения к БД), а вот реквизит "Платформа" устанавливается в значение "MS-SQL ч/з OLEDB" даже если там до этого было указано значение "PostgreSQL ч/з OLEDB".

**Comment by tormozit** [comment]
Значит в этом поставщике OLEDB нет поддержки пакетных запросов. Ну наверное для бесплатного продукта 2006 года это нормально. Кстати в современной платной версии у них есть и 64-разрядный вариант и поддержка работы со схемой БД и пакетные запросы. Текущий достигнутый с этим бесплатным поставщиком результат уже дает много пользы. 
Подумаю над другими вариантами подключения.

> реквизит "Платформа" устанавливается в значение "MS-SQL ч/з OLEDB" даже если там до этого было указано значение "PostgreSQL ч/з OLEDB"

Исправлю

**Comment by MelenchukEvgeniy** [comment]
В сухом остатке на текущий момент:
1. Инструмент "Структура хранения БД" в части размеров страниц работает через 32-разрядный драйвер OLEDB, который нужно предварительно скачать и установить вручную; в части очистки таблиц формируется пакетный запрос, но ограничения драйвера не позволяют его выполнить - можно скопировать текст в запросник постгреса и выполнить там;
2. Консоли запроса для прямой работы с БД требуется ODBC драйвер (есть и 32 и 64-разрядный) с дополнительной настройкой DSN.
Верно?

**Comment by tormozit** [comment]
1. Да. Только после ошибки выполнения запроса очистки теперь открывается консоль запросов с текстом запроса очистки, где пользователь может в частности указать другую строку соединения с другим драйвером ODBC
2. Да. Точнее в консоли запросов можно использовать любой доступный драйвер, т.к. можно редактировать строку соединения.

**Comment by tormozit** [comment]
Кстати даже с этим урезанным поставщиком OLEDB в консоли запросов ИР можно выполнить пакетный запрос очистки командой "Выполнить все запросы (F5)" в структуре запроса, т.к. запросы пакета там выполняются по одному.

![изображение](https://user-images.githubusercontent.com/11896251/185600878-199eb9bf-65d4-425b-8e78-50b59b33de53.png)

**Comment by tormozit** [comment]
реализовано в 6.41

**Comment by MelenchukEvgeniy** [comment]
Здорово! Благодарю) А как эту задачу закрыть? Или её не нужно закрывать?

**Comment by tormozit** [comment]
кнопка "Close issue" внизу

**Comment by MelenchukEvgeniy** [comment]
Ещё раз спасибо!) Если нужна будет какая-нибудь помощь в тестировании - я завсегда "за")

**Comment by tormozit** [comment]
На всякий случай замечу, что лучше закрывать заявку когда проверил исправление в релизе.

**Comment by MelenchukEvgeniy** [comment]
Хорошо, я здесь ещё неопытен)

**Comment by PythonOfJungle** [comment]
Предложение полностью изменить существующий способ подключения через драйвер PGOLEDB.DLL на стоковый ODBC через MS OLEDB. Сейчас точно также подключается MySQL.
В макете Обработки/ирКонсольЗапросов/ПлатформыADODB поменять строку подключения для PostgreSQL на
`Driver={PostgreSQL ODBC Driver(Unicode)}; SERVER=!БазаСервер!; DATABASE=!БазаИмя!; UID=!Пользователь!; PWD=!Пароль!;`
Остальные параметры строки соединения не нужны. После этого при установленном из родного комплекта драйвере psqlODBC все работает нативно и в "Консоли запросов", и в инструменте "Структура хранения БД".
Только надо тогда текст ошибки изменить (Обработки/ирКонсольЗапросов/МодульОбъекта[782]). Примерно так:
`Установите от имени администратора с помощью Application Stack Builder из инструментов PostgreSQL драйвер psqlODBC той же разрядности, что используемое приложение`

**Comment by tormozit** [comment]
@MelenchukEvgeniy Можешь сделать и проверить модификацию от @PythonOfJungle ?

**Comment by tormozit** [comment]
@PythonOfJungle 
Предположим пользователь не знаком с PostgreSQL и у него на клиентском компьютере не установлено какого либо ПО этой СУБД, но он запустил ИР в клиент-серверной базе на PostgreSQL и хочет посмотреть размеры таблиц БД. В текущей реализации он достаточно быстро скачает и зарегистрирует нужную библиотеку, затем получит параметры подключения от администратора и выполнит неявно нужный прямой запрос к СУБД в инструменте "Структура хранения БД (ИР)". 

В предлагаемой тобой модификации ему придется изучать, что такое "Application Stack Builder из инструментов PostgreSQL драйвер psqlODBC" и как это правильно устанавливать и желательно без лишних компонент. Это кажется существенным усложнением в описанном мной случае. Попробуй упростить пользовательский путь.

**Comment by PythonOfJungle** [comment]
@tormozit 
Логично. Драйвер psqlODBC есть отдельно от общего комплекта. Вот здесь https://www.postgresql.org/ftp/odbc/versions/msi/
Можно смело качать последний, в установщике обе разрядности сразу. Эту же ссылку можно дать в тексте ошибки.
Нюанс только в том, что он в системе называется не "PostgreSQL ODBC Driver(Unicode)", а "PostgreSQL Unicode". Строка подключения будет такая:
`Driver={PostgreSQL Unicode}; SERVER=!БазаСервер!; DATABASE=!БазаИмя!; UID=!Пользователь!; PWD=!Пароль!;`
Так даже лучше, поскольку штатный установщик PostgreSQL AppStackBuilder скачивает и ставит не самую последнюю версию. 
Полагаю, что те пользователи, у которых установлен PostgreSQL и уже вручную установлен комплектный драйвер, сами догадаются поправить строку подключения. А если не догадаются, то ничего страшного, драйверы в системе мешать друг другу не будут.

![image](https://user-images.githubusercontent.com/63949215/202890905-449ef1e3-a8d4-42ba-bd13-bcd6276be324.png)
13.00 - комплектный драйвер
13.02 - из ссылки выше
На самом деле это один и тот же драйвер.
Для меня только остается загадкой, почему в списке 64-разрядных драйверов две строки - обычная и с указанием "(x64)". 32-разрядный драйвер находится, как ему и положено, в своем списке. Может для совместимости сделали две строки регистрации. В любом случае "PostgreSQL Unicode" работает и для 32-битного клиента, и для 64-битного.

**Comment by tormozit** [comment]
Создал задачу на добавление поддержки ODBC драйвера https://www.hostedredmine.com/issues/954415

**Comment by PythonOfJungle** [comment]
@tormozit 
Сначала вот так и хотел - добавить еще один вариант. Но потом посмотрел код. Если добавить новую строку в список подключения, то открытым останется вопрос, как будет работать инструмент "Структура хранения БД". Поэтому в итоге предложение было не добавить строку а заменить текущую. MySQL же точно также подключается.
Вообще говоря, насколько я понимаю, специфические OLE-поставщики в опенсорсе не разрабатывают как раз по той причине, что есть платформенно-независимая технология ODBC и есть универсальный конвертер ODBC > MS OLEDB. Соответственно нет смысла делать для каждой СУБД собственный OLEDB. Хотя проприетарные, конечно, есть.

**Comment by tormozit** [comment]
Реализовано в 6.53

**Comment by MelenchukEvgeniy** [comment]
> @MelenchukEvgeniy Можешь сделать и проверить модификацию от @PythonOfJungle ?

Добрый вечер. Прошу прощения за долгую реакцию. Дома 1С сейчас не работает. Могу проверить только завтра на работе, но уже неактуально как я понимаю?

**Comment by tormozit** [comment]
@MelenchukEvgeniy Эта правка вошла в релиз. Но без второй проверки. Теперь уже все будут проверять в релизе =)

**Comment by PythonOfJungle** [comment]
@tormozit Все отлично работает, спасибо :)
