### ISSUE TITLE
Конструктор запросов ИР. Перестал открываться из консоли кода.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#248]
https://user-images.githubusercontent.com/87958986/187527526-51a3cd24-f51c-413a-a292-508d68af5238.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.42.2p
> Инструменты разработчика. Инструмент: Консоль кода
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС Текущая кодовая страница: 866
> Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль кода"
2. Ввел текстовую переменную с текстом запроса "ВЫБРАТЬ 1"
3. Вызвал команду Конструктора запросов ИР
4. Получил окно с ошибкой:

```
Значение не является значением объектного типа (Найти)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5296)}:		СтрокаТерминала = мТерминалыЯзыкаЗапросов.Найти(Ключ, "Ключ");
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(1657)}:	Результат = СловоЯзыкаЗапросов(Ключ, ПараметрыДиалектаSQL, Английский1С);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(7027)}:	АгрегатныеФункции.Добавить("SUM(", СловоЯзыкаЗапросовВФорме("SUM"));
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2615)}:		КонструкторЗапроса.УстановитьДиалектSQL(ДиалектSQL, ИменованныеПараметры);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2403)}:			РезультатРазбора = ЗагрузитьТекстВКонструктор(ТекстЗапроса, КонструкторЗапроса,, мДиалектSQL,, НачальнаяСтрокаЗапроса);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(943)}:			Результат = ВызватьКонструкторЗапросов();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(899)}:	Результат = ВыполнитьКоманду(Команда,, Ложь);
{ВнешняяОбработка.ирКонсольКода.Форма.Форма.Форма(58)}:	ПолеТекстаАлгоритма.Нажатие(Кнопка);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/949196

**Comment by tormozit** [comment]
Исправлено в 6.43

**Comment by PerlAmutor** [comment]
К сожалению не исправилось, видно, что на другом номере строки теперь ошибка. Платформу перезапускал (файловые вариант).
```
Значение не является значением объектного типа (Найти)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5326)}:		СтрокаТерминала = мТерминалыЯзыкаЗапросов.Найти(Ключ, "Ключ");
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(1691)}:	Результат = СловоЯзыкаЗапросов(Ключ, ПараметрыДиалектаSQL, Английский1С);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(7102)}:	АгрегатныеФункции.Добавить("SUM(", СловоЯзыкаЗапросовВФорме("SUM"));
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2631)}:		КонструкторЗапроса.УстановитьДиалектSQL(ДиалектSQL, ИменованныеПараметры);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2419)}:			РезультатРазбора = ЗагрузитьТекстВКонструктор(ТекстЗапроса, КонструкторЗапроса,, мДиалектSQL,, НачальнаяСтрокаЗапроса);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(953)}:			Результат = ВызватьКонструкторЗапросов();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(909)}:	Результат = ВыполнитьКоманду(Команда,, Ложь);
{ВнешняяОбработка.ирКонсольКода.Форма.Форма.Форма(58)}:	ПолеТекстаАлгоритма.Нажатие(Кнопка);
```

**Comment by tormozit** [comment]
Проверил в файловой базе в портативном варианте. Ошибки нет. Нужно более подробное описание.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/949196

**Comment by tormozit** [comment]
В качестве способа обхода проблемы можно первый раз в форме консоли открыть конструктор следующим образом. Установить каретку в любую позицию вне строкового литерала или в пустом строковом литерале. Открыть конструктор. Далее он будет открываться без ошибки в любом месте.

**Comment by tormozit** [comment]
Исправлено в 6.44
