### ISSUE TITLE
Редактор объекта БД

### ISSUE THREAD

**Issue by a-sitnikov** [tormozit/RDT1C#249]
Добавить возможность выбора объекта из отрытых окон как в обработке
https://infostart.ru/public/552368
Там выбор объекта из окна предлагается сразу при открытии обработки

**Comment by tormozit** [comment]
Есть же [глобальное меню](https://infostart.ru/1c/articles/1273456/) - CTRL+ё. Чем не подошло?

**Comment by a-sitnikov** [comment]
В портативной версии не работает. А может просто прав нет на терминале

**Comment by tormozit** [comment]
Портативная версия работает только в обычном приложении. Там невозможно обойти открытые формы.
