### ISSUE TITLE
Анализ техножурнала. Ошибка при вызове команды "Начать/Кончить трассу"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#25]
https://user-images.githubusercontent.com/87958986/130390036-ec867d5d-e813-4707-a07c-fedda98a7538.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.06.1e
> Инструменты разработчика. Инструмент: Анализ техножурнала
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.06.1e)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: tcp

</details>

При вызове команды "Трасса" в обработке "Анализ техножурнала" выдается ошибка:

```
Слишком много фактических параметров
{ИнструментыРазработчикаTormozit Обработка.ирАнализТехножурнала.МодульОбъекта(1501)}:			ТехножурналСервераВключен = ирОбщий.ЛиТехножурналВключенЛкс(Истина, ВыводитьСообщения,, , мЛиАнализТрассыЗапроса);
{ИнструментыРазработчикаTormozit Обработка.ирАнализТехножурнала.Форма.Форма.Форма(1149)}:		Если НачатьТрассу(, Истина) Тогда

```

По мотивам AAC.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932290

> По мотивам AAC

Не понял связь с АСС и что такое АСС.

**Comment by PerlAmutor** [comment]
> Ошибку воспроизвел https://www.hostedredmine.com/issues/932290
> 
> > По мотивам AAC
> 
> Не понял связь с АСС и что такое АСС.

Ты просил создать отдельными тремя темами вопросы по ошибкам из этой темы https://github.com/tormozit/RDT1C/issues/24
Ну вот я начал.

P.S.: AAC - Автоматизированная Проверка Конфигураций. Видимо аббревиатура на английском от 1С.

**Comment by tormozit** [comment]
По данному типу ошибки (267) согласен, что он имеет высокую ценность, т.к. ошибка препятствует работе программы. Правда и в этом типе все равно много ложных срабатываний.

**Comment by PerlAmutor** [comment]
> По данному типу ошибки (267) согласен, что он имеет высокую ценность, т.к. ошибка препятствует работе функции программы. Правда и в этом типе все равно много ложных срабатываний.

Да, в основном в конструкции #Если Сервер И Не Сервер Тогда, т.к. там обычно прописаны функции и процедуры без параметров.

Я прошелся по всему списку. Больше ничего критического не обнаружил за исключением одного вызова в конструкции #Если Не Сервер Тогда, который относится к этой теме http://devtool1c.ucoz.ru/forum/2-1828-1 Но судя по текущему коду в этот участок захода никогда не будет. Хотя кто знает как код измениться в будущем.

**Comment by tormozit** [comment]
Исправлено в 6.06.3
