### ISSUE TITLE
Тотальный крэш толстого клиента (опять!) при использовании варианта расширение

### ISSUE THREAD

**Issue by agithubber2** [tormozit/RDT1C#250]
Платформа: 8.3.19.1522
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия для Беларуси, редакция 2.1 (2.1.44.6)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.42.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. Адаптация1 ()
Расширения. Битрикс24КомплексБП (1.1.0.11)
Расширения. EDiN_ЭДО ()
Расширения. ИнструментыРазработчикаTormozit (6.42.2e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

СНОВА та же ошибка, что и летом!!! Но на этот раз, уже никакие отключения перехватов клавиатурного ввода, или использования эмуляции уже больше НЕ помогают!!! Вот вообще, надо сидеть на древнгей версии и ничего не обновлять: только портишь , сорри, свое ты расширение!!!!
Воспроизведение ошибки:  установить вариант расширение, далее любая работа с расширением, наприме, вызвать отчет "Анализ прав доступа" и там попытаться выбрать пользователя - сразу ОШИБКА:

![image](https://user-images.githubusercontent.com/65526781/187838588-650e1a86-24a5-48e1-ac5f-21bcfffafad0.png)

**Comment by tormozit** [comment]
Нужен текст ошибки. Также полезно указывать ссылки на упоминаемые обсуждения. Если же ошибка в точности повторяется, то обычно переоткрывают старую заявку кнопкой Reopen.

**Comment by agithubber2** [comment]
Текст ошибки:
![image](https://user-images.githubusercontent.com/65526781/187841904-0a7551f8-0b13-4159-a170-5af8347c3c06.png)

Вот предыдущее аналогичное issue:
https://github.com/tormozit/RDT1C/issues/225

**Comment by tormozit** [comment]
Ты показал картинку с текстом ошибки, а нужен текст. Почитай рекомендации к описанию проблем http://devtool1c.ucoz.ru/forum/2-2-1

**Comment by tormozit** [comment]
Подтверди, что прочитал и применил 3 моих рекомендации, начиная с https://github.com/tormozit/RDT1C/issues/225#issuecomment-1166218734 .

**Comment by agithubber2** [comment]
Текстовое описание:

Значение не является значением объектного типа (ПараметрыПодключенияПО)
{ОбщийМодуль.МенеджерОборудованияКлиент.Модуль(2084)}:	ПараметрыПодключенияПО = глПодключаемоеОборудование.ПараметрыПодключенияПО; //Массив Из Структура, где: *Параметры - Структура - .
{МодульУправляемогоПриложения(157)}:	Результат = МенеджерОборудованияКлиент.ОбработатьСобытиеОтУстройства(ОписаниеСобытия, ОписаниеОшибки);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(28027)}:		РезультатВыбора = ФормаВыбора.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Отчет.ирАнализПравДоступа.Форма.ФормаОтчета.Форма(393)}:	ирОбщий.ПолеВводаПользователя_НачалоВыбораЛкс(Элемент, СтандартнаяОбработка);



В расширении "Адаптация1" код:
https://github.com/tormozit/RDT1C/issues/225#issuecomment-1166903577
 по-прежнему остался

**Comment by agithubber2** [comment]
Но тогда я на файловой копии БД ставил расширение, а сейчас (случайно) поставил на сервеной!
На файловой копии у меня ошибки нет!
А вот на серверной копии ошибка есть! (Возможно, и в прошлый раз она на сервере не была испралвена, но тогда я на серверной базе не проверял

**Comment by tormozit** [comment]
Ну вроде получается что у тебя в базе с ошибкой то нет твоего расширения, которое должно ее исправить?
Если так то попробуй его туда добавить.

**Comment by agithubber2** [comment]
Как это нет?? В самом первом посте видно, что есть (строчка "Расширения. Адаптация1 ()")! Это основное расширение - без него вся база полностью неработоспособна для нашей организации!

**Comment by tormozit** [comment]
Покажи тогда снимок из отладчика что твоя вставка в методе Адапт1_ОбработкаВнешнегоСобытия модуля управляемого приложения действительно выполняется из расширения "Адаптация1" в базе с ошибкой.

**Comment by agithubber2** [comment]
Хорошая мысль, сейчас проверю

**Comment by agithubber2** [comment]
Вот что выяснил: 
1) Точка останова в расширении в СЕРВЕРНОМ варианте НЕ работает вообще - не заходит в эту процедуру "Процедура Адапт1_ОбработкаВнешнегоСобытия(Источник, Событие, Данные)" (отладка на сервере включена)
2) В файловом варианте, как только (в отчёте "Анализ прав доступа") я нажимаю выбор пользователя, и нажимаю PgDn для пролистывания - мгновенно заходит в мою эту проц из расширения - и ошибки нет.

Расширения, базы - всё идентично полностью

**Comment by agithubber2** [comment]
Еще проверил: в серверном варианте в ОРИГИНАЛЬНУЮ (НЕ из расширения) процедуру "Процедура ОбработкаВнешнегоСобытия(Источник, Событие, Данные)" заходит! То есть , по мне абсолютно не понятной причине код из моего расширения в серверном варианте не подключается (но в целом это моё расширение в серверном варианте безусловно работает (повторяю, это основное расш, там все доработки, оно подключено всегда

**Comment by tormozit** [comment]
Аннотация &ИзменениеИКонтроль пока сырая. Поэтому не рекомендую ее использовать.
Замени ее на &Вместо и внутри используй ПродолжитьВызов(). Это будет намного надежнее.

**Comment by agithubber2** [comment]
Хорошо, завтра попробую заменить. Но у меня в основном исп-ся как раз "Изменение и контроль", это , по логике, очень верный подход, и до этого случая вроде особо с этой директивой я не замечал проблем. 
Но конечно, ты как настоящий профи в платформе тоже не спроста так считаешь.  И именно в этом конкретном случае 100% можно смело заменить на "Вместо", потому что тут чисто системная , а не прикладная процедура, как я понимаю

**Comment by tormozit** [comment]
Ну в любом случае думаю уже понятно, что изменения в ИР здесь не вовлечены в формирование проблемы, т.к. новая версия ИР в твоей файловой базе продолжает работать без ошибки, как и старая версия ИР.

**Comment by agithubber2** [comment]
В общем, заменил в расширении на код:
&Вместо("ОбработкаВнешнегоСобытия")
Такой вариант на сервере работает.
(Всё же потом вообще убрал из расширения и перенёс в основную конфиг (чтобы при обновлениях всё же мониторить, если вдруг сами разраб типовой что-то пофиксят-изменят)
Закрываю тогда этот issue
