### ISSUE TITLE
Ошибка: Удаление объектов с контролем ссылок при заполнении помеченных объектов

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#251]
**Программное окружение**

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1613
Режим БД: клиент-серверный
Конфигурация. Название: Business automation software for accounting CORP (2.1.15.2)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Версия БСП: 300
Инструменты разработчика. Версия: Расширение 6.43.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ВводОстатковВзаиморасчетов3779 (21.2.1)
Расширения. ОшибкаСортировкиСотрудников (21.18.9)
Расширения. HF ()
Расширения. НастройкиДинамическогоСпискаTormozit (1.00)
Расширения. МониторингОбменаБСП (21.01.06)
Расширения. БлокировкаУдобнее (1.2)
Расширения. ЗапуститьСеансПользователя (2.1)
Расширения. ИнструментыРазработчикаTormozit (6.43.1e)
Клиент. Приложение: Управляемое приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Microsoft Windows Server 2019 Standard 64-bit НеРусский-042a
Клиент. ОС от имени администратора: Нет
Клиент. ОС Active code page: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Microsoft Windows Server 2019 Standard 64-bit НеРусский-042a
Сервер. Процесс: 64б
Сервер. Отладка: tcp
</details>

**Воспроизведение проблемы**
1. Открыл инструмент Удаление объектов с контролем ссылок
2. Нажал кнопку Заполнить
3. В окне выбора метаданных нажал Ок
4. Получил окно с ошибкой:
Итератор для значения не определен
{ИнструментыРазработчикаTormozit Обработка.ирУдалениеОбъектовСКонтролемСсылок.Форма.Форма.Форма(142)}:Для Каждого ПомеченныйОбъект Из ПомеченныеОбъекты Цикл
{(1)}:ЭтаФормаИлиОбработка.ЗаполнитьПомеченныеНаУдалениеЗавершение(, Результат)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(32758)}:Выполнить("ЭтаФормаИлиОбработка." + ОбработчикЗавершения + "(, Результат)");
{ИнструментыРазработчикаTormozit Обработка.ирУдалениеОбъектовСКонтролемСсылок.Форма.Форма.Форма(114)}:ирОбщий.ВыполнитьЗаданиеФормыЛкс("НайтиПомеченныеНаУдалениеЛкс", ПараметрыЗадания, ЭтаФорма, "ЗаполнитьКандидаты",,
{ИнструментыРазработчикаTormozit Обработка.ирУдалениеОбъектовСКонтролемСсылок.Форма.Форма.Форма(466)}:ЗаполнитьПомеченныеНаУдаление();

**Ожидаемое поведение**
Заполнение объектов помеченных на удаление

**Comment by tormozit** [comment]
Очень похоже, что ты сообщил вторичную ошибку. До нее наверное была первичная ошибка в виде сообщения пользователю?

**Comment by marv-ua** [comment]
> Очень похоже, что ты сообщил вторичную ошибку. До нее наверное была первичная ошибка в виде сообщения пользователю?

да, было, в строке сообщения:

{ИнструментыРазработчикаTormozit Обработка.ирУдалениеОбъектовСКонтролемСсылок.МодульОбъекта(475)}: Ошибка при вызове метода контекста (НайтиПомеченныеНаУдаление): При подписке ПереопределитьПолучаемуюФормуПрисоединенногоФайла на событие ОбработкаПолученияФормы произошла ошибка. Обработчик события не найден.

**Comment by tormozit** [comment]
При открытии первой в сеансе формы ИР какие сообщения выводит программа?

**Comment by marv-ua** [comment]
База перестала запускаться в толстом клиенте управляемое приложение. Поправлю проверю еще раз.

**Comment by tormozit** [comment]
Удалось поправить конфигурацию?

**Comment by tormozit** [comment]
Попробуй открыть обработчик подписки ПереопределитьПолучаемуюФормуПрисоединенногоФайла и для его общего модуля установить флажок "ВызовСервера".
