### ISSUE TITLE
Удаление объектов с контролем ссылок. Минимальный поиск. Битые ссылки.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#252]
<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.44.2p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС Текущая кодовая страница: 866
> Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. В инструменте "Удаление объектов с контролем ссылок" включил флажок "Минимальный поиск"
2. Вызвал команду "Контроль" и подтвердил удаление объектов после поиска
3. Открыл документы и обнаружил битую ссылку на удаленные элементы как "Объект не найден"

**Ожидаемое поведение**
Проверка на использование объектов в базе перед удаление

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/950075

**Comment by tormozit** [comment]
Исправлено в 6.45

**Comment by tormozit** [comment]
Было бы здорово проверить команду "Контроль" на маленьком, но содержащем все типы из исходного случая, примере.
