### ISSUE TITLE
Консоль запросов. Табличный документ. Сноски с пустыми типами значений

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#254]
https://user-images.githubusercontent.com/87958986/190954203-5a5d6087-1da3-49aa-a6d7-c125a20de9aa.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.45.1p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС Текущая кодовая страница: 866
> Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов", выполнил запрос
2. Выполнил команду  \ Панель \ Результат-коллекция(5*) \ Командная панель \ Вывести строки
3. Снял флажок "Колонки типов" в открывшемся диалоге
4. Получил Табличный документ с не заполненными сносками колонки типов

**Ожидаемое поведение**
Либо отсутствие сносок вообще, при отключенном флажке "Колонки типов", либо заполненные сноски

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/950679

**Comment by tormozit** [comment]
Исправлено в 6.46
