### ISSUE TITLE
Консоль запросов. Табличный документ. Не учитывается флажок "Редактирования"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#255]
https://user-images.githubusercontent.com/87958986/190954824-b756a788-1c37-4cd3-bc11-05806e615f5b.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.45.1p
> Инструменты разработчика. Инструмент: Табличный документ
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС Текущая кодовая страница: 866
> Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов", выполнил запрос
2. Выгрузил результат в Табличный документ
3. Попытался перейти по встроенной расшифровке в документ. Вместо этого ячейка открылась на редактирования, хотя режим редактирования отключен.

**Ожидаемое поведение**
Учитывать текущее значение режима редактирования документа.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/950382

**Comment by tormozit** [comment]
Исправлено в 6.46
