### ISSUE TITLE
Консоль запросов. Табличный документ. Длинные имена полей не выгружаются

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#256]
https://user-images.githubusercontent.com/87958986/190957223-77625c33-2d20-411e-9bbc-33697a9ae011.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.45.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС Текущая кодовая страница: 866
> Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Выполнил запрос:
```
ВЫБРАТЬ
	1 КАК ДлинноеПолеееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееее
```
3. Вызвал команду  \ Панель \ Результат-коллекция(1) \ Командная панель \ Вывести строки
4. Получил пустой табличный документ (видимо длинные имена полей не поддерживаются)

**Comment by tormozit** [comment]
Сейчас там 150 символов. Увеличу до 300. Хотя мне сложно представить что кто то в реальном коде превысил и 150.

**Comment by tormozit** [comment]
Сделал в 6.46
