### ISSUE TITLE
Структура БД. Ошибка при открытии "Обработчик события не найден"

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#257]
**Программное окружение**

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1710
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.44.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ПатчИМ ()
Расширения. ПатчДоставка ()
Расширения. ПатчИнтеркампаниДублиПередачТоваров ()
Расширения. Патч_ОтложенноеПроведение ()
Расширения. Патч_КонтрольОтрицательныхОстатков ()
Расширения. Патч_Обработка_УправлениемПоступлением ()
Расширения. Зооград (1.1.1.0)
Расширения. зг_ЗУП (1.0.1.7)
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет
</details>

**Воспроизведение проблемы**
1. Открыть комплексную автоматизацию
2. Открыть "Структура хранения БД"
3. Получить ошибку

> При подписке ПереопределитьПолучаемуюФормуПрисоединенногоФайлаСПАРКРиски на событие ОбработкаПолученияФормы произошла ошибка. Обработчик события не найден.
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(36307)}:Результат = ПолучитьСтруктуруХраненияБазыДанных(ОтборПоМетаданным, ЛиИменаБД);
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКэш.Модуль(143)}:Результат = ирОбщий.СтруктураХраненияБДЛкс(, ЛиИменаБД, АдресЧужойСхемыБД);
> {ИнструментыРазработчикаTormozit Обработка.ирСтруктураХраненияБД.МодульОбъекта(42)}:мСтруктураХраненияСУБД = ирКэш.СтруктураХраненияБДЛкс(Истина);
> {ИнструментыРазработчикаTormozit Обработка.ирСтруктураХраненияБД.Форма.Форма.Форма(122)}:ОбновитьТаблицы();
> {ИнструментыРазработчикаTormozit Обработка.ирСтруктураХраненияБД.Форма.Форма.Форма(55)}:ОбновитьТаблицыВФорме(Истина);
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(42925)}:Форма.Открыть();
> {ИнструментыРазработчикаTormozit Обработка.ирСтруктураХраненияБД.Команда.Команда1.МодульКоманды(4)}:ирОбщий.ОткрытьФормуЛкс("Обработка.ирСтруктураХраненияБД.Форма");
> 
> по причине:
> При подписке ПереопределитьПолучаемуюФормуПрисоединенногоФайлаСПАРКРиски на событие ОбработкаПолученияФормы произошла ошибка. Обработчик события не найден.

**Ожидаемое поведение**
Отсутствие ошибок.

**Способ обхода**
Сейчас помогает зайти в конструктор запросов. Пробежаться там по всем метаданным зажав ctrl+down.
После чего структура БД открывается.

**Comment by tormozit** [comment]
Попробуй выполнить проверку совместимости подписок 

![изображение](https://user-images.githubusercontent.com/11896251/191177817-ef810b6d-0768-478f-9888-e7283447d690.png)

**Comment by KovAlexey** [comment]
> В конфигурации обнаружены недоступные на клиенте (Управляемое приложение) общие модули с обработчиками подписок на события менеджеров.
> Поэтому в работе некоторых инструментов возможны ошибки "При подписке * на событие * произошла ошибка. Обработчик события не найден."
> Рекомендуется установить флажок "Вызова сервера" или "Клиент (Управляемое приложение)" и обеспечить компиляцию у этих общих модулей: РаботаСФайлами

Собственно, как я уже сказал. Помогает обойти прогон всех справочников в типовом конструкторе запросов.
Может это и программно как-то можно обойти?

**Comment by tormozit** [comment]
> Может это и программно как-то можно обойти?

Врядли. 
Выполнение инициализация модуля менеджера в описанной тобой ситуации похоже на исправленную ошибку платформы
https://partners.v8.1c.ru/forum/topic/1751092
https://bugboard.v8.1c.ru/error/000046221.html

А твой способ обхода вероятно как то связан с 
https://partners.v8.1c.ru/forum/topic/1870117
https://bugboard.v8.1c.ru/error/000046221.html
https://bugboard.v8.1c.ru/error/000051719

**Comment by tormozit** [comment]
В ERP 2.5.6.159 есть одноименная подписка, но такой ошибки нет, т.к. там исправили подписку, указав ей обработчик из модуля, доступного на толстом клиенте (РаботаСФайламиКлиентСервер)

**Comment by tormozit** [comment]
Проверь на последней версии конфигурации поставщика. Если ошибка воспроизведется, то нужно сообщить о ней поставщику. 
У меня нет номера NFR от твоей конфигурации. Ты готов отправить сообщение об ошибке в 1С или предоставить мне этот номер (тогда я отправлю сообщение)?

**Comment by KovAlexey** [comment]
Я пока ничего толком не успеваю по работе..
Я посмотрю в течение недели. Но почти уверен, что если в ERP исправлено, то в КА тоже. Всеж из одного собирается
