### ISSUE TITLE
Таблица значений. Некорректные значения в колонках при загрузке из текста

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#258]
**Программное окружение**

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1710
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.44.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ПатчИМ ()
Расширения. ПатчДоставка ()
Расширения. ПатчИнтеркампаниДублиПередачТоваров ()
Расширения. Патч_ОтложенноеПроведение ()
Расширения. Патч_КонтрольОтрицательныхОстатков ()
Расширения. Патч_Обработка_УправлениемПоступлением ()
Расширения. Зооград (1.1.1.0)
Расширения. зг_ЗУП (1.0.1.7)
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет
</details>

**Воспроизведение проблемы**
1. Открыть инструмент "Таблица значений"
2. Получить из текста текста с разделителем
![изображение](https://user-images.githubusercontent.com/16429518/191392538-ec3ee73b-6460-48b2-8d8b-8bf54de4096d.png)

> code	curr_date	beg_rest	in_qty	out_qty	end_rest
> 37ff5177-982a-11e2-8bad-001e67163420	17.09.2022	-3	0	5	-8
> 4bc8c417-cac1-11e3-b419-00155d00690b	17.09.2022	-10	0	1	-11
> 37ff5177-982a-11e2-8bad-001e67163420	14.09.2022	-2	0	1	-3
> 4bc8c417-cac1-11e3-b419-00155d00690b	14.09.2022	-9	0	1	-10
> 4bc8c417-cac1-11e3-b419-00155d00690b	10.09.2022	-8	0	1	-9

Сам текст.
3. Все корректно определяется.
![изображение](https://user-images.githubusercontent.com/16429518/191392782-e8f9cdc4-4eaa-43b3-9602-278c006e663d.png)

4. Но при загрузке в ТЗ - значения становятся некорректными (колонки in_qty, out_qty вдруг почему-то стали булевыми, это я уже руками типы исправил)
![изображение](https://user-images.githubusercontent.com/16429518/191392905-1b54a4f3-0e2c-486b-9da9-56023e6d6e53.png)

**Ожидаемое поведение**
1. Тип "число" для in_qty, out_qty
2. 5 в первой строке в колонке out_qty

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/950439

**Comment by tormozit** [comment]
Исправлено в 6.46

**Comment by tormozit** [comment]
закрывай заявку, если проверку сделал. По умолчанию я ее закрою через 3 недели.

**Comment by KovAlexey** [comment]
Проверил. Да, работает. Спасибо
