### ISSUE TITLE
Добавить в консоле запросов в список запросов колонки

### ISSUE THREAD

**Issue by TOLCOM31** [tormozit/RDT1C#259]
В консоле запросов в ДеревоЗапросов добавить колонки дата первого исполнения( или создания) и последняя дата исполнения
Пригодитса когда там запросов овер 300 и нейминг был плохой ))
Или просто понять года велась разработка именно етого запроса

**Comment by tormozit** [comment]
Думаю исчерпывающий ответ найдешь тут http://devtool1c.ucoz.ru/forum/3-2138-1
Самое важное продублирую здесь.
В списках консолей запросов и кода есть скрытая колонка ДатаВыполнения (Возраст выполнения).
