### ISSUE TITLE
Удаление объектов с контролем. Не ожидается окончание формирования кэша при Заполнении.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#26]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.06.1e
> Инструменты разработчика. Инструмент: Удаление объектов с контролем ссылок
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.06.1e)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: tcp

</details>

Если вызвать команду "Заполнить" в обработке "Удаление объектов с контролем ссылок", то при первом формировании кэша, команда не дожидается окончания и выдает ошибку:

```
Значение не является значением объектного типа (Метаданные)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(35858)}:	Возврат ОбработкаОбъект.Метаданные().ПолноеИмя() + ".";
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(35510)}:	ПрефиксКлючаПотока = ПрефиксКлючаПотокаЛкс(ЭтаФорма);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(4882)}:				ирОбщий.ОжидатьЗавершенияФоновойОперацииЛкс(ФоновоеЗадание);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(4906)}:	ПроверитьЗагрузитьКэшМДСеанса();
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.ВыборОбъектаМетаданных.Форма(374)}:	ДеревоИсточников = ДеревоОбъектовМД().Скопировать();
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.ВыборОбъектаМетаданных.Форма(213)}:	ЗаполнитьДеревоИсточников(, ?(мТолькоПомеченные, НачальноеЗначениеВыбора, Неопределено));
{ИнструментыРазработчикаTormozit Обработка.ирУдалениеОбъектовСКонтролемСсылок.Форма.Форма.Форма(96)}:		МассивРазрешенныхТипов = Форма.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Обработка.ирУдалениеОбъектовСКонтролемСсылок.Форма.Форма.Форма(441)}:	ЗаполнитьПомеченныеНаУдаление();

```
При последующих вызовов команды все отрабатывает, поэтому записать момент не удалось.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932291

**Comment by tormozit** [comment]
Исправлено в 6.06.2
