### ISSUE TITLE
В функцию ирОбщий.ОтЛкс() добавить возможность передавать менеджер временных таблиц

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#260]
С помощью функции ирОбщий.ОтЛкс() можно открывать через команду "Открыть объект для отладки", например, запрос со всеми временными таблицами в консоли запросов.

У меня пожелание добавить возможность передавать менеджер временных таблиц в эту функцию, чтобы через команду "Открыть объект для отладки" открывалась консоль запросов со всеми временными таблицами из этого менеджера временных таблиц.

**Comment by tormozit** [comment]
Сразу возникает вопрос - почему нельзя отловить запрос в том месте где он выполняется? Ведь там точно в самом запросе будет готовый менеджер временных таблиц.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/950477

**Comment by tormozit** [comment]
Реализовано в 6.46
