### ISSUE TITLE
Консоль запросов, результат запроса, команда "Вывести строки стаблицы": не выводить заголовок

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#261]
В параметрах вывода строк таблицы в табдок хочу флажок, позволяющий отказаться от вывода заголовка (шапки) таблицы в табдок

**Comment by tormozit** [comment]
Неужели так сложно вручную удалить первую строку в сформированном табличном документе? Сколько кликов у тебя на это уходит?

**Comment by john-doe-1c** [comment]
> Неужели так сложно вручную удалить первую строку в сформированном табличном документе? Сколько кликов у тебя на это уходит?

Три клика (выделить строку щелчком по "системному" номеру строки, ПКМ, удалить).
Согласен, что потребность, возможно, не стоит отдельного флажка. С другой стороны форма параметров вывода позволяет не думать об экономии и еще один ряд флажков ее вряд ли ухудшит.

Я еще руководствуюсь соображениями, что такая опция (выводить заголовки или не выводить) присутствует много где в мире ИТ (вообще) и в 1С (в частности - СКД и УФ), поэтому был удивлен, что в кастомной реализации вывода данных в табдок ты ее еще не сделал.

**Comment by tormozit** [comment]
Слишком большое число полей на форме затрудняет поиск нужного. Поэтому нужно не просто добавлять флажки, но соотносить их с затруднением поиска. И такая операция врядли будет часто выполняться. Поэтому не считаю, что флажок имеет смысл добавлять. Если же операция будет выполняться часто, то очень вероятно что пользователь выбрал неверный путь решения задачи и ему больше подойдет консоль компоновки. Кроме того СКД не позволяет пользователю просто скрыть заголовки полей. Да и в других местах интерфейса пользователя 1С не припоминаю подобных возможностей.
