### ISSUE TITLE
Выведение списка из результата запроса

### ISSUE THREAD

**Issue by LordSenya** [tormozit/RDT1C#262]
**Программное окружение**

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.13.1926
Режим БД: клиент-серверный
Конфигурация. Название: ASSOL_Рабочая ()
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_3_11
Инструменты разработчика. Версия: Портативный 6.46.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru_RU
Клиент. ОС: Microsoft Windows Server 2008 R2 Enterprise  64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да</summary>  
</details>

**Воспроизведение проблемы**
1. Открыл "Консоль запросов"
2. Выполнил запрос и получил результат 12129 строк
3 клик правой кнопкой мыши на табличном документе
4 выбираю "Вывести список"
В версии Портативные 5.66p операция выполняется 12секунд
В текущей Портативный 6.46.1p операция выполняется 2 минуты 15 секунд

**Ожидаемое поведение**
Ожидалось одинаковое время выведения или меньше
[техничесские данные.txt](https://github.com/tormozit/RDT1C/files/9674381/default.txt)

**Comment by tormozit** [comment]
Нужен снимок полный консоли запросов перед вызовом команды. Желательно чтобы все колонки было видно и их типы.
Для теста сократи число строк в таблице в 10 раз и запускай клиентской приложение с параметром запуска РежимОтладкиИР (не забудь его потом убрать - он замедляет работу кода).
Очень хотелось бы построчный замер производительности увидеть с новом сеансе для старой версии ИР и в новом сеансе для новой версии ИР.
Есть ли у типов ссылок, представленных в табличном поле, обработчики формирования представления в модулях менеджеров?
Попробуй командой "Вывести строки" с вЫключенным флажком "Без оформления" и с включенным. Как будет отличаться время в обоих случаях между собой и от команды контекстного меню?

**Comment by LordSenya** [comment]
29 сентября 2022, 18:51:01, от "Sergey Starykh" ***@***.***>:

Нужен снимок полный консоли запросов перед вызовом команды.
Для теста сократи число строк в таблице в 10 раз.
Очень хотелось бы построчный замер производительности увидеть.
Есть ли у типов ссылок, представленных в табличном поле, обработчики формирования представления в модулях менеджеров?
Попробуй командой "Вывести строки" с вЫключенным флажком "Без оформления" и с включенным. Как будет отличаться время в обоих случаях и с командой контекстного меню?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.
Привет, сорян, что долго не отвечал
"Очень хотелось бы построчный замер производительности увидеть"
Извини не понял о чем ты

"Есть ли у типов ссылок, представленных в табличном поле"
Да это документ
"обработчики формирования представления в модулях менеджеров"
 нет это неуправляемые формы"
"Попробуй командой "Вывести строки" с вЫключенным флажком "Без оформления" и с включенным. Как будет отличаться время в обоих случаях и с командой контекстного меню?"
никак

**Comment by tormozit** [comment]
пример построчного замера производительности

![изображение](https://user-images.githubusercontent.com/11896251/194143680-e5c0a61b-f2f8-4cf1-87bc-c998204770c1.png)

**Comment by LordSenya** [comment]
5 октября 2022, 22:16:32, от "Sergey Starykh" ***@***.***>:


пример построчного замера производительности

**Comment by tormozit** [comment]
Пожалуйста перестань отвечать через почту и пиши ответ в самой заявке.

**Comment by tormozit** [comment]
Похоже причина проблемы найдена https://www.hostedredmine.com/issues/951951
