### ISSUE TITLE
Консоль запросов, результат запроса, команда "Вывести строки стаблицы": разбивать имена полей выборки (колонок таблицы-результата) в отдельные слова

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#263]
В параметрах вывода строк таблицы в табдок хочу флажок, позволяющий автоматически разбивать заголовки колонок на отдельные слова.
Например, в запросе поле "КодТовара" при выводе в табдок должно превратиться в "Код товара" (как это делает СКД для своих полей или конфигуратор для синонимов различных объектов метаданных).

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/951005

**Comment by tormozit** [comment]
Реализовано в 6.47
