### ISSUE TITLE
Проблема поиска запроса по тексту в консоле запросов

### ISSUE THREAD

**Issue by TOLCOM31** [tormozit/RDT1C#264]
**Программное окружение**
Платформа: 8.3.13.1644
Режим БД: клиент-серверный
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_2_13
Инструменты разработчика. Версия: Портативный 6.46.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

**Воспроизведение проблемы**
1. Открыл инструмент ирКонсольЗапросов
3. Нажал кнопку ВпередНажатие строка кода 10131
4. Получил окно с ошибкой {ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(10133)}: Недостаточно фактических параметров
	ирОбщий.СледующееВхождениеСтрокиПоискаВТабличномПолеЛкс(ЭтаФорма, ЭлементыФормы.ДеревоЗапросов);

**Ожидаемое поведение**
переход на строку с найденым з значнением в дереве запросов
Проблема в том что процедура СледующееВхождениеСтрокиПоискаВТабличномПолеЛкс имеет 3 параметра а на форме указано 2 
Процедура СледующееВхождениеСтрокиПоискаВТабличномПолеЛкс(ЭтаФорма, ТабличноеПоле, _СтруктураПоиска) Экспорт

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/951049

**Comment by tormozit** [comment]
Исправлено в 6.47
