### ISSUE TITLE
ТестированиеМетаданных.  Метод объекта не обнаружен (Снимок)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#265]
https://user-images.githubusercontent.com/87958986/193889276-0e71abde-8c05-415d-b9a6-e14c96bc3fe3.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

> Платформа: 8.3.20.1549
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.244)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.47.1p
> Инструменты разработчика. Инструмент: Тестирование метаданных
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС Текущая кодовая страница: 866
> Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Тестирование метаданных"
2. Выбрал справочники
3. Нажал кнопку "Выполнить"
4. Вместо текстов с ошибками на строках вижу одну

```
Метод объекта не обнаружен (Снимок)
{ВнешняяОбработка.ирТестированиеМетаданных.МодульОбъекта(207)}: ОбразОбъекта = СтруктураОбъекта.Методы.Снимок();
{ВнешняяОбработка.ирТестированиеМетаданных.МодульОбъекта(133)}:                                 ПроверитьСсылочныйОбъект(СтруктураОбъекта, ИмяОперации, СтрокаТипаМетаданных.Единственное, Истина);
{ВнешняяОбработка.ирТестированиеМетаданных.Форма.Форма.Форма(647)}:     ГлобальныйТестОбъектов(ЭтаФорма);
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/951398

**Comment by tormozit** [comment]
Исправлено в 6.48
