### ISSUE TITLE
Консоль кода. Редактирование схемы компоновки данных в параметрах.

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#266]
Просьба в консоли кода добавить возможность устанавливать и редактировать параметр с типом "СхемаКомпоновкиДанных".
На текущий момент, если добавить схему в параметр, то редактировать ее нельзя. Можно только полностью заместить параметр новой схемой из сериализованных данных, что довольно неудобно.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/951410

**Comment by tormozit** [comment]
Реализовано в 6.48
