### ISSUE TITLE
ИР + EDT (Ошибки Конфигурации)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#267]
В EDT отсутствуют адекватные способы фильтрации результатов проверки на ошибки конфигурации. Даже если просто поставить фильтр по фразе, то прокрутка списков результатов занимает целую вечность.
Более менее работает следующий вариант - выгрузка результатов в .tsv файла. Это обычный текстовый "Tab Delimited" формат в UTF-8 кодировке, который легко импортируется в Excel. Далее можно накладывать любые фильтры и искать то, что интересует.
Но этого мало т.к. надо еще знать что искать.

Предложение. Добавить в ИР новый инструмент, который будет преобразовывать .tsv файл в таблицу (как вариант добавить "представление" - в виде дерева). На форму добавить различные фильтры и отборы, которые позволят отображать лишь действительно важные ошибки. Плюс фильтр по метаданным и всех ошибок связанных с этим объектом.

https://user-images.githubusercontent.com/87958986/194125324-e4642373-b66c-49ca-95e8-284aae622e8d.mp4

Пример tsv файла с ошибками (ошибки конфигурации поставщика ERP 2.5.8.267).
[Problems_ERP2_5_8_267.zip](https://github.com/tormozit/RDT1C/files/9717807/Problems_ERP2_5_8_267.zip)

**Comment by tormozit** [comment]
EDT пока далек от пригодности к удобной стабильной разработке. Мне казалось ты уже понял это. Года через 2 можно будет подумать над подобным пожеланием.  

Полный список проверок EDT на 50-70% содержит бесполезные и даже вредные замечания. Весь его выгружать/загружать и делать прочее - много пустой траты времени.

Существующим функциональном ИР можно загрузить CSV файл в таблицу значений. Но правда сейчас там безусловно будет выполняться промежуточная передача этой таблицы в загрузку табличных данных, что для 300к строк будет выполняться довольно долго.  Создал задачу на обход этой затратой операции https://www.hostedredmine.com/issues/951443
А дальше можно использовать команды "Группировка таблицы" или "Различные значения колонки" для анализа данных. 

![изображение](https://user-images.githubusercontent.com/11896251/194132851-d9738e3e-4c40-4099-afc7-c93ec97aa7fa.png)

**Comment by PerlAmutor** [comment]
Попробовал ИР 6.48.1p, файловый вариант базы. Не дает загрузить, падает с нехваткой памяти (клиент 64 бит)

![image](https://user-images.githubusercontent.com/87958986/195986126-07bc4b49-693f-40e3-9dc6-7fcce43ca5dc.png)

**Comment by tormozit** [comment]
У меня твой файл загружается даже в 32б приложении. Правда я проверяю в непортативном варианте. Но вроде бы это не должно играть роли.

Платформа: 8.3.22.1553
Режим БД: клиент-серверный
Конфигурация. Название: Комплексная автоматизация, редакция 1.1  (1.1.20.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_13
Конфигурация. Версия БСП: 102
Инструменты разработчика. Версия: Конфигурация 6.48.1
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 32б
Сервер. Отладка: http

![изображение](https://user-images.githubusercontent.com/11896251/195987573-c2cc9e93-ab17-4cf4-8bfa-a9574588c746.png)

![изображение](https://user-images.githubusercontent.com/11896251/195987697-76b67d4b-2056-4d8c-b362-44aa7939cb38.png)

**Comment by PerlAmutor** [comment]
Похоже косяк платформы. Заменил 8.3.20 на 8.3.22 и стало нормально.
