### ISSUE TITLE
Консоль компоновок данных. "Внешние" ВТ.

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#268]
Просьба в консоли компоновки данных в алгоритмах перед выполнением дать возможность создавать передаваемый в компоновку менеджер временных таблиц.
Так же просьба расширить функциональность ИрОбщий.ОтЛкс(), добавив туда возможность с со схемой компоновки и настройками передавать уже заполненный менеджер временных таблиц.

**Comment by tormozit** [comment]
Задача по функции От() https://www.hostedredmine.com/issues/905285

**Comment by tormozit** [comment]
реализовано в 6.48

**Comment by tormozit** [comment]
Задача по консоли компоновки https://www.hostedredmine.com/issues/951495

**Comment by tormozit** [comment]
реализовано в 6.48

**Comment by KovAlexey** [comment]
Создавать новый ишуз?
Теперь нельзя этот запрос с менеджером ВТ открыть в кострукторе запросов 
ВТ туда не пробрасывается.
![изображение](https://user-images.githubusercontent.com/16429518/203236622-a764b0f7-daa7-4f43-a85e-6ceeb21c11e6.png)
![изображение](https://user-images.githubusercontent.com/16429518/203236659-2992d549-5c7e-47f6-a556-3a780be3a22a.png)

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/954530

**Comment by tormozit** [comment]
Реализовано в 6.54
