### ISSUE TITLE
Определение колонок ТЗ в параметре консоли запросов

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#269]
Возможно ли добавить автоматическое определение состава колонок ТЗ для консоли запросов, если параметра не было?
![изображение](https://user-images.githubusercontent.com/16429518/194468300-d21ed788-f64e-4e6f-9189-fdc7dc1ab8bb.png)

На данный момент параметр определяет правильно.
Но список колонок в нем пустой
![изображение](https://user-images.githubusercontent.com/16429518/194468329-9b61dafe-2c15-4188-9694-50cb361ad785.png)

Как предложение, если тип явно не указан - тогда колонки с произвольным типом.
Если есть выразить - тогда колонки с теми типами, что указанны.

**Comment by tormozit** [comment]
Консоль непосредственно не сможет это делать. Но сможет конструктор запроса ИР. Создал задачу https://www.hostedredmine.com/issues/951518

**Comment by tormozit** [comment]
Реализовано в 6.48

**Comment by KovAlexey** [comment]
Спасибо.
