### ISSUE TITLE
Конструктор запросов ИР. Копирование запроса в буфер обмена в виде текста.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#27]
https://user-images.githubusercontent.com/87958986/130406015-4ca97309-5e80-46d0-95ce-dd088bc94887.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.06.1e
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.06.1e)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: tcp

</details>

При частичном выделении текста запроса, вызов команды "Копировать в виде кода" в Конструкторе Запросов ИР выдает ошибку:

```
Слишком много фактических параметров
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1188)}:		НовыйТекстЗапроса = "|" + ирОбщий.УдалитьВнешниеСкобкиВыраженияЛкс(НовыйТекстЗапроса, """", , Символы.ПС + "|""");
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(938)}:			КопироватьВБуферОбменаТекстВВидеКода();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(891)}:	Результат = ВыполнитьКоманду(Команда);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(53)}:		Результат = ЭкземплярКомпоненты.Нажатие(Кнопка);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2746)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(930)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(891)}:	Результат = ВыполнитьКоманду(Команда);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(284)}:		Результат = ЭкземплярКомпоненты.Нажатие(Кнопка);
```

По мотивам AAC.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932335

**Comment by tormozit** [comment]
Исправлено в 6.07.1
