### ISSUE TITLE
Список индексов временных таблиц в Консоли Запросов

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#270]
Отлаживал расчет себестоимости в ERP через функцию От(), чтобы понять почему запрос долго выполняется. Выяснилось, что запрос использует временную таблицу, у которой состав индекса может быть динамическим. Пример функция ЗаполнитьНомераСтрокВременнойТаблицы() общего модуля "РасчетСебестоимостиПрикладныеАлгоритмы" из ERP 2.5.8.267:

![image](https://user-images.githubusercontent.com/87958986/194760327-e1e6531a-b840-4dd7-b94a-a9260dfe781b.png)

В результате невозможно понять выполняется ли запрос полученный через функцию От() с той же скоростью, что и запрос в рантайме, и как следует оптимизировать запрос ориентируясь на состав индексов временной таблицы. Сейчас получить состав индексов временных таблиц через ИР не представляется возможным.

**Comment by tormozit** [comment]
Платформа не предоставляет такой возможности. Пиши пожелание в 1С на добавление в объект ВременнаяТаблицаЗапроса описания индекса.

**Comment by PerlAmutor** [comment]
Написал в @platform_suggestions
