### ISSUE TITLE
Ошибка при сравнении таблиц

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#271]
**Программное окружение**

Платформа: 8.3.21.1484
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: НеИспользовать
Инструменты разработчика. Версия: Расширение 6.46.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.46.1e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

**Воспроизведение проблемы**
1. С помощью редактора объекта сравниваю две ссылки через команду заполнить ссылку для сравнения:
![изображение](https://user-images.githubusercontent.com/12731230/194833312-3814c0ba-2c5e-4819-8c04-243649f3cc13.png)
2. Каждую таб.часть сравниваемых ссылок открываю сначала в исследователе объекта, потом в исследователе значения, потом нажимаю кнопу "Запомнить содержимое для сравнения".
![изображение](https://user-images.githubusercontent.com/12731230/194834347-a99e76aa-46e5-49c0-855a-53074fa40910.png)
![изображение](https://user-images.githubusercontent.com/12731230/194834336-e6e8a741-a7d9-40d6-866c-1019ca54f1fb.png)
3. После второй передачи в буфер сравнения соглашаюсь, что надо сравнить с пред.значением и получаю ошибку:
![изображение](https://user-images.githubusercontent.com/12731230/194834757-1c013703-3a71-4e8e-a6e6-e39bce551e60.png)
Текст ошибки:
Ошибка при вызове метода контекста (Выполнить)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(39396)}:ФоновоеЗадание = ФоновыеЗадания.Выполнить(ОписаниеЗадания.Метод, ОписаниеЗадания.Параметры, , ЭтаФорма.Метаданные().Представление() + ". " + ОписаниеЗадания.Представление);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(33340)}:Результат = ирОбщий.ЗапуститьИлиОтменитьФоновоеЗаданиеФормыЛкс(ЭтаФормаИлиОбработка, ОписаниеЗадания, Перезапустить);
{ИнструментыРазработчикаTormozit Обработка.ирСравнениеТаблиц.Форма.Форма.Форма(180)}:РезультатЗадания = ирОбщий.ВыполнитьЗаданиеФормыЛкс("СравнитьТаблицы", ПараметрыЗадания, ЭтаФорма,,, Кнопка, "СравнитьТаблицыЗавершение", Кнопка <> Неопределено, БлокируемыеЭлементыФормы);
{ИнструментыРазработчикаTormozit Обработка.ирСравнениеТаблиц.Форма.Форма.Форма(433)}:СравнитьТаблицыВФорме();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10310)}:ФормаСравнителя.Открыть();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10286)}:СравнитьТаблицыИнтерактивноЛкс(Значение1, Значение2, Модально);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10528)}:Сравнить2ЗначенияВФормеЛкс(СравниваемыйДокумент1, СравниваемыйДокумент2,,,,, ТекущееСвойство,,, ВариантСинтаксиса, ЗаголовокЭлементаФормы);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10459)}:ДобавитьОбъектВБуферИПредложитьСравнениеЛкс(СравниваемыйДокумент, ЭтаФорма,, ЗаголовокЭлементаФормы, ВариантСинтаксиса);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(41454)}:ЗапомнитьСодержимоеЭлементаФормыДляСравненияЛкс(ЭтаФорма, ИсточникДействий);
{ИнструментыРазработчикаTormozit Обработка.ирИсследовательОбъектов.Форма.ИсследовательКоллекций.Форма(320)}:ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);

[ОшибкаВоВремяВыполненияВстроенногоЯзыка]
по причине:
Параметр фонового задания не поддерживает сериализацию 

![изображение](https://user-images.githubusercontent.com/12731230/194834853-83734136-8816-4786-8d2e-47d39b834fdc.png)
Ошибка при вызове метода контекста (Сохранить)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(31760)}:ХранилищеОбщихНастроек.Сохранить(ирКэш.ИмяПродукта(), КлючНастроек, Значение,, ИмяПользователя);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(27568)}:СохранитьЗначениеЛкс(МенеджерСохраненияНастроек.КлючНастроек, МенеджерСохраненияНастроек.СохраненныеНастройки);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(41131)}:СохранитьНастройкуФормыЛкс(ЭтаФорма);
{ИнструментыРазработчикаTormozit Обработка.ирСравнениеТаблиц.Форма.Форма.Форма(977)}:ирОбщий.Форма_ПриЗакрытииЛкс(ЭтаФорма);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10310)}:ФормаСравнителя.Открыть();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10286)}:СравнитьТаблицыИнтерактивноЛкс(Значение1, Значение2, Модально);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10528)}:Сравнить2ЗначенияВФормеЛкс(СравниваемыйДокумент1, СравниваемыйДокумент2,,,,, ТекущееСвойство,,, ВариантСинтаксиса, ЗаголовокЭлементаФормы);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10459)}:ДобавитьОбъектВБуферИПредложитьСравнениеЛкс(СравниваемыйДокумент, ЭтаФорма,, ЗаголовокЭлементаФормы, ВариантСинтаксиса);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(41454)}:ЗапомнитьСодержимоеЭлементаФормыДляСравненияЛкс(ЭтаФорма, ИсточникДействий);
{ИнструментыРазработчикаTormozit Обработка.ирИсследовательОбъектов.Форма.ИсследовательКоллекций.Форма(320)}:ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);

[ОшибкаВоВремяВыполненияВстроенногоЯзыка]
по причине:
Ошибка формата объекта настроек

**Ожидаемое поведение**
Ожидал, что откроется сравнение таблиц.
Я потом нашел, что можно было нажать на поле "Изменено" слева от таб.частей и сравнение работает корректно, но ошибку решил зарепортить.
![изображение](https://user-images.githubusercontent.com/12731230/194833954-fae36797-3778-4b76-b52f-afd497503939.png)

Ошибка воспроизводится на доработанной УНФ на платформе 8.3.18.1741.
Базу, в которой воспроизводил ошибку, приложил.
[1Cv8.zip](https://github.com/tormozit/RDT1C/files/9744720/1Cv8.zip)

**Comment by tormozit** [comment]
Ситуацию воспроизвел. В этом случае в таблицах присутствуют значения несерилизуемых типов (Табличная часть строка). Пока не смог придумать как тут улучшить программу.
Для обхода проблемы нужно отключить вывод колонки "_ЗначениеЭлемента".

**Comment by tormozit** [comment]
Буду исправлять https://www.hostedredmine.com/issues/952207

**Comment by tormozit** [comment]
Исправлено в 6.50

**Comment by tormozit** [comment]
Предыдущее исправление было неполноценным. Делаю новое https://www.hostedredmine.com/issues/956621
