### ISSUE TITLE
В список значений не загружаются данные

### ISSUE THREAD

**Issue by starasov43** [tormozit/RDT1C#272]
Открыть любой список документов, выполнить команду "Настройка списка", добавить отбор с сравнением "В списке", открыть форму списка, нажать CTRL-ё, выполнить команду "Загрузить строки", в открывшейся форме не создается "предопределенная строка" с названием колонки. 

Она создается только если в списке значений есть хотя бы одна строка.
![image](https://user-images.githubusercontent.com/115646769/195376529-f8d120c3-ae80-4de1-9a73-4dbc76960938.png)

**Comment by tormozit** [comment]
Воспроизвести проблему на 8.3.22 не удалось. Нужна техническая информация http://devtool1c.ucoz.ru/forum/2-2-1

**Comment by tormozit** [comment]
У меня так 
![изображение](https://user-images.githubusercontent.com/11896251/195979197-9fcaf7be-cbc9-4d70-a89c-3fd8fc3f574e.png)

**Comment by tormozit** [comment]
В версии 6.49 появилась возможность групповой вставки элементов списка через буфер обмена https://www.hostedredmine.com/issues/951969

**Comment by starasov43** [comment]
Платформа: 8.3.20.1674
Режим БД: клиент-серверный
Конфигурация. Название: TMS X4 (4.0.4.4)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Версия БСП: 300
Инструменты разработчика. Версия: Расширение 6.33.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.33.1e)
Клиент. ОС: Microsoft Windows Server 2019 Standard 64-bit Русский
Клиент. Приложение: Управляемое приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Microsoft Windows Server 2019 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Comment by tormozit** [comment]
Вероятно проблема была в старой версии инструментов. Проверь на актуальной.
