### ISSUE TITLE
Консоль компоновок данных. Убрать снятие ограничения доступности

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#274]
Возможно ли сделать так, чтоб не снималось ограничение доступности при использовании консоли компоновки данных? При открытии схемы компоновки с настройками через ИрОбщий.ОтЛкс(Схема, Настройки)
Сейчас подредактировал схему в консоли компоновки, поместил в хранилище не глядя.
И обнаружил, что большой список параметров стал доступным без моего желания.

![изображение](https://user-images.githubusercontent.com/16429518/195733159-2d9a030f-b484-4879-b849-d8b04868f47f.png)

**Comment by tormozit** [comment]
Все таки главное назначение функции От*() - отладка. Снятие ограничений доступности параметров заметно облегчает эту задачу, т.к. такие параметры могут быть установлены программно и в этом случае важно видеть их значения. И именно в этом случае происходит снятие их ограничений в схеме. А возвращение схемы в конфигурацию при этом случается нечасто. Также инструмент сообщает о том, что он снял этот признак при открытии формы. Можно конечно задавать вопрос, но он кажется будет раздражать.

Пока не вижу хорошего выхода.

Рациональный подход к редактированию схемы компоновки - брать ее из конфигурации, загружать в консоль, редактировать, сохранять в конфигурацию. Ну или вручную дублировать изменения в конфигурации, если они мелкие и их немного.

**Comment by KovAlexey** [comment]
От() очень хорошо помогает найти проблему при определенной комбинации параметров и тут же ее исправить.

В случае загрузки схемы из конфы, нужно будет:
1) Сохранить параметры пользователя
2) Загрузить схему в СКД
3) Загрузить параметры

Или же запоминать изменения, которые произвел и переносить их вручную.
И хорошо, если это запрос. Плохо, если это вычисляемые поля + ресурсы + параметры + запрос.

Может какой-нибудь доп параметр к От()? Или глобальный параметр, который можно будет поставить для удобного поведения?

**Comment by KovAlexey** [comment]
>Снятие ограничений доступности параметров заметно облегчает эту задачу, т.к. такие параметры могут быть установлены программно и в этом случае важно видеть их значения. 

Тем более мы же итак получается видим такие параметры, даже если есть ограничение

![изображение](https://user-images.githubusercontent.com/16429518/197094047-5d6fc2ad-e0be-493d-bd51-1c190c90f0bf.png)

![изображение](https://user-images.githubusercontent.com/16429518/197093849-77690f06-8348-44d7-935d-f2996468fcf5.png)

**Comment by tormozit** [comment]
> случае загрузки схемы из конфы

В случае использования команды "Из конфигурации" нет описанной тобой проблемы.

**Comment by KovAlexey** [comment]
![изображение](https://user-images.githubusercontent.com/16429518/197117222-9a8b12e1-0ee2-4aaa-a66d-2dfe5bfc3ee2.png)

Я похоже чего-то не улавливаю?

**Comment by tormozit** [comment]
Я ошибся. Команда называется "По метаданным".

**Comment by KovAlexey** [comment]
И что-то я все равно не очень улавливаю, как эта команда решает проблему..
Оно же просто создает схему сразу с запросом к метаданным

**Comment by tormozit** [comment]
Если подсказку к команде "По метаданным" не прочитал или команда не позволяет достать нужную схему из макета, то можно использовать команду "Загрузить из файла" в конструкторе схемы компоновки.

**Comment by KovAlexey** [comment]
Не позволяет. Схема в документе.

А "загрузить из файла" подпортит параметры самой схемы, заменив своими.

**Comment by KovAlexey** [comment]
В том то и все удовольствие у От().
Оно позволяет получить схему с настройками с уже заполненными всеми параметрами.
А не готовить сначала событие перед компоновкой или же вручную их ставить.

**Comment by tormozit** [comment]
Разработчики платформы не рекомендуют устанавливать в настройках  компоновки значения параметрам, у которых включен флажок "Ограничение доступности" в схеме, т.к. их значения могут не сохраняться/загружаться/применяться в некоторых случаях. Чтобы избавить пользователя от необходимости знать эти тонкости, консоль компоновки в некоторых случаях убирает этот флажок.

![изображение](https://user-images.githubusercontent.com/11896251/197124467-0d5e8481-e7df-4398-8638-ffbd70cc719f.png)

**Comment by tormozit** [comment]
> А "загрузить из файла" подпортит параметры самой схемы, заменив своими.

Не понял. Я про системное окно конструктора схемы компоновки. Там прикладной код не выполняется. 

![изображение](https://user-images.githubusercontent.com/11896251/197126183-12a3b30c-fd28-428b-b245-6b25a262f071.png)

**Comment by KovAlexey** [comment]
Так, давай заново. Попробую донести.

>Разработчики платформы не рекомендуют устанавливать в настройках компоновки значения параметрам, у которых включен флажок "Ограничение доступности" в схеме, т.к. их значения могут не сохраняться/загружаться/применяться в некоторых случаях. Чтобы избавить пользователя от необходимости знать эти тонкости, консоль компоновки в некоторых случаях убирает этот флажок.

Эти настройки устанавливаются исключительно программно. Являются по факту константами, не зависят от вариантов.
Это конкретно параметры схемы, а не "варианта отчета".
Пользователь эти настройки видеть не должен. Но заполнять их при отладке самому - довольно трудоемкая задача.

Не сохраняются и не загружаются эти параметры именно в настройке варианта, т.к. у них даже использование ложь стоит. И при сериализации они в любом случае потеряются.

![изображение](https://user-images.githubusercontent.com/16429518/197140887-00bd0126-5348-488b-9823-61b4de8a1627.png)
![изображение](https://user-images.githubusercontent.com/16429518/197141016-78c44e53-d60f-4187-ad70-7bcd8e7a45cf.png)

Допустим во время работы оказалось, что при определенном наборе параметров возникает ошибка.
Соответственно, мне нужно получить схему с этими параметрами.
И тут есть три варианта:
1) Либо я руками проставляю настройки во вкладке параметры, затем пользовательские загружаю\устанавилваю.
2) Либо я пишу алгоритм, который перед компоновкой задаст эти параметры схеме. Не варианту, а именно схеме.
3) Либо я использую От и получу эту схему, с настроенными параметрами и СКД, и варианта

Я хочу пофиксить проблему.
И если в 1 и 2 трудоемких вариантах я могу после задания настроек просто спокойно изменить схему, сохранить ее из редактора СКД и загрузить в конфигурацию.
То в третьем варианте мне теперь требуется сначала вспомнить, а какие несколько часов назад галочки сняла консоль компоновки. Т.к. иначе пользователь получит на своей форме параметры, которые он видеть не должен в принципе.

Соответственно, не хочется, чтоб ограничение доступность снималось. Т.к. фактически никакой пользы от этого не видно.
Те параметры, что заданы в схеме, но ограничены к использованию, я все равно вижу в компоновке. Просто менять их из самой консоли смысла никакого нет.

**Comment by KovAlexey** [comment]
> Не понял. Я про системное окно конструктора схемы компоновки. Там прикладной код не выполняется.

И я про нее.
![изображение](https://user-images.githubusercontent.com/16429518/197142308-52949acd-806e-45b4-8900-5c53dd4c2039.png)
Но эти параметры хранятся в самой схеме. Их значения со схемой тоже передаются.
Соответственно все то, что было установлено программно до вызова От() стирается.

**Comment by tormozit** [comment]
Вот теперь ты достаточно подробно объяснил ситуацию. Теперь я понял что значения параметрам ты задаешь кодом в схеме компоновки, а не в настройках компоновки. Теперь смотри на программный код, который выполняет это неудобное тебе изменение
```
				ЗначениеПараметра = Настройки.ПараметрыДанных.НайтиЗначениеПараметра(Новый ПараметрКомпоновкиДанных(ПараметрСхемы.Имя));
				Если Истина
					И ЗначениеПараметра <> Неопределено
					И ЗначениеПараметра.Использование
				Тогда 
					ПараметрСхемы.ОграничениеИспользования = Ложь;
					ирОбщий.СообщитьЛкс("Для используемого скрытого параметра """ + ПараметрСхемы.Имя + """ выполнено снятие ограничения использования в схеме компоновки.");
				КонецЕсли;
```
Он срабатывает только когда у недоступного параметра в настройках ВКЛЮЧЕНО ИСПОЛЬЗОВАНИЕ, что подразумевает, что программист умышленно задает значение недоступному параметру через настройки компоновки. В этом случае при компоновке значение из схемы игнорируется и используется именно значение из настроек компоновки https://partners.v8.1c.ru/forum/t/690982/m/691114 . Разработчики платформы ошибкой это не посчитали, поэтому пришлось в консоли делать несколько фич, делающих эту особенность более очевидной.

Попробуй не включать использование таких параметров в настройках компоновки.

**Comment by tormozit** [comment]
Вроде бы придумал поведение, учитывающее все сложности без модификации схемы https://www.hostedredmine.com/issues/952524

**Comment by tormozit** [comment]
Реализовано в 6.50
