### ISSUE TITLE
Добавить панель "Свойства" в таблицу значений в консоли компоновок данных

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#275]
Сейчас, чтоб с удобством просматривать данные строки, после выполнения компоновки приходится открывать отдельно таблицу значений, где уже смотреть свойства конкретной строки.
По колонкам, когда их у тебя даже 30 просмотр, к сожалению, не так удобен.
![изображение](https://user-images.githubusercontent.com/16429518/197093027-d4c07bcf-3a2a-421f-a8a7-f0a09bcdc2ac.png)

**Comment by tormozit** [comment]
Пожелание не понятно. В консоли компоновок нет отображения содержимого таблицы значений. Там лишь есть открытие таблицы значений в редакторе таблицы значений.

**Comment by KovAlexey** [comment]
Ну так фактически в консоли компоновки отображается таблица значений.
И хочется видеть все ее поля так же, как в инструменте "Таблица значений"

**Comment by tormozit** [comment]
>И хочется видеть все ее поля так же, как в инструменте "Таблица значений"
Превращать консоль компоновки в редактор таблицы значений я точно не буду.

**Comment by tormozit** [comment]
Теперь понял, что ты писал про таблицу значений в панели результата. А я подумал что ты имел ввиду входную таблицу значений. Постарайся делать более опозноваемые снимки. 

![изображение](https://user-images.githubusercontent.com/11896251/200163739-aaeffaa9-4a11-4fa2-8a65-5dffcacf4d25.png)

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/953421

**Comment by tormozit** [comment]
Реализовано в 6.51
