### ISSUE TITLE
Дин. список: Выделить Н первых строк

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#276]
> Платформа: 8.3.17.1851
> Режим БД: клиент-серверный
> 
> Инструменты разработчика. Версия: Конфигурация 6.49.3
> Инструменты разработчика. Инструмент: Динамический список
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Асинхронность запрещена: Нет
> Инструменты разработчика. Разрешены имитаторы: Да
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-bit Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС Active code page: 866
> Клиент. ОС выполнение BAT: Да
> Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: tcp
> 

1. Открыл дин. список.
2. Нажал кнопку **Выделить Н первых строк**
3. Нажал ОК.
4. Получил окно с ошибкой
```
Тип не определен (ТабличноеПоле)
{ОбщийМодуль.ирОбщий.Модуль(4819)}:		Если ТипЗнч(ТабличноеПолеПриемник) = Тип("ТабличноеПоле") Тогда
{ОбщийМодуль.ирОбщий.Модуль(4662)}:		СкопироватьЭлементыКомпоновкиЛкс(ОтборПриемник, ОтборИсточник, ОчищатьПриемник);
{ОбщийМодуль.ирОбщий.Модуль(38949)}:	СкопироватьОтборЛюбойЛкс(НастройкаКомпоновки.Отбор, НастройкиСписка.Отбор);
{Обработка.ирДинамическийСписок.Форма.ФормаУпр.Форма(702)}:	ирОбщий.ВыделитьПервыеСтрокиДинамическогоСпискаЛкс(ЭлементыФормы.ДинамическийСписок, Количество, НастройкиСписка);
{Обработка.ирДинамическийСписок.Форма.ФормаУпр.Форма(693)}:	ВыделитьНужноеКоличествоНаСервере(Количество);
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/952895

**Comment by tormozit** [comment]
Исправлена в 6.50
