### ISSUE TITLE
Дин. список: куда пропала иконка редактора объекта БД для команды "Изменить"?

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#278]
> Платформа: 8.3.17.1851
> Режим БД: клиент-серверный
> 
> Инструменты разработчика. Версия: Конфигурация 6.49.3
> Инструменты разработчика. Инструмент: Динамический список
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Асинхронность запрещена: Нет
> Инструменты разработчика. Разрешены имитаторы: Да
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-bit Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС Active code page: 866
> Клиент. ОС выполнение BAT: Да
> Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: tcp
> 

Я привык находить эту кнопку по иконке.

**Comment by tormozit** [comment]
Исправлено в 6.50
