### ISSUE TITLE
Автосохранение в консоли HTTP запросов

### ISSUE THREAD

**Issue by Absolemus** [tormozit/RDT1C#279]
При нештатном закрытии 1С предприятия (критическая ошибка, остановка через отладчик, закрытие через диспетчер и т.д.) консоль HTTP запросов не сохраняет свое состояние. Возможно ли сделать по аналогии с консолью кода и консолью запросов, чтобы при открытии консоли HTTP запросов он предлагал восстановить предыдущую сессию.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/919981

**Comment by tormozit** [comment]
Реализовано в 6.50
