### ISSUE TITLE
Орфографические ошибки в подсказках элементов.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#28]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.06.1e
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.06.1e)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: нет

</details>

Две опечатки в подсказках элементов формы

![Typo1](https://user-images.githubusercontent.com/87958986/130413933-d8c4a189-8e04-402b-a7eb-9edce2c85280.png)

![Typo2](https://user-images.githubusercontent.com/87958986/130413943-7c4a460d-3e4e-487b-90e1-8e1b97e5b3db.png)

**Comment by tormozit** [comment]
Исправлено в 6.07.1
