### ISSUE TITLE
Ошибка при вызове "Структура формы" глобального меню

### ISSUE THREAD

**Issue by Absolemus** [tormozit/RDT1C#280]
**Программное окружение**
Платформа: 8.3.18.1779
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия для Казахстана, редакция 3.0 (3.0.43.3)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.50.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.50.1e)
Расширения. fix ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл форму документа
2. Нажал сочетание клавиш ctrl + ё
3. Получил окно глобального меню. Дважды нажал на "Структура формы"
4. Получил ошибку Поле объекта не обнаружено (УсловноеОформление)
Стэктрейс:
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.СтруктураФормы.Форма(1356)}:			ирОбщий.НайтиЭлементУсловногоОформленияПоПолюЛкс(мУсловноеОформлениеФормы.УсловноеОформление, ЭлементФормы.Имя,, СсылающиесяЭлементыОформления);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.СтруктураФормы.Форма(981)}:	ЗаполнитьСтрокуЭлементаУправляемойФормы(СтрокаДочерняяСтрока);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.СтруктураФормы.Форма(875)}:		ДобавитьЗависимуюКоманднуюПанель(КорневаяСтрокаФормы, Форма, НаборыКнопок);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.СтруктураФормы.Форма(476)}:			ДобавитьФорму(Форма);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.СтруктураФормы.Форма(16)}:	ОбновитьДерево();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(32069)}:	ФормаСтруктуры.ОткрытьМодально();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирГлобальный.Модуль(515)}:			ирОбщий.ОткрытьСтруктуруФормыЛкс(ТекущаяФорма);
{(1)}:ОткрытьСтруктуруАктивнойФормыЛкс(ПараметрыОбработчикаОжидания)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10180)}:	Выполнить(ПараметрыОбработчикаОжидания.ИмяМетода + "(ПараметрыОбработчикаОжидания)");
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирГлобальный.Модуль(473)}:	ирОбщий.ОбработчикОжиданияСПараметрамиЛкс();

**Ожидаемое поведение**
Откроется структура формы

**Comment by tormozit** [comment]
Воспроизвести не удалось. Хотелось бы полный текст модуля формы документа.
Если есть возможность, передай мне конфигурацию базы.
Если нет такой возможности, то найди в модуле формы инструмента строку
`мУсловноеОформлениеФормы = ирОбщий.УправляемаяФормаБСП_ВыполнитьНаСервереЛкс(Форма, "ирОбщий.УправляемаяФормаБСП_УсловноеОформлениеЛкс")`
Установи в ней точку останова. Попробуй прошагать ее выполнение и понять почему она возвращает НЕ ожидаемое НастройкиКомпоновкиДанных и какое значение она возвращает.

**Comment by Absolemus** [comment]
Все отрабатывает как и должно. 
Единственная проблема в БСП ПодключаемыеКоманды.ВыполнитьКоманду

Строка ОбщегоНазначения.ВыполнитьМетодКонфигурации(Обработчик, ПараметрыЭкспортнойПроцедуры); все делает как надо
А следующая строка 
ПараметрыВызова.Результат = Результат;
Возвращает дичь, структуру которая изначально была инициализирована

Я не могу отправить свою конфигурацию. Это бухгалтерия для РК. Я подниму типовую, проверю, если не будет работать смогу отправить типовую. Или на чистой БСП попробую
БСП версии 3.1.2.306

**Comment by Absolemus** [comment]
БСП демо база 3.1.2.306, ошибка воспроизводится. Если надо отправить дистрибутив, скажи куда

**Comment by tormozit** [comment]
Проверил на демобазе БСП 3.1. Не воспроизводится и в файловой и в клиент-серверной версии на платформе 8.3.18-22. 
Опиши подробнее в какой форме ты вызываешь команду. Лучше покажи на картинке.
Еще будет полезно увидеть картинки из отладчика, чтобы я понял какие свойства у структуры в переменной "Результат".

**Comment by Absolemus** [comment]
![image](https://user-images.githubusercontent.com/20809734/199640352-198818ce-1538-4786-a55b-934a91156050.png)
![image](https://user-images.githubusercontent.com/20809734/199640577-2324fce8-9a5e-4789-88f8-7b53eaf74657.png)

У переменной результат свойства заданные при инициализации структуры

**Comment by Absolemus** [comment]
В этой же демо базе заказ покупателя работает как задумывалось

![image](https://user-images.githubusercontent.com/20809734/199640930-17f95430-ea93-4a88-b383-2a2149aae947.png)

**Comment by tormozit** [comment]
Пробуй такой код

```
Функция УправляемаяФормаБСП_ВыполнитьНаСервереЛкс(Знач Форма, Знач Обработчик, ПараметрКоманды = Неопределено) Экспорт 
	
	Если Истина
		И ирКэш.НомерВерсииБСПЛкс() > 200
		И (Ложь
			Или ирОбщий.МетодРеализованЛкс(Форма, "Подключаемый_ВыполнитьКомандуНаСервере") 
			Или ирОбщий.МетодРеализованЛкс(Форма, "Подключаемый_ПродолжитьВыполнениеКомандыНаСервере"))
	Тогда
		Попытка
			ТаблицаКомандБСП = ПолучитьИзВременногоХранилища(Форма.ПараметрыПодключаемыхКоманд.АдресТаблицыКоманд);
		Исключение
			ОписаниеОшибки = ОписаниеОшибки(); // Для отладки
			Возврат Неопределено;
		КонецПопытки;
		ИмяКомандыВФорме = ирОбщий.ПоследнийФрагментЛкс(Обработчик);
		ПараметрыВызова = Новый Структура;
		ПараметрыВызова.Вставить("ИмяКомандыВФорме", ИмяКомандыВФорме);
		ПараметрыВызова.Вставить("ПараметрКоманды", ПараметрКоманды);
		ПараметрыВызова.Вставить("Результат", Неопределено);
		#Если Сервер И Не Сервер Тогда
			ТаблицаКомандБСП = Новый ТаблицаЗначений;
			ирОбщий.УсловноеОформлениеУправляемойФормыЛкс();
		#КонецЕсли
		Если ТаблицаКомандБСП.Найти(ИмяКомандыВФорме, "ИмяВФорме") = Неопределено Тогда
			ОписаниеКоманды = ТаблицаКомандБСП.Добавить();
			ОписаниеКоманды.ИмяВФорме = ИмяКомандыВФорме;
			ОписаниеКоманды.Обработчик = Обработчик;
			АдресТаблицыКомандБСП = ПоместитьВоВременноеХранилище(ТаблицаКомандБСП, Форма.УникальныйИдентификатор);
			Форма.ПараметрыПодключаемыхКоманд.АдресТаблицыКоманд = АдресТаблицыКомандБСП;
		КонецЕсли; 
		Если ирОбщий.МетодРеализованЛкс(Форма, "Подключаемый_ВыполнитьКомандуНаСервере") Тогда 
			Форма.Подключаемый_ВыполнитьКомандуНаСервере(ПараметрыВызова, );
		ИначеЕсли ирОбщий.МетодРеализованЛкс(Форма, "Подключаемый_ПродолжитьВыполнениеКомандыНаСервере") Тогда 
			Форма.Подключаемый_ПродолжитьВыполнениеКомандыНаСервере(ПараметрыВызова, );
		КонецЕсли; 
		РезультатВызова = ПараметрыВызова.Результат.Текст;
	КонецЕсли; 
	Возврат РезультатВызова;

КонецФункции

Функция УправляемаяФормаБСП_УсловноеОформлениеЛкс(ПараметрКоманды, Контекст) Экспорт 
	НастройкиКомпоновки = Новый НастройкиКомпоновкиДанных;
	ирОбщий.СкопироватьЭлементыКомпоновкиЛкс(НастройкиКомпоновки.УсловноеОформление, Контекст.Форма.УсловноеОформление);
	Контекст.Результат.Текст = НастройкиКомпоновки; 
КонецФункции
```

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/953307

**Comment by Absolemus** [comment]
Работает
![image](https://user-images.githubusercontent.com/20809734/199673844-6ddd47a4-b7c6-42bc-868d-30ef496f266f.png)

**Comment by tormozit** [comment]
Исправлено в 6.51
