### ISSUE TITLE
При загрузке настроек в консоли компоновки данных структура не загружается в виде дереа

### ISSUE THREAD

**Issue by GladilovDmitry** [tormozit/RDT1C#281]
**Программное окружение**

Платформа: 8.3.20.1914
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP. Управление холдингом (3.1.8.24)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.50.1e
Инструменты разработчика. Инструмент: Консоль компоновок данных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ВсеФункции ()
Расширения. ИнструментыРазработчикаTormozit (6.50.1e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Microsoft Windows 10 Enterprise 64-разрядная Русский
Клиент. ОС от имени администратора: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Microsoft Windows Server 2016 Datacenter 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: http

**Воспроизведение проблемы**
1. Открыл инструмент Консоль компоновок
2. Нажал кнопку Схема (редактировать схему). Загрузил схему из файла. Нажал ОК. Вернулся в главное окно консоли компоновки. Нажал "загрузить настройки из файла". Загрузил.
3. Получил настройки не в виде дерева, а в плоском виде.
4. При нажатии "Сформировать" получил окно с ошибкой "Поле объекта не обнаружено "Структура""

**Ожидаемое поведение**

При загрузке настройки из файла, структура сразу заполняется в виде дерева.

**Дополнительные материалы**

![изображение](https://user-images.githubusercontent.com/49302260/200287971-8ce843f0-89bd-467c-99ba-ade970bae946.png)
![изображение](https://user-images.githubusercontent.com/49302260/200288002-be088410-05e3-4af2-a36f-41ee5e69d408.png)

Способ обхода: щелкнуть в поле настроек - произойдет перестройка настроек в древовидную структуру.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/953458

**Comment by tormozit** [comment]
Текст ошибки желательно добавить в описание.

**Comment by tormozit** [comment]
Исправлено в 6.52.1
