### ISSUE TITLE
Проблема со стандартным периодом в консоли компоновок данных

### ISSUE THREAD

**Issue by Absolemus** [tormozit/RDT1C#282]
**Программное окружение**

Платформа: 8.3.22.1603
Режим БД: файловый
Конфигурация. Название: Тестовая база (1.0.1.1)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.51.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.51.1e)
Расширения. YAXUNIT (22.10.0)
Пользователь. Защита от опасных действий: Да
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 11 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Да
Клиент. ОС выполнение BAT: Да

**Воспроизведение проблемы**
1. Открыл инструмент консоль компоновки данных
2. Создал запрос, в параметрах СКД добавл параметр с Типом "Стандартный период", а так же 2 параметра "Дата начала" и "Дата окончания" с типом Дата. Для параметорв с типом дата установил выражение "&СтандартныйПериод.ДатаНачала" и дата окончания соответсвенно.
3. Примел все изменения и снова попал в консоль компоновки данных
4. Дважды нажал на ранее созданный набор данных (запрос), открылось окно "Консоль запросов", в параметрах 3 элемента (СтандартныйПериод, ДатаНачала, ДатаОкончания)
![image](https://user-images.githubusercontent.com/20809734/200372495-9c679e57-ea69-4878-9a43-8519e41b47ef.png)
5. При изменении стандартного периода, не устанавливаются значения в поля "ДатаНачала" и "ДатаОкончания"
6. Если консоль запросов открылась, и в параметрах есть предустановленные значения "ДатаНачала" и "ДатаОкончания", то после выполнения запроса поля очищаются.

**Ожидаемое поведение**
При изменении стандартного периода устанавливаются значения в поля "ДатаНачала" и "ДатаОкончания"
После выполнения запроса поля "ДатаНачала" и "ДатаОкончания" не очищаются

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/953469

**Comment by tormozit** [comment]
исправлено в 6.51.2
