### ISSUE TITLE
Ошибка выполнения: Ожидается идентификатор при установке флажков в таб. выбранные поля консоли компоновки данных

### ISSUE THREAD

**Issue by dillayla-dvs** [tormozit/RDT1C#283]
**Программное окружение**
Платформа: 8.3.20.2076
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия МФГ (1.5.7.5)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Версия БСП: 203
Инструменты разработчика. Версия: Портативный 6.50.1p
Инструменты разработчика. Инструмент: Консоль компоновок данных
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

**Воспроизведение проблемы**
1. Консоль компоновки данных 
2. Создаем/загружаем схему в которой есть заполненные значения выводимых полей
3. В консоли компоновки переходим на закладку "Выбранные поля"
4. Пытаемся установить или снять все флажки с выбранных полей путем нажатия на кнопку Установить флажки выделенных или всех строк
5. Получаем окно с ошибкой
{<Неизвестный модуль>(1,10)}: Ожидается идентификатор
ЭтаФорма.<<?>>(ТабличноеПоле, ОформлениеСтроки, ДанныеСтроки)
{<Неизвестный модуль>(1,11)}: Неопознанный оператор
ЭтаФорма.(<<?>>ТабличноеПоле, ОформлениеСтроки, ДанныеСтроки)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/953615

**Comment by tormozit** [comment]
Исправлено в 6.52.1
