### ISSUE TITLE
Конструктор запроса ИР. Поддержка новых функций

### ISSUE THREAD

**Issue by Morkhe** [tormozit/RDT1C#284]
**Программное окружение**

Платформа: 8.3.20.1789
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.7.394)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Версия БСП: 301
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Active code page: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Ввел текст запроса 
```
ВЫБРАТЬ
	ДЛИНАСТРОКИ("123") КАК Поле2,
	ЛЕВ("123", 1) КАК Поле3,
	ПРАВ("123", 2) КАК Поле4,
	ВРЕГ("врег") КАК Поле5,
	НРЕГ("НРЕГ") КАК Поле6,
	СОКРЛ(" СокрЛ ") КАК Поле8,
	СОКРП(" СокрП ") КАК Поле9,
	СОКРЛП(" СокрЛП ") КАК Поле10,
	СТРНАЙТИ("12345", "3") КАК Поле11,
	СТРЗАМЕНИТЬ("12345", "1", "0") КАК Поле12,
	SQRT(4) КАК Поле13,
	ОКР(15.7888, 2) КАК Поле15,
	ЦЕЛ(15.7888) КАК Поле16
```
4. Нажал кнопку Конструктор ИР
5. Получил окно с ошибкой `"Не найден терминал """ + Ключ + """ языка запросов 1C"`
6. Ввел текст запроса
` ВЫБРАТЬ POW(2, 3) КАК Поле14 `

7. Нажал кнопку Конструктор ИР
8. Получил сообщение об ошибке `Синтаксическая ошибка ",", ожидается: <)>`

**Ожидаемое поведение**
Конструктор запроса ИР поддерживает новые функции языка запросов:
https://wonderland.v8.1c.ru/blog/novye-funktsii-yazyka-zaprosov-i-sistemy-komponovki-dannykh/?sphrase_id=356719

P.s. вроде не все новые функции перечислил

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/953647

**Comment by tormozit** [comment]
Исправлено в 6.52.1
