### ISSUE TITLE
Консоль кода из редактора объекта

### ISSUE THREAD

**Issue by Morkhe** [tormozit/RDT1C#285]
Добавить возможность передачи текущего объекта или набора записей в консоль кода для дальнейшей обработки.
Что-нибудь вроде
```
ДокументОбъект = АвансовыйОтчет0000_000001От01_01_200100_00_00.ПолучитьОбъект();
или
НаборЗаписей = РегистрыНакопления.ДенежныеСредстваУПодотчетныхЛиц.СоздатьНаборЗаписей();
НаборЗаписей.Отбор.Регистратор.Установить(АвансовыйОтчет0000_000001От01_01_200100_00_00);
НаборЗаписей.Прочитать();
```
Для меня это будет более удобным вариантом, чем передача в подбор и обработку объектов БД с произвольным алгоритмом

**Comment by tormozit** [comment]
Используй команду "Исследовать". Из открывшегося исследователя сможешь уже передать объект в консоль кода.

**Comment by Morkhe** [comment]
В случае набора записей передается таблица значений. В принципе можно через имитатор получить набор, но о такой возможности надо помнить =)
`НаборЗаписей = _Значение_.Методы.ОбъектБд();`
