### ISSUE TITLE
Ошибка в команде вызова формы отчета "Анализ прав доступа"

### ISSUE THREAD

**Issue by Fatman78** [tormozit/RDT1C#286]
**Программное окружение**
Платформа: 8.3.20.2039
Режим БД: клиент-серверный
Конфигурация. Название: Управление нашей фирмой, редакция 3.0 (3.0.1.202)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.51.3e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.51.3e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
3. при попытке открыть форму отчета "ирАнализПравДоступа" Получил окно с ошибкой:

Неизвестный идентификатор формы
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(40928)}:Результат = Менеджер.ПолучитьФорму(ИмяФормы, Владелец, Уникальность);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(43958)}:Форма = ПолучитьФормуЛкс(ПолноеИмяФормы, Параметры, Владелец, Уникальность, Окно);
{ИнструментыРазработчикаTormozit Отчет.ирАнализПравДоступа.Команда.Команда1.МодульКоманды(4)}:ирОбщий.ОткрытьФормуЛкс("Отчет.ирАнализПравДоступа.Форма");

по причине:
Неизвестный идентификатор формы

**Ожидаемое поведение**
Форма должна открываться

Проблема в полном имени формы отчета ирОбщий.ОткрытьФормуЛкс("Отчет.ирАнализПравДоступа.Форма");

Не хватает ".ФормаОтчета". Полное имя формы "Отчет.ирАнализПравДоступа.Форма.ФормаОтчета"

**Comment by tormozit** [comment]
При открытии первой в сеансе формы из подсистемы выводилось сообщение?

**Comment by Fatman78** [comment]
> При открытии первой в сеансе формы из подсистемы выводилось сообщение?
Если ты об этом, то я его не вижу. 
```bsl
СообщитьЛкс("Для использования отчетов подсистемы запустите обычное приложение либо в свойствах конфигурации установите флажок ""Использовать обычные формы в управляемом приложении""
| доступный в режиме ""Сервис""/""Параметры""/""Редактирование конфигурации для режимов запуска""=""Управляемое приложение и обычное приложение"".");
```
![image](https://user-images.githubusercontent.com/79182295/201467062-071443e1-1759-49ad-9ba5-f7441eceff24.png)

Проблема находится в другой плоскости... 

Посмотрел более детально исходный код ИР, протестировал с разными вариантами запуска, смог воспроизвести эту ошибку в неинформативном виде.  Я из сеанса тонкого клиента в меню ИР просто выбираю пункт открыть отчет ИР "Анализ прав доступа (ИР)", на предложение запустить сеанс толстого клиента соглашаюсь и сразу при запуске ловлю эту ошибку про "Неизвестный идентификатор формы" (скриншот выше) с предложением перезапустить сеанс или завершить.  До появления окна приложения в режиме толстого клиента дело даже не доходит и сообщение про "Использовать обычные формы в управляемом приложении" я не вижу.

Мне создать новый Issue с предложением к доработке? Например подавлять попытку открытия отчетов ИР при старте толстого клиента, вместо этого желательно выводить какое-нибудь предупреждение.

**Comment by tormozit** [comment]
> До появления окна приложения в режиме толстого клиента дело даже не доходит и сообщение про "Использовать обычные формы в управляемом приложении" я не вижу

Эту ошибку воспроизвел https://www.hostedredmine.com/issues/953670

**Comment by tormozit** [comment]
Исправлено в 6.52.1
