### ISSUE TITLE
Консоль кода: режим "Фоновый асинх" блокирует клиент

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#287]
**Программное окружение**

> Платформа: 8.3.17.1851
> Режим БД: клиент-серверный
> Конфигурация. Название: СССР 2.0
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_9
> Конфигурация. Версия БСП: 203
> Конфигурация. Использовать обычные формы в управляемом приложении: Да
> Инструменты разработчика. Версия: Конфигурация 6.52.1
> Инструменты разработчика. Инструмент: Консоль кода
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Асинхронность запрещена: Нет
> Инструменты разработчика. Разрешены имитаторы: Да
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-bit Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС Active code page: 866
> Клиент. ОС выполнение BAT: Да
> Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл консоль кода.
2. Выполнил там следующий код в режиме "Фоновый асинх":
```
а = 1;
Пока а < 10000000 Цикл
	а = а + 1;
КонецЦикла
```

3. Клиент "подвесился" на секунд 20, а я ожидал что он не будет блокироваться.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/953985

**Comment by tormozit** [comment]
Исправлено в 6.53
