### ISSUE TITLE
Редактор изменений на узлах: съезжает последняя колонка (флажок отсуствия в БД) у регистров со строковым измернием большой длины

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#288]
**Программное окружение**

Платформа: 8.3.15.1700
Режим БД: файловый
Конфигурация. Название: Управление торговлей, редакция 11 (11.4.7.150)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Версия БСП: 300
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.52.1e
Инструменты разработчика. Инструмент: Редактор изменений на узлах
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.52.1e)
Пользователь. Защита от опасных действий: Да
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru

**Воспроизведение проблемы**
1. Взять типовую УТ 11, там в регистре штрихкодов Строка(200).
2. Полагаю из-за этого последняя колонка с флажком не влезает в таблицу - появляется горизонтальный скролл:
![image](https://user-images.githubusercontent.com/75837433/201946727-82a17737-760d-47ff-aa8d-51caca2f3b7a.png)
3. Хочу чтоб влезала. Со ссылочными измерениями это же как-то достигается - они вроде бы всегда пропорционально ужимаются и скролла у таких регистров нет.

**Comment by tormozit** [comment]
Из существующих способов лучший - открыть менеджер табличного поля и уже в нем выполнить команду "Сжать колонки". Могу добавить такую кнопку прямо в командную панель. 
Делать сокращение ширины колонок всегда - пока кажется не очень хорошей идеей.

![изображение](https://user-images.githubusercontent.com/11896251/201972571-9c34b7d2-38ab-497c-8873-2c524a2bee05.png)

**Comment by john-doe-1c** [comment]
Это помогает лишь до перевыбора таблицы регистрации.
Ширина строковой колонки табличного поля там выставляется в 200 - почему бы ее всегда не сделать максимум 100? В каком сценарии лицезрения этой колонки это будет вредить?

**Comment by tormozit** [comment]
Согласен. Создал задачу https://www.hostedredmine.com/issues/954006

**Comment by tormozit** [comment]
Реализовано в 6.53
