### ISSUE TITLE
Запуск ИР толстого клиента из тонкого клиента.

### ISSUE THREAD

**Issue by Kebzaby** [tormozit/RDT1C#289]
**Программное окружение**

Платформа: 8.3.21.1622
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.309)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.51.3e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. EF_00_00448079 ()
Расширения. EF_00_00447398 ()
Расширения. EF_00_00444678 ()
Расширения. EF_00_00446154 ()
Расширения. EF_00_00445149 ()
Расширения. EF_00_00440473 ()
Расширения. EF_00_00426724 ()
Расширения. EF_00_00442239_7 ()
Расширения. EF_00_00431953 ()
Расширения. EF_00_00439231 ()
Расширения. ...
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows Server 2019 Datacenter 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Была платформа 8.3.18.1433. Стала 8.3.21.1607(1622 тоже проверил). Доменная аутентификация Win AD.
В тонком клиенте, вызываю какой либо инструмент ИР, который просит запустить клиент потолще.
В старом релизе без проблем запускался толстый клиент под текущим пользователем. В новом релизе не может запуститься, просит ввести пароль пользователя, типовым методом 1С, авторизация при запуске.
1.1 Проверялось на разных конфигурациях (ДО, CRM- самописный,...) На разных версиях ИР (встроенные в конфу и в виде расширения). Поведение везде как в п.1
2. В "Редакторе пользователей" - проблем нет, все запускается под любым пользователем.

**Ожидаемое поведение**
Ожидалось старое поведение, запуск под текущим пользователем, без запроса пароля.

**Comment by tormozit** [comment]
Нужны снимок формы запуска сеанса и командная строка запущенного из нее процесса.

**Comment by Kebzaby** [comment]
![image](https://user-images.githubusercontent.com/118299315/202013768-01024782-0f66-4666-941a-c96a95f8afa7.png)
Как получить командную строку?

**Comment by Kebzaby** [comment]
"C:\Program Files\1cv8\8.3.21.1622\bin\1cv8.exe"  ENTERPRISE /IBConnectionString"Srvr=""ЫЫ"";Ref=""АА"";" /RunModeManagedApplication /Debug /UC"" /N"LOGIN" /C"ОткрытьФормуИР.Обработка.ирКонсольКода.Форма" /DEBUGGERURL"tcp://10.112.5.28:1560"   /DEBUG -tcp /TechnicalSpecialistMode /UseHwLicenses- /Lru /VLru

**Comment by tormozit** [comment]
Убери флажок "Текущий пользователь". Тогда сработает аутентификация ОС.

**Comment by tormozit** [comment]
Я проверил в файловом режиме указанные тобой версии платформы и много других (8.3.16, 8.3.18, 8.3.21, 8.3.22). На всех версиях  у меня одинаковое поведение - если в командной строке процесса указан непустой параметр "N", то Windows аутентификация отключается. Этот параметр передается при включенном флажке "Текущий пользователь".

**Comment by Kebzaby** [comment]
Проверил. Все именно так. Спасибо!
