### ISSUE TITLE
Не найден файл внешней компоненты. "О подсистеме."->"Информация для технической поддержки"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#29]
https://user-images.githubusercontent.com/87958986/130414466-b427d8d8-1b50-4908-8e10-bfc67daf34ea.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.06.1e
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.06.1e)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: нет

</details>

При вызове команды "О подсистеме."->"Информация для технической поддержки" появляется сообщение:

```
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКэш.Модуль(435)}: Ошибка при вызове метода контекста (НоваяВКОбщаяЛкс): Не найден файл внешней компоненты

Ошибка обращения к процессу ОС рабочего процесса: Процесс ОС с отбором () не найден
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКэш.Модуль(435)}: Ошибка при вызове метода контекста (НоваяВКОбщаяЛкс): Не найден файл внешней компоненты
```
Видимо это она:
https://www.hostedredmine.com/issues/889213

Исправление в 5.90 в моем случае не помогло. Ошибка плавает и дальше.

**Comment by tormozit** [comment]
Да. Это плавающая ошибка платформы, к которой я пока не подобрал достаточно универсальное противодействие.
Когда она у тебя снова возникнет, попробуй в методе ирКэш.ВКОбщаяЛкс переключить вариант кода
```bsl
	//ВК = ирОбщий.НоваяВКОбщаяЛкс(Секунда(ТекущаяДата()));
	ВК = ирОбщий.НоваяВКОбщаяЛкс();
```

**Comment by PerlAmutor** [comment]
> ```bsl
> ВК = ирОбщий.НоваяВКОбщаяЛкс(Секунда(ТекущаяДата()));
> ```

Не помогло.

**Comment by tormozit** [comment]
При наблюдении ошибки прошагай выполнение НоваяВКОбщаяЛкс() и СоздатьВКОбщая() и запиши видео.

**Comment by PerlAmutor** [comment]
https://user-images.githubusercontent.com/87958986/130620968-25bbfe15-568f-4d8d-ac11-66c4a01fa585.mp4


https://user-images.githubusercontent.com/87958986/130621258-1fd606bf-2ca9-4e06-a3e6-6bec5fba5c62.mp4

**Comment by tormozit** [comment]
Попробую еще один способ https://www.hostedredmine.com/issues/932389

**Comment by tormozit** [comment]
Пробуй новый вариант кода в 6.07.1

**Comment by PerlAmutor** [comment]
С версией 6.07.1 пока проблем не наблюдается.

**Comment by tormozit** [comment]
6.18.2 Сегодня снова поймал эту ошибку https://www.hostedredmine.com/issues/937706
