### ISSUE TITLE
Не передается параметр запроса Консоль HTTP сервисов

### ISSUE THREAD

**Issue by Absolemus** [tormozit/RDT1C#290]
**Программное окружение**

Платформа: 8.3.21.1302
Режим БД: клиент-серверный
Конфигурация. Название: Администрирование ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_18
Инструменты разработчика. Версия: Расширение 6.51.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.51.1e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
В консоли HTTP запросов устанавливаю параметр запроса
![image](https://user-images.githubusercontent.com/20809734/202147949-00771ee8-ca98-4741-aa54-e1bd42c607c0.png)

В отладке
![image](https://user-images.githubusercontent.com/20809734/202148151-87130802-669b-4761-9725-e8c7c7c04c3e.png)

В консоли устанавливаю параметр напрямую в адрес
![image](https://user-images.githubusercontent.com/20809734/202148665-34128904-dfdf-4148-ab9c-8f48ad3a7098.png)

В отладке
![image](https://user-images.githubusercontent.com/20809734/202148745-029bff0b-e6a8-4136-8b4a-c4ca0cdaa5ca.png)

**Ожидаемое поведение**
При установке параметра во вкладке "Параметры запроса" параметр запроса передается в сервис

**Comment by tormozit** [comment]
На твоей первой картинке есть синяя надпись, в которой все объясняется.

**Comment by tormozit** [comment]
Сделай полноразмерный снимок формы без списка запросов. Покажи, где в коде ты вычисляешь выражения.
Почитай флажок "Использовать для всех методов".

**Comment by Absolemus** [comment]
При установке флажка все работает как ожидалось. Спасибо
