### ISSUE TITLE
Долгое открытие формы "ИзменитьДобавитьСтроку" из "ирПодборИОбработкаОбъектов"

### ISSUE THREAD

**Issue by baybas** [tormozit/RDT1C#291]
**Программное **окружение****
Платформа: 8.3.20.1710
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия для Беларуси, редакция 1.6 (1.6.16.15)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: АвтоматическийИУправляемый
Конфигурация. Режим совместимости: Версия8_3_5
Инструменты разработчика. Версия: Конфигурация 6.51.3
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Пользователь. Защита от опасных действий: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Сервер. Процесс: 32б
Сервер. Отладка: tcp

**Ожидаемое поведение**
Какая реакция программы ожидалась?

Хочу изменить записи регистра Хозрасчетный.
Вызываю обработку "ирПодборИОбработкаОбъектов", накладываю отборы, как мне нужно, нажимаю "Заполнить строки", всё успешно отрабатывает, есть строки для обработки, иду на закладку "Обработки", делаю выбор на строке "Изменить/добавить строку" и Предприятие виснет.

Отладкой определил, что виснет на строке 
ОбщийМодуль.ирОбщий.Модуль : 16542 : Таблица = Запрос.Выполнить().Выгрузить();'

там предварительно генерится запрос такого вида
"ВЫБРАТЬ Т.* ИЗ РегистрБухгалтерии.Хозрасчетный.ДвиженияССубконто КАК Т ГДЕ ИСТИНА И Регистратор = &Регистратор И Т.НомерСтроки = &НомерСтроки"
а для регистра бухгалтерии это смерти подобно

переделал, чтобы условие передавалось в параметры виртуальной таблицы - всё работает отлично.
ВЫБРАТЬ Т.* ИЗ РегистрБухгалтерии.Хозрасчетный.ДвиженияССубконто(,,Регистратор = &Регистратор) КАК Т ГДЕ ИСТИНА  И Т.НомерСтроки = &НомерСтроки

Моё костыльное решение вот такое:
// ОбщийМодуль.ирОбщий.Модуль
Функция СтрокаТаблицыБДПоКлючуЛкс(ПолноеИмяТаблицы, СтруктураКлюча) Экспорт 
	
	Запрос = Новый Запрос;
	//Хвисюк+	
	Если СтрНайти(ПолноеИмяТаблицы, "ДвиженияССубконто") > 0 Тогда
		ТекстУсловиеЗапроса = "ИСТИНА";
		Для Каждого КлючИЗначение Из СтруктураКлюча Цикл
			ТекстУсловиеЗапроса = ТекстУсловиеЗапроса + " И " + КлючИЗначение.Ключ + " = &" + КлючИЗначение.Ключ;
		КонецЦикла;
		ТекстЗапроса = "ВЫБРАТЬ Т.* ИЗ " + ПолноеИмяТаблицы + "(,, " + ТекстУсловиеЗапроса  + ") КАК Т ГДЕ ИСТИНА ";		
	Иначе
		ТекстЗапроса = "ВЫБРАТЬ Т.* ИЗ " + ПолноеИмяТаблицы + " КАК Т ГДЕ ИСТИНА ";
		Для Каждого КлючИЗначение Из СтруктураКлюча Цикл
			ТекстЗапроса = ТекстЗапроса + " И Т." + КлючИЗначение.Ключ + " = &" + КлючИЗначение.Ключ;
		КонецЦикла;	
	КонецЕсли;
	//Хвисюк-
	СкопироватьУниверсальнуюКоллекциюЛкс(СтруктураКлюча, Запрос.Параметры);
	Запрос.Текст = ТекстЗапроса;
	Таблица = Запрос.Выполнить().Выгрузить();
	Если Таблица.Количество() > 1 Тогда
		ВызватьИсключение "По переданному ключу (" + ПредставлениеСтруктурыЛкс(СтруктураКлюча) + ") найдено несколько строк таблицы";
	ИначеЕсли Таблица.Количество() > 0 Тогда
		СтрокаРезультата = Таблица[0];
	Иначе
		СтрокаРезультата = Неопределено;
	КонецЕсли; 
	Возврат СтрокаРезультата;
	
КонецФункци

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/954153

**Comment by tormozit** [comment]
Исправлено в 6.53
