### ISSUE TITLE
Поиск дублей и замена ссылок: различные значения колонки для ссылающихся объектов

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#292]
Поиск дублей и замена ссылок: в нижней таблице вкладки "Правила замены" хочу команду "Различные значения колонки" для колонки "Тип объекта", чтобы одним взглядом оценивать в каких справочниках / документах и т.д. и сколько раз встречаются неправильные (заменяемые) объекты.

**Comment by tormozit** [comment]
Эту команду можно вызывать в любой таблице инструментов через глобальное меню (CTRL+ё)

**Comment by john-doe-1c** [comment]
Точно. Но думаю я в следующий раз все равно забуду об этом и стану искать заветную иконку на КП.
В ИР тобой выбран курс на неразмещение в КП команд из глобального меню?

**Comment by tormozit** [comment]
Из-за большого количества кнопок в инструментах сильно выросла сложность освоения инструментов. Чтобы хоть как то сократить количество кнопок в командных панелях, я рассматриваю вариант удаления (как минимум не добавления) тех кнопок, которые одновременно не часто нажимаются, не играют важной роли и доступны через глобальное меню.

**Comment by tormozit** [comment]
Но в данном случае я добавлю эту кнопку в командную панель, т.к. она вероятно уже полезнее чем имеющаяся там "Отобрать по типам". https://www.hostedredmine.com/issues/954198

**Comment by tormozit** [comment]
Реализовано в 6.53
