### ISSUE TITLE
Вставка текста в значение с типом в редакторе массивов не приводит к ожидаемым результатам

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#293]
**Программное окружение**

Платформа: 8.3.18.1483
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.53.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ПатчДоставка ()
Расширения. ПатчИнтеркампаниДублиПередачТоваров ()
Расширения. ПатчРаспределениеУдержаний ()
Расширения. Патч_ЗаказКлиента_Стадия_НаСогласовании ()
Расширения. Патч_ПересортицаТоваров_ОбработкаПроведения ()
Расширения. Патч_СвободныеОстатки ()
Расширения. Патч_221024 ()
Расширения. ИмяКомпании(1.1.1.0)
Расширения. зг_ЗУП (1.0.1.7)
Расширения. ФормыПотомВКод ()
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Microsoft Windows Server 2008 R2 Enterprise  64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл редактор массива в консоли кода
![изображение](https://user-images.githubusercontent.com/16429518/203704888-ad85511d-7815-46ad-b5ce-c24d6a3426b4.png)
2. Добавил строку 
![изображение](https://user-images.githubusercontent.com/16429518/203704924-1bdc56c1-bbf0-4ef1-b7e0-e1ecc20d62be.png)
3. Выбрал тип значения
![изображение](https://user-images.githubusercontent.com/16429518/203705000-7a829c0b-fc64-45ab-80bd-2d39e8f0ebd6.png)
4. Вставил значение в эту строку
5. И вот тут начинается ошибка:
![изображение](https://user-images.githubusercontent.com/16429518/203705195-0b06bfe9-9183-4328-859c-320a50749ced.png)
6. Выбрал нет
7. Получил две строки, одна из которых совершенно мне не нужна
![изображение](https://user-images.githubusercontent.com/16429518/203705350-ecca89dd-4cc1-499b-9cbb-c614d729f492.png)

**Ожидаемое поведение**
Отсутствие вставки новой строки при вставке значения в выбранный элемент.

**Comment by tormozit** [comment]
Добавь описание шага копирования значения в буфер обмена и покажи содержимое внутреннего буфера обмена перед вставкой путем открытия глобального меню и активации в нем строки "Вставить значение".

**Comment by KovAlexey** [comment]
Немного по другому отвечу, но думаю тебе как раз это и нужно.

Изначально копировал склад (и если я его сразу вставляю - все ок, как раз проверил)

Но в ИР я уже брал значения из Clipdiary, которое хранит историю буфера обмена
![изображение](https://user-images.githubusercontent.com/16429518/203707586-ae5ee71d-87c7-4552-9f93-eedacbabf6e0.png)
Там оно уже становится строкой

**Comment by tormozit** [comment]
Прошу все таки сделать именно то, что я попросил.
И попробуй сделать вставку сочетанием клавиш CTRL+V без использование программ, отправляющих вставку.

**Comment by KovAlexey** [comment]
Ну со вставкой значения все работает. Вставляется склад.

Хорошо, подскажи как это меню открыть. Я им не пользуюсь и сходу не разобрался
А открытие из списка инструментов приводит к такому
![изображение](https://user-images.githubusercontent.com/16429518/203708744-1e2e1c0a-f864-4f34-ab3c-14e609c90c76.png)

**Comment by tormozit** [comment]
Глобальное меню https://infostart.ru/1c/articles/1273456/

**Comment by KovAlexey** [comment]
И вставка через глобальное меню
И вставка через Ctrl+V приводит к правильному результату
![изображение](https://user-images.githubusercontent.com/16429518/203710397-3abdcacd-e1e3-4d76-9661-6071c6d5bfde.png)

**Comment by tormozit** [comment]
Я уже не знаю как донести, но ты так и не сделал что я просил тут https://github.com/tormozit/RDT1C/issues/293#issuecomment-1325997760

**Comment by KovAlexey** [comment]
![изображение](https://user-images.githubusercontent.com/16429518/203711007-c5e93814-91ea-4216-800d-2d293f8970f8.png)

![изображение](https://user-images.githubusercontent.com/16429518/203711260-f41c639d-c8d0-48bf-aebc-4409d41975a8.png)

Но проблема то не со вставкой значения. Проблема с тем, что при вставке наименования в значение ячейки создается новая строка, хотя ожидается типовое поведение с выбором по наименованию

**Comment by tormozit** [comment]
Тут описано как работает перехват вставки из буфера обмена https://www.hostedredmine.com/issues/952307
Ключевой момент - полное сохранение оригинальной функциональности вставки в режиме редактирования текста поля.
Поэтому в твоем случае скорее всего табличное поле выходит из режима редактирования. А в таком случае стандартная вставка не может сработать и поэтому срабатывает моя.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/954757
На твоей последней картинке кстати показано такое содержимое внутреннего буфера, при котором проблема не наблюдается. Поэтому сначала мне не удалось воспроизвести. Похоже ты по-другому копировал в буфер в исходном случае.

**Comment by tormozit** [comment]
Исправлено в 6.54
