### ISSUE TITLE
Ошибка в консоли запросов, открытой командой Открыть объект для отладки

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#294]
**Программное окружение**

Платформа: 8.3.22.1704
Режим БД: файловый
Конфигурация. Название: Управление нашей фирмой, редакция 3.0 (3.0.1.230)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 6.53.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.53.1e)
Пользователь. Защита от опасных действий: Да
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

УНФ понятностью типовая.
Есть две ошибки.

**Воспроизведение проблемы**
1. Поставил точку останова для отладки запроса в процедуре СформироватьТаблицаЗапасыРазборка в модуле менеджера документа на строке 891
![изображение](https://user-images.githubusercontent.com/12731230/204247296-b9ae1dc4-5907-4e95-84c3-6180b20b682a.png)
2. Открыл документ Комплектация запасов e1cib/data/Документ.КомплектацияЗапасов?ref=b0f41413333d97ea11ed6f00f15f938b и нажал на кнопку провести
3. Остановил на точке останова, вычислил выражение и применил функцию ирОбщий.ОтЛкс(Запрос)
4. Нажал F5, сеанс под отладкой отвис
5. В толстом клиенте открыл команду Открыть объект для отладки, открылась Консоль запросов.
6. В таблице Пакет нажать на первую строку на колонку Имя - ВЗЗапасыОстатки.
Первая ошибка:
7.  Получил ошибку - К сожалению возникла непредвиденная ситуация.
![изображение](https://user-images.githubusercontent.com/12731230/204268586-8e3258bf-9053-40a4-81d1-5ac14dab05a4.png)
Текст ошибки:  
Ошибка при вызове метода контекста (ВыполнитьПакет)
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(3094)}:Результат = мОбъектЗапроса.ВыполнитьПакет();
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(9922)}:мРезультатЗапроса = ВыполнитьЗапросИсточникаДанных("SELECT * FROM " + ИмяСозданнойВременнойТаблицы)[0];
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(9861)}:ЗагрузитьВременнуюТаблицуРезультатаПакета();

по причине:
{(1, 15)}: Таблица не найдена "ВЗЗапасыОстатки"
SELECT * FROM <<?>>ВЗЗапасыОстатки

8. Открыл закладку Временные таблицы, и нажал на строку - ВЗЗапасыОстатки.
![изображение](https://user-images.githubusercontent.com/12731230/204268859-d0d0641f-45f1-4147-b6fe-5b3bf2e9c384.png)

Вторая ошибка.
9. Появилось сообщение:
Текст запроса: Строка кода 1: {(1,14)}: Таблица не найдена "ВЗЗапасыОстатки"
ВЫБРАТЬ * ИЗ <<?>>ВЗЗапасыОстатки

**Ожидаемое поведение**
Ожидал, что выведется таблица, соответствующая временной таблице.

Файл, сохраненный в каталоге для отладки:

[_28_11_202212_43_40ОтладитьСтруктура.zip](https://github.com/tormozit/RDT1C/files/10103298/_28_11_202212_43_40.zip)

**Comment by antonsm2011** [comment]
dt-шник отправил в личку в телеграмм.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955038

**Comment by tormozit** [comment]
Исправлено в 6.54
