### ISSUE TITLE
Сравнение объектов Документов/Справочников/ПлановВидовХарактеристик двух идентичных конфигураций

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#295]
Столкнулся сегодня с ситуацией. Подрядчик внес доработку в конфигурацию, которая позволила всем пользователям изменять документы в закрытом периоде. Сформировались задания к расчету себестоимости. По ним я выгрузил набор ссылок. Но вот понять что конкретно меняли сложно, есть развернутый бэкап на утро. Т.е. 2 базы идентичные, метаданные не менялись.
Хотелось бы видеть в ИР инструмент позволяющий сделать следующее:
1. Выгружаем по набору ссылок через "Выгрузка / Загрузка данных через файл" объекты с движениями в .zip файл.
2. Открываем ИР во второй базе, там выбираем сохраненный файл.
3. ИР распаковывает объекты из файла и по полученным ссылкам выбирает данные из текущей базы.
4. Затем происходит сравнение:
    а) Реквизитов,
    б) Строк Табличных частей,
    в) Движений регистров
5. Выводятся расхождения в отчет, либо на форму.

Суть этого действия в том, чтобы оценить масштаб бедствия, а также увидеть и отсеять изменения пользователей, которые могут потеряться при переносе объектов из бэкапа в рабочую базу.

**Comment by tormozit** [comment]
Уже делал такое в рамках другого продукта на 1С и представляю масштабы (60ч+) и вызовы этой задачи 
1. Очень быстро ты захочешь игнорировать ряд реквизитов типа АвтоИзменения, ДатаИзменения.
2. С твоими аппетитами быстро кончится память, т.к. почти все прочитанные (различающиеся) объекты нужно будет хранить в ней.
3. Дальше ты пожалуешься что работает очень медленно и что нужно продолжение загрузки с места последней остановки (например по ошибке чтения объекта из БД).

Кроме того документы при проведении могут менять и независимые регистры, а для них еще будет масса проблем с визуализацией. 

Из существующих функций можно попробовать выгрузку ключевых регистров (например регистра бухгалтерии) с отбором по списку регистраторов инструментом "Сравнение таблиц" в двух этапном режиме, который позволяет обрабатывать значительный объем данных с неплохой скоростью.

**Comment by PerlAmutor** [comment]
Меня больше всего волнуют три регистра: ПрочиеРасходы, ПрочиеРасходыНезавершенногоПроизводства и СебестоимостьТоваров. Хозрасчетный по стольку по скольку, т.к. в большинстве случаев опирается на перечисленные три.
То что есть независимые регистры я знаю, там и СтатусыДокументов и РеестрДокументов, но они на учет не сильно оказывают влияние. Вот остаточные регистры да.
Результаты  сравнения по идее можно выгружать на диск для экономии памяти и подгружать по мере необходимости когда потребуется увидеть изменения по конкретному объекту. Мне по больше части не нужно в реальном времени это все видеть при изменении строки. Настраивать сравниваемые поля, табличные части или регистры было бы несомненным плюсом.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/956027
Там же есть ссылка на существующий аналог. Попробуй его. Возможно у тебя появятся еще пожелания к этой функции.

**Comment by PerlAmutor** [comment]
Оставлю тут ссылку с сайта разработчика где можно бесплатно скачать, чтобы не забыть
http://moolex.ru/loads.php?file=Updates/MO/MovingObjects.epf
