### ISSUE TITLE
Консоль кода. Строка неограниченной длины не принимает флаг в параметре

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#296]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.49.1p
Инструменты разработчика. Инструмент: Консоль кода
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1.  Пишу код с возвращаемыми параметрами:
```
Тип1 = Новый ОписаниеТипов("Строка");
Тип2 = Новый ОписаниеТипов("Строка", , , , Новый КвалификаторыСтроки(0));

```
2. Анализирую результат:
![image](https://user-images.githubusercontent.com/87958986/205140744-c8e8c4a1-4f43-4625-b2e7-2babf1840637.png)

И вижу, что у строки неограниченной длинны флаг отсутствует, хотя по логике быть должен.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955217

**Comment by tormozit** [comment]
Исправлено в 6.55
