### ISSUE TITLE
Менеджер табличного поля. Поле не найдено "Подразделение"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#297]
https://user-images.githubusercontent.com/87958986/205505273-a8c9740b-7931-4cab-b1a1-d94dc7346c49.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Менеджер табличного поля
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл "Редактор объекта БД"
2. Выбрал документ с движениями.
3. Выбрал регистр накопления.
4. Вызвал "Менеджер табличного поля"
5. Задал отбор по полю "Подразделение"
6. Вызвал команду "Применить"
7. В "Редакторе объекта БД" переключился на Регистр Бухгалтерии
8. Вернулся в "Менеджер табличного поля"
9. Вызвал команду "Применить"
10. Получил ошибку:

```
Ошибка при вызове метода контекста (Выполнить)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(22405)}:		МакетКомпоновки = КомпоновщикМакета.Выполнить(СхемаКомпоновки, НастройкаКомпоновки, ДанныеРасшифровки, СвойМакетОформления, ТипГенератора, ПроверятьДоступностьПолей);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(22296)}:	МакетКомпоновки = СобратьМакетКомпоновкиЛкс(СхемаКомпоновки, НастройкаКомпоновки, ВнешниеНаборыДанных, ОтключитьОбщиеИтоги, РежимОтладки, ПроверятьДоступностьПолей, ВыбратьВсеДоступныеПоля);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(22323)}:	СкомпоноватьВКоллекциюЗначенийПоСхемеЛкс(СхемаКомпоновки, НастройкаКомпоновки, ТаблицаОтобранное, НаборыДанных,,,,, РежимОтладки,,,, Истина);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(27033)}:		ТаблицаОтобранное = ОтобратьТаблицуЗначенийКомпоновкойЛкс(ТаблицаЗначений, Компоновщик.Настройки, РежимОтладки,, ТаблицаБезДанныхСУзкимиТипами);
{ВнешняяОбработка.ирПлатформа.Форма.МенеджерТабличногоПоля.Форма(1154)}:	ирОбщий.ТабличноеПолеСОтборомПросмотраОтобратьЛкс(ВладелецФормы, СвязанноеТабличноеПоле,,, Истина);
по причине:
Ошибка компоновки макета
по причине:
Поле не найдено "Подразделение"

```
**Ожидаемое поведение**
Не учитывать настроенные отборы для отсутствующих полей в новой таблице, либо отключать их автоматически.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955340

**Comment by tormozit** [comment]
Исправлено в 6.55
