### ISSUE TITLE
Функция отладки От() и РезультатЗапроса. Ошибка ИР.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#298]
https://user-images.githubusercontent.com/87958986/205505636-006a0aff-7d19-44cb-8a64-c7ce54d265c4.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Включил отладку. Остановился в конфигураторе. Вызвал Shift+F9. Вызвал функцию От() для сохранения снимка с объектом типа РезультатЗапроса
2. Скопировал возвращенную строку, вернулся в ИР, вызвал инструмент отложенной отладки сохраненного объекта.
3. Получил ошибку:

```
Ошибка при вызове метода контекста (ОткрытьФайл)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(22710)}:				ЧтениеXML.ОткрытьФайл(СсылкаИлиИмяФайла);
{(1)}:ирОбщий.ОтладитьОтложенныйОбъектЛкс()
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(150)}:		Выполнить(СтрокаИнструмента.ПолноеИмя + "()");
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(143)}:	ОткрытьИнструмент(СтрокаИнструмента);
по причине:
Неправильный путь к файлу 'C:\Users\user123\Downloads\6.54.1p\ОбъектыДляОтладки\File__F__SABROG_1C_erp24554_demo__\_04_12_202220_19_22Исследовать_____0f725605_ea6e_420c_8968_a82dbfcd51cd__0_1_8182374e_7600_47bf_974e_05f8e0432420____T__2_15__S___ID___S___Date_Time___S___Number___S___Fld11849___S___Fld105087___S___Fld11846___S___Fld11847___S___Fld11857___S___Fld106262___S___Fld11859___S___Fld11858___S___Fld11851___S___Fld45635___S___Marked___S___Posted___R__503_92f10050568b35ac11e4ecd21ff77d60__D__636287184000000__S___ТД00_000002___R__47_a7a9000d884fd00d11e4c18026093579__L__0__R__230_b3360011955cba6b11df722051ed67a3__R__477_848a00112f43529a11d955bd14ed8ba6__R__410_b33a0011955cba6b11df7ab14d9d0772__R__1410_8c8d0688fd890a1d46ef94e1507f3953__R__295_b3380011955cba6b11df730aa4212b3d__S______N__38000__R__43628_b0b876741c05be134746734f09600afb__L__0__L__1___0_0_0_0_0_1_0__15_15___Ссылка_____25___Pattern_______9115b259_5081_43b5_bf68_c82d941bc44c____L____0_0_0__0_0__0_0_1_0____Период_____19___Pattern____D_____L____0_0_0__0_0__0_1_1_0____Номер_____11___Pattern____S__11_0____L____0_0_0__0_0__0_2_1_0____Валюта_____25___Pattern_______3a87ef2a_9de1_4d34_9e5f_3c8cdf53b3ab____L____0_0_0__0_0__0_3_1_0____Мультивалютный_____2___Pattern____B_____L____0_0_0__0_0__0_4_1_0____Организация_____25___Pattern_______55adb97e_a84e_453e_8020_7665bb2abdef____L____0_0_0__0_0__0_5_1_0____ПодотчетноеЛицо_____25___Pattern____L________cedad008_72f7_4948_9729_1d52bc8841e6___0_1_0__0_0__0_6_1_0____Подразделение_____25___Pattern_______56c86461_d1a1_4757_ac34_d36ef2ecf333____L____0_0_0__0_0__0_7_1_0____ЗакупкаПодДеятельность_____25___Pattern____L________d18f8feb_b37e_47f1_a2d4_8f34f5510b3b___0_0_0__0_0__0_8_1_0____Автор_____25___Pattern_______604931cd_d4a8_48d0_bc59_2ac90e044abb____L____0_0_0__0_0__0_9_1_0____Комментарий_____32___Pattern____S_____L____0_0_0__0_0__0_10_1_0____СуммаИзрасходовано_____15___Pattern____L_____N__15_2_1___0_0_0__0_0__0_11_1_0____Статус_____25___Pattern_______450973de_9959_4a52_88fa_0a6d6ab5df57____L____0_0_0__0_0__0_12_1_0____ПометкаУдаления_____2___Pattern____B_____L____0_0_0__0_0__0_13_1_0____Проведен_____2___Pattern____B_____L____0_0_0__0_0__0_14_1_0___0_1_0_0__1_0_0_0_0_0_0_0_0_0_00000000_0000_0000_0000_000000000000__.deb'
```

**Ожидаемое поведение**
Понятно, что объект РезультатЗапроса не описан как допустимый объект отладки, но тем не менее проверки на типы нигде не производятся.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955338
Дополню описание функции От*() https://www.hostedredmine.com/issues/955339

**Comment by tormozit** [comment]
1. Исправлено в 6.55

**Comment by tormozit** [comment]
2. Реализовано в 6.55
