### ISSUE TITLE
Редактор объекта БД. Не обновляется состояние команды включения/выключение Итогов в подвале

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#299]
https://user-images.githubusercontent.com/87958986/205506595-51e4a998-1915-4ea4-9163-7d2c1cc9f20d.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

При работе с Движениями в "Редакторе Объектов БД" не обновляется состояние кнопки включения/выключения Итогов в подвале таблиц формы. Например если включить итоги в одном регистре, то при переключении на другой - команда будет показывать включенное состояние показа итогов, но чтобы их включить, потребуется сначала их отключать, а затем включать (делать 2 действия вместо 1)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955365

**Comment by tormozit** [comment]
Исправлено в 6.55
