### ISSUE TITLE
Консоль запросов. Копирование текста в виде кода, странное поведение.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#30]
https://user-images.githubusercontent.com/87958986/130417151-2fe04580-a8b3-4400-80d0-7240cae9ebca.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.06.2e
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.06.2e)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Да
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: нет

</details>

При вызове команды " \ Панель \ Текст запроса(1) \ Командная панель \ Копировать в виде кода" наблюдается странное поведение. Окно результата открывается не с первого вызова.

**Comment by tormozit** [comment]
Окно "Текст" открывается только в том случае, если не удалось поместить текст в буфер обмена. Такое происходит из-за использования невидимого HTML документа для помещения в буфер обмена, в котором иногда что то ломается.  Тогда пользователю предлагается это сделать вручную. Согласен, что такое поведение выглядит странно, но вроде бы описание команды достаточно четко обозначает ее действие.
