### ISSUE TITLE
Редактор объекта БД. Редактирование движений.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#300]
При работе с движениями в "Редакторе объекта БД" хотелось бы как-то выделять (цветом, иконкой или шрифтом) поля по которым считаются итоги (измерения):

![image](https://user-images.githubusercontent.com/87958986/205507586-3e243fb9-dfa1-4f5e-8ab1-b740a7c7c2ff.png)

Аналогично и в "Редакторе строки":

![image](https://user-images.githubusercontent.com/87958986/205507774-f1763311-9019-4738-9edb-0dea8f9e8b5f.png)

**Comment by tormozit** [comment]
Создал задачи
https://www.hostedredmine.com/issues/956123
https://www.hostedredmine.com/issues/956127
https://www.hostedredmine.com/issues/956126

**Comment by tormozit** [comment]
Реализовано в 6.57
