### ISSUE TITLE
Редактор объекта БД. При выводе движений в ТаблицуЗначений все колонки типа "Строка(0)"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#301]
https://user-images.githubusercontent.com/87958986/205508200-ec93743f-fb67-4ed0-a259-ca0f579218be.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

При выводе движений в Таблицу Значений из "Редактора Объекта БД" - все колонки принимают тип "Строка(0)"

**Comment by PerlAmutor** [comment]
Разобрался. Надо без оформления выводить.

**Comment by tormozit** [comment]
Доработаю подсказку флажка "Без оформления":

Выводить только данные строк табличного поля без оригинального оформления **(с типами значений)**. Дает больше настроек. Колонки с пустым свойством "Данные" игнорируются.

**Comment by tormozit** [comment]
Подсказку доработал в 6.55
