### ISSUE TITLE
Глобальный модуль и работа с разными расширениями\доработками.

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#302]
**Программное окружение**

Платформа: 8.3.21.1622
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.44.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ПатчИМ ()
Расширения. ПатчДоставка ()
Расширения. ПатчИнтеркампаниДублиПередачТоваров ()
Расширения. Патч_ОтложенноеПроведение ()
Расширения. Патч_КонтрольОтрицательныхОстатков ()
Расширения. ПатчРаспределениеУдержаний ()
Расширения. Патч_СвободныеОстатки ()
Расширения. ИмяКомпании (1.1.1.0)
Расширения. зг_ЗУП (1.0.1.7)
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**

1. Подключил расширение для тестов с функцией "Наблюдать" в общих модулях (не глобальная)
2. Получил ошибку, что такая функция уже существует (глобальная)

**Ожидаемое поведение**

Хотелось бы, чтоб глобальные функции имели префикс, которые гарантирует, что такие вполне используемые слова, как "Наблюдать" не пересекались с ними.
Или же чтоб глобальных функций не было вовсе.

**Comment by tormozit** [comment]
В модуле ирГлобальный несколько глобальных клиентских методов с короткими именами без префиксов. Их можно найти по строке "#Если Клиент Тогда". К ним уже все привыкли, хотя конкретно метод Наблюдать() не описан в документации и потому его редко применяют. Чтобы менять имена этих методов, нужна веская причина. В твоем случае выбор стоит между широко и давно используемым расширением с одной стороны и неуказанным расширением с другой стороны. В такой ситуации для большинства пользователей будет правильнее править неуказанное расширение, т.е. переименовать метод в нем.

**Comment by KovAlexey** [comment]
https://github.com/bia-technologies/yaxunit
Это расширение я использую.

Так что правильнее будет все же просто закомментить\переимовать этот метод в ИР. Потому что он ни к чему не привязан и спокойно может быть выброшен (Поскольку есть нормальный вызов ИрОбщий.Наблюдать() и это лишь обертка), в отличии от таких методов в данном расширении

Ну, отклонено так отклонено. Буду комментить

**Comment by tormozit** [comment]
Указанное тобой расширение существует всего пол года. ИР существует 15 лет, а функция Наблюдать() - 12 лет. Поэтому кажется правильнее править в указанном тобой расширении. К тому же не вижу в нем твоей заявки на правку. Завтра автор этого расширения придумает добавить себе метод Поп/Оп/Опс/ОперироватьСтруктурой - и я должен буду всех переучивать на новые глобальные имена?
Так что тут скорее стоит вопрос о доступности всех глобальных функций ИР сразу. Пока я не готов ее убирать, но при достаточном количестве конфликтов пересмотрю свое решение.

**Comment by KovAlexey** [comment]
> К тому же не вижу в нем твоей заявки на правку. 

И ее не будет. Поскольку модуль не является глобальным.
Был бы глобальным - заявка бы появилась там естественно.
В целом глобальные переменные, глобальные методы считаю "злом" и плохим проектированием, когда в них нет прям необходимости.

В остальном, конечно, согласен - разумные доводы.
Ну, мне не сложно закомментить глобальные функции. Я итак управление доступом в каждой версии подгоняю под роли ИР для полных прав. Буду еще и это делать

**Comment by tormozit** [comment]
Я по заявкам в ИР уже сделал десятки переименований НЕглобальных методов по причине конфликта с чужими глобальными методами. Думаю другие тоже могут такое пережить разок то.

**Comment by tormozit** [comment]
Конфликт имен устранен в 6.91 https://www.hostedredmine.com/issues/968833
