### ISSUE TITLE
Подбор и обработка объектов БД. Метод объекта не обнаружен (ЭтоНовый)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#303]
https://user-images.githubusercontent.com/87958986/206553227-51358a7a-1b65-41e2-b6a4-88d67c337d47.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Выбрал ссылки в Динамическом Списке ИР и передал их в Подбор и обработку объектов БД
2. Выбрал настройку "Обход данных"->"Ключи объектов", чтобы не Получать Данные, а обрабатывать ссылки
3. Выбрал "Произвольный алгоритм". Нажал "Выполнить"
4. Получил сообщения об ошибках:

```
Обработка объекта DocumentRef.АвансовыйОтчет(a813faa2-f578-11e4-92f1-0050568b35ac)
	{ВнешняяОбработка.ирПодборИОбработкаОбъектов.МодульОбъекта(747)}: Метод объекта не обнаружен (ЭтоНовый)
Обработка объекта DocumentRef.АвансовыйОтчет(a5a20561-ec3c-11e6-a22c-bcaec56cc144)
	{ВнешняяОбработка.ирПодборИОбработкаОбъектов.МодульОбъекта(747)}: Метод объекта не обнаружен (ЭтоНовый)
Обработка объекта DocumentRef.АвансовыйОтчет(a5a20563-ec3c-11e6-a22c-bcaec56cc144)
	{ВнешняяОбработка.ирПодборИОбработкаОбъектов.МодульОбъекта(747)}: Метод объекта не обнаружен (ЭтоНовый)
Обработка объекта DocumentRef.АвансовыйОтчет(98b611b6-f97b-11e4-92f1-0050568b35ac)
	{ВнешняяОбработка.ирПодборИОбработкаОбъектов.МодульОбъекта(747)}: Метод объекта не обнаружен (ЭтоНовый)
Обработка объекта DocumentRef.АвансовыйОтчет(1ff77d60-ecd2-11e4-92f1-0050568b35ac)
	{ВнешняяОбработка.ирПодборИОбработкаОбъектов.МодульОбъекта(747)}: Метод объекта не обнаружен (ЭтоНовый)
Обработка объекта DocumentRef.АвансовыйОтчет(91f310ae-ecd0-11e4-92f1-0050568b35ac)
	{ВнешняяОбработка.ирПодборИОбработкаОбъектов.МодульОбъекта(747)}: Метод объекта не обнаружен (ЭтоНовый)
*Строк обработано - 6, неуспешно - 6, успешно - 0. Объектов обработано - 6, записано автоматически - 0.
*Обработка 1 потоков завершено за 0:00:00 (0 сек), обработано 6 элементов.

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955456

**Comment by tormozit** [comment]
Исправлено в 6.55
