### ISSUE TITLE
Различные значения колонки. Индекс находится за границами массива

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#304]
https://user-images.githubusercontent.com/87958986/206558443-abf22793-adad-4954-8fad-c0d894789525.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Различные значения колонки
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыть любую таблицу где доступна команда "Различные значения колонки"
2. Выбрать поле таблицы. Вызвать "Различные значения колонки"
3. Выбрать несколько значений (поставить флажки). Применить группировку.
4. Выбрать другое группируемое поле в таблице. Снова вызвать "Различные значения колонки". Выбрать любое значение. Применить.
5. Встать на поле по которому группировали в пункте 2 (изначально). Вызвать "Различные значения колонки".
6. Снять любой флажок оставив, остальные. Применить группировку.
7. Получим сообщение об ошибке:

```
Индекс находится за границами массива
{ВнешняяОбработка.ирРазличныеЗначенияКолонки.Форма.Форма.Форма(826)}:			СтрокаРасширенногоЗначения = ЗначенияРасширенные[Значения.Индекс(ЭлементСписка)];
{ВнешняяОбработка.ирОбщий.МодульОбъекта(41772)}:	РезультатФормы = Форма.ОткрытьМодально();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(42315)}:				ОткрытьРазличныеЗначенияКолонкиЛкс(ИсточникДействий,,, ЭтаФорма);
{ВнешняяОбработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(772)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);

```

**Comment by tormozit** [comment]
Почему ты отбор называешь группировкой?

**Comment by PerlAmutor** [comment]
> Почему ты отбор называешь группировкой?

Согласен, что некорректный термин. Я подразумеваю под этим термином сделанный отбор по сгруппированным уникальным значениям в списке инструмента "Различные значения колонок". По сути GROUP BY это и есть "Различные значения" )

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955589

**Comment by tormozit** [comment]
Исправлено в 6.55
