### ISSUE TITLE
Динамический список ИР. Таблица БД с именем "" не найдена

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#305]
https://user-images.githubusercontent.com/87958986/206566135-e347e130-f397-42f1-835f-edd9b86fb6a6.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Динамический список
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Динамически список ИР.
2. Выбрал таблицу
3. Встал на поле с именем таблицы и очистил её вручную
4. Получил ошибку:

```
Таблица БД с именем "" не найдена
{ВнешняяОбработка.ирОбщий.МодульОбъекта(14789)}:		ВызватьИсключение "Таблица БД с именем """ + ПолноеИмяТаблицыБД + """ не найдена";
{ВнешняяОбработка.ирОбщий.МодульОбъекта(13966)}:	ТекстЗапроса = ПолучитьТекстЗапросаПолейТаблицыБДЛкс(ПолноеИмяТаблицыБД, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(13775)}:	ТаблицаРезультата = ПустаяТаблицаЗначенийИзТаблицыБДЛкс(ПолноеИмяТаблицыБД, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирКэш.МодульОбъекта(72)}:	Результат = ирОбщий.ПоляТаблицыБДЛкс(ПолноеИмяТаблицыБД, _ВызыватьИсключениеПриОтсутствииПрав, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(322)}:	ПоляТаблицыБД = ирКэш.ПоляТаблицыБДЛкс(ПолноеИмяТаблицы);

```

**Comment by tormozit** [comment]
исправлено в 6.55
