### ISSUE TITLE
Менеджер табличного поля и сравнение строк. Индекс находится за границами массива

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#306]
https://user-images.githubusercontent.com/87958986/206567452-692c999e-3ba7-4a9c-a0b9-badbf9a2a8b6.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Менеджер табличного поля
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Динамический список ИР.
2. Не выбирая таблицу вызвать "Менеджер табличного поля"
3. В Менеджере табличного поля вызвать команду "Прочее"-> "Сравнить строки" (первая в списке)
4. Далее везде соглашаться и жать "ОК"
5. Получим ошибку:

```
Индекс находится за границами массива
{ВнешняяОбработка.ирСравнениеТаблиц.МодульОбъекта(131)}:		Если ирОбщий.ОбъектВСтрокуXMLЛкс(Таблица2[0][Колонка.Имя],,, Ложь) = Неопределено Тогда
{ВнешняяОбработка.ирСравнениеТаблиц.Форма.Форма.Форма(442)}:	ОбновитьСопоставлениеКолонок();
{ВнешняяОбработка.ирСравнениеТаблиц.Форма.Форма.Форма(1168)}:	ОбновитьСопоставлениеКолонокВФорме(ЗаполнитьСопоставлениеКолонок);
{ВнешняяОбработка.ирСравнениеТаблиц.Форма.Форма.Форма(45)}:	ПриИзмененииРежимаСравнения();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(28067)}:		ЭтаФорма.ЗагрузитьНастройкуВФорме(НастройкаФормы, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(28044)}:	ЗагрузитьНастройкуФормыЧерезОбработчикЛкс(ЭтаФорма, НастройкаФормы, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(28022)}:			ЗагрузитьНастройкуФормыПоУмолчаниюЛкс(ЭтаФорма, Истина, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирСравнениеТаблиц.Форма.Форма.Форма(413)}:	ирОбщий.СоздатьМенеджерСохраненияНастроекФормыЛкс(ЭтаФорма,,,, "ctb");
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10429)}:		ФормаСравнителя.Открыть();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10405)}:		СравнитьТаблицыИнтерактивноЛкс(Значение1, Значение2, Модально);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10647)}:		Сравнить2ЗначенияВФормеЛкс(СравниваемыйДокумент1, СравниваемыйДокумент2,,,,, ТекущееСвойство,,, ВариантСинтаксиса, ЗаголовокЭлементаФормы);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10578)}:	ДобавитьОбъектВБуферИПредложитьСравнениеЛкс(СравниваемыйДокумент, ЭтаФорма,, ЗаголовокЭлементаФормы, ВариантСинтаксиса);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(42330)}:				ЗапомнитьСодержимоеЭлементаФормыДляСравненияЛкс(ЭтаФорма, ИсточникДействий);
{ВнешняяОбработка.ирПлатформа.Форма.МенеджерТабличногоПоля.Форма(901)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка, СвязанноеТабличноеПоле);
```

**Comment by tormozit** [comment]
Ошибку воспроизвел и исправил в 6.59 в рамках https://www.hostedredmine.com/issues/956621
