### ISSUE TITLE
Динамический список. Добавить. Получение структуры ключа таблицы БД "" не поддерживается

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#307]
https://user-images.githubusercontent.com/87958986/206568895-4cae6667-8493-417b-abbd-091766ca819f.mp4

**Программное окружение**

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Динамический список
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Динамический список ИР
2. Не выбирая таблицы вызвал команду " \ Командная панель \ Подменю редактора \ Добавить"
3. Получил сообщение об ошибке:

```
Получение структуры ключа таблицы БД "" не поддерживается
{ВнешняяОбработка.ирОбщий.МодульОбъекта(16141)}:		ВызватьИсключение "Получение структуры ключа таблицы БД """ + ПолноеИмяТаблицыБД + """ не поддерживается";
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(804)}:		КлючОбъекта = ирОбщий.СтруктураКлючаТаблицыБДЛкс(фОбъект.ПолноеИмяТаблицы, Ложь);


```

**Comment by tormozit** [comment]
Это конечно ошибка, но исправлять я ее не буду из-за высоких затрат и крайне низкой вероятности возникновения.
