### ISSUE TITLE
Различные значения колонки. Фильтр по подстроке находит другие данные

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#308]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Различные значения колонки
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыть большую таблицу в которой содержится поле с ссылочным значением, например справочник ФизическиеЛица
2. Выбрать поле по которому есть большое количество различных ссылочных значений
3. Условия выше необходимы, чтобы ИР начал вызов "Получение представлений для ссылочных значений"
4. Вызвать команду "Различные значения колонки"
5. В строке статуса внизу должно появится сообщение "Получение представлений для ссылочных значений" (или как-то так)
6. В открывшейся форме должно стать видимым поле "Поля поиска" (галочка должна быть отключена!)
7. Вводим в фильтр искомую подстроку (можно пробовать вводить просто числа).
8. В качестве результатов поиска должны начать выдаваться значения которые даже не искали и не содержат искомого текста

На демо-базах не воспроизводится из-за маленького объема информации в таблицах. На SQL серверных, рабочих, периодически сталкиваюсь с этим (в ERP и ЗУП). Искал как-то сотрудника по имени фамилии и отчеству (копировал из другой формы), а нашелся совсем другой сотрудник, другого пола, с совершенно другим ФИО. Тоже самое было и с подразделениями, у которых в представлениях есть Код подразделения. Находились совсем другие.

**Comment by tormozit** [comment]
Скорее всего это связано с соседней ошибкой https://www.hostedredmine.com/issues/955589

**Comment by PerlAmutor** [comment]
Сомневаюсь. Я отбор ставлю лишь по одной колонке и не отбираю по другим, не снимаю отборы только лишь ищу. Ошибка плавающая, воспроизводится не 100%. Хотя тебе виднее.

**Comment by tormozit** [comment]
Я делаю выводы из предоставленного описания. Теперь ты предоставил дополнительные условия. Согласен. С ними моя гипотеза выглядит маловероятной. 
Но предоставленной информации недостаточно чтобы за разумное время найти причину проблемы. Было бы полезно хотя бы показать картинку.

**Comment by PerlAmutor** [comment]
В общем проверил отладчиком и нашел проблемный участок:

![image](https://user-images.githubusercontent.com/87958986/207079637-e510f057-8b85-4cab-b358-aa9a257377ba.png)

SQL сервер может возвращать результаты запроса в различном порядке. Поэтому при Выгрузке данных и последующей Загрузки в колонку, значения принимают чужие представления.

У себя поправил таким образом:
Взял не используемую колонку "Индекс", в цикле перед выгрузкой пронумеровал строки таблицы значений, потом в запросе отсортировал по полю Индекс в возрастающем порядке.

**Comment by tormozit** [comment]
Какая СУБД?
Если пренебречь поддержкой 8.3.12-, то лучше использовать АВТОНОМЕРЗАПИСИ() для фиксации порядка строк временной таблицы. Мне же придется делать твоим способом.

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/955670

**Comment by PerlAmutor** [comment]
MSSQL. Да, про АВТОНОМЕРЗАПИСИ() думал, но как раз и решил не использовать из-за разных версий платформ в нашем зоопарке. Была еще мысль использовать поле НомерСтроки, которое есть у Таблицы Формы.
Кстати ПРЕДСТАВЛЕНИЕССЫЛКИ() на пустые ссылки возвращает NULL, а не пустую строку. Но скорее всего это не критично в данной реализации.

**Comment by tormozit** [comment]
> Кстати ПРЕДСТАВЛЕНИЕССЫЛКИ() на пустые ссылки возвращает NULL, а не пустую строку

Ты ошибаешься
Запрос "ВЫБРАТЬ ПРЕДСТАВЛЕНИЕССЫЛКИ(ЗНАЧЕНИЕ(Справочник.Банки.ПустаяСсылка))" даст пустую строку.

**Comment by PerlAmutor** [comment]
Вероятно. Я так мог подумать из-за того, что при отладке одно из представлений было NULL, но я не подумал, что это значение могло встать напротив пустой ссылки из-за ошибки с сортировкой. Значит там было какое-то другое значение в оригинале. Но null туда попасть может очень запросто:

![image](https://user-images.githubusercontent.com/87958986/207215763-488803c7-b28d-49d5-b145-8f8e1a984f27.png)

**Comment by tormozit** [comment]
Исправлено в 6.56
