### ISSUE TITLE
Колонки БД. Не показывает количество строк в таблицах.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#309]
https://user-images.githubusercontent.com/87958986/206904733-8d1132f7-ea8e-4130-a467-0f09d1a12b82.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Колонки БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл "Колонки БД"
2. Не устанавливая галочку "Искать значение", вызываю команду "Анализ данных"
3. После сбора статистики колонка "Кол-во строк в таблице" остается пустой (символ "?")

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955637

**Comment by tormozit** [comment]
Исправлено в 6.55
