### ISSUE TITLE
Колонки БД. Не обновляется таблица после очистки отбора по наименованию.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#310]
https://user-images.githubusercontent.com/87958986/206905068-fc1067b0-9b42-4c53-b7fb-cca9ecdb406f.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.54.1p
Инструменты разработчика. Инструмент: Колонки БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыть инструмент "Колонки БД"
2. Установить галочку "Имя/Синоним"
3. Ввести несуществующее имя таблицы (чтобы результат был пустым)
4. Снять галочку "Имя/Синоним"
5. Нажать кнопку очистки (крестик) поля фильтра по наименованию
6. Ввести существующее имя таблицы и оно не найдется... Не обновляется таблица.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955638

**Comment by tormozit** [comment]
Исправлено в 6.55
