### ISSUE TITLE
Различные значения колонки. Ошибка при вызове метода контекста (Сортировать). Недопустимое значение параметра (параметр номер '1')

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#311]
https://user-images.githubusercontent.com/87958986/207372442-fb6c10f5-7aee-4d8d-8706-496e2f907206.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.55.1p
Инструменты разработчика. Инструмент: Различные значения колонки
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
Ошибка воспроизводится только на большом количестве данных. Поэтому предварительно можно на тестовой базе сгенерировать их, например таким образом:

```
ГСЧ = Новый ГенераторСлучайныхЧисел(ТекущаяУниверсальнаяДатаВМиллисекундах());

Для Инд = 0 По 10000-1 Цикл
    Эл = Справочники.ФизическиеЛица.СоздатьЭлемент();
    Эл.Наименование = ГСЧ.СлучайноеЧисло();
    Эл.Записать();
КонецЦикла;
```

1. Открыл инструмент Динамический Список ИР на таблице с большим количеством различных данных в колонке
2. Вызвал "Различные значения колонки"
3. В открывшемся диалоге вызвал команду сортировки
4. Всплыло диалоговое окно с подтверждением "Сортировка в памяти большого числа..."
5. Выбрал вариант "Нет"
6. Получил сообщение об ошибке:

```
Ошибка при вызове метода контекста (Сортировать)
{ВнешняяОбработка.ирРазличныеЗначенияКолонки.Форма.Форма.Форма(1301)}:	ЗначенияРасширенные.Сортировать(ирОбщий.ТабличноеПолеСортироватьЛкс(ЭтаФорма, ЭлементыФормы.Значения, Истина));
{ВнешняяОбработка.ирОбщий.МодульОбъекта(41782)}:	РезультатФормы = Форма.ОткрытьМодально();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(42325)}:				ОткрытьРазличныеЗначенияКолонкиЛкс(ИсточникДействий,,, ЭтаФорма);
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(523)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
по причине:
Недопустимое значение параметра (параметр номер '1')
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955717

**Comment by tormozit** [comment]
Исправлено в 6.56
