### ISSUE TITLE
Консоль кода. Произвольно меняется тип СтандартногоПериода на ВариантСтандартногоПериода.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#312]
https://user-images.githubusercontent.com/87958986/207375135-c13878c3-8f32-477d-8c5b-feb6b20cd1bb.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.55.1p
Инструменты разработчика. Инструмент: Консоль кода
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Консоль кода.
2. Добавил параметр с типом "СтандартныйПериод"
3. Хочу выбрать произвольный период для передачи параметров ДатаНачала и ДатаОкончания в процедуру
4. Но при выборе "Произвольного периода" типа параметра меняется на "ВариантСтандартногоПериода"

**Ожидаемое поведение**
Ожидал такого же поведения как и в Консоли Запроса

![image](https://user-images.githubusercontent.com/87958986/207375797-b5fbe1aa-7110-4062-99cc-012be870f20e.png)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955718

**Comment by tormozit** [comment]
Исправлено в 6.56
