### ISSUE TITLE
Колонки БД. Поиск значения. Падает платформа.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#313]
https://user-images.githubusercontent.com/87958986/207662831-f307665d-f136-4098-a0b7-5d4ac2e65ee1.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.55.1p
Инструменты разработчика. Инструмент: Колонки БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Колонки БД", установил галочку "Искать значение"
2. Выбрал тип данных "Строка"
3. Ввел слово "ФизическиеЛица":
Платформа упала с исключением

**Comment by tormozit** [comment]
Пока не удалось повторить. Похоже на ошибку платформы.
