### ISSUE TITLE
Редактор объекта БД. Связанные колонки. Отображать пустые значения.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#314]
https://user-images.githubusercontent.com/87958986/207669197-fcdabd34-61d8-4fbb-8a93-c60866c06436.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.55.1p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Выбрал ссылку. Перешел на вкладку "Связанные колонки", нашел ссылки.
3. Вызвал команду "Показывать пустые значения" - ничего не происходит.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955752

**Comment by tormozit** [comment]
Исправлено в 6.56
