### ISSUE TITLE
Ошибка при попытке добавить элемент к сравнению из "Исследовать элемент формы"

### ISSUE THREAD

**Issue by Fatman78** [tormozit/RDT1C#315]
**Программное окружение**
Платформа: 8.3.20.1914
Режим БД: файловый
Конфигурация. Название: Демонстрационная конфигурация "Библиотека стандартных подсистем", редакция 3.1 (3.1.7.61)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 6.55.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. _ДемоПустоеРасширение (1.0.1.1)
Расширения. _ДемоРасширение (1.0.1.13)
Расширения. ИнструментыРазработчикаTormozit (6.55.1e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

**Воспроизведение проблемы**
1. Открыл форму объекта, Выбрал поле формы, Нажал Ctrl~ Открыл инструмент Глобальное меню (ИР) - "Исследовать элемент формы" 
2. Нажал кнопку "Заполнить для сравнения неглубокий снимок значения из текущей строки"
3. Получил окно с ошибкой (см. скриншот)
`Свойство недоступно
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(9573)}:ЗаполнитьЗначенияСвойств(СтруктураОбъекта, Объект);
{ИнструментыРазработчикаTormozit Обработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(1411)}:ирОбщий.ДобавитьОбъектВБуферИПредложитьСравнениеЛкс(ирОбщий.СтруктураИзОбъектаЛкс(ОбъектДляСравнения), ЭтаФорма);

по причине:
Ошибка установки значения свойства 'ПутьКДанным'
по причине:
Свойство недоступно`

**Ожидаемое поведение**
Надеялся на лучшее.

![ИР Ошибка 2022-12-17_201005](https://user-images.githubusercontent.com/79182295/208253839-a7eef5e2-4e58-470c-af9f-17a23d880054.jpg)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/955978

**Comment by tormozit** [comment]
Задача на добавление команды сравнения в структуру формы https://www.hostedredmine.com/issues/955979

**Comment by tormozit** [comment]
Исправлено в 6.56
