### ISSUE TITLE
Консоль компоновоки, консоль запросов: Вылет платформы

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#316]
**Программное окружение**
Платформа: 8.3.19.1529
Режим БД: клиент-серверный
Конфигурация. Название: Зарплата и Управление Персоналом для Украины, редакция 2.1 (2.1.63.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_3_9
Инструменты разработчика. Версия: Расширение 6.56.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.56.1e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Корпоративная 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows 10 Корпоративная 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp
Получить эту информацию можно кнопкой "Техническая информация" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1

**Воспроизведение проблемы**
1. Открыл консоль компоновки, набросал отчет
2. В консоли компоновки открыл запрос, открыл структуру запроса, внес изменений
3. Сохранил запрос, нажал принять изменения в консоли запроса в консоль компоновки
4. вылет платформы. 
5. В журнале регистрации завершение аунтификации
6. Непостоянно, но последнее время довольно часто
в дампе:
exception information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
![image](https://user-images.githubusercontent.com/81148850/208419982-05055fa8-1bd3-4784-9442-600ef9bb01d7.png)

**Ожидаемое поведение**
Какая реакция программы ожидалась?

**Comment by tormozit** [comment]
Видно ли окно приложения после вылета или оно сразу исчезает?
Если видно, то нужна картинка. Если исчезает, то может заметил, нарисовалось ли внутри окно конструктора схемы компоновки?
Проблема стабильная? Если сразу после вылета снова повторить точно те же действия, то вылет повторяется?

**Comment by marv-ua** [comment]
Подвисает на несколько секунд и сразу вылетает. 
Повторить не могу, с теми же действиями после перезапуска работает, примерно через час повторяется

**Comment by marv-ua** [comment]
Заметил что чаще всего вылетает после того как накопится большое количество изменений для применения в схему компоновки

**Comment by tormozit** [comment]
Без воспроизведения пока могу предложить переход на другую версию платформы. 
Перед этим лучше проверить повторение проблемы в файловой базе, если есть возможность. После успешного воспроизведения в файловой базе, можно будет в файловой же и пробовать другую версию платформы, т.к. это проще чем в клиент-серверной.

**Comment by marv-ua** [comment]
Буду наблюдать дальше, перейти на другую версию платформы возможности нет.

обновил на 6.57.1

Сейчас дважды попался: 
Набрал запрос в консоли запроса, нажал применить и вылет
зашел по новой, открыл консоль компоновки, провалился в запрос, набрал запрос нажал применить и опять вылет.

**Comment by tormozit** [comment]
Кстати, консоль запросов должна автосохранять текст запроса в этой ситуации, если конечно падение происходит до ее уничтожения, и при следующем _независимом_ открытии консоли предлагать его восстановить. 

Но если падает уже в консоли компоновки, то автосохраненый запрос уже будет удален. Тогда попробуй сохранять запрос в файл явно перед нажатие кнопки "Применить" в консоли.

**Comment by tormozit** [comment]
Кстати твоя версия платформы является тестовой и отменена, т.е. в ней были внесены неопубликованные критические ошибки. Поэтому настоятельно рекомендую перейти на другую версию платформы. Вполне вероятно что и аварийное завершение уйдет.
