### ISSUE TITLE
Снимок объекта для отложенной отладки сделанный в транзакции провоцирует открытие ЖР.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#317]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.56.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

При использовании функции От() на запросе выполняющимся в открытой транзакции создается .deb файл, который при открытии в ИР через "Отладить отложенный объект" принудительно открывает Журнал Регистрации с предложением сделать отбор по изменившимся объектам и вопросом делать это или нет. При этом наблюдается некоторая задержка, кроме того это принуждает пользователя закрыть форму Журнала Регистрации и самостоятельно найти новое открывшееся окно консоли запросов. Когда у тебя уже было открыто штук 10 консолей запросов, то это вызывает проблему. Хотелось бы увидеть возможность отключения такого механизма для объектов сформированных в транзакции, чтобы вернуть прежнее поведение.

**Comment by tormozit** [comment]
Если пользователь нажмет клавишу Escape или кнопку "Закрыть" (крестик) в окне открытого таким образом инструмента "Анализ журнала регистрации", то ему не придется искать окно консоли запросов, т.к. оно автоматически активируется при этом.

**Comment by tormozit** [comment]
Если длительность выполнения операции тебе кажется слишком большой, сделай замер производительности.

**Comment by tormozit** [comment]
Окно "Анализа журнала регистрации" открывается только если в транзакции на момент снимка была выполнена хотя бы одна операция изменения БД. Если транзакция была зафиксирована, то показывать анализ журнала регистрации смысла нет. Однако чтобы это узнать, программе нужно будет делать отбор по журналу регистрации, что может быть долго. Поэтому программа задает вопрос пользователю, чтобы сделать отобрать события из журнала регистрации.

**Comment by tormozit** [comment]
Сейчас тщательно проверил много раз. Достаточно при отображении вопроса один раз нажать клавишу "Escape", чтобы вопрос исчез и сразу активировалось окно нужной консоли запросов. Кажется что тут нет большого неудобства. 
Можешь еще раз проверить у себя?

Платформа: 8.3.22.1750
Режим БД: клиент-серверный
Конфигурация. Название: Комплексная автоматизация, редакция 1.1  (1.1.20.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_13
Конфигурация. Версия БСП: 102
Инструменты разработчика. Версия: Конфигурация 6.57.1
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. НастройкиДинамическогоСпискаTormozit (1.00)
Расширения. Расширение1 ()
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 32б
Сервер. Отладка: http

**Comment by PerlAmutor** [comment]
"Сейчас тщательно проверил много раз. Достаточно при отображении вопроса один раз нажать клавишу "Escape", чтобы вопрос исчез и сразу активировалось окно нужной консоли запросов. Кажется что тут нет большого неудобства.
Можешь еще раз проверить у себя?"

Я пытался через "Escape" делать, но при этом случайно закрывал и открывшуюся консоль запросов, т.к. вопрос появляется не сразу, сначала появляется окно ЖР, которое повисит некоторое время и лишь затем задаст вопрос.

**Comment by tormozit** [comment]
Иными словами тебе просто нужно не торопиться и нажимать клавишу, когда появится вопрос. 
Если все таки считаешь, что это все еще очень неудобно, то запиши видео, т.к. мне твои неудобства кажутся преувеличенными.

**Comment by PerlAmutor** [comment]
Есть еще одно сильное неудобство. Даже если я отказался от отбора по ЖР и закрыл окно, то при последующем открытии ЖР эти отборы восстанавливаются и я сижу и вычищаю отборы.

**Comment by tormozit** [comment]
Не нужно валить в одну кучу разные проблемы, т.к. инструмент "Анализ журнала регистрации" открывается из многих мест с отбором и там по идее будет возникать та же проблема запоминания отборов.
Создай новую заявку и опиши ее там как основную.
