### ISSUE TITLE
Консоль кода: запускать в фоне произвольное кол-во разных алгоритмов

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#318]
Хочу запускать в фоне произвольное кол-во разных алгоритмов.
Запустил один в фоне - переключился после этого в дереве на другой, что-нибудь подредактировал и запустил его тоже.
Пока эти два выполняются, перешел к третьему и что-нибудь начал писать там. Затем переключился на первый и отменил его выполнение. Остальные уже запущенные должны продолжить выполняться.

В общем, чтоб это все в одной консоли кода происходило. Без размножения окон самой консоли.
В дереве все выполняющиеся фоновые помечать иконкой красного квадратика, а после выполнения - каким-нибудь зеленым флажком, чтоб я имел хоть какую-то возможность обратить внимание на факт завершения.

**Comment by tormozit** [comment]
Мой механизм фоновых операций не поддерживает такой сценарий работы. Для его поддержки потребуется большая доработка в основном в интерфейсе пользователя. При этом существенных преимуществ на мой взгляд эта возможность не дает, т.к. обычно пользователь не запускает более 3-х фоновых операций. А для 3-х одновременных операций текущая реализация на мой взгляд вполне достаточна. Да, немного неудобно размножать окна и собирать результаты в одно окно консоли.

Пока я сделаю небольшие улучшения в рамках текущего подхода:
Доступность команды "Новое окно" https://www.hostedredmine.com/issues/956136
Ошибка доступности дерева https://www.hostedredmine.com/issues/956137

**Comment by john-doe-1c** [comment]
А как теперь остановить фоновый алгоритм? Кнопка "Выполнить" с красным квадратом после старта алгоритма теперь недоступна - это так и задумано?

**Comment by tormozit** [comment]
Тут я поленился делать ее доступной, т.к. в окне "Фоновое задание формы" есть флажок "Отменить". 
Но раз ты про это спросил в заявке, то значит тебе это важно. Поэтому считаю это ошибкой https://www.hostedredmine.com/issues/957309

**Comment by john-doe-1c** [comment]
> в окне "Фоновое задание формы" есть флажок "Отменить"

Я это окно почти сразу закрываю, само оно у меня почему-то редко после этого воскресает.
Но если бы у кнопки не появлялся красный квадратик, то я бы за ошибку это вообще и не считал наверное.

**Comment by tormozit** [comment]
Исправлено в 6.62
