### ISSUE TITLE
Редактор остатков. Не очищаются предыдущие настройки

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#319]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.57.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Отладка разрешена: Да
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Редактор остатков, выбрал регистр, вышел из приложения.
2. Обновил релиз конфигурации на тот, где регистр был удален или переименован
3. При повторном открытии Редактора остатков в новом релизе ИР видит, что настройки некорректные и предлагает их сбросить на настройки по умолчанию.
4. Соглашаемся.
5. После этого возникает ошибка, что регистра не существует и инструмент не открывается. И так по кругу. Помогает ручная чистка настроек этого инструмента в хранилище настроек.

**Comment by tormozit** [comment]
Нужно указать точное сообщение или ошибку программы из п.5

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/956278

**Comment by tormozit** [comment]
Исправлено в 6.58
