### ISSUE TITLE
Редактор объекта БД. Не открывается форма выбора перечисления

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#320]
https://user-images.githubusercontent.com/87958986/210570293-4a1f170c-84c2-45b9-945d-c2cb612e14dc.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.58.2p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Отладка разрешена: Да
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыть Редактор объекта БД с документом содержащим реквизит типа ПеречислениеСсылка
2. Выделить реквизит и открыть форму выбора через 3 точки
3. Возникает ошибка:

```
Поле объекта не обнаружено (Ссылка)
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(338)}:			ИдентификаторСсылки = ирОбщий.СтроковыйИдентификаторСсылкиЛкс(ДанныеСтроки[ИмяПоляСсылка]);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/956588

**Comment by tormozit** [comment]
Исправлено в 6.58.3
