### ISSUE TITLE
Редактор изменений на узлах: автоматически (сразу) выделять узлы после выбора определенных планов обмена

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#321]
Для большинства планов, которые я смотрю, там изменений быть вообще не должно (все оттуда выгребается довольно частым РЗ), поэтому после выбора всех узлов флажками проходит меньше секунды времени (для подсчета и показа зарегистрированных объектов). Но каждый раз после выбора такого плана мне приходится вручную отмечать узел / узлы обмена (по одному или кнопкой массовой установки флажка всем / выделенным строкам) .

Делаю я это в целях "ручного мониторинга" накопленной очереди изменений каждый день (иногда но нескольку раз), т.к. долгое нахождение там какого-то объекта - это сигнал к разбору ситуации.

Пожелание: для каждого такого "легкого" плана хочу указывать программе, чтобы она после его выбора сразу отмечала флажками все узлы такого плана (наверное кроме собственного предопределенного, ведь там вроде все равно нельзя ничего регистрировать и поэтому какой вообще смысл в его отметке?), и соответственно чтобы вся статистика выводилась мне на экран без дополнительных действий.

**Comment by tormozit** [comment]
какой вариант поставки инструментов используешь?

**Comment by john-doe-1c** [comment]
Расширение и встраиваемую подсистему. Чаще подсистему.
Хранить имена "особенных" планов обмена в хранилищах настроек (системных / формы) разве нельзя? Вроде это свойство базы / платформы в целом и должно работать независимо от варианта поставки ИР.
Или ты не с этой целью интересуешься?

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/956829
Подумаю

**Comment by tormozit** [comment]
Реализовано в 6.60

**Comment by john-doe-1c** [comment]
Теперь каждый раз при открытии формы приходится целиться мышкой во флажок вычисления кол-ва изменений. Раньше я не отвлекался на работу с этим флажком вообще - как единственный раз в жизни его поставил, так он и работал. Вернешь как было?

**Comment by tormozit** [comment]
Нет. Поведение флажка документировано и значит умышленно. Как я уже писал в чате, это большой и потенциально тяжелый запрос. Поэтому нажатие на флажок один раз в жизни этой долгоживущей формы не кажется большим неудобством. Пореже закрывай эту форму. Или объясни почему ты ее так часто закрываешь.

**Comment by john-doe-1c** [comment]
> это большой и потенциально тяжелый запрос

Который все равно будет выполняться при нажатии мною флажка. Но зачем теперь это делать каждый раз вручную? В каких случаях я могу захотеть открыть редактор, но не нажать этот флажок? По моей оценке такой сценарий может быть раз в год возникает, когда надо что-то неглядя куда-то зарегистрировать, остальные же 364 дня нужно именно смотреть статистику по узлам.

**Comment by tormozit** [comment]
Ты очень узко рассматриваешь применение инструмента, не желая выходить за рамки своих сценариев использования. 
Сделаю условное сохранение включенного флажка https://www.hostedredmine.com/issues/957337

**Comment by john-doe-1c** [comment]
> выходить за рамки своих сценариев использования

Потому и спрашиваю:
> В каких случаях я могу захотеть открыть редактор, но не нажать этот флажок?

**Comment by tormozit** [comment]
> В каких случаях я могу захотеть открыть редактор, но не нажать этот флажок?

Посмотреть состав регистрируемых на узле типов объектов, активировать нужный тип и смотреть изменения только по нему.

**Comment by tormozit** [comment]
Реализовано в 6.62
