### ISSUE TITLE
Ошибка при открытии команды Открыть объект для отладки

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#322]
**Программное окружение**

Платформа: 8.3.22.1704
Режим БД: файловый
Конфигурация. Название: Управление нашей фирмой, редакция 1.6 (1.6.26.185)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 6.59.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. Расширение1 ()
Расширения. Roles (1.0.8.241)
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Отладка разрешена: Нет
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

**Воспроизведение проблемы**
1. Сохранил при отладке запрос функцией ирОбщий.ОтЛкс(Запрос)
2. Пробую открыть команду Открыть объект для отладки, чтобы увидеть сохраненный запрос
3. Получил окно с ошибкой:
Метод объекта не обнаружен (ОтладитьОтложенныйОбъектБезПараметровЛкс)
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Команда.ОткрытьОбъектДляОтладки.МодульКоманды(5)}:ирОбщий.ОтладитьОтложенныйОбъектБезПараметровЛкс();

**Ожидаемое поведение**
Ожидал, что откроется запрос в консоли запроса.

**Comment by tormozit** [comment]
Пока используй аналогичную функцию в режиме обычного приложения

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/956827

**Comment by tormozit** [comment]
Исправлено в 6.59.2
