### ISSUE TITLE
6.59.2e Ошибка запуска толстого клиента и обычного приложения 

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#323]
**Программное окружение**
версия расширение 6.59.2е

**Воспроизведение проблемы**
1. нажал Запустить толстый клиент, получил ошибку
```
Ошибка инициализации модуля: ИнструментыРазработчикаTormozit Обработка.ирПортативный.МодульОбъекта
по причине:
{<Неизвестный модуль>(1,1)}: Переменная не определена (ирКлиент)
по причине:
{<Неизвестный модуль>(1,1)}: Переменная не определена (ирКлиент)
<<?>>ирКлиент
```
![image](https://user-images.githubusercontent.com/81148850/211758317-1d4d4212-b7f8-4a8d-8e6c-97f631c7780d.png)

пробовал 6.57 - работает

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/956851

**Comment by tormozit** [comment]
исправлено в 6.59.3
