### ISSUE TITLE
Редактор объекта БД. Исключение при получении представления объекта

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#324]
![image](https://user-images.githubusercontent.com/87958986/212125831-e6c89bbd-f1d3-4361-bde3-007de0e63e30.png)

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Версия БСП: 204
Инструменты разработчика. Версия: Портативный 6.59.2p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Отладка разрешена: Да
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
В платформе есть как минимум две возможности получения представления:
- представление ссылки
- представление еще не записанного объекта

В одной из редакции БСП допустили ошибку и написали такой код в модуле менеджера справочника ИдентификаторыОбъектовМетаданных (ERP 2.5.8.269):

```

Процедура ОбработкаПолученияПолейПредставления(Поля, СтандартнаяОбработка) Экспорт
	
	СтандартнаяОбработка = Ложь;
	
	Поля.Добавить("Ссылка");
	Поля.Добавить("Наименование");
	Поля.Добавить("ПолноеИмя");
	Поля.Добавить("ПолныйСиноним");
	
КонецПроцедуры

Процедура ОбработкаПолученияПредставления(Данные, Представление, СтандартнаяОбработка) Экспорт
	
	СтандартнаяОбработка = Ложь;
	
#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда
	Представление = СтандартныеПодсистемыПовтИсп.ПредставлениеИдентификатораОбъектаМетаданных(Данные.Ссылка);
#Иначе
	Представление = СтандартныеПодсистемыКлиентПовтИсп.ПредставлениеИдентификатораОбъектаМетаданных(Данные.Ссылка);
#КонецЕсли
	
КонецПроцедуры

Функция ПредставлениеИдентификатора(Ссылка) Экспорт
	
	ОбъектыРасширений = ТипЗнч(Ссылка) <> Тип("СправочникСсылка.ИдентификаторыОбъектовМетаданных");
	СвойстваКоллекций = СтандартныеПодсистемыПовтИсп.СвойстваКоллекцийОбъектовМетаданных(ОбъектыРасширений);
	
	СвойстваКоллекции = СвойстваКоллекций.Найти(Ссылка.УникальныйИдентификатор(), "Идентификатор");
	Если СвойстваКоллекции <> Неопределено Тогда
		Возврат СвойстваКоллекции.Синоним;
	КонецЕсли;
	
	Запрос = Новый Запрос;
	Запрос.УстановитьПараметр("Ссылка", Ссылка);

```

Т.е. разработчики наивно полагали, что Ссылка будет всегда в этой строке и она будет заполнена:

```
СвойстваКоллекции = СвойстваКоллекций.Найти(Ссылка.УникальныйИдентификатор(), "Идентификатор");
```

Но в ИР есть такой участок кода:

```
Если Найти(Объект, ПеревестиСтроку(Подтип) + ".") > 0 Тогда
```

Где в качестве значения переменной "Объект" передается "СправочникОбъект", а не "СправочникСсылка". Происходит это в момент нажатия комбинации клавиш Ctrl+Q на ячейке (как в скриншоте выше), где содержится ссылка.
Так вот в попытке неявного преобразования "Объект" в строку идет вызов модуля менеджера для получения представления для него (еще не записанного объекта). И в процедуру ОбработкаПолученияПредставления передается структура через первый параметр "Данные", где ключ структуры "Ссылка" = Неопределено.
Получить УникальныйИдентификатор() у Неопределено никак не получается, поэтому ИР выдает следующую ошибку:

```
Значение не является значением объектного типа (УникальныйИдентификатор)
{Справочник.ИдентификаторыОбъектовМетаданных.МодульМенеджера(3761)}:	СвойстваКоллекции = СвойстваКоллекций.Найти(Ссылка.УникальныйИдентификатор(), "Идентификатор");
{ОбщийМодуль.СтандартныеПодсистемыПовтИсп.Модуль(663)}:	Возврат Справочники.ИдентификаторыОбъектовМетаданных.ПредставлениеИдентификатора(Ссылка);
{Справочник.ИдентификаторыОбъектовМетаданных.МодульМенеджера(75)}:	Представление = СтандартныеПодсистемыПовтИсп.ПредставлениеИдентификатораОбъектаМетаданных(Данные.Ссылка);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(3354)}:	Если Найти(Объект, ПеревестиСтроку(Подтип) + ".") > 0 Тогда
{ВнешняяОбработка.ирОбщий.МодульОбъекта(3399)}:	Результат = ЛиТипыРегистровРодственныЛкс(Объект, "КлючЗаписи", 2);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1119)}:		Если ирОбщий.ЛиКлючЗаписиРегистраЛкс(КлючИлиОбъект) Тогда
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1019)}:		ЗагрузитьОбъектПоКлючу(фОбъект.ПараметрКлючИлиОбъект);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(8023)}:	ФормаРедактора.Открыть();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(8013)}:		ОткрытьСсылкуВРедактореОбъектаБДЛкс(ЗначениеЯчейки);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3753)}:	ирКлиент.ОткрытьСсылкуЯчейкиВРедактореОбъектаБДЛкс(ТабличноеПоле);

```

Видимо другие программисты ERP или БСП знают об этой особенности поэтому, например, в документе ВводОстатков это предусмотрели:

![image](https://user-images.githubusercontent.com/87958986/212128752-f9f64488-a837-43f5-b9a7-69d3484bf5f6.png)

Т.к. это не ошибка ИР, то у меня есть предложение хотя бы попробовать обернуть код в Попытка..Исключение:

```
Функция ЛиТипыРегистровРодственныЛкс(Знач Объект, Знач Подтип, Знач КоличествоСлов) Экспорт 

    Попытка

    	Если Найти(Объект, ПеревестиСтроку(Подтип) + ".") > 0 Тогда
    		// Внешний источник данных
    		Результат = Истина;
    	Иначе
    		ТипОбразец = ирКэш.ЛюбойТипРегистраЛкс(Подтип);
    		Если ТипОбразец = Неопределено Тогда
    			Возврат Ложь;
    		КонецЕсли;
    		Результат = ЛиПодтипыТиповРавныЛкс(ТипОбразец, Объект, КоличествоСлов);
    	КонецЕсли;

    Исключение
        Результат = Ложь;
    КонецПопытки;

	Возврат Результат;

КонецФункции
```

**Comment by tormozit** [comment]
Проверяй мое исправление
```
	Если Истина
		И Найти(ТипЗнч(Объект), ":") > 0 // Антибаг БСП 2 https://github.com/tormozit/RDT1C/issues/324
		И Найти(Объект, ПеревестиСтроку(Подтип) + ".") > 0 
```

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/956894

**Comment by PerlAmutor** [comment]
Не сработало

```
Значение не является значением объектного типа (УникальныйИдентификатор)
{Справочник.ИдентификаторыОбъектовМетаданных.МодульМенеджера(4031)}:	СвойстваКоллекции = СвойстваКоллекций.Найти(Ссылка.УникальныйИдентификатор(), "Идентификатор");
{ОбщийМодуль.СтандартныеПодсистемыПовтИсп.Модуль(741)}:	Возврат Справочники.ИдентификаторыОбъектовМетаданных.ПредставлениеИдентификатора(Ссылка);
{Справочник.ИдентификаторыОбъектовМетаданных.МодульМенеджера(75)}:	Представление = СтандартныеПодсистемыПовтИсп.ПредставлениеИдентификатораОбъектаМетаданных(Данные.Ссылка);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(3356)}:    		И Найти(Объект, ПеревестиСтроку(Подтип) + ".") > 0 Тогда
{ВнешняяОбработка.ирОбщий.МодульОбъекта(3401)}:	Результат = ЛиТипыРегистровРодственныЛкс(Объект, "КлючЗаписи", 2);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1119)}:		Если ирОбщий.ЛиКлючЗаписиРегистраЛкс(КлючИлиОбъект) Тогда
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1019)}:		ЗагрузитьОбъектПоКлючу(фОбъект.ПараметрКлючИлиОбъект);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(8023)}:	ФормаРедактора.Открыть();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(8013)}:		ОткрытьСсылкуВРедактореОбъектаБДЛкс(ЗначениеЯчейки);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3753)}:	ирКлиент.ОткрытьСсылкуЯчейкиВРедактореОбъектаБДЛкс(ТабличноеПоле);

```
Условие надо поменять на "= 0"

![image](https://user-images.githubusercontent.com/87958986/212150585-fc4bed88-3fc6-49db-b419-bbeff6770c38.png)

**Comment by tormozit** [comment]
Конкретно этот сценарий исправлю, но думаю что эта ошибка БСП и в ряде других мест будет возникать. Например в консоли кода и исследователе объектов. Поэтому нужно стремиться к ее исправлению в БСП. В 1С отчет отправил?

**Comment by PerlAmutor** [comment]
Не отправлял. В рабочей базе у себя исправил.

**Comment by tormozit** [comment]
исправлено в 6.59.3
