### ISSUE TITLE
Редактор изменений на узлах. Не сбрасываются настройки формы при открытии.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#325]
https://user-images.githubusercontent.com/87958986/212556961-b8016f78-564c-4ca0-bc26-788e2ab440e8.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.60.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Вызвал команду открытия Редактора изменений на узлах
2. Получил предложение загрузить пустую настройку
3. Ответил утвердительно.
4. Получил ошибку:

```
Значение не является значением объектного типа (Свойство)
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(25)}:	НастройкаФормы.Свойство("ПометкиУзлов", мПометкиУзлов); 
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9908)}:		ЭтаФорма.ЗагрузитьНастройкуВФорме(НастройкаФормы, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9885)}:	ЗагрузитьНастройкуФормыЧерезОбработчикЛкс(ЭтаФорма, НастройкаФормы, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9863)}:			ЗагрузитьНастройкуФормыПоУмолчаниюЛкс(ЭтаФорма, Истина, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(827)}:	ирКлиент.СоздатьМенеджерСохраненияНастроекФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(161)}:		Форма.Открыть();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(143)}:	ОткрытьИнструмент(СтрокаИнструмента);

```
И так по кругу.

Если выбрать вариант "Отмена" то выдает такую ошибку:

```
Значение не является значением объектного типа (Количество)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(5288)}:	Если ОчиститьПередЗагрузкой Или ТаблицаПриемник.Количество() = 0 Тогда
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(1568)}:	ирОбщий.ЗагрузитьВТаблицуЗначенийЛкс(Узлы, мПометкиУзлов);
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(18)}:	ОбновитьСохраняемыеПометкиУзлов();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(10027)}:	СохраняемаяНастройкаФормы = ЭтаФорма.СохраняемаяНастройкаФормы(выхНовоеНаименование, ИменаСвойств);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9965)}:		НастройкаПоУмолчанию.Значение = СохраняемаяНастройкаФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9879)}:			СохранитьНастройкуФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9858)}:		ЗагрузитьНастройкуФормыПоУмолчаниюЛкс(ЭтаФорма, Не ЗагружатьСохранятьНастройкуПоУмолчанию, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(827)}:	ирКлиент.СоздатьМенеджерСохраненияНастроекФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(161)}:		Форма.Открыть();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(143)}:	ОткрытьИнструмент(СтрокаИнструмента);
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/956965

**Comment by tormozit** [comment]
Исправлено в 6.60.2
