### ISSUE TITLE
Сравнение таблиц. Не сбрасываются настройки формы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#326]
https://user-images.githubusercontent.com/87958986/212557319-5cfa75de-3238-4ffc-a929-3b1d6eaa45c1.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.60.1p
Инструменты разработчика. Инструмент: Сравнение таблиц
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Вызвал инструмент "Сравнение таблицу"
2. Возникла ошибка:

```
Преобразование значения к типу Булево не может быть выполнено
{ВнешняяОбработка.ирСравнениеТаблиц.Форма.Форма.Форма(11)}:	Если ирОбщий.ЛиТаблицаСериализуемаЛкс(Таблица1) И Таблица1.Количество() <= МаксЧислоСтрокДляСохранения Тогда
{ВнешняяОбработка.ирКлиент.МодульОбъекта(10027)}:	СохраняемаяНастройкаФормы = ЭтаФорма.СохраняемаяНастройкаФормы(выхНовоеНаименование, ИменаСвойств);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9965)}:		НастройкаПоУмолчанию.Значение = СохраняемаяНастройкаФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9879)}:			СохранитьНастройкуФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9858)}:		ЗагрузитьНастройкуФормыПоУмолчаниюЛкс(ЭтаФорма, Не ЗагружатьСохранятьНастройкуПоУмолчанию, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирСравнениеТаблиц.Форма.Форма.Форма(411)}:	ирКлиент.СоздатьМенеджерСохраненияНастроекФормыЛкс(ЭтаФорма,,,, "ctb");
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(161)}:		Форма.Открыть();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(143)}:	ОткрытьИнструмент(СтрокаИнструмента);

```

3. ИР предложил сбросить на пустую настройку
4. Согласился. Форма открылась нормально, но при закрытии выдается такую ошибку и весь процесс повторяется заново

```
Преобразование значения к типу Булево не может быть выполнено
{ВнешняяОбработка.ирСравнениеТаблиц.Форма.Форма.Форма(11)}:	Если ирОбщий.ЛиТаблицаСериализуемаЛкс(Таблица1) И Таблица1.Количество() <= МаксЧислоСтрокДляСохранения Тогда
{ВнешняяОбработка.ирКлиент.МодульОбъекта(10027)}:	СохраняемаяНастройкаФормы = ЭтаФорма.СохраняемаяНастройкаФормы(выхНовоеНаименование, ИменаСвойств);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9965)}:		НастройкаПоУмолчанию.Значение = СохраняемаяНастройкаФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(16096)}:		СохранитьНастройкуФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирСравнениеТаблиц.Форма.Форма.Форма(975)}:	ирКлиент.Форма_ПриЗакрытииЛкс(ЭтаФорма);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/956966

**Comment by tormozit** [comment]
Исправлено в 6.60.2
