### ISSUE TITLE
Уменьшить занимаемое списком инструментов подсистемы пространство по высоте

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#327]
Добавляем три новых раздела: отладка, отчеты, внешние инструменты.
![image](https://user-images.githubusercontent.com/75837433/213102451-f8ff5730-f90b-4830-b472-0b3e5a3381e8.png)
От появления трех новых сущностей (разделов) вряд ли у кого-то возникнут проблемы.
Но даже если ты опасаешься чрезмерной нагрузки на мозг, то добавь хотя бы какой-нибудь один любой раздел - уже это позволит избавить меня от вертикальной полосы прокрутки в полноэкранном режиме (при разрешении экрана 1080 по вертикали), которая есть сейчас.
А остальные разделы можно вводить постепенно (с выходом новых релизов).

**Comment by tormozit** [comment]
Лучше начинать  с описания проблемы (неудобства) и уже затем предлагать ее решение. Покажи чем неудобно именно тебе текущее поведение.

**Comment by john-doe-1c** [comment]
Неудобен скролл справа:
![image](https://user-images.githubusercontent.com/75837433/213136418-928280bc-e875-43c9-9ded-049246d12292.png)

И это я развернул окно на весь экран. В идеале хочется чтоб оно все умещалось без скролла и при меньших размерах окна клиента.

**Comment by tormozit** [comment]
На твоей картинке все команды раздела видны, не смотря на наличие полосы прокрутки. Кажется что неудобство преувеличено.

**Comment by john-doe-1c** [comment]
Чтобы убедиться, видны они все или нет, уже сейчас приходится отвлекаться на скролл и проматывать.
Ну а в будущем добавится 1-2 новых инструмента и приехали :)

**Comment by Absolemus** [comment]
Дело даже не в том, помещается на экран или нет,  а в удобстве навигации. Я постоянно пользуюсь поиском нужного инструмента через поиск, потому что искать глазами его очень сложно. Если инструменты будут разбиты по разделам, это исключит кучу кликов при ежедневной работе с инструментами и принесет нам кучу добра и счастья

**Comment by tormozit** [comment]
> пользуюсь поиском нужного инструмента через поиск

Так и задумано. Первое время ты ищешь медленно (фильтром) и постепенно запоминаешь название инструмента, а потом уже быстро находишь сканированием взглядом по алфавиту - наиболее универсальным поиском.

> инструменты будут разбиты по разделам

Тут проблема что разные группы пользователей хотят разбивку на разные группы команд. Мне например предложенная разбивка не подходит, т.к. я не вижу разницы между элементами группы "Отчеты" и "Администрирование". Всем не угодишь. А любая группировка испортит сканирование взглядом по алфавиту. Так что счастье для всех тут просто невозможно из-за различных потребностей и уровня знакомства пользователей с подсистемой.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/957123
Пока попробуем такой вариант. Для меня он удобства не снижает и устраняет главное неудобство инициатора - полосу прокрутки.

![изображение](https://user-images.githubusercontent.com/11896251/213258113-7f30b20a-5062-43a0-a040-1fdbba941c17.png)

**Comment by Absolemus** [comment]
> сканированием взглядом по алфавиту

В инструментах 9 редакторов, 7 консолей, 4 управления. Простым сканированием сходу никак не найти, ты все равно 3-4 секунды тупишь какой редактор из предложенных нужен в данный момент.

**Comment by tormozit** [comment]
Еще сделал менее компактный вариант с отдельной группой "Отладка". Он конечно больше понравится тем, кто часто пользуется функциями режима отладки и при этом не использует платформенное "Избранное".

![изображение](https://user-images.githubusercontent.com/11896251/213261021-b6f8f1a2-1dd5-4a38-83fb-be5b0ec6b525.png)

**Comment by Absolemus** [comment]
> и при этом не использует платформенное "Избранное"

Оно превращается в помойку и никак не помогает в быстром нахождении нужного инструмента.

**Comment by john-doe-1c** [comment]
> сделал менее компактный вариант с отдельной группой "Отладка"

Разработку и отладку разделить по разным колонкам не хочешь?
![image](https://user-images.githubusercontent.com/75837433/213287087-2d9add9f-5390-4385-bad5-a63081576c1b.png)

**Comment by tormozit** [comment]
Отладка - по сути подгруппа разработки. Пока я еще даже окончательно не решил что буду выделять группу "Отладка". Поэтому твой последний вариант мне точно не подходит.

**Comment by john-doe-1c** [comment]
В соседних столбцах отладку и разработку тоже отвергаешь?
![image](https://user-images.githubusercontent.com/75837433/213363808-88f9857d-46d9-49a3-863c-4097341930bf.png)

**Comment by tormozit** [comment]
Реализовано в 6.61
