### ISSUE TITLE
Консоль компоновок: Проблема с заполнение параметра, у которого доступен список значений

### ISSUE THREAD

**Issue by Mikeware2007** [tormozit/RDT1C#328]
**Программное окружение**
Платформа: 8.3.18.1289
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.7.141)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.61.1e
Инструменты разработчика. Инструмент: Консоль компоновок данных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да

**Воспроизведение проблемы**
1. Открыл инструмент Консоль компоновок
2. Загрузил схему, сохраненную из основной конфигурации. В параметрах -параметр ХозОперация, у которого доступен список значений.
3. Нажал кнопку заполнения значения ("...")
4. Открылось окно заполнения СЗ. 
5. Заполняю СЗ значениями
6. нажимаю ОК
7. Окно заполнения СЗ закрывается, но список в параметрах остается пустой.

**Ожидаемое поведение**
Ожидалось, что заполненный список перенесется в параметр.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/957353

**Comment by tormozit** [comment]
Исправлено в 6.61.2
