### ISSUE TITLE
Дин. список: ошибка при выборе ТЧ справочников

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#329]
> Платформа: 8.3.17.1851
Режим БД: клиент-серверный
Конфигурация. Название: УТП 11
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_9
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 203
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Конфигурация 6.61.1
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Active code page: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

Открыть ДС, выбрать любую ТЧ любого справочника. Например, "_Справочник.Кассы.ДополнительныеРеквизиты_". Будет ошибка:
```
Метод ПолучитьИменаПредопределенных недоступен
{ОбщийМодуль.ирСервер.Модуль(1217)}:		И ирОбщий.ЛиКорневойТипОбъектаСПредопределеннымЛкс(ирОбщий.ПервыйФрагментЛкс(ПолноеИмяТаблицыБД))
{Обработка.ирДинамическийСписок.Форма.ФормаУпр.Форма(391)}:	Если Не ирСервер.НастроитьАвтоТаблицуФормыДинамическогоСпискаЛкс(ЭтаФорма, ОсновнойЭУ, ПолноеИмяТаблицыСДопами, фОбъект.РежимИмяСиноним, СоединенныеРегистры, СхемаПодвала) Тогда 
{Обработка.ирДинамическийСписок.Форма.ФормаУпр.Форма(100)}:	Если Не ОбновитьЗапросБД() Тогда
{Обработка.ирДинамическийСписок.Форма.ФормаУпр.Форма(662)}:	УстановитьОбъектМетаданных(ПолноеИмяТаблицы, СохранитьНастройкиТаблицы);
{Обработка.ирДинамическийСписок.Форма.ФормаУпр.Форма(627)}:	УстановитьОбъектМетаданныхНаКлиенте(, Истина);
{ОбщийМодуль.ирКлиент.Модуль(2899)}:	ФормаИнициатор.ОповеститьОВыборе(Значение); 
{ОбщийМодуль.ирКлиент.Модуль(9302)}:		ИнтерактивноЗаписатьВПолеВводаЛкс(Элемент, РезультатВыбора.ПолноеИмяОбъекта);
{Обработка.ирДинамическийСписок.Форма.ФормаУпр.Форма(639)}:	ирКлиент.ОбъектМетаданныхНачалоВыбораЛкс(Элемент, ПараметрыВыбораОбъектаМетаданных(), СтандартнаяОбработка);

по причине:
Метод ПолучитьИменаПредопределенных недоступен
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/957352

**Comment by tormozit** [comment]
Исправлено в 6.61.2
