### ISSUE TITLE
Консоль кода. Значение не является значением объектного типа (НайденныеСтроки)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#330]
https://user-images.githubusercontent.com/87958986/214644251-a748fe75-6083-4d5c-92d2-664cf39676be.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.61.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл консоль кода. Вызвал команду "Структура"
2. При отключении кнопки получил ошибку:

```
Значение не является значением объектного типа (НайденныеСтроки)
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(10165)}:	Для Каждого НайденнаяСтрока Из МенеджерПоиска.НайденныеСтроки Цикл 
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(10153)}:		ПрименитьСтрокуПоискаКСтруктуреЗапроса(Текст, АктивизироватьСтрокуДереваЗапроса <> Ложь, ИскатьСНачала);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(4420)}:	СтрокаПоискаПриИзменении(, Ложь, Истина, Ложь, Истина,, Истина);
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/957362

**Comment by tormozit** [comment]
Исправлено в 6.61.3
