### ISSUE TITLE
Редактор объекта БД. Связанные колонки БД. Ошибка при вызове метода контекста (ИзменитьСтроку)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#331]
https://user-images.githubusercontent.com/87958986/214645791-35f314bd-8a40-4944-93c4-bfb5e25b46fa.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.61.2p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Редактор объекта БД. 
2. Перешел на вкладку "Связанные колонки БД"
3. "Отжал" команду "Только избранное"
4. Вызвал команду "Выключить выделенные строки"
5. Получил ошибку:

```
Ошибка при вызове метода контекста (ИзменитьСтроку)
{ВнешняяОбработка.ирКлиент.МодульОбъекта(2965)}:			ТабличноеПоле.ИзменитьСтроку();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(7103)}:		ИнтерактивноЗаписатьВКолонкуТабличногоПоляЛкс(ТабличноеПоле, Колонка, ПоследняяОбработаннаяСтрока[ирОбщий.ПутьКДаннымКолонкиТабличногоПоляЛкс(ТабличноеПоле, Колонка)],,,,, Истина, ПутьКДаннымКолонки, МетаданныеВыбора); 
{ВнешняяОбработка.ирКлиент.МодульОбъекта(1669)}:	УстановитьЗначениеВКолонкеТабличногоПоляТЧИлиТЗЛкс(ЭтаФорма, ТабличноеПоле, НовоеЗначениеПометки, "", Колонка, ТабличноеПоле.ВыделенныеСтроки.Количество() > 1, ИнтерактивнаяУстановка,, СтруктураОтбора);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(5214)}:	ирКлиент.ИзменитьПометкиВыделенныхИлиОтобранныхСтрокЛкс(ЭтаФорма, ЭлементыФормы.СвязанныеДанные,, Ложь);
по причине:
Отсутствует строка данных


```

**Comment by tormozit** [comment]
Непонятно как добиться исчезновения выделения текущей строки как у тебя уже сначала ролика показано.

**Comment by PerlAmutor** [comment]
> Непонятно как добиться исчезновения выделения текущей строки как у тебя уже сначала ролика показано.

А просто не нужно никуда кликать мышкой кроме команды "Только избранное".

**Comment by tormozit** [comment]
Это тоже непонятно. Постарайся описать с момента открытия инструмента. Например в текущем описании непонятно каким образом ты установил объект в редакторе.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/957364

**Comment by tormozit** [comment]
Исправлено в 6.62
