### ISSUE TITLE
Редактор объекта БД. Редактирование перечислений. Поле объекта не обнаружено (Ссылка)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#332]
https://user-images.githubusercontent.com/87958986/214651094-6d411487-c2a9-48a0-85fe-de1c34fd21c1.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.61.2p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл "Редактор объекта БД"
2. Выбрал значение _перечисления_
3. Вызвал команду "ОК"
4. Получил ошибку

```
Поле объекта не обнаружено (Ссылка)
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1474)}:	Если Истина
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(5563)}:	КнопкаЗаписатьНажатие();
```

**Comment by tormozit** [comment]
Ошибку воспроизвел
