### ISSUE TITLE
Редактор объекта БД. Добавление ссылки в историю.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#333]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.61.2p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

Ошибка сложно воспроизводимая. В какой-то момент она у меня вылезла. Могу лишь дать наводку.

**Воспроизведение проблемы**
1. Открыть Редактор объекта БД
2. Выбрать значение перечисления
3. Оставить форму открытой на какое-то время
4. Если повезет то можно наблюдать диалоговое окно с ошибкой в строке 709 модуля объекта Внешней обработки ирКлиент.
Приблизительный текст: "Ошибка при вызове метода контекста (ПолучитьНавигационнуюСсылку). По стеку вызова происходит на этой строке:

![image](https://user-images.githubusercontent.com/87958986/214656336-3335dba6-8247-4c1a-80e2-14c60cbcb9e5.png)

Возможно есть проблема с проверкой заполнения ссылки, т.к. функция ирКлиент.КлючОсновногоОбъектаФормыЛкс(ФормаСсылки) иногда может возвращать не пустую строку:

![image](https://user-images.githubusercontent.com/87958986/214656663-d31928a8-3f05-4229-b747-4e25a7bdd293.png)

**Comment by tormozit** [comment]
Проблему понял. Исправлю.

**Comment by tormozit** [comment]
Исправлено в 6.61.3
