### ISSUE TITLE
Не запускается отладка запроса когда программа остановлена по точке останова - Метод объекта не обнаружен (От)

### ISSUE THREAD

**Issue by Serg2252** [tormozit/RDT1C#334]
Платформа: 8.3.22.1704
Режим БД: клиент-серверный
Конфигурация. Название: УПП 1.3 (1.3.6.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 6.61.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс

**Воспроизведение проблемы**
1. Открыл инструмент "Функции режима отладки"
2. Скопировал строку для отладки запроса
3. Программа остановилась по точке останова на коде "пПараметры.Запрос.Выполнить();". Это выполнение запроса при проведении документа.
4. В окно "вычислить выражение" вставил текст ВнешниеОбработки.Создать("E:\C1\DevTools\ирПортативный.epf", Ложь).От(пПараметры.Запрос)
5. После нажатия рассчитать получил ошибку:
ВнешниеОбработки.Создать("E:\C1\DevTools\ирПортативный.epf", Ложь).От(пПараметры.Запрос)	{<Неизвестный модуль>(1)}: Метод объекта не обнаружен (От)	

**Ожидаемое поведение**
В предприятии должна была открыться консоль запросов.

**Comment by tormozit** [comment]
Нужен полный список окна отладчика, чтобы был виден стек.  И еще покажи результат вычисления выражения до ".От"

**Comment by Serg2252** [comment]
![image](https://user-images.githubusercontent.com/7805476/214862641-3159725c-1490-406c-9bbe-6cb52f56919f.png)


Еще инфо:

Кэш чистил
Название папки с ИР менял (иногда после обновления ИР нужно менять, иначе глюки)
Конфигуратор запущен на машине с кластером 1С.
В параметрах службы 1С есть параметр -debug

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/957385

**Comment by tormozit** [comment]
Исправлено в 6.61.3

**Comment by PerlAmutor** [comment]
А у меня вот не починилось. Последний рабочий релиз где работала отладка ИР 6.58. Тестировал на версии 6.62.1p.

**Comment by tormozit** [comment]
@PerlAmutor Уверен, что ошибка такая же? У меня огромные сомнения в возможности этого. А если ошибка другая, то нужно создать новую заявку.

**Comment by PerlAmutor** [comment]
Ошибка другая. Неизвестная какая-то. Никакой конкретики. На файловой базе не воспроизводится. Пытался запрос отладить.
