### ISSUE TITLE
Отслеживание обновления конфигурации.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#335]
```
Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.61.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

```

Большинство инструментов ИР строят первоначальный кэш метаданных в каждом запущенном сеансе, раз за разом, даже если конфигурация не меняется. Хотелось бы этот кэш сохранять на диск и подгружать готовым, чтобы не ждать открытия инструментов.
К сожалению на данный момент в платформе нет инструментов для отслеживания изменений. Если получиться найти обходной путь будет здорово.

**Comment by tormozit** [comment]
Начни с описания конкретной проблемы http://devtool1c.ucoz.ru/forum/2-2-1 . Затем уже можешь описать ее обобщение и предложить решение.

**Comment by PerlAmutor** [comment]
Проблему записал на видео, т.к. база файловая, то все достаточно быстро, на клиент-серверных все не так радужно


https://user-images.githubusercontent.com/87958986/215276626-fc500003-b948-4428-95ad-dab658801f59.mp4

**Comment by tormozit** [comment]
Нужна техническая информация http://devtool1c.ucoz.ru/forum/2-2-1

**Comment by tormozit** [comment]
На твоем ролике наполнение кэша сеанса ИР выполнилось за 6 секунд. Это - хороший результат для портативного варианта в ERP.
Если ты хочешь значительного ускорения, то используй вариант "Расширение", о чем я тебе уже 10+ раз сообщал. Но ты упорно продолжаешь пользоваться ущербным однопоточным портативным вариантом и ждать какого то чуда.

**Comment by tormozit** [comment]
> на клиент-серверных все не так радужно

Не верю. У меня ERP клиент-серверная с ИР вариантом "Расширение" работает с приемлемой скоростью.

**Comment by tormozit** [comment]
Как то быстро ты сдался. А начало заявки было многообещающим.
