### ISSUE TITLE
Редактор объекта БД. Серии номенклатуры.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#336]
https://user-images.githubusercontent.com/87958986/215332276-3ee4b4be-3d0e-4f83-9550-1a97a47caa84.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.61.2p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыть Редактор объекта БД на конфигурации ERP
2. Выбрать справочник "СерииНоменклатуры"
3. Выдается ошибка:

`Ошибка создания объекта: {ВнешняяОбработка.ирОбщий.МодульОбъекта(1786)}: Ошибка при вызове метода контекста (Заполнить): Ошибка при выполнении обработчика - 'ОбработкаЗаполнения': {Справочник.СерииНоменклатуры.МодульОбъекта(86)}: Значение не является значением объектного типа (ВидНоменклатуры)
`

Создание серий номенклатуры по задумке программистов ERP невозможно без передачи структуры с ключом "ВидНоменклатуры" в обработчик заполнения. ИР же туда передает "Неопределено". Видимо надо оборачивать в Попытка ... Исключение.

**Comment by tormozit** [comment]
Покажи фрагмент кода конфигурации, в котором возникает ошибка

**Comment by tormozit** [comment]
> Покажи фрагмент кода конфигурации, в котором возникает ошибка

Так это уже сделано. Именно поэтому ты и видишь не окно ошибки, а сообщение, и команда пользователя выполняется. Сообщение выводится, чтобы пользователь понимал, почему реквизиты не заполнены значениями по умолчанию.

**Comment by PerlAmutor** [comment]
А зачем ИР вообще пытается заполнить что-то, когда я открываю ссылку существующего объекта?

https://user-images.githubusercontent.com/87958986/215333920-001d2898-fe39-4d63-9e97-63497085bb35.mp4

А то возникает ложное чувство, что с кодом документа что-то не так.

**Comment by tormozit** [comment]
Неоправданный вызов заполнения объекта при открытии существующего объекта воспроизвел https://www.hostedredmine.com/issues/957473

**Comment by tormozit** [comment]
Исправлено в 6.62
