### ISSUE TITLE
Не работает отладка.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#337]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.62.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. При использовании функции От() в вычислить выражение происходит возврат неизвестной ошибки
2. Я произвел вызов функции из своей обработки и получил следующее:

```
{ВнешняяОбработка.ирКлиент.МодульОбъекта(869,30)}: Конструктор не найден
:ВнешниеОбработки.Создать("\\server1\ИР\ирПортативный.epf", Ложь).От(Объект);

по причине:
Ошибка инициализации модуля: ВнешняяОбработка.ирПортативный.МодульОбъекта
по причине:
{ВнешняяОбработка.ирКлиент.МодульОбъекта(869,30)}: Конструктор не найден
по причине:
Ошибка инициализации модуля: ВнешняяОбработка.ирКлиент.МодульОбъекта
по причине:
{ВнешняяОбработка.ирКлиент.МодульОбъекта(869,30)}: Конструктор не найден
		ДействиеТранслятор = Новый <<?>>Действие("Клс" + ИмяКласса + "Нажатие");
{ВнешняяОбработка.ирКлиент.МодульОбъекта(875,30)}: Конструктор не найден
		ДействиеТранслятор = Новый <<?>>Действие("КнопкаКоманднойПанели_Действие")
{ВнешняяОбработка.ирКлиент.МодульОбъекта(1390,62)}: Конструктор не найден
		ТабличноеПоле.УстановитьДействие(КлючИЗначение.Ключ, Новый <<?>>Действие(ИмяОбработчика));
{ВнешняяОбработка.ирКлиент.МодульОбъекта(1473,49)}: Конструктор не найден
	ПолеВвода.УстановитьДействие(ИмяСобытия, Новый <<?>>Действие(ИмяОбработчика));
{ВнешняяОбработка.ирКлиент.МодульОбъекта(1807,21)}: Тип не определен (ДиалогВыбораФайла)
	ВыборФайла = Новый <<?>>ДиалогВыбораФайла(РежимДиалога);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(1828,21)}: Тип не определен (ДиалогВыбораФайла)
	ВыборФайла = Новый <<?>>ДиалогВыбораФайла(РежимДиалогаВыбораФайла.ВыборКаталога);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(2093,28)}: Тип не определен (СравнениеФайлов)
			СравнениеФайлов = Новый <<?>>СравнениеФайлов;
{ВнешняяОбработка.ирКлиент.МодульОбъекта(4040,26)}: Тип не определен (СравнениеФайлов)
	СравнениеФайлов = Новый <<?>>СравнениеФайлов;
{ВнешняяОбработка.ирКлиент.МодульОбъекта(4679,29)}: Тип не определен (ДиалогВыбораЦвета)
		ДиалогВыбораЦвета = Новый <<?>>ДиалогВыбораЦвета;
{ВнешняяОбработка.ирКлиент.МодульОбъекта(4687,30)}: Тип не определен (ДиалогВыбораШрифта)
		ДиалогВыбораШрифта = Новый <<?>>ДиалогВыбораШрифта;
{ВнешняяОбработка.ирКлиент.МодульОбъекта(8015,111)}: Конструктор не найден
	ПоследниеВыбранныеЗаполнитьПодменюЛкс(ЭтаФорма, КоманднаяПанель.Кнопки.ПоследниеОтборы, ТабличноеПоле, Новый <<?>>Действие("КлсКомандаНажатие"), "Отборы");
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9813,25)}: Конструктор не найден
	ДействиеКнопки = Новый <<?>>Действие(ИмяДействия);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(10119,21)}: Тип не определен (ДиалогВыбораФайла)
	ВыборФайла = Новый <<?>>ДиалогВыбораФайла(РежимДиалогаВыбораФайла.ВыборКаталога);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(14032,54)}: Конструктор не найден
					КнопкаСтруктураКоманднойПанели.Действие = Новый <<?>>Действие("СтруктураКоманднойПанелиНажатие");
{ВнешняяОбработка.ирКлиент.МодульОбъекта(14994,28)}: Тип не определен (ДиалогВыбораФайла)
	ДиалогВыбораФайла = Новый <<?>>ДиалогВыбораФайла(РежимДиалогаВыбораФайла.Открытие);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(15068,29)}: Тип не определен (ДиалогВыбораФайла)
		ДиалогВыбораФайла = Новый <<?>>ДиалогВыбораФайла(РежимДиалогаВыбораФайла.Сохранение);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(16785,37)}: Конструктор не найден
		КнопкаКопировать.Действие = Новый <<?>>Действие("КлсКомандаНажатие");
{ВнешняяОбработка.ирКлиент.МодульОбъекта(16803,34)}: Конструктор не найден
	КнопкаВставить.Действие = Новый <<?>>Действие("КлсКомандаНажатие");
```

Ошибка воспроизводится только на клиент-серверных базах. Идет попытка подключить ИрКлиент на Сервере без проверки контекста.
В одном из релизов появилась следующая строчка, после которой отладка работать перестала:

![image](https://user-images.githubusercontent.com/87958986/215806066-4bb81ca0-a55e-4a47-912b-6e4058a06748.png)

Я исправил как смог у себя. Пример прикрепил.
[ирПортативный.zip](https://github.com/tormozit/RDT1C/files/10548127/default.zip)

**Comment by tormozit** [comment]
Ошибка тут https://www.hostedredmine.com/issues/957603

**Comment by tormozit** [comment]
Техническая информация у тебя от файловой базы. Ошибка не может проявляться в файловой базе.

**Comment by tormozit** [comment]
Исправлено в 6.62.2
