### ISSUE TITLE
Добавить кнопку "Выдать копию результата в табличный документ" для плоского макета компоновки в консоли компоновки данных

### ISSUE THREAD

**Issue by Irekovich** [tormozit/RDT1C#339]
Прошу рассмотреть возможность добавления кнопки "Выдать копию результата в табличный документ" для плоского макета компоновки в консоли компоновки данных.
![image](https://user-images.githubusercontent.com/7760229/215871917-b367dd02-c6ba-41fc-b212-952bfbddc920.png)

**Comment by tormozit** [comment]
Зачем это нужно?

**Comment by Irekovich** [comment]
Это необходимо для повышения удобства просмотра макета компоновки данных на небольших экранах.
Сейчас приходится двигать панели, либо по ctrl+n создавать новый табличный документ и копипастить макет в него.
На соседней закладке "Табличный документ" такая кнопка есть, и я ей часто пользуюсь по этой же причине.

**Comment by tormozit** [comment]
В глобальном меню есть команда такая.

**Comment by Irekovich** [comment]
Не понимаю. Покажи, пожалуйста.

**Comment by tormozit** [comment]
https://infostart.ru/1c/articles/1273456/

**Comment by Irekovich** [comment]
Что я делаю не так?
Написано, что работает в любой форме инструмента во всех клиентских приложениях.
В толстом управляемом приложении получилось, а в обычном приложении в той же базе нет. Стою сфокусированным на плоском макете компоновки, жму CTRL + Ё, ничего не происходит.

**Comment by tormozit** [comment]
Смотри в общих настройках. Там отключен перехват клавиатурного ввода у тебя. Так сделано по умолчанию для конфигураций под обычное приложение.

**Comment by Irekovich** [comment]
Получилось, спасибо.
