### ISSUE TITLE
Поблема с консолью запроса

### ISSUE THREAD

**Issue by nvronzhin** [tormozit/RDT1C#340]
**Программное окружение**

Платформа: 8.3.20.1710
Режим БД: клиент-серверный
Конфигурация. Название: Альфа-Авто: Автосалон+Автосервис+Автозапчасти ПРОФ, редакция 5.1 (5.1.27.04)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Конфигурация 6.62.1
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. РНВ_ДоработкиПо_SP_DMSАдаптеру ()
Расширения. РНВ_ДоработкиСтандартногоФункционала ()
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2008 R2 Enterprise  64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Сервер. Процесс: 32б
Сервер. Отладка: tcp

**Воспроизведение проблемы**

С некоторго времени перестал исполняться запрос из консоли содержащий вот такой кусок:
ВЫРАЗИТЬ((_24_Данные_для_маржинального_анализа.ФРЦ - _24_Данные_для_маржинального_анализа.Закупочная_цена) * _24_Данные_для_маржинального_анализа.КоэффициентНДС_Кузов * ВЫБОР
      КОГДА _24_Данные_для_маржинального_анализа.Организация.СистемаНалогообложения = ЗНАЧЕНИЕ(перечисление.СистемыНалогообложения.Общая)
        ТОГДА &КоэффициентНалогаНаПрибыль
      КОГДА _24_Данные_для_маржинального_анализа.Организация.СистемаНалогообложения = ЗНАЧЕНИЕ(перечисление.СистемыНалогообложения.Упрощенная)
        ТОГДА 1
    КОНЕЦ * (1 - 0.01 * _24_Данные_для_маржинального_анализа.СрокХранения / 30) КАК ЧИСЛО(15, 2))

Вот с таким диагнозом:
Текст запроса: Строка кода 1 289: {(1 289,171)}: Неверные параметры "*"
ВЫРАЗИТЬ((_24_Данные_для_маржинального_анализа.ФРЦ - _24_Данные_для_маржинального_анализа.Закупочная_цена) * _24_Данные_для_маржинального_анализа.КоэффициентНДС_Кузов * <<?>>ВЫБОР

При этом если его исполнять в СКД или в простом коде 1С - никаких ошибок не вылетает.

**Comment by tormozit** [comment]
Скорее всего в твоей конструкции ВЫБОР одна из веток возвращает НЕ число (например &КоэффициентНалогаНаПрибыль) . Поэтому платформа и ругается, т.к. умножение на НЕ число она не умеет делать. Думаю, что в коде ты выполняешь запрос с другими значениями параметров. Поэтому там и не возникает ошибки. 
Еще в этой конструкции у тебя отсутствует секция ИНАЧЕ, что тоже не очень хорошо для числового выражения. Но на проявление описанной проблемы возможно и не влияет.

Если уверен что все параметры имеют правильные типы, то делай целостный минимальный пример запроса, желательно отвязанный от метаданных, в виде файла консоли и прикрепи его сюда.

**Comment by nvronzhin** [comment]
Нет - сейчас этот запрос нормально исполняется в СКД.

Я добавил иначе

ВЫРАЗИТЬ((_24_Данные_для_маржинального_анализа.ФРЦ -
_24_Данные_для_маржинального_анализа.Закупочная_цена) *
_24_Данные_для_маржинального_анализа.КоэффициентНДС_Кузов * ВЫБОР
КОГДА
_24_Данные_для_маржинального_анализа.Организация.СистемаНалогообложения =
ЗНАЧЕНИЕ(перечисление.СистемыНалогообложения.Общая)
ТОГДА &КоэффициентНалогаНаПрибыль
КОГДА
_24_Данные_для_маржинального_анализа.Организация.СистемаНалогообложения =
ЗНАЧЕНИЕ(перечисление.СистемыНалогообложения.Упрощенная)
ТОГДА 1
ИНАЧЕ 1
КОНЕЦ * (1 - 0.01 * _24_Данные_для_маржинального_анализа.СрокХранения / 30)
КАК ЧИСЛО(15, 2))

ошибку выдает такую же

Попробую разбить запрос на части и посмотреть что выдает каждая часть

ср, 1 февр. 2023 г. в 19:02, Sergey Starykh ***@***.***>:

**Comment by tormozit** [comment]
Кажется, ты ответил на старый вариант моего ответа. Лучше все таки прочитай актуальный.

**Comment by nvronzhin** [comment]
Мне твоей наводки хватило - проблема оказалась не в этом куске - в _24_Данные_для_маржинального_анализа.КоэффициентНДС_Кузов попало не число
вопрос можно закрывать
