### ISSUE TITLE
Динамический список. Перечисления.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#341]
https://user-images.githubusercontent.com/87958986/216090264-b13a229a-6a61-44e6-8360-5d5d4132591a.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.62.1p
Инструменты разработчика. Инструмент: Обработка.ирДинамическийСписок.Форма.Форма
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыть динамический список ИР с перечислениями
2. Нажать на Группировку таблицы
3. Получить сообщение об ошибке

```
Ошибка при вызове метода контекста (Выполнить)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(13226)}:	Таблица = Запрос.Выполнить().Выгрузить();
{ВнешняяОбработка.ирПлатформа.Форма.ГруппировкаТаблицы.Форма(50)}:			ДанныеСтаройТекущейСтроки = ирОбщий.СтрокаТаблицыБДПоКлючуЛкс(ИмяТаблицыБД, СтруктураКлюча);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(16385)}:		Форма.Открыть();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(16924)}:				ОткрытьГруппировкуТабличногоПоляЛкс(ИсточникДействий, НастройкаКомпоновки);
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(560)}:	ирКлиент.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
по причине:
{(1, 87)}: Неверные параметры в операции сравнения. Нельзя сравнивать поля
 неограниченной длины и поля несовместимых типов.
ВЫБРАТЬ Т.* ИЗ Перечисление.ОбеспечениеЗаказовПриПоддержанииЗапаса КАК Т ГДЕ Т.Ссылка <<?>>= &Ссылка

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.63
