### ISSUE TITLE
Динамический список. Перечисления. Скопировать.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#343]
https://user-images.githubusercontent.com/87958986/216092797-3b8c2540-d4bd-420c-95ee-96eb70957c6c.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.62.1p
Инструменты разработчика. Инструмент: Обработка.ирДинамическийСписок.Форма.Форма
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Динамический список ИР
2. Выбрал перечисление
3. Нажал кнопку "Добавить копированием"
4. Получил ошибку

```
Поле объекта не обнаружено (Ссылка)
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(852)}:				КлючОбъекта[КлючИЗначение.Ключ] = ЭлементыФормы.ДинамическийСписок.ТекущаяСтрока[КлючИЗначение.Ключ];
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(591)}:		ДобавитьСтрокуЧерезРедакторОбъектаБД(, Копирование, ЭтоГруппа);

```

**Comment by tormozit** [comment]
ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.63
