### ISSUE TITLE
Динамический список. Перечисления. Выделить N строк.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#344]
https://user-images.githubusercontent.com/87958986/216093634-ce203f12-795a-41e5-8e4e-708aa8c78d69.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.62.1p
Инструменты разработчика. Инструмент: Обработка.ирДинамическийСписок.Форма.Форма
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Динамический список ИР
2. Выбрал перечисления
3. Вызвал команду "Выделить N строк"
4. Получил ошибку:

```
Поле объекта не обнаружено (Порядок)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(26578)}:	СкопироватьПорядокЛюбойЛкс(НастройкаКомпоновки.Порядок, НастройкиСписка.Порядок);
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(554)}:	ирОбщий.ВыделитьПервыеСтрокиДинамическогоСпискаЛкс(ЭлементыФормы.ДинамическийСписок, Количество);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/957813

**Comment by tormozit** [comment]
Исправлено в 6.63
