### ISSUE TITLE
Редактор объекта БД. Табличный документ. Загрузить строки.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#345]
https://user-images.githubusercontent.com/87958986/216094471-e912d4c0-8615-4b43-852a-67f5893a32fc.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.62.1p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Редактор объекта БД
2. Выбрал документ
3. Перешел на вкладку "Табличный документ"
4. Вызвал команду "Загрузить строки"
5. Получил ошибку:

```
Значение не является значением объектного типа (Имя)
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4236)}:	ИмяТЧ = ирОбщий.ПоследнийФрагментЛкс(ТабличноеПоле.Имя, фОбъект.мПрефиксИмениТабличногоПоляТЧ, Ложь);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4294)}:	ИмяТаблицыБДТабличногоПоля = ИмяТаблицыБДТабличногоПоля(ТабличноеПоле,,, Истина);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4283)}:		МетаданныеКолонок = МетаданныеКолонокТабличногоПоля(ТабличноеПоле);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.63
