### ISSUE TITLE
Консоль запросов. ТаблицаЗначений копируется в буфер обмена в виде строки

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#347]
https://user-images.githubusercontent.com/87958986/216877648-1391df91-227a-4b4c-8726-1edd952b5e56.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.63.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл ТаблицуЗначений
2. Вызвал команду "Передать в буфер обмена"
3. Перешел в Консоль запросов. Вызвал Глобальное меню (Ctrl+~), выбрал команду "Вставить из буфера обмена"
4. В качестве параметра вставилась строка с текстом "ТаблицаЗначений"

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/957871

**Comment by tormozit** [comment]
Исправлено в 6.64
