### ISSUE TITLE
Невозможно очистить поля ввода.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#348]
https://user-images.githubusercontent.com/87958986/217018155-75079290-1878-4b0f-90b6-8aec2460ce59.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.63.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. При попытке очистить значение ссылочного поля в таких инструментах как Редактор объекта БД и параметры Консоли Запросов, ИР не дает этого сделать предлагая выбрать каждый раз значение. В версии 6.61 и ранее такого не было.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/957861

**Comment by tormozit** [comment]
Исправлено в 6.63.2
