### ISSUE TITLE
Редактор объекта БД. Поле не найдено "Дата"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#349]
https://user-images.githubusercontent.com/87958986/217021376-ea27dfa2-1a1c-4eaa-add2-dbbc9d8cd22d.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.63.1p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл документ Авансовый Отчет (ERP) в Редакторе Объекта БД
2. Встал на поле "Руководитель"
3. Нажал на кнопку "Очистить"
4. Получил ошибку:

```
Ошибка при вызове метода контекста (Выполнить)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(22376)}:	МакетКомпоновки = КомпоновщикМакета.Выполнить(Схема, НастройкаКомпоновки, ,, Тип("ГенераторМакетаКомпоновкиДанныхДляКоллекцииЗначений"), ПроверятьДоступностьПолей);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(27417)}:	Запрос = ЗапросИзКомпоновкиЛкс(СхемаКомпоновки, НастройкаКомпоновки,,,, СхемаКолонок);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(27519)}:		ТаблицаРезультата = ТаблицаДанныхВыбораМенеджераЛкс(ОбъектМД, Параметры, СхемаКомпоновки, РазмерСпискаПлатформы);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(4479)}:				ирОбщий.СсылочныйМенеджерОбработкаПолученияДанныхВыбораЛкс(Менеджер, выхСписокПодобранных, ПараметрыВыбора, СтандартнаяОбработка);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(5714)}:	ПолеВвода_ОкончаниеВводаТекстаЛкс(ТабличноеПоле.Колонки[ИмяКолонкиЗначения].ЭлементУправления, Текст, Значение, СтандартнаяОбработка, ТабличноеПоле.ТекущиеДанные[ИмяКолонкиЗначения],,, СтруктураОтбора, ТекстАвтоПодбора);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(2202)}:	ирКлиент.ПолеВводаКолонкиЗначенияРеквизита_ОкончаниеВводаТекстаЛкс(ЭтаФорма, ЭлементыФормы.РеквизитыТаблица, ИмяОсновнойТаблицы, "ИмяРеквизита", "ЗначениеРеквизита", СвязиИПараметрыВыбора,
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(2207)}:	РеквизитыТаблицаЗначениеРеквизитаОкончаниеВводаТекста(Элемент, Текст,, СтандартнаяОбработка, ТекстАвтоПодбора);
по причине:
Ошибка компоновки макета
по причине:
Поле не найдено "Дата"

```

**Comment by tormozit** [comment]
Ошибку воспроизвел  https://www.hostedredmine.com/issues/957872

**Comment by tormozit** [comment]
Исправлено в 6.63.2
