### ISSUE TITLE
Не проводятся документы с помощью Подбор и обработка объектов БД в 1С Drive

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#35]
**Программное окружение**
Платформа: 8.3.17.1851
Режим БД: файловый
Конфигурация. Название: 1C:Drive, версия 1.3 (1.3.6.5)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: English
Конфигурация. Режим управления блокировкой данных: Managed
Конфигурация. Режим совместимости: Version8_3_14
Инструменты разработчика. Версия: Расширение 6.07.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.07.1e)
Клиент. ОС: Майкрософт Windows 10 Домашняя для одного языка 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

**Воспроизведение проблемы**
1. Открыл инструмент Подбор и обработка объектов БД.
2. Выбрал в поле "Области" поиска таблицу Авансовый отчет (Document.ExpenseReport).
3. На странице "Настройка выборки" нажал кнопку "Заполнить строки".
4. На странице "Обработки" двойным кликом выбрал пункт "Провести документы".
5. В открывшейся форме нажал кнопку "Выполнить". По-умолчанию установлена галка "Пропускать непроведенные".
6. Получил окно с ошибкой:
Обработка объекта DocumentObject.ExpenseReport(Авансовый отчет 0000-000001 от 12.08.2019 ,e7428eb0-1d03-11eb-83fd-0050569f5652)
    {ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(15897)}: {ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(15819)}: Ошибка при вызове метода контекста (Write): Ошибка при выполнении обработчика - 'Posting': {Document.ExpenseReport.ObjectModule(228)}: Ошибка при вызове метода контекста (InitializeAdditionalPropertiesForPosting): Ошибка при вызове серверного метода.: Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.: Ошибка преобразования данных XDTO:
Запись значения свойства 'param':
    форма: Элемент
    имя: {http://v8.1c.ru/8.2/managed-application/modules}param: Ошибка преобразования данных XDTO:
Запись значения свойства 'Value':
    форма: Элемент
    имя: {http://v8.1c.ru/8.1/data/core}Value: Ошибка преобразования данных XDTO:
Запись значения свойства 'Value':
    форма: Элемент
    имя: {http://v8.1c.ru/8.1/data/core}Value: Ошибка преобразования данных XDTO:
Запись значения свойства 'Value':
    форма: Элемент
    имя: {http://v8.1c.ru/8.1/data/core}Value: Ошибка отображения типов:
Отсутствует отображение для типа 'TempTablesManager'
WriteMode: Проведение
Posted: Да
CustomizableNumbering: Structure
Строк обработано - 2, неуспешно - 1, успешно - 1. Объектов обработано - 2, записано автоматически - 0.
Обработка 1 потоков завершено, обработано 2 элементов за 0:00:01 (1 сек). Грубое среднее время обработки элемента - 500 мс

**Ожидаемое поведение**
Ожидал, что все выбранные документы перепроведутся.

**Comment by antonsm2011** [comment]
База 1С Drive полностью типовая, та же самая как здесь - https://github.com/tormozit/RDT1C/issues/34.
Только расширение ИР 6.07.

**Comment by tormozit** [comment]
Судя по "Ошибка передачи данных между клиентом и сервером", код выполняется на клиенте. Если ты умышленно его там выполняешь, то появление такой ошибки допустимо. Включи флажок "Выполнять на сервере".

**Comment by antonsm2011** [comment]
На клиенте выполняю не умышленно.
Это я все делал в файловой базе.

Флажок "Выполнить на сервере" в файловой базе недоступен. Так и задумано?
![2021-08-30_12-23-34](https://user-images.githubusercontent.com/12731230/131318858-bf4939ff-c351-4b7b-8d99-98c0b63216e4.png)

**Comment by antonsm2011** [comment]
Развернул эту же базу на сервере.
Делаю все тоже самое, что написал в первом сообщении.
Флажок "Выполнять на сервере" установлен.
Получаю такую ошибку:
Ошибка через 00:01 фонового задания "Подбор и обработка объектов БД (ИР). Обработка объектов ПровестиДокументы": Тип не определен (DataProcessorОбъект.ирПодборИОбработкаОбъектов)
{ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(19909)}:       ТипОбъекта = Тип(ТипМетаданных + "Объект." + ИмяОбъекта);
{ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(30742)}:           Обработка = СоздатьОбъектПоПолномуИмениМетаданныхЛкс(ПолноеИмяОбработки);

**Comment by antonsm2011** [comment]
**Программное окружение** из серверной базы
Платформа: 8.3.17.1549
Режим БД: клиент-серверный
Конфигурация. Название: 1C:Drive, версия 1.3 (1.3.6.5)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: English
Конфигурация. Режим управления блокировкой данных: Managed
Конфигурация. Режим совместимости: Version8_3_14
Инструменты разработчика. Версия: Расширение 6.07.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.07.1e)
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная НеРусский-0409
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Comment by tormozit** [comment]
> Тип не определен (DataProcessorОбъект.ирПодборИОбработкаОбъектов)
> {ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(19909)}: ТипОбъекта = Тип(ТипМетаданных + "Объект." + ИмяОбъекта);

Ошибку воспроизвел https://www.hostedredmine.com/issues/932589

**Comment by tormozit** [comment]
>     6\. {ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(15897)}: {ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(15819)}: Ошибка при вызове метода контекста (Write): Ошибка при выполнении обработчика - 'Posting': {Document.ExpenseReport.ObjectModule(228)}: Ошибка при вызове метода контекста (InitializeAdditionalPropertiesForPosting): Ошибка при вызове серверного метода.: Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.: Ошибка преобразования данных XDTO:
>         Запись значения свойства 'param':
Требуется ссылка на выгрузку базы.

**Comment by tormozit** [comment]
>     Ошибка при вызове серверного метода.: Ошибка передачи данных между клиентом и сервером

Ошибку воспроизвел. В файловом режиме управляемого приложения есть ряд сложностей с определением необходимости серверного вызова, который там выполняется почти как в клиент-серверном режиме, т.е. с сериализацией параметров. Чтобы их обойти создал задачу https://www.hostedredmine.com/issues/932702 . 
А вот  файловом режиме обычного приложения клиент-серверные вызовы выполняются точно как клиентские, т.е. без сериализации параметров. Поэтому в нем такой ошибки нет.

**Comment by tormozit** [comment]
Первая ошибка исправлена в 6.07.2

**Comment by tormozit** [comment]
Вторая ошибка исправлена в 6.08.1
