### ISSUE TITLE
Открытая консоль запросов съедает место на системном диске 

### ISSUE THREAD

**Issue by FragsterAt** [tormozit/RDT1C#350]
**Программное окружение**

Платформа: 8.3.20.1674
Режим БД: клиент-серверный
Конфигурация. Название: Управленческий учет (1.0.0.73)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим совместимости: Версия8_3_7
Конфигурация. Версия БСП: 2.1.6.20
Инструменты разработчика. Версия: Конфигурация 5.70.3
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 32б
Клиент. Текущий язык системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Выполнил некоторое количество запросов
3. Оставил открытой на ночь (на сисемном диске десятки гигабайт свободного места)
....
5. Места на системном диске нет

**Ожидаемое поведение**
Неуменьшение места на системном диске при отсустствии активности.

**Comment by tormozit** [comment]
Почему такая старая версия? Возможно в те давние времена какая то проблема в коде консоли и была. Проверь на актуальной версии.

**Comment by FragsterAt** [comment]
Обновил до 6.63.2, понаблюдаю

**Comment by tormozit** [comment]
Проблема исчезла?

**Comment by FragsterAt** [comment]
Пока наблюдаю. заметил колебания в пределах пяти гигабайт, но точно ли это от открытых ИР пока не отследил. Если в течение этой недели будет ок, то закрою.

**Comment by FragsterAt** [comment]
Больше не воспроизводится
