### ISSUE TITLE
сделать так, чтобы при двойном клике в форме списка справочника "объекты для отладки" запускалась команда "Отладить"

### ISSUE THREAD

**Issue by FragsterAt** [tormozit/RDT1C#351]
Сделать так, чтобы при двойном клике в ДС в форме списка справочника "объекты для отладки" запускалась команда "Отладить".
Ну реально, как часто нужна форма объекта, особенно если учесть, что xml отображается внизу формы списка?
Для открытия формы объекта можно задействовать кнопку F2, как в БСП для присоединенных файлов.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/958478

**Comment by tormozit** [comment]
Реализовано в 6.65
