### ISSUE TITLE
Ошибка при отладке схемы компоновки данных с внешним источником (ТаблицаЗначений)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#352]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.63.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Есть отчет на СКД, где программно в качестве внешнего источника данных устанавливается Таблица Значений
2. При использовании функции От() и последующей загрузке в ИР выдается ошибка:

![ОтладкаСКД_1](https://user-images.githubusercontent.com/87958986/217584847-b9cb4fc6-01d1-471f-9b18-de7c839799da.png)

**Comment by tormozit** [comment]
Ты передал в функцию От() структуру с этой таблицей?

**Comment by PerlAmutor** [comment]
> Ты передал в функцию От() структуру с этой таблицей?

Макет передал после вызова Инициализировать() перед непосредственным выводом в генератор ДереваЗначений.

**Comment by tormozit** [comment]
Значит не передал. Попробуй таки передать.

**Comment by PerlAmutor** [comment]
Я почему-то думал, что ИР сама умеет определять наличие внешних источников. Как-то я забыл, что там дополнительные параметры надо передавать по примеру:
"НастройкиКомпоновки?, ВнешниеНаборыДанных?,, ПорогОбрезкиВременнойТаблицы?,, МенеджерВременныхТаблиц?"

**Comment by tormozit** [comment]
> ИР сама умеет определять

Может и умеет. Это станет понятно, когда ты сделаешь нормальное описание проблемы - с текстом ошибки, с картинкой вызова функции, с картинкой окна консоли компоновки в момент ошибки.

**Comment by PerlAmutor** [comment]
https://user-images.githubusercontent.com/87958986/217614824-67ca3a98-05b6-487e-ae44-b6802b5dfc40.mp4

[ВнешнийИсточник.zip](https://github.com/tormozit/RDT1C/files/10688577/default.zip)

**Comment by tormozit** [comment]
Макет компоновки данных не содержит информацию о типах полей наборов данных, в частности внешних. Поэтому консоль не может даже создать пустую таблицу с нужными типами, чтобы макет корректно выполнился. Пустую таблицу с нужными колонками она создает только когда есть схема.
