### ISSUE TITLE
Таблица значений. Передать в JSON. Ошибка при сериализации.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#353]
https://user-images.githubusercontent.com/87958986/217607009-efc7f01e-5e1c-4803-b44b-c95ce3240fff.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.63.1p
Инструменты разработчика. Инструмент: Таблица значений
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Консоль запросов
2. Выполнил запрос:
```
ВЫБРАТЬ ПЕРВЫЕ 2
	Т.Ссылка КАК Поле1
ИЗ
	Документ.АвансовыйОтчет КАК Т
```
3. Выгрузил в Таблицу Значений
4. Вызвал команду "В строку JSON"
5. Получил ошибку:

```
Ошибка при вызове метода контекста (ЗаписатьJSON)
{(1)}:ЗаписатьJSON(ЗаписьJSON, Объект)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(16317)}:	Выполнить("ЗаписатьJSON(ЗаписьJSON, Объект)");
{ВнешняяОбработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(1256)}:	Результат = ирОбщий.ОбъектВСтрокуJSONЛкс(Массив, Истина);
по причине:
Передано значение недопустимого типа

```

**Comment by tormozit** [comment]
Исправлю подсказку кнопки на "в строку JSON через массив структур. Допустимы только значения примитивных типов."
