### ISSUE TITLE
Исследовать глобальный контекст. Работа с копиями доступна только в клиент-серверном варианте

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#354]
https://user-images.githubusercontent.com/87958986/217620906-3ec9defc-b6df-43f2-8552-519782c6a9b1.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.63.1p
Инструменты разработчика. Инструмент: Исследователь объектов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Исследователь"
2. Вызвал команду "Глобальный контекст"
3. Нажал "плюс" для раскрытия ветки. Получил ошибку:

![image](https://user-images.githubusercontent.com/87958986/217620803-07441ada-b8b8-492e-9966-80e654998678.png)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/957986

**Comment by tormozit** [comment]
Пробуй исправление в модуле ирОбщий
```
Функция КоличествоЭлементовКоллекцииЛкс(Значение) Экспорт
	// Антибаг платформы 8.3.14+ https://www.hostedredmine.com/issues/957985
	Если Истина
		И ирКэш.ЛиФайловаяБазаЛкс()
		И ирКэш.НомерРежимаСовместимостиЛкс() >= 803014
		И Значение = Вычислить("КопииБазыДанных")
	Тогда
		Возврат 0;
	КонецЕсли;
	Если Не ЛиКоллекцияЛкс(Значение) Тогда
```

**Comment by PerlAmutor** [comment]
Не помогло.

**Comment by tormozit** [comment]
Пробуй там же
```
	Если Истина
		И ирКэш.ЛиФайловаяБазаЛкс()
		И (Ложь
			// Антибаг платформы 8.3.14+ https://www.hostedredmine.com/issues/957985
			Или ирКэш.НомерРежимаСовместимостиЛкс() >= 803014 И ТипЗнч(Значение) = Тип("МенеджерКопийБазыДанных")
			Или ирКэш.НомерВерсииПлатформыЛкс() >= 803023 И ТипЗнч(Значение) = Тип("МенеджерТабличныхПространствБазыДанных"))
	Тогда
		Возврат 0;
	КонецЕсли;
```

**Comment by PerlAmutor** [comment]
Пошло дальше, но потом видимо нарвалось на "особенность" конфигурации ERP:

```
{ОбщийМодуль.ПрослеживаемостьФормыКлиент.Модуль(31,3)}: Переменная не определена (ПрослеживаемостьКлиентПереопределяемый)
		<<?>>ПрослеживаемостьКлиентПереопределяемый.ДанныеСтрокиТаблицыТоварыУведомленияОбОстатках(ДанныеСтрокиТаблицы);
{ОбщийМодуль.ПрослеживаемостьФормыКлиент.Модуль(37,3)}: Переменная не определена (ПрослеживаемостьКлиентПереопределяемый)
		<<?>>ПрослеживаемостьКлиентПереопределяемый.ДанныеОбъектаУведомленияОбОСтатках(ДанныеОбъекта);
{ОбщийМодуль.ПрослеживаемостьФормыКлиент.Модуль(159,20)}: Переменная не определена (ПрослеживаемостьКлиентПереопределяемый)
	ПараметрыПечати = <<?>>ПрослеживаемостьКлиентПереопределяемый.ПолучитьЗаголовокПечатнойФормы(ОписаниеКоманды.ОбъектыПечати);
{ОбщийМодуль.ПрослеживаемостьФормыКлиент.Модуль(184,20)}: Переменная не определена (ПрослеживаемостьКлиентПереопределяемый)
	ПараметрыПечати = <<?>>ПрослеживаемостьКлиентПереопределяемый.ПолучитьЗаголовокПечатнойФормы(ОписаниеКоманды.ОбъектыПечати);
{ОбщийМодуль.ПрослеживаемостьФормыКлиент.Модуль(229,20)}: Переменная не определена (ПрослеживаемостьКлиентПереопределяемый)
	ПараметрыПечати = <<?>>ПрослеживаемостьКлиентПереопределяемый.ПолучитьЗаголовокПечатнойФормы(ОписаниеКоманды.ОбъектыПечати);

```
а потом это
```
{ОбщийМодуль.СобытияФормИСКлиент.Модуль(362,8)}: Переменная не определена (глПодключаемоеОборудованиеСобытиеОбработаноДанные)
		Если <<?>>глПодключаемоеОборудованиеСобытиеОбработаноДанные = Неопределено Тогда
{ОбщийМодуль.СобытияФормИСКлиент.Модуль(578,8)}: Переменная не определена (глПодключаемоеОборудованиеСобытиеОбработаноДанные)
		Если <<?>>глПодключаемоеОборудованиеСобытиеОбработаноДанные = Неопределено Тогда
```

**Comment by tormozit** [comment]
Нужна картинка, а лучше описание новой ошибки в новой заявке.

**Comment by PerlAmutor** [comment]
Доработал конфигурацию ERP, вроде больше ошибок нет. Список наконец развернулся:

![image](https://user-images.githubusercontent.com/87958986/217868583-59088829-1ca0-4d8d-ad72-e4c842d543aa.png)

**Comment by tormozit** [comment]
Я имел ввиду картинку в момент появления ошибки, чтобы я понял в каком виде она выводится.

**Comment by tormozit** [comment]
Снова призываю сделать новую заявку по новой проблеме.

**Comment by tormozit** [comment]
Исправлено в 6.64
