### ISSUE TITLE
Исследователь объектов. Глобальный контекст. Перечисления.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#355]
https://user-images.githubusercontent.com/87958986/217869953-f7d2b60b-47fa-444c-b0f0-fcc6dab05d5a.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.63.1p
Инструменты разработчика. Инструмент: Исследователь объектов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Исследователь объектов
2. Выполнил команду "Глобальный контекст"
3. Попытался раскрыть объект с типом "Перечисление"
4. Получил ошибку:

```
Операции сравнения на больше-меньше допустимы только для значений совпадающих примитивных типов (Булево, Число, Строка, Дата)
{ВнешняяОбработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(438)}:	Если Истина
{ВнешняяОбработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(377)}:	ЗаполнитьДочерниеСтроки(СтрокаДерева);

```

**Comment by tormozit** [comment]
https://www.hostedredmine.com/issues/957999

**Comment by tormozit** [comment]
О, в твоих роликах появилось музыкальное оформление. Стало немного приятнее их смотреть =)
