### ISSUE TITLE
Исследователь объектов. Общие клиентские модули

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#356]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.63.1p
Инструменты разработчика. Инструмент: Исследователь объектов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Исследователь объектов
2. Вызвал команду "Глобальный"
3. Получил ошибки:

```
{ОбщийМодуль.ПрослеживаемостьФормыКлиент.Модуль(31,3)}: Переменная не определена (ПрослеживаемостьКлиентПереопределяемый)
		<<?>>ПрослеживаемостьКлиентПереопределяемый.ДанныеСтрокиТаблицыТоварыУведомленияОбОстатках(ДанныеСтрокиТаблицы);
{ОбщийМодуль.ПрослеживаемостьФормыКлиент.Модуль(37,3)}: Переменная не определена (ПрослеживаемостьКлиентПереопределяемый)
		<<?>>ПрослеживаемостьКлиентПереопределяемый.ДанныеОбъектаУведомленияОбОСтатках(ДанныеОбъекта);
{ОбщийМодуль.ПрослеживаемостьФормыКлиент.Модуль(159,20)}: Переменная не определена (ПрослеживаемостьКлиентПереопределяемый)
	ПараметрыПечати = <<?>>ПрослеживаемостьКлиентПереопределяемый.ПолучитьЗаголовокПечатнойФормы(ОписаниеКоманды.ОбъектыПечати);
{ОбщийМодуль.ПрослеживаемостьФормыКлиент.Модуль(184,20)}: Переменная не определена (ПрослеживаемостьКлиентПереопределяемый)
	ПараметрыПечати = <<?>>ПрослеживаемостьКлиентПереопределяемый.ПолучитьЗаголовокПечатнойФормы(ОписаниеКоманды.ОбъектыПечати);
{ОбщийМодуль.ПрослеживаемостьФормыКлиент.Модуль(229,20)}: Переменная не определена (ПрослеживаемостьКлиентПереопределяемый)
	ПараметрыПечати = <<?>>ПрослеживаемостьКлиентПереопределяемый.ПолучитьЗаголовокПечатнойФормы(ОписаниеКоманды.ОбъектыПечати);

```
а потом это
```
{ОбщийМодуль.СобытияФормИСКлиент.Модуль(362,8)}: Переменная не определена (глПодключаемоеОборудованиеСобытиеОбработаноДанные)
		Если <<?>>глПодключаемоеОборудованиеСобытиеОбработаноДанные = Неопределено Тогда
{ОбщийМодуль.СобытияФормИСКлиент.Модуль(578,8)}: Переменная не определена (глПодключаемоеОборудованиеСобытиеОбработаноДанные)
		Если <<?>>глПодключаемоеОборудованиеСобытиеОбработаноДанные = Неопределено Тогда
```

В первом случае не стояла галочка "Клиент (обычное приложение)" на общем модуле ПрослеживаемостьФормыКлиент.
Второй случай (СобытияФормИСКлиент) сложнее, пришлось прописывать вот так, чтобы заработало, т.к. переменная глПодключаемоеОборудованиеСобытиеОбработаноДанные инициализируется в модуле управляемого приложения:

```
		#Если Не ТолстыйКлиентОбычноеПриложение Тогда
		Если глПодключаемоеОборудованиеСобытиеОбработаноДанные = Неопределено Тогда
			глПодключаемоеОборудованиеСобытиеОбработаноДанные = Новый Соответствие();
		КонецЕсли;
		#Иначе
		глПодключаемоеОборудованиеСобытиеОбработаноДанные = Новый Соответствие();
		#КонецЕсли
```

**Comment by tormozit** [comment]
Покажи на картинке, в каком виде эти ошибки отображались. Желательно целиком окно приложения.

**Comment by PerlAmutor** [comment]
![image](https://user-images.githubusercontent.com/87958986/217888972-a976cef7-aa27-4a13-b276-73ff9bc22c2c.png)

**Comment by tormozit** [comment]
Технически возможность показать наличие общего модуля без его инициации есть. Но ради нее придется очень много переделывать в исследователе и родственных механизмах. Поэтому все таки придется оставить как есть.
