### ISSUE TITLE
Подбор и обработка объектов БД. Связь параметров выбора

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#357]
https://user-images.githubusercontent.com/87958986/218312037-1e610501-1ea9-4512-a66f-76751925c189.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.63.3p
Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Подбор и обработка объектов БД"
2. Выбрал документ
3. Выбрал обработку "Изменить/добавить строку"
4. Открыл форму настройки
5. Попытался выбрать значение реквизита
6. Получил ошибку:

```
Поле объекта не обнаружено (СвязиПараметровВыбора)
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ИзменитьДобавитьСтроку.Форма(940)}:	ИначеЕсли Колонка = ЭлементыФормы.ЗначенияРеквизитов.Колонки.СвязиПараметровВыбора Тогда 

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/958225

**Comment by tormozit** [comment]
Исправлено в 6.64
