### ISSUE TITLE
Консоль управления серверами 1С. СерверАвтономный

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#358]
https://user-images.githubusercontent.com/87958986/218363249-93ef9926-8cc2-4c64-afd4-647c680d4425.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.64.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. При попытке открыть инструмент "Консоль управления серверами 1С" выдается ошибка:

```
Поле объекта не обнаружено (СерверАвтономный)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(23898)}:		СтрокаТаблицыСборок.СерверАвтономный = ИсполняемыйФайл.Существует();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(4990)}:	ирОбщий.ЗаполнитьДоступныеСборкиПлатформыЛкс(ОбработкаРегистрации.СборкиПлатформы,, ОбработкаРегистрации.ТипыComКлассов);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(4976)}:	ОткрытьКонсольСерверов1СЛкс();
{(1)}:ирКлиент.ОткрытьКонсольСерверов1СБезПараметровЛкс()
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(150)}:		Выполнить(СтрокаИнструмента.ПолноеИмя + "()");
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(143)}:	ОткрытьИнструмент(СтрокаИнструмента);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/958346

**Comment by tormozit** [comment]
Исправлено в 6.64.2
