### ISSUE TITLE
Консоль запросов. Некорректно работает "Вынести во временную таблицу" при включенном редактировании

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#359]
**Программное окружение**
Платформа: 8.3.21.1622
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.63.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИмяКомпании (1.1.1.0)
Расширения. зг_ЗУП (1.0.1.7)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открываем консоль запросов
2. Делаем запрос с подзапросами
```
ВЫБРАТЬ
	ЕщеПодзапрос.Поле1 КАК Поле1
ИЗ
	(ВЫБРАТЬ
		Подзапрос.Поле1 КАК Поле1
	ИЗ
		(ВЫБРАТЬ
			1 КАК Поле1) КАК Подзапрос) КАК ЕщеПодзапрос
```
3. Переходим в режим "структура"
4. Переходим на один из подзапросов
5. Жмем "Изменить"
6. Теперь в структуре выполняем "Вынести во временную таблицу"
7. После кнопка "перейти" перестает реагировать и выйти из режима редактирования нельзя, кроме как обходными путями выйдя из самого режима "структура"
8. Так же кнопка "Отменить редактирование элемента структуры запроса" неактивна

**Ожидаемое поведение**

Редактируемым запросом становится вынесенный во временную таблицу запрос, если мы выносим редактируемый запрос.
Или же режим редактирования снимается, если это проблематично определить

**Comment by tormozit** [comment]
Старайся вместо "любой" указывать в первую очередь конкретный и дополнительно можно указывать "любой". 
Картинку покажи.

**Comment by KovAlexey** [comment]
Хорошо.
Выбираю второй вложенный запрос "Подзапрос1"
![изображение](https://user-images.githubusercontent.com/16429518/218952067-13bf41e5-12dc-48e1-9222-507ddfb05b07.png)

Жму "Изменить"

![изображение](https://user-images.githubusercontent.com/16429518/218952108-921477ca-0aaf-4e24-bb72-576d9413e63b.png)

Выношу его во временную таблицу
![изображение](https://user-images.githubusercontent.com/16429518/218952145-62589011-18de-49fc-9d85-fd322f9f5778.png)

В диалоге выбираю "Добавить в текущий пакетный запрос"
![изображение](https://user-images.githubusercontent.com/16429518/218952257-1d0358df-deb3-4188-bf07-8344aae9ab47.png)

Кнопка "Перейти" не работает
Кнопка "Отменить редактирование текущего запроса" недоступна
![изображение](https://user-images.githubusercontent.com/16429518/218952298-dbba436a-ffae-471c-9387-a2fb1af8002b.png)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/958524

**Comment by tormozit** [comment]
Исправлено в 6.65
