### ISSUE TITLE
Консоль запросов. HTML редактор. Комментирование. Различное поведение.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#36]
https://user-images.githubusercontent.com/87958986/131356079-9fa3ec44-d719-4cc2-b5eb-591df7325029.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.07.1e
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.07.1e)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: tcp

</details>

При раскомментировании запроса через комбинацию клавиш Ctrl+Shift+Grey Slash в HTML редакторе последние символы начала комментария не удаляются. При этом если использовать комбинацию Ctrl+Shift+/ (рядом с шифтом), то все нормально. Также это поведение не воспроизводится в обычном поле текста запроса.

**Comment by tormozit** [comment]
ошибку воспроизвел https://www.hostedredmine.com/issues/932582

**Comment by tormozit** [comment]
Исправлено в 6.08.1
