### ISSUE TITLE
Анализ техножурнала. Значение не является значением объектного типа "Назначение"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#360]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.64.1p
Инструменты разработчика. Инструмент: Анализ техножурнала
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Анализ техножурнала
2. Загрузил логи. Перешел на вкладку "Тексты SDBL"
3. Два раза кликнул на значение в колонке "Текст SDBL"
4. Получил ошибку:

![WhatsApp Image 2023-02-16 at 06 23 27](https://user-images.githubusercontent.com/87958986/219260860-c0c5a411-b695-47e6-aecc-1f9186746565.jpeg)

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/958541

**Comment by tormozit** [comment]
Исправлено в 6.64.3
