### ISSUE TITLE
Редактор хранилищ настроек. Преобразование значения к типу Строка не может быть выполнено

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#361]
https://user-images.githubusercontent.com/87958986/219412100-60d7934b-e867-44bd-87ce-bbcd8f4426b4.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.64.1p
Инструменты разработчика. Инструмент: Редактор хранилищ настроек
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл Редактор хранилищ настроек
2. Выбрал настройку с типом "ИсторияПоискаТаблицы"
3. Два раза кликнул на строку и получил ошибку:

```
Преобразование значения к типу Строка не может быть выполнено
{ВнешняяОбработка.ирОбщий.МодульОбъекта(7264)}:	ПредставлениеЗначения = "" + Значение;
{ВнешняяОбработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(288)}:	Результат = ирОбщий.ПредставлениеЗначенияСОграничениемДлиныЛкс(Результат);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(6683)}:			ПредставлениеОбъекта = ЭтаФорма.ПредставлениеОбъектаДанных();
{ВнешняяОбработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(259)}:	ирКлиент.ФормаОбъекта_ОбновитьЗаголовокЛкс(ЭтаФорма);
{ВнешняяОбработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(319)}:		мВычислитьВыражение();
{ВнешняяОбработка.ирИсследовательОбъектов.МодульОбъекта(34)}:		ФормаИсследователя.Открыть();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(900)}:			Результат = ИсследовательОбъектов.ИсследоватьОбъект(Объект, Модально, ТекущееВыражение, ИмяТекущегоСвойства, ПрикрепитьОкно, ВладелецФормы);
{ВнешняяОбработка.ирРедакторХранилищНастроек.МодульОбъекта(400)}:				ирОбщий.ИсследоватьЛкс(текЗначениеНастройки);
{ВнешняяОбработка.ирРедакторХранилищНастроек.МодульОбъекта(354)}:        ОткрытьЗнач(текЗначениеНастройки);
{ВнешняяОбработка.ирРедакторХранилищНастроек.Форма.Форма.Форма(323)}:	ОткрытьЗначНастройки(ТекДанные, ЭлементыФормы.ПанельРазделаНастроек.ТекущаяСтраница.Имя, Исследовать);
{ВнешняяОбработка.ирРедакторХранилищНастроек.Форма.Форма.Форма(330)}:	ОткрытьТекНастройку();

```

Другие типы настроек вроде бы преобразовывает к строке нормально.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/958574

**Comment by tormozit** [comment]
Исправлено в 6.65
