### ISSUE TITLE
Предложение. Список баз как отдельный инструмент.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#362]
В инструменте "Управления Профайлами" есть форма списка баз:

![image](https://user-images.githubusercontent.com/87958986/220004214-4889dfe5-dff9-4231-bec5-bfb267bbee26.png)

Полезные команды типа "Выгрузка DT" или выгрузка в XML, выгрузка Модулей конфигурации "разбросаны" по различным инструментам. Хотелось бы эту форму видеть как отдельный инструмент на главной панели. Я часто работаю со списком баз при обновлении релизов и не хватает в одном месте таких команд как:
- Загрузка/Выгрузка CF/DT файлов (из/в XML в основном)
- Создание файловых баз сразу через из XML посредством вызова ibcmd:
// Создание файловой базы из каталога с XML
`ibcmd infobase create --db-path="E:\1C\ФайловыеБазы\ERP_2_5_8_309_2_5_8_321" --db-name="ERP_2_5_8_309_2_5_8_321" --create-database --import="E:\git_conf_update_258_309_321\src"`
// Экспорт конфигурации в XML из файловой базы
`ibcmd infobase config export --db-path="E:\1C\ФайловыеБазы\ERP_2_5_8_342_КонфигурацияПоставщика" --db-name="ERP_2_5_8_342_КонфигурацияПоставщика" "E:\1C\ВыгрузкиXML\ERP258342"`
// Создание файловой базы из CF файла
`ibcmd infobase create --db-path="E:\1C\ФайловыеБазы\ERP_2_5_8_342_КонфигурацияПоставщика" --db-name="ERP_2_5_8_342_КонфигурацияПоставщика" --create-database --load="G:\1С\ERP_258_342_КонфигурацияПоставщика.cf"`
// Экспорт конфигурации в CF файл из файловой базы
`ibcmd infobase config save -c "E:\1C\ФайловыеБазы\ERP_2_5_8_295_2_5_8_309.yml" "E:\1C\ФайловыеБазы\ERP_2_5_8_295_2_5_8_309.cf"`

Было бы неплохо добавить команды для работы с git. Например инициализация локального репозитория git на основе выгрузки XML файлов из конкретной базы.

**Comment by tormozit** [comment]
Пока сделаю для собственной базы https://www.hostedredmine.com/issues/959751

**Comment by tormozit** [comment]
Для собственной базы реализовано в 6.68.1
