### ISSUE TITLE
Пожелание. Консоль запросов. Добавить команду скрытия списка запросов с параметрами.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#363]
В консоли запросов хотелось бы команду аналогичную команде "Результат", но которая бы скрывала верхнюю часть с запросом освобождая место для результата запроса (как это сделано для Таблицы Значений, команда "Колонки")

https://user-images.githubusercontent.com/87958986/220240145-c5776344-6bbf-4c80-8289-ea3166f6c3e1.mp4

https://user-images.githubusercontent.com/87958986/220240160-23098440-5cbd-4437-a601-ec413fb84553.mp4

**Comment by tormozit** [comment]
В командной панели результата запроса есть кнопка "Открыть копию коллекции в отдельном окне". Чем она не устраивает?

**Comment by tormozit** [comment]
Необходимость перемещать второй (верхний) разделитель является ошибкой https://www.hostedredmine.com/issues/958786

**Comment by tormozit** [comment]
Исправлено в 6.65.2
