### ISSUE TITLE
Недопустимый вызов объекта на клиенте

### ISSUE THREAD

**Issue by Absolemus** [tormozit/RDT1C#364]
**Программное окружение**

Бухгалтерия 3.0
ИР 6.67.1
Платформа (8.3.18.1779)

**Воспроизведение проблемы**
1. Открыл любой инструмент
2. Получил окно с ошибкой ВВВ

![image](https://user-images.githubusercontent.com/20809734/223037021-56b493bf-7192-4baa-aec9-073574954a9e.png)

![image](https://user-images.githubusercontent.com/20809734/223037045-41333c9c-1a86-4ffe-bf11-9fc2a88210fa.png)

**Ожидаемое поведение**
Не получил окно с ошибкой

**Comment by tormozit** [comment]
Полный текст ошибки хорошо бы вставлять. Ошибку воспроизвел https://www.hostedredmine.com/issues/959493 . Исправлено в 6.67.2

**Comment by Absolemus** [comment]
@tormozit, да, ты прав, я запомню это.
Спасибо
