### ISSUE TITLE
От(). Отладка без расшаренной сетевой папки

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#365]
Предложение.
В функции От() создавать .deb файл во временном каталоге на сервере, записывать имя файла в Системное Хранилище Общих Настроек. При вызове инструмента "Отладить отложенный объект" показывать форму со списком отложенных предметов отладки взятый из хранилища настроек. При выборе строки - скачивать файл из временного каталога на сервере во временный каталог на клиенте. А дальше уже по старой схеме.
Это избавит сразу от двух неудобств:
а) не будет необходимости просить админов расшаривать сетевой каталог и настраивать права
б) отпадет необходимость копирования текста в буфер обмена с последующей вставкой

**Comment by tormozit** [comment]
Отлаживаемый процесс может быть на одном рабочем сервере кластера, а сеанс ИР - на другом. Тогда доступа к сохраненному таким образом файлу не будет у сеанса ИР.

**Comment by PerlAmutor** [comment]
Тогда остается использовать регистр типа БезопасноеХранилищеДанных из БСП, помещать данные в него... Правда файлы отладки бывают по 10Гб и больше, база замусорится...
