### ISSUE TITLE
Редактор изменений на узлах. ОбластьДанныхОсновныеДанные

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#367]
https://user-images.githubusercontent.com/87958986/224103989-8114266b-c161-4a26-bd6b-974b0ee77aeb.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.67.1p
Инструменты разработчика. Инструмент: Редактор изменений на узлах
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. При попытке изменить регистрацию (добавление/удаление) в инструменте "Редактор изменение на узлах", где присутствует поле "ОбластьДанныхОсновныеДанные" (Изменения РегистровСведений, РегистровНакоплений) возникает ошибка:

```
Поле объекта не обнаружено (ОбластьДанныхОсновныеДанные)
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(687)}:			ЭлементОтбора = мМакетныйОбъект.Методы.Отбор[Колонка.Имя];
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(1410)}:	СтруктураОбъекта = ПолучитьОбъектДанныхПоСтрокеИзменений();

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/959750

**Comment by tormozit** [comment]
Исправлено в 6.67.4
