### ISSUE TITLE
Редактор изменений на узлах. ПолноеИмяТаблицы

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#368]
https://user-images.githubusercontent.com/87958986/224106835-aaab5c1f-1e1b-4ee5-b006-cd52c8edf221.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.67.1p
Инструменты разработчика. Инструмент: Редактор изменений на узлах
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл "Редактор изменений на узлах"
2. Выбрал 2 записи
3. Вызвал команду "Передать в инструмент "Подбор и обработка объектов""
4. Открылся Диалог, выбрал вариант "Нет", получил ошибку:

```
Поле объекта не обнаружено (ПолноеИмяТаблицы)
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ПодборИОбработка.Форма(2167)}:			ПолноеИмяМД = КлючЗаписи.ПолноеИмяТаблицы;
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ПодборИОбработка.Форма(1331)}:		ЗагрузитьСтрокиДляОбработки(ирОбщий.РазличныеЗначенияМассиваЛкс(ПараметрМассивСсылок),, ПараметрВыбранныеПоля, Истина);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(12500)}:	Форма.Открыть();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(12323)}:	ОткрытьМассивОбъектовВПодбореИОбработкеОбъектовЛкс(МассивСсылок,, ЭтаФорма,, КлючТекущейСтроки);
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(1950)}:	ирКлиент.ОткрытьОбъектыИзВыделенныхЯчеекВПодбореИОбработкеОбъектовЛкс(ЭлементыФормы.ТаблицаИзменений,, ЭтаФорма, ЭлементыФормы.ДеревоТаблиц.ТекущаяСтрока.ПолноеИмя);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/959714

**Comment by tormozit** [comment]
Исправлено в 6.67.4
