### ISSUE TITLE
Просмотр длины строки в форме "Обработка.ирПлатформа.Форма.Текст"

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#369]
Сейчас это достигается через флажок "Только просмотр". Я бы никогда не догадался нажимать его для просмотра длины.

Почему бы не открывать это окно сразу с показом длины в заголовке? Я часто открываю в этом окне многострочные строки и где-то в одном случае из десяти мне было бы полезно знать длину такой строки.

Если причина в невозможности отследить начало редактирования текста, то это единственный сдерживающий фактор?

**Comment by tormozit** [comment]
У поля текстового документа обычной формы невозможно оперативно отследить изменение длины текста кроме как очень часто выполняющимся обработчиком ожидания. Подключать такой высокочастотный обработчик не хочется ради такой редко полезной возможности (видеть длину текста). Поэтому и отображать длину в отдельном поле тоже не хочется, т.к. при отсутствии оперативного обновления при редактировании она там будет часто неактуальной. Поэтому была выбрана текущая неочевидная реализация отображение длины в заголовке окна при включенном флажке "Только просмотр". Ведь при этом есть гарантия что отображаемая длина соответствует реальной.

Попробую придумать какое то улучшение.

**Comment by john-doe-1c** [comment]
Как насчет переделать форму на управляемую?

**Comment by tormozit** [comment]
Форма достаточно сложная. В ней применяются сложные интерфейсные компоненты, которых не поддерживают управляемые формы. Объем работы будет довольно большой и не сопоставим с пользой.

**Comment by tormozit** [comment]
Есть много веских причин НЕ использовать управляемую форму.

**Comment by john-doe-1c** [comment]
Сразу при открытии показывать в заголовке "замороженную" длину (которая не будет обновляться пока не переткнешь флажок "Только просмотр") тоже не хочешь?

**Comment by tormozit** [comment]
Считаю, что показывать неактуальную информацию без пояснения правил ее актуализации вреднее чем не показывать ее вовсе.

**Comment by john-doe-1c** [comment]
Может тогда открывать форму в режиме просмотра, а над полем ввода текста разместить поясняющую надпись:
`Только просмотр: Да. Для редактирования снимите флажок такой-то.`
?
Или открывать все как обычно, показывать в заголовке длину, а над тем же самым полем редактирования разместить надпись:
`Длина строки в заголовке окна не обновляется при редактировании содержимого. Для обновления длины нажмите флажок такой-то.`
.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/960173

**Comment by tormozit** [comment]
Реализовано в 6.68
