### ISSUE TITLE
Редактор объекта БД, просмотр содержимого ТЧ: различные значения колонки

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#370]
Хочу это команду в командной панели над содержимым ТЧ, а не в подменю "Текущая таблица", т.к. весьма часто пользуюсь ею.

**Comment by tormozit** [comment]
Используй сочетание клавиш ALT+F или глобальное меню.

**Comment by john-doe-1c** [comment]
Так а в саму командную панель почему бы не добавить?

**Comment by tormozit** [comment]
Я стараюсь без оснований не добавлять кнопки в командные панели, т.к. они итак содержат очень много кнопок в среднем. Поэтому нужно обосновать, почему нужная тебе кнопка нужна именно в командной панели. Если ты часто пользуешься, то сочетание клавиш - оптимальный способ вызова команды.

**Comment by john-doe-1c** [comment]
Вот бы это сочетание еще в остальных формах, где есть эта команда, работало.
В дин. списке оно например уже не работает.
А в ИР еще где-то есть формы где эта команда скрыта, но ее можно вызывать такой горячей клавишей?
Я таких мест вспомнить навскидку не смог, поэтому запоминать это сочетание будет неудобно. Т.е. везде в таблицах я пользуюсь этой командой через кнопку и поэтому сочетание для редактора объекта БД я вскоре все равно забуду и снова стану визуально искать привычную кнопку.

**Comment by john-doe-1c** [comment]
Дин. список, поиск битых ссылок, консоль запросов, загрузка табличных данных, сравнение таблиц, анализ ТЖ - везде там где у таблицы есть возможность отобрать по текущему значению / без текущего значения, есть и заветная кнопка. Они для меня всегда образуют единый блок.
Поэтому и наш случай не должен становиться исключением.

**Comment by tormozit** [comment]
> В дин. списке оно например уже не работает.

В управляемой форме "Динамический список (ИР)" сочетание перекрыто платформой на команду поиска. Поэтому там рассматриваемой команде ИР не назначено сочетание. В остальных формах сочетание одинаковое. 

В подменю команды убираются, когда их становится слишком много в одной командной панели.

**Comment by john-doe-1c** [comment]
> В подменю команды убираются

Но не лидеров по частоте использования же убирать...

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/962719

**Comment by john-doe-1c** [comment]
А почему "Закрыто"?

**Comment by tormozit** [comment]
Думаю здесь больше не возникнет вопросов. Ты можешь открыть заявку кнопкой "Reopen" если требуется.

**Comment by john-doe-1c** [comment]
Не вижу такой кнопки. А где-то вообще описана твоя политика работы с заявками? Кто когда и что может и не может с ними делать.

**Comment by tormozit** [comment]
Видимо кнопка "Reopen" есть только у меня. Политика не описана и описывать я ее не планирую. Все права тут стандартные от поставщика сервиса github. Заявитель может писать в свои заявки даже после их закрытия. При необходимости разработчик открывает заявку повторно.

**Comment by john-doe-1c** [comment]
> Все права тут стандартные от поставщика сервиса github

А я не про права на сайте спрашиваю, а про твою этику / философию работы с заявками. Например, в части их закрытия - когда они закрываются, кем, по каким событиям.

**Comment by tormozit** [comment]
Реализовано в 6.74

**Comment by tormozit** [comment]
Проверил. Кнопка "Reopen" всегда есть у автора заявки. Ищи лучше.

**Comment by tormozit** [comment]
Закрывают заявку, когда по оценке разработчика она исчерпана. Это помогает держать список открытых заявок был небольшим и потому с ним удобно работать. Заявитель может в ней дальше писать. Если станет понятно, что требуется участие разработчика снова, он откроет заявку снова.
