### ISSUE TITLE
Дин. список, команда "Колонки": брать порядок из метаданных

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#371]
Хочу иметь возможность разместить колонки дин. списка слева направо в порядке реквизитов, как он задан в дереве метаданных (сверху вниз). Сейчас в форме настройки колонок есть возможность, как я понял, взять этот порядок только из формы списка?

**Comment by tormozit** [comment]
Да

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/960171

**Comment by tormozit** [comment]
Реализовано в 6.68
