### ISSUE TITLE
Консоль запросов. "Заменить литералами" перестала работать.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#372]
https://user-images.githubusercontent.com/87958986/225193155-0f6d75d1-d657-41b5-b2a5-155f011ce8d5.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.67.5p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**

Команда Консоли Запросов - " \ Панель \ Параметры(0) \ Командная панель \ Заменить литералами" перестала подставлять удаленный параметр в текст запроса.

![image](https://user-images.githubusercontent.com/87958986/225193555-984cb45a-eb13-4415-b292-bb235f6328aa.png)

```
ВЫБРАТЬ
	ПриобретениеТоваровУслуг.Ссылка КАК Ссылка
ИЗ
	Документ.ПриобретениеТоваровУслуг КАК ПриобретениеТоваровУслуг
ГДЕ
	ПриобретениеТоваровУслуг.ХозяйственнаяОперация = &ХозяйственнаяОперация
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/959972

**Comment by tormozit** [comment]
Исправлено в 6.67.6
