### ISSUE TITLE
Структура хранения БД. Поведение окна

### ISSUE THREAD

**Issue by Pufilov** [tormozit/RDT1C#373]
**Программное окружение**
Платформа: 8.3.16.1502
Режим БД: клиент-серверный
Конфигурация. Название: Самопал (1.22.09.15)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_2_16
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 6.67.6p
Инструменты разработчика. Инструмент: **Структура хранения БД**
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс

https://user-images.githubusercontent.com/88433411/225310556-a6d0f8a1-32b3-4160-82d7-d71f6bc7ce48.mp4

В окне когда переходишь по колонкам то, начиная с колонки индексы, типа появляется и скрывается какой-то невидимый столбец. В видео пример отображения. Появислоь релиза после 61 наверное. Терпеливо ждал - вдруг "фича", ан нет. Примечательно что при перемещении по колонкам одного ряда все ок. Если переходить после колонки "Индекс" по рядам то уже все - артефакты так сказать.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/960021

**Comment by tormozit** [comment]
Исправлено в 6.67.7
