### ISSUE TITLE
Консоль запросов. Краш системы при заполнении параметра

### ISSUE THREAD

**Issue by Pufilov** [tormozit/RDT1C#374]
**Программное окружение**
Платформа: 8.3.16.1502
Режим БД: клиент-серверный
Конфигурация. Название: Самопал (1.22.09.15)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_2_16
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 6.67.6p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс

**Воспроизведение проблемы**
1. готовим запрос, определяем параметр
2. устанавливаем значение паараметра не через форму подбора, а вводим в строку начало наименования
3. после энтера крашится система
![image](https://user-images.githubusercontent.com/88433411/225348057-e159b9e4-a97c-45a8-a5fb-44d905d770b9.png)

**Ожидаемое поведение**
Заполненный параметр как в релизе 6.61.1p.
В релизе 6.62.2p замечено улучшение (фича) по заполнению параметра при вводе не из формы подбора а при вводе строки.
С релиза 6.64.1p и дальше тоже система крашится при вводе из строки, при выборе из формы подбора - все ок

**Comment by tormozit** [comment]
Нужна картинка в момент появления ошибки, чтобы была видна таблица параметров и особенно текущая строка таблицы

**Comment by Pufilov** [comment]
![image](https://user-images.githubusercontent.com/88433411/225438647-79f3197e-ec9d-4149-b603-fda127d7a346.png)

**Comment by Pufilov** [comment]
Ошибка получается если вводить по Наименованию. Если по коду - все отлично заполняется в параметре.

**Comment by tormozit** [comment]
Перед появлением ошибки остановись в процедуре ирОбщий.ТаблицаДанныхВыбораМенеджераЛкс на строке
`ТаблицаРезультата = Запрос.Выполнить().Выгрузить();`
И покажи текст запроса.

**Comment by Pufilov** [comment]
ВЫБРАТЬ ПЕРВЫЕ 51
	Т.Ссылка КАК Ссылка,
	Т.ПометкаУдаления КАК ПометкаУдаления,
	Т.ЭтоГруппа КАК ЭтоГруппа,
	Т.Код КАК Код,
	Т.Наименование КАК Наименование
ИЗ
	Справочник.Контрагенты КАК Т
ГДЕ
	(Т.Наименование ПОДОБНО &П СПЕЦСИМВОЛ "/"
				И Т.Наименование ПОДОБНО &П2 СПЕЦСИМВОЛ "/"
			ИЛИ Т.Код = &П3)
УПОРЯДОЧИТЬ ПО
	Наименование = &СтрокаПоиска УБЫВ,
	Код = &ЧислоПоиска УБЫВ,
	Наименование ПОДОБНО &СтрокаПоиска + "%" УБЫВ,
	Ссылка
АВТОУПОРЯДОЧИВАНИЕ

**Comment by tormozit** [comment]
Попробуй в консоли запросов выполнить запрос. Возникнет ли та же ошибка? 
```
ВЫБРАТЬ
Т.Ссылка 
ИЗ
Справочник.Контрагенты КАК Т
ГДЕ ЛОЖЬ
УПОРЯДОЧИТЬ ПО
Код = &ЧислоПоиска УБЫВ
АВТОУПОРЯДОЧИВАНИЕ
```

**Comment by Pufilov** [comment]
Сам запрос в 1С отрабатывается нормально, но там П3 и ЧислоПоиска числового типа. а в процедуре параметры П3 и ЧислоПоиска = Неопределено

**Comment by tormozit** [comment]
Что есть ПЗ?

**Comment by Pufilov** [comment]
> Попробуй в консоли запросов выполнить запрос. Возникнет ли та же ошибка?
> 
> ```
> ВЫБРАТЬ
> Т.Ссылка 
> ИЗ
> Справочник.Контрагенты КАК Т
> ГДЕ ЛОЖЬ
> УПОРЯДОЧИТЬ ПО
> Код = &ЧислоПоиска УБЫВ
> АВТОУПОРЯДОЧИВАНИЕ
> ```

тут все отлично, ошибок нет

**Comment by Pufilov** [comment]
![image](https://user-images.githubusercontent.com/88433411/225448102-4884c4f4-60ed-40d0-89c1-e46c2e102c98.png)

**Comment by tormozit** [comment]
Правильно я понял, что запрос 
```
ВЫБРАТЬ Т.Ссылка ИЗ Справочник.Контрагенты КАК Т
ГДЕ ЛОЖЬ
УПОРЯДОЧИТЬ ПО
Код = &ЧислоПоиска УБЫВ
АВТОУПОРЯДОЧИВАНИЕ
```
С параметром ЧислоПоиска = Неопределено в консоли запросов выполняется без ошибки?

**Comment by Pufilov** [comment]
Этот запрос после определения параметров приводи параметр к типу число
![image](https://user-images.githubusercontent.com/88433411/225448895-1d53f3ab-2552-48ad-93dd-16751e36b99d.png)
и все отлично, без ошибок

**Comment by tormozit** [comment]
Пробуй добавить такую правку
```
			Иначе**Если ЧислоПоиска <> Неопределено Тогда**
				НайтиДобавитьЭлементОтбораКомпоновкиЛкс(ГруппаИли, ПолеПоискаПоСтроке.Имя, ЧислоПоиска, ВидСравненияКомпоновкиДанных.Равно,, Ложь);
				ТекстСортировки.Добавить(ПолеПоискаПоСтроке.Имя + " = &ЧислоПоиска УБЫВ");
```

**Comment by Pufilov** [comment]
А вот когда параметр добавить руками, без указания типов
![image](https://user-images.githubusercontent.com/88433411/225449167-f983be27-9b20-4d0b-9b8c-3d2958be792b.png)
то все валится :)

**Comment by Pufilov** [comment]
> Если ЧислоПоиска <> Неопределено Тогда

все отлично. работает без вылетов

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/960050

**Comment by tormozit** [comment]
Исправлено в 6.67.7
