### ISSUE TITLE
Управление профайлами. Список Баз Пользователя ОС. Тормозит прокрутка списка баз

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#375]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.67.6p
Инструменты разработчика. Инструмент: Обработка.ирПлатформа.Форма.СписокБазПользователяОС
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Управления профайлами"
2. Нажал кнопку выбора списка баз (поле База)
3. При любой прокрутке окна или смены строки мышкой все табличное поле списка сильно неторопливо перерисовывается

**Comment by tormozit** [comment]
Не воспроизводится. Нужен замер производительности.

**Comment by PerlAmutor** [comment]
Держи

[ИР_СписокБазПрокрутка.zip](https://github.com/tormozit/RDT1C/files/10997707/_.zip)


![image](https://user-images.githubusercontent.com/87958986/225809270-4c4a551c-6a96-4450-ac6c-58ba8bf46839.png)

![image](https://user-images.githubusercontent.com/87958986/225809523-9348dbed-df67-4303-b762-68d735118cb5.png)

**Comment by tormozit** [comment]
Проблему воспроизвел https://www.hostedredmine.com/issues/960052

**Comment by tormozit** [comment]
Исправлено в 6.68.1
