### ISSUE TITLE
Консоль запросов. Передать ссылки для обработки

### ISSUE THREAD

**Issue by Pufilov** [tormozit/RDT1C#376]
**Программное окружение**
Платформа: 8.3.16.1502
Режим БД: файловый
Конфигурация. Название: Управление торговым предприятием для Украины, редакция 1.2 (1.2.68.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_2_13
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 6.67.6p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

**Воспроизведение проблемы**
1. Выполняем запрос
2. Нажимаем кнопку "Передать ссылки..."
3. Получаем ошибку
![image](https://user-images.githubusercontent.com/88433411/225558430-18739567-5626-475a-8cf6-dab82d7feeda.png)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(11532)}: Таблица БД с именем "" не найдена
		ВызватьИсключение "Таблица БД с именем """ + ПолноеИмяТаблицыБД + """ не найдена";

**Ожидаемое поведение**
Какая в релизе ИР_Портативный 6.61.1p - все работает

**Comment by tormozit** [comment]
https://www.hostedredmine.com/issues/960047

**Comment by tormozit** [comment]
Исправлено в 6.67.7
