### ISSUE TITLE
Ошибка из-за отсутствия подсистемы "Подключаемые команды"

### ISSUE THREAD

**Issue by VZhulanov1** [tormozit/RDT1C#377]
Платформа: 8.3.20.1710
Режим БД: клиент-серверный
Конфигурация. Название: Фарм Капитан (2.115)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_18
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Инструменты разработчика. Версия: Конфигурация 6.65.2
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows 7 Максимальная  64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс
Сервер. ОС: Microsoft Windows 7 Максимальная  64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Редактор объекта БД
2. Выбрал таблицу - один из справочников.
3. Открываю форму списка справочника для выбора элемента. Получаю ошибку в окне сообщений.
4. Открылась форма выбора справочника (не универсальная из ИР). Дальше все работает

Ошибка:
Ошибка динамического списка ИР: {Обработка.ирДинамическийСписок.Форма.ФормаУпр.Форма(340)}: Ошибка компиляции при вычислении выражения или выполнении фрагмента кода: {<Неизвестный модуль>(1,1)}: Переменная не определена (ПодключаемыеКоманды)

Подсистема Подключаемые команды у меня не интегрирована

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/960143

**Comment by tormozit** [comment]
Исправлено в 6.67.7
