### ISSUE TITLE
у интерфейса ирРазработчик не установлено свойство Переключаемый

### ISSUE THREAD

**Issue by VZhulanov1** [tormozit/RDT1C#379]
**Программное окружение**

Платформа: 8.3.20.1710
Режим БД: клиент-серверный
Конфигурация. Название: Фарм Капитан (2.115)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_18
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Инструменты разработчика. Версия: Конфигурация 6.67.7
Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows 7 Максимальная 64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс
Сервер. ОС: Microsoft Windows 7 Максимальная 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. у интерфейса ирРазработчик не установлено свойство Переключаемый
2. под свои нужны приходится его устанавливать, так удобнее получается

**Ожидаемое поведение**
Если можно, то установите это свойство в поставке инструмента

**Comment by tormozit** [comment]
Непонятно в чем удобство

**Comment by VZhulanov1** [comment]
Могу быстро переключаться на этот интерфейс из своего интерфейса
![image](https://user-images.githubusercontent.com/128121602/226159388-2aa95614-3d58-425a-87b5-aafbdf2f5dfe.png)

**Comment by VZhulanov1** [comment]
интерфейс ИР мне нужен раз в неделю бывает или реже и поэтому я на него переключаюсь только когда это необходимо
да и то доступ к основным инструментам сделан еще быстрее, даже переключаться не приходится

**Comment by tormozit** [comment]
Такое делать не буду, т.к. это создаст сложности в других сценариях использования.
