### ISSUE TITLE
Ошибки в работе "Загрузка табличных данных (ИР)"

### ISSUE THREAD

**Issue by kibor-mail** [tormozit/RDT1C#38]
**Программное окружение**
Платформа: 8.3.17.1851
Режим БД: файловый
Конфигурация. Название: Бухгалтерия предприятия, редакция 3.0 (3.0.96.35)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.07.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. СинхронизацияДанныхСUTM5Плюс (1.03)
Расширения. ИнструментыРазработчикаTormozit (6.07.1e)
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

**Воспроизведение проблемы**
1. Открыл инструмент "Загрузка табличных данных (ИР)";
2. Загрузил сохранённую ранее настройку "настройка ОС 10.sxl";
3. На закладке "Конвертация значений" нажал кнопку редактирования алгоритма;
4. Получил окно с ошибкой
"{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(192)}: Индекс находится за границами массива
						СтрокаПараметра.ИмяТипазначения = СтрокаВнешнегоПараметра.ТаблицаСтруктурТипов[0].ИмяОбщегоТипа;"

**Ожидаемое поведение**
Открытие окна редактирования алгоритма

![Снимок1](https://user-images.githubusercontent.com/89959554/131782531-f9503042-a881-43d8-8877-3c5659796e3d.JPG)
![Снимок2](https://user-images.githubusercontent.com/89959554/131782535-1a98a593-6865-4dbf-8c72-4bbb843babde.JPG)

Также до этого при выполнении отбора на закладке "Таблица значений - ТЗ" очищались значения почти всех колонок, потому что в Компоновщике НастройкаКомпоновки.Выбор.Элементы было только два элемента со значением "Использование = Истина". Хотя должны быть все. И в режиме предприятия это никак не поменять.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932707
По проблеме очистки колонок прошу создать отдельную заявку.

**Comment by kibor-mail** [comment]
> Ошибку воспроизвел https://www.hostedredmine.com/issues/932707

Настройка была сделана в "Расширение 6.03.1e".
[настройка ОС 10.zip](https://github.com/tormozit/RDT1C/files/7096227/10.zip)

**Comment by tormozit** [comment]
Исправлено в 6.07.2
