### ISSUE TITLE
ирОбщий.ИзменитьРегистрациюОбъектаДляУзлаЛкс параметр НомерВерсииПлатформы

### ISSUE THREAD

**Issue by VZhulanov1** [tormozit/RDT1C#380]
**Программное окружение**

Платформа: 8.3.20.1710
Режим БД: клиент-серверный
Конфигурация. Название: Фарм Капитан (2.115)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_18
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Инструменты разработчика. Версия: Конфигурация 6.67.7
Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows 7 Максимальная 64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс
Сервер. ОС: Microsoft Windows 7 Максимальная 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
в модуле ирОбщий процедура ИзменитьРегистрациюОбъектаДляУзлаЛкс
последний параметр НомерВерсииПлатформы можно не задавать и тогда он будет равным ""
но в коде идет проверка Если НомерВерсииПлатформы = Неопределено Тогда 

**Ожидаемое поведение**
сейчас я данную процедуру из своего кода не вызываю, но раньше (на старых версиях) вызывал и получал ошибку в этом месте
заменил условие на Если Не ЗначениеЗаполнено(НомерВерсииПлатформы) Тогда

у меня в заметках по обновлению ИР написано что и где надо поменять при обновлении
но причина (текст ошибки) не приведена
теперь вот решил заявки по этим корректировкам создать

**Comment by tormozit** [comment]
Да. Это спящая ошибка. Исправлю.

**Comment by tormozit** [comment]
Исправлено в 6.68
