### ISSUE TITLE
Некорректное отображение формы консоли запросов в толстом клиенте.

### ISSUE THREAD

**Issue by Spakus** [tormozit/RDT1C#381]
[**Программное] окружение**
https://disk.yandex.ru/d/8Yq3Dar5Q1v_EQ
https://disk.yandex.ru/d/zwXHy71NDoRQRw

Описание ошибки.
При открытии консоли запросов в толстом клиенте, некорректно отрабатывают привязки.
При чем привязки отрабатывают некорректно только при использовании экрана ноутбука.
При подключении к ноутбуку внешнего монитора и использовании его в качества основного, привязки отрабатывают корректно.

**Воспроизведение проблемы**
Работа на ноутбуке без внешнего монитора.
1. Подключился к удаленному рабочему столу.
2. Открыл сеанс в режиме "Толстый клиент".
3. Открыл внешнюю обработку "ирПортативный".
4. Открыл инструмент "Консоль запросов".
5. Получил окно с некорректными привязками.

**Ожидаемое поведение**
При открытии консоли запросов привязки отрабатывают корректно.

Вложения:
https://disk.yandex.ru/i/vgmFQ5bUfOz1OA
https://disk.yandex.ru/i/8e72u7KxvSJrVQ
https://disk.yandex.ru/i/rRpp0kubFW2ogQ
https://disk.yandex.ru/i/Wk7N-r5XEG35Xg

**Comment by tormozit** [comment]
Из-за ошибок обработки привязок в платформе, они иногда ломаются и поломка может сохраняться в настройках пользователя. Чтобы починить их, пробуй рецепт описанный в подсказке флажка "Пакет" в форме конструктора запроса ИР:
"Восстановить положение окна" (Alt+Shift+R), максимизируйте и восстановите его размеры.

**Comment by Spakus** [comment]
Не совсем понял, где описан рецепт, но восстановление положение окна и дальнейшая его максимизация не помогла.

**Comment by tormozit** [comment]
Попробуй развернуть панель "Свойства" одноименной кнопкой-переключателем и затем закрыть и окно.

**Comment by Spakus** [comment]
> Попробуй развернуть панель "Свойства" одноименной кнопкой-переключателем и затем закрыть и окно.

Помогло, спасибо!!!
