### ISSUE TITLE
Тестирование метаданных. Транзакция не активна

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#382]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.68.1p
Инструменты разработчика. Инструмент: Тестирование метаданных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

![image](https://user-images.githubusercontent.com/87958986/226963960-e1e7c20b-9f60-492f-975d-f400dc725b4d.png)

**Воспроизведение проблемы**
1. Запустил инструмент Тестирование метаданных на Демо-конфигурации 1С:ERP Управление предприятием 2 (2.5.8.369)
2. Получил окно с ошибкой:

```
Ошибка при вызове метода контекста (ОтменитьТранзакцию)
{ВнешняяОбработка.ирТестированиеМетаданных.МодульОбъекта(180)}:			ОтменитьТранзакцию();
{ВнешняяОбработка.ирТестированиеМетаданных.Форма.Форма.Форма(647)}:		ГлобальныйТестОбъектов(ЭтаФорма);
по причине:
Транзакция не активна

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/960972

**Comment by tormozit** [comment]
Исправлено в 6.69.1
