### ISSUE TITLE
Тестирование метаданных. Значение не является значением объектного типа (Методы)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#383]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.68.1p
Инструменты разработчика. Инструмент: Тестирование метаданных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

![image](https://user-images.githubusercontent.com/87958986/226965522-2d007ffd-7929-45f0-8b4b-96149f477e6a.png)

**Воспроизведение проблемы**
1. В инструменте Тестирование метаданных при тестировании справочника ДоговорыКонтрагентов фиксируется такая ошибка:

```
Значение не является значением объектного типа (Методы)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(952)}:		ИмитаторОбъекта = СтруктураОбъекта.Методы;
{ВнешняяОбработка.ирТестированиеМетаданных.МодульОбъекта(213)}:	СнимокОбъекта = ирОбщий.СнимокОбъектаЛкс(СтруктураОбъекта.Методы);
{ВнешняяОбработка.ирТестированиеМетаданных.МодульОбъекта(130)}:										ПроверитьСсылочныйОбъект(КопияОбъекта, ИмяОперации, СтрокаТипаМетаданных.Единственное, Истина);
{ВнешняяОбработка.ирТестированиеМетаданных.Форма.Форма.Форма(647)}:		ГлобальныйТестОбъектов(ЭтаФорма);

```
Не уверен относится ли она к ошибке в ИР или ошибке типовой конфигурации.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/961077

**Comment by tormozit** [comment]
Исправлено в 6.69.1
