### ISSUE TITLE
Тестирование метаданных. Значение не является значением объектного типа (Данные)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#384]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.68.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

![image](https://user-images.githubusercontent.com/87958986/226967161-d4a44ca6-65c4-4e7c-8800-710ebbda65b2.png)

**Воспроизведение проблемы**
1. При тестировании метаданных справочника ОснованияЛьготПоИмущественнымНалогам региструрется следующая ошибка:
```
Значение не является значением объектного типа (Данные)
{ВнешняяОбработка.ирТестированиеМетаданных.МодульОбъекта(136)}:								ЗаполнитьРеквизитыНепустымиЗначениями(СтруктураОбъекта.Данные, МетаОбъект);
{ВнешняяОбработка.ирТестированиеМетаданных.Форма.Форма.Форма(647)}:		ГлобальныйТестОбъектов(ЭтаФорма);

```

**Comment by tormozit** [comment]
Ошибку не смог воспроизвести, но вероятно у нее та же причина https://www.hostedredmine.com/issues/961077

**Comment by tormozit** [comment]
Исправлено в 6.69.1
