### ISSUE TITLE
Тестирование метаданных. Метод объекта не обнаружен (ЗагрузитьСнимок)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#385]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.68.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

![image](https://user-images.githubusercontent.com/87958986/226969443-26a61416-7a95-4564-b1a7-594a91533007.png)

**Воспроизведение проблемы**
1. При тестировании метаданных объекта Документ.АвансовыйОтчет регистрируется ошибка:
```
Метод объекта не обнаружен (ЗагрузитьСнимок)
{ВнешняяОбработка.ирТестированиеМетаданных.МодульОбъекта(255)}:		СтруктураОбъекта.Методы.ЗагрузитьСнимок(СнимокОбъекта.Снимок);
{ВнешняяОбработка.ирТестированиеМетаданных.МодульОбъекта(123)}:									ПроверитьСсылочныйОбъект(СтруктураОбъекта, ИмяОперации, СтрокаТипаМетаданных.Единственное);
{ВнешняяОбработка.ирТестированиеМетаданных.Форма.Форма.Форма(647)}:		ГлобальныйТестОбъектов(ЭтаФорма);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/961078

**Comment by tormozit** [comment]
Исправлено в 6.69.1
