### ISSUE TITLE
Тестирование метаданных. Превышено количество уровней!

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#386]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.68.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

![image](https://user-images.githubusercontent.com/87958986/226969971-068411b2-6b41-4f4f-8668-91667008b7cf.png)

**Воспроизведение проблемы**
1. При тестировании метаданных таких объектов как:
Справочник.ВидыОтправляемыхДокументов
Справочник.ВидыРегистровУчета
Справочник.КодыВалютныхОпераций
Справочник.НаборыДополнительныхРеквизитовИСведений
Справочник.СостоянияПроцессов
Справочник.УдалитьВидыОбъектовЕГАИС
Справочник.УдалитьВидыОтправляемыхДокументов
Справочник.ВерсииМобильныхПриложений

Регистрируется ошибка:

```
Ошибка при вызове метода контекста (Записать)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(14478)}:					Объект.Записать();
{ВнешняяОбработка.ирТестированиеМетаданных.МодульОбъекта(215)}:		ирОбщий.ЗаписатьОбъектЛкс(СтруктураОбъекта.Методы);
{ВнешняяОбработка.ирТестированиеМетаданных.МодульОбъекта(139)}:									ПроверитьСсылочныйОбъект(СтруктураОбъекта, ИмяОперации, СтрокаТипаМетаданных.Единственное, Истина);
{ВнешняяОбработка.ирТестированиеМетаданных.Форма.Форма.Форма(647)}:		ГлобальныйТестОбъектов(ЭтаФорма);
по причине:
Превышено количество уровней!

```
Осуществил поиск этой ошибки по всей конфигурации ERP и не нашел такой фразы.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/961081

**Comment by tormozit** [comment]
Исправлено в 6.69.1

**Comment by PerlAmutor** [comment]
Похоже, что не помогло

![image](https://user-images.githubusercontent.com/87958986/227791188-2d8d960e-10af-4188-acb8-831cca21aa86.png)

**Comment by tormozit** [comment]
> Осуществил поиск этой ошибки по всей конфигурации ERP и не нашел такой фразы.

Потому что эту ошибку генерирует платформа при превышении максимального числа уровней иерархии в справочнике

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/962194

**Comment by tormozit** [comment]
Исправлено в 6.72.1

**Comment by PerlAmutor** [comment]
В 6.72.1p ошибка осталась:

![image](https://user-images.githubusercontent.com/87958986/232362780-64f39ba2-e639-485a-a902-54c3069fcc7c.png)

**Comment by tormozit** [comment]
Нужен снимок объекта из одноименной колонки. Желательно сообщать текстом имена проблемных объектов метаданных.

**Comment by PerlAmutor** [comment]
> Нужен снимок объекта из одноименной колонки. Желательно сообщать текстом имена проблемных объектов метаданных.

```
<CatalogObject.СостоянияПроцессов xmlns="http://v8.1c.ru/8.1/data/enterprise/current-config" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Ref>0f233ed4-2a5c-47ee-a526-1b0a4102058e</Ref>
	<DeletionMark>false</DeletionMark>
	<Parent>260936b8-c180-11e4-a7a9-000d884fd00d</Parent>
	<Description>а</Description>
	<Описание>а</Описание>
	<РеквизитДопУпорядочивания>1</РеквизитДопУпорядочивания>
</CatalogObject.СостоянияПроцессов>
```

Справочник.СостоянияПроцессов
Справочник.УдалитьВидыОбъектовЕГАИС

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/962261

**Comment by tormozit** [comment]
Исправлено в 6.73
