### ISSUE TITLE
Тестирование метаданных. АвтоТест

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#387]
Чтобы снизить количество ложных срабатываний ошибок при УФ в инструменте Тестировании Метаданных в ERP есть предложение передавать произвольные ключи через "Параметры" формы как это сделано для ДопольнительныеСвойства у объектов:

![image](https://user-images.githubusercontent.com/87958986/226974845-4b66c35c-ab63-41e2-84f2-34b37786dccc.png)

В данном случае реализовать возможность передать ключ "АвтоТест".

**Comment by tormozit** [comment]
Согласен, что это снизит число ложных ошибок. Но в таком случае тестироваться по сути будет только компиляция модулей форм, т.е. и чисто ложных не срабатываний вырастет значительно. А ошибки компиляции модулей встречаются очень редко. Поэтому для тестирования форм сделано столько флажков - так можно управлять вероятностью ложных ошибок. У форм объектов и списков БД она минимальна. А у произвольных (неосновных) форм она максимальна.
