### ISSUE TITLE
Новый инструмент - Редактор поддержки поставщика.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#388]
В конфигураторе есть редактор поддержки конфигурации поставщика:

![image](https://user-images.githubusercontent.com/87958986/227757449-f72f9960-a3c6-4304-8e5f-e214e2f7f8b0.png)

Многие разработчики снимают "замки" со всех объектов конфигурации забывая про то, что это влияет на скорость сравнения и объединения при обновлении. Обратно поставить на замки не изменившиеся объекты задача уже не тривиальная.

Есть такая обработка - https://infostart.ru/1c/articles/1148991/ которая это делает
Хотелось бы видеть подобный функционал в ИР.

Файл настройки поддержки при выгрузке в XML располагается по папке Ext - ParentConfigurations.bin
Если я правильно понял, то его можно выборочно загружать без необходимости загрузки всей конфигурации (можно ли также выгрузить без полной выгрузки?).

Подсмотреть его формат можно тут:
https://github.com/1c-syntax/supportconf/blob/develop/src/main/java/com/github/_1c_syntax/bsl/supconf/ParseSupportData.java

Как варианты использования, можно рисовать дополнительные иконки в интерфейсной панеле:

![image](https://user-images.githubusercontent.com/87958986/227758091-25912c65-9cd1-4501-a89d-8b208ba6b829.png)

Или в инструменте Тестирование Метаданных сделать фильтр отбора для выбора лишь НЕ типовых объектов метаданных (своих). Правда все это потребует контроля изменения конфигурации, чтобы вовремя обновлять.

**Comment by tormozit** [comment]
Возможно будет полезно https://www.hostedredmine.com/issues/962964
