### ISSUE TITLE
Тестирование метаданных. Недостаточно памяти.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#389]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.69.1p
Инструменты разработчика. Инструмент: Тестирование метаданных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

![image](https://user-images.githubusercontent.com/87958986/227792968-cc4e82ba-1f9c-4cd9-a033-371d6b794980.png)

**Воспроизведение проблемы**
1. Запустил тестирование только объектов в инструменте Тестирование метаданных
2. Через какое-то время возникло сообщение о нехватке памяти:

![image](https://user-images.githubusercontent.com/87958986/227793044-af592276-ef51-44d2-b632-cf749490db77.png)

**Comment by tormozit** [comment]
Прогнал аналогичный тест на своей клиент-серверной базе (КА1 с демо данными) с вариантом "Конфигурация". Клиентский процесс достиг 400МБ и серверный 400МБ. 
Проверь с вариантом "Расширение". Если проблема повторится, то проблема либо в коде конфигурации, либо в том что инструмент выбирает в качестве эталона очень большие объекты. 
Открой инструмент "Сборщики счетчиков Windows (ИР)" и создай счетчик "\Process(1cv8*)\Private Bytes". Повтори эксперимент и покажи диаграмму.

**Comment by PerlAmutor** [comment]
Проверил в варианте "Расширение". Ситуация повторяется, при этом прогресс обработки метаданных в ИР не идет.

![image](https://user-images.githubusercontent.com/87958986/227835922-2e35e90c-1f5e-46df-8e5a-1819ec121311.png)

**Comment by tormozit** [comment]
> прогресс обработки метаданных в ИР не идет

С самого начала не идет? Или застывает в каком то состоянии? Если застывает, то хочется картинку и из отладчика имя объекта метаданных. Замер производительности сделай. Думаю это какой то мегадокумент (с очень большой табличной частью) или какое то мега хранилище значения (кто то засунул туда большой файл).

**Comment by PerlAmutor** [comment]
Документ.ОперацияНалоговогоУчетаПоНДФЛ

![image](https://user-images.githubusercontent.com/87958986/229409433-e0d64315-1c93-4f29-aa6e-0abd5f838ecc.png)

Результаты замера производительности пока открываются, уже минут 30. Возможно выложу позже.

**Comment by tormozit** [comment]
Думаю тут ошибка кода конфигурации. Если провести документ с очень маленькой датой (НалоговыйПериод), то он анализирует периоды за всю историю, на что уходит огромное время и память.

Покажи значения реквизитов этого документа.

**Comment by tormozit** [comment]
Видимо похожая проблема https://infostart.ru/1c/articles/1794627/

**Comment by PerlAmutor** [comment]
Да, ошибка в тестовом релизе ERP 2.5.12.28
Впадает в бесконечный цикл из-за даты 01.12.0001  0:00:00 и условия Период >= НачалоГода(НалоговыйПериод) который всегда возвращает Истина, т.к. метод платформы ДобавитьМесяц(Период, -1) не может отнять от рождества 1 месяц и увести дату в минус.

![image](https://user-images.githubusercontent.com/87958986/229605542-d9388969-dbdf-4fd7-a7ec-a71bdd287bde.png)

**Comment by tormozit** [comment]
Врядли я смогу придумать тут какую то универсальную защиту. Поэтому закрываю заявку.
