### ISSUE TITLE
В "Загрузка табличных данных (ИР)" некорректно работает флажок "Использовать отбор" закладки ТЗ

### ISSUE THREAD

**Issue by kibor-mail** [tormozit/RDT1C#39]
**Программное окружение**
Платформа: 8.3.17.1851
Режим БД: файловый
Конфигурация. Название: Бухгалтерия предприятия, редакция 3.0 (3.0.96.35)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.03.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. СинхронизацияДанныхСUTM5Плюс (1.03)
Расширения. ИнструментыРазработчикаTormozit (6.03.1e)
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

**Воспроизведение проблемы**
1. Открыл инструмент "Загрузка табличных данных (ИР)". 
2. Загрузил сохранённую ранее настройку "настройка ОС 10.sxl". Таблица значений сконвертирована. Отбора не указано. Колонки таблицы снизу заполнены.
![отбор1](https://user-images.githubusercontent.com/89959554/131787903-162fbb01-514f-4db7-8092-2b96f5f93d73.JPG)

2.1. Если нажать кнопку "Посмотреть исполняемую компоновку в консоли компоновки", то ничего не происходит, отборы зачем-то очищаются.
![отбор2](https://user-images.githubusercontent.com/89959554/131788112-2b05aab1-b94b-4f3c-9c5a-70596c67f55b.JPG)
![отбор3](https://user-images.githubusercontent.com/89959554/131788162-f54f426d-464f-4e82-ab92-1c8ff5d26ad6.JPG)

3. Вернул назад отборы, Включил флажок "Использовать отбор". Отбор строк сработал. Но практически все колонки очистились.
![отбор4](https://user-images.githubusercontent.com/89959554/131788567-31177cb3-7d99-4330-bc6f-ec863ac8cd7c.JPG)

4. Если опять нажать кнопку "Посмотреть исполняемую компоновку в консоли компоновки", то откроется "Консоль компоновок данных (ИР)". В ней на закладке "Выбранные поля" видно, что почему-то практически все поля не выбраны. Как их выбрать назад в "Загрузка табличных данных (ИР)" - непонятно.
![отбор5](https://user-images.githubusercontent.com/89959554/131788964-2855f50a-ba0f-4c6d-a122-f7837c55b45c.JPG)

5. Со стороны конфигуратора, когда нажимается флажок "Использовать отбор", то считывается "Компоновщик" формы. В доступных полях есть все. Но в выборе они все (почти) с признаком "Использование = Ложь".
![отбор6](https://user-images.githubusercontent.com/89959554/131789193-75703244-1fcc-4573-b0d1-3b0715e9c58e.JPG)
![отбор7](https://user-images.githubusercontent.com/89959554/131789200-c1f7f516-1128-4234-acc2-b82aed59e861.JPG)

6. Более-менее это можно обойти, если отладкой в функции ирОбщий.ОтобратьТаблицуЗначенийКомпоновкойЛкс() параметр "СкопироватьИВосстановитьНастройки" задать "Истина". Тогда коллекция Компоновщик.Настройки.Выбор.Элементы будет пустая. Отбор отработает нормально. Значения всех колонок сохранятся.
![отбор8](https://user-images.githubusercontent.com/89959554/131790139-4658f5c7-0376-4d21-9dca-18e5ed9801e4.JPG)

**Ожидаемое поведение**
Что просто выполнится отбор.

**Comment by kibor-mail** [comment]
Настройка с проблемой.
[настройка ОС 10.zip](https://github.com/tormozit/RDT1C/files/7096558/10.zip)

Настройка без проблемы.
[настройка ОС 11.zip](https://github.com/tormozit/RDT1C/files/7096568/11.zip)

11 получена открытием старой настройки 8 и внесением (вроде бы) тех же изменений, что и между 8 и 10.
[настройка ОС 8.zip](https://github.com/tormozit/RDT1C/files/7096589/8.zip)

**Comment by tormozit** [comment]
Нужны картинка страниц "Конвертация значений" и "Сопоставление колонок"

**Comment by tormozit** [comment]
Твой файл я открыть пока не могу - нет такой конфигурации под рукой. Нужна картинка страницы "Конвертация значений"

**Comment by tormozit** [comment]
Воспроизвести не смог. Но скорее всего исправлю https://www.hostedredmine.com/issues/932752
Сама проблема отсутствия пометки "Использование" у выбранных полей видимо возникла ранее и хранится в твоем файле.

**Comment by kibor-mail** [comment]
Не очень понимаю, что будет видно по скриншотам, но прилагаю.Для себя пока исправил изменением ОтобратьТаблицуЗначенийКомпоновкойЛкс(): СкопироватьИВосстановитьНастройки = Истина  03.09.2021, 11:59, "Sergey Starykh" ***@***.***>: Нужны картинка страниц "Конвертация значений" и "Сопоставление колонок"—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.   -- С уважением,Ждановский МаксимООО "КИБОР-С"+79138341634

**Comment by kibor-mail** [comment]
> Воспроизвести не смог. Но скорее всего исправлю https://www.hostedredmine.com/issues/932752
> Сама проблема отсутствия пометки "Использование" у выбранных полей видимо возникла ранее и хранится в твоем файле.

**Comment by kibor-mail** [comment]
Сложно пока ещё здесь ориентироваться. Просили скриншоты.
[RE_Issue #39.zip](https://github.com/tormozit/RDT1C/files/7103634/RE_Issue.39.zip)

Если проблема хранится в файле, то почему Компоновщик не заполняется новыми значениями, если добавлять новые колонки, конвертировать ТЗ ещё раз, делать что-либо ещё?

Было бы неплохо хотя бы иметь кнопку "Обновить доступность колонок", которая для всех Компоновщик.Настройки.Выбор.Элементы поставит Истина. 
Ну или сделать в открываемой "Консоль компоновок данных (ИР)" по кнопке "Посмотреть исполняемую компоновку в консоли компоновки" какую-нибудь кнопку переноса значений. Допустим, открыл, изменил галочки, скомпоновал, проверил, перенёс назад в инструмент "Загрузка табличных данных (ИР)"

**Comment by tormozit** [comment]
Исправлено в 6.07.2
