### ISSUE TITLE
Текст в заголовках дин. списка...

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#390]
... не должен быть меньше трех символов на строку.
![image](https://user-images.githubusercontent.com/75837433/227953199-03ac8721-1c0b-4d8f-ad3c-a8f629b95d31.png)

**Comment by tormozit** [comment]
Понятие "строка" здесь довольно расплывчатое, т.к. часто платформа делает перенос строки по словам. Наверное лучше заменить "строка" на "слово". 
Замечания/жалобы проще воспринимать, когда они сопровождаются конкретным примером, что не отвергает полезность и обобщенных формулировок. Выбери одну конкретную колонку и для нее
1. Покажи ее отображение в табличном поле (на твоей картинке например "З... к...")
2. Активируй ее и нажми F12
3. Покажи открывшееся окно ее свойств
4. Покажи эту колонку в окне "Колонки табличного поля"

**Comment by john-doe-1c** [comment]
Строка в тексте выше означает строку - это любой текст до переноса строки в следующую.
Пример на картинке. Многоточие не должно быть раньше чем через три символа после начала строки.

**Comment by tormozit** [comment]
> Многоточие не должно быть раньше чем через три символа после начала строки

К сожалению такое сделать в прикладном коде невозможно. Я это уже объяснил выше - "платформа делает перенос строки по словам"

**Comment by john-doe-1c** [comment]
А при чем тут платформа? Ты же переопределяешь текст заголовков у всех колонок. Переопределить можно на любой нужный с какими надо переносами.

**Comment by tormozit** [comment]
Попробуй с другой стороны подойти к проблеме. Не предлагай решение задачи в общем виде, т.к. она очень непростая. Опиши конкретные 1-2 неудобства как я описал выше.
