### ISSUE TITLE
Дин. список, когда выбрана не основная таблица а ТЧ: открывать прикладную форму а не редактор объекта БД

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#391]
Когда в дин. списке выбрана таблица-"шапка", то двойной клик по строке открывает прикладную форму объекта (из конфигурации), а не редактор объекта БД. И это логично, т.к. редактор я всегда могу открыть нужной мне кнопкой в верхней панели.

Если же в дин. списке выбрана не шапка, а какая-то ТЧ, то двойной клик в строке открывает редактор объекта БД, и это нелогично, т.к. редактор я и так могу открыть той же самой кнопкой в верхней панели.

Хочу чтобы по двойному клику открывалась прикладная форма объекта, а не редактор объекта БД.
Или если уж по какой-то причине и открывать редактор, то чтобы в нем была лупа у поля "Ссылка", чтобы я мог быстро перейти из ненужного мне редактора к нужной мне прикладной форме объекта.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/961202

**Comment by tormozit** [comment]
Реализовано в 6.70
