### ISSUE TITLE
Журнал регистрации. Невидимые события.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#392]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.69.1e
Инструменты разработчика. Инструмент: Анализ журнала регистрации
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.69.1e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. В инструменте "Журнал Регистрации" часть Событий в отборе выглядит как пустая строка
2. При наведении мышки на строку видно подсказку

![image](https://user-images.githubusercontent.com/87958986/228006243-5fdd957d-2534-460c-bcb6-dca0231cbf08.png)

Какие-то символы в строке приводят к неправильному парсингу?

**Comment by tormozit** [comment]
Скопируй текст и вставь в редактор с обозначением спец символов или HEX отображением. Это точно не моих рук дело.

**Comment by PerlAmutor** [comment]
Похоже, что это ошибка платформы возникающая при записи текстов исключений в поле Событие вместо поля Комментарий.

На этом скрине то как видит ИР это событие:

![IMG-20230328-WA0005](https://user-images.githubusercontent.com/87958986/228290241-8f34538e-cbfb-4afc-9d2e-ce990537f6ad.jpg)

Платформенный просмотр Журнала Регистрации этого события вообще не видит, как будто его нет:

![IMG-20230328-WA0006](https://user-images.githubusercontent.com/87958986/228290193-ca69ff6c-340c-42fe-a7f8-2064ca8b63a5.jpg)

Это код обработки ПомощникаЗачетаОплат в ERP (ошибка и в 2.5.8 и в 2.5.12 не исправлена), который формирует такие кривые записи:

![IMG-20230328-WA0003](https://user-images.githubusercontent.com/87958986/228290020-2b01e3be-0f25-4ae9-8546-706209c5b0a5.jpg)

А это то как видит ИР это событие:

![IMG-20230328-WA0004](https://user-images.githubusercontent.com/87958986/228290085-5a710225-ab53-4dd5-b4ba-0148d59ba69a.jpg)

А это содержимое самого .lgp файла:

![IMG-20230328-WA0002](https://user-images.githubusercontent.com/87958986/228291539-83f0d372-17ae-44e8-b2e5-2c6e6d24df01.jpg)

Т.е. с представлением события все-таки и в ИР не все гладко, т.к. в форме события он это событие видит, хоть и с символом переноса строки, а вот в результате выгрузки и в отборе уже не видит.

**Comment by tormozit** [comment]
Ты в курсе как работаешь флажок "Многострочное" у поля ввода? Все дело в нем. В ИР нет ошибки. Табличное поле отображает текст ячейки с уважением символа "Перенос строки", а поле ввода в форме события журнала ИР - его не уважает. Для углубления познаний включи у колонки журнала флажок "Автовысота" и "Высота"=2+

**Comment by PerlAmutor** [comment]
Так может для формирования представления отбора по Событию ЖР убирать переводы строки? Визуально хотя бы какой-то текст будет виден, а значение отбора оставить как есть.

**Comment by tormozit** [comment]
Адаптировать инструмент под многострочные имена событий я не буду. От них во многих местах будут проблемы. Это НЕ правильное использование имени события. Нормальный код так не делает. 
Как увидеть их в удобном виде, я написал выше. Подозреваю, что ты еще даже не пробовал.

**Comment by tormozit** [comment]
Создал задачу на общее решение проблемы https://www.hostedredmine.com/issues/961562

**Comment by tormozit** [comment]
Реализовано в 6.70
