### ISSUE TITLE
Ошибка при передаче ссылок между инструментамии

### ISSUE THREAD

**Issue by LordSenya** [tormozit/RDT1C#393]
**Программное окружение**

Платформа: 8.3.13.1926
Режим БД: клиент-серверный
Конфигурация. Название: ASSOL_Рабочая ()
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_3_11
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 6.67.6p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru_RU
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2008 R2 Enterprise  64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов". создал и выполнил запрос получив ссылки на документы
2. Выделил все ссылки и нажал кнопку "Передать ссылки из выделенных ячеек в "Подбор и обработка объектов"
3. Получил окно с ошибкой "{ВнешняяОбработка.ирОбщий.МодульОбъекта(11532)}: Таблица БД с именем "" не найдена
		ВызватьИсключение "Таблица БД с именем """ + ПолноеИмяТаблицыБД + """ не найдена";
"

**Ожидаемое поведение**
Раньше передавало все ссылки в инструмент "Подбор и обработка объектов"

**Comment by tormozit** [comment]
Уже исправлено. Полезно смотреть список последних исправлений или хотя бы искать по нему слова из ошибки. Тогда можно не тратить свое время на создание заявки
https://www.hostedredmine.com/issues/960047
