### ISSUE TITLE
Ошибка при открытии ИР в тонком клиенте.

### ISSUE THREAD

**Issue by awk-kazmin** [tormozit/RDT1C#394]
При открытии обработки в тонком клиенте, происходит ошибка.

Ошибка инициализации модуля: ВнешняяОбработка.ирПортативный.Форма.ЗапускСеансаУправляемая.Форма
по причине:
{ВнешняяОбработка.ирПортативный.Форма.ЗапускСеансаУправляемая.Форма(210,26)}: Переменная не определена (ирОбщий)
	Если ТипЗнч(ЭтаФорма) = <<?>>ирОбщий.ТипУправляемаяФормаЛкс() Тогда

Платформа: 8.3.22.1750
Режим БД: клиент-серверный
Конфигурация. Название: БИТ: Строительство (БИТ.ФИНАНС) КОРП, редакция 3.0 (3.0.129.13/3.1.53.9/3.0.1.241)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.69.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. ОшибкаВРасходахУменьшающихНалоги ()
Расширения. ФСК_ОшибкаВПравахРоли_бит_НалоговыйМониторинг ()
Расширения. Инвентаризация_НМА_РБП (1.3.1)
Расширения. ОшибкаРегОтчСтатистика ()
Расширения. БизнесРУ_Фискализация (1.3.1.15)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс
Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 17763)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/961231

**Comment by tormozit** [comment]
Исправлено в 6.69.3
