### ISSUE TITLE
Выгрузка/Загрузка данных через файл. Битые ссылки

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#395]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.69.1e
Инструменты разработчика. Инструмент: Выгрузка/загрузка данных через файл
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.69.1e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Передать ссылку в Подбор и обработку объектов БД 
2. Выбрать обработку "Выгрузка в файл"
3. Выбрать ВСЕ типы выгружаемые по ссылке:
![image](https://user-images.githubusercontent.com/87958986/228293928-b56b691e-c7f2-4783-8744-c1662c0fa74c.png)
4. Перейти в ИР в тестовой базе и загрузить .zip файл через инструмент "Выгрузка / Загрузка данных через файл"
5. Открыть получившийся документ. Видим битые ссылки, хотя настраивали выгружать все типы:

![image](https://user-images.githubusercontent.com/87958986/228294583-a2a7bd6e-c5f8-4225-94ee-a2a89c0f7feb.png)

**Comment by tormozit** [comment]
1. Какой первичный объект выгружался?  Желательно, чтобы он был один.
2. В какой части объекта обнаружены битые ссылки?

**Comment by PerlAmutor** [comment]
Документ выгружался.
Табличная часть документа.

**Comment by tormozit** [comment]
Проверил в варианте "Расширение". Выгрузились все объекты по ссылкам из табличной части. 
Повтори эксперимент с одним документом желательно с одной строкой среди всех ТЧ. Покажи экран и текстовые сообщения после завершения выгрузки, а также выгруженный файл. Проверь, что после его загрузки в строке видны битые ссылки.

**Comment by tormozit** [comment]
Еще покажи настройки загрузки.

**Comment by tormozit** [comment]
Не воспроизвелось?
