### ISSUE TITLE
Динамический список регистра сведений. Активность неверно отображается.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#396]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.69.1p
Инструменты разработчика. Инструмент: Динамический список
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

</details>

**Воспроизведение проблемы**
1. Открыть инструмент Динамический список
2. Выбрать регистр сведений (напр. РегистрСведений.МестонахождениеОС)
3. Видим поле "Активность" не установлено для всех записей, хотя это не так:

![image](https://user-images.githubusercontent.com/87958986/228298497-0540be96-9f75-422e-ba38-0a3b41264cb9.png)

![image](https://user-images.githubusercontent.com/87958986/228298740-43034eca-e4c3-4bc7-a63f-6684bb192db5.png)

В варианте "Расширение" все отображается корректно.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/961234

**Comment by tormozit** [comment]
Исправлено в 6.70
