### ISSUE TITLE
Зависание при подключении внешней компоненты из макета ВК64 Обработки.ирПортативный

### ISSUE THREAD

**Issue by VZhulanov1** [tormozit/RDT1C#397]
Платформа: 8.3.20.1710
Режим БД: клиент-серверный
Конфигурация. Название: Фарм Капитан (2.115.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_18
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Инструменты разработчика. Версия: Конфигурация 6.67.7
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows 7 Максимальная  64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс
Сервер. ОС: Microsoft Windows 7 Максимальная  64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Запустил программу
2. Открыл инструмент консоль запросов либо консоль кода
3. Жестко зависаем, только через диспетчер задач снимать. Если подключен отладчик, то в нем бесполезно завершать или перезапускать процесс, висит

Начал разбираться
Зависает на попытке подключения dll-ки из макета ВК64 Обработки.ирПортативный при вызове функции ВыполнитьПроверкуСовместимостиКонфигурацииЛкс();

И что интересно. 
Если перед открытием консоли запросов я сам вызываю принудительно эту функцию ВыполнитьПроверкуСовместимостиКонфигурацииЛкс(), то потом консоль открывается без проблем и дальше все работает.
Если открою другой инструмент, например подбор и обработку объектов или просто окно о подсистеме, то эта функция тоже вызывается (отладчиком ловил) и без проблем выполняется и потом так-же консоль работает без проблем.
Зависание ловится только если консоль запросов или консоль кода открываю как самый первый инструмент ИР после запуска программы.

На скрине показано на какой строке зависание происходит.
Куда копать не знаю, кэш чистил, хранилища настроек чистил, не помогает.

![image](https://user-images.githubusercontent.com/128121602/229074943-10bb0865-5e81-4380-a177-5aad4aaa70f0.png)

**Comment by tormozit** [comment]
Скорее всего ошибка в платформе. Пробуй [8.3.20.2290](https://releases.1c.ru/version_files?nick=Platform83&ver=8.3.20.2290)

**Comment by tormozit** [comment]
тут похожую проблему обсуждали 
http://devtool1c.ucoz.ru/forum/2-1905-1
http://devtool1c.ucoz.ru/forum/2-1335-1

**Comment by tormozit** [comment]
Удалось решить проблему?

**Comment by VZhulanov1** [comment]
На смену платформы для тестирования пока времени нету.
У клиентов ни у кого не зависает, но там и версии платформы другие немного
