### ISSUE TITLE
Редактор остатков. Таблица не найдена.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#399]
https://user-images.githubusercontent.com/87958986/230728883-67c58cca-365d-4529-8806-2e8be2ae3308.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В инструменте Редактор остатков не предлагает варианты подбора по строке "ПрочиеРасходы" (ERP)
2. Получаю ошибку:

```
Таблица БД с именем "ПрочиеРасходы" не найдена
{ВнешняяОбработка.ирОбщий.МодульОбъекта(11543)}:		ВызватьИсключение "Таблица БД с именем """ + ПолноеИмяТаблицыБД + """ не найдена";
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10673)}:	ТекстЗапроса = ПолучитьТекстЗапросаПолейТаблицыБДЛкс(ПолноеИмяТаблицыБД, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10484)}:	ТаблицаРезультата = ПустаяТаблицаЗначенийИзТаблицыБДЛкс(ПолноеИмяТаблицыБД, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирКэш.МодульОбъекта(72)}:	Результат = ирОбщий.ПоляТаблицыБДЛкс(ПолноеИмяТаблицыБД, _ВызыватьИсключениеПриОтсутствииПрав, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирРедакторОстатков.Форма.Форма.Форма(148)}:		ЭлементыФормы.Регистратор.ОграничениеТипа = ирКэш.ПоляТаблицыБДЛкс(ИмяТаблицыРегистра).Найти("Регистратор", "Имя").ТипЗначения;
```

**Comment by tormozit** [comment]
Исправлено в 6.71
