### ISSUE TITLE
Конструктор запросов ИР. К выбранному полю.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#4]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1363
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Расширение 6.02.1e
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.02.1e)
> Клиент. ОС: Microsoft Windows 7 Ultimate  64-bit Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

После исправления предыдущей ошибки "К выбранному полю" в Конструкторе Запросов ИР сломался переход по другим полям объединения.
```
ВЫБРАТЬ
   1 КАК Поле
ОБЪЕДИНИТЬ ВСЕ
ВЫБРАТЬ
   2 КАК Поле
```

https://user-images.githubusercontent.com/87958986/126929526-84b9bcd7-9695-40bb-a534-8a4769c50f1a.mp4

**Comment by tormozit** [comment]
В описании не хватает текста запроса

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/931182
Текст запроса добавил в твое описание.

**Comment by tormozit** [comment]
Исправлено в 6.02.2
