### ISSUE TITLE
Консоль запросов. Вставить ссылку. Выбор объекта метаданных. Фильтр по подсистеме.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#40]
https://user-images.githubusercontent.com/87958986/131797623-de2e82cd-3d76-445c-a59d-8c8fed9ea170.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.07.1e
> Инструменты разработчика. Инструмент: Обработка.ирПлатформа.Форма.ВыборОбъектаМетаданных
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.07.1e)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: tcp

</details>

Следующие действия в Консоли Запросов приводят к ошибке:
1. Используем команду  "\ Панель \ Текст запроса(2) \ Командная панель \ Вставка \ Ссылка на объект БД (Alt+Shift+_1)"
2. В открывшемся диалоге выбора объекта метаданных жмем "Выбор" на "<ФильтрПодсистем>"
3. В открывшемся диалоге выбора подсистем используем команду " \ Командная панель \ Установить пометки \ Пометить выделенные"
4. Жмем "Ок"

```
Значение не является значением объектного типа (Состав)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(31674)}:		Для Каждого ЭлементСостава Из ПодсистемаМД.Состав Цикл
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.ВыборОбъектаМетаданных.Форма(345)}:	ОбъектыВыбранныхПодсистем = ирОбщий.ОбъектыПодсистемЛкс(ФильтрПодсистем);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.ВыборОбъектаМетаданных.Форма(1031)}:	ЗаполнитьДеревоИсточников(,, Истина);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.ВыборПодсистемы.Форма(180)}:		ОповеститьОВыборе(Результат);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(832)}:		Результат = Форма.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(6751)}:	СтрокаПараметра = ЭкземплярКомпоненты.ВставитьСсылкуНаОбъектБД(ЭлементыФормы.Параметры, "ИмяПараметра", , "Параметры", Истина,,,

```

Кроме того, хоть мышкой и нельзя поставить флажок на корне дерева, это можно сделать через нажатие Пробела.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932738

**Comment by tormozit** [comment]
Исправлено в 6.08.1
