### ISSUE TITLE
Редактор остатков. Значение не является значением объектного типа (ПолноеИмя)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#401]
https://user-images.githubusercontent.com/87958986/230729214-d318dd10-e1cd-4658-8bc3-21763b26296d.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В инструменте Редактор остатков после прочтения остатков и использования команды "Регистратор" (Открыть регистратор) получаю ошибку:

```
Значение не является значением объектного типа (ПолноеИмя)
{ВнешняяОбработка.ирКлиент.МодульОбъекта(10967)}:		ИмяТаблицы = ирОбщий.МетаданныеОбъектаБДЛкс(КлючОбъекта).ПолноеИмя();
{ВнешняяОбработка.ирРедакторОстатков.Форма.Форма.Форма(545)}:	ирКлиент.ОткрытьСсылкуВРедактореОбъектаБДЛкс(Регистратор);
```

**Comment by tormozit** [comment]
Исправлено в 6.71
