### ISSUE TITLE
Менеджер табличного поля. Не принимается ссылка без очистки типа.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#402]
https://user-images.githubusercontent.com/87958986/230729418-e9535b35-e639-4a7a-a17e-27b993358016.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл движения документа в Редакторе объекта БД
2. В отдельном окне Редактора объекта была был открыт элемент справочника откуда я скопировал навигационную ссылку
3. В первом редакторе я вызвал Менеджер табличного документа
4. Вытащил в отбор поле АналитикаУчетаПоПартнерам
5. Попытался вставить ссылку скопированную заранее сразу в поле и получил сообщение о том что в поле введены некорректные данные
6. Если при этом очистить тип поля (T) и нажать комбинацию Ctrl+V, то ссылка вставляется нормально

**Comment by tormozit** [comment]
Можно использовать явную вставку из внутреннего буфера (глобальное меню подскажет сочетание клавиш), либо нажимать CTRL+V без входа в режим редактирования строки https://www.hostedredmine.com/issues/952307

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/961918

**Comment by tormozit** [comment]
Исправлено в 6.71
