### ISSUE TITLE
Конструктор запросов ИР. Комментарии меняют свое положение.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#403]
https://user-images.githubusercontent.com/87958986/230729754-4c08e02c-021b-4f3b-ac5a-352d79628005.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Конструкторе запросов ввел запрос::
```
ВЫБРАТЬ
	1 КАК Поле,
	// +Тест
	// Раз два три
	ВЫБОР КОГДА ИСТИНА ТОГДА
		ИСТИНА
	ИНАЧЕ
		ЛОЖЬ
	КОНЕЦ   
	// -Тест
```
2. Открыл Конструктор запросов ИР и он отформатировал запрос с перемещением комментариев:
```
ВЫБРАТЬ
	1 КАК Поле,
	//+Тест
	//Раз два три
	//-Тест
	ВЫБОР
		КОГДА ИСТИНА
			ТОГДА ИСТИНА
		ИНАЧЕ ЛОЖЬ
	КОНЕЦ КАК Поле1
```

**Comment by tormozit** [comment]
Это задуманное поведение, т.к. любой комментарий при разборе текста запроса получает привязку к конкретному синтаксическому элементу, а у каждого синтаксического элемента есть только один комментарий. Поэтому разбросанные внутри синтаксического элемента комментарии сливаются в один текст.
Это можно увидеть уже в самом конструкторе запроса. В данном случае таким элементом является выбранное поле, что видно на твоем видео (колонка "Комментарий").

**Comment by PerlAmutor** [comment]
Я планировал доработать типовой запрос конфигурации и вставлять комментарии в своих доработанных блоках описанным способом в первом сообщении, но с удивлением обнаружил такое поведение. Ну раз нельзя, значит нельзя.
