### ISSUE TITLE
Отладить отложенный объект. Индексируемое поле не может иметь составной тип и тип неограниченной длины

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#404]
https://user-images.githubusercontent.com/87958986/230730843-e9e84697-2f07-4f49-a8b3-c4a708752457.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При отладке запроса формирования проводок для документа ВозвратТоваровОтКлиента на этой строке в ERP:

![image](https://user-images.githubusercontent.com/87958986/230730968-ff6c97b9-99c8-4329-8a05-7222cebf9771.png)

2. При последующей передачи .deb файла в ИР 
3. Возникает ошибка:

```
{ВнешняяОбработка.ирКонсольЗапросов.МодульОбъекта(65)}: Ошибка при вызове метода контекста (НайтиПараметры): {(8432, 2)}: Индексируемое поле не может иметь составной тип и тип неограниченной длины
<<?>>Т.ОбъектУчета                          КАК ОбъектУчета,
Текст запроса: Строка кода 8 432: {(8 432,2)}: Индексируемое поле не может иметь составной тип и тип неограниченной длины
<<?>>Т.ОбъектУчета                          КАК ОбъектУчета,
```

Сам запрос ошибок не содержит и в типовой демо-конфигурации работает.

Файл отладки прилагаю:

[_08_04_202318_51_05ОтладитьСтруктура.zip](https://github.com/tormozit/RDT1C/files/11183621/_08_04_202318_51_05.zip)

**Comment by tormozit** [comment]
Скорее всего это ошибка платформы. Возникает при вызове метода Запрос.НайтиПараметры() с таким текстом при наличии в менеджере временных таблиц запроса каких то особых временных таблиц. Поковырялся немного, чтобы понять что в моем коде нет ошибки. Но сделать пример для отправки в тех. поддержку 1С там довольно сложно. Поэтому предоставляю эту возможность тебе =)

**Comment by PerlAmutor** [comment]
Боюсь что все-таки это не ошибка платформы. Я воспроизвел в обработке. ИР зачем-то добавляет лишние типы "Булево" и "Число" там где их не будет при обычном выполнении запроса.

[ДолгосрочнаяЗадолженность.zip](https://github.com/tormozit/RDT1C/files/11185413/default.zip)


https://user-images.githubusercontent.com/87958986/230772264-4ef99be9-513d-4f79-ae73-214103b52aed.mp4

**Comment by tormozit** [comment]
Попробуй в модуле ирОбщий найти строку целиком 
`Типы.Добавить(Тип("Строка"));`
и замени ее на 
`Типы.Добавить(Тип("Null"))`

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/961925

**Comment by PerlAmutor** [comment]
> Типы.Добавить(Тип("Строка"));

Нашел только такое, но там уже есть Null

![image](https://user-images.githubusercontent.com/87958986/230789570-b7c840d7-57b4-4c32-a8ae-7c3302cf1a91.png)

**Comment by tormozit** [comment]
Ошибся. Там 
`Типы.Добавить(Тип("Число"));`

**Comment by PerlAmutor** [comment]
> Ошибся. Там
> `Типы.Добавить(Тип("Число"));`

Там видимо надо две строки заменять на одну с Null

![image](https://user-images.githubusercontent.com/87958986/230790002-4a3bc873-ef59-4d75-a8cd-451707d7af6a.png)

**Comment by PerlAmutor** [comment]
Ничего не получилось:

![image](https://user-images.githubusercontent.com/87958986/230790564-2784e5be-64ca-4208-b09f-cda29ff48077.png)


![image](https://user-images.githubusercontent.com/87958986/230790536-7ed8edf0-a0b6-4cd8-a3e1-1d82f4c48138.png)

**Comment by PerlAmutor** [comment]
Когда смотрю состав типа колонки временной таблицы, то вижу "НеизвестныйОбъект":

![image](https://user-images.githubusercontent.com/87958986/230819670-195cdbae-4a18-492d-b141-2f161005e399.png)

Попробовал добавить его таким образом:

![image](https://user-images.githubusercontent.com/87958986/230819724-c10c5465-503f-43ca-846c-127eca6281f1.png)

Он добавляется, но ошибка все та же, с таким типом выбрать невозможно из ТЗ.
Вероятно требуется дополнительная доработка на этом участке, чтобы такой Неудобный тип переварить:

![image](https://user-images.githubusercontent.com/87958986/230819874-b7e0fe5b-0878-48ba-8d4f-b72de3ff24b1.png)

//////// Дополнение
При выгрузке данных из временной таблицы этот тип теряется. Он виден получается только когда в менеджере временных таблиц состав типов просматриваешь.

![image](https://user-images.githubusercontent.com/87958986/230821802-638e35fa-53ed-4293-8086-cb376e1a5046.png)

![image](https://user-images.githubusercontent.com/87958986/230821942-7a7294a8-7c36-403f-bcc2-34786fdaee2c.png)

![image](https://user-images.githubusercontent.com/87958986/230822382-50f64aab-7151-4733-9a96-603120953791.png)

**Comment by tormozit** [comment]
Исправлено в 6.71

**Comment by PerlAmutor** [comment]
> 

Проверил. Проблема осталась:

![image](https://user-images.githubusercontent.com/87958986/230932826-0371de05-3fce-4cfd-b9e0-009038e9f08d.png)

Скорее всего тут надо иначе исправлять. Как вариант сначала выбрать во временную таблицу данные с теми полями у которых есть типы, вторым запросом выбирать недостающие поля через объединение из первой временной таблицы со вторым запросом где будет в секции ГДЕ ЛОЖЬ, но только если в исходной ТЗ нет строк.

**Comment by tormozit** [comment]
В моем тесте (указан в задаче) заработало. Сделай подобный тест для твоего случая.
```
Запрос = Новый Запрос;
Запрос.МенеджерВременныхТаблиц = Новый МенеджерВременныхТаблиц;
Запрос.Текст = 
"выбрать НЕОПРЕДЕЛЕНО как ф1
|ПОМЕСТИТЬ вт
|ГДЕ ЛОЖЬ";
Запрос.Выполнить();
Запрос.Текст = "выбрать * ПОМЕСТИТЬ ВТ2 ИЗ ВТ ИНДЕКСИРОВАТЬ ПО Ф1";
ф = иробщий.ОтЛкс(Запрос,,, Истина);
```

**Comment by PerlAmutor** [comment]
> В моем тесте (указан в задаче) заработало. Сделай подобный тест для твоего случая.
> 
> ```
> Запрос = Новый Запрос;
> Запрос.МенеджерВременныхТаблиц = Новый МенеджерВременныхТаблиц;
> Запрос.Текст = 
> "выбрать НЕОПРЕДЕЛЕНО как ф1
> |ПОМЕСТИТЬ вт
> |ГДЕ ЛОЖЬ";
> Запрос.Выполнить();
> Запрос.Текст = "выбрать * ПОМЕСТИТЬ ВТ2 ИЗ ВТ ИНДЕКСИРОВАТЬ ПО Ф1";
> ф = иробщий.ОтЛкс(Запрос,,, Истина);
> ```

Так у тебя тест некорректно сделан, попробуй такое:

```
Запрос = Новый Запрос;
Запрос.МенеджерВременныхТаблиц = Новый МенеджерВременныхТаблиц;
Запрос.Текст = 
"выбрать НЕОПРЕДЕЛЕНО как ф1
|ПОМЕСТИТЬ вт
|ГДЕ ЛОЖЬ";
Запрос.Выполнить();
Запрос.Текст = 
"ВЫБРАТЬ
|	Т.ф1 КАК ф1
|ПОМЕСТИТЬ ВТ2
|ИЗ
|	(ВЫБРАТЬ
|		Т1.ф1 КАК ф1
|	ИЗ
|		ВТ КАК Т1
|	ОБЪЕДИНИТЬ
|	ВЫБРАТЬ
|		ЗНАЧЕНИЕ(Справочник.Организации.ПустаяСсылка) КАК ф1) КАК Т
|ИНДЕКСИРОВАТЬ ПО
|	Ф1
|";

ф = иробщий.ОтЛкс(Запрос,,, Истина);
```

**Comment by tormozit** [comment]
Да. Наконец то ты сделал правильный тест. Исправлено в 6.72.2

**Comment by PerlAmutor** [comment]
Спасибо, работает.
