### ISSUE TITLE
Конструктор запросов ИР. Не используется кэш в функции ТаблицаВсехТаблицБД.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#405]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

При вызове Конструктора запросов ИР 4150 раз вызывается одна и та же функция ТаблицаВсехТаблицБД(), что замедляет открытие. Скорее всего список таблиц (результат функции) не поменяется до перезапуска сеанса, поэтому ИР вроде бы должен использовать Кэш, но этого не происходит:

![image](https://user-images.githubusercontent.com/87958986/230756655-5cc1b9af-4174-48aa-9d33-1e6fd4545aa2.png)

Тут видно, что из 4150 вызовов в Кэш функция не попала ни разу:

![image](https://user-images.githubusercontent.com/87958986/230756771-6e417f77-a1f3-49e0-8c98-79b6e464e168.png)

Похоже что причина кроется в этой функции:

![image](https://user-images.githubusercontent.com/87958986/230756805-8e13e397-bbb6-498a-947e-c30e0891c52f.png)

Которая каждый раз возвращает новую пустую структуру:

![image](https://user-images.githubusercontent.com/87958986/230756836-dedfb192-e398-4a8f-95a4-a8724a007063.png)

У функции ПроверитьЗагрузитьКэшМДСеанса() нет параметров, поэтому этот кэш очевидно должен был бы появится сразу после первого вызова.

/////////////////////
Дополнение.

Похоже, что вызов функции ПроверитьЗагрузитьКэшМДСеанса() избыточен, т.к. мТаблицаВсехТаблицБД заполняется при вызове ДеревоОбъектовМД() и проверка "Если мТаблицаВсехТаблицБД <> Неопределено Тогда" должна быть в самом начале функции.

![image](https://user-images.githubusercontent.com/87958986/230757479-1b8aa564-0bbc-4879-b2c2-57393994b4d3.png)

////////////////////
Дополнение 2.
На проверке дублей таблиц с именем "Изменения" немного проседает скорость открытия:

![image](https://user-images.githubusercontent.com/87958986/230758014-6cf6be98-b488-48ed-9b49-e22a1a9374d4.png)

![image](https://user-images.githubusercontent.com/87958986/230758034-e7d5ae6f-4e39-42ce-b545-9b47b1d3ab35.png)

НПолноеИмя не проиндексировано. Там вообще нет индексов в таблице мТаблицаВсехТаблицБД

**Comment by tormozit** [comment]
Предоставь файл замера и текст запроса, который при этом передавался в конструктор

**Comment by PerlAmutor** [comment]
Это при открытии Конструктора Запросов ИР без текста запроса.
[Новый10.zip](https://github.com/tormozit/RDT1C/files/11184972/10.zip)

**Comment by tormozit** [comment]
Это замер повторного открытия конструктора?

**Comment by PerlAmutor** [comment]
Нет, первого, 14 секунд:

![image](https://user-images.githubusercontent.com/87958986/230760125-d7fff87f-ed2d-4a01-af84-e608debac32d.png)

**Comment by tormozit** [comment]
Тогда это бесполезный замер в рамках сформулированной проблемы. Ты же подверг сомнению кэширование. А сам сделал замер первого вызова. Делай замер второго вызова конструктора и строй обоснование заново.
Кэш ТаблицаВсехТаблицБД заполняется при первом обращении к нему в сеансе.
