### ISSUE TITLE
При сборке информации о метаданных происходит избыточная проверка ролей на ПравоДоступа

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#406]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

В функции ДеревоОбъектовМД() ирПлатформа.epf происходит избыточная проверка ПраваДоступа() на Метаданные с типом Роль. В ERP таких ролей за 1700.

![image](https://user-images.githubusercontent.com/87958986/230759058-0090eeb7-2e11-47a3-a1b3-5ddfe3dd8b71.png)

![image](https://user-images.githubusercontent.com/87958986/230759166-e3439fd7-def5-4ef7-a90e-b431668a3c66.png)

![image](https://user-images.githubusercontent.com/87958986/230759175-400c7653-2018-4d55-8d1c-fff4a7a53f31.png)

**Comment by tormozit** [comment]
Обоснуй избыточность

**Comment by tormozit** [comment]
Согласен, что проверка избыточная, но платформа для неподходящих метаданных очень быстро возвращает результат. Все выполнения этой строки вместе идут 280мс на 14000 объектов. Значит 1700 ролей максимум где то 30мс занимают, а скорее всего 10мс. На фоне 10000мс+ твоего замера это кажется каплей в море.

**Comment by PerlAmutor** [comment]
В клиент-серверной базе оно конечно подольше идет.

**Comment by tormozit** [comment]
Метод ПравоДоступа() не вызывает обращение к серверу. Поэтому в клиент-серверной базе должны быть те же затраты.

**Comment by tormozit** [comment]
Сделай нормальный тест своей гипотезы - цикл чисто с ролями. И покажи результат его замера.

**Comment by PerlAmutor** [comment]
Сделал, судя по всему первый запуск долгий, т.к. все-таки идет какое-то обращение к серверу и затем это кэшируется.

![image](https://user-images.githubusercontent.com/87958986/230773509-63d694f6-fbdb-499f-82bb-0a9e9d23997d.png)

[ЦиклСОрялми.zip](https://github.com/tormozit/RDT1C/files/11185456/default.zip)

643 мс. для первого запуска это не много но и не мало.

**Comment by tormozit** [comment]
Думаю вопрос можно считать закрытым, т.к. роли я все равно будут обходить, и чисто вызовы ПравоДоступа(<Роль>) занимают мизерное время. Время тут в первом обходе уходит в основном на обращение к метаданным. 
Плохо что ты не показал построчный замер.
