### ISSUE TITLE
Редактор объекта БД. Ошибка приводящая к невозможности дальнейшего использованию инструмента.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#407]
https://user-images.githubusercontent.com/87958986/230761591-cfa1c5f1-4501-43db-ae73-8c3cdded8a54.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыть документ в Редакторе объекта БД
2. Очистить поле "Порядок" через вызов команды "Очистить" контекстного меню
3. Возникнет ошибка:
```
Ошибка при вызове метода контекста (Сортировать)
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(6097)}:	РеквизитыТаблица.Сортировать(СтрокаСортировки);
по причине:
Недопустимое значение параметра (параметр номер '1')
```
4. Закрываем инструмент и пытаемся открыть его заново:
5. Получаем предупреждение:
![image](https://user-images.githubusercontent.com/87958986/230761687-ae0df14a-5004-4f96-9fdf-de823ed9b9d5.png)
6. Соглашаемся на сброс настроек
7. Получаем ошибку:

```
Ошибка при вызове метода контекста (Сортировать)
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(6097)}:	РеквизитыТаблица.Сортировать(СтрокаСортировки);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3969)}:	ПорядокРеквизитовПриИзменении();
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(22)}:	ИмяСинонимПриИзменении();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(10359)}:		ЭтаФорма.ЗагрузитьНастройкуВФорме(НастройкаФормы, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(10336)}:	ЗагрузитьНастройкуФормыЧерезОбработчикЛкс(ЭтаФорма, НастройкаФормы, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(10314)}:			ЗагрузитьНастройкуФормыПоУмолчаниюЛкс(ЭтаФорма, Истина, ПараметрыЗагрузкиНастройкиПоУмолчанию);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1011)}:	ирКлиент.СоздатьМенеджерСохраненияНастроекФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(161)}:		Форма.Открыть();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(143)}:	ОткрытьИнструмент(СтрокаИнструмента);
по причине:
Недопустимое значение параметра (параметр номер '1')

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/961928

**Comment by tormozit** [comment]
Исправлено в 6.71
