### ISSUE TITLE
Анализ техножурнала. Падает платформа.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#408]
https://user-images.githubusercontent.com/87958986/230774734-1b59153c-75f0-4c40-a41c-b5a8ab95e36f.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Анализ техножурнала
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Анализ техножурнала
2. Загрузил логи
3. Выбрал событие DMSSQL
4. 2 раза кликнул по полю "Текст СУБД"
5. В открывшейся форме кликнул 2 раза по значению в колонке "Индекс мета"
6. После некоторого времени платформа 1С упала.

Небольшой файл ТЖ прилагаю.

[tzh_09042023.zip](https://github.com/tormozit/RDT1C/files/11185512/tzh_09042023.zip)

**Comment by tormozit** [comment]
Открой инструмент "Структура хранения БД". Включи флажок "Показывать размеры". Нормально выполняется?

**Comment by tormozit** [comment]
Если там повторится ошибка, то ковыряй метод Обработка.ирСтруктураХраненияБД.ЗаполнитьРазмерыФайлойБазы() . Вероятно проблема во внешней компоненте расчета размеров таблиц файловой базы https://infostart.ru/public/176476/

**Comment by PerlAmutor** [comment]
Да, падает на строчке
`мКомпонентаCDDB.Open1CDFile(ИмяФайла);`

У тебя какой вариант встроен, который из публикации или из комментария?

![image](https://user-images.githubusercontent.com/87958986/231019453-c9ded7c2-e042-45e7-817c-1b3d7ecb680c.png)

**Comment by PerlAmutor** [comment]
Кстати вот что странно, у переменной ПоказыватьРазмеры значение Истина, а на форме флажок снят...

![image](https://user-images.githubusercontent.com/87958986/231020015-dd4c7baa-1069-49c8-ae2b-0a4a6897f90f.png)


![image](https://user-images.githubusercontent.com/87958986/231020055-cd195da1-fb89-4050-bd96-79a977e1e0c6.png)

**Comment by PerlAmutor** [comment]
Судя по логам компоненте даже удается что-то считывать, но в какой-то момент происходит падение:

![image](https://user-images.githubusercontent.com/87958986/231021602-1eaba67f-27cd-48eb-8d65-c7cc21cc3810.png)

Это последние записи перед падением:
![image](https://user-images.githubusercontent.com/87958986/231021269-0737cd79-32df-4d88-b934-61dd65669db7.png)

**Comment by tormozit** [comment]
> У тебя какой вариант встроен, который из публикации или из комментария?

Да.

> Кстати вот что странно, у переменной ПоказыватьРазмеры значение Истина, а на форме флажок снят...

Надо описать проблему в отдельной заявке.

**Comment by tormozit** [comment]
> Судя по логам компоненте даже удается что-то считывать, но в какой-то момент происходит падение:

Думаю тут лучше напрямую написать автору компоненты.

**Comment by PerlAmutor** [comment]
> > Судя по логам компоненте даже удается что-то считывать, но в какой-то момент происходит падение:
> 
> Думаю тут лучше напрямую написать автору компоненты.

Написал 4 дня назад. Автор не отвечает.

**Comment by tormozit** [comment]
Думаю ждать автора компоненты уже бессмысленно. Пробуй тестирование и исправление с реструктуризацией сделать в проблемной базе. В общем надо пробовать двигаться сразу в двух направлениях:
1. Обойти проблему путем каких то воздействий на внутреннюю структуру базы.
2. Создавать похожие базы и искать условия по которым можно программно отличить проблемную базу от здоровой.
