### ISSUE TITLE
Редактор объекта БД. Метод объекта не обнаружен (ОбъектБД)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#409]
https://user-images.githubusercontent.com/87958986/230775726-1e4aec6c-00e6-4752-b9bb-c5068cfc80ee.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл документ в Редакторе объекта БД
2. Вызвал команду " \ Командная панель \ Основная форма \ Обычная форма измененного"
3. Получил ошибку:

`
Ошибка создания объекта на клиенте: {ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(2532)}: Метод объекта не обнаружен (ОбъектБД)`

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/961926

**Comment by tormozit** [comment]
Исправлено в 6.71
