### ISSUE TITLE
Консоль запросов. Вставить ссылочное значение ячейки в текст запроса в виде параметра

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#41]
https://user-images.githubusercontent.com/87958986/131801790-2aab10f4-092c-446e-bf48-f2c8b5cea969.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Расширение 6.07.1e
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.07.1e)
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: tcp

</details>

При использовании команды  "\ Панель \ Результат-коллекция(1) \ Командная панель \ Вставить в текст запроса" Консоли Запросов возникает ошибка:

```
Поле объекта не обнаружено
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(9449)}:	ТекущееЗначение = ЭлементыФормы.РезультатКоллекция.ТекущаяСтрока[ЭлементыФормы.РезультатКоллекция.ТекущаяКолонка.Данные];

```

Текст запроса:

```
ВЫБРАТЬ
	"123" КАК ЧислоСтрокой

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.08.1
