### ISSUE TITLE
Консоль запросов. Очистка поля поиска в результате запроса приводит к ошибке.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#410]
https://user-images.githubusercontent.com/87958986/230776452-2ce1f998-71d8-483f-82bb-fa44a3d2dae8.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
При вызове команды очистки поля поиска результата запроса ( \ Панель \ Результат-коллекция(0) \ <РезультатКоллекцияСтрокаПоиска> (Ctrl+Shift+F)) возникает ошибка:

```
Поле объекта не обнаружено (НачальноеИзменятьСоставСтрок)
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9016)}:		Если ДопСвойства.НачальноеИзменятьСоставСтрок Тогда
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(11328)}:		ирКлиент.ТабличноеПолеСОтборомПросмотраОтобратьЛкс(ЭтаФорма, ЭлементыФормы.РезультатКоллекция,,, Элемент = Неопределено);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(11522)}:	РезультатКоллекцияИспользоватьОтборПриИзменении();
```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.71
