### ISSUE TITLE
Консоль запросов. Поле объекта не обнаружено (Fields)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#411]
https://user-images.githubusercontent.com/87958986/230776928-d649d5a7-e0f7-4e3f-be7d-b3cbf1f94c74.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.70.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Выполнил текст запроса в Консоли запросов
2. Перешел на вкладку "Обработки строки результата"
3. Вставил код "ирОбщий.СообщитьЛкс("Тест");"
4. Вызвал команду " \ Панель \ Обработка строки результата(1) \ Командная панель \ Сформировать текст модуля"
5. В открывшемся инструменте Консоль кода вызвал команду Выполнить
6. Получил ошибку:

`Редактор встроенный: Строка кода 15: Поле объекта не обнаружено (Fields)`

**Comment by tormozit** [comment]
ошибку воспроизвел https://www.hostedredmine.com/issues/961927

**Comment by tormozit** [comment]
Исправлено в 6.71
