### ISSUE TITLE
Редактор хранилищ настроек: распараллеливать когда читаем по всем пользователям

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#414]
Выбрал в дереве слева отбор загрузки "Все пользователи" и жду 2-3 минуты, несмотря на то что предварительно вбил имя настройки в отбор основной (широкой) таблицы.
Просьба распараллелить хотя бы на 4 потока (в идеале - чтоб можно было настраивать).

**Comment by tormozit** [comment]
Нужно разделять отбор загрузки данных (из БД) и просмотра. Отбор просмотра ориентирован на высокую оперативность и частое изменение. Обычно у меня широкие возможности по его изменению. А отбор загрузки данных нередко сильно ограничен платформой, как например в этом случае. При выборке элементов из стандартного хранилища настроек платформа позволяет только отбор на равенство по полям Пользователь, КлючОбъекта, КлючНастроек

Выбрать(<Отбор>)
Параметры:
<Отбор> (необязательный)
Тип: Структура. 
Задает поле и значение отбора открываемой выборки. Ключ структуры описывает имя поля, а значение структуры - значение отбора по этому полю. В качестве полей для отбора могут задаваться поля "КлючОбъекта" ("ObjectKey"), "КлючНастроек" ("SettingsKey"), "Пользователь" ("User").

Можно подумать над режимом опционального применения отбора просмотра на РАВЕНСТВО по полям КлючОбъекта и КлючНастроек к отбору запроса данных. В твоем случае он помог бы?

**Comment by john-doe-1c** [comment]
Отбор на равенство по ключам не помог бы, т.к. я туда максимум имя объекта метаданных вписываю.
Но я все-таки думаю про отбор по пользователю - когда я выбрал слева "Все" пусть оно в разных потоках в цикле получает по одному пользователю (в каждом потоке будет своя группа пользователей), а потом склеит. Ведь любопытному пользователю получение всех существующих в базе настроек без отбора посмотреть тоже иногда хочется, хотя бы чтоб проконтролировать что отбор просмотра задан верно (что там не пустота изначально считалась, а реально что-то отбросилось).

**Comment by tormozit** [comment]
Разделение на потоки сделать можно, но подходящего механизма высокого уровня готовности в инструментах нет. Делать это будет трудоемко, а полезно это очень редко. Поэтому вероятность реализации в ближайшее время низка.

**Comment by PerlAmutor** [comment]
Голосую за распараллеливание. Проблема древняя из-за чего тяжело работать со списком настроек пользователей, когда их у тебя более 2000 в базе и всем надо вычистить настройку какой-нибудь формы.

**Comment by tormozit** [comment]
Распараллеливание не даст ускорения в файловой базе и в портативном варианте, что особенно важно для @PerlAmutor . Так что его голос можно игнорировать =)

**Comment by tormozit** [comment]
Создал задачу на ускорение загрузки настроек при наличии отбора по подстроке https://www.hostedredmine.com/issues/963230

**Comment by tormozit** [comment]
Сделано в 6.76

**Comment by john-doe-1c** [comment]
Это с клиента должен быть доступ к СУБД, а также должны быть известны логин-пароль?

**Comment by tormozit** [comment]
Нажми гиперссылку "Параметры СУБД". Там увидишь ответы на все эти вопросы.

**Comment by john-doe-1c** [comment]
Вбил туда, но так и не понял как этот флажок должен работать: время подгрузки настроек на форму не изменилось.

**Comment by tormozit** [comment]
А мне непонятно, что тебе непонятно. Если время загрузки большое, нужно делать замер производительности и выкладывать его сюда. 
Также нужна картинка. Почему у тебя постоянные проблемы с картинками? Надо тренировать этот важный навык - делать снимки экрана.

**Comment by john-doe-1c** [comment]
Непонятно, где заявленное тобою ускорение или хотя бы каким оно должно быть.
Картинку чего нужно приложить?
