### ISSUE TITLE
Поиск битых ссылок. Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#415]
https://user-images.githubusercontent.com/87958986/231337664-03b16dd0-f008-44a0-a11a-7843f096e23c.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.71.2p
Инструменты разработчика. Инструмент: Поиск битых ссылок
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Запустил поиск битых ссылок в инструменте "Поиск битых ссылок"
2. В табличном поле "БитыеСсылки" выбрал поле отличное от поля "Ссылка"
3. Вызвал команду  \ Командная панель \ Передать для обработки
4. Получил ошибку:

```
Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств)
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ПодборИОбработка.Форма(2287)}:			ЗаполнитьЗначенияСвойств(СтрокаДанных, КлючЗаписи);  // Здесь наверное может неоправдано наполняться объектный кэш
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ПодборИОбработка.Форма(1358)}:		ЗагрузитьСтрокиДляОбработки(ПараметрМассивСсылок,, ПараметрВыбранныеПоля, Истина);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(12572)}:	Форма.Открыть();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(12394)}:	ОткрытьМассивОбъектовВПодбореИОбработкеОбъектовЛкс(МассивСсылок,, ЭтаФорма,, КлючТекущейСтроки);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(17319)}:				ОткрытьОбъектыИзВыделенныхЯчеекВПодбореИОбработкеОбъектовЛкс(ИсточникДействий,, ЭтаФорма);
{ВнешняяОбработка.ирПоискБитыхСсылок.Форма.Форма.Форма(481)}:	ирКлиент.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
по причине:
Недопустимое значение параметра (параметр номер '2')

```
Ошибка общая и для других инструментов:

![image](https://user-images.githubusercontent.com/87958986/231338832-76f8e927-8286-4954-ad6f-9f04501a1175.png)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/962063

**Comment by tormozit** [comment]
Исправлено в 6.71.3
