### ISSUE TITLE
Анализ прав доступа. Полные права.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#416]
В инструменте "Анализ прав доступа" хотелось бы видеть вариант отчета который показывает следующие установленные права на роли "ПолныеПрава":

![image](https://user-images.githubusercontent.com/87958986/231345830-20d58876-e5f7-4544-af7c-9c2439ca2169.png)

![image](https://user-images.githubusercontent.com/87958986/231345911-263ec39f-249c-45d2-b273-f82b641bcb84.png)

![image](https://user-images.githubusercontent.com/87958986/231345988-a2e2a184-12db-4f23-a1f8-fddf1a1da5b4.png)

![image](https://user-images.githubusercontent.com/87958986/231346050-a39e1076-343f-4282-948d-83352b932e4e.png)

![image](https://user-images.githubusercontent.com/87958986/231346149-b112960b-ae81-46a8-b98e-3d610c23ef6c.png)

![image](https://user-images.githubusercontent.com/87958986/231346197-16a4dd87-f8d7-425a-a181-d16d9919bf07.png)

![image](https://user-images.githubusercontent.com/87958986/231346243-a8067e86-7f58-4967-84f3-59a994f8b6a8.png)

Часто при добавлении новых объектов в систему, а также при загрузке конфигурации из XML файлов можно столкнуться с ситуацией, когда эти права выставлены некорректно. Из-за этого например невозможно воспользоваться обработкой Обновление вспомогательных данных из БСП, помимо очевидной опасности установки таких прав.

**Comment by tormozit** [comment]
Интерактивное удаление инструмент анализирует. Остальные обозначенные тобой права нужно анализировать очень редко. А длительность анализа они увеличивают заметно. Поэтому для решения задачи придется делать настройку, какие права анализировать, что усложнит работу с инструментом.

Хотелось бы более подробного описания когда показанные права нужно анализировать.

**Comment by PerlAmutor** [comment]
Показанные права нужно анализировать только когда пользователь вызвал специальную команду для анализа таких прав. Такой команды пока нет, в чем и состоит мое предложение.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/962675

**Comment by tormozit** [comment]
Реализовано в 6.74

**Comment by PerlAmutor** [comment]
Как-то странно работает, выбрал 5 свойств, но не все из них попадают в отчет и откуда-то вылезает свойство "Просмотр" в результате отчета, хотя я его не выбирал

![image](https://github.com/tormozit/RDT1C/assets/87958986/96e79e90-3089-444b-a772-9a178b3e6646)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/963887 
Но лучше все таки создавать отдельную заявку, если заявка по новой функции в целом выполнена

**Comment by PerlAmutor** [comment]
Я её потому и не закрывал, что еще не проверил новый функционал.

**Comment by tormozit** [comment]
Исправлено в 6.76

**Comment by PerlAmutor** [comment]
Спасибо, вроде работает.
Возможно ли добавить в список отбора свойства роли и верхнего уровня?

![image](https://github.com/tormozit/RDT1C/assets/87958986/fadc4ba9-6d15-4633-a017-44a08bffc6a4)

**Comment by tormozit** [comment]
Права на базу смотри в отдельном отчете https://www.hostedredmine.com/issues/948400

**Comment by PerlAmutor** [comment]
Спасибо, буду знать.
