### ISSUE TITLE
Дин. список, зеленый отбор (по значению) или красный (без значения): ошибка "Итератор для значения не определен"

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#417]
> Платформа: 8.3.17.1851
> Режим БД: клиент-серверный
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим использования синхронных вызовов: Использовать
> Конфигурация. Использовать обычные формы в управляемом приложении: Да
> Инструменты разработчика. Версия: Конфигурация 6.70.3
> Инструменты разработчика. Инструмент: Динамический список
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Асинхронность запрещена: Нет
> Инструменты разработчика. Разрешены имитаторы: Да
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru_RU
> Клиент. Отладка разрешена: Да
> Клиент. Постоянный кэш метаданных: Да
> Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-bit Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС выполнение BAT: Да
> Клиент. ОС Active code page: 866
> Клиент. ОС пинг сервера: 0мс
> Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
> Сервер. Процесс: 64б
> Сервер. Отладка: нет

Открыть ДС, выбрать любую таблицу, выполнить команду "Сбросить" (без этого ошибка не каждый раз воспроизводится), вызвать отбор по любой ячейке. Будет ошибка:
```
Итератор для значения не определен
{ОбщийМодуль.ирОбщий.Модуль(12161)}:	Для Каждого ЭлементОтбора ИЗ ЭлементыОтбора Цикл
{ОбщийМодуль.ирКлиент.Модуль(18719)}:				СтарыйЭлементОтбора = ирОбщий.НайтиЭлементОтбораЛкс(СтарыйОтбор, "" + ЭлементОтбора.ЛевоеЗначение);
{Обработка.ирДинамическийСписок.Форма.ФормаУпр.Форма(1007)}:	ДобавленВСписок = ирКлиент.ДобавитьОтборКомпоновкиВИсториюТаблицыБДЛкс(ЭтаФорма, фОбъект.ПолноеИмяТаблицы, АктивнаяНастройка, СтараяНастройка, ОтборИзменен);
{Обработка.ирДинамическийСписок.Форма.ФормаУпр.Форма(1292)}:	ПроверитьЗапомнитьОтбор();
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/962104

**Comment by tormozit** [comment]
Исправлено в 6.71.3
