### ISSUE TITLE
Анализ Данных. Недостаточно оперативной памяти для анализа данных.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#418]
https://user-images.githubusercontent.com/87958986/231937473-10a02896-4194-4765-ad57-626f6eacecea.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.71.3p
Инструменты разработчика. Инструмент: Анализ данных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При использовании варианта Анализа Данных - Поиск Ассоциаций выдает ошибку:

```
Ошибка при вызове метода контекста (Выполнить)
{ВнешняяОбработка.ирАнализДанных.Форма.Форма.Форма(74)}:	Построитель.Выполнить();
по причине:
Недостаточно оперативной памяти для выполнения анализа.

```

Количество памяти:

![image](https://user-images.githubusercontent.com/87958986/231937685-0a93723e-ceed-42fc-ae03-4b87c434c7ed.png)

**Comment by tormozit** [comment]
Не удалось воспроизвести. Проверь на другом компьютере.
Если повторится, предоставь таблицу значений.

**Comment by tormozit** [comment]
Думаю тут та же причина что и в https://github.com/tormozit/RDT1C/issues/424
