### ISSUE TITLE
Анализ данных. Переменная не определена "Анализ данных"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#419]
https://user-images.githubusercontent.com/87958986/231938129-335d3fd5-051a-44d4-8642-8e3a8b979fa5.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.71.3p
Инструменты разработчика. Инструмент: Анализ данных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Сгенерированный код для варианта Анализа Данных - Поиск ассоциаций выдает ошибку при выполнении в Консоли Кода:

`Редактор встроенный: Строка кода 18: {(18,125)}: Переменная не определена (АнализДанных)
`

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/962123

**Comment by tormozit** [comment]
Исправлено в 6.71.4
