### ISSUE TITLE
Консоль запросов, вкладка "Обработка результата": добавить гиперссылку для задания параметров записи

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#421]
И заодно код из подменю "Вставка - Запись на сервере" чтоб вставлялся без указания второго параметра, иначе параметры записи при таком вызове игнорируются.

**Comment by tormozit** [comment]
Почему не стал использовать передачу строк в подбор и обработку объектов? Кажется обычно это удобнее.
Нужна техническая информация для анализа работы второго параметра.

**Comment by tormozit** [comment]
Ошибку обработки параметра воспроизвел https://www.hostedredmine.com/issues/962165

**Comment by tormozit** [comment]
Для информации.
Общие параметры можно открыть через форму "Список инструментов и общие настройки".
Значения параметров записи передать явно в параметрах метода ЗаписатьОбъектЛкс с подсказкой.

**Comment by tormozit** [comment]
Есть сильная причина не добавлять гиперссылку - кончилась удобная ширина макета формы. Эта форма имеет очень сложную структуру и я долго лечил в ней поломки привязок. Если начну сейчас ее всю передвигать, то они могут снова поломаться.

![изображение](https://user-images.githubusercontent.com/11896251/232202126-180c7524-69d2-4172-aa16-eb4ab9779a2f.png)

**Comment by tormozit** [comment]
Создал задачу на добавление кнопки https://www.hostedredmine.com/issues/962185

**Comment by john-doe-1c** [comment]
> Почему не стал использовать передачу строк в подбор и обработку объектов? Кажется обычно это удобнее.

Держать сам запрос и код по обработке его результата мне удобнее в одном файле запросов, чем не в одном.

> Нужна техническая информация для анализа работы второго параметра

Судя по всему не понадобилось?

> Общие параметры можно открыть через форму "Список инструментов и общие настройки"

Можно. А можно и забыть это сделать, когда будешь обрабатывать результат запроса в разных базах.
Я достаточно уже привык что везде где совершаются операции по записи в БД можно сразу и параметры записи посмотреть / установить по узнаваемой гиперссылке.

> кончилась удобная ширина макета формы

У тебя на картинке не та вкладка.

**Comment by john-doe-1c** [comment]
> Создал задачу на добавление кнопки https://www.hostedredmine.com/issues/962185

Аналогично - вкладка не та что нужно.

**Comment by tormozit** [comment]
Страницы для обработки результата 2. Поэтому делать нужно единообразно на обеих.

**Comment by john-doe-1c** [comment]
А чем вообще отличаются подменю "Вставка" и "Установить текст"? И то, и то вставляет какой-то код. Может их объединить в одно подменю?

**Comment by tormozit** [comment]
Ответ кажется очевидным.
Установить = присвоить значение.
Вставка = вставить текст в текущую позицию .

**Comment by john-doe-1c** [comment]
Ничего не понял из этого ответа. Потыкал команды из второго подменю - оно тоже вставляет текст, но просто с заменой всего что там уже было набрано.

**Comment by tormozit** [comment]
Реализовано в 6.72.1

**Comment by john-doe-1c** [comment]
Не увидел там гиперссылки. Только кнопку. Почему?

**Comment by john-doe-1c** [comment]
https://github.com/tormozit/RDT1C/issues/421#issuecomment-1510817978
