### ISSUE TITLE
Конструктор запросов ИР. Падение платформы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#422]
[ТекстЗапроса.txt](https://github.com/tormozit/RDT1C/files/11234715/default.txt)

https://user-images.githubusercontent.com/87958986/232092985-dd299671-618d-4951-aaf8-5a2c6d0807a4.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.71.4p
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Конструкторе Запросов выполнил команду "Все типы ссылок"
2. Вызвал Конструктор Запросов ИР
3. Платформа упала

**Comment by tormozit** [comment]
Думаю тут та же причина что и в https://github.com/tormozit/RDT1C/issues/424
