### ISSUE TITLE
Консоль запросов. Структура. Падение платформы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#424]
[ТекстЗапроса.txt](https://github.com/tormozit/RDT1C/files/11234875/default.txt)

https://user-images.githubusercontent.com/87958986/232097587-7437cb2f-77cc-4594-b6e4-8fc9a082e9a1.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.71.4p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Консоли Запросов выполнить команду "Установить текст"->"Все типы ссылок"
2. Нажать кнопку "Структура"
3. Падает платформа

**Comment by tormozit** [comment]
Мы уже с тобой это проходили https://github.com/tormozit/RDT1C/issues/76 .
Тогда я поставил защиту на 1000 глубину стека. В новом случае ее видимо не хватило в твоем окружении
```
	Если УровеньВложенности > 1000 Тогда
		ВызватьИсключение "Слишком много частей в объединении или запросов в пакете";
	КонецЕсли; 
```
В моем окружении сработало исключение. Попробуй поставь там поменьше число.

**Comment by PerlAmutor** [comment]
Разработчики ERP опытным путем определили максимальный уровень вложенности в 650 при расчете себестоимости. О чем написали в комментарии.

![image](https://user-images.githubusercontent.com/87958986/232106612-564fb63c-5e18-4316-be21-bf644a92c8e0.png)

**Comment by tormozit** [comment]
Мои тесты примерно тот же минимум (640) показали. Но он зависит от окружения и характера рекурсивной функции, т.е. сохраняемого в стеке набора ее локальных переменных и несквозных параметров. Поэтому повторяю свой совет - попробуй поставь там поменьше число и сообщи его мне, когда оно начнет срабатывать в твоем окружении.

**Comment by PerlAmutor** [comment]
80 уровней отрабатывает нормально 85 уже падает. Возможно в файловых базах этот порог гораздо ниже.

**Comment by tormozit** [comment]
Проверил еще в файловой базе в вариантах "Портативный" и "Расширение". У меня не падает - доходит до 1000 и получаю ошибку "Слишком много частей в объединении или запросов в пакете"

Платформа: 8.3.22.1851
Режим БД: файловый
Конфигурация. Название: Инструменты разработчика (6.71.4)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_2_13
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Конфигурация 6.71.4
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

Платформа: 8.3.22.1851
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_18
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 6.71.4p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Расширения. Расширение1 ()
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

**Comment by tormozit** [comment]
Пробуй в 32б приложении и на другом ПК
