### ISSUE TITLE
Редактор остатков. Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#426]
https://user-images.githubusercontent.com/87958986/232369701-4510d392-24bb-4f6a-be3b-55c421d19423.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.43)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.72.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В инструменте "Редактор остатков" возникает ошибка при выполнении команды "Движения регистратора", если не задана таблица регистра:

```
Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств)
{ВнешняяОбработка.ирРедакторОстатков.Форма.Форма.Форма(703)}:	ЗаполнитьЗначенияСвойств(СтруктураКлюча, ТекущаяСтрока);
{ВнешняяОбработка.ирРедакторОстатков.Форма.Форма.Форма(717)}:	ирКлиент.ОткрытьФормуСпискаЛкс(ИмяТаблицыРегистра,,,,,,,, КлючСтроки());
по причине:
Недопустимое значение параметра (параметр номер '2')

```

**Comment by tormozit** [comment]
Исправлено в 6.77
