### ISSUE TITLE
Редактор остатков. Индекс находится за границами массива

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#427]
https://user-images.githubusercontent.com/87958986/232370365-86f1229f-aedb-46cb-819e-c9ad1405c7ad.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.43)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.72.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Если в инструменте "Редактор Остатков" не выбрана основная таблица, то при использовании команды "Записать" могут возникать следующие ошибки:

```
Индекс находится за границами массива
{ВнешняяОбработка.ирРедакторОстатков.Форма.Форма.Форма(385)}:		ЭлементыФормы.НаборЗаписей.ТекущаяСтрока = ЭлементыФормы.НаборЗаписей.ВыделенныеСтроки[0];

```

```
Значение не является значением объектного типа (ПолноеИмя)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(1825)}:	ПолноеИмяМД = ОбъектМД.ПолноеИмя();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(14996)}:							Объект = СоздатьСсылочныйОбъектПоМетаданнымЛкс(мПолноеИмяМД, ЭтоГруппаДляНового, выхИдентификаторСсылки, ЗаполнитьНовыйСсылочный);
{ВнешняяОбработка.ирРедакторОстатков.Форма.Форма.Форма(389)}:		СтруктураОбъекта = ирОбщий.ОбъектБДПоКлючуЛкс("Документ." + ТипРегистратора);

```

**Comment by tormozit** [comment]
Исправлено в 6.76

**Comment by tormozit** [comment]
Исправлено в 6.77
