### ISSUE TITLE
Колонки БД. Открыть метаданные.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#430]
https://user-images.githubusercontent.com/87958986/232373907-c4d89ed8-7588-44df-9d49-d81dd0a4a6de.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.43)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.72.1p
Инструменты разработчика. Инструмент: Колонки БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При попытке воспользоваться командой "Открыть метаданные" в инструменте "Колонки БД" на таблице с типом "Константа" ничего не происходит, хотя в инструменте "Интерфейсная панель" константа присутствует.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/962198

**Comment by tormozit** [comment]
Исправлено в 6.73
