### ISSUE TITLE
Динамический список ИР. Перечисления. ПодборИОбработкаОбъектов

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#433]
https://user-images.githubusercontent.com/87958986/232375852-947bc734-8b31-4e91-9c36-aac06a7a9d27.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.43)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.72.1p
Инструменты разработчика. Инструмент: Динамический список
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При попытке передать значение перечисления в инструмент "Подбор и обработка объектов БД" из инструмента "Динамический список ИР" возникает ошибка:

```
Ошибка при вызове метода контекста (Вставить)
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ПодборИОбработка.Форма(2304)}:			мСхемаКолонок.Вставить(СтрЗаменить(ПараметрТекущееПоле, ",", "_"), ПараметрТекущееПоле);
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ПодборИОбработка.Форма(1358)}:		ЗагрузитьСтрокиДляОбработки(ПараметрМассивСсылок,, ПараметрВыбранныеПоля, Истина);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(12580)}:	Форма.Открыть();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(12473)}:		Форма = ОткрытьМассивОбъектовВПодбореИОбработкеОбъектовЛкс(ВыделенныеСтроки, ВыбранныеПоля,, ТекущееПолеТаблицы, ТекущаяСтрока, КлючУникальности);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(17334)}:				ОткрытьПодборИОбработкуОбъектовИзДинамическогоСпискаЛкс(ИсточникДействий);
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(578)}:	ирКлиент.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
по причине:
Задано неправильное имя атрибута структуры

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/962257

**Comment by tormozit** [comment]
Исправлено в 6.73
