### ISSUE TITLE
Консоль запросов, Итоговая строка и Фильтры

### ISSUE THREAD

**Issue by Pufilov** [tormozit/RDT1C#434]
**Программное окружение**

Платформа: 8.3.16.1502
Режим БД: клиент-серверный
Конфигурация. Название: Самопал (1.22.09.15)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_2_16
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 6.72.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС пинг сервера: 0мс

**Воспроизведение проблемы**
1. Открыл Консоль запросов. 
2. В результате запроса выделяю некоторые строки - итоговая строка показывется нормально по всем колонкам
3. Включаю фильтр (alt-w) по нужной колонке, выделяю нужные строки - и получаю некорректные данные в итоговой строке
![image](https://user-images.githubusercontent.com/88433411/233016725-4fc86160-5a7e-40d5-b919-9bb1c39c0e5b.png)

**Comment by tormozit** [comment]
Воспроизвести не удалось.
Сделай снимок, чтобы была видна вся панель результата.
Опиши подробнее шаги после открытия консоли. Например было ли это первое выполнение запроса в окне консоли, было ли это первое наложение отбора просмотра, выполнялись ли еще какие то действия до появления проблемы. В идеале нужно описание шагов кратчайшего пути от открытия консоли до появления проблемы.
Желательно сделать видео.

**Comment by Pufilov** [comment]
https://user-images.githubusercontent.com/88433411/233040621-0451c826-2c5e-409c-9802-ef38b061d0b6.mp4

ну вот, проще некуда :) открыл, запустил, сложил, отфильтровал - сложил, снял фильтр - сложил

**Comment by tormozit** [comment]
Возможно тут ошибка платформы связанная с ее версией или режимом совместимости. Пробуй другие.

**Comment by Pufilov** [comment]
ой не знаю даже :) вот другая версия

Платформа: 8.3.15.1869
Режим БД: клиент-серверный
Конфигурация. Название: Управление торговым предприятием для Украины, редакция 1.2 (1.2.68.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_2_13
Инструменты разработчика. Версия: Портативный 6.58.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. Отладка разрешена: Да
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да

https://user-images.githubusercontent.com/88433411/233054617-7698f119-250f-4bb7-88cf-0ddc7fbddf71.mp4

**Comment by tormozit** [comment]
Я имел ввиду пробовать более высокие версию платформы и режима совместимости. Попробуй создать копию базы и поднять в ней режим совместимости например до 8.3.16. 

Открой таблицу значений в отдельном окне и удали из нее все ссылочные колонки. Желательно оставить минимальный набор колонок, с которым проблема воспроизводится. Если проблема воспроизведется, то выгрузи эту таблицу в файл и передай мне.

**Comment by Pufilov** [comment]
Взял типовую демо базу и платформу 8.3.19.1522, снял с поддержки и поднял совместимость 8.2.13 до 8.3.16 - "особенность" в консоли запросов не повторилась при таких условиях. Теперь попробую повторить, но с проверкой на каждом шаге и на платформе рабочей 8.3.16.1502. Занятный квест.

**Comment by Pufilov** [comment]
Результаты пошаговой проверки:

Платформа: 8.3.16.1502
Режим БД: файловый
Конфигурация. Название: Управление торговым предприятием для Украины, редакция 1.2 (1.2.68.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_6
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 6.74.1p

Ситуация исправилась на этом шаге: Версия 8.3.6, и до 8.3.12 все стабильно

Если Режим совместимости Версия 8.3.1-Версия 8.3.5
- вовсе отказываются работать отборы в таблице результата запроса. Результат сработки команды вовсе непредсказуем.

**Comment by tormozit** [comment]
Отключу отбор просмотра для этих случаев, чтобы не путал пользователя некорректными данными https://www.hostedredmine.com/issues/964302

**Comment by tormozit** [comment]
Реализовано в 6.78
