### ISSUE TITLE
Консоль запроса. Дерево запроса. Индекс находится за границами массива

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#435]
https://user-images.githubusercontent.com/87958986/233252846-157ad5b3-9bb3-407f-8a60-2a292e1ac76d.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.43)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.72.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В инструменте Консоль запроса ввести текст пакета запросов:

```
ВЫБРАТЬ
	*
ИЗ
	РегистрНакопления.ТоварыНаСкладах КАК Т
ГДЕ
	ТИПЗНАЧЕНИЯ(Т.Регистратор) = ТИП(Документ.ПересортицаТоваров)

;
ВЫБРАТЬ
	*
ИЗ
	РегистрНакопления.ТоварыНаСкладах КАК Т
ГДЕ
	ТИПЗНАЧЕНИЯ(Т.Регистратор) = ТИП(Документ.ПересортицаТоваров)

```

3. Дождаться пока будет построена "структура запроса ведомая"
4. После этого в контекстном меню табличного поля "Структуры запроса ведомая" станет доступной команда F5 для выполнения всего пакета запросов
5. Добавляем новый пустой запрос или единичный запрос (не пакет)
6. Жмем F5 в любом месте консоли запроса (работает даже при отключенной "Структуре запроса ведомая")
7. Возникает ошибка:
```
Индекс находится за границами массива
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(7592)}:	Количество = ДеревоЗапроса.Строки[0].Строки.Количество();

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.73
