### ISSUE TITLE
Различные значения колонок. Журнал Регистрации. Сортировать. Неверное имя колонки.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#436]
https://user-images.githubusercontent.com/87958986/233253951-afe01747-12fd-40ae-b803-133a4cb750f7.mp4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.43)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.72.2p
Инструменты разработчика. Инструмент: Различные значения колонки
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Выбрать записи в инструменте "Журнал Регистрации"
2. Встать мышкой на поле "Данные"
3. Вызвать команду "Различные значения колонки"
4. Встать на значение поля "Имя типа значения"
5. Вызвать команду "Сортировать по убыванию" / "Сортировать по возрастанию"
6. Возникает ошибка:

```
Ошибка при вызове метода контекста (Сортировать)
{ВнешняяОбработка.ирРазличныеЗначенияКолонки.Форма.Форма.Форма(1291)}:		ЗначенияРасширенные.Сортировать(СтрокаСортировки);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(16701)}:	РезультатФормы = Форма.ОткрытьМодально();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(17326)}:				ОткрытьРазличныеЗначенияКолонкиЛкс(ИсточникДействий,,, ЭтаФорма);
{ВнешняяОбработка.ирАнализЖурналаРегистрации.Форма.Форма.Форма(347)}:	ирКлиент.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
по причине:
Неверное имя колонки

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/962352

**Comment by tormozit** [comment]
Исправлено в 6.73
