### ISSUE TITLE
Интерфейсная панель. Преобразование к значению типа булево не может быть выполнено.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#437]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.43)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.72.2p
Инструменты разработчика. Инструмент: Интерфейсная панель
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

Возникла такая ошибка:

![WhatsApp Image 2023-04-20 at 07 11 46](https://user-images.githubusercontent.com/87958986/233256450-7c6c6562-96e1-4c41-b164-811a66407633.jpeg)

К сожалению я не знаю как её воспроизвести. Возможно дело в том, что поля "Избранное" не существует в таблице:

![image](https://user-images.githubusercontent.com/87958986/233256644-17885c25-56b1-49a3-b461-5fe86e63ec26.png)

Может быть имелось ввиду "ТекущееИзбранное"

![image](https://user-images.githubusercontent.com/87958986/233256777-e6d3767b-bbbd-45d4-a735-ce3361d8d74e.png)

**Comment by tormozit** [comment]
Хотелось бы больше текста в описании проблемы, например имена методов, текст ошибки, фрагменты привязки.

**Comment by tormozit** [comment]
Такая ошибка может возникать при чтении очень старых настроек (2+ года).
Замени условие  после строки 
`стрСтатистика = ВыборкаСтатистики[МаксЭлементовСтатистики - Индекс]`
на
```
						И (Ложь
							Или стрСтатистика.Избранное = Неопределено // Старые версии
							Или стрСтатистика.Избранное = 0)
						И (Ложь
							Или стрСтатистика.КоличествоИспользований = Неопределено
							Или стрСтатистика.КоличествоИспользований < 10)
```

**Comment by tormozit** [comment]
Исправлено в 6.73
