### ISSUE TITLE
Возможность сохранения результата-конллекции из консоли запроса в файл-эксель

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#438]
Консоль запросов, при формировани результата с большим количеством строк хорошо было бы иметь возможность сохранять в файл-эксель программно. - Минуя "выбрать список" - "сохранить как". 
К примеру так: сформировали результат, жмем сохранить, выбираем куда сохранить, профит.

**Comment by tormozit** [comment]
Думаю мне станет понятнее, если ты покажешь хотя бы примерно программный код, который это сделает быстрее. Раз ты это просишь, значит у тебя есть ожидание что так будет быстрее и оно опирается вероятно на какой то опыт. Расскажи о нем подробнее.

**Comment by tormozit** [comment]
Еще хотелось бы понять, сколько колонок и строк в твоей таблице и сколько времени занимает вывод в табличный документ сейчас и главное - **с какими настройками**

**Comment by marv-ua** [comment]
изначально пробовал платформенным вывести строки - там жуть. Ждал минут 10 пока выведет строки, потом минут 5 пока сохранит в файл.
Твой знатно лучше :-)

637 тыс. строк
колонок не много - 8-15
настройки для сохранения "Без оформления", "Колонки значений"
Потом стартует компоновка - чуть больше минуты, потом сохранение в файл минут 5

из способов которыми мы пользуемся - формируем табдок и потом сохраняем его в эксель:
ТабДок.Записать(ИмяФайла, ТипФайлаТабличногоДокумента.XLSX);

**Comment by tormozit** [comment]
Получается подготовка табличного документа командой ИР занимает минуту. Это кажется приемлемым временем. 

Покажи уже наконец картинки, чтобы были видны все настройки (флажки)
1. Окно "Параметры вывода строк"
2. Окно "Табличный документ"

Основное время уходит на сохранение табличного документа в файл. Предлагаю сосредоточиться на этой операции.
Сделай замеры производительности отладчиком для своего сохранения в файл и моего для одного табличного документа.

**Comment by marv-ua** [comment]
![image](https://user-images.githubusercontent.com/81148850/233777881-45134095-179b-4ea1-b364-be438c369a4c.png)
![image](https://user-images.githubusercontent.com/81148850/233777946-9992c5e0-b987-4b1b-9e2a-bf9fc141751a.png)

замеры на одних и тех же данных сделать не смогу.
Меня тут осенило: в эксель имеет смысл сохранять таблицы до 1 млн строк. Даже на миллионе сохраняться в файл будет минут 15-20. что в принципе приемлемо.
Возможно актуально для других типов файлов: типа текстовых с разделителем, дбф.
Наверное было бы удобно выгружать результат запроса в таблицу sql или формировать файл-скрипт который создать таблицу в sql.
Но реальных кейсов пока нет.

**Comment by tormozit** [comment]
Попробуй отключить флажок "Устанавливать Содержит значение"

**Comment by tormozit** [comment]
Еще попробуй в модуле ирКлиент найти строку 
`ТипФайла = ТипФайлаТабличногоДокумента.XLSX`
и заменить ее на другие варианты форма EXCEL, например
`ТипФайла = ТипФайлаТабличногоДокумента.XLS`

**Comment by tormozit** [comment]
Если формат сериализации не важен, то один из наиболее быстрых способов сохранить таблицу значений - команда "Сохранить в файл", использующая формат XML сжатый в zip.
Также можно использовать компактную сериализацию в JSON, если все типы примитивные.

![изображение](https://user-images.githubusercontent.com/11896251/233778928-5235f35e-f40e-400c-b44c-779ac73af201.png)

**Comment by tormozit** [comment]
Добавлю еще команду для быстрого сохранения в CSV https://www.hostedredmine.com/issues/962451

**Comment by marv-ua** [comment]
спасибо.

**Comment by tormozit** [comment]
Добавлю еще команду для быстрого наполнения листа EXCEL https://www.hostedredmine.com/issues/962455

**Comment by tormozit** [comment]
Реализовано в 6.73
