### ISSUE TITLE
Не открываются различные значения колонки из консоли запросов в 1С Drive

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#44]
**Программное окружение**
Платформа: 8.3.17.1549
Режим БД: клиент-серверный
Конфигурация. Название: 1C:Drive, версия 1.3 (1.3.6.5)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: English
Конфигурация. Режим управления блокировкой данных: Managed
Конфигурация. Режим совместимости: Version8_3_14
Инструменты разработчика. Версия: Расширение 6.08.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.08.1e)
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная НеРусский-0409
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Выполнил запрос:
SELECT TOP 1
	SalesOrder.Ref AS Ref
FROM
	Document.SalesOrder AS SalesOrder
3. Выделил первую строку, колонку Ref в таблице Результат-коллекция 
4. Нажал кнопку "Различные значения колонки"
5. Получил окно с ошибкой:
Тип не определен (ДокументСсылкаRef.SalesOrder)
{ИнструментыРазработчикаTormozit DataProcessor.ирРазличныеЗначенияКолонки.Form.Форма.Form(1067)}:		ТипЗначения = Тип(ирОбщий.ИмяТипаИзПолногоИмениМДЛкс(ИмяТипаЗначения));
{ИнструментыРазработчикаTormozit DataProcessor.ирРазличныеЗначенияКолонки.Form.Форма.Form(953)}:	ПрименитьФильтрПоПодстрокеБезСохранения();
{ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(37673)}:	РезультатФормы = Форма.ОткрытьМодально();
{ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(38136)}:				ОткрытьРазличныеЗначенияКолонкиЛкс(ИсточникДействий,,, ЭтаФорма);
{ИнструментыРазработчикаTormozit DataProcessor.ирКонсольЗапросов.Form.Форма.Form(9491)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);

**Ожидаемое поведение**
Откррывается окно "Различные значения колонки".

**Comment by antonsm2011** [comment]
База 1С Drive полностью типовая, та же самая как здесь - https://github.com/tormozit/RDT1C/issues/34.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932854

**Comment by tormozit** [comment]
Исправлено в 6.08.2
