### ISSUE TITLE
Консоль Запросов: Кнопка "Копировать выделенный текст в буфер обмена в виде кода на встроенном языке" уходит в подменю >>Другие кнопки при малом разрешении

### ISSUE THREAD

**Issue by Altez50** [tormozit/RDT1C#440]
**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Нажал кнопку "Копировать выделенный текст в буфер обмена в виде кода на встроенном языке"
3. profit

**Ожидаемое поведение**
Нашел бы кнопку раньше, будь она левее и имела в иконке вертикальную черту, а в списке ключевых слов содержала 'Вставить Переносы строк ("|") ' (на малом разрешении уходит в подменю >>Другие кнопки).

**Comment by tormozit** [comment]
Искать кнопку первый раз лучше не глазами а поиском по структуре формы. Подробнее о нем можно узнать в разделе "Как найти кнопку" http://devtool1c.ucoz.ru/index/opisanie_podsistemy/0-4
Когда что то куда то не умещается, очень желательно  прикладывать иллюстрацию.

**Comment by tormozit** [comment]
В версии 6.74 подсказка кнопки станет:

Сформировать новый текст на встроенном языке из выделенного или всего текста запроса. В начало строк добавляются символы "|", каждая двойная кавычка заменяется на две, добавляются крайние двойные кавычки.

**Comment by tormozit** [comment]
Подсказка кнопки обновлена в 6.74
