### ISSUE TITLE
Ошибка после установке расширения

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#441]
**Программное окружение**
Платформа: 8.3.19.1529
Режим БД: клиент-серверный
Конфигурация. Название: Business automation software for accounting CORP (2.1.15.10)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.74.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ВводОстатковВзаиморасчетов3779 (21.2.1)
Расширения. ОшибкаСортировкиСотрудников (21.18.9)
Расширения. HF ()
Расширения. НастройкиДинамическогоСпискаTormozit (1.00)
Расширения. МониторингОбменаБСП (21.01.06)
Расширения. БлокировкаУдобнее (1.2)
Расширения. ЗапуститьСеансПользователя (2.1)
Расширения. ИнструментыРазработчикаTormozit (6.74.1e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2019 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Клиент. ОС пинг сервера: 0мс
Сервер. ОС: Microsoft Windows Server 2016 Standard 64-bit НеРусский-0422
Сервер. Процесс: 64б
Сервер. Отладка: tcp

Получить эту информацию можно кнопкой "Техническая информация" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1

**Воспроизведение проблемы**
версия расширения ИР 6.74.1e
1. При установке расширения в конфигурацию методом: скачал расширение, добавил его в расширения, перезапустил клиент
2. при запуске тонкого клиента ошибка: 
```
Поле объекта не обнаружено (УИ_УниверсальныеИнструменты)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирСервер.Модуль(1156)}:		ОбъектГруппа.Записать();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(28338)}:		ирСервер.ДобавитьТекущемуПользователюБСПРолиИРЛкс();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирСервер.Модуль(813)}:			ирОбщий.ДобавитьТекущемуПользователюРолиИРЛкс();
{ИнструментыРазработчикаTormozit МодульУправляемогоПриложения(8)}:	Если ирСервер.ПриНачалеРаботыСистемыРасширениеЛкс(ПараметрЗапуска) Тогда 

по причине:
Ошибка при выполнении обработчика - 'ПриЗаписи'
по причине:
Поле объекта не обнаружено (УИ_УниверсальныеИнструменты)
```
3. в толстом клиенте аналогично
4. в обычном приложении аналогично

**Comment by marv-ua** [comment]
73.1е - та же ошибка

**Comment by tormozit** [comment]
К сожалению платформа 8.3.19 некорректно отображает ошибку. Она удаляет из ее описания самую ценную часть. Включи в конфигураторе флажок "Остановка по ошибке" и укажи фильтр "Содержит УИ_УниверсальныеИнструменты". При остановке из окна сообщений конфигуратора скопируй текст ошибки - там будет необрезанный текст.

**Comment by marv-ua** [comment]
![image](https://user-images.githubusercontent.com/81148850/235643356-c5e1b2d4-7c1f-45d9-8be3-a53897390c94.png)
в служебных сообщениях только это :-(
```
Поле объекта не обнаружено (УИ_УниверсальныеИнструменты)
{ОбщийМодуль.УправлениеДоступомСлужебный.Модуль(5615)}:			ПользовательИБ.Роли.Удалить(Метаданные.Роли[КлючИЗначение.Ключ]);
{ОбщийМодуль.УправлениеДоступомСлужебный.Модуль(2408)}:		ОбновитьРолиПользователейИБ(ОбновляемыеПользователиИБ, ПарольПользователяСервиса);
{ОбщийМодуль.УправлениеДоступом.Модуль(1904)}:	УправлениеДоступомСлужебный.ОбновитьРолиПользователей(МассивПользователей, ПарольПользователяСервиса);
{Справочник.ГруппыДоступа.МодульОбъекта(269)}:	УправлениеДоступом.ОбновитьРолиПользователей(ПользователиДляОбновления, ПарольПользователяСервиса);
{Справочник.ГруппыДоступа.МодульОбъекта(131)}:		ОбновитьРолиПользователейПриИзмененииГруппыДоступа();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирСервер.Модуль(1147)}:		ОбъектГруппа.Записать();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(28156)}:		ирСервер.ДобавитьТекущемуПользователюБСПРолиИРЛкс();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирСервер.Модуль(814)}:			ирОбщий.ДобавитьТекущемуПользователюРолиИРЛкс();

```

**Comment by marv-ua** [comment]
![image](https://user-images.githubusercontent.com/81148850/235643671-2a07bd11-9af2-4993-bf71-b5c2aa7a3567.png)

**Comment by marv-ua** [comment]
вопрос решился удалением расширения "других" инструментов. До этого я просто отключал его.

Похоже на ошибку окружения.
