### ISSUE TITLE
Редактор объекта БД: ошибка при выборе таблицы Регистра сведений

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#442]
**Программное окружение**
Платформа: 8.3.19.1529
Режим БД: файловый
Конфигурация. Название: МММ сервис (23.04.27.002)
Конфигурация. Основной режим запуска: Керована прикладна програма
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Ні
Инструменты разработчика. Версия: Расширение 6.74.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Так
Инструменты разработчика. Объекты на сервере: Так
Инструменты разработчика. Асинхронность запрещена: Ні
Инструменты разработчика. Разрешены имитаторы: Так
Расширения. ИнструментыРазработчикаTormozit (6.74.1e)
Расширения. InfostartToolkitPROF (2023.1.04)
Клиент. Приложение: Керована прикладна програма 64б
Клиент. Проверка модальных вызовов: Так
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: uk
Клиент. Отладка разрешена: Так
Клиент. Постоянный кэш метаданных: Так
Клиент. ОС: Майкрософт Windows 11 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Ні
Клиент. ОС выполнение BAT: Так
Клиент. ОС ╥хъє∙р  ъюфютр  ёЄЁрэшЎр: 866

**Воспроизведение проблемы**
1. Открыл редактор объекта БД
2. Выбрал регистр сведений
3. Получил окно с ошибкой 

![image](https://user-images.githubusercontent.com/81148850/235841697-d537e307-ecb4-49e7-addd-217dcaca7f46.png)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/962994

**Comment by tormozit** [comment]
Исправлено в 6.75
