### ISSUE TITLE
Консоль компоновок данных. Упорядочивание в отчете

### ISSUE THREAD

**Issue by Pufilov** [tormozit/RDT1C#443]
Платформа: 8.3.16.1502
Режим БД: клиент-серверный
Конфигурация. Название: Самопал (1.22.09.15)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_3_6
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 6.74.1p
Инструменты разработчика. Инструмент: Консоль компоновок данных
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС пинг сервера: 0мс

**Воспроизведение проблемы**
1. Формируется отчет
2. Тыц на ячейке -> Упорядочить: ...
3. При выборе ячейки числового типа - все ок, при ссылочном типа возникает ошибка
![image](https://user-images.githubusercontent.com/88433411/235876033-b586eefa-dd4d-469a-8278-8b77499b637f.png)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(11745)}: Преобразование значения к типу Булево не может быть выполнено
	Если ПроверятьУникальность Тогда

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/962990

**Comment by tormozit** [comment]
Исправлено в 6.75
