### ISSUE TITLE
Тестирование метаданных - запуск из коммандной строки

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#444]
Есть инструмент Тестирование метаданных.
Но его надо запускать вручную каждый раз.
Есть желание сделать его запуск автоматически по расписанию.
На текущий момент я не нашел такой функции в инструменте.

Хотелось бы что-то похожее по схеме с add и va, чтобы не сильно ломать шаблон применения такого варианта работы.
Вот пример строки запуска для vanessa automation:
"C:\Program Files\1cv8\8.3.22.1750\bin\1cv8c" /N"Парфенов Антон" /TestManager /Execute "C:\Program Files\OneScript\lib\vanessa-automation-single\vanessa-automation-single.epf" /IBConnectionString "File=""L:\!db\unf"";" /C"StartFeaturePlayer;QuietInstallVanessaExt;VAParams=C:\Temp\VAParams.json"

Список пожеланий:
- чтение настроек для инструмента из спец.файла/файлов (например, json-ов)
![изображение](https://github.com/tormozit/RDT1C/assets/12731230/b9a80469-338b-482c-a848-c4bb1bb592fe)
- запуск 1С из командной строки с каким-нибудь спец.ключом запуска и передачей пути к файлу настроек
- вывод в консоль лога, что делает инструмент, что сейчас пишется в сообщения, чтобы оперативно видеть, что происходит
- вывод лога, что делает инструмент в файл лога
- вывод результата работы инструмента в файл сохранения результата: 0 - все ок, 1 - что-то поломалось.
- закрытие сеанса 1С после завершение работы инструмента

**Comment by PerlAmutor** [comment]
Опасное желание. В ERP до сих пор существует один проблемный документ, который не проходит тестирование метаданных, из-за пустой даты - документ уходит в бесконечный цикл и наполняет массив. Затем ожидаемо все падает, т.к. на машине заканчивается оперативная память. В случае с регламентным заданием это может сильно подпортить жизнь пользователям, если собираетесь запускать тестирование в продакшене.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/964222

**Comment by tormozit** [comment]
Сделано в 6.77

**Comment by antonsm2011** [comment]
> Опасное желание. В ERP до сих пор существует один проблемный документ, который не проходит тестирование метаданных, из-за пустой даты - документ уходит в бесконечный цикл и наполняет массив. Затем ожидаемо все падает, т.к. на машине заканчивается оперативная память. В случае с регламентным заданием это может сильно подпортить жизнь пользователям, если собираетесь запускать тестирование в продакшене.

Так я собираюсь это запускать на копии базы перед заливкой на продакшен.
А всякие подобные баги исключать через настройки.
