### ISSUE TITLE
Журнал регистрации. Некорректное прибавление даты.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#445]
https://github.com/tormozit/RDT1C/assets/87958986/9c78d66a-2b7a-4ab7-8361-9dce02c445f4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.53)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.75.1p
Инструменты разработчика. Инструмент: Анализ журнала регистрации
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При ручном вводе даты и времени в поле "Конец периода" инструмента "Журнал Регистрации" и последующем увеличении даты через кнопки "Вверх/Вниз" дата некорректно сбрасывается на начало дня. При выборе периода через диалог такого поведения не происходит.

**Comment by tormozit** [comment]
Поведение возможно корректное, т.к. принадлежит платформе. Позже им напишу.
Упоминание похожей проблемы http://devtool1c.ucoz.ru/forum/3-1982-8631-16-1635582782
Создал задачу https://www.hostedredmine.com/issues/963885

**Comment by tormozit** [comment]
Сделано в 6.76
