### ISSUE TITLE
Объединение данных списков и массивов

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#446]
Хотелось бы видеть предложение дополнить массив или список значений при загрузке данных списков/массивов из сохраненного ранее файла, в том числе и при вставке данных из буфера обмена. Такой функционал присутствует в Таблице Значений, но не реализован для списков и массивов.

![image](https://github.com/tormozit/RDT1C/assets/87958986/cdbd7908-8fd4-43ff-88fb-178b313ede67)

**Comment by tormozit** [comment]
CTRL+C, CTRL+V пробуй

**Comment by PerlAmutor** [comment]
Да, так работает. Спасибо.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/963891

**Comment by tormozit** [comment]
Сделано в 6.76 https://www.hostedredmine.com/issues/963891
