### ISSUE TITLE
Таблица значений. Нельзя загружать коллекцию в саму себя

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#447]
https://github.com/tormozit/RDT1C/assets/87958986/7b80d721-5083-4dc2-b5d1-3a9f1a5c93a8

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.53)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.75.1p
Инструменты разработчика. Инструмент: Таблица значений
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Если в Таблице Значений сначала передать данные в Буфер обмена
2. Затем Получить данные из Буфера обмена и отказаться от дополнения
3. А затем снова Получить данные из Буфера обмена и согласится с дополнением
4. Возникает ошибка

```
Нельзя загружать коллекцию в саму себя
{ВнешняяОбработка.ирОбщий.МодульОбъекта(5371)}:		ВызватьИсключение "Нельзя загружать коллекцию в саму себя";
{ВнешняяОбработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(119)}:					ирОбщий.ЗагрузитьВТаблицуЗначенийЛкс(НовоеЗначение, Коллекция);
{ВнешняяОбработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(1112)}:		УстановитьРедактируемоеЗначение(ТаблицаИзБуфера);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/963886

**Comment by tormozit** [comment]
Исправлено в 6.76
