### ISSUE TITLE
Консоль запросов. Создать новый файл и скопировать текущий запрос.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#448]
https://github.com/tormozit/RDT1C/assets/87958986/f422d0ff-833a-4ec6-aaba-d996387daa76

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.53)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.75.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

При создании новой формы Консоли запросов отсутствует вариант "Создать новый файл, но не копировать текущий запрос"
Проблема проявляется, когда в текущей Консоли запросов открыт файл запросов (т.е. запросы не новые). При вызове команды "+" задается вопрос 

![image](https://github.com/tormozit/RDT1C/assets/87958986/a29ae7b1-8b96-45c7-b3dc-cfc9550b16f6)

Но ни первый ни второй вариант не подразумевают создание новой консоли без запросов.

**Comment by tormozit** [comment]
Но ведь достаточно ответить любой вариант и затем выполнить команду "Новый файл запросов". Непонятно в чем будет экономия. В одном клике?

**Comment by PerlAmutor** [comment]
Так и приходится делать каждый раз. Просто есть ощущение, что это несколько не нормально. Есть накладные расходы при копировании массивных файлов с запросами, где содержится большое количество параметров, в том числе с объемными таблицами значений.

**Comment by tormozit** [comment]
Технически копирование запроса в памяти происходит только при ответе "Да".

**Comment by PerlAmutor** [comment]
Так а разве он не копирует текущий открытый файл запросов?

**Comment by tormozit** [comment]
Файл не копируется. Но загружается в новую форму. Если он большой то на его чтение конечно тоже уйдет время.

**Comment by PerlAmutor** [comment]
Ну вот не хотелось бы )

**Comment by tormozit** [comment]
Понял. Создал задачу https://www.hostedredmine.com/issues/963889

**Comment by tormozit** [comment]
Сделано в 6.76
