### ISSUE TITLE
Ошибка при открытии Редактора объекта БД для контрагента через глобальное меню разработчика в 1С Drive

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#45]
**Программное окружение**
Платформа: 8.3.17.1549
Режим БД: клиент-серверный
Конфигурация. Название: 1C:Drive, версия 1.3 (1.3.6.5)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: English
Конфигурация. Режим управления блокировкой данных: Managed
Конфигурация. Режим совместимости: Version8_3_14
Инструменты разработчика. Версия: Расширение 6.08.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.08.1e)
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная НеРусский-0409
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл контрагента Abata Co (код 00-000262)
2. Открыл глобальное меню разработчика (ctrl+Ё)
3. Выбрал пункт  - форма | Редактировать объект 
4. Получил окно с ошибкой:
Поле объекта не обнаружено (ЭтоГруппа)
{ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(14823)}:			Если Ложь
{ИнструментыРазработчикаTormozit DataProcessor.ирРедакторОбъектаБД.Form.Форма.Form(3562)}:		СтруктураТЧ = ирОбщий.ТабличныеЧастиОбъектаЛкс(мСтруктураОбъектаБД.Методы);
{ИнструментыРазработчикаTormozit DataProcessor.ирРедакторОбъектаБД.Form.Форма.Form(3288)}:	ИмяСинонимПриИзменении();
{ИнструментыРазработчикаTormozit DataProcessor.ирРедакторОбъектаБД.Form.Форма.Form(1090)}:		ИмяОсновнойТаблицыПриИзменении();
{ИнструментыРазработчикаTormozit DataProcessor.ирРедакторОбъектаБД.Form.Форма.Form(1038)}:	УстановитьТаблицуБД(НовоеИмяОсновнойТаблицы);
{ИнструментыРазработчикаTormozit DataProcessor.ирРедакторОбъектаБД.Form.Форма.Form(985)}:		ЗагрузитьОбъектПоКлючу(фОбъект.ПараметрКлючИлиОбъект);
{ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(23490)}:	ФормаРедактора.Открыть();
{ИнструментыРазработчикаTormozit CommonModule.ирГлобальный.Module(412)}:		ирОбщий.ОткрытьСсылкуВРедактореОбъектаБДЛкс(Ссылка,, ИмяТЧБД, ИмяПоляБД, КлючСтроки);
{(1)}:РедактироватьОбъектАктивнойФормыЛкс(ПараметрыОбработчикаОжидания)
{ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(9148)}:	Выполнить(ПараметрыОбработчикаОжидания.ИмяМетода + "(ПараметрыОбработчикаОжидания)");
{ИнструментыРазработчикаTormozit CommonModule.ирГлобальный.Module(352)}:	ирОбщий.ОбработчикОжиданияСПараметрамиЛкс();

**Ожидаемое поведение**
Ожидал, что откроется Редактор объекта БД для контрагента.

**Comment by antonsm2011** [comment]
Если открывать контрагента через Редактор объекта, то ошибка возникает, но редактор объекта БД открыть удается.

**Comment by antonsm2011** [comment]
База 1С Drive полностью типовая, та же самая как здесь - https://github.com/tormozit/RDT1C/issues/34.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932958

**Comment by tormozit** [comment]
Исправлено в 6.08.2
