### ISSUE TITLE
Форма выбора типа. Имя/Синоним

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#450]
Можно ли добавить в форму выбора типа флажок "Имя/Синоним"? Мне, как программисту, привычнее выбирать известные уникальные имена метаданных вместо синонимов, т.к. я провожу большую часть времени в конфигураторе. Кроме того, некоторые типы метаданных имеют одинаковые названия. Вот пример "Статья расходов"

![image](https://github.com/tormozit/RDT1C/assets/87958986/9704aa70-076f-4149-8dff-16661953daab)

Лишь по иконке можно догадаться что один из них справочник, а другой - план видов характеристик. Ранее даже элемент справочника СтруктураПредприятия назывался "Подразделение" и таких было 2 (второй ПодразделениеПредприятия). Ну и некоторые имена вообще отличаются от синонимов.

Можно конечно вывести отдельную колонку как тут:

![image](https://github.com/tormozit/RDT1C/assets/87958986/7cfa60e6-734d-42cb-91c5-b01e3ac70652)

Но от этого "Фильтр" не начинает работать, если набирать "СтатьяРасходов"

![image](https://github.com/tormozit/RDT1C/assets/87958986/4494e67d-e23b-48cb-aa05-b1f2d51c1fb2)

![image](https://github.com/tormozit/RDT1C/assets/87958986/1a8ad603-abd5-44c8-82e8-730ddbe2ac57)

Ну и видимо доработать поиск по Фильтру понадобится.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/963892

**Comment by tormozit** [comment]
Сделано в 6.76

**Comment by PerlAmutor** [comment]
В 6.76 поведение не изменилось. Ничего не находит:

![image](https://github.com/tormozit/RDT1C/assets/87958986/1ddf98c8-0f2a-4999-b383-8138b99881d0)

**Comment by tormozit** [comment]
Ты неправильную строку ищешь.

**Comment by PerlAmutor** [comment]
> Ты неправильную строку ищешь.

Так мне по имени метаданных надо искать

А я понял. Представление типа в XML почему-то в множественном числе идет, т.е. не так как в конфигураторе. Нуу, такое себе

![image](https://github.com/tormozit/RDT1C/assets/87958986/04efcb1c-b398-4df5-9a23-cc965f955a53)

**Comment by tormozit** [comment]
> не так как в конфигураторе

Не выдумывай. Где доказательства?

**Comment by PerlAmutor** [comment]
> Не выдумывай. Где доказательства?

Не выспался... Перепутал реквизит СтатьяРасходов со справочником. Все нормально, по "СтатьиРасходов" я должен был искать, извиняюсь.
