### ISSUE TITLE
Конструктор запросов ИР. Индекс находится за границами массива

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#451]
https://github.com/tormozit/RDT1C/assets/87958986/65c9fb81-218d-42d4-928d-883ce52c3f8d

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.53)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.76.1p
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Загрузил файл с запросом в Консоль запросов
2. Вызвал Конструктора запросов ИР
3. Перешел на вкладку "Текст запроса/пакета"
4. Нажал кнопку "Ок"
5. Получил ошибку:

```
Индекс находится за границами массива
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(2875)}:				ВыбраннаяТаблица = СтрокаЗапроса.ЧастиОбъединения[0].ВыбранныеТаблицы.Найти("&" + СтрокаПараметра.Имя, "ПолноеИмя");
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(2853)}:		ЗагрузитьПараметрыВОбъект();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2711)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1029)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(982)}:	Результат = ВыполнитьКоманду(Команда,, Ложь);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(314)}:		Результат = Компонента.Нажатие(Кнопка);

```

Пример запроса ниже:

[КорректировкаПриобретения_ИР_ОшибкаКонструктораИР.zip](https://github.com/tormozit/RDT1C/files/11536270/_._.zip)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/963968
Можно исправить вставкой перед ошибочной строкой фрагмента
```
				Если СтрокаЗапроса.ТипЗапроса <> 1 Тогда
					Продолжить;
				КонецЕсли;
```

**Comment by tormozit** [comment]
Исправлено в 6.77
