### ISSUE TITLE
Различные значения колонки: ранжировать строки по длине

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#452]
В дин. списке товаров встал на "Наименование полное", вызвал команду различных и теперь хочу взглянуть на товары с самыми длинными наименованиями.
Просится аналог кнопки-короны, но если в таблице будет колонка отображающая длину значения то хватит и ее.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/964217

**Comment by tormozit** [comment]
Сделано в 6.77
