### ISSUE TITLE
Ошибка поиска в динамическом списке

### ISSUE THREAD

**Issue by VZhulanov1** [tormozit/RDT1C#453]
**Программное окружение**

Платформа: 8.3.20.1789
Режим БД: клиент-серверный
Конфигурация. Название: Конфигурация "Сервер обработки данных от аптек" (1.0)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Конфигурация 6.76.1
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Динамический список (упр.форму)
2. Выбрал нужный справочник. В строке поиска, либо просто в списке справочника набрал слово поиска **кат**
3. Получил окно с ошибкой 
Ошибка при выполнении запроса.
по причине:
Невозможно применить элемент отбора в наборе данных "(Адрес Содержит кат ИЛИ Версия данных Содержит кат ИЛИ ИД Содержит кат ИЛИ ИД из ЕС Содержит кат ИЛИ ИД из МДЛП Содержит кат ИЛИ Разархивировать прайс при получении и взять из архива файл Содержит кат ИЛИ Имя файла заявки Содержит кат ИЛИ Имя файла прайса Содержит кат ИЛИ ИНН Содержит кат ИЛИ Код Содержит кат ИЛИ Контроль номера накладной В списке  ИЛИ КПП Содержит кат ИЛИ Куда отправить заказ Содержит кат ИЛИ Наименование Содержит кат ИЛИ Накладные по ФТП Содержит кат ИЛИ (Настройки импорта эл.накладных.Наименование Содержит кат) ИЛИ (Настройки импорта отказов.Наименование Содержит кат) ИЛИ (Настройки импорта прайсов.Наименование Содержит кат) ИЛИ ОГРН Содержит кат ИЛИ ОКАТО Содержит кат ИЛИ ОКДП/ОКВЭД Содержит кат ИЛИ ОКОНХ Содержит кат ИЛИ ОКПО Содержит кат ИЛИ Описание Содержит кат ИЛИ Отказы по ФТП Содержит кат ИЛИ Полное наименование Содержит кат ИЛИ Прайс по ФТП Содержит кат ИЛИ (Преобразовывать прайсы.Наименование Содержит кат) ИЛИ (Родитель.Наименование Содержит кат) ИЛИ (Ссылка.Наименование Содержит кат) ИЛИ Телефон Содержит кат ИЛИ Тело файла заявки Содержит кат ИЛИ Фильтр накл адреса Содержит кат)"

**Ожидаемое поведение**
ожидалось что будет обычный поиск как в обычной управляемой форме списка справочника

**Comment by tormozit** [comment]
Строка поиска в динамическом списке обрабатывается полностью платформой.
Покажи картинку окна, чтобы было видно шапку и подвал целиком.
Покажи все колонки списка с типами значений.
Возникает ли ошибка в других справочниках/документах?
Если тот же справочник открыть в основной управляемой форме списка и повторить поиск, ошибка возникает?

**Comment by VZhulanov1** [comment]
Даже на простейшем справочнике ошибка возникает
При использовании основной формы списка ошибки нет при поиске

**Comment by tormozit** [comment]
Проблема актуальна?

**Comment by tormozit** [comment]
Скорее всего ошибка в платформе и связана с режимом совместимости.
