### ISSUE TITLE
Консоль заданий: очищать сообщения перед показом сообщений ФЗ

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#454]
Когда щелкаю мышкой по сообщениям, то они выводятся без предварительной очистки.
В результате после каждого клика остаются сообщения от предыдущего ФЗ, что сбивает с толку.
Хочу чтоб при клике всегда отображались только сообщения, относящиеся к строке в которой я кликнул.
![image](https://github.com/tormozit/RDT1C/assets/75837433/41434faf-1765-4f91-90b5-e5d0b31fc371)

**Comment by tormozit** [comment]
Сколько сообщений было выведено в предыдущем клике и в текущем?
Кажется что при малом количестве очистка скорее вредна, т.к. не позволит сопоставить тексты от разных фоновых заданий.
Для большого числа сообщений вывод в окно сообщений кажется не очень удобен даже с очисткой. Тут больше подойдет просмотр в отдельном окне, который кстати уже есть в форме фонового задания. Ты его пробовал?

**Comment by john-doe-1c** [comment]
По одному.
> не позволит сопоставить тексты от разных фоновых заданий

Это реально кому-то требуется?
> просмотр в отдельном окне, который кстати уже есть в форме фонового задания. Ты его пробовал?

Нет. У меня мало сообщений от каждого РЗ, но много самих РЗ, поэтому мне хочется быстро их просмотреть, не отвлекаясь на вывод остающийся после каждого просмотренного РЗ.

**Comment by tormozit** [comment]
В таком случае мне непонятно твое неудобство. Нужен снимок экрана поясняющий сложность в нахождении сообщений, выведенных последним кликом. Тем более ты не пробовал просмотр сообщений в отдельном окне.

**Comment by john-doe-1c** [comment]
Из-за верхних сообщений единственное интересующее меня последнее обрезано:
![image](https://github.com/tormozit/RDT1C/assets/75837433/9b8c51c3-a39c-4c8c-a161-15b5d5c70fec)

**Comment by tormozit** [comment]
Убедил. Создал задачу https://www.hostedredmine.com/issues/964557
Но замечу, что эта проблема растет из платформы. По непонятной причине она выводит в этой ситуации почему то только 2 сообщения от новой порции. Логичнее было бы, если бы приоритет отображения отдавался сообщениям новой порции.

**Comment by tormozit** [comment]
Реализовано в 6.78
