### ISSUE TITLE
Выгрузка в файл. Автоопределение выгружаемых типов

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#455]
Очень не хватает автоопределения выгружаемых типов при выгрузке данных в файл

![image](https://github.com/tormozit/RDT1C/assets/87958986/d1c0c1aa-0834-44d9-9eb4-2c1e4401c69f)

Если не указывать никакие типы, то например при проведении документа в другой базе могут создаваться новые Ключи Аналитики Учета Номенклатуры при формировании движений. При последующей загрузке документа с движениями в рабочую базу записывается несуществующая ссылка в движениях документа.

**Comment by tormozit** [comment]
Не понял. Что есть автоопределение типов, выгружаемых по ссылке?
Чем это отличается от выбора всех типов?

**Comment by PerlAmutor** [comment]
> Не понял. Что есть автоопределение типов, выгружаемых по ссылке? Чем это отличается от выбора всех типов?

Скорее всего ничем. Тут тогда нужен какой-то контроль на стороне загрузки, что в загружаемых данных присутствуют ссылки на несуществующие объекты. А вообще конечно в случае с загрузкой элемента справочника Ключи Аналитики Учета Номенклатуры в регистре сведений АналитикаУчетаНоменклатуры дополнительная запись на этот ключ скорее всего не появится автоматически и будут потом ошибки при проведении, либо потребуется исправление ключей.

Столкнулся еще с тем, что при массовой загрузке документов из .zip файла - отсутствует возможность выбора что грузить, а что нет. Т.е. я выгружал 10 документов, а потом задачу поменяли и сказали не грузить 1 один из них. А если таких документов много, то повторно их выгружать занимает время.

**Comment by tormozit** [comment]
Про выбор загружаемых объектов ты уже просил https://github.com/tormozit/RDT1C/issues/295 и зачем то закрыл заявку

**Comment by PerlAmutor** [comment]
> Про выбор загружаемых объектов ты уже просил #295 и зачем то закрыл заявку

Это было не про выбор, а про сравнение объектов базы с загружаемыми данными. А выбор это просто отметить галочками те объекты, которые я буду грузить из .zip файла.
