### ISSUE TITLE
Ошибка при выполнении запроса с настройками в консоли запросов

### ISSUE THREAD

**Issue by Absolemus** [tormozit/RDT1C#456]
**Программное окружение**

Платформа: 8.3.17.1549
Режим БД: клиент-серверный
Конфигурация. Название: Зарплата и управление персоналом для Казахстана, редакция 3.1 (3.1.1.87)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 204
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 6.75.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.75.1e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 11 Корпоративная 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ╥хъє∙р  ъюфютр  ёЄЁрэшЎр: 866
Клиент. ОС пинг сервера: 0мс
Сервер. ОС: Microsoft Windows Server 2019 Standard 64-bit НеРусский-0409
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Выбрал тип запроса "Компоновка"
3. Открыл вкладку "Компоновка"
4. Нажал на кнопку "Выполнить с настройками"
5. Получил ошибку
```
Значение не является значением объектного типа (Выгрузить)
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(2283)}:			СтрокаДерева.РазмерРезультата = РезультатЗапроса.Выгрузить()[0][0];
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(2255)}:			ОбновитьКоличествоСтрокРезультата(мРезультатПакета[ЭлементРезультата.Индекс], СтрокаДерева);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(2083)}:		ЗагрузитьРезультатПакета();
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(10466)}:	ВыполнитьЗапрос(,,,, Истина);
```

**Ожидаемое поведение**
Не получил ошибку

**Comment by tormozit** [comment]
Не удалось повторить ошибку. Нужен текст запроса и снимок всех страниц настроек компоновки. Желательно передать файл запросов.

**Comment by tormozit** [comment]
Эта ошибка исправлена в следующих версиях.
