### ISSUE TITLE
Сравнение таблиц: убирать из типа колонок "Нулл"

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#458]
Информация о допустимых типах колонок (полей сравниваемых таблиц) является важной при сопоставлении этих колонок (в ходе настройки сравнения).
Если источник сравниваемой таблицы - это запрос, то везде в типы ее колонок добавляется тип "Нулл", что в подавляющем большинстве моих случаев просто замусоривает восприятие этих колонок (т.к. нуллу там взяться неоткуда) и поэтому затрудняет процесс их сопоставления.

Хочу видеть нулл в типах колонки только если он действительно возможен в такой колонке. Пример, когда я хочу видеть нулл - это если один из источников - это таблица ВИДа, но и в этом случае я хочу видеть там нуллы только если у поля в метаданных стоит флажок "Разрешить нуллы", а сейчас в инструменте там везде добавляются нуллы, что заставляет меня волноваться пока я не вспомню что это "особенность" выгрузки результата запроса в ТЗ.

Поскольку после сохранения запроса ТЗ-источник формируется сразу (я вижу кол-во ее строк в поле у правого края экрана), то сузить типы по фактическому содержимому строк не кажется сложной задачей.

Загвоздка может оказаться разве что когда после настройки сопоставления я нажимаю "Сравнить таблицы", запросы выполняются повторно, соответственно ТЗ актуализируются и в актуальных строках могут уже реально оказаться Нуллы (а мы их ранее уже вырезали). Думаю, если такое случилось то надо обратить внимание пользователя на это, а лучше вообще прервать сравнение и показать предупреждение а-ля "_Тип значения в некоторых колонках расширился: в строках появились значения Null. Рекомендуется повторить настройку сравнения колонок._".

**Comment by tormozit** [comment]
Тебе надо срочно осваивать навык создания снимков экрана. Рекомендую программу https://getsharex.com/
Очень не хватает снимка экрана для наглядности.
Не вполне понятно, какие неудобства вызывает наличие этого типа. Почему так важно его удалять?

Полное сужение типов в общем случае - не быстрая операция, т.к. нужно обойти все значения всех колонок и перезагрузить каждую измененную колонку. Поэтому вызывать ее надо как можно реже и точечно.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/964736

**Comment by tormozit** [comment]
Реализовано в 6.79

**Comment by john-doe-1c** [comment]
> Очень не хватает снимка экрана для наглядности.
Не вполне понятно, какие неудобства вызывает наличие этого типа

Когда я ищу в нижней таблице колонку для сопоставления с верхней, то видеть там везде нуллы (да еще на разных позициях - то в начале, то в конце) - это последнее, что я хочу.
Найти глазами в таком винегрете заветную и единственную подходящую по типу "Булево" мне легче когда мусорных нуллов и "отступов" образуемых этими нуллами там нет:
![image](https://github.com/tormozit/RDT1C/assets/75837433/62545218-ce6a-4b6f-ad9a-8720bb9599c9)

**Comment by tormozit** [comment]
Создал задачу по улучшению представлений описаний типов https://www.hostedredmine.com/issues/965406
