### ISSUE TITLE
Консоль кода. Ошибка при проведении документа в отменяемой транзакции

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#459]
**Программное окружение**

Платформа: 8.3.21.1622
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.78.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИмяКомпании (1.1.1.0)
Расширения. зг_ЗУП (1.0.1.7)
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС Текущая кодовая страница: 866
Клиент. ОС выполнение BAT: Да
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыть инструмент Консоль Кода
2. Написать код получения и проведения объекта документа в отмененной транзакции (в моем случае это использовалось для отладки)
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/339ee596-f192-4d35-8056-4fe365718f5f)
3. Выполнить
4. Получить ошибку 
```
Редактор встроенный: Ошибка передачи переменной: Ошибка преобразования данных XDTO:
Запись значения свойства:
    форма: Элемент
    имя: {http://v8.1c.ru/8.1/data/core}Structure: Ошибка преобразования данных XDTO:
Запись значения свойства 'Value':
    форма: Элемент
    имя: {http://v8.1c.ru/8.1/data/core}Value
по причине:
Ошибка отображения типов:
Ошибка преобразования данных XDTO:
Запись значения свойства 'Value':
    форма: Элемент
    имя: {http://v8.1c.ru/8.1/data/core}Value
по причине:
Ошибка отображения типов:
Отсутствует отображение для типа 'РезультатЗапроса'
```

![изображение](https://github.com/tormozit/RDT1C/assets/16429518/c2ad2a21-4809-4e71-9b3d-3c1aef6ff1f5)

Эта ошибка возникает только если мы проводим документ. Если просто получим объект, то ошибки не возникнет, при этом имитатор будет заполнен.

**Ожидаемое поведение**
Отсутствие такой ошибки.

**Способ обхода**
Присваиваем объекту неопределено после проведения

**Comment by tormozit** [comment]
Нужный текст проблемного кода

**Comment by KovAlexey** [comment]
Если я правильно понял сказанное выше. то вот
```
НачатьТранзакцию();
док = п1.ПолучитьОбъект();   
Док.Записать(РежимЗаписиДокумента.Проведение);
ОтменитьТранзакцию();
```
Где п1 - это ссылка на любой документ.

В данном случае ПриобретениеТоваровУслуг конфигурации Комплексная автоматизация

**Comment by KovAlexey** [comment]
В таком виде работает
```
НачатьТранзакцию();
док = п1.получитьОбъект();   
ОтменитьТранзакцию();
```

В таком виде тоже
```
НачатьТранзакцию();
док = п1.получитьОбъект();   
Док.Записать(режимЗаписиДокумента.Проведение);
Док = Неопределено;
ОтменитьТранзакцию();
```

**Comment by tormozit** [comment]
включи режим выполнения через внешнюю обработку, открой ее в отладчике и установи точку останова на последней строке твоего кода, запусти выполнение кода, в точке останова покажи свойства "док.ДополнительныеСвойства". Похоже там сидит объект "РезультатЗапроса", помещаемый туда обработкой проведения. Если так, то можно в твой код добавить очистку этого объекта.

**Comment by KovAlexey** [comment]
Да, и правда.
Спасибо
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/df2d263b-dc22-4521-a01d-51e7862738a2)

**Comment by KovAlexey** [comment]
я зря закрыл?

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/964790

**Comment by tormozit** [comment]
Исправлено в 6.79
