### ISSUE TITLE
Подсказка к шаблону вызова отладочных функций расширения

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#46]
Перешел от использования встроенной подсистемы к использованию расширения.
В подсистеме привык к коротким именам функций отладки. В расширении такая возможность исчезла - приходится дописывать "ирОбщий.":
![image](https://user-images.githubusercontent.com/75837433/132471257-d1c62cab-a103-4588-8339-102ec82b9006.png)

Чтобы сгладить дискомфорт от такого лишения и предотвратить появление вопросов, почему так стало, предлагаю добавить в подсказку к шаблону объяснение такого поведения (про невозможность иметь глобальные серверные модули в расширении).

**Comment by tormozit** [comment]
Согласен. Добавлю такое пояснение.

**Comment by tormozit** [comment]
Сделал в 6.09.1
