### ISSUE TITLE
Журнал Регистрации. Получение элемента по индексу для значения не определено

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#460]
https://github.com/tormozit/RDT1C/assets/87958986/22fa1db9-04c6-4c26-a1cd-e097e6ff0315

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.53)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.78.2p
Инструменты разработчика. Инструмент: Анализ журнала регистрации
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Журнал Регистрации
2. Выбрал событие
3. В открывшемся диалоге перешел на вкладку "Подробно"
4. Два раза кликнул на любую ячейку табличного поля с колонками "Свойство" и "Представление значения"
5. Получил ошибку

```
Получение элемента по индексу для значения не определено
{ВнешняяОбработка.ирАнализЖурналаРегистрации.Форма.ФормаСобытия.Форма(170)}:	ЗначениеСвойства = ДанныеСобытия[ВыбраннаяСтрока.Свойство];

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.79

**Comment by PerlAmutor** [comment]
> Исправлено в 6.79

Не похоже


https://github.com/tormozit/RDT1C/assets/87958986/3088e497-036e-42fa-be3c-c4ce642f6e66

**Comment by tormozit** [comment]
Ошибку воспроизвел.
