### ISSUE TITLE
Ошибка несоответствия протокола отладки

### ISSUE THREAD

**Issue by GladilovDmitry** [tormozit/RDT1C#462]
**Программное окружение**
Платформа: 8.3.22.1923
Режим БД: клиент-серверный
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Режим совместимости: Версия8_3_17
Инструменты разработчика. Версия: Расширение 6.73.1e
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ...
Клиент. Отладка разрешена: Да
Клиент. ОС: Microsoft Windows 10 Enterprise 64-разрядная Русский
Сервер. ОС: Microsoft Windows Server 2016 Datacenter 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: http
Отладка тонкого клиента УФ.

**Воспроизведение проблемы**
1. В конфигураторе вношу изменения в свое расширение
2. Выполняю запуск отладочного сеанса из конфигуратора по кнопке F5
3. Получаю ошибку "Неверно указан протокол отладки: на сервере - "http", в запускаемом приложении - "tcp""
Ошибка плавающая, проявляется в 3-5 случаях из 10. Для воспроизведения вносил изменение в модуль своего расширения, например добавить и удалить пустую строку.

**Ожидаемое поведение**
Запуск сеанса без ошибок.

**Доп.инфо**
Ошибка указана в https://partners.v8.1c.ru/forum/topic/2135488
Сравнил строки запуска из диспетчера задач:

Нормальная:
Имя	ИД процесса	Состояние	Имя пользователя	ЦП	Выделенная память	Командная строка
1cv8c.exe	20472	Выполняется	Iam	00 	123 276 К	"C:\Program Files\1cv8\8.3.22.1923\bin\1CV8C.exe" /IBName" zup" /UseHwLicenses+ /TComp -SDC /C"РежимОтладки"  /Lru /VLru /DisableStartupMessages /DisplayPerformance /TechnicalSpecialistMode /EnableCheckModal /EnableCheckExtensionsAndAddInsSyncCalls /DEBUG -http -attach /DEBUGGERURL"http://1C:1550"   /O Normal

Проблемная:
Имя	ИД процесса	Состояние	Имя пользователя	ЦП	Выделенная память	Командная строка
1cv8c.exe	16588	Выполняется	Iam00 	69 752 К	"C:\Program Files\1cv8\8.3.22.1923\bin\1CV8C.exe" ENTERPRISE /IBName"zup" /O Normal /UseHwLicenses+ /TechnicalSpecialistMode /DisplayPerformance /EnableCheckModal /EnableCheckExtensionsAndAddInsSyncCalls /TComp -SDC /DEBUG -http -attach /DEBUGGERURLhttp://1C:1550 /DisableStartupMessages /Lru  /CНеДобавлятьРолиИР /DEBUG 

В проблемной:
  - ошибка в строке
    - DEBUGGERURL - написано слитно с http://1C:1550`
  - добавились:
    - ENTERPRISE
    - /DEBUG - второй раз в конце строки
    - /CНеДобавлятьРолиИР
  - пропали флаги:
    - /C"РежимОтладки"
    - /VLru
  - изменен порядок следования большинства флагов, причем не только сдвиг на позицию добавленных.

**Comment by tormozit** [comment]
Если есть возможность проверь на последней версии ИР. Вечером посмотрю подробнее.

**Comment by GladilovDmitry** [comment]
Обновил ИР. Со второй попытки проблема проявилась такая же.

**Comment by tormozit** [comment]
Описанный тобой перезапуск сеанса я делаю очень простым кодом в методе ирКлиент.ПерезапуститьСеансПослеДобавленияРолиЛкс :
```
	ПараметрыЗапуска = " /CНеДобавлятьРолиИР /DEBUG ";
	ЗавершитьРаботуСистемы(Ложь, Истина, ПараметрыЗапуска);
```
Поэтому основную порчу (удаление двойных кавычек вокруг адреса отладчика) командной строки делает сама платформа. Попробуй из консоли кода выполнить этот код.

**Comment by tormozit** [comment]
Пропажу фрагмента "/C"РежимОтладки"" устраню https://www.hostedredmine.com/issues/965079 . 
Остальные изменения командной строки не существенны.

**Comment by tormozit** [comment]
Ты предоставил недостаточно информации о конфигурации. Нужно обязательно сообщить версию БСП.
Для борьбы с наглостью БСП я сделал https://www.hostedredmine.com/issues/959441 . Но это к сожалению не помогло решить проблему полностью. Иногда она все равно удаляет роль подсистемы. Поэтому иногда происходит умышленный авто перезапуск сеанса при старте приложения после того, как ИР обнаруживает отсутствие своей роли у пользователя http://devtool1c.ucoz.ru/forum/2-2196-1 .

**Comment by tormozit** [comment]
Описал подробно причину авто добавления роли со стороны ИР в пожелании на ту же тему для БСП https://github.com/SeiOkami/OneS/issues/223

**Comment by tormozit** [comment]
В качестве временного решения проблемы с удалением роли расширения в БСП сделал отдельное расширение http://devtool1c.ucoz.ru/load/osnovnye/zashhita_rolej_rasshirenij_bsp_3_1_0/1-1-0-25

**Comment by tormozit** [comment]
Пропажа фрагмента "/C"РежимОтладки"" устранена в 6.80

**Comment by GladilovDmitry** [comment]
БСП 3.1.7.294

**Comment by tormozit** [comment]
Проблема решена?
