### ISSUE TITLE
Консоль запросов, обработка результата: открывать алгоритм с учетом кнопки "На сервере"

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#463]
Сейчас алгоритм открывается в режиме выполнения "Клиент" независимо от нажатости кнопки "На сервере":
![image](https://github.com/tormozit/RDT1C/assets/75837433/4dcd08d8-669c-46a9-a1d9-d66d5a90b297)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/965081

**Comment by tormozit** [comment]
Исправлено в 6.80
