### ISSUE TITLE
Консоль запросов. Значение не является значением объектного типа (Количество)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#464]
https://github.com/tormozit/RDT1C/assets/87958986/3c544e3a-1216-4290-8d8b-666666451842

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.79.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл Консоль запросов
2. Вызвал команду " \ Командная панель \ Сохранить объект "
3. Открылся диалог. Выбрал "Отмена"
4. Получил ошибку

![image](https://github.com/tormozit/RDT1C/assets/87958986/e0cfea7c-07c9-4f4a-a246-b176922e7497)

```
Значение не является значением объектного типа (Количество)
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(2244)}:	Для НомерРезультата = 1 По мРезультатПакета.Количество() Цикл
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(2063)}:		мРезультатЗапроса = мРезультатПакета[ПолучитьИндексПоследнегоРезультатЗапросаИзРезультатаПакета()];
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(10247)}:	ВыполнитьЗапрос(,,, Истина);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/965086

**Comment by tormozit** [comment]
Исправлено в 6.79.2
