### ISSUE TITLE
Интерфейсная панель. Выгрузить БД без блокировки

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#465]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.79.1p
Инструменты разработчика. Инструмент: Интерфейсная панель
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
Столкнулся со следующими проблемами при использовании команды "Выгрузить БД без блокировки", которая использует ibcmd.
1. Нет возможности указать где-то Имя пользователя и Пароль от Информационной базы 1С. Без этого база не выгружается...
2. По-умолчанию в параметры командной строки почему-то подставляются параметры соединения к рабочей базе. Хотя я запускал на копии базы. Нет возможности где-то указать имя сервера и имя базы до запуска утилиты
3. ИР ищет утилиту ibcmd на клиенте. Но она ставится с серверной частью платформы. Возможности запуска на стороне сервера с выгрузкой в сетевой каталог нет.

![image](https://github.com/tormozit/RDT1C/assets/87958986/1ef06cd1-e7dc-49ca-b636-3201172cab6a)

**Comment by tormozit** [comment]
Забыл в подсказке написать. Текущий подход к вызовам утилиты ibcmd использует в клиент-серверном варианте общие параметры СУБД.

**Comment by PerlAmutor** [comment]
> Забыл в подсказке написать. Текущий подход к вызовам утилиты ibcmd использует в клиент-серверном варианте общие параметры СУБД.

Вот только там нет возможности заполнить логин и пароль от базы, а не от SQL сервера.

**Comment by tormozit** [comment]
Запуск на стороне сервера с выгрузкой в сетевой каталог не планирую делать. Достаточно установить серверную часть на компьютер клиента.

**Comment by tormozit** [comment]
Запуск на стороне сервера с выгрузкой в сетевой каталог не планирую делать. Достаточно установить серверную часть на компьютер клиента либо запустить инструменты на компьютере сервера приложений.

**Comment by tormozit** [comment]
Создал задачу для ввода имени и пароля 1С и проверки соединения СУБД
https://www.hostedredmine.com/issues/965089

**Comment by tormozit** [comment]
Реализовано в 6.80
