### ISSUE TITLE
Конструктор запросов ИР. Отбор по периоду

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#466]
В инструменте "Конструктор запросов ИР" хотелось бы иметь команду, которая добавляет условие по периоду и устанавливает Параметры - Стандартный период

![image](https://github.com/tormozit/RDT1C/assets/87958986/ac89c908-ee8c-4f3c-8c41-a0af4d7204f0)

![image](https://github.com/tormozit/RDT1C/assets/87958986/3dbd4f98-95c9-453d-bb1a-30d3702637bf)

Очень часто приходится такие условия писать вручную по реквизитам Период в регистрах и Дата в документах.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/966086

**Comment by tormozit** [comment]
Сделано в 6.83
