### ISSUE TITLE
Конструктор запросов ИР. "Показывать индексы" добавляет несуществующее поле.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#467]
https://github.com/tormozit/RDT1C/assets/87958986/6cadacf9-07dd-4ff3-b7ac-c75273fdec30

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.79.1p
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Включил настройку "Показывать индексы" в "Конструкторе запросов ИР"
2. Отключил кнопку "Автополе"
3. В запрос добавляется несуществующее поле "_Индексы"
4. После этого запрос становится не рабочим

**Comment by tormozit** [comment]
Хорошо, что ты освоил визуализатор действий мыши. По умолчанию он использует слишком большую непрозрачность.
Рекомендую установить половинную непрозрачность (opacity). Иначе тяжеловато разглядывать самую важную область - вокруг указателя мыши. 
К сожалению эта программа визуализации не имеет портативного режима и хранит свои настройки в профиле пользователя. Поэтому легко копировать ее настройки не получится.

![изображение](https://github.com/tormozit/RDT1C/assets/11896251/2ba47eda-aabe-4327-9aba-c6ae9e47a91d)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/965084

**Comment by tormozit** [comment]
Исправлено в 6.80
