### ISSUE TITLE
Не устанавливается план запроса из MSSQL

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#469]
**Программное окружение**

Платформа: 8.3.21.1709
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.80.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ПатчДоставка ()
Расширения. ПатчРаспределениеУдержаний ()
Расширения. ПатчУскорениеПроизводительностиЗагрузки ()
Расширения. З (1.1.1.5)
Расширения. зг_ЗУП (1.0.2.2)
Расширения. ЭР_Обмен_КА_БП (1.0.2.11)
Расширения. YAXUNIT ()
Расширения. ИнструментыРазработчикаTormozit (6.80.2e)
Расширения. МаркетКоннекторКА2 (1.0.2.2)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
План запроса:
[ПланЗапрос.zip](https://github.com/tormozit/RDT1C/files/11829830/default.zip)

Т.к. по логике я догадываюсь. что без нее никак, прикладываю схему БД:
[Схема.zip](https://github.com/tormozit/RDT1C/files/11829832/default.zip)

1. Открываем План Запроса MSSQL 
2. Жмем "Установить"
2. Вставляем XML план запроса
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/f4b7ea53-0295-4c26-9f5b-321d755ff8af)
3. Жмем ОК.
4. Получаем ряд ошибок:
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/564bd366-c876-428a-9653-aa76243b8296)
`Преобразование значения к типу Число не может быть выполнено
{ИнструментыРазработчикаTormozit Обработка.ирАнализТехножурнала.Форма.ПланЗапросаMSSQL.Форма(72)}:СтрокаЗначения = Число(Фрагменты[0]) * pow(10, Число(Фрагменты[1]));
{ИнструментыРазработчикаTormozit Обработка.ирАнализТехножурнала.Форма.ПланЗапросаMSSQL.Форма(202)}:УстановитьПлан();
`
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/f4ca1bbf-b6f9-4239-b858-f826a3f4b262)
`Значение не является значением объектного типа (Картинка)
{ИнструментыРазработчикаTormozit Обработка.ирАнализТехножурнала.Форма.ПланЗапросаMSSQL.Форма(136)}:Если ТипЗнч(СтрокаСловаря.Картинка) = Тип("Картинка") Тогда
`

**Ожидаемое поведение**

Отсутствие ошибок или внятное их описание.

**Comment by tormozit** [comment]
Обработку установки некорректного текста улучшу https://www.hostedredmine.com/issues/965394
Подсказку кнопки тоже детализирую.
XML формат плана запроса этой командой не поддерживается и делать это не вижу смысла. Если ты его видишь, обоснуй.

**Comment by tormozit** [comment]
Плохо, что ты не указал текст ошибки. Другие пользователи не смогут найти эту заявку по нему.

**Comment by KovAlexey** [comment]
> Плохо, что ты не указал текст ошибки. Другие пользователи не смогут найти эту заявку по нему.

Указал

**Comment by KovAlexey** [comment]
>  XML формат плана запроса этой командой не поддерживается и делать это не вижу смысла. Если ты его видишь, обоснуй.

В SQL Management Studio это стандартный формат. 
Например, запрос по выполняющимся сейчас запросам с планом выдаст именно XML. 

```
SELECT
	DB_NAME(ex.database_id) AS DB_Name,
	ex.start_time,
	ex_plans.query_plan,
	ex_texts.text,
	ex.session_id
FROM 
 sys.dm_exec_requests as ex
	CROSS APPLY sys.dm_exec_query_plan(plan_handle) AS ex_plans
	CROSS APPLY sys.dm_exec_sql_text(sql_handle) AS ex_texts

 order by start_time

```


![изображение](https://github.com/tormozit/RDT1C/assets/16429518/79b248a5-6eaa-426d-91fd-3875552c8dd9)

И я что-то не вижу вариантов сохранить в другом формате и гуглом найти не могу. Подскажешь? Хотя бы правильное название другого формата, чтоб указать мне направление куда идти не в грубой форме=)
Пока нашел только SET SHOWPLAN_TEXT, но это не то

**Comment by tormozit** [comment]
Не вижу смысла гоняться за текстовым форматом плана и смотреть его во встроенном форме ИР, когда есть подробный (XML) формат. Конвертируй подробный формат плана и смотри его родным средством СУБД. Текстовый формат собирается техножурналом и именно поэтому сделана форма для его просмотра в ИР, т.е. для случая отсутствия прямого доступа к СУБД и к XML форматам планов.

SET SHOWPLAN_TEXT - да, это правильное направление. Рекомендую чат https://t.me/OneC_Expert

**Comment by KovAlexey** [comment]
>Не вижу смысла гоняться за текстовым форматом плана и смотреть его во встроенном форме ИР, когда есть подробный (XML) формат. Конвертируй подробный формат плана и смотри его родным средством СУБД. Текстовый формат собирается техножурналом и именно поэтому сделана форма для его просмотра в ИР, т.е. для случая отсутствия прямого доступа к СУБД и к XML форматам планов.

В принципе, да. Ты прав. 
Мне требовалось все таки именно конвертнуть план в имена метаданных.  А меня уже не туда понесло.

**Comment by tormozit** [comment]
Исправлено в 6.81
