### ISSUE TITLE
Проблема ширины столбцов окна сравнения результата запросов

### ISSUE THREAD

**Issue by zsa2000** [tormozit/RDT1C#47]
Портативный 6.08.1p

При сравнении в консоле запросов результатов выполнения через функцию - "Сравнить результат с предыдущим переданным" в окне сравнения столбцы таблиц имеют минимальную ширину. Возможности увеличить ширину столбцов не нашел. 
![image](https://user-images.githubusercontent.com/8749552/132496735-eb7f0c24-debe-4856-bf25-9f36b9b7583e.png)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932943

**Comment by tormozit** [comment]
Исправлено в 6.08.2
