### ISSUE TITLE
Не форматируется большой запрос в конверторе текста СУБД

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#470]
**Программное окружение**

Получить эту информацию можно кнопкой "Техническая информация" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1

**Воспроизведение проблемы**
План запроса:
[ПланЗапрос.zip](https://github.com/tormozit/RDT1C/files/11829830/default.zip)

Т.к. по логике я догадываюсь. что без нее никак, прикладываю схему БД:
[Схема.zip](https://github.com/tormozit/RDT1C/files/11829832/default.zip)

1. Открываем Конвертор текста БД
2. Вставляем запрос СУБД
3. Устанавливаем галочку "Пересборка текста"
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/16c31af5-dbdc-4d0d-8f54-107b7ded5f49)
4. Жмем преобразовать
5. Получаем ошибку (при этом текст преобразован, но не отформатирован)
`Строка 1: {(1,2 260)}: Синтаксическая ошибка "(", ожидается: <EOF>, <->, <##>, <#EmbeddedQuery>, <#UnionPart>, <)>, <*>, <,>, <.>, <.*>, </>, <::>, <;>, <||>, <+>, <AND>, <AS>, <ASC>, <AUTOORDER>, <AVG>, <BadID>, <BEGIN>, <BEGINOFPERIOD>, <BETWEEN>, <COMP_OPERATOR>, <COUNT>, <DATE>, <DATEADD>, <DATEDIFF>, <DATETIME>, <DAY>, <DAYOFYEAR>, <DESC>, <ELSE>, <END>, <ENDOFPERIOD>, <ESCAPE>, <FOR>, <FROM>, <FULL>, <GROUP>, <HAVING>, <HIERARCHY>, <HIERARCHYON>, <HOUR>, <id>, <IN>, <INDEX>, <INNER>, <INTO>, <IS>, <ISNULL>, <JOIN>, <LEFT>, <LIKE>, <LIMIT>, <MAX>, <MIN>, <MINUTE>, <MONTH>, <NOT>, <NUMBER>, <OFFSET>, <ON>, <ONLY>, <OR>, <ORDER>, <PERIODS>, <PRESENTATION>, <PRESENTATIONREFS>, <QUARTER>, <REF>, <REFS>, <RIGHT>, <SECOND>, <SELECT>, <STRING>, <SUBSTRING>, <SUM>, <TABLE>, <THEN>, <TOTALS>, <TYPE>, <UNION>, <UPDATE>, <UPPER>, <UUID>, <VALUE>, <VALUETYPE>, <WEEK>, <WEEKDAY>, <WHEN>, <WHERE>, <WITH>, <YEAR>`
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/5543fa11-0224-438b-842b-8eb1ccc47d89)

**Ожидаемое поведение**

Форматированный текст запроса

**Comment by tormozit** [comment]
"Пересборка текста" как написано в подсказке выполняет полный разбор **текста запроса**, а текста не плана запроса. Основная же функция этой формы - "Перевод в мета" - поддерживает произвольные тексты БД. Поэтому сними флажок "Пересборка текста".

**Comment by KovAlexey** [comment]
В данном случае я копирую именно текст запроса. А не плана запроса.
Если я удалю блок параметров и оставлю только select и далее, то результат будет тем же.

**Comment by KovAlexey** [comment]
Я по ошибке прикрепил архив, который содержит в том числе и план.
Но там два файла. Текст Запроса и план запроса 

И моей целью и было его, в том числе, отформатировать.

**Comment by tormozit** [comment]
Создал задачу на улучшение форматирования https://www.hostedredmine.com/issues/965396

**Comment by tormozit** [comment]
Реализовано в 6.81
