### ISSUE TITLE
Статистика по запросам СУБД.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#471]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.80.1p
Инструменты разработчика. Инструмент: Статистика по запросам СУБД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

Пожелания:
1. При открытии текста запроса проверять, что у запроса есть План Запроса и передавать в "Конвертер текста БД" текст запроса с Параметрами из плана.
2. При открытии Плана Запроса сейчас открывается Внешний инструмент просмотра (SQL Management Studio, SQL Plan Explorer и т.п.). Хотелось бы иметь возможность открыть План через инструмент - "План запроса MSSQL" прямо из отчета.
3. Слишком длинные планы запросов в отчете обрезаются и их невозможно потом открыть из отчета. Хотя в Mangement Studio тот же план запроса полученный через DMV не обрезан.

**Comment by tormozit** [comment]
1. Опиши подробнее в отдельном пожелании. Приложи картинку, текст запроса и план и покажи для них что нужно сделать.
2. План запроса MSSQL может быть представлен в двух форматах - txt (текстовый) и xml (подробный). Встроенное средство просмотра плана запроса (форма "План запроса MSSQL") поддерживает только текстовый формат. Делать в нем поддержку подробного формата я не планирую. А отчет "Статистика по запросам СУБД" умеет доставать только подробный формат планов. Вообще не очень понятно зачем использовать текстовый формат плана, когда есть подробный, для которого есть не только штатный визуализатор SQL Management Studio.
3. Опиши проблему подробнее в отдельной заявке. Приложи текст плана полученный через DMV.
