### ISSUE TITLE
Консоль кода. Модуль. Сервер. Слишком много фактических параметров

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#473]
https://github.com/tormozit/RDT1C/assets/87958986/fe1d55c5-fee6-48a2-acc2-a759dca4c5a5

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.82.1p
Инструменты разработчика. Инструмент: Консоль кода
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Консоли кода создал алгоритм с типом "Модуль"
2. Переключил выполнение на "Сервер"
3. Вызвал "Выполнить"
4. Получил ошибку:

```
Слишком много фактических параметров
{ВнешняяОбработка.ирКонсольКода.МодульОбъекта(28)}:		КонтекстВыполнения.ВыполнитьАлгоритмЧерезВнешнююОбработкуЛкс(Параметры.ИмяФайлаВнешнейОбработки, Параметры.СтруктураПараметров, Параметры.ВремяНачала, Параметры.ВерсияАлгоритма,
{(1)}:Обработка.ВыполнитьАлгоритмВКонтексте(ПараметрыЗадания)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(21984)}:		Результат = Вычислить("Обработка." + ИмяМетодаОбработки + "(ПараметрыЗадания)");
{ВнешняяОбработка.ирКонсольКода.Форма.Форма.Форма(569)}:		ирОбщий.ВыполнитьЗаданиеФормыЛкс("ВыполнитьАлгоритмВКонтексте", ПараметрыЗадания, ЭтаФорма, "ВыполнитьАлгоритм",, Кнопка, "ВыполнитьАлгоритмВФонеЗавершение",
{ВнешняяОбработка.ирКонсольКода.Форма.Форма.Форма(508)}:	ИнформацияОбОшибке = ВыполнитьЛокальноПоСтруктуреПараметров(ТекстДляВыполнения, СтруктураПараметров, ЛиСинтаксическийКонтроль, ВерсияАлгоритма, выхИнформацияОбОшибке);
{(1)}:КонтекстВыполнения.ВыполнитьЛокально(ТекстДляВыполнения, ЛиСинтаксическийКонтроль)
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(5684)}:		ИнформацияОбОшибке = Вычислить("КонтекстВыполнения." + МетодВыполнения + "(ТекстДляВыполнения, ЛиСинтаксическийКонтроль)");
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2236)}:		мПлатформа.ВыполнитьПрограммныйКодВКонтексте(КонтекстВыполнения, МетодВыполнения, ТекстДляВыполнения, ЛиСинтаксическийКонтроль);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1104)}:			ВыполнитьПрограммныйКод();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1017)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольКода.Форма.Форма.Форма(67)}:	ПолеТекстаАлгоритма.Нажатие(Кнопка, ПолеТекстаАлгоритма.ЭтоМодуль);
```

**Comment by tormozit** [comment]
Исправлено в 6.82.2 https://www.hostedredmine.com/issues/965762
