### ISSUE TITLE
Отладить отложенный объект. Ошибка восстановления временной таблицы

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#475]
https://github.com/tormozit/RDT1C/assets/87958986/44245c0c-c7a7-4278-9243-8895d41ff308

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.82.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Перестала работать отладка отложенного объекта где-то с версии ИР 6.77p
2. Код для воспроизведения:

```
Запрос = Новый Запрос;
Запрос.МенеджерВременныхТаблиц = Новый МенеджерВременныхТаблиц;
Запрос.Текст = "ВЫБРАТЬ ВЫБОР КОГДА 1 ТОГДА ЗНАЧЕНИЕ(Справочник.Организации.ПустаяСсылка) КОГДА 2 ТОГДА ЗНАЧЕНИЕ(ПланВидовХарактеристик.СтатьиРасходов.ПустаяСсылка) ИНАЧЕ NULL КОНЕЦ КАК Поле ПОМЕСТИТЬ ВтДанные1 ОБЪЕДИНИТЬ ВСЕ ВЫБРАТЬ NULL";
РезультатЗапроса = Запрос.Выполнить();
Запрос.Текст = 
"ВЫБРАТЬ
|	*
|ПОМЕСТИТЬ ВтДанные3
|ИЗ
|   ВтДанные1 КАК Т
|";

ф = иробщий.ОтЛкс(Запрос,,, Истина);
```

```
Ошибка восстановления временной таблицы "ВтДанные1": {ВнешняяОбработка.ирОбщий.МодульОбъекта(26196)}: Ошибка при вызове метода контекста (Выполнить): {(2, 9)}: Поле не найдено "Поле"
ВЫБРАТЬ <<?>>Поле ПОМЕСТИТЬ _Т3463 ИЗ &ВтДанные1 КАК Т;

```

Похоже проблемный участок в ИрОбщий.СоздатьВременнуюТаблицуЗапросаИзТаблицыЗначенийЛкс()
Тут колонка удаляется из Таблицы Значений:

![image](https://github.com/tormozit/RDT1C/assets/87958986/bf54a3bc-091d-4e0b-a0bf-2652d99854ea)

Но в переменной "ПоддерживаемыеКолонки" она продолжает присутствовать.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/965846

Пробуй новый код
[Clip_452942.txt](https://github.com/tormozit/RDT1C/files/11940199/Clip_452942.txt)

**Comment by PerlAmutor** [comment]
На этом коде вроде работает. Спасибо. Попробую еще потестить на других запросах.
Тут видимо пора автотесты начать писать.

**Comment by PerlAmutor** [comment]
К сожалению исправление не работает, теперь другую ошибку выдает.

```
Ошибка восстановления временной таблицы "ВТ": {ВнешняяОбработка.ирОбщий.МодульОбъекта(26184)}: Ошибка при вызове метода контекста (Выполнить): {(3, 2)}: Тип не может быть выбран в запросе
<<?>>НЕОПРЕДЕЛЕНО КАК ф1

```

Вот проверочный код:

```
Запрос = Новый Запрос;
Запрос.МенеджерВременныхТаблиц = Новый МенеджерВременныхТаблиц;
Запрос.Текст = 
"выбрать НЕОПРЕДЕЛЕНО как ф1
|ПОМЕСТИТЬ вт
|ГДЕ ЛОЖЬ";
Запрос.Выполнить();
Запрос.Текст = 
"ВЫБРАТЬ
|	Т.ф1 КАК ф1
|ПОМЕСТИТЬ ВТ2
|ИЗ
|	(ВЫБРАТЬ
|		Т1.ф1 КАК ф1
|	ИЗ
|		ВТ КАК Т1
|	ОБЪЕДИНИТЬ
|	ВЫБРАТЬ
|		ЗНАЧЕНИЕ(Справочник.Организации.ПустаяСсылка) КАК ф1) КАК Т
|ИНДЕКСИРОВАТЬ ПО
|	Ф1
|";

ф = иробщий.ОтЛкс(Запрос,,, Истина);
```

**Comment by tormozit** [comment]
Обновил тест. Сделал новый вариант исправления.
[Clip_454077.txt](https://github.com/tormozit/RDT1C/files/11985912/Clip_454077.txt)

**Comment by tormozit** [comment]
Исправлено в 6.83
