### ISSUE TITLE
Добавить поддержку всех стандартных хранилищ в «Редактор хранилищ настроек (ИР)»

### ISSUE THREAD

**Issue by igor11176** [tormozit/RDT1C#476]
Добавить в «**Редактор хранилищ настроек (ИР)**» возможность работы со следующими стандартными хранилищами:
- _ХранилищеПользовательскихНастроекДинамическихСписков_ (доступно с 8.3.3)
- _ХранилищеВнешнихДанныхНавигационныхСсылок_ (доступно с 8.3.19)

![ХранилищеПользовательскихНастроекДинамическихСписков](https://github.com/tormozit/RDT1C/assets/28685268/95024df8-98d7-4b23-ad7f-3211cebceed0)

**Comment by PerlAmutor** [comment]
В ERP даже такая функция есть:

![image](https://github.com/tormozit/RDT1C/assets/87958986/1a43bec7-3612-4711-aead-2f4f923be76b)
![image](https://github.com/tormozit/RDT1C/assets/87958986/810865c6-d79a-4eb2-a406-8fb0b049e066)

Да, странно, что в ИР нету, этот менеджер аж с версии 8.3.3 доступен, только сейчас обнаружили пропажу ))

![image](https://github.com/tormozit/RDT1C/assets/87958986/38f7f1bb-c0a6-4fc8-8c96-541b0cf1b1bb)

В ИР на данный момент есть только эти хранилища, но этот список должен заполняться динамически с учетом на версию платформы, в 8.2. хранилищ меньше.

![image](https://github.com/tormozit/RDT1C/assets/87958986/85be908c-af4b-41d3-aac9-3b6dbac37031)

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/966025

**Comment by PerlAmutor** [comment]
> Создал задачу https://www.hostedredmine.com/issues/966025

А ХранилищеВнешнихДанныхНавигационныхСсылок не будешь добавлять?

**Comment by tormozit** [comment]
Сделано в 6.83
