### ISSUE TITLE
Редактор объекта БД. Ссылки на объект. Критерии отбора. Поле объекта не обнаружено (ЗамерПоиска)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#477]
https://github.com/tormozit/RDT1C/assets/87958986/c6d03069-5153-44c4-af4b-60086e7423e3

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.82.2p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Редактор объекта БД выбрал документ
2. Перешел на вкладку "Ссылки на объект"
3. Переключился на вкладку "Критерии отбора"
4. Получил ошибку:

```
Поле объекта не обнаружено (ЗамерПоиска)
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4787)}:		ирКлиент.ОткрытьЗамерПоискаСсылокЛкс(РезультатЗадания.ЗамерПоиска);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4735)}:		ПоискСсылокЗавершитьВФорме(, РезультатЗадания);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(6143)}:	КП_СсылкиНаОбъектОбновить();

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/966085

**Comment by tormozit** [comment]
Исправлено в 6.83
