### ISSUE TITLE
Консоль запросов. Автосохранение.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#478]
https://github.com/tormozit/RDT1C/assets/87958986/5e227f20-59e7-4e55-bdb8-b3d763130faf

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.82.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Если открыть файл запросов и переключится в структуре запросов на подзапрос
2. Сделать в нем изменения
3. Подождать 30 секунд
4. Включается автосохранение
5. При этом нет возможности внести эти изменения в основной файл, т.к. он закрывается

**Comment by tormozit** [comment]
Пробуй такое исправления для модуля формы консоли 
[Clip_453812.txt](https://github.com/tormozit/RDT1C/files/11971805/Clip_453812.txt)

Впервые столкнулся с такой ошибкой в файловой базе да еще при отсутствии расширений
![изображение](https://github.com/tormozit/RDT1C/assets/11896251/0df2661c-5a23-479e-8801-686eb5909b25)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/966081

**Comment by tormozit** [comment]
Исправлено в 6.83
