### ISSUE TITLE
Конструктор запросов ИР. Отбор по периоду

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#479]
https://github.com/tormozit/RDT1C/assets/87958986/514d0bf7-a013-453e-9101-aa723a861f93

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.83.1p
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл "Конструктор запросов ИР"
2. Перешел на вкладку Отбор
3. Вызвал команду "Период"
4. Получил ошибку:

```
Поле объекта не обнаружено (Представление)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(12900)}:	Если Ложь
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2818)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1064)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1017)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(322)}:		Результат = Компонента.Нажатие(Кнопка);

```

**Comment by tormozit** [comment]
Исправлено в 6.83.3
