### ISSUE TITLE
Конструктор запросов ИР. Ошибка при завершении работы системы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#48]
https://user-images.githubusercontent.com/87958986/132544955-1d2c7cc0-eb72-415c-ab00-4dea26416928.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.08.1p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При завершении работы системы по требованию сервера возникает ошибка в модальной форме Конструктора Запросов ИР:

```
Значение не является значением объектного типа (ТекущийЭлемент)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1130)}:	Если ТипЗнч(ФормаВладелец.ТекущийЭлемент) = Тип("ПолеHTMLДокумента") Тогда
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1017)}:	ВосстановитьФокусВвода();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(891)}:	Результат = ВыполнитьКоманду(Команда);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(284)}:		Результат = ЭкземплярКомпоненты.Нажатие(Кнопка);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/932963

**Comment by tormozit** [comment]
Исправлено в 6.08.2
