### ISSUE TITLE
Конструктор запросов ИР. Символ перевода строки в подсказке.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#480]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.83.1p
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
Для команды "Период" на странице "Отбор" в "Конструкторе запросов ИР" отображается подсказка содержащая символ перевода строки:

![image](https://github.com/tormozit/RDT1C/assets/87958986/718b43c6-5eef-4193-a643-0e5c3c9d7831)

**Comment by tormozit** [comment]
Исправлено в 6.83.3
