### ISSUE TITLE
Консоль запросов. Поле объекта не обнаружено (ВариантыЗначения)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#481]
https://github.com/tormozit/RDT1C/assets/87958986/17e8a44c-13c9-4a5d-a95e-7f6e4d51b6e6

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.83.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Консоли запросов при открытии существующего файла запросов возникает ошибка:

```
Поле объекта не обнаружено (ВариантыЗначения)
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(7451)}:	Если СтрокаПараметра.ВариантыЗначения.Количество() = 0 Тогда
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(2630)}:			ОбновитьТипЗначенияВСтрокеПараметровВФорме(НоваяСтрока);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(2524)}:		ЗагрузитьТаблицуПараметровЗапроса();
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(2713)}:	ЗагрузитьДанныеТекущейСтрокиДереваЗапросов();
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(1023)}:			ЭлементыФормы.ДеревоЗапросов.ТекущаяСтрока = НоваяТекущаяСтрока;
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(950)}:	Успех = ЗагрузитьЗапросыИзОбъекта(ПолученноеЗначение, РежимОбъединения,, ЭтоФайлВосстановления);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(872)}:		ЗагрузитьЗапросыИзФайла();
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(882)}:		ОткрытьФайлПоПолномуИмени(СтрокаИстории.Значение);

```

**Comment by tormozit** [comment]
Не удается воспроизвести и со старыми файлами и с новыми.
1. Это происходит со всеми файлами?
2. Если файл сохранить и затем открыть, то проблема повторяется?

Передай мне один такой файл размером поменьше.

**Comment by PerlAmutor** [comment]
Похоже кэш. Причем даже после перезапуска.
В данный момент тоже не воспроизводится (оставил файл открытым на целый день в ИР, сейчас ошибки нет).

**Comment by tormozit** [comment]
Воспроизвел в соседней заявке https://www.hostedredmine.com/issues/966180

**Comment by tormozit** [comment]
Исправлено в 6.83.2
