### ISSUE TITLE
Анализ техножурнала. Отбор по длительности

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#482]
https://github.com/tormozit/RDT1C/assets/87958986/8b99206c-c4ff-4a9a-ac04-bbb0a951e84c

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.83.1p
Инструменты разработчика. Инструмент: Анализ техножурнала
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
Отбор по длительности в Анализе техножурнала работает даже при выключенной галочке. Тогда неясно её назначение.

**Comment by tormozit** [comment]
Рекомендую использовать вариант "Расширение". Там нет этой ошибки платформы.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/966385

**Comment by tormozit** [comment]
Исправлено в 6.84
