### ISSUE TITLE
Анализ замера производительности с извлечением имен методов выдает ошибку

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#484]
**Программное окружение**

Платформа: 8.3.21.1709
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.80.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ПатчДоставка ()
Расширения. ПатчРаспределениеУдержаний ()
Расширения. ПатчУскорениеПроизводительностиЗагрузки ()
Расширения. З (1.1.1.5)
Расширения. зг_ЗУП (1.0.2.2)
Расширения. ЭР_Обмен_КА_БП (1.0.2.11)
Расширения. YAXUNIT ()
Расширения. ИнструментыРазработчикаTormozit (6.80.2e)
Расширения. МаркетКоннекторКА2 (1.0.2.2)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: Локальный
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыть инструмент "Анализ замера производительности"
2. Подгрузить этот файл  [Новый4.zip](https://github.com/tormozit/RDT1C/files/12011872/4.zip)
3. Установить галочку "Извлекать имена методов"
4. Нажать сформировать
5. Получить ошибку

>Ошибка при вызове метода контекста (СкомпоноватьРезультат)
>
> {ИнструментыРазработчикаTormozit Отчет.ирАнализЗамераПроизводительности.Форма.ФормаОтчета.Форма(154)}:СкомпоноватьРезультат(ЭлементыФормы.ТабличныйДокумент, ДанныеРасшифровки);
> 
> по причине:
> Ошибка исполнения отчета
> по причине:
> Ошибка при выполнении обработчика - 'ПриКомпоновкеРезультата'
> по причине:
> Значение не является значением объектного типа (ПолучитьТекст)

![изображение](https://github.com/tormozit/RDT1C/assets/16429518/f800f0c6-6328-41ab-8cd2-2c46b2f880e8)

**Ожидаемое поведение**
Отсутствие ошибок

**Comment by tormozit** [comment]
Текст ошибки обрезан платформой. Нужен полный текст ошибки. Для этого запусти приложение с подключенным отладчиком и повтори ошибку. В появившемся окне ошибки нажми кнопку "Конфигуратор" и затем скопируй полный текст ошибки из окна конфигуратора.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/966235

**Comment by tormozit** [comment]
Исправлено в 6.83.3
