### ISSUE TITLE
Консоль запросов. Сохранить объект для отладки с менеджером временных таблиц не сохраняет временные таблицы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#485]
https://github.com/tormozit/RDT1C/assets/87958986/5dd096ef-48ba-416e-a4be-43721062196e

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.83.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Консоли Запросов выполнил запрос помещающий данные во временную таблицу
2. Вызвал команду " \ Командная панель \ Сохранить объект "
3. Скопировал возвращенный текст
4. Вызвал инструмент "Отладить отложенный объект"
5. В восстановленном запросе отсутствуют временные таблицы. В файле .deb тоже нет никакого намека на их присутствие.
6. Запрос для воспроизведения:

```
ВЫБРАТЬ ПЕРВЫЕ 10
	Т.Ссылка
ПОМЕСТИТЬ ВтДокументы
ИЗ
	Документ.АвансовыйОтчет КАК Т
;
ВЫБРАТЬ
	*
ИЗ
	ВтДокументы КАК Т
```

Пробовал на всех версиях ИР вплоть до версии Ир6.60p. Нигде не работает.

**Comment by tormozit** [comment]
Так сделано умышленно. В снимок запроса сохраняются только входящие временные таблицы, т.е. те которые необходимы для выполнения запроса. В твоем примере таких нет. А выходящие временные таблицы можно получить путем выполнения запроса.
Такой подход в частности позволяет сократить размер снимка, который иногда может и без того быть очень большим.

[Обновлено 13.07.2023] 
Тут я предоставил устаревшую информацию и потому некорректную. 
На самом деле функцией ОтЛкс() на платформе 8.3.8+ в снимок сохраняются все временные таблицы менеджера.

**Comment by PerlAmutor** [comment]
> Так сделано умышленно. В снимок запроса сохраняются только входящие временные таблицы, т.е. те которые необходимы для выполнения запроса. В твоем примере таких нет. А выходящие временные таблицы можно получить путем выполнения запроса.
> 
> Такой подход в частности позволяет сократить размер снимка, который иногда может и без того быть очень большим.

Тут ситуация следующая. Есть регламентное задание, которое периодически забирает из регистра заданий данные, а потом удаляет. Обнаружилось, что в задания попадают некие данные, которые сильно влияют на длительность выполнения запроса в регламентном задании. Т.к. регистр заданий постоянно содержит различные данные, то и мой запрос помещает во временную таблицу каждый раз разные данные. Я такие данные отловил и хотел сохранить в снимок, но ИР не дал мне этого сделать, да еще и чистанул их из временной таблицы. В последствии я хотел использовать этот снимок для оптимизации запроса, но пришлось потратить еще день, чтобы снова эти данные выловить, т.к. ИР оказал мне медвежью услугу из-за задуманного поведения...

**Comment by tormozit** [comment]
Если нужно таблицу значений сохранить, то используй команду "Сохранить в файл" формы "Таблица значений". Про очистку временных таблиц от тебя есть другая заявка. Подсказку кнопки заменю на более точную.

**Comment by PerlAmutor** [comment]
Но тут странная ситуация получается. Если у тебя есть входящие временные таблицы, значит у тебя уже есть .deb файл и его можно переиспользовать. И выходит, что для Консоли Запросов нет альтернативы типа функции иробщий.ОтЛкс().

**Comment by tormozit** [comment]
Консоль запросов снимок запроса делает ровно тем же алгоритмом - вызывает функцию ОтЛкс(). Можешь проверить это установкой туда точки останова. Поэтому непонятно использование термина "альтернатива".

**Comment by PerlAmutor** [comment]
Дело то не в этом, а в различном поведении. У меня получается нет возможности сохранить из консоли запросов все временные таблицы. А чтобы это сделать надо переходить в консоль кода и оттуда уже делать снимок вызывая ОтЛкс() непосредственно.

Хотя бы галочку сделай для этого, чтобы можно было выбирать сохранять все временные таблицы или только из внешнего файла. Пусть даже будет выключена по умолчанию, я не настаиваю.

**Comment by tormozit** [comment]
Не понял. Ты считаешь, что есть различное поведение между какими сценариями? 
Объясни в одном сообщении четко предполагаемое различие.
Как я уже писал выше, консоль запросов вызывает функцию ирОбщий.ОтЛкс.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/966321

**Comment by tormozit** [comment]
Исправил предоставленную мной здесь выше некорректную информацию в сообщении https://github.com/tormozit/RDT1C/issues/485#issuecomment-1631886345

**Comment by tormozit** [comment]
Исправлено в 6.84
