### ISSUE TITLE
Консоль запросов. Сохранить объект для отладки с менеджером временных таблиц очищает данные во временных таблицах

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#486]
https://github.com/tormozit/RDT1C/assets/87958986/e96a19bf-a4d5-4eb1-8bf4-d7d91100496a

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.83.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Консоли Запросов выполнил запрос помещающий данные во временную таблицу
2. Вызвал команду " \ Командная панель \ Сохранить объект "
3. Скопировал возвращенный текст
4. Вызвал инструмент "Отладить отложенный объект"
5. Вернулся в окно с оригинальным запросом
6. Попробовал посмотреть содержимое временной таблицы
7. Получил ошибку:
```
Текст запроса: Строка кода 1: {(1,14)}: Таблица не найдена "ВтДокументы"
ВЫБРАТЬ * ИЗ <<?>>ВтДокументы
```

Запрос для воспроизведения:
```
ВЫБРАТЬ ПЕРВЫЕ 10
	Т.Ссылка
ПОМЕСТИТЬ ВтДокументы
ИЗ
	Документ.АвансовыйОтчет КАК Т
;
ВЫБРАТЬ
	*
ИЗ
	ВтДокументы КАК Т
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/966321

**Comment by tormozit** [comment]
Исправлено в 6.84
