### ISSUE TITLE
Консоль запросов. Показать структуру хранения. Падение платформы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#487]
https://github.com/tormozit/RDT1C/assets/87958986/57cd75b5-e453-4bec-98fb-152abdd9b758

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.34)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.83.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл Консоль запросов
2. Ввел запрос
3. Переключился на "Структуру запроса"
4. Вызвал команду "Показать структуру хранения"
5. Упала платформа

Запрос для воспроизведения:
```
ВЫБРАТЬ
	Т.Ссылка
ИЗ
	ДОкумент.АвансовыйОтчет КАК Т
```

**Comment by tormozit** [comment]
Думаю причина та же https://github.com/tormozit/RDT1C/issues/408

**Comment by PerlAmutor** [comment]
> Думаю причина та же #408

Да, тоже так подумал. Если включать флажок "Показывать размеры" в инструменте "Структура хранения БД", то тоже платформа падает.
Я только вот чего не понимаю, зачем флажок "Показывать размеры" передается в этот инструмент из других, в то время как на основной форме его никто не включал?

**Comment by tormozit** [comment]
Программа нацелена на максимальные удобства в типичных сценариях. Поэтому флажок включен в этом случае.
Твой случай не типичен. Поэтому ищи как отделить твой случай от остальных или как обойти проблему.
