### ISSUE TITLE
В консоли компоновок данных добавить возможность показывать имена полей, а не заголовки

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#488]
В консоли компоновок данных в структуре, отборах и тд показываются заголовки полей.
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/ede861c4-d19f-4651-a4d2-9f02d42a5291)

Фактически это довольно неудобно, т.к. глядя на структуру нельзя однозначно сказать, что на самом деле за поле в ней находится
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/9484a0dd-65ad-44bc-b052-75a84ada0c83)
Например здесь "Вид доходов\расходов" - это на самом деле "Раздел". Чтоб это выяснить приходится залезать в структуру в самой схеме или сопоставлять по набору данных.
Т.к. это обработка предназначена для разработки схем компоновки, то считаю разумным и необходимым иметь возможность показывать в ней именно имена полей, как более удобное для разработчика.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/966246

**Comment by tormozit** [comment]
Реализовано в 6.84
