### ISSUE TITLE
Конвертер текста БД. Открывать в отдельных окнах для каждого запроса

### ISSUE THREAD

**Issue by JohnyDeath** [tormozit/RDT1C#489]
ИР Расширение 6.83.2e

Из обработки "Анализ техножурнала" Открываю событие техножурнала № 1
В нем кликаю на запрос из свойства "Оператор обращения к БД" (SDBL)
Открывается окно Конвертора текста БД.

теперь хочу сделать тоже самое для события техножурнала №2, но не закрывая конвертер запроса 1.
При клике на запрос из окна события 2 перекидывает на уже открытое окно конвертера 1.
А хотелось бы, чтобы открылось еще одно окно с запросом события 2
![image](https://github.com/tormozit/RDT1C/assets/5936030/5f27bdd5-cbb6-4342-a7da-08c70cb339eb)

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/966266

**Comment by tormozit** [comment]
Реализовано в 6.84
