### ISSUE TITLE
Редактор объекта БД. Таблица БД с именем "" не найдена

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#49]
![photo_2021-09-08_20-18-11](https://user-images.githubusercontent.com/87958986/132555394-f3890b2e-043a-44a7-a9f0-8c36532b65d4.jpg)

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.08.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Иногда при очистке параметра "Таблица" возникает ошибка "Таблица БД с именем "" не найдена".
Как воспроизвести не знаю...

**Comment by tormozit** [comment]
Установи точку останова в этой строке. Когда она сработает, сделай снимок стека.

**Comment by PerlAmutor** [comment]
Сделал

![ТаблицаНеНайдена](https://user-images.githubusercontent.com/87958986/132998257-cf90f9cc-dd48-4727-919f-af2704333c15.png)

**Comment by tormozit** [comment]
Не понял как такое может происходить.  Видимо это новый баг 8.3.19 . Сделал защиту от него в 6.09.1. Но не тестировал, т.к. не смог воспроизвести.

**Comment by PerlAmutor** [comment]
На вряд ли новый баг. Ошибка возникает и на 8.3.17.1851.

**Comment by PerlAmutor** [comment]
Закрываю, т.к. за пару недель пока ошибки не возникало.
