### ISSUE TITLE
Консоль компоновок данных передает в консоль запросов некорректную длину строки в параметрах

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#490]
**Программное окружение**

Платформа: 8.3.21.1709
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.80.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ПатчДоставка ()
Расширения. ПатчРаспределениеУдержаний ()
Расширения. ПатчУскорениеПроизводительностиЗагрузки ()
Расширения. З (1.1.1.5)
Расширения. зг_ЗУП (1.0.2.2)
Расширения. ЭР_Обмен_КА_БП (1.0.2.11)
Расширения. YAXUNIT ()
Расширения. ИнструментыРазработчикаTormozit (6.80.2e)
Расширения. МаркетКоннекторКА2 (1.0.2.2)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: Локальный
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открываем "Консоль компоновок данных"
2. Задаем параметр схемы компоновки с типом строка определенной длины
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/e66340d9-2a89-42d5-9488-139674f7f829)
3. Задаем значение параметра (в моем случае они были заданы при передаче схемы из отладки) в настройках варианта отчета
4. Передаем в консоль запросов
5. Переходим на вкладку Параметры
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/66b56a2e-6df0-4e34-b42f-d0e6c70e515f)
Видим, что параметр стал строкой неограниченной длины
6. Выполняем запрос
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/3540d1f9-2c3b-46c5-bccb-96982a3e2e04)
Выдает ошибку, но запрос при этом выполняется

**Ожидаемое поведение**
Корректные длины строк при передачи из консоли компоновки, если длина строки в типах параметра указана (если причина в этом)
Или же отсутствие такой ошибки для выполняемого запроса.

**Comment by KovAlexey** [comment]
Сейчас проверил.
Ограничение длины строки этого параметра не приводит к нужному результату.
Полагаю дело еще в списке значений.
Хотя из СКД это все работает

**Comment by tormozit** [comment]
При выполнении запроса у его параметров нет квалификаторов, т.е. описаний типов. У них есть только конкретные значения. Описания же типов (квалификаторы) в таблице параметров консоли и в конструкторе схемы компоновки сделаны для удобства редактирования. Причина ошибки в твоем запросе скорее всего в различающихся типах операндов. Подозреваю что в &П у тебя значение Неопределено. Но ты почему то не показал его значение.

**Comment by KovAlexey** [comment]
Нет, это список значений со строками. 
И после выдачи ошибки запрос выполняется
Скрин добавлю минут через 20

**Comment by KovAlexey** [comment]
Сделал видео


https://github.com/tormozit/RDT1C/assets/16429518/b7ecccd0-84d8-4c30-bc7c-66645ac4a9ab


Как видишь запрос выполняется, возвращает результат.
Но что-то выдает ошибку еще до его выполнения и это что-то явно из ИР.

UPD: Не ту строку выделил, когда показывал параметр "СтрокаПродажи". Но Строку "Продажи" - ее видно. Можно не буду перезаписывать?

**Comment by tormozit** [comment]
Нужен полный текст сообщений программы и файл с запросами.

**Comment by KovAlexey** [comment]
> Текст запроса: Строка кода 131: {(131,23)}: Неверные параметры в операции сравнения. Нельзя сравнивать поля
>  неограниченной длины и поля несовместимых типов.
> И НЕ &СтрокаПродажи <<?>>В (&П3)

Стека нет, с отладчиком подключенным тоже.

[ФайлСЗапросами.zip](https://github.com/tormozit/RDT1C/files/12035833/default.zip)

**Comment by tormozit** [comment]
У меня файл не открывается в консоли из-за ссылок на метаданные. Поэтому оставь один запрос и обрежь его максимально. Желательно вообще избавиться от метаданных. 
Еще попробуй кнопку "Сохранить объект для отладки" для этого запроса и посмотри значения параметров там.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/966382

**Comment by tormozit** [comment]
Исправлено в 6.84
