### ISSUE TITLE
Анализ техножурнала. Автообновление таблицы событий после загрузки данных

### ISSUE THREAD

**Issue by JohnyDeath** [tormozit/RDT1C#491]
Нахожусь в обработке "Анализ техножурнала", просматриваю события SDBL
![image](https://github.com/tormozit/RDT1C/assets/5936030/78447fff-def5-4d2d-a23e-10774f50dea9)
Через настройки табличного поля ИР установлена сортировка по полю "Дата начала"
![image](https://github.com/tormozit/RDT1C/assets/5936030/969061cd-811e-49f8-bf8d-743e27055a45)

Теперь хочу подгрузить новую порцию данных из ТЖ. Нажимаю "Загрузить".
Вижу, что количество событий SDBL изменилось (верхняя таблица).
Но нижняя таблица с событиями не изменилась.
Далее хотел принудительно обновить, изменив текущую строку в верхней таблице: перешел в события QERR и потом обратно в SDBL. Ничего не изменилось. Новых событий в нижней таблице нет.

Помогает только нажатие кнопки "Применить" в настройках табличного поля (второй скрин).

Хотелось бы, чтобы список событий в нижней таблице обновлялся автоматически после загрузки очередной порции ТЖ

**Comment by tormozit** [comment]
Запиши видео, начиная с открытия формы "Анализ техножурнала". У меня такое происходило никогда. Сейчас проверил твое описание. Тоже не воспроизвелось. Новые строки появились сразу.

**Comment by JohnyDeath** [comment]
Записал видео и отправил в личку телеграма 17.07.2023 10:04 (Мартыненков Е.В.)

**Comment by tormozit** [comment]
Посмотрел видео. Поведение программы умышленное. Ты через **применяемый**, т.е. разовый, порядок изменял порядок строк в таблице журнала, используя универсальное средство "Менеджер табличного поля", которое не знает об остальной форме за табличным полем и том, как и когда изменяется состав строк в нем.
Затем ты выполнил дозагрузку новых строк из логов в таблицу журнала. Они добавились естественно в конец, т.е. по стандартному порядку для читалки логов. Поэтому ты их не видишь, пока снова не применишь сортировку.

**Comment by JohnyDeath** [comment]
А можно как-то еще сделать сортировку этого списка не через "применяемый"?
Хочу, чтобы более ранние события находились выше.

**Comment by tormozit** [comment]
Интерфейс этого инструмента итак сильно перегружен. Не хочется усугублять без веских причин. 
Ну и кажется что это "вкусовщина", т.е. чисто привычка. Или есть какие то веские причины?

**Comment by JohnyDeath** [comment]
Веских причин нет, просто уже как-то давно настроены все журналы по убыванию периода.
Если такого нет - не страшно. Обойдемся текущей сортировкой и текущими инструментами.
Спасибо.
