### ISSUE TITLE
Консоль кода. Роль доступна.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#493]
https://github.com/tormozit/RDT1C/assets/87958986/9bc0fbcc-a153-4bff-81c9-8fe3697b2f40

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.84.1p
Инструменты разработчика. Инструмент: Консоль кода
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл Консоль кода
2. Вызвал команду Выполнить
3. Получил ошибку

```
Ошибка при вызове метода контекста (РольДоступна)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(14738)}:	Если Истина
{ВнешняяОбработка.ирОбщий.МодульОбъекта(14731)}:	ТребоватьРольИРЛкс();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(544)}:	УстановитьПривилегированныйРежимЛкс();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(858)}:	Результат = ОтладитьЛкс(Объект, Истина, Объект2, ВнешниеНаборыДанных, ОтложенноеВыполнение, ПорогОбрезкиВременнойТаблицы,, Наименование, МенеджерВременныхТаблиц);
{(14)}:ф = иробщий.ОтЛкс(Запрос,,, Истина);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(1255)}:	Выполнить(_ТекстДляВыполнения);
{ВнешняяОбработка.ирКонсольКода.МодульОбъекта(39)}:		КонтекстВыполнения.ВыполнитьАлгоритм(Параметры.ТекстДляВыполнения, Параметры.СтруктураПараметров);
{(1)}:Обработка.ВыполнитьАлгоритмВКонтексте(ПараметрыЗадания)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(22027)}:		Результат = Вычислить("Обработка." + ИмяМетодаОбработки + "(ПараметрыЗадания)");
{ВнешняяОбработка.ирКонсольКода.Форма.Форма.Форма(597)}:		ирОбщий.ВыполнитьЗаданиеФормыЛкс("ВыполнитьАлгоритмВКонтексте", ПараметрыЗадания, ЭтаФорма, "ВыполнитьАлгоритм",, Кнопка, "ВыполнитьАлгоритмВФонеЗавершение",
{ВнешняяОбработка.ирКонсольКода.Форма.Форма.Форма(537)}:	ИнформацияОбОшибке = ВыполнитьЛокальноПоСтруктуреПараметров(ТекстДляВыполнения, СтруктураПараметров, ЛиСинтаксическийКонтроль, ВерсияАлгоритма, выхИнформацияОбОшибке);
{(1)}:КонтекстВыполнения.ВыполнитьЛокально(ТекстДляВыполнения, ЛиСинтаксическийКонтроль)
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(5679)}:		ИнформацияОбОшибке = Вычислить("КонтекстВыполнения." + МетодВыполнения + "(ТекстДляВыполнения, ЛиСинтаксическийКонтроль)");
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2248)}:		мПлатформа.ВыполнитьПрограммныйКодВКонтексте(КонтекстВыполнения, МетодВыполнения, ТекстДляВыполнения, ЛиСинтаксическийКонтроль);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1108)}:			ВыполнитьПрограммныйКод();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1017)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольКода.Форма.Форма.Форма(79)}:	ПолеТекстаАлгоритма.Нажатие(Кнопка, ПолеТекстаАлгоритма.ЭтоМодуль);
по причине:
Недопустимое значение параметра (параметр номер '1')

```

**Comment by tormozit** [comment]
Ошибку воспроизвел. Исправил в 6.84.1
