### ISSUE TITLE
Консоль запросов. Сохранить объект для отладки.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#494]
https://github.com/tormozit/RDT1C/assets/87958986/ac047ac9-1627-4e41-b413-536ef83e0539

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.84.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Ввел текст запроса
2. Выполнил
3. Вызвал команду "Сохранить объект для отладки"
4. Получил ошибку:

`Текст запроса: Строка кода 3: Ошибка при вызове метода контекста (РольДоступна): Недопустимое значение параметра (параметр номер '1')
`

**Comment by tormozit** [comment]
Ошибку воспроизвел. Исправлено в 6.84.1
