### ISSUE TITLE
Поиск по интерфейсам. Переменная не определена (ирОбщий)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#495]
https://github.com/tormozit/RDT1C/assets/87958986/37005b87-2a5c-4af1-92c9-d28acb268d33

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.84.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Вызвал "Список инструментов и общие настройки"
2. Вызвал команду "Поиск по интерфейсам"
3. Получил ошибку

`Ошибка при получении формы ВнешняяОбработка.ирПлатформа.Форма.ОписаниеПлатформы: {ВнешняяОбработка.ирПлатформа.Форма.СтруктураФормы.Форма(519)}: Ошибка при вызове метода контекста (ПолучитьФорму): Ошибка инициализации модуля: ВнешняяОбработка.ирПлатформа.Форма.ОписаниеПлатформы.Форма: {ВнешняяОбработка.ирПлатформа.Форма.ОписаниеПлатформы.Форма(11,27)}: Переменная не определена (ирОбщий)`

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/969874

**Comment by tormozit** [comment]
Исправлено в 6.95
