### ISSUE TITLE
Консоль кода. Перестали заполнятся исходящие параметры

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#497]
https://github.com/tormozit/RDT1C/assets/87958986/f53eaacb-94e8-49be-8c16-dd7018222d1d

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.85.1p
Инструменты разработчика. Инструмент: Консоль кода
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
В Консоли кода не заполняются выходящие параметры
Код для воспроизведения:

```
УИДСтрокой = Строка(Пар1.УникальныйИдентификатор());
ШестнадцатиричноеЧисло = СтрЗаменить(УИДСтрокой,"-","");
ДД = ПолучитьДвоичныеДанныеИзHEXСтроки(ШестнадцатиричноеЧисло);
ХД = Новый ХешированиеДанных(ХешФункция.MD5);
ХД.Добавить(ДД);
Хеш = ХД.ХешСумма;

```

В таком коде заполняются:

```
П1 = "Тест";
П2 = Неопределено;
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/966677

**Comment by tormozit** [comment]
Исправлено в 6.85.2
