### ISSUE TITLE
Динамический список. Неверные параметры в операции сравнения. Нельзя сравнивать поля  неограниченной длины и поля несовместимых типов.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#498]
https://github.com/tormozit/RDT1C/assets/87958986/66339d96-967d-4535-9330-cd954a1be683

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.85.1p
Инструменты разработчика. Инструмент: Динамический список
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл Динамический Список с объектом РегистрСведений.АдресныеОбъекты
2. Выделил поле Идентификатор на одной строке
3. Зажал Ctrl и выделил Идентификатор на другой строке
4. Получил ошибку

```
Ошибка при вызове метода контекста (Добавить)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(23566)}:		ОператорЗапроса.Отбор.Добавить(ВыражениеЗапроса); // В режиме совместимости 8.2.13 некорректно добавляется выражение
{ВнешняяОбработка.ирКлиент.МодульОбъекта(2654)}:					Запрос = ирОбщий.ЗапросОтбораПоТаблицеКлючейЛкс(Запрос, СтруктураКлюча, Истина);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(3366)}:		КоллекцияСтрок = ДанныеСтрокДинамическогоСпискаЛкс(ТабличноеПоле, ТабличноеПоле.ВыделенныеСтроки, ирОбщий.СтрСоединитьЛкс(ИменаВидимыхКолонок),,, ЭтаФорма, Истина); // Долго
{ВнешняяОбработка.ирКлиент.МодульОбъекта(6969)}:	ТабличноеПолеОбновитьТекстыПодваловЛкс(Параметры.ЭтаФорма, Параметры.ТабличноеПоле, Ложь);
{(1)}:ирКлиент.ТабличноеПолеОбновитьТекстыПодваловОтложенноЛкс(ПараметрыОбработчикаОжидания)
{ВнешняяОбработка.ирКлиент.МодульОбъекта(1721)}:	Выполнить(ПараметрыОбработчикаОжидания.ИмяМетода + "(ПараметрыОбработчикаОжидания)");
{ВнешняяОбработка.ирКлиент.МодульОбъекта(1661)}:		ОбработчикОжиданияСЯвнымиПараметрамиЛкс(Параметры);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(6962)}:		ПодключитьОбработчикОжиданияСПараметрамиЛкс("ирКлиент.ТабличноеПолеОбновитьТекстыПодваловОтложенноЛкс", ПараметрыОбработчика, Задержка,, Ложь);
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(694)}:	ирКлиент.ТабличноеПолеПриАктивизацииСтрокиЛкс(ЭтаФорма, Элемент);
по причине:
{(1, 56)}: Неверные параметры в операции сравнения. Нельзя сравнивать поля
 неограниченной длины и поля несовместимых типов.
(Таблица3463.Идентификатор, Таблица3463.КодСубъектаРФ) <<?>>В (ВЫБРАТЬ Таблица3463.Идентификатор, Таблица3463.КодСубъектаРФ ИЗ КлючиОтбираемыхСтрок КАК Таблица3463)

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/966821

**Comment by tormozit** [comment]
Исправлено в 6.86
