### ISSUE TITLE
"Выгрузка/Загрузка данных через файл" очищает весь регистр сведений

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#499]
https://github.com/tormozit/RDT1C/assets/87958986/44b7d916-6121-482d-870f-1bf660e211fa

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.85.1p
Инструменты разработчика. Инструмент: Выгрузка/загрузка данных через файл
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Выгрузил данные регистра РегистрСведений.АдресныеОбъекты в файл
2. Загрузил данные регистра из файла через "Выгрузка/Загрузка данных через файл"
3. Очистился весь регистр сведений

[АдресныеОбъекты.zip](https://github.com/tormozit/RDT1C/files/12167498/default.zip)

**Comment by PerlAmutor** [comment]
Понял свою ошибку. Я выгрузил "Ключи объектов" не прочитав описание... Хотелось бы какое-то предупреждение что-ли, а то вместо резервной копии данных так можно наоборот выгрузить удаление записей и напортачить еще больше.

**Comment by tormozit** [comment]
Чтобы подстраховать пользователя в этом сценарии, мне нужно понять ход его рассуждений.
Зачем ты выбрал "Ключи объектов"? Как понял это изначально, т.е. что предполагал выгрузится?

**Comment by PerlAmutor** [comment]
Т.к. пункт "Выгрузка" по умолчанию не доступен для набора записей, то пришлось "подбирать" варианты при каких настройках этот пункт обработки становится доступным. А дальше просто бахнул Выгрузить в надежде на то, что выгрузятся все записи регистра "по ключам". А оказывается выгрузились лишь ключи. И уже потом после затирки регистра я прочитать описание к настройке, тогда пазл и сложился...

**Comment by tormozit** [comment]
Ясно. Создал задачу https://www.hostedredmine.com/issues/966676
