### ISSUE TITLE
Не передается вид регистра сведений из динамического списка в подбор и обработку объектов

### ISSUE THREAD

**Issue by etnety** [tormozit/RDT1C#5]
Платформа: 8.3.18.1520
Режим БД: файловый
Конфигурация. Название: Управление холдингом, редакция 3.1 (3.1.8.1)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.02.1e
Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. РЛ7_Адаптация (1.0.0.65)
Расширения. ИнструментыРазработчикаTormozit (6.02.1e)
Клиент. ОС: Майкрософт Windows 10 Домашняя для одного языка 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru_RU
Клиент. От имени администратора Windows: Нет

1. В управляемом приложении открываю динамический список
2. Настраиваю отборы
3. Нажимаю кнопку "Передать строки в инструмент "Подбор и обработка объектов"
4. Выбираю "Нет" (иначе будет использован текущий отбор)
5. Открывается  Подбор и обработка объектов с настроенными отборами, но выбрана таблица, которая обрабатывалась в прошлый раз

Ожидается открытие обработки таблицы, выбранной в динамическом списке.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/931229

**Comment by tormozit** [comment]
Исправлено в 6.02.2
