### ISSUE TITLE
Подбор и обработка объектов БД в режиме обычного приложения

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#50]
**Программное окружение**
Платформа: 8.3.17.1549
Режим БД: клиент-серверный
Конфигурация. Название: 1C:Drive, версия 1.3 (1.3.6.5)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: English
Конфигурация. Режим управления блокировкой данных: Managed
Конфигурация. Режим совместимости: Version8_3_14
Инструменты разработчика. Версия: Расширение 6.08.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.08.1e)
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная НеРусский-0409
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Подбор и обработка объектов БД в режиме обычного приложения
2. В поле Область поиска выбрал "Авансовый отчет (4) " (Document.ExpenseReport)
3. Получил окно с ошибкой:
{ИнструментыРазработчикаTormozit DataProcessor.ирПодборИОбработкаОбъектов.Form.ПодборИОбработка.Form(1769)}: Значение не является значением объектного типа (ТипЗначения)
				ОписаниеТипов = ОписаниеПоляТаблицы.ТипЗначения;
4. Не заполнилось поле "Доступные поля отбора".

**Ожидаемое поведение**
Заполнилось поле "Доступные поля отбора". 
Это не позволяет накладывать отборы.

**Comment by antonsm2011** [comment]
База 1С Drive полностью типовая, та же самая как здесь - https://github.com/tormozit/RDT1C/issues/34.

**Comment by antonsm2011** [comment]
Такая же ошибка, если выбрать Приходная накладная (Document.SupplierInvoice), например.

А по следующим документам ошибки нет:
Заказ покупателя (Document.SalesOrder)
Заказ поставщику (Document.PurchaseOrder)
Расходная накладная (Document.SalesInvoice)

**Comment by antonsm2011** [comment]
1С запускаю с ключом /RunModeOrdinaryApplication.
Не из конфигуратора.

**Comment by tormozit** [comment]
Желательно заполучить версию этой конфигурации, работающую в 8.3.18. Есть такая?
Эта версия при запуске на 8.3.18 выдает ошибку. 
Ошибка инициализации модуля: CommonModule.FilesOperationsInternalServerCall.Module
по причине:
{CommonModule.FilesOperationsInternalServerCall.Module(1267,10)}: Процедура или функция с указанным именем уже определена (CopyFile)
Function <<?>>CopyFile(SourceFile, NewFileOwner)
{CommonModule.FilesOperationsInternalServerCall.Module(3454,13)}: Обращение к процедуре как к функции (CopyFile)
		NewFile = <<?>>CopyFile(File, NewFileOwner);

**Comment by antonsm2011** [comment]
> Желательно заполучить версию этой конфигурации, работающую в 8.3.18. Есть такая?

Попробую найти.

**Comment by tormozit** [comment]
Остановись в отладчике на этой строке по ошибке. Вычисли выражение "ЭлементКлюча.Ключ"

**Comment by antonsm2011** [comment]
Теперь не получается воспроизвести эту ошибку.
Перед открытием Подбора и обработки объектов возникает ошибка, но сам инструмент открывается:  
{Document.ExpenseReport.ManagerModule(2495,2)}: Переменная не определена (InventoryOwnershipServer)
	<<?>>InventoryOwnershipServer.InfobaseUpdate_FillMainTableColumn("ExpenseReport");

У модуля InventoryOwnershipServer галка Клиент (Обычное приложение) отсутствует.

**Comment by antonsm2011** [comment]
Похоже, что можно закрывать.

**Comment by tormozit** [comment]
Значит исправлено в 6.09

**Comment by tormozit** [comment]
> Перед открытием Подбора и обработки объектов возникает ошибка, но сам инструмент открывается:
> {Document.ExpenseReport.ManagerModule(2495,2)}: Переменная не определена (InventoryOwnershipServer)
> <<?>>InventoryOwnershipServer.InfobaseUpdate_FillMainTableColumn("ExpenseReport");
> У модуля InventoryOwnershipServer галка Клиент (Обычное приложение) отсутствует.

Переходи в режим запуска "Управляемое приложение". Там этой ошибки не будет.
