### ISSUE TITLE
Оптимизация дерева метаданных

### ISSUE THREAD

**Issue by a-sitnikov** [tormozit/RDT1C#500]
Инструмент: Редактор объекта БД.
При выборе ссылки инициализируется полное дерево метаданных включая все обработки, отчеты и роли. Что раза в 2-3 увеличивает вермя открытия дерева метаданных. Но роли и обработки не нужны при выборе типа ссылки.

Предложение: Реализовать отложенную инициализацию некоторых видов метаданных

**Comment by tormozit** [comment]
Идея конечно заманчивая. Но я уже минимум раз 5 переделывал этот непростой и чувствительный механизм кэширования, чтобы в среднем минимизировать задержки во всех местах его использования. Нужны веские причины чтобы начать в нем что то снова менять. Поэтому продемонстрируй в числах (замером производительности) предполагаемую экономию, т.к. оценка в 2-3 раза кажется слишком смелой. По моим воспоминаниями обработки, отчеты и прочие нехранимые типы объектов занимают не более 30% от общего времени построения дерева.

Все это дерево итак отложенно строится в непортативных вариантах. Поэтому сообщи техническую информацию.
