### ISSUE TITLE
Ошибка при обработке записей последовательности

### ISSUE THREAD

**Issue by MishiGit** [tormozit/RDT1C#502]
**Программное окружение**

Платформа: 8.3.19.1770
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия предприятия КОРП, редакция 3.0 (3.0.135.22/3.1.54.9)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 6.85.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. РасширениеОбщепит ()
Расширения. Расширение1 ()
Расширения. ИнструментыРазработчикаTormozit (6.85.2e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows Server 2016 Datacenter 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2016 Datacenter 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**

1. Открыл инструмент подбор и обработка объектов БД. Выбрал объект - Последовательность. Добавил отбор по измерению. Важно! У нас в базе по одному регистратору может быть несколько записей последовательности с разными значениями измерений.
2. Нажал "Заполнить строки". Получил список строк для обработки. Тут всё верно.
3. Перешел на закладку "Обработки". Выбрал инструмент "Удалить". **Удаляется произвольная запись по регистратору. Не та, которая отобрана в строках для обработки.**
4. Попробовал произвольный алгоритм. В переменную "Объект" попадает произвольная (или первая по счету) запись по регистратору, а не та, которая отобрана в списке для обработки.
5. Галочки настроек записи не влияют, щелкал по-разному

**Ожидаемое поведение**
Ожидалось, что инструменты не будут путать в пределах регистратора записи последовательности и будут обрабатывать именно те записи, которые отобраны на закладке Настройка выборки.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/967872

**Comment by tormozit** [comment]
Исправлено в 6.88
