### ISSUE TITLE
Определенный текст поля выборки ломает анализатор запроса ИР

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#503]
**Программное окружение**

Платформа: 8.3.21.1624
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.86.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. Патч_РасширениеРоли_ЭтапыДоставки ()
Расширения. Патч040823 ()
Расширения. ИмяКомпании (1.1.1.9)
Расширения. зг_ЗУП (1.0.2.7)
Расширения. ЭР_Обмен_КА_БП (1.0.2.19)
Расширения. ИнструментыРазработчикаTormozit (6.86.1e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Вставил следующий запрос

```
ВЫБРАТЬ
	ВЫБОР
		КОГДА МАКСИМУМ(ВТНумерацияСоСдвигами.Нумерация) / 2 <> ЦЕЛ(МАКСИМУМ(ВТНумерацияСоСдвигами.Нумерация) / 2)
			ТОГДА ОКР(МАКСИМУМ(ВТНумерацияСоСдвигами.Нумерация) / 2)
		ИНАЧЕ МАКСИМУМ(ВТНумерацияСоСдвигами.Нумерация) / 2
	КОНЕЦ КАК ПерваяСтрока
ПОМЕСТИТЬ ВТНумерацияСреднее
ИЗ
	ВТНумерацияСоСдвигами КАК ВТНумерацияСоСдвигами

```

3. При попытке открытия конструктора ИР или структуры запроса получил следующую ошибку

> Текст запроса: Строка 4: {(4,59)}: Синтаксическая ошибка ")", ожидается: <,>

![изображение](https://github.com/tormozit/RDT1C/assets/16429518/19075a28-a009-4b70-b7ae-c28b11c90fcc)

**Ожидаемое поведение**
Отсутствие ошибок, конечно же

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/967521

**Comment by tormozit** [comment]
Исправлено в 6.87
