### ISSUE TITLE
Сообщение "Использование модальных окон в данном режиме запрещено!" при каждом открытии формы из результата консоли запросов

### ISSUE THREAD

**Issue by JohnyDeath** [tormozit/RDT1C#504]
> Платформа: 8.3.23.1688
> Режим БД: клиент-серверный
> Конфигурация. Название: Бухгалтерия предприятия КОРП, редакция 3.0. БитФинанс (3.0.139.19/3.1.55.5)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_17
> Конфигурация. Режим использования синхронных вызовов: Использовать
> Конфигурация. Версия БСП: 301
> Конфигурация. Использовать обычные формы в управляемом приложении: Да
> Инструменты разработчика. Версия: Расширение 6.86.1e
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Асинхронность запрещена: Нет
> Инструменты разработчика. Разрешены имитаторы: Да
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Да
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. Отладка разрешена: Да
> 

В консоли запросов выполняем запрос:
`Выбрать ПЕРВЫЕ 15  
	спр.Ссылка
Из Справочник.Контрагенты как спр`
дважды кликаем на любой строке результата запроса.
Наблюдаем сообщение "Использование модальных окон в данном режиме запрещено!" при каждом открытии формы
![image](https://github.com/tormozit/RDT1C/assets/5936030/d25b6131-4152-4a27-b4d5-e6f7afecba3d)

Хотелось бы, чтобы этого сообщения не было.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/967554

**Comment by tormozit** [comment]
Исправлено в 6.86.2

**Comment by JohnyDeath** [comment]
Спасибо
