### ISSUE TITLE
Редактор остатков. Замена на null ломает отбор в динамическом списке.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#505]
https://github.com/tormozit/RDT1C/assets/87958986/2c69830f-0592-4b3a-b4a4-393e79a48ce4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.86.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Редактор Остатков
2. Получил Остаток
3. Вызвал команду "Движения остатка"
4. Увидел предупреждения:
```
Отбор по измерению "Валюта" заменен с Null на Неопределено
Отбор по измерению "Субконто3" заменен с Null на Неопределено
```
5. Открылся Динамический Список, где отбор с замененными значениями Валюта и Субконто3 влияют на результат выборки. А именно ничего не отбирается, если не снять отбор по этим полям.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/967692
Исправлено в 6.87
