### ISSUE TITLE
Редактор остатков и Динамический список. Различные значения колонки.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#506]
https://github.com/tormozit/RDT1C/assets/87958986/f1a1d144-8710-40de-80cc-b86ff49e39f1

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.86.1p
Инструменты разработчика. Инструмент: Редактор остатков
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Если в Редакторе Остатков вызвать команду "Движения остатка"
2. Затем при наложенном отборе вызвать Alt+F для получения различных значений регистраторов
3. Получаю ошибку "Поле не найдено "НаправлениеДеятельности""

```
Ошибка при вызове метода контекста (Выполнить)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(23485)}:	МакетКомпоновки = КомпоновщикМакета.Выполнить(Схема, НастройкаКомпоновки, ,, Тип("ГенераторМакетаКомпоновкиДанныхДляКоллекцииЗначений"), ПроверятьДоступностьПолей);
{ВнешняяОбработка.ирРазличныеЗначенияКолонки.Форма.Форма.Форма(560)}:		Запрос = ирОбщий.ЗапросИзКомпоновкиЛкс(СхемаКомпоновки, НастройкаКомпоновки);
{ВнешняяОбработка.ирРазличныеЗначенияКолонки.Форма.Форма.Форма(1045)}:	Если Не ОбновитьДанные(, Истина) Тогда 
{ВнешняяОбработка.ирКлиент.МодульОбъекта(17050)}:	РезультатФормы = Форма.ОткрытьМодально();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(17675)}:				ОткрытьРазличныеЗначенияКолонкиЛкс(ИсточникДействий,,, ЭтаФорма);
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(582)}:	ирКлиент.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
по причине:
Ошибка компоновки макета
по причине:
Поле не найдено "НаправлениеДеятельности"

```
При отключенном отборе работает нормально.

**Comment by tormozit** [comment]
Некорректное наложение отбора воспроизвел https://www.hostedredmine.com/issues/967692

**Comment by tormozit** [comment]
Ошибку открытия различных значений воспроизвел https://www.hostedredmine.com/issues/967693

**Comment by tormozit** [comment]
Исправлено в 6.87
