### ISSUE TITLE
Консоль кода > Общие методы -> ошибка

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#508]
**Программное окружение**

Платформа: 8.3.20.2184
Режим БД: клиент-серверный
Конфигурация. Название: Управление недвижимостью и арендой КОРП на базе "1С:Бухгалтерия 8 КОРП", редакция 3.0 (3.0.119.9)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.86.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.86.2e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс
Сервер. ОС: Microsoft Windows Server 2016 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Консоль кода
2. Нажал кнопку Общие методы
3. Получил окно с ошибкой 

{(2, 5)}: Неоднозначное поле "Таблица.Предопределенный"
ГДЕ <<?>>Таблица.Предопределенный
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(1983)}:Результат = Запрос.Выполнить().Выгрузить();
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(4045)}:СвойстваТипаМетаданные(СтруктураТипа, Слово, ТипСлова,, ЯзыкПрограммы,, ВнешниеФункцииКомпоновкиДанных, ВычислятьТипы, ЛиСерверныйКонтекст,
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(3248)}:Для Каждого СтрокаСлова Из ТаблицаСловИзСтруктурыТипа(СтруктураТипа,,,, Ложь,, "Свойство",,, МодульМетаданных("")) Цикл
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(2954)}:МодульМетаданных = МодульМетаданных(ТекстовыйДокумент.ПолучитьТекст(), СтруктураТипа, ФайлМодуля.ИмяБезРасширения);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.ОбщиеМетоды.Форма(119)}:МодульМетаданных = мПлатформа.ПодготовитьМодульМетаданных(СтруктураТипа, ТипМодуляКонфигурации);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.ОбщиеМетоды.Форма(94)}:ДобавитьМетодыМодуля(СтруктураТипа, МетаТип);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.ОбщиеМетоды.Форма(51)}:ПерезаполнитьТаблицуВсехМетодов();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(6182)}:ФормаВыбора.Открыть();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1168)}:ОткрытьСписокОбщихМетодов();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1149)}:Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(78)}:ПолеТекстаАлгоритма.Нажатие(Кнопка, Ложь);

по причине:
{(2, 5)}: Неоднозначное поле "Таблица.Предопределенный"
ГДЕ <<?>>Таблица.Предопределенный

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/967611

**Comment by tormozit** [comment]
Исправлено в 6.87
