### ISSUE TITLE
Редактор объекта БД. Перечисление. Метод объекта не обнаружен (УникальныйИдентификатор)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#509]
https://github.com/tormozit/RDT1C/assets/87958986/8432a970-6b07-4eb2-8e58-8cbf2870fad7

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.86.2p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл значение перечисления в Редактор объекта БД
2. Перешел на вкладку "Ссылки на объект"
3. Выполнил поиск ссылок
4. Вызвал команду Alt+F2 на найденном документе
5. Получил ошибку:

```
Метод объекта не обнаружен (УникальныйИдентификатор)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(21452)}:		ТекстСсылки = ТипХМЛ.ИмяТипа + """>" + ИскомаяСсылка.УникальныйИдентификатор() + "<";
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(2956)}:		ТекстыСсылок.Добавить(ирОбщий.ТекстПоискаСсылкиВXMLЛкс(фОбъект.ИскомоеЗначение, Истина));
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1082)}:	НайтиВОбъектеНажатие();
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1072)}:		НайтиЗначениеВОбъекте(фОбъект.ПараметрИскомоеЗначение);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1050)}:	ОбработатьПараметрОткрытияИскомоеЗначение();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(11374)}:		Форма.Открыть(); // В открытой форме платформа при этом тоже выполняет перерисовку табличных текущих страниц панелей формы
{ВнешняяОбработка.ирКлиент.МодульОбъекта(11278)}:	Форма_АктивироватьОткрытьЛкс(ФормаРедактора);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(11203)}:	ФормаРедактора = ОткрытьРедакторОбъектаБДЛкс(ИмяТаблицы, ИмяПоля,, КлючОбъекта,, ДанныеСтрокиТаблицы, КлючОбъекта,, НайденныеСсылки,,,,, ИскомоеЗначение);
{ВнешняяОбработка.ирРедакторОбъектаБД.МодульОбъекта(115)}:	ирКлиент.ОткрытьСсылкуВРедактореОбъектаБДЛкс(КлючОбъекта, ИскомаяСсылка);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4825)}:	ОбработкаОбъект.ОткрытьСсылающийсяОбъектВРедактореОбъектаБД(ТекущаяСтрока, ИскомаяСсылкаПоискаСсылокНаОбъект());

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/967613

**Comment by tormozit** [comment]
Исправлено в 6.87
