### ISSUE TITLE
Подбор и обработка объектов БД в режиме обычного приложения - выбор нескольких документов для обработки

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#51]
**Программное окружение**
Платформа: 8.3.17.1549
Режим БД: клиент-серверный
Конфигурация. Название: 1C:Drive, версия 1.3 (1.3.6.5)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: English
Конфигурация. Режим управления блокировкой данных: Managed
Конфигурация. Режим совместимости: Version8_3_14
Инструменты разработчика. Версия: Расширение 6.08.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.08.1e)
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная НеРусский-0409
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Подбор и обработка объектов БД в режиме обычного приложения
2. В поле Область поиска выбрал Расходная накладная (Document.SalesInvoice) и Приходная накладная (Document.SupplierInvoice)
3. Получил окно с ошибкой:
{ИнструментыРазработчикаTormozit DataProcessor.ирПодборИОбработкаОбъектов.Form.ПодборИОбработка.Form(1771)}: Значение не является значением объектного типа (Заголовок)
			СтрокиДляОбработки.Колонки.Добавить(ЭлементКлюча.Ключ, ОписаниеТипов, ОписаниеПоляТаблицы.Заголовок);
4. Не заполнилось поле "Доступные поля отбора".

**Ожидаемое поведение**
Заполнилось поле "Доступные поля отбора".

**Comment by antonsm2011** [comment]
База 1С Drive полностью типовая, та же самая как здесь - https://github.com/tormozit/RDT1C/issues/34.

**Comment by antonsm2011** [comment]
1С запускаю с ключом /RunModeOrdinaryApplication.
Не из конфигуратора.

**Comment by tormozit** [comment]
Нужна картинка страницы "Настройки выборки"

**Comment by antonsm2011** [comment]
> Нужна картинка страницы "Настройки выборки"

![2021-09-10_09-33-11](https://user-images.githubusercontent.com/12731230/132810327-7bca6dc8-7140-47e6-ab34-7c9ce1e36898.png)

**Comment by tormozit** [comment]
Остановись в отладчике на этой строке по ошибке. Вычисли выражение "ЭлементКлюча.Ключ"

**Comment by antonsm2011** [comment]
Теперь не получается воспроизвести эту ошибку.
Перед открытием Подбора и обработки объектов возникает ошибка, но сам инструмент открывается:
{Document.SupplierInvoice.ManagerModule(6937,2)}: Переменная не определена (InventoryOwnershipServer)
	<<?>>InventoryOwnershipServer.InfobaseUpdate_FillMainTableColumn("SupplierInvoice");

У модуля InventoryOwnershipServer галка Клиент (Обычное приложение) отсутствует.
Похоже, что можно закрывать.

**Comment by tormozit** [comment]
Да. Новая ошибка уже относится к самой конфигурации. Кстати не понял, как им сообщать об ошибках. Там полностью отдельная компания 1Ci.

**Comment by tormozit** [comment]
Значит исправлено в 6.09

**Comment by tormozit** [comment]
> Перед открытием Подбора и обработки объектов возникает ошибка, но сам инструмент открывается:
> {Document.SupplierInvoice.ManagerModule(6937,2)}: Переменная не определена (InventoryOwnershipServer)
> <<?>>InventoryOwnershipServer.InfobaseUpdate_FillMainTableColumn("SupplierInvoice");
> 
> У модуля InventoryOwnershipServer галка Клиент (Обычное приложение) отсутствует.

Будет полезно, если ты сделаешь пример для воспроизведения этой ошибки в виде внешней обработки (желательно без ИР). Тогда я его отправлю в тех. поддержку производителя.

**Comment by tormozit** [comment]
> Перед открытием Подбора и обработки объектов возникает ошибка, но сам инструмент открывается:
> {Document.SupplierInvoice.ManagerModule(6937,2)}: Переменная не определена (InventoryOwnershipServer)
> <<?>>InventoryOwnershipServer.InfobaseUpdate_FillMainTableColumn("SupplierInvoice");
> У модуля InventoryOwnershipServer галка Клиент (Обычное приложение) отсутствует.

Переходи в режим запуска "Управляемое приложение". Там этой ошибки не будет.
