### ISSUE TITLE
Консоль кода. Непонятное описание ошибки, в случае наличия вызовов методов

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#510]
**Программное окружение**

Платформа: 8.3.21.1624
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.86.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ПатчДоставка ()
Расширения. ПатчРаспределениеУдержаний ()
Расширения. Патч_РасширениеРоли_ЭтапыДоставки ()
Расширения. Патч_Цислинк_20230817 ()
Расширения. ИмяКрмпании (1.1.1.9)
Расширения. зг_ЗУП (1.0.2.7)
Расширения. ЭР_Обмен_КА_БП (1.0.2.19)
Расширения. ИнструментыРазработчикаTormozit (6.86.2e)
Расширения. МаркетКоннекторКА2 (1.0.2.2)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Консоль кода
2. Ввел код с вызовом любой функции. галочка "Модуль" должна быть выключена
Например:
` Рез = Труляля();`
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/70c4feff-5a5a-4aa2-9763-b3f9c782f5f4)

4. Получил ошибку:

> Редактор встроенный: Строка кода 1: {(1,1)}: Метка с указанным именем уже определена

При этом ошибка всегда ссылается на последнюю строку:
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/e579cdc7-72ce-4d73-a6ed-bbe1283496fc)
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/20128d83-a7a2-409b-811c-0f9b068aba8f)

**Ожидаемое поведение**
Понятное описание ошибки, которое сразу намекает, что проблема в коде.

**Comment by tormozit** [comment]
Не удалось воспроизвести. Можешь воспроизвести в новом окне консоли ?

**Comment by KovAlexey** [comment]
Воспроизвел. Но как оказалось есть один нюанс.
В новой консоли ошибка повторяется только при нажатии заполнить

https://github.com/tormozit/RDT1C/assets/16429518/6f036354-94f0-4179-b4e2-eef4cdc89359

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/967654

**Comment by tormozit** [comment]
Исправлено в 6.87
