### ISSUE TITLE
Консоль запросов. Ведущая структура. Имена ВТ не отображаются при помещении

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#511]
**Программное окружение**

Платформа: 8.3.21.1624
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.86.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ПатчДоставка ()
Расширения. ПатчРаспределениеУдержаний ()
Расширения. Патч_РасширениеРоли_ЭтапыДоставки ()
Расширения. Патч_Цислинк_20230817 ()
Расширения. ИмяКрмпании (1.1.1.9)
Расширения. зг_ЗУП (1.0.2.7)
Расширения. ЭР_Обмен_КА_БП (1.0.2.19)
Расширения. ИнструментыРазработчикаTormozit (6.86.2e)
Расширения. МаркетКоннекторКА2 (1.0.2.2)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент консоль запросов
2. Ввел запрос
```
ВЫБРАТЬ 1 ПОМЕСТИТЬ ВТ;
ВЫБРАТЬ 1 ПОМЕСТИТЬ ВТ2;
ВЫБРАТЬ * ИЗ ВТ

```
3. Открываю ведущую структуру запроса, ожидаю увидеть там имена ВТ
4. Не вижу их
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/075a2e66-c2f7-4886-a10a-c6fbe19f49ec)

На больших запросах это особенно критично
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/7e957810-1368-4526-8173-10f124cbf011)

Что интересно, там где "Создать_Период" запрос выглядит так 
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/f7e06d7f-f358-4f67-86a9-736cf2e2e273)

**Ожидаемое поведение**
Как было раньше, когда трава была зеленее, а имена ВТ при помещении отображались в ведущей структуре

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/967645

**Comment by KovAlexey** [comment]
Способ обхода:
Сохранить и открыть сохранённый файл

**Comment by tormozit** [comment]
Исправлено в 6.87
