### ISSUE TITLE
Удаление объектов с контролем ссылок ошибка при выделении блокирующих объектов

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#513]
**Программное окружение**

Платформа: 8.3.19.1529
Режим БД: клиент-серверный
Конфигурация. Название: Business automation software for accounting (2.1.23.2)
Конфигурация. Основной режим запуска: Керована прикладна програма
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.88.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. Розширення1 ()
Расширения. Розширення2 ()
Расширения. СохранениеДокументов (23.07.11.001)
Расширения. ОбновлениеЦен (23.08.24.001)
Расширения. ИнструментыРазработчикаTormozit (6.88.2e)
Расширения. ЗапуститьСеансПользователя (2.1)
Клиент. Приложение: Керована прикладна програма 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: uk
Клиент. Язык интерфейса системы: uk
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Так
Клиент. ОС: Майкрософт Windows Server 2019 Datacenter 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows Server 2019 Datacenter 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Удаление объектов с контролем ссылок
2. Запустил контроль
3. Выделяю несколько объектов
![image](https://github.com/tormozit/RDT1C/assets/81148850/60914bf9-4de2-4803-b232-3e8a71800de4)

`Таблица БД с именем "Обработка.ирУдалениеОбъектовСКонтролемСсылок.СсылкиНаКандидата" не найдена
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(11681)}:		ВызватьИсключение "Таблица БД с именем """ + ПолноеИмяТаблицыБД + """ не найдена";
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10809)}:	ТекстЗапроса = ПолучитьТекстЗапросаПолейТаблицыБДЛкс(ПолноеИмяТаблицыБД, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10576)}:		ТаблицаРезультата = ПустаяТаблицаЗначенийИзТаблицыБДЛкс(ПолноеИмяТаблицыБД, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКэш.Модуль(72)}:	Результат = ирОбщий.ПоляТаблицыБДЛкс(ПолноеИмяТаблицыБД, НужныТолькоТипы, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(10581)}:		Результат = ирКэш.ПоляТаблицыБДЛкс(ПолноеИмяТаблицыБД, Истина, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКэш.Модуль(72)}:	Результат = ирОбщий.ПоляТаблицыБДЛкс(ПолноеИмяТаблицыБД, НужныТолькоТипы, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(12931)}:		ПоляБД = ирКэш.ПоляТаблицыБДЛкс(ПолноеИмяТаблицыБД);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(2710)}:		СтруктураКлюча = ирОбщий.СтруктураКлючаТаблицыБДЛкс(ПолноеИмяТаблицы,,, Ложь);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(3513)}:		КоллекцияСтрок = ДанныеСтрокДинамическогоСпискаЛкс(ТабличноеПоле, ТабличноеПоле.ВыделенныеСтроки, ирОбщий.СтрСоединитьЛкс(ИменаВидимыхКолонок),,, ЭтаФорма, Истина); // Долго
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(7149)}:	ТабличноеПолеОбновитьТекстыПодваловЛкс(Параметры.ЭтаФорма, Параметры.ТабличноеПоле, Ложь);
{(1)}:ирКлиент.ТабличноеПолеОбновитьТекстыПодваловОтложенноЛкс(ПараметрыОбработчикаОжидания)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(1856)}:	Выполнить(ПараметрыОбработчикаОжидания.ИмяМетода + "(ПараметрыОбработчикаОжидания)");
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(1797)}:		ОбработчикОжиданияСЯвнымиПараметрамиЛкс(Параметры);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(7142)}:		ПодключитьОбработчикОжиданияСПараметрамиЛкс("ирКлиент.ТабличноеПолеОбновитьТекстыПодваловОтложенноЛкс", ПараметрыОбработчика, Задержка,, Ложь);
{ИнструментыРазработчикаTormozit Обработка.ирУдалениеОбъектовСКонтролемСсылок.Форма.Форма.Форма(972)}:	ирКлиент.ТабличноеПолеПриАктивизацииСтрокиЛкс(ЭтаФорма, Элемент);
`

**Comment by tormozit** [comment]
Проблема связана с ограниченной поддержкой украинского языка интерфейса системы  (Клиент. Язык интерфейса системы: uk). Для ее обхода попробуй запустить с русским или английским языком системы. В описании подсистемы указано:

> Поддерживаются языки интерфейса системы (платформы)
>     русский
>     английский

**Comment by tormozit** [comment]
Делать полную поддержку этого режима работы пока не планирую. Кстати при открытии первой формы инструментов программа должна была сообщить

> Язык системы сеанса 1С (параметр /L) не является русским или английским. Корректная работа подсистемы "Инструменты разработчика" не гарантируется
