### ISSUE TITLE
АнализТЖ. Значение не является значением объектного типа (ПолеТекста)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#514]
https://github.com/tormozit/RDT1C/assets/87958986/ba5ab164-2acb-4b59-a803-8d284e884a6c

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.89.1p
Инструменты разработчика. Инструмент: Анализ техножурнала
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Загрузить журнал в инструменте "Анализ техножурнала"
2. Выделить любую строку события где не пустая "Строка модуля"
3. Появляется сообщение об ошибке

```
Значение не является значением объектного типа (ПолеТекста)
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(6091)}:	Если Ложь
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(6078)}:	ИмяМетода = НайтиИмяМетодаСтрокиФайлаМодуля(ОписаниеМодуля.ИмяФайлаМодуля, НомерСтроки, СодержаниеСтроки, ТекстыМодулей, СтароеИмяФайлаМодуляБезРасширения, ЧислоСтрокДляПоискаИмениМетода);
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(1461)}:		СтрокаСтека.Метод = мПлатформа.НайтиИмяМетодаСтрокиМодуля(СтрокаСтека.Модуль, СтрокаСтека.НомерСтроки, СтрокаСтека.СтрокаМодуля);
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(1422)}:			ОбновитьТаблицуКонтекста(ЗначениеПоля);
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(1394)}:	ОбновитьТекущуюСтраницуПанелиЭлемента();

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/968301 . Исправить самостоятельно можно вставкой фрагмента перед ошибочным "Если".
```
	Если ПолеТекстаМодуля = Неопределено Тогда
		Возврат Неопределено;
	КонецЕсли;
```

**Comment by tormozit** [comment]
Исправлено в 6.90
