### ISSUE TITLE
Управление итогами регистров. Отсутствует функционал

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#516]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.89.1p
Инструменты разработчика. Инструмент: Управление итогами регистров
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

В инструменте "Управление итогами регистров" отсутствует часть функционала связанная с Агрегатами

![image](https://github.com/tormozit/RDT1C/assets/87958986/8f0ad1fc-b064-48ed-95c3-fa8b6fdbc62e)

В БСП также есть 2 регламентных задания:

![image](https://github.com/tormozit/RDT1C/assets/87958986/d6bae42f-730b-42ce-bbe8-dd9a55f9f7c4)

Настройку выполнения которых можно было бы включить в форму инструмента.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/985324

**Comment by tormozit** [comment]
Сделано в 7.27
