### ISSUE TITLE
Техножурнал. TDEADLOCK. Значение не является значением объектного типа (ТекущийЭлемент)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#517]
https://github.com/tormozit/RDT1C/assets/87958986/5730a18a-0ec2-4ef3-8a8e-de6e9f871e5d

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.89.1p
Инструменты разработчика. Инструмент: Анализ техножурнала
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При активизации ячейки строки поля "Взиамоблокировки" событий TDEADLOCK в инструменте "Анализ техножурнала" возникает ошибка:

```
Значение не является значением объектного типа (ТекущийЭлемент)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(3625)}:	ФормаВладелец.ТекущийЭлемент = ПолеТекста.ЭлементФормы;
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(3864)}:						ПоказатьТекущиеКоординаты(пПолеТекста, СтартоваяСтрокаДляОтображенияОшибок);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(3742)}:	НачальныйТокен = РазобратьТекстЗапроса(ТекстЗапроса, СокращенноеДерево,,, Истина, ТаблицаКомментариев, БылиПотери, СтартоваяСтрокаДляОтображенияОшибок);
{ВнешняяОбработка.ирАнализТехножурнала.МодульОбъекта(2369)}:			Если ПолеТекста.ЗагрузитьТекстВКонструктор(ТекстМета, КонструкторЗапроса,, ДиалектSQL, ИменованныеПараметры) Тогда 
{ВнешняяОбработка.ирАнализТехножурнала.Форма.КонверторТекстаСУБД.Форма(45)}:	СтруктураЗапроса = СтруктураЗапросаИзТекстаБД(ЭлементыФормы.ТекстБД.ПолучитьТекст(), ТипСУБДЛ, ПересобратьТекст, ПереводитьИндексы, ПереводитьВМета,, ВстраиватьПараметры);
{ВнешняяОбработка.ирАнализТехножурнала.Форма.КонверторТекстаСУБД.Форма(97)}:	ОбновитьЗапрос();
{ВнешняяОбработка.ирАнализТехножурнала.МодульОбъекта(1975)}:	ФормаЗапроса.Открыть();
{ВнешняяОбработка.ирАнализТехножурнала.МодульОбъекта(2004)}:		ОткрытьТекстБДВКонверторе(ВыбраннаяСтрока[ИмяСвойстваБезМета], Не ирОбщий.СтрокиРавныЛкс(ИмяСвойстваБезМета, ИмяСвойства),
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(108)}:			ОткрытьТекстБДСтрокиЖурнала(ВыбраннаяСтрока, ИмяСвойства);

```

[23090909.log](https://github.com/tormozit/RDT1C/files/12565743/23090909.log)

**Comment by tormozit** [comment]
Старайся прикладывать либо выгрузку таблицы журнала либо файлы лога с сохранением структуры папок, т.к. часть информации находится в них.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/968580

**Comment by tormozit** [comment]
Исправлено в 6.90
