### ISSUE TITLE
Конструктор запросов ИР. Группирующие наборы

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#52]
https://user-images.githubusercontent.com/87958986/132717743-2da5099d-9f57-4d33-a328-3503ae91cff3.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.08.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Конструктор запросов ИР не поддерживает GROUPING SETS доступные с 2019 года. https://wonderland.v8.1c.ru/blog/podderzhka-grouping-sets-v-yazyke-zaprosov/

Пример запроса:

```
ВЫБРАТЬ
	АвансовыйОтчет.Ссылка КАК Ссылка
ИЗ
	Документ.АвансовыйОтчет КАК АвансовыйОтчет

СГРУППИРОВАТЬ ПО ГРУППИРУЮЩИМ НАБОРАМ
(	
(	АвансовыйОтчет.Ссылка),
(	АвансовыйОтчет.Ссылка)

)

```

**Comment by tormozit** [comment]
Такая задача уже давно есть https://www.hostedredmine.com/issues/877515
Пока я в реальных запросах не встречал применения этой конструкции. У тебя есть?

**Comment by PerlAmutor** [comment]
Тогда извиняюсь.

Нет пока не пробовал, что это за конструкция, хотя похожие запросы у меня есть. Возможно, когда-нибудь попробую переписать через группирующие наборы.
