### ISSUE TITLE
Конфликт имен методов в расширениях (Наблюдать)

### ISSUE THREAD

**Issue by Absolemus** [tormozit/RDT1C#520]
В общем глобальном модуле ирГлобальный есть метод Наблюдать. С ним конфликтует экспортный метод Наблюдать неглобального общего модуля другого расширения.

Прошу рассмотреть возможность исправления конфликта наименований методов на стороне ИР.

Этот вопрос поднимался [тут](https://github.com/tormozit/RDT1C/issues/302)

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/968833

**Comment by tormozit** [comment]
Сделано в 6.91

**Comment by Absolemus** [comment]
Спасибо
