### ISSUE TITLE
Консоль запросов. Параметры. Список значений. Вставка скопированного значения. Метод объекта не обнаружен (Количество)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#522]
https://github.com/tormozit/RDT1C/assets/87958986/77c5af42-223f-419b-95d2-4525d537bc47

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: клиент-серверный
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: НеИспользовать
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 6.95.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс

</details>

**Воспроизведение проблемы**
1. Скопировать ссылку в буфер обмена
2. Добавить параметр в Консоль Запросов
3. Изменить Вид параметра на Список Значений
4. Вставить ссылку в добавленный параметры
5. Войти в режим редактирования значения параметра
6. Получить ошибку:

```
Метод объекта не обнаружен (Количество)
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(4105)}:			Если ТекущиеДанные.Значение.Количество() = 0 Тогда // Иначе можно потерять значения в списке

```

**Comment by tormozit** [comment]
Исправление этой ошибки видится опасным. Поэтому пока рекомендую выполнять вставку в форму списка значений.

**Comment by tormozit** [comment]
Проверил. Теперь не воспроизводится. Видимо было исправлено в рамках решения другой проблемы.
