### ISSUE TITLE
Конструктор запросов ИР. Перейти к определению. Ошибка при установке значения атрибута контекста (ТекущаяСтрока)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#524]
https://github.com/tormozit/RDT1C/assets/87958986/e0bdf694-d429-483b-8bc9-6d1e1bf7f1af

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.47)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.97.1p
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл запрос через Конструктор Запросов ИР:
```
//{Запрос: 0, -3 ////////////////////////////////////////
ВЫБРАТЬ
	Т.Ссылка КАК Регистратор
ПОМЕСТИТЬ ВтДанные
ИЗ
	Справочник.Сотрудники КАК Т
;
//{Запрос: 1, -2 ////////////////////////////////////////
ВЫБРАТЬ
	Т.Ссылка КАК Ссылка
ПОМЕСТИТЬ ВтДанные2
ИЗ
	Справочник.Сотрудники КАК Т
;
//{Запрос: 2, -1 ////////////////////////////////////////
ВЫБРАТЬ
	Т.Регистратор КАК Поле1,
	Т2.Ссылка КАК Поле2
ИЗ
	ВтДанные КАК Т
	ЛЕВОЕ СОЕДИНЕНИЕ ВтДанные2 КАК Т2
	ПО ИСТИНА
```
2. Перешел на страницу "Текст запроса/пакета"
3. Установил курсор на "Т2.Ссылка"
4. Вызвал "Перейти к определению" клавишей F12
5. Получил ошибку

```
Ошибка при установке значения атрибута контекста (ТекущаяСтрока)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(11304)}:				ЭлементыФормы.ДоступныеПоляУсловия.ТекущаяСтрока = СтрокаЗапросаСоздания;
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(11377)}:	МенюДоступныхПолейПерейтиКВыбраннойТаблице(, Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(3519)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1251)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1199)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(323)}:		Результат = Компонента.Нажатие(Кнопка);
по причине:
Отсутствует ключ строки

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/971263

**Comment by tormozit** [comment]
Исправлено в 6.97.2

**Comment by PerlAmutor** [comment]
> Исправлено в 6.97.2

Я правильно понимаю, что если портативной версии 6.97.2 не появилось с исправлением этой ошибки, то считается, что она никогда не будет исправлена в портативном варианте после того как я закрою эту заявку?

**Comment by tormozit** [comment]
Если ошибка касается портативного режима, но не исправлена в его коде, то я об этом стараюсь сразу писать в задаче. И такие исправления случаются такое довольно редко.

**Comment by PerlAmutor** [comment]
Ну в 6.97.3p она не исправилась

![image](https://github.com/tormozit/RDT1C/assets/87958986/278d1822-05e4-4bac-a31f-31c7094a5921)

**Comment by tormozit** [comment]
Я еще раз проверил. **В точности** повторил действия по видео. Ошибки нет. А раньше она была. Запиши новое видео.

**Comment by PerlAmutor** [comment]
https://github.com/tormozit/RDT1C/assets/87958986/d5252c57-2da2-45ad-b9e2-7851fdbc90d6

**Comment by tormozit** [comment]
Ранее ты каретку ставил на выражение выбранного поля. В новом видео ты ее поставил на псевдоним. Ошибку воспроизвел. Задачу перенес.

**Comment by tormozit** [comment]
Исправлено в 6.98

**Comment by PerlAmutor** [comment]
F12 и непосредственное выполнение команды "Перейти к определению (F12)" работают по разному. В некоторых случаях F12 вообще перестает срабатывать, а вызов команды "Перейти к определению" вообще выдает ошибку:

```
Значение не является значением объектного типа (Модуль)
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4682)}:Если ПакетЗапросов.КоординатыТекста.Модуль = мМодульМетаданных Тогда
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4183)}:НайтиОпределениеСлова(мКонтекст, ПоследнееОпределение, ПоследнееВхождение);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1291)}:ПерейтиКОпределению();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1207)}:Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(64)}:Результат = ЭкземплярКомпоненты.Нажатие(Кнопка);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(3593)}:РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1259)}:Результат = ВызватьКонструкторЗапросов(Истина);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1207)}:Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(323)}:Результат = Компонента.Нажатие(Кнопка);

```


https://github.com/tormozit/RDT1C/assets/87958986/a0ba1583-6c34-41fd-9fa0-939733e71f07

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/972533

**Comment by tormozit** [comment]
Исправлено в 6.98.3
