### ISSUE TITLE
Выбор списка значений (из консолей). Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств). 6.97.3e

### ISSUE THREAD

**Issue by dimjmur** [tormozit/RDT1C#525]
Консоль запросов, также проверено в консоли СКД. 6.97.3e. Применимо с 6.97.1 
*в ИР 6.96.2e нет этой ошибки*
При заполнении пераметров запроса, выбираем вид параметра "список".
Выбираем необходимые значения, нажимаем ОК 
Ошибка: 
**Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств)**
**{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.СписокЗначений.Форма(10)}:		ЗаполнитьЗначенияСвойств(ЭлементСписка, СтрокаТаблицы);**
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.СписокЗначений.Форма(43)}:		Результат = ПолучитьРезультат();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(4896)}:			РезультатВыбора = Форма.ОткрытьМодально();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(5660)}:		Результат = ОткрытьЗначениеЛкс(РасширенноеЗначение, РедактированиеРазрешено, СтандартнаяОбработка, Заголовок,, ПринудительноВОтдельнойФорме,, ТабличноеПоле, СтрокаПоиска, КлючУникальности);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(6612)}:		Если ирКлиент.ЯчейкаТабличногоПоляРасширенногоЗначения_ВыборЛкс(ЭтаФорма, Элемент, СтандартнаяОбработка,,,,, ВыбраннаяСтрока.ИмяПараметра) Тогда 
по причине:
Ошибка установки значения свойства 'Картинка'
по причине:
Несоответствие типов

![скрин](https://github.com/tormozit/RDT1C/assets/47595842/fdeb3f39-c7b7-449e-9965-77e4ebd7884a)

**Программное окружение**

>Платформа: 8.3.21.1709
Режим БД: клиент-серверный
Конфигурация. Название: 
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Инструменты разработчика. Версия: Расширение 6.97.3e
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.97.3e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-bit 
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Active code page: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная 
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/971466

**Comment by tormozit** [comment]
Исправлено в 6.97.4

**Comment by dimjmur** [comment]
> Исправлено в 6.97.4

Обновился. Всё заработало
