### ISSUE TITLE
Анализ данных. Консоль запросов. Поле объекта не обнаружено

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#526]
https://github.com/tormozit/RDT1C/assets/87958986/ce4c5416-fcc5-497e-a55b-18b38b46ae25

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.47)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.97.3p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Выполнить любой запрос в Консоли Запросов
2. Вызвать "Анализ данных" над результатом запроса
3. В открывшемся окне вызвать команду "Источник"
4. Удалить любую колонку, нажать "Закрыть", согласиться на предложение "Сохранить"
5. Вернуться в консоль запросов и нажать "Выполнить"
6. Появится подобная ошибка

```
Поле объекта не обнаружено (Поле1)
{ВнешняяОбработка.ирКлиент.МодульОбъекта(12230)}:	СтараяКолонкаТЗ = ТабличноеПолеРезультата.Значение.Колонки[СтараяКолонкаТП.Имя];
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(1521)}:			мСтарыеКолонкиТабличногоПоляРезультата.Вставить(ирКлиент.КлючХраненияНастроекКолонкиРезультатаЗапросаЛкс(ЭлементыФормы.РезультатКоллекция, СтараяКолонкаТП), СтараяКолонкаТП);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(1231)}:		СохранитьСтарыеКолонкиТабличногоПоляРезультата();
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(10366)}:		ЗагрузитьРезультатЗапроса(,, Истина);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(2310)}:		ЭлементыФормы.ТаблицаРезультатаПакета.ТекущаяСтрока = ТаблицаРезультатаПакета[ПолучитьИндексПоследнегоРезультатЗапросаИзРезультатаПакета()];
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(2149)}:		ЗагрузитьРезультатПакета();

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/971484

**Comment by tormozit** [comment]
Исправлено в 6.98

**Comment by PerlAmutor** [comment]
Что-то не исправилось:

```
Поле объекта не обнаружено (Ссылка)
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(427)}:СтараяКолонка = Таблица.Колонки[ИмяСтаройКолонки];
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(407)}:ОбновитьКолонкиТаблицы(Истина);

```


https://github.com/tormozit/RDT1C/assets/87958986/8336a80f-e33d-4ed1-a8de-e10155637981

**Comment by tormozit** [comment]
запрещу редактирование в отдельном окне источника в следующей версии

**Comment by tormozit** [comment]
Запретил редактирование источника в отдельном окне в 7.01
