### ISSUE TITLE
Редактор выражения компоновки данных. Текст программы не допускает определения методов. 6.97.3e

### ISSUE THREAD

**Issue by dimjmur** [tormozit/RDT1C#527]
Консоль СКД. 6.97.3e. Применимо с 6.97.1
в ИР 6.96.2e нет этой ошибки
При работе в редакторе выражения компонвки данных, например страница "вычисляемые поля" или "ресурсы" выдается програмное исключение: 
Текст программы не допускает определения методов
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(10356)}:ВызватьИсключение "Текст программы не допускает определения методов";
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(10466)}:ИнформацияОбОшибке = ПроверитьТекстИВернутьОшибку(ТекстДляПроверки, СтартоваяСтрока, СтартоваяКолонка, Контекст);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКомпоновокДанных.Форма.РедакторВыраженияКомпоновки.Форма(165)}:Если Не ПолеТекстаВыражения.ПроверитьПрограммныйКод() Тогда
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКомпоновокДанных.Форма.РедакторВыраженияКомпоновки.Форма(184)}:СохранитьИзменения();
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(2911)}:Результат = Форма.ОткрытьМодально();

Выражение в редакторе корректное. Проверено на разных СКД
![зображення](https://github.com/tormozit/RDT1C/assets/47595842/ee104e3b-bf9d-4bfe-84ec-10e905c856ac)

**Программное окружение**
>Платформа: 8.3.21.1709
Режим БД: клиент-серверный
Конфигурация. Название: 
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.97.3e
Инструменты разработчика. Инструмент: Консоль компоновок данных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.97.3e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-bit 
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Active code page: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная 
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Comment by tormozit** [comment]
Воспроизвести не удалось. Попробую исправить всплепую https://www.hostedredmine.com/issues/971483

**Comment by tormozit** [comment]
Предположительно исправлено в 6.97.4

**Comment by dimjmur** [comment]
могу прислать файл консли СКД. Конфа давно не типовая. Но запросы можно воспроизвести на типовой БУ. Там где есть РегистрБухгалтерии.Хозрасчетный

**Comment by dimjmur** [comment]
> Предположительно исправлено в 6.97.4

Обновился. Всё заработало
