### ISSUE TITLE
Редактор пользователей. Запуск от имени

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#528]
Очень бы хотелось, чтоб можно было запустить конкретного пользователя, установив ему (хотя бы на время сеанса) "Каталог объектов для отладки" такой же, как у пользователя, из под которого выполняется запуск.
У меня довольно частый сценарий - это когда я захожу из под пользователя и сохраняю схему и настройки через ИрОбщий.ОтЛкс().  При этом потом использую эту сохраненную схему при запуске от других.
В том числе иногда я сохраняю из одной базы, потом отлаживаю в копии\другой такой же конфигурации.

Сохранять из консоли компоновки в файл - не вариант. Т.к. иногда есть ВТ и тд.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/972026

**Comment by tormozit** [comment]
Сделано в 6.98
