### ISSUE TITLE
Консоль кода. Список значений в параметрах. Несоответствие типов. Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#529]
https://github.com/tormozit/RDT1C/assets/87958986/332c9c11-b59c-42b0-8a87-3a18cbc2b9df

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.47)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.97.3p
Инструменты разработчика. Инструмент: Консоль кода
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл Консоль кода, добавил параметр с типом СписокЗначений,
2. Нажал Добавить
3. Выбрал ссылочный тип на документ
4. Выбрал ссылку на документ
5. Нажал "ОК"
6. Получил ошибку:

```
Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств)
{ВнешняяОбработка.ирПлатформа.Форма.СписокЗначений.Форма(10)}:		ЗаполнитьЗначенияСвойств(ЭлементСписка, СтрокаТаблицы); 
{ВнешняяОбработка.ирПлатформа.Форма.СписокЗначений.Форма(43)}:		Результат = ПолучитьРезультат();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(5517)}:	РезультатФормы = ФормаРедактирования.ОткрытьМодально();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(5802)}:			ЗначениеИзменено = РедактироватьСписокЗначенийЛкс(РасширенноеЗначение, СтруктураОтбора, Заголовок);
{ВнешняяОбработка.ирКонсольКода.Форма.Форма.Форма(1469)}:	Если ирКлиент.ПолеВводаКолонкиРасширенногоЗначения_НачалоВыбораЛкс(ЭтаФорма, ЭлементыФормы.Параметры, СтандартнаяОбработка, ЭлементыФормы.Параметры.ТекущаяСтрока.Значение,,,,,
по причине:
Ошибка установки значения свойства 'Картинка'
по причине:
Несоответствие типов

```

**Comment by tormozit** [comment]
https://www.hostedredmine.com/issues/971466

**Comment by PerlAmutor** [comment]
> https://www.hostedredmine.com/issues/971466

Ну 6.97.4p пока не существует, т.ч. видимо не зря багрепорт оставил.
