### ISSUE TITLE
Консоль кода. Переименование функции в режиме модуля

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#530]
**Программное окружение**

Платформа: 8.3.21.1775
Режим БД: клиент-серверный
Конфигурация. Название: Торговый дом 7 SE (7.0.33.7)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Расширение 6.96.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.96.1e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс
Сервер. ОС: Microsoft Windows Server 2016 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Консоль кода
2. создал алгоритм в режиме модуля с функциями
3. Нажал сочетание ctrl-alr-r чтобы переименовать функцию
4. Получил окно с ошибкой 

`Шаблонная строка "переменную" не найдена в тексте
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(30853)}:		ВызватьИсключение "Шаблонная строка """ + ЧтоЗаменять + """ не найдена в тексте";
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.ПереименоватьСлово.Форма(43)}:		ЭтаФорма.Заголовок = ирОбщий.СтрЗаменитьЛкс(Заголовок, "переменную", "метод");
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1914)}:	РезультатФормы = Форма.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(3574)}:	ФормаПереименования = ПолеТекстаАлгоритма.ПереименоватьСлово();
`

**Ожидаемое поведение**
функция переименовалась

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/971997

**Comment by tormozit** [comment]
Исправлено в 6.98
