### ISSUE TITLE
Консоль кода. При включенном TurboConf в поле ввода текста программы пропадает фокус после контекстной подсказки

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#531]
**Программное окружение**

Платформа: 8.3.21.1775
Режим БД: клиент-серверный
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Расширение 6.96.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.96.1e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс
Сервер. ОС: Microsoft Windows Server 2016 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Запущен TurboConf
2. Открыл инструмент Консоль кода
3. Пишу алгоритм в окне текста программы
4. Получаю контекстную подсказку
5. Теряется фокус окна ввода текста программы
6. Приходится мышкой "возвращать курсор"

**Ожидаемое поведение**
Ожидалось что TurboConf и ИР не будут конфликтовать в консоли кода

**Comment by tormozit** [comment]
Если при отключенном TurboConf проблемы не наблюдается, то расследование нужно начинать в TurboConf , т.к. он работает на более низком уровне и активно вмешается в работу окон. Проверь в нем флажок
![изображение](https://github.com/tormozit/RDT1C/assets/11896251/54f2d342-2aed-4933-b369-fd5b6d2de347)

**Comment by dmitri-0** [comment]
включение галки помогло
TurboConf и ИнструментыРазработчика работают совместно корректно
Сергей, прошу закрыть заявку

**Comment by tormozit** [comment]
В**ы**ключенный флажок как раз должен блокировать активность Турбоконфа в этом окне. А включенный - разрешать. Поэтому включение флажка - неожиданно для меня - устранило проблему, но вероятно приведет к возникновению других. Нужно все же донести проблему до разработчика Турбоконфа. Закрывать заявку ты можешь сам.
