### ISSUE TITLE
Консоль компоновок данных. Вариант по умолчанию после копирования и затем редактирования

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#532]
**Программное окружение**

Платформа: 8.3.21.1709
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Конфигурация 6.96.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл инструмент Консоль компоновок данных
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/4411afd6-1b01-41c7-b61f-3c03e80481a8)

2. Скопировал отчет нажав F9
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/593b7928-ff29-46cb-8b75-710b0f4520c5)

3. Открыл Консоль запросов, нажал применить
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/6952d18b-da9a-49a6-ba16-efb2a92afe0a)
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/8c21e9da-9ab2-49e3-964d-a00746e2b404)
4. После чего открылся конструктор схемы компоновки, где нажал ОК
5. Настройки сбросились на настройки по умолчанию
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/dca90ea4-0cb5-4e71-aca2-c835178debcb)

**Ожидаемое поведение**

Диалоговое окно с вопросом про загрузку настроек по умолчанию

**Comment by KovAlexey** [comment]
При копировании перетаскиванием такого не происходит
Только при копировании через стандартную кнопку скопировать или же через горячую клавишу

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/973037

**Comment by tormozit** [comment]
Исправлено в 7.00
