### ISSUE TITLE
Консоль запросов. Неверное присоединение

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#533]
https://github.com/tormozit/RDT1C/assets/87958986/b9dcc0c5-e9ca-4a92-af64-19571d8dcd37

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: клиент-серверный
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: НеИспользовать
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 6.98.1e
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.98.1e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

</details>

**Воспроизведение проблемы**
1. При выполнении запроса в Консоли Запросов:
```
ВЫБРАТЬ
	Т.Ссылка
ИЗ
	Справочник.Справочник1 КАК Т
```
3. Возникает ошибка:

```
Текст запроса: Строка кода 4: {(4,15)}: Неверное присоединение
SELECT * FROM <<?>>
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/972499

**Comment by tormozit** [comment]
Исправлено в 6.98.2
