### ISSUE TITLE
Анализ техножурнала. Обрезается стек вызовов.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#534]
https://github.com/tormozit/RDT1C/assets/87958986/f3c2294b-6799-4f27-8f9a-a340faa65885

[тест.zip](https://github.com/tormozit/RDT1C/files/13120276/default.zip)

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: клиент-серверный
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: НеИспользовать
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 6.98.2e
Инструменты разработчика. Инструмент: Анализ техножурнала
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.98.2e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

</details>

**Воспроизведение проблемы**
1. Открыть Анализ Техножурнала
2. Загрузить в него прикрепленный файл
3. Видно, что событие исключения заканчивается на одинарной кавычке, но не на последней, обрезая важную информацию о стеке вызовов.

В оригинале событие выглядит так:

```
58:01.302077-0,EXCP,2,process=rphost,p:processName=erp,OSThread=46192,t:clientID=17950,t:applicationName=1CV8C,t:computerName=computer1,t:connectID=1022245,SessionID=82149,Usr=Пользователь1,AppID=1CV8C,Exception=afd2b550-0d52-4e03-b448-15ed68d87ac5,Descr='src\basic\src\DocumentLogFormObjController.cpp(884):
afd2b550-0d52-4e03-b448-15ed68d87ac5
0d2200af-1696-4395-91e5-2872675e6d3d: Ошибка при выполнении обработчика - ''ОбработкаПроведения''
8d366056-4d5a-4d88-a207-0ae535b7d28e: Преобразование значения к типу Булево не может быть выполнено
{ОбщийМодуль.ЗапасыСервер.Модуль(611)}:		ПерезаполнитьВидыЗапасов = Документ.ДополнительныеСвойства.Свойство("ПерезаполнитьВидыЗапасов")
{ОбщийМодуль.ПроведениеДокументов.Модуль(2140)}:		Механизм.Значение.МодульМеханизма.СообщитьОРезультатахКонтроляИзменений(РезультатыКонтроля, Документ, Отказ);
{ОбщийМодуль.ПроведениеДокументов.Модуль(1549)}:	ВыполнитьКонтрольРезультатовПроведения(Механизмы, Документ, МенеджерВременныхТаблиц, Отказ);
{ОбщийМодуль.ПроведениеДокументов.Модуль(221)}:	ПровестиДокумент(Документ, Отказ, ДопПараметры);
{Документ.ПрочееОприходованиеТоваров.МодульОбъекта(288)}:	ПроведениеДокументов.ОбработкаПроведенияДокумента(ЭтотОбъект, Отказ);
'
```

А так его показывает Анализ техножурнала:

```
src\basic\src\DocumentLogFormObjController.cpp(884):
afd2b550-0d52-4e03-b448-15ed68d87ac5
0d2200af-1696-4395-91e5-2872675e6d3d: Ошибка при выполнении обработчика - ''ОбработкаПроведения'
```

Отсутствует часть идущая после ''ОбработкаПроведения'
Возможно некорректно составлено реглярное выражение, часть связанная с одинарными кавычками.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/972620

**Comment by tormozit** [comment]
Исправлено в 6.99
