### ISSUE TITLE
Консоль запроса. Конструктор запроса ИР. Ошибка при открытии.

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#535]
**Программное окружение**

Платформа: 8.3.21.1775
Режим БД: клиент-серверный
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Расширение 6.98.2e
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.98.2e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс
Сервер. ОС: Microsoft Windows Server 2016 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Нажал кнопку Конструктор запросов ИР
3. Получил окно с ошибкой 

`Значение не является значением объектного типа (Структура)
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4803)}:	Если ПакетЗапросов.Структура = Неопределено Тогда
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4790)}:	ПодготовитьПакетЗапросов(ПакетЗапросов);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5105)}:		выхИндексЗапроса = НайтиИндексЗапросаСозданияВременнойТаблицы(ТекущееСлово, выхПакетЗапросовТекущий);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5006)}:						ПостроительЗапроса = НайтиЗапросВременнойТаблицы(ТекущееСлово, РодительскаяСтруктураТипа.ДержательМетаданных);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5788)}:				ВычислитьТипДочернегоЭлемента(ТаблицаТиповРодителя, ТекущееСлово, ТипСлова, ТекущийИндекс, ТекущиеАргументы, ПредшествующийТекст, ПолныйАнализСоставаТипов, ЛиПеременнаяМодуля,
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5779)}:					ТаблицаТиповРодителя = ВычислитьТипЗначенияВыражения(РодительскийКонтекст, ТекстДляПоискаОпределения, ПредшествующийТекст, РазрешитьАнализИмениТипа,, ПолныйАнализСоставаТипов, Ложь,,,,,
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(8507)}:		ТаблицаТиповКонтекста = ВычислитьТипЗначенияВыражения(ПолноеИмяТаблицы);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(8488)}:		ОбновитьТаблицуПараметровВыбраннойТаблицы(мТекущаяСтрокаВыбранныеТаблицы);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(8467)}:	ЗагрузитьВыбраннуюТаблицу();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(3603)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1259)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1207)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(323)}:		Результат = Компонента.Нажатие(Кнопка);
`

текст запроса
`ВЫБРАТЬ
	РаспределениеОтветственныхПоСК.Ответственный_1 КАК Ответственный_1,
	РаспределениеОтветственныхПоСК.Ответственный_2 КАК Ответственный_2,
	РаспределениеОтветственныхПоСК.Ответственный_3 КАК Ответственный_3,
	РаспределениеОтветственныхПоСК.Ответственный_4 КАК Ответственный_4,
	РаспределениеОтветственныхПоСК.ОтветственныйДляЛистаЗДФ КАК ОтветственныйДляЛистаЗДФ,
	РаспределениеОтветственныхПоСК.Период КАК Период,
	РаспределениеОтветственныхПоСК.СтруктурнаяЕдиница КАК СтруктурнаяЕдиница
ПОМЕСТИТЬ вт_РаспределениеОтветственныхПоСК
ИЗ
	РегистрСведений.РаспределениеОтветственныхПоСК КАК РаспределениеОтветственныхПоСК
ГДЕ ИСТИНА
	И РаспределениеОтветственныхПоСК.Период >= &ПериодНачало
	И РаспределениеОтветственныхПоСК.Период <= &ПериодКонец

ВЫБРАТЬ
	ДополнительныеСведенияпоСЕ.Информация КАК Информация,
	ДополнительныеСведенияпоСЕ.Период КАК Период,
	ДополнительныеСведенияпоСЕ.СтруктурнаяЕдиница КАК СтруктурнаяЕдиница,
	ДополнительныеСведенияпоСЕ.ТипДопИнформации КАК ТипДопИнформации,
	ДополнительныеСведенияпоСЕ.Фирма КАК Фирма
ПОМЕСТИТЬ вт_ДополнительныеСведенияпоСЕ
ИЗ
	РегистрСведений.ДополнительныеСведенияпоСЕ КАК ДополнительныеСведенияпоСЕ
ГДЕ ИСТИНА
	И ДополнительныеСведенияпоСЕ.ТипДопИнформации В (&ТипДопИнформации)
	И ДополнительныеСведенияпоСЕ.Период >= &ПериодНачало
	И ДополнительныеСведенияпоСЕ.Период <= &ПериодКонец
`
**Ожидаемое поведение**
без ошибки

**Comment by PerlAmutor** [comment]
Такая же проблема:

https://github.com/tormozit/RDT1C/assets/87958986/bf6f2cab-3ff0-490b-b6a0-d43e64e720df

```

ВЫБРАТЬ
	Т.Ссылка КАК Ссылка
ИЗ
	Справочник.Справочник1 КАК Т

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/972557

**Comment by tormozit** [comment]
Исправлено в 6.98.3
