### ISSUE TITLE
Консоль запроса. Значение не является значением объектного типа (Строки)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#536]
https://github.com/tormozit/RDT1C/assets/87958986/b360cbae-1509-4725-a6f4-d14a8707df82

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: клиент-серверный
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: НеИспользовать
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 6.98.2e
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.98.2e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

</details>

**Воспроизведение проблемы**
1. В Консоль Запросов вставил запрос:
```
ВЫБРАТЬ
	1 КАК Поле1
ПОМЕСТИТЬ вт_Таблица

```
3. Установил курсор на имя временной таблицы
4. Вызвал F12 (или команду Перейти к определению)
5. Получил ошибку:

```
Значение не является значением объектного типа (Строки)
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(621)}:Для Каждого ДочерняяСтрока Из ЭлементыФормы.ДеревоЗапроса.ТекущаяСтрока.Строки.НайтиСтроки(Новый Структура("ТипУзла", "<FromUnion>")) Цикл
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(636)}:СтрокаЗапросаСоздания = НайтиСтрокуДереваВложенногоЗапроса(ОпределениеСлова);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(507)}:ПереходВыполнен = ПроверитьПерейтиКСтрокеВложенногоЗапроса(ПолеТекстаЗапроса, ПервыйФрагмент, ФрагментыВыражения);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(464)}:Результат = ПерейтиКОпределениюПоИмени(ТекущееВыражение, ЕстьТочкаСправа);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(317)}:Если ПерейтиКОпределениюВФорме() Тогда

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/972558

**Comment by tormozit** [comment]
Исправлено в 6.98.3
