### ISSUE TITLE
Консоль запросов. ADO. Проверка мутабельных значений на заполненность не поддерживается

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#537]
https://github.com/tormozit/RDT1C/assets/87958986/a4264014-1e0a-4408-877d-79a6abf90114

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: клиент-серверный
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: НеИспользовать
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 6.98.2e
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.98.2e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

</details>

**Воспроизведение проблемы**
1. Сформировал отчет по статистике запросов через инструмент "Статистика по запросам СУБД"
2. Из этого инструмента вызвал команду "Открыть запрос статистики в консоли запросов"
3. В открывшейся Консоли Запросов вызвал "Выполнить"
4. Получил ошибку:

```
Проверка мутабельных значений на заполненность не поддерживается
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(2008)}:Если Ложь

по причине:
Проверка мутабельных значений на заполненность не поддерживается
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/972559

**Comment by tormozit** [comment]
Исправлено в 6.98.3
