### ISSUE TITLE
Консоль запросов. Конфликт нажатия ctrl-d с TurboConf

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#538]
**Программное окружение**

Платформа: 8.3.21.1775
Режим БД: клиент-серверный
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Расширение 6.98.3e
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.98.3e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс
Сервер. ОС: Microsoft Windows Server 2016 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

подключен TurboConf

**Воспроизведение проблемы**

1. Открыл инструмент Консоль запросов
2. Нажал кнопку ctrl-d
3. TurboConf перехватывает нажатие, пытается выполнить команду Окружить

**Ожидаемое поведение**
Скрыть/показать панель Результат в консоли запросов

Стоит ли переназначить сочетание ctrl-d в TurboConf ?

**Comment by tormozit** [comment]
Я уже объяснял, что Турбоконф во всем виноват. Он не должен вмешиваться в работу клиентского приложения. Кроме того ты сам включил флажок, который ему это разрешает, не смотря на мой совет этого НЕ делать. https://github.com/tormozit/RDT1C/issues/531

**Comment by dmitri-0** [comment]
спасибо, отключил
