### ISSUE TITLE
Консоль компоновки данных по кнопке Сформировать - ошибка

### ISSUE THREAD

**Issue by awk-kazmin** [tormozit/RDT1C#539]
Платформа: 8.3.23.1865
Режим БД: клиент-серверный
Конфигурация. Название: БИТ: Строительство (БИТ.ФИНАНС) КОРП, редакция 3.0 (3.0.141.39/3.1.57.2/3.0.1.253)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.98.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Расширения. БизнесРУ_Фискализация (1.3.1.19)
Расширения. Инвентаризация_НМА_РБП (1.3.1)
Расширения. ФинПланВстраиваемый (2.0.22.0)
Расширения. ОшибкаВРасходахУменьшающихНалоги ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс
Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 17763)

### ОШИБКА

{ВнешняяОбработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(541)}:    Если ЗначениеЗаполнено(ВременныеТаблицы[ВременныеТаблицы.ВГраница()].Значение) Тогда
{ВнешняяОбработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(637)}:  МакетКомпоновкиДанных = МакетКомпоновки(,, СтруктураВнешниеНаборыДанных,, МенеджерВременныхТаблиц);
{ВнешняяОбработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(1199)}:  Если ВыполнитьОтчет() Тогда

### Причина

Возвращается не массив, а список значений

### Исправление 

стр. 541

Если ЗначениеЗаполнено(ВременныеТаблицы[ВременныеТаблицы.Количество()-1].Значение) Тогда

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/972719

**Comment by tormozit** [comment]
Исправлено в 6.99
