### ISSUE TITLE
Конструктор запросов. Структура запроса. Невозможно отладить.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#54]
https://user-images.githubusercontent.com/87958986/132721860-e5f2acf7-433a-44fb-bca2-4b8746954e5b.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.08.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Есть подобный запрос, где на вкладке "Перед выполнением запроса" идет установка ТЗ в качестве параметра запроса. Я прикрепил упрощенный вариант. Но в реальном варианте из файла извлекается сериализованная ТЗ и помещается во временную таблицу.

[ВнешняяТЗ.zip](https://github.com/tormozit/RDT1C/files/7138095/default.zip)

При попытке найти самые медленные участки в пакете запроса я использую структуру запроса, но из-за того, что код на вкладке "Перед выполнение запроса" выполняется лишь для корня узла, то выполнить все подзапросы не представляется возможным из-за ошибки:

```
Текст запроса: Строка кода 2: {(2,17)}: Неверные параметры "ТЗ2"
ПОМЕСТИТЬ ТЗ ИЗ <<?>>&ТЗ2 КАК Т
```

**Comment by tormozit** [comment]
Да. Похоже этот момент я не учел при последнем изменении поведения этого обработчика https://www.hostedredmine.com/issues/933016

**Comment by tormozit** [comment]
Исправлено в 6.08.2
