### ISSUE TITLE
Конструктор запроса ИР, переход на закладку "Выбор таблиц"

### ISSUE THREAD

**Issue by awk-kazmin** [tormozit/RDT1C#540]
**Программное окружение**

Платформа: 8.3.23.1865
Режим БД: клиент-серверный
Конфигурация. Название: БИТ: Строительство (БИТ.ФИНАНС) КОРП, редакция 3.0 (3.0.141.39/3.1.57.2/3.0.1.253)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.98.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Расширения. ФинПланВстраиваемый (2.0.22.0)
Расширения. БизнесРУ_Фискализация (1.3.1.19)
Расширения. Инвентаризация_НМА_РБП (1.3.1)
Расширения. ОшибкаВРасходахУменьшающихНалоги ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс
Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 17763)

**Воспроизведение проблемы**
1. Открыл инструмент Конструктор запроса ИР
2. переход на закладку "Выбор таблиц"
3. Получил окно с ошибкой 

Значение не является значением объектного типа (Структура)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4803)}:	Если ПакетЗапросов.Структура = Неопределено Тогда
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4790)}:	ПодготовитьПакетЗапросов(ПакетЗапросов);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5105)}:		выхИндексЗапроса = НайтиИндексЗапросаСозданияВременнойТаблицы(ТекущееСлово, выхПакетЗапросовТекущий);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5006)}:						ПостроительЗапроса = НайтиЗапросВременнойТаблицы(ТекущееСлово, РодительскаяСтруктураТипа.ДержательМетаданных);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5788)}:				ВычислитьТипДочернегоЭлемента(ТаблицаТиповРодителя, ТекущееСлово, ТипСлова, ТекущийИндекс, ТекущиеАргументы, ПредшествующийТекст, ПолныйАнализСоставаТипов, ЛиПеременнаяМодуля,
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5779)}:					ТаблицаТиповРодителя = ВычислитьТипЗначенияВыражения(РодительскийКонтекст, ТекстДляПоискаОпределения, ПредшествующийТекст, РазрешитьАнализИмениТипа,, ПолныйАнализСоставаТипов, Ложь,,,,,
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(5779)}:					ТаблицаТиповРодителя = ВычислитьТипЗначенияВыражения(РодительскийКонтекст, ТекстДляПоискаОпределения, ПредшествующийТекст, РазрешитьАнализИмениТипа,, ПолныйАнализСоставаТипов, Ложь,,,,,
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(8507)}:		ТаблицаТиповКонтекста = ВычислитьТипЗначенияВыражения(ПолноеИмяТаблицы);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(8488)}:		ОбновитьТаблицуПараметровВыбраннойТаблицы(мТекущаяСтрокаВыбранныеТаблицы);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(8467)}:	ЗагрузитьВыбраннуюТаблицу();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(3603)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1259)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1207)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(323)}:		Результат = Компонента.Нажатие(Кнопка);

**Comment by tormozit** [comment]
https://www.hostedredmine.com/issues/972557
