### ISSUE TITLE
Редактор объекта БД. Ссылки на объект. Ошибка формата потока

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#541]
https://github.com/tormozit/RDT1C/assets/87958986/949d4e01-98d1-4570-aea5-aa714dfd583c

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.53)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.99.1e
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.99.1e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл ссылку на элемент справочника Справочник.КлючиАналитикиУчетаПартий (ERP) в Редакторе Объекта БД
2. Перешел на вкладку "Ссылки на объект"
3. Выполнил поиск ссылок
4. В таблице результатов вижу записи с надписью "<Ключ записи регистра обрезан и не может быть восстановлен>" (это движения в не подчиненном регистратору регистре сведений РегистрСведений.ДетализацияСебестоимостиПартииТоваров)
5. При попытке открыть через Alt+F2 выдается ошибка:

```
Ошибка формата потока
{ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.МодульОбъекта(113)}:КлючОбъекта = ирОбщий.ОбъектБДПоКлючуЛкс(ТекущаяСтрока.Метаданные, ЗначениеИзСтрокиВнутр(ТекущаяСтрока.Данные));
{ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4827)}:ОбработкаОбъект.ОткрытьСсылающийсяОбъектВРедактореОбъектаБД(ТекущаяСтрока, ИскомаяСсылкаПоискаСсылокНаОбъект());

по причине:
Ошибка преобразования
по причине:
Ошибка формата потока
```

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/972855
В ближайшем будущем решения проблемы не планируется, т.к. она очень редкая и ее решение будет достаточно сложным.

**Comment by PerlAmutor** [comment]
Сама платформа генерирует такие ссылки на ключи записи регистров сведений не подчиненных регистратору. Может это как-то поможет придумать решение:

`e1cib/data/РегистрСведений.ДетализацияСебестоимостиПартииТоваров?Партия=%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%A1%D1%81%D1%8B%D0%BB%D0%BA%D0%B0.%D0%9F%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B0%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2%D0%9C%D0%B5%D0%B6%D0%B4%D1%83%D0%9E%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%D0%BC%D0%B8%3A8e500050568b35ac11e83d9747b55a68&АналитикаУчетаПартий=8e500050568b35ac11e83d9747b55a69&Организация=a7a9000d884fd00d11e4c1800d667f0c&ВидЗапасов=8e500050568b35ac11e801cb5a33ddce&Номенклатура=aee70015e9b8c48d11e01fecb9c33deb&Характеристика=00000000000000000000000000000000&ЗатратыПредыдущихПеределов=0&ПериодРегистрации=20220901000000&ДокументПоступления=%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%A1%D1%81%D1%8B%D0%BB%D0%BA%D0%B0.%D0%9F%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B0%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2%D0%9C%D0%B5%D0%B6%D0%B4%D1%83%D0%9E%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%D0%BC%D0%B8%3A8e500050568b35ac11e83d9747b55a68&АналитикаУчетаПартийДокументаПоступления=8e500050568b35ac11e83d9747b55a69&АналитикаУчетаНоменклатурыДокументаПоступления=92f10050568b35ac11e4ee5966a0e593&АналитикаУчетаНоменклатурыНЗП=00000000000000000000000000000000&ТипЗаписи=00000000000000000000000000000000`

**Comment by tormozit** [comment]
Проблема в типе реквизита табличной части - строка не может быть длиннее 1024 символов в составном типе.

**Comment by tormozit** [comment]
Исправлено в 7.02
