### ISSUE TITLE
Консоль запросов. Перейти к определению. Значение не является значением объектного типа (РолиПоля)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#542]
https://github.com/tormozit/RDT1C/assets/87958986/90aac69a-b1c7-4db5-9d04-4f4072ae9db2

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.53)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.99.1e
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.99.1e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открыл консоль запроса, ввел текст запроса:
```
ВЫБРАТЬ
	Т.Регистратор
ИЗ
	РегистрНакопления.ПрочиеРасходыНезавершенногоПроизводства КАК Т
ГДЕ
	Т.ОстаткиИОбороты.Этап

```
3. Установил курсор мышки на слово "ОстаткиИОбороты"
4. Нажал F12 (Перейти к определению)
5. Получил ошибку:

```
Значение не является значением объектного типа (РолиПоля)
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4358)}:Результат = ИмяТаблицы + "." + ФормаКолонки.РолиПоля + "." + мТекущееСлово;
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1293)}:ПерейтиКОпределению();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1209)}:Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(323)}:Результат = Компонента.Нажатие(Кнопка);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/973032

**Comment by tormozit** [comment]
Исправлено в 7.00
