### ISSUE TITLE
Ошибка при формировании отчета в консоли СКД

### ISSUE THREAD

**Issue by 9815444** [tormozit/RDT1C#543]
**Программное окружение**

Получить эту информацию можно кнопкой "Техническая информация" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1

Платформа: 8.3.23.1865
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP. Управление холдингом (3.1.12.4)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.99.1e
Инструменты разработчика. Инструмент: Консоль компоновок данных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.99.1e)
Расширения. Баимская_ERPУХ (1.0.0.1)
Расширения. Баимская_ЕРПУХ_Тест ()
Расширения. ИнструментыУФ_ЕРП_ИнтерфейсОтладки (1.0)
Расширения. РКС_ПатчИсправлениеОшибок (1.0.0.1)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2019 Datacenter 64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Active code page: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Linux x86-64
Сервер. Процесс: 64б

**Воспроизведение проблемы**
1. Открыл инструмент Консоль СКД
2. Нажал кнопку Сформировать
3. Получил окно с ошибкой 

Поле объекта не обнаружено (Поле)
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТабличногоДокумента.МодульОбъекта(269)}:ДоступноеПоле = ЭлементСтруктуры.ПоляГруппировки.ДоступныеПоляПолейГруппировок.НайтиПоле(ПолеГруппировки.Поле);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТабличногоДокумента.МодульОбъекта(282)}:МассивИзмеренийПотомков = ПолучитьМассивИзмеренийКолонокНастройкиКомпоновкиПоУровням(ЭлементСтруктуры.Колонки);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТабличногоДокумента.МодульОбъекта(135)}:КоллекцияИзмерений = ПолучитьМассивИзмеренийКолонокНастройкиКомпоновкиПоУровням(Источник.Структура);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(804)}:ПолеТабличногоДокументаСГруппировками.СформироватьМенюГруппировок(КомпоновщикНастроек.Настройки);
{(1)}:ЭтаФормаИлиОбработка.ВывестиРезультатЗавершение(, Результат)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(22320)}:Выполнить("ЭтаФормаИлиОбработка." + ОбработчикЗавершения + "(, Результат)");
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(739)}:Результат = ирОбщий.ВыполнитьЗаданиеФормыЛкс("ВывестиРезультат", ПараметрыЗадания, ЭтаФорма,,, ЭлементыФормы.КоманднаяПанельФормы.Кнопки.ВывестиВТаблицу, "ВывестиРезультатЗавершение",
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(645)}:Результат = СкомпоноватьРезультатМой(, СтруктураВнешниеНаборыДанных,, Истина, МенеджерВременныхТаблиц);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(1199)}:Если ВыполнитьОтчет() Тогда

**Comment by tormozit** [comment]
нужна схема с настройками компоновки в виде xml файла

**Comment by 9815444** [comment]
[схема.zip](https://github.com/tormozit/RDT1C/files/13225142/default.zip)

**Comment by 9815444** [comment]
ерпух

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/973014

**Comment by 9815444** [comment]
как можно быстро пофикситть до обновления?

**Comment by tormozit** [comment]
Исправлено в 7.00
