### ISSUE TITLE
Интерфейсная панель. ctrl-alt-g не всегда срабатывает

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#544]
**Программное окружение**
Платформа: 8.3.21.1775
Режим БД: клиент-серверный
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Расширение 6.98.3e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.98.3e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс
Сервер. ОС: Microsoft Windows Server 2016 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл Предприятие
2. нажимаю ctrl-alt-g. флаг перехват клавиатуры в настройках ир установлен
3. ничего не происходит
4. ctrl-alt-g начинает работать после открытия любой формы в предприятии 
5. первой интерфейсная панель не хочет открываться

**Ожидаемое поведение**
после открытия предприятия сразу попасть в интерфейсную панель через ctrl-alt-g а не мышкой

**Comment by tormozit** [comment]
Так сделано умышленно, чтобы ускорить старт сеанса обычного приложения и избежать нежелательных эффектов в некоторых старых конфигурациях под обычное приложение, где есть много форм с тяжелыми обработчиками внешних событий.
Мне кажется что не так уж и тяжело сначала открыть любую одну форму инструмента без клавиатуры.

**Comment by dmitri-0** [comment]
согласен, думал  это баг 
теперь понятно
спасибо
