### ISSUE TITLE
При запуске "От имени пользователю" окно запускаемого приложения ведет себя неадекватно

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#545]
**Программное окружение**

Платформа: 8.3.21.1709
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 6.99.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. МаркетКоннекторКА2 (1.0.2.2)
Расширения. ИнструментыРазработчикаTormozit (6.99.1e)
Расширения. YAXUNIT ()
Расширения. ЭР_Обмен_КА_БП (1.0.2.11)
Расширения. ИмяКомпании (1.1.1.9)
Расширения. испр_Автовычерки ()
Расширения. зг_ЗУП (1.0.2.2)
Расширения. ПатчРаспределениеУдержаний ()
Расширения. ОптимизионВыручки ()
Расширения. ПатчДоставка ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл запуск от имени пользователя
2. Запустил от пользователя со следующими параметрами:
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/0e4eb1a4-f189-4b1e-a1b7-e5e733784b5a)
3. После этого запускаемое приложение начинает вести себя странно:
Из расширенного на весь рабочий стол окна его нельзя перетаскиванием уменьшить. (Срабатывает только через Alt + Стрелка вниз)
У уменьшенного окна не меняются размеры.

https://github.com/tormozit/RDT1C/assets/16429518/413eb178-664b-4b48-a5f6-7f686a45c8a8

Просьба помочь понять. может ли дело быть в ИР (но без ИР такого не наблюдается)

**Ожидаемое поведение**
Отсутствие такого.

**Comment by tormozit** [comment]
Нужна техническая информация ИР и полная картинка окна при записке через ИР и при запуске без ИР

**Comment by tormozit** [comment]
Скорее всего без ИР ты запускаешь тонкий клиент и не сообщил об этом.
В платформе есть ошибка https://www.hostedredmine.com/issues/899263

**Comment by KovAlexey** [comment]
Полное видео.
Запускал толстый. Специально проверил
https://github.com/tormozit/RDT1C/assets/16429518/a2bcd498-240e-458d-b964-e18ca4f02b2f

**Comment by KovAlexey** [comment]
Информацию обновил

**Comment by tormozit** [comment]
Посмотрел твое новое видео и увидел много отличий в составе панелей главного окна при запуске через ИР и без него. Этим и объясняется разница в поведении главного окна. Сделай такой же состав панелей и не забудь про панель показателей производительности. И будет такая же проблема и без ИР. Смотри мою ссылку на ошибку платформы.

**Comment by KovAlexey** [comment]
>Посмотрел твое новое видео и увидел много отличий в составе панелей главного окна при запуске через ИР и без него. Этим и объясняется разница в поведении главного окна. Сделай такой же состав панелей и не забудь про панель показателей производительности. И будет такая же проблема и без ИР. Смотри мою ссылку на ошибку платформы.

Панели отличаются сейчас только из-за того. что я перед видео поубирал все разделы.
Про производительность посмотрю, полагаю ключевое как раз это

**Comment by KovAlexey** [comment]
Итак. Получилось повторить при обычном запуске
Но! Это зависело не от показа производительности или панелей
А именно от наличия всех ключей запуска.
Попробую выяснить какой именно

**Comment by KovAlexey** [comment]
Так, да. Ты прав был.
От панелей это и зависит. Видать я где-то проглядел что-то.
Заявку закрываю тогда, полагаю? Проблема платформенная.

**Comment by tormozit** [comment]
Да. У меня вопросов нет. Доработок я по этой проблеме делать не планирую.
