### ISSUE TITLE
Конструктор запросов ИР. Ошибка удаления поля на странице "Выбор полей"

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#546]
**Программное окружение**
Платформа: 8.3.22.2283
Режим БД: файловый
Конфигурация. Название: ИР расширение ()
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Расширение 7.00.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.00.1e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Нажал кнопку del для удаления поля (см скрин)
3. Получил окно с ошибкой 

```
Ошибка при вызове метода контекста (Удалить)
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(9376)}:		ЗапросПакета.ПоляОбъединения.Удалить(СтрокаПоляОбъединенияПоИмени);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(9537)}:			УдалитьВыбранноеПоле(СтрокаПоля, ЗапросПакета);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(9463)}:	УдалитьВыбранныеПоляСЗависимыми(Кандидаты, мТекущийЗапросПакета, Истина);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(3612)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1264)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1212)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(323)}:		Результат = Компонента.Нажатие(Кнопка);
по причине:
Несоответствие типов (параметр номер '2')

```

**Ожидаемое поведение**
Удаление поля

**Comment by dmitri-0** [comment]
скрин не получается приложить
поле называется null

**Comment by tormozit** [comment]
Нужна картинка или описание причины, по которой ее не удается приложить.
Еще желательно приложить текст запроса.

**Comment by dmitri-0** [comment]
Сергей, вставляю картинку из буфера в поле комментария
вот такой текст появляется 
![Uploading image.png…]()

но не загружается
приложить файл - такая же ситуация

ошибка появляется если через + добавить поле NULL
а потом попытаться его удалить

**Comment by tormozit** [comment]
Если не вставляется сама картинка, загрузи ее на любой другой сайт и вставь ссылку. Кстати ClipAngel это позволяет сделать одной командой.
Еще попробуй другим браузером и проверь включенные модификаторы страницы (например расширения браузера).

**Comment by dmitri-0** [comment]
https://i.imgur.com/5sixnyx.png

**Comment by dmitri-0** [comment]
![image](https://github.com/tormozit/RDT1C/assets/141411224/3e784d6c-f56a-4159-bbbd-0a2299700f92)

**Comment by dmitri-0** [comment]
https://github.com/tormozit/RDT1C/assets/141411224/916e916c-ddb0-4f4b-ad45-bd48f5744546

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/973717

**Comment by tormozit** [comment]
Исправлено в 7.01.2
