### ISSUE TITLE
Исследователь объектов. Ошибка при вызове метода контекста при просмотре ДанныеКоллекцииФормы

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#548]
**Программное окружение**
Платформа: 8.3.21.1709
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.01.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. МаркетКоннекторКА2 (1.0.2.2)
Расширения. ИнструментыРазработчикаTormozit (7.01.1e)
Расширения. ОптимизионВыручки ()
Расширения. YAXUNIT ()
Расширения. ЭР_Обмен_КА_БП (1.0.2.11)
Расширения. зг_ЗУП (1.0.2.2)
Расширения. Зооград (1.1.1.9)
Расширения. испр_Автовычерки ()
Расширения. ПатчРаспределениеУдержаний ()
Расширения. ПатчДоставка ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл форму, которая содержит табличную часть с колонками:
Ссылка - СправочникСсылка.Номенклатура
Ссылка_Найден - Булево
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/248aaedc-8bda-4234-a565-bdd8e0069412)
2. Открыл Структуру формы
3. Выбрал ФормуКлиентскогоПриложения и передал в исследователь объектов
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/e4179359-34ad-4b4b-8d6f-1ec5bb9273dd)
4. Открылась копия, пытаюсь открыть нужную мне таблицу, получаю ошибку.
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/0ee13a0f-b211-4130-b35e-f87c8180cddf)
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/20a48692-a93a-4cf9-8464-3c962570396d)
```
Ошибка при вызове метода контекста (ЗаписатьXML)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(16863)}:Сериализатор.ЗаписатьXML(Поток, Объект);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(7147)}:ДокументДОМ = ирОбщий.ТекстВДокументDOMЛкс(ирОбщий.ОбъектВСтрокуXMLЛкс(ДанныеФормы));
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(2607)}:СтруктураИмен = ДочерниеСвойстваДанныхФормы(МетаданныеРодителя, ЛиКоллекция, Форма, Слово);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(5586)}:СловаКонтекстаМетаданные(СтруктураТипа, Слово, ТипСлова,, ЯзыкПрограммы,, ВнешниеФункцииКомпоновкиДанных, ВычислятьТипы, ФлагиКомпиляции,
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(8828)}:ВнутренняяТаблицаСлов = мПлатформа.ТаблицаСловИзСтруктурыТипа(СтруктураТипаЭлементаКоллекции);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(8669)}:ДобавитьТипЭлементаВТаблицуКоллекции(ТаблицаКоллекции, СвойстваЭлементовКоллекции, ИмяКолонкиИндекс, выхОписанияКолонок, лСтруктураТипаЭлементаКоллекции);
{ИнструментыРазработчикаTormozit Обработка.ирИсследовательОбъектов.Форма.ИсследовательКоллекций.Форма(64)}:ирОбщий.ТаблицаЗначенийИзКоллекцииЛкс(Коллекция, СтруктураТипаКоллекции, ТаблицаКоллекции, ОписанияКолонок, СтруктураТипаЭлементаКоллекции,, Истина,,,,, СписокТиповОбнаруженныхЭлементов);
{ИнструментыРазработчикаTormozit Обработка.ирИсследовательОбъектов.Форма.ИсследовательКоллекций.Форма(120)}:ОбновитьДанные();
{ИнструментыРазработчикаTormozit Обработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(754)}:Форма.Открыть();
{ИнструментыРазработчикаTormozit Обработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(525)}:ОткрытьТекущийЭлемент(Колонка = Элемент.Колонки.КоличествоЭлементов, СтандартнаяОбработка);

по причине:
Несоответствие типов (параметр номер '2') (Ошибка отображения типов)
```
Падает на следующих данных:
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/111f0409-c161-4416-9c74-413479fa93fb)

**Ожидаемое поведение**
Отсутствие ошибок, показ коллекции

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/973739

**Comment by tormozit** [comment]
Исправлено в 7.01.2
