### ISSUE TITLE
Форма настроек. Ошибка при двойном открытии из разных мест

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#55]
https://user-images.githubusercontent.com/87958986/133018757-b54a8111-144f-450c-9649-8188a7311183.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.1p
> Инструменты разработчика. Инструмент: Обработка.ирПортативный.Форма.ФормаНастроек
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При открытой Формы Настроек из инструмента "Функции Режима Отладки", невозможно повторно открыть эту форму из глобальной панели ИР.

```
Ошибка при вызове метода контекста (ОткрытьМодально)
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(267)}:		РезультатФормы = ФормаНастроек.ОткрытьМодально();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(252)}:		ОткрытьФормуНастроек();
по причине:
Невозможно открыть форму в модальном режиме, так как она уже открыта!

```

**Comment by tormozit** [comment]
Так вроде программа правильно ругается. Чего ты ожидал?

**Comment by tormozit** [comment]
Создал близкую задачу https://www.hostedredmine.com/issues/933158 . Возможно в рамках нее что то улучшу здесь.

**Comment by tormozit** [comment]
Исправлено в 6.10.1
