### ISSUE TITLE
Сравнение объектов. Ошибка вставки объекта из буфера

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#550]
<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.00.1e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.00.1e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details> 

**Воспроизведение проблемы**
1. Открыл инструмент Сравнение объектов
2. Нажал кнопку вставить из буфера
3. Получил окно с ошибкой 

```1c-enterprise
Индекс находится за границами массива
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.СравнениеОбъектов.Форма(477)}:	Возврат Ложь
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.СравнениеОбъектов.Форма(469)}:	Если ЛиОбъектСовместим(НовыйОбъект) Тогда
{ИнструментыРазработчикаTormozit Обработка.ирПортативный.Форма.Форма.Форма(192)}:		РезультатФормы = ФормаНастроек.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Обработка.ирПортативный.Форма.Форма.Форма(171)}:		ОткрытьФормуНастроек();
``` 

https://github.com/tormozit/RDT1C/assets/141411224/a2b796d0-b92b-4bd0-b14d-336075aafd0b

**Ожидаемое поведение**
Сравнение объектов

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/973799

**Comment by tormozit** [comment]
Исправлено в 7.01.2
