### ISSUE TITLE
Консоль кода. Ошибка добавления параметра.

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#551]
<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.01.1e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.00.1e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details> 

**Воспроизведение проблемы**

https://github.com/tormozit/RDT1C/assets/141411224/db667306-7cf4-4bb7-9f86-42ecfa932de1

**Ошибка**
```1c-enterprise
Ошибка при установке значения атрибута контекста (ТекущаяКолонка)
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.СписокЗначений.Форма(136)}:			ЭлементыФормы.Таблица.ТекущаяКолонка = КолонкиТП.Представление;
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(5498)}:		Результат = ФормаРедактирования.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.ВыборРедактируемыхТипов.Форма(701)}:	РезультатВыбора = ирКлиент.ВыбратьЭлементСпискаЗначенийЛкс(СписокВыбора, НачальныйВыбор, Истина, "Выберите набор типов");
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(9774)}:		РезультатВыбора = ФормаРедактора.ОткрытьМодально();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(5773)}:		НовыйТипИлиЗначение = ВыбратьРедактируемыйТипЛкс(ОграничениеТипа,,,,, Заголовок);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(1473)}:	Если ирКлиент.ПолеВводаКолонкиРасширенногоЗначения_НачалоВыбораЛкс(ЭтаФорма, ЭлементыФормы.Параметры, СтандартнаяОбработка, ЭлементыФормы.Параметры.ТекущаяСтрока.Значение,,,,,
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(2888)}:	ПараметрыПредставлениеЗначенияНачалоВыбора(ЭлементыФормы.Параметры.Колонки.ПредставлениеЗначения.ЭлементУправления, Истина);
по причине:
Невозможно активизировать колонку

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/974477

**Comment by tormozit** [comment]
Исправлено в 7.01.2
