### ISSUE TITLE
Консоль кода. Ошибка получения свойства динамического списка.

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#552]
<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.01.1e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.00.1e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details> 

**Воспроизведение проблемы**

https://github.com/tormozit/RDT1C/assets/141411224/1314c70a-e8c4-4a17-ae54-a8f2e283064e

**Ошибка**
```1c-enterprise
Редактор встроенный: Строка кода 3: Поле объекта не обнаружено (ОсновнаяТаблица)
```

**Comment by tormozit** [comment]
Конфигуратор точно также показывает наличие этого свойства на клиенте, но выполнение такого кода вызовет ту же ошибку. Опять же читай внимательнее синтакс-помощник. Свойство недоступно на клиенте.

**Comment by dmitri-0** [comment]
я переключил контекст в консоли кода на Серверный
выполнил этот же код
но получил сообщение что 
```1c-enterprise
Параметр "Форма" на выходе имел мутабельное значение (Форма клиентского приложения) и был очищен
``` 
как мне выполнить этот код?
