### ISSUE TITLE
Консоль кода. Отсутствует метод РеквизитФормыВЗначение()

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#553]
**Воспроизведение проблемы**

https://github.com/tormozit/RDT1C/assets/141411224/78a8d6a7-0d69-4c89-8033-6d0eb7a03d60

**Ошибка**
```1c-enterprise
Редактор встроенный: Строка кода 2: {(2,10)}: Процедура или функция с указанным именем не определена (РеквизитФормыВЗначение)

``` 
При этом метод ДанныеФормыВЗначение() есть.

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.01.1e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.01.1e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details>

**Comment by tormozit** [comment]
Ты бы хоть сначала синтакс помощник почитал. Установи каретку на имя метода и нажми CTRL+F1. Такого метода в глобальном контексте нет. Поэтому и подсказка в консоли кода его не показывает.

**Comment by dmitri-0** [comment]
а почему этот метод отсутствует в глобальном контексте в консоли кода?
ты же говорил что у тебя есть этот метод в консоли кода а у меня нет?
как мне его добавить в мою консоль?

**Comment by dmitri-0** [comment]
я его нашел
он находится в контексте ФормаКлиентскогоПриложения
