### ISSUE TITLE
Консоль кода. Разное поведение метода ПолучитьФорму() в режиме модуля и вне.

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#554]
**Воспроизведение проблемы**

https://github.com/tormozit/RDT1C/assets/141411224/f65852f9-d348-43d8-b202-ef12ab8ab664

**Ошибка**
```1c-enterprise
Редактор встроенный: Строка кода 2: {(2,67)}: Слишком много фактических параметров (ПолучитьФорму)
``` 

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.01.3e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.01.1e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details>

**Comment by tormozit** [comment]
Такое поведение является особенностью. Объясняется это тем, что модуль помещается во внешнюю обработку, у которой есть собственный метод ПолучитьФорму, вытесняющий одноименный метод глобального контекста.
В качестве способа обхода этой особенности можно использовать метод ирКлиент.ПолучитьФормуЛкс()

**Comment by dmitri-0** [comment]
спасибо за оперативный ответ.

**Comment by tormozit** [comment]
Добавлю команду для облегчения обнаружения этого пути обхода https://www.hostedredmine.com/issues/976242

**Comment by tormozit** [comment]
Добавлено в 7.04
