### ISSUE TITLE
Консоль кода. Выделить метод > ошибка

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#555]
**Воспроизведение проблемы**

https://github.com/tormozit/RDT1C/assets/141411224/5fc0b883-575d-472f-a28b-5c3bc6b60186

**Ошибка**
```1c-enterprise
Итератор для значения не определен
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(20065)}:	Для каждого Э Из Коллекция Цикл
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2005)}:	ВыходныеПараметрыМатеринскогоМетода = ирОбщий.ВыгрузитьСвойствоЛкс(мПлатформа.ПараметрыМетодаМодуля(мМетодМодуля),, Новый Структура("Знач", Ложь));
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(2810)}:	Если ПолеТекстаАлгоритма.ВыделитьМетод(Параметры, ирОбщий.ИдентификаторИзПредставленияЛкс(мТекущаяСтрокаДереваАлгоритмов.Наименование)) <> Истина Тогда 

``` 

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.01.1e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.03.1e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details>

**Comment by dmitri-0** [comment]
![image](https://github.com/tormozit/RDT1C/assets/141411224/48e26172-5207-4d78-861e-02b2d323b17e)

**Comment by dmitri-0** [comment]
в 7.02.2е выделение метода работает

![image](https://github.com/tormozit/RDT1C/assets/141411224/cb017cb5-2c61-4766-afd8-a369a7f590e3)

**Comment by dmitri-0** [comment]
ошибка в посл версии ИР воспроизводится с любым кодом при попытке выделить метод

**Comment by tormozit** [comment]
У меня нет твоего текста для проверки твоего сценария. На моих текстах ошибка не воспроизводится.

**Comment by dmitri-0** [comment]
текст алгоритма

```1c-enterprise
Функция Главный()
Форма = п1.ПолучитьФорму("ФормаДокумента");

М = Новый Массив;
Для Каждого Эл Из Форма.Реквизит1 Цикл
	Если Эл.Реквизит1 = "1" Тогда
		М.Добавить(Эл.Реквизит2);	
	КонецЕсли;
КонецЦикла;      


КонецФункции


``` 


выгрузка базы
[1Cv8 тестовая ИР.zip](https://github.com/tormozit/RDT1C/files/13613870/1Cv8.zip)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/976450

**Comment by tormozit** [comment]
Исправлено в 7.04
