### ISSUE TITLE
Консоль кода > Общие методы > ошибка

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#556]
**Воспроизведение проблемы**
Открыл консоль кода
Нажал Общие методы

**Ошибка**
```1c-enterprise
Индекс находится за границами массива
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(4887)}:								Модуль = ПодготовитьМодульМетаданных(ТаблицаТиповМодуля[0]);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.МетодыМодулей.Форма(193)}:			ПараметрыМетода = мПлатформа.ПараметрыМетодаМодуля(МетодМодуля, БылиИзмененияКэшаМодуля);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.МетодыМодулей.Форма(135)}:				ДобавитьМетодыМодуля(СтруктураТипа, МетаТип,, ФайлыРасширений);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.Форма.МетодыМодулей.Форма(61)}:	ПерезаполнитьТаблицуВсехМетодов();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(8735)}:	ФормаВыбора.Открыть();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1239)}:			ОткрытьСписокМетодов();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1216)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(80)}:	ПолеТекстаАлгоритма.Нажатие(Кнопка, Ложь);

``` 

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.01.1e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.02.2e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details>

**Comment by dmitri-0** [comment]
обновил ИР через Загрузить конфигурацию из файла. 
самовылечилось

**Comment by tormozit** [comment]
Это ошибка исправлена в актуальной версии
