### ISSUE TITLE
Консоль запросов. ADO. HEX строка не отображается.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#557]
https://github.com/tormozit/RDT1C/assets/87958986/7958480e-c2cf-4bab-8705-080b65c5bbc6

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.443)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.03.2e
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.03.2e)
Расширения. Понижайка ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

</details>

**Воспроизведение проблемы**
1. Выполнил запрос к SQL серверу через ADO в инструменте Консоль Запросов
2. В полях результата запроса вместо HEX строки (0x83F1DFBC0F9738F511EB80B35C63959E) вижу массив чисел
3. Переключение флажка "Бинарные преобразовывать в строку" на вкладке ADO ничего не меняет

**Ожидаемое поведение**
Хотелось получить идентификатор ссылки вида 0x83F1DFBC0F9738F511EB80B35C63959E вместо массива.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/976479

**Comment by tormozit** [comment]
Исправлено в 7.04
