### ISSUE TITLE
Редактор объекта БД. Не открываются ключи регистра сведений в поиске ссылок.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#558]
https://github.com/tormozit/RDT1C/assets/87958986/5eb1ea12-b18d-4327-b8a0-d978349d88bf

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.443)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.03.2e
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.03.2e)
Расширения. Расширение1 ()
Расширения. Понижайка ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

</details>

**Воспроизведение проблемы**
1. Открыл ссылку на объект в Редактор Объекта БД
2. Выполнил поиск ссылок
3. В таблице с результатом поиска встал на строку с ключом регистра сведений и нажал Alt+F2
4. Получил ошибку:

```
Несоответствие типов (параметр номер '1')
{ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.МодульОбъекта(113)}:КлючОбъекта = ирОбщий.ОбъектБДПоКлючуЛкс(ТекущаяСтрока.Метаданные, ЗначениеИзСтрокиВнутр(ТекущаяСтрока.Данные));
{ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4827)}:ОбработкаОбъект.ОткрытьСсылающийсяОбъектВРедактореОбъектаБД(ТекущаяСтрока, ИскомаяСсылкаПоискаСсылокНаОбъект());

по причине:
Несоответствие типов (параметр номер '1')
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/976480

**Comment by tormozit** [comment]
Исправлено в 7.04
