### ISSUE TITLE
Консоль запросов. Различные иконки сортировки для команд с однотипными действиями

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#559]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.20.1996
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.443)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.03.2e
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.03.2e)
Расширения. Расширение1 ()
Расширения. Понижайка ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

</details>

![image](https://github.com/tormozit/RDT1C/assets/87958986/2203de0f-30cd-42e8-b9e4-5046a5d0c39e)

**Воспроизведение проблемы**
Не придерживается стиль иконок для команд с однотипными действиями. В частности иконки на командах сортировки в командной панели результата запроса консоли запросов отличаются от общепринятых в целом в ИР. Проблема наблюдается только в поставке вида "Расширение".

**Comment by tormozit** [comment]
Частично тут проблема в платформе, т.к. это частично системные картинки. Они выглядят по-разному в обычной форме в режиме совместимости и без него и управляемой форме. Причем таких картинок немало. Переводить все кнопки на собственные картинки кажется большого смысла нет особенно с учетом легкой узнаваемости смысла по самой картинке. В некоторых формах инструментов кнопкам безальтернативно назначены прикладные, а в некоторых - системные картинки с тем же смыслом.
