### ISSUE TITLE
Редактор Объекта БД. Вести историю. Падает платформа.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#56]
https://user-images.githubusercontent.com/87958986/133020507-b8db57af-b448-4129-9b04-046ac61ab46b.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Падает платформа при вызове команды "Вести историю" в обработке Редактор Объекта БД.

**Comment by tormozit** [comment]
У меня такого не наблюдается. Пробовал в разных базах и версиях платформы. 
Проблема только с одной таблицей данных? Если да, то покажи настройки ведения истории через инструмент "История данных".
Еще в каких то базах такое наблюдается?
Прошагай процедуру ирОбщий.УстановитьИспользованиеИсторииДанныхЛкс() отладчиком. На какой строке кода происходит аварийное завершение?

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/933159

**Comment by tormozit** [comment]
Исправлено в 6.10.1
