### ISSUE TITLE
Конвертор текста БД. Планы запросов. Строка внутри строки в аргументе xml

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#560]
**Программное окружение**

Платформа: 8.3.21.1624
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.02.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. испр_цислинк_ ()
Расширения. УправлениеПрофилем ()
Расширения. Оптимизации ()
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Datacenter 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент конвертор текста БД
2. Вставил следующий кусок плана запроса:

`<ScalarOperator ScalarString="[ka2].[dbo].[_Document1181].[_Number] as [T1].[_Number] like [@P284] escape N'/' ">
`
3. В результате получил нечитаемый для парсера xml аргумент:
`
<ScalarOperator ScalarString="[ka2].[dbo].[Документ.ПриходныйКассовыйОрдер].[Номер] as [T1].[Номер] like [@P284] escape "/" ">
`
Проблема в кавычках, которые вместо того, чтоб быть вложенными, в данном случае закрывают аргмент

**Ожидаемое поведение**
Ожидалось
`
<ScalarOperator ScalarString="[ka2].[dbo].[Документ.ПриходныйКассовыйОрдер].[Номер] as [T1].[Номер] like [@P284] escape '/' ">
`

Или же для более универсального решения лучше, наверно, так:
`<ScalarOperator ScalarString="[ka2].[dbo].[Документ.ПриходныйКассовыйОрдер].[Номер] as [T1].[Номер] like [@P284] escape &quot;/&quot; ">`

Этот вариант тоже отлично читается парсерами

**Comment by tormozit** [comment]
нужна картинка с настройками конвертации

**Comment by KovAlexey** [comment]
Только "Перевод в мета"
Ну естественно изначально это полноценный план
Я выделил только некорректный тег
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/24bcc7a6-36c1-496e-b6a6-a374d1c003e7)

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/977197

**Comment by tormozit** [comment]
Сделано в 7.06
