### ISSUE TITLE
Доработка консоли HTTP запросов - доступность тела запроса для метода GET

### ISSUE THREAD

**Issue by VZhulanov1** [tormozit/RDT1C#561]
Ошибки никакой нет, но есть потребность передавать тело запроса при методе GET
Это не запрещено и есть реальные запросы, в которых это требуется для отладки.
API на сервере не мое, переписать не могу и в него надо отправлять данные в теле запроса.

А в ИР версии 7.02.1 тело запроса недоступно для GET

**Comment by tormozit** [comment]
Нужен публичный сервис для теста.

**Comment by VZhulanov1** [comment]
попробую сделать на своем сервере
в ответе могу отправлять полученное тело запроса

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/995820

**Comment by tormozit** [comment]
Сделано в 7.52
