### ISSUE TITLE
Функция для отладки От() -> ошибка

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#563]
**Воспроизведение проблемы**

https://github.com/tormozit/RDT1C/assets/141411224/0f42b932-710a-41a8-92a8-9844eca1ceae

Выгрузка базы
https://disk.yandex.ru/d/Qr5CZ4FbX4IGCw

**Ошибка**
```1c-enterprise
Итератор для значения не определен
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(2995)}:			Для Каждого ЭлементКоллекции Из КоллекцияЗначений Цикл
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(5845)}:	СловаКонтекстаМетаданные(СтруктураТипа, Слово, ТипСлова,, ЯзыкПрограммы,, ВнешниеФункцииКомпоновкиДанных, ВычислятьТипы, ФлагиКомпиляции, 
{ИнструментыРазработчикаTormozit Обработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(392)}:	ВнутренняяТаблицаСлов = мПлатформа.ТаблицаСловИзСтруктурыТипа(СтрокаДерева.СтруктураТипа);
{ИнструментыРазработчикаTormozit Обработка.ирИсследовательОбъектов.Форма.ИсследовательОбъектов.Форма(377)}:	ЗаполнитьДочерниеСтроки(СтрокаДерева);
{ИнструментыРазработчикаTormozit Обработка.ирИсследовательОбъектов.МодульОбъекта(32)}:		Результат = ФормаИсследователя.ОткрытьМодально();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(891)}:			Результат = ИсследовательОбъектов.ИсследоватьОбъект(Объект, Модально, ТекущееВыражение, ИмяТекущегоСвойства, ПрикрепитьОкно, ВладелецФормы);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(1016)}:	Результат = ИсследоватьЛкс(Объект, Истина, КакКоллекцию, ОтложенноеВыполнение);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(621)}:				Ис(Объект,, ОтложенноеВыполнение);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(849)}:	Результат = ОтладитьЛкс(Объект, Истина, Объект2, ВнешниеНаборыДанных, ОтложенноеВыполнение, ПорогОбрезкиВременнойТаблицы,, Наименование, МенеджерВременныхТаблиц);
{(1)}:ИрОбщий.От(ДокументРезультат)

``` 

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.05.2e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.05.2e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details>

**Comment by tormozit** [comment]
Сохрани и приложи файл табличного документа

**Comment by tormozit** [comment]
ошибку воспроизвел https://www.hostedredmine.com/issues/977589

**Comment by tormozit** [comment]
Исправлено в 7.06.3
