### ISSUE TITLE
Ошибка очистки ИсторииДанных по метаданным

### ISSUE THREAD

**Issue by 240596448** [tormozit/RDT1C#564]
"Метод объекта не обнаружен" 
[единственное упоминание здесь](https://github.com/tormozit/RDT1C/blob/master/src/DataProcessors/ирИсторияДанных/Forms/Форма/Ext/Form/Module.bsl#L575)

Требуется заменить
`ИсторияДанныхМоя = ирОбщий.ИсторияДанныхМоя();`
на
`ИсторияДанныхМоя = ирОбщий.ИсторияДанныхЛкс();`

Версия расширения `7.07.1`

**Comment by tormozit** [comment]
Нужен полный текст ошибки и картинка.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/977683

**Comment by 240596448** [comment]
> Нужен полный текст ошибки и картинка.

Да, сорри. Отвлекся на оливье, не встравил.

**Comment by tormozit** [comment]
исправлено в 7.08
