### ISSUE TITLE
Консоль запросов. ADO. Режет последние символы пароля в параметрах СУБД если он длинный

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#565]
**Воспроизведение проблемы**

https://github.com/tormozit/RDT1C/assets/141411224/4fb01b1f-814e-44c6-b543-d1a06488639e

**Ошибка**
```1c-enterprise
Ошибки при подключении к источнику данных ADO:
1) Ошибка инициализации подключения:
	{ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.МодульОбъекта(787)}: Ошибка при вызове метода контекста (Open): Произошла исключительная ситуация (Microsoft OLE DB Provider for SQL Server): [DBNETLIB][ConnectionOpen (Connect()).]SQL Server не существует, или доступ запрещен.
Фактическая строка соединения с базой:
	Provider=SQLOLEDB; Data Source="srv-x.x.xxxxx"; Initial Catalog="AAAAACO_1225_AAAAAAAAAAAA_1"; User Id="AAAAACO_1225_AAAAAAAAAAAA_1"; Password="AAAAACO_1225_AAAAAAAAAAAA";


``` 

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.05.2e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.09.2e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details>

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/978217

**Comment by tormozit** [comment]
Сделано в 7.10
