### ISSUE TITLE
Управление итогами регистров. Невозможно открыть из-за таймаута

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#566]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.23.1997
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.09.1p
Инструменты разработчика. Инструмент: Управление итогами регистров
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

![image](https://github.com/tormozit/RDT1C/assets/87958986/4733eec9-60c9-405a-8ca6-4c4932ea2996)

**Воспроизведение проблемы**
1. При установленном флажке "Показывать структуру хранения" в инструменте "Управление итогами регистров" возникает ситуация с невозможностью открыть данный инструмент, если в базе находится большая таблица Итогов
2. Возникает ошибка таймаута запроса ADO, т.к. запрос выполняется дольше 300 секунд
3. Необходимо настройку таймаута вынести в интерфейс или увеличить в этом участке модуля объекта обработки ирКонсольЗапросов.epf:

![image](https://github.com/tormozit/RDT1C/assets/87958986/1fd8932c-33a8-41c1-bd4f-8a25363848a8)

4. Сделать защиту инструмента от возникшего исключения, чтобы он открывался даже при возникшем исключении

**Comment by tormozit** [comment]
нужен текст проблемного запроса и полный текст (стек) ошибки

**Comment by tormozit** [comment]
Создал задачу на обход проблемы https://www.hostedredmine.com/issues/978612

**Comment by tormozit** [comment]
Обход проблемы открытия инструмента сделан в 7.10
