### ISSUE TITLE
Редактор объекта БД. Для битых ссылок не генерируется навигационная ссылка.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#567]
https://github.com/tormozit/RDT1C/assets/87958986/58064ae4-d073-4fde-bd1b-367e457964a0

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.23.1997
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.28)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.09.1p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Открываю битую ссылку на элемент справочника Валюты: 
`e1cib/data/Справочник.Валюты?ref=84a66c71d914a43d11edcbf5be869b30`
в инструменте Редактор Объекта БД
3. Вижу, что навигационная ссылка генерируется пустой, но при переключении флажка "Внешняя ссылка" ситуация исправляется

**Ожидаемое поведение**
Сразу отображение навигационной ссылки с нужным идентификатором

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/978611

**Comment by tormozit** [comment]
Исправлено в 7.10
