### ISSUE TITLE
Редактор хранилищ настроек. Значение не является значением объектного типа (init)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#568]
https://github.com/tormozit/RDT1C/assets/87958986/36f821bc-9b6a-438a-b27a-c1f2b74b110f

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.23.2040
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.10.1p
Инструменты разработчика. Инструмент: Редактор хранилищ настроек
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Если в инструменте "Редактор хранилищ настроек" два раза кликнуть на ячейку поля "Тип Настройки", то открывается форма в которой возникает ошибка:

`Значение не является значением объектного типа (init)
{ВнешняяОбработка.ирПлатформа.Форма.Текст.Форма(649)}:	РедакторHTML.init("1"); // Версия1С
`

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/978912

**Comment by tormozit** [comment]
Исправлено в 7.11
