### ISSUE TITLE
Ошибка в консоле кода при вызове подсказки (индекс находится за границами массива)

### ISSUE THREAD

**Issue by JohnyDeath** [tormozit/RDT1C#569]
Открываем консоль кода, вставляем следующий код:

```bsl
валюта = Справочники.Валюты.НайтиПоКоду(123);
ОбщегоНазначения.ЗначениеРеквизитаОбъекта(валюта, "на
```
после "на" вызываем подсказку по ктрл+пробел. Получаем ошибку:

> Индекс находится за границами массива
> {ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(9860)}:СтруктураТипаСсылки = ВычислитьТипЗначенияВыражения(мПервыйФактическийПараметр, мТекстДляПоискаОпределения)[0];
> {ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(8919)}:КоллекцияЭлементовМД = ЗаполнитьТаблицуСловДляТекстовогоЛитерала(ВыбраннаяСтруктураТипа, КонтекстТекстовогоЛитералаИзвестен);
> {ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(8680)}:Успешно = ЗаполнитьТаблицуСлов(ТаблицаТиповКонтекста,,, Модально,, Не ЗначениеЗаполнено(КодКлавиши));
> {ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1292)}:ОткрытьАвтодополнение(КодКлавиши, Не ЗначениеЗаполнено(КодКлавиши));
> {ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1270)}:Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(81)}:ПолеТекстаАлгоритма.Нажатие(Кнопка, Ложь);
> 
> [ОшибкаВоВремяВыполненияВстроенногоЯзыка, ОшибкаИспользованияВстроенногоЯзыка]

Также не срабатывает (но и нет ошибки) подсказка, если написать "валюта."
![image](https://github.com/tormozit/RDT1C/assets/5936030/8fd0d2ec-162c-4f09-a58a-b210ab749de3)

Тех информация:
> Платформа: 8.3.24.1342
> Режим БД: файловый
> Конфигурация. Название: Бухгалтерия предприятия КОРП, редакция 3.0. БитФинанс (3.0.145.19/3.1.58.7)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_21
> Конфигурация. Режим использования синхронных вызовов: Использовать
> Конфигурация. Версия БСП: 301
> Конфигурация. Использовать обычные формы в управляемом приложении: Да
> Инструменты разработчика. Версия: Расширение 7.11.2e
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Асинхронность запрещена: Нет
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (7.11.2e)
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. Отладка разрешена: Да
> Клиент. Постоянный кэш метаданных: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС выполнение BAT: Да
> Клиент. ОС Текущая кодовая страница: 866

**Comment by tormozit** [comment]
Нужна информация о кэше модулей. Также покажи реакцию программы на CTRL+Space после точки от имени общего модуля и на CTRL+SHIFT+Space в позиции параметра вызова метода.

**Comment by tormozit** [comment]
>если написать "валюта."

Старайся всегда приводить текст программы, в котором пробуешь автодополнение. Я его буду просто копировать и вставлять. Это упрощает мне воспроизведение и снижает внесения искажений.

**Comment by tormozit** [comment]
> не срабатывает (но и нет ошибки) подсказка, если написать "валюта."

Нужно видео с полным отображением окна консоли кода, начиная с запуска клиентского приложения, желательно с открытием готового текста (без редактирования).

**Comment by tormozit** [comment]
Неуверенно воспроизвел https://www.hostedredmine.com/issues/979006

**Comment by tormozit** [comment]
Проблема похоже возникает только за последним методом модуля. Очень желательно бы найти способ ее воспроизведения начиная с открытия окна консоли кода.
Предположительно исправленная версия https://www.hostedredmine.com/attachments/download/1170659/%D0%98%D0%A0%207.11.3e.cfe

**Comment by JohnyDeath** [comment]
> Нужна информация о кэше модулей. 

Обновлял вчера вечером вместе с тобой в рамках Адаптера (это база-донор)
![image](https://github.com/tormozit/RDT1C/assets/5936030/0c5ae0a0-d636-4999-8a0f-83e724bc5a8f)

> Также покажи реакцию программы на CTRL+Space после точки от имени общего модуля

тут всё хорошо:
![image](https://github.com/tormozit/RDT1C/assets/5936030/a7ac0bfc-6668-4bbb-9c94-9c73b9b7b13f)

>  и на CTRL+SHIFT+Space в позиции параметра вызова метода.

похоже ИР подрубил параметры от другого метода:
![image](https://github.com/tormozit/RDT1C/assets/5936030/2ddae869-8d08-4871-be8d-747b518e96cd)

**Comment by tormozit** [comment]
Предположительно исправлено в 7.11.3 (файл опубликован тот же)

**Comment by JohnyDeath** [comment]
Тут еще один момент с кэшем всплыл.

Я закрыл базу донора из адаптера, запустил её руками как обычную базу.
Запустил консоль кода и там вообще всё перестало работать в плане подсказок по модулям.
Пошел посмотреть что там с кэшем, а мне показывает, что он пустой и как будто ни разу не создавался.
Каталог, на который сейчас ссылается ИР как на хранилище кэша отличается от вчерашнего в одно последнее подчеркивание в каталоге предпоследнего уровня.
Кэш модулей хранится здесь:

> C:\Users\МартыненковЕВ\AppData\Local\1C\1cv8\File__d__BASE_ИмяБазы___\КэшМодулей

а сейчас показывает сюда:

> C:\Users\МартыненковЕВ\AppData\Local\1C\1cv8\File__d__BASE_ИмяБазы__\КэшМодулей

Разница в одном подчеркивании предпоследнего каталога "File__d__BASE_ИмяБазы__"
![image](https://github.com/tormozit/RDT1C/assets/5936030/ae217fde-5b75-4f24-833a-e8f46b9e0a79)

* на версии 7.11.2

**Comment by JohnyDeath** [comment]
Обновился на версию 7.11.3.
Попутно обновил и кэш. Ничего не изменилось
![image](https://github.com/tormozit/RDT1C/assets/5936030/d2514e00-418d-4987-8de6-0b2fd40111fb)
![image](https://github.com/tormozit/RDT1C/assets/5936030/e5436cbd-038d-472e-a07a-cea1d50da1f0)

но в этот раз стартануло с "правильным" каталогом, который я задал руками, когда увидел в прошлый раз, что подставился новый

**Comment by tormozit** [comment]
Ты описал уже как минимум 3 разные проблемы в одной заявке и к сожалению без способа воспроизведения. Я предположительно исправил только одну - "не срабатывает (но и нет ошибки) подсказка, если написать "валюта.""

**Comment by JohnyDeath** [comment]
Да, проблема с "валюта."" на 11.3 ушла.
про подсказку отдельной задачей оформлять?

**Comment by tormozit** [comment]
> Тут еще один момент с кэшем всплыл.

Кажется это явно нужно в отдельную заявку выносить и возможно даже по адаптеру.

**Comment by tormozit** [comment]
Первая ошибка "Индекс находится за границами массива" возникает только в случае когда анализатор не смог вычислить тип значения первого параметра метода. До последнего исправления ИР он у тебя не вычислялся из-за ошибки в ИР. Поэтому кажется и первая ошибка должна была уйти вместе с этим исправлением. Если она осталась, то покажи какой тип рассчитал анализатор для первого параметра.

**Comment by JohnyDeath** [comment]
Ошибка  "Индекс находится за границами массива" также ушла после обновления.
Спасибо
