### ISSUE TITLE
Анализ техножурнала. Принудительное завершение

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#57]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.1p
> Инструменты разработчика. Инструмент: Анализ техножурнала
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Когда система **принудительно** выгоняет пользователей, то в некоторых случаях возникает ошибка при завершении работы системы, если открыт Анализ техножурнала.

```
Значение не является значением объектного типа (НомерРежимаСовместимостиЛкс)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(40652)}:	Если ирКэш.НомерРежимаСовместимостиЛкс() >= 803006 Тогда
{ВнешняяОбработка.ирОбщий.МодульОбъекта(5082)}:	Возврат СтрНайтиЛкс(ПервыйФрагментЛкс(ТипЗначения, ":", Ложь), ПеревестиСтроку("табличная часть")) > 0;
{ВнешняяОбработка.ирОбщий.МодульОбъекта(25128)}:			Если ЛиТипТабличнойЧастиЛкс(ТипЗначения) Тогда
{ВнешняяОбработка.ирОбщий.МодульОбъекта(25050)}:		НастройкаПоУмолчанию.Значение = СохраняемаяНастройкаФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(37913)}:	СохранитьНастройкуФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирАнализТехножурнала.Форма.Форма.Форма(1757)}:	ирОбщий.Форма_ПриЗакрытииЛкс(ЭтаФорма);
```

**Comment by tormozit** [comment]
Сделай полный снимок окна приложения 1С при следующем возникновении такой ошибки. Важно увидеть все открытые в этот момент окна и их заголовки.

**Comment by PerlAmutor** [comment]
А там особо нечего снимать, все окна закрываются и остается только пустое окно обычного приложения и модальный диалог с текстом ошибки. Никаких дополнительных окон и инструментов помимо Анализа техножурнала я не открывал, чтобы исключить их влияние.

**Comment by PerlAmutor** [comment]
https://user-images.githubusercontent.com/87958986/134390195-ee4613b6-cb4e-4c78-90e9-5fa0f3281715.mp4

**Comment by PerlAmutor** [comment]
Стек возникновения ошибки:

![image](https://user-images.githubusercontent.com/87958986/134612985-dc902602-b08e-4b48-b23e-22eb9bd23ee3.png)


Проблема похоже все та же - различный порядок уничтожения обработок платформой - https://github.com/tormozit/RDT1C/issues/81

**Comment by tormozit** [comment]
Без стабильного способа воспроизведения такую ошибку выявить будет очень сложно из-за большого количества перекрестных ссылок в модулях в варианте "Портативный".

**Comment by PerlAmutor** [comment]
А не пробовал провести следующий эксперимент - сделать одну основную форму и цепочку из вспомогательных передавая параметр Владелец в ПолучитьФорму() и посмотреть в каком порядке вызывается событие ПриЗакрытии(), когда вызывается ЗавершитьРаботуСистемы(Ложь)?:

![image](https://user-images.githubusercontent.com/87958986/134755927-46661d2d-0b5e-4676-ac6b-4ba67b79715b.png)

Правда в случае нескольких модулей ирКэш и ирОбщий получается несколько владельцев должно быть, либо их надо выстраивать в цепочку на верхних уровнях и делать еще один общий для них объект.
