### ISSUE TITLE
Типизирующие комментарии формата "снегопат" "//:"

### ISSUE THREAD

**Issue by JohnyDeath** [tormozit/RDT1C#570]
Было бы отлично, если бы ИР научился воспринимать типизирующие комментарии не только формата "//!", но и формат снегопата "//:" 
У меня остались места с такими комментариями, когда снегопат еще работал. Было бы замечательно, если бы они обрели свою вторю жизнь.

**Comment by tormozit** [comment]
Нужен пример

**Comment by 7OH** [comment]
`//:Валюта = Справочники.Валюты.НайтиПоКоду();`
возможно тут может быть и создание объекта, если объект передавали
Снегопат "//:" заменял на лету на блок "#Если _ Тогда

**Comment by JohnyDeath** [comment]
> Снегопат "//:" заменял на лету на блок "#Если _ Тогда

нет, он не заменял. Он просто как бы откидывал "//:"
Но в любом случае в ИР уже есть механизм, только повешен на "//!"

Вот тут даже видео-пример остался: https://www.youtube.com/watch?v=ybQkiLsfCCw

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/979159

**Comment by tormozit** [comment]
Сделано в 7.12

**Comment by JohnyDeath** [comment]
Работает! Спасибо!
![image](https://github.com/tormozit/RDT1C/assets/5936030/e8f3823a-cde8-4de1-b942-0edf8cdebe2f)
