### ISSUE TITLE
Кэш модулей ИР Адаптера управление

### ISSUE THREAD

**Issue by Kebzaby** [tormozit/RDT1C#571]
Добрый день
Просьба рассмотреть вопрос управления кэшем модулей, а именно отключать не нужные расширения например патчи 1С.
По причине очень долгого по времени генерации кэша в случае наличия большого числа расширений, что является постоянным состоянием.

**Comment by tormozit** [comment]
Хотелось бы 
1. Техническую информацию
2. Полный список имен расширений из конкретной базы с обозначением бесполезных расширений.
3. Пример 2-х бесполезных расширений в виде CFE файлов
4. Файл замера производительности (файл PFF) операции выгрузки кэша модулей.
5. Примерную длительность всего этапа выгрузки расширений по ощущениям.
6. В идеале видеозапись процесса

**Comment by Kebzaby** [comment]
Что то сломалось, не могу повторить выгрузку кэша после обновлений ТК и ИР адаптера.
Есть какой то другой способ выгрузить кэш, кроме команды из меню в конфигураторе?
Поломка в следующем: 
1. в конфигураторе ctrl+` . в меню скрипты запускаю "обновить кэш модулей"
2. запускается ИР приложение удачно. 
3. возникает диалог вопрос Да - выгрузить через конфигуратор, Нет - через автономный сервер. Жал и Да и Нет.
4. далее попытка запуска приложения с ошибкой авторизации.
На этом все.
Запускал скрипт по сбросу настроек базы, вводил пароль снова. Приложение ИР запускается нормально, проблем с авторизацией не возникает. Как только начинаю выгрузку кэша - не авторизован.

**Comment by tormozit** [comment]
Форму "Настройки компоненты "Поле текста программы"", содержащую команды управления кэшем модулей, можно открыть из любого экземпляра этой компоненты. Например из консоли кода 

![изображение](https://github.com/tormozit/RDT1C/assets/11896251/75ba01a8-202a-41fc-9a9f-703cf285fafb)

По проблеме обновления кэша создай отдельную тему и вставь туда ее описание для случая без автономного сервера и дополнительно укажи

1. Техническую информацию
2. Картинку с отображением ошибки
3. Текст ошибки

**Comment by Kebzaby** [comment]
> * Файл замера производительности (файл PFF) операции выгрузки кэша модулей.

Не многу найти файл pff. Он сам создается при обновлении кэша модулей? Или что то от меня дополнительно требуется?

**Comment by tormozit** [comment]
файл pff создается пользователем в конфигураторе 

![изображение](https://github.com/tormozit/RDT1C/assets/11896251/7e4c2bff-91dc-4c22-8c7b-17bd1d5fafe0)

**Comment by tormozit** [comment]
Сделано в 7.13  https://www.hostedredmine.com/issues/979774

**Comment by tormozit** [comment]
Помогло?

**Comment by Kebzaby** [comment]
Обновил ИР до 7.13.
Выгрузка кэша теперь с пропусками патчей на моих мощях заняла 8 минут. База ЕРП 2.5.12 + 3 расширения.
Из них технический долг (на запуск перезапуск конфигуратора, предприятия и т.п.) - 3-4 мин.
Ранее процесс(со всем патчами около 90 шт) занимал навскидку 45-55 минут.
Гораздо лучше стало.

![Screenshot 2024-02-08 115424](https://github.com/tormozit/RDT1C/assets/118299315/4b9d19bd-48d1-4e73-b186-aafe8c752162)
Возможно тут стоит изменить сообщение?

**Comment by tormozit** [comment]
Согласен. Сообщение исправлю на

Будут выгружены модули всех расширений, кроме патчей EF, и затем основной конфигурации
