### ISSUE TITLE
Ошибка авторизации при обновлении кэша модулей

### ISSUE THREAD

**Issue by Kebzaby** [tormozit/RDT1C#572]
Платформа: 8.3.22.2175
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.195)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.12.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. EF_00_00573731 ()
Расширения. EF_00_00577225 ()
Расширения. EF_00_00574137 ()
Расширения. EF_00_00579457 ()
Расширения. EF_00_00577262 ()
Расширения. EF_00_00580313 ()
Расширения. EF_00_00583967 ()
Расширения. EF_00_00566422 ()
Расширения. EF_00_00584808 ()
Расширения. ИнструментыРазработчикаTormozit (7.12.1e)
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс
Сервер. ОС: Майкрософт Windows Server 2019 Datacenter 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

https://github.com/tormozit/RDT1C/assets/118299315/7e6022da-31f5-4f6a-bd60-cb0e950ae558

1. В конфигураторе ctrl+` . в меню скрипты запускаю "обновить кэш модулей". 
2. Запускается ИР приложение удачно.
3. Возникает диалог вопрос Да - выгрузить через конфигуратор, Нет - через автономный сервер. Жал и Да и Нет.
Далее попытка запуска приложения с ошибкой авторизации.
На этом все.
Запускал скрипт по сбросу настроек базы, вводил пароль снова. Приложение ИР запускается нормально, проблем с авторизацией не возникает. Как только начинаю выгрузку кэша - не авторизован.

ожидается обновление кэша модулей

**Comment by tormozit** [comment]
Нужна строка запуска процесса, который выдает эту ошибку. Если в ней есть пароль, нужно заменить его звездочками и сообщить, правильный ли он. Получить эту строку можно например через сторонние утилиты ProcessHacker или ProcessExplorer.

**Comment by Kebzaby** [comment]
`"C:\Program Files\1cv8\8.3.22.2175\bin\1cv8.exe"  ENTERPRISE /IBConnectionString"Srvr=""***"";Ref=""***"";Usr=""***"";" /DEBUG  /CОбновитьКэшМодулейИР;Нет`
В строке отсутствует параметр пароль. Остальные параметры корректные. Убрал их значения.

**Comment by Kebzaby** [comment]
У пользователя в базе настроена виндовая доменная аутентификация. Может он в них путается? 
Получилось запустить выгрузку кэша с через указание в сбросе винаутентификации, т.е. передав Srvr и Ref.
Ранее я указывал пароль аутентификации 1С. С ней все выше описанное происходит. Пароль в этом случае надо в каком виде указывать? Просто ввести или тоже с тегом?

**Comment by tormozit** [comment]
Попробуй в строку запуска добавить " /WA-".
Затем дополнительно попробуй в строку запуска добавить " /P<пароль>".

**Comment by tormozit** [comment]
Ты все правильно вводил.
Я ошибку воспроизвел. Она будет исправлена в следующей версии адаптера.

**Comment by Kebzaby** [comment]
Отлично. Рад был помочь.

**Comment by tormozit** [comment]
Исправлено в адаптере 1.32

**Comment by Kebzaby** [comment]
Обновил адаптер. Авторизация работает корректно.
