### ISSUE TITLE
Конструктор Запросов ИР. Ломается запрос. Плавающая ошибка.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#573]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.23.2040
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.14.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Форматирую ниже указанный запрос через Конструктор Запросов ИР или просто в нем открываю и частица "НЕ" в условии "Т.Партия НЕ В (" - пропадает. При этом в Конструкторе Запросов ИР в Отборе это условие помечается красным крестиком.
2. На другом компьютере воспроизвести не удалось. Непонятно что на это влияет.

```
ВЫБРАТЬ
	Т.Ссылка,
	Т.ИдентификаторСтроки,
	Т.Номенклатура,
	Т.Характеристика,
	Т.Серия,
	ВЫРАЗИТЬ(Т.Партия КАК Документ.ПриобретениеТоваровУслуг) КАК Партия
ПОМЕСТИТЬ ВтПартииЗакупок
ИЗ
	ВтТовары КАК Т
ГДЕ
	ТИПЗНАЧЕНИЯ(Т.Партия) = ТИП(Документ.ПриобретениеТоваровУслуг)
	И Т.Партия НЕ В (ЗНАЧЕНИЕ(Документ.ПриобретениеТоваровУслуг.ПустаяСсылка))
```

**Comment by tormozit** [comment]
Нужна картинка с красным крестиком

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/980299

**Comment by tormozit** [comment]
Исправлено в 7.15
