### ISSUE TITLE
Консоль запросов. Структура запросов. неожиданное поведение

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#574]
**Воспроизведение проблемы**

структура запроса. свернуть все. 
перейти на другой запрос, потом вернуться 
или ходить по тексту запроса.

**Ошибка**

автоматически разворачивается структура запроса. 

**Желаемое поведение**

хочу чтобы оставалась свернутой. можно сделать опцию Оставлять свернутой.

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.05.2e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.14.1e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details>

**Comment by tormozit** [comment]
Необходима картинка

**Comment by dmitri-0** [comment]
https://github.com/tormozit/RDT1C/assets/141411224/7e03de5b-0a11-4a21-a180-207517c6fe86

**Comment by tormozit** [comment]
Все деревья в инструментах разворачиваются автоматически, если в них менее 30 строк. Это сделано для удобства. Да, в каких то случаях или каким то людям это можно быть немного менее удобно, чем свернутое отображение по умолчанию всегда. Но ты не описал в чем заключается неудобство. Попробуй его описать более четко. Если оно действительно значимое, буду думать.

**Comment by tormozit** [comment]
Из существующих настроек можно попробовать эту установить в 1. Тогда будет строиться только верхний уровень ведомой структуры запроса.

![изображение](https://github.com/tormozit/RDT1C/assets/11896251/a8434dcf-115d-4c33-becb-504db25cc748)

**Comment by dmitri-0** [comment]
когда большой пакет запросов и много соединений таблиц, то ходить по развернутому дереву становится неудобно.
например если запросов в пакете около 20, то дерево становится слишком насыщенным.
мне нужно быстро перейти от запроса к запросу, это удобно когда оно свернуто.

функция автоматического разворачивания удобная.
предлагаю добавить опцию Оставлять свернутым для структуры запросов.

**Comment by tormozit** [comment]
Я же написал, что "когда большой пакет запросов и много соединений таблиц", дерево должно быть свернутым и разворачивает оно только путь к текущему узлу. У меня программа именно так ведет себя.
Ты показал маленькое дерево. Оно должно быть развернуто полностью сразу .
Покажи ситуацию, когда у тебя большое дерево само разворачивается полностью.

**Comment by tormozit** [comment]
Большая просьба - делай первую букву в предложении заглавной.  Так удобнее навигация по тексту.

**Comment by dmitri-0** [comment]
На больших запросах все равно разворачивается.
Нажимаю ctrl-s - разворачивается.
Поведение такое же как на видео, только запрос большой.
Жаль что у тебя не получается воспроизвести.

**Comment by tormozit** [comment]
Ты умеешь записывать видео с экрана. Так запиши "На больших запросах все равно разворачивается." и покажи мне.

**Comment by dmitri-0** [comment]
https://github.com/tormozit/RDT1C/assets/141411224/5bef22e2-569b-4f2f-ac33-2b72ee3f4827

**Comment by dmitri-0** [comment]
Получается 30 строк.
Это так не очевидно. Почему именно 30?
Можно как-то дать мне возможность самому регулировать это количество?

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/980328
Она снизит продемонстрированное тобой неудобство.

**Comment by tormozit** [comment]
Сделано в 7.15

**Comment by dmitri-0** [comment]
Большое спасибо!
