### ISSUE TITLE
Не работает поиск по названию на больших справочника (более 500000) при наличий в названии символа "/"

### ISSUE THREAD

**Issue by DenisBogdanskiiBS** [tormozit/RDT1C#575]
**Программное окружение**

Платформа: 8.3.22.1923
Режим БД: клиент-серверный
Конфигурация. Название: Управление торговлей, редакция 11 (11.4.14.181)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 7.14.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.14.2e)
Расширения. Патч_РасЗак_23012024_ПроверкаНазванияКонтрагента ()
Расширения. УниверсальныеИнструменты_БСПБезТаблиц (23.6.1)
Расширения. Фикс_ЗагрузкаZ ()
Расширения. лд_ОтчетПоступлениеТоваров ()
Расширения. РасширениеЗакупки ()
Расширения. лдСогласованиеЗаявокРДС ()
Расширения. API (4.0.1 23.05.22)
Расширения. Debug ()
Расширения. РасширениеОбменБП (28.07.2023)
Расширения. ...
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Сервер. Процесс: 32б
Сервер. Отладка: http

**Воспроизведение проблемы**
ну например в консоли запросов 
при вводе в поле вода названия заведомо существующего элемента подстановка ссылки на него не происходит 
если в названии есть символ "/" и при условии что в справочнике более 500000 элементов 

проблема в том что для поиска используется подобно со спецсимволом "/" но при этом экранирование его не происходит  

решается добавлением в ирОбщий.ТаблицаДанныхВыбораМенеджераЛкс после строки 29555 строки 
`ЗначениеОтбора = СтрЗаменить(ЗначениеОтбора, "/", "//");`

![image](https://github.com/tormozit/RDT1C/assets/160826374/b3d2bbf1-2e49-4324-9efb-2250d042db7e)

**Ожидаемое поведение**
ожидалось что при вводе названия элемента в поле с сылкой она будет туда выбрана

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/981163

**Comment by tormozit** [comment]
Исправлено в 7.16
