### ISSUE TITLE
Автоматическое открытие Интерфейсной панели при старте

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#576]
При старте системы открывать Интерфейсную панель.
![image](https://github.com/tormozit/RDT1C/assets/141411224/4b5556d9-a145-4b06-9506-43815d08d047)

Добавить опцию:
![image](https://github.com/tormozit/RDT1C/assets/141411224/92bb1d0a-b0da-4d66-a916-854d3c11272d)

Как если бы я добавил строку кода в расширение ИР:
Модуль приложения > ирПриНачалеРаботыСистемы()
```1c-enterprise
Обработки.ирИнтерфейснаяПанель.ПолучитьФорму().Открыть();

```

**Comment by tormozit** [comment]
Это будет замедлять каждый старт приложения. Сколько секунд открывается эта форма в твоей базе первый раз?

**Comment by dmitri-0** [comment]
Открывается моментально:
https://github.com/tormozit/RDT1C/assets/141411224/5adf02fc-ec48-4f6e-8bec-5685c1715394

Можно сделать опцию в настройках. Если кому-то надо (мне) - пусть включает.

**Comment by dmitri-0** [comment]
https://github.com/tormozit/RDT1C/assets/141411224/cc6a2e80-4a91-4acc-a34a-bce5c04610bd

**Comment by tormozit** [comment]
Я не достаточно подробно объяснил неочевидное поведение. Инструмент использует "таблицу всех таблиц БД", которая готовится в фоне (в непортативных вариантах). Длительность подготовки зависит от количества объектов метаданных в конфигурации. Поэтому если открывать его не сразу, то он открывается достаточно быстро. А вот при открытии сразу при стартер приложения он заблокирует интерфейс для ожидания подготовки этой таблицы. Объяснять это в описании предлагаемого флажка будет тяжело.

**Comment by dmitri-0** [comment]
Предлагаю при первоначальном запуске ИР оставить стандартное поведение, как сейчас.
Интерфейсной панелью приходится пользоваться очень часто.
Наличие такого флажка было бы удобно для меня. Я бы его нашел и включил. Остальные пусть не включают.

**Comment by dmitri-0** [comment]
Сергей, вы вот это будете реализовывать?

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/996646

**Comment by tormozit** [comment]
Сделано в 7.54
