### ISSUE TITLE
Динамический список. Ошибка отбора Ctrl-F 

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#577]
**Воспроизведение проблемы**

https://github.com/tormozit/RDT1C/assets/141411224/c1c40143-e7f4-4678-b922-2a1df4680bf1

**Ошибка**
```1c-enterprise
Ошибка при выполнении запроса.
по причине:
Невозможно применить элемент отбора в наборе данных "(Версия данных Содержит й ИЛИ Код Содержит й ИЛИ Наименование Содержит й ИЛИ (Ссылка.Наименование Содержит й))"

``` 

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.15.1e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Нет
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.15.1e)
<br>Клиент. Приложение: Обычное приложение 64б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details>

**Comment by tormozit** [comment]
У меня проблема не воспроизводится. Нужны выгрузка базы или хотя бы конфигурация.

**Comment by dmitri-0** [comment]
[https://disk.yandex.ru/d/mu4hry_MHKU9ug](url)

**Comment by dmitri-0** [comment]
https://disk.yandex.ru/d/mu4hry_MHKU9ug

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/981422

**Comment by tormozit** [comment]
Исправлено в 7.16.2

**Comment by dmitri-0** [comment]
Спасибо, в тестовой базе ок.
Но в другой базе с таким же режимом совместимости ошибка сохранилась.

```1c-enterprise
Ошибка при выполнении запроса.
по причине:
Невозможно применить элемент отбора в наборе данных "(Id ящика контур Содержит к ИЛИ Id ящика корус Содержит к ИЛИ Адрес Содержит к ИЛИ (Ассортиментная матрица.Наименование Содержит к) ....
```

**Comment by tormozit** [comment]
нужна выгрузка базы

**Comment by dmitri-0** [comment]
Не смогу предоставить выгрузку. Это коммерческая база.
Если интересно, то в документах работает, в справочниках - нет.
