### ISSUE TITLE
Порядок полей в запросе

### ISSUE THREAD

**Issue by 9815444** [tormozit/RDT1C#579]
Пример запроса:
![image](https://github.com/tormozit/RDT1C/assets/64223370/726b5287-9b23-4162-932b-cc2295268dea)
Задача: быстро выбрать явно (не через *) поля первой таблицы сохраняя исходный порядок колонок.
При выборе всех полей неявно порядок сохраняется.
Если нужно выбрать явно - приходится тыкать все поля.
А хотелось бы сохранить исходный порядок.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/986565

**Comment by tormozit** [comment]
Сделано в 7.31
