### ISSUE TITLE
Структура формы. Независимое открытие.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#58]
https://user-images.githubusercontent.com/87958986/133365963-4a4520ea-e5d8-4c8b-9537-6719ab9cf2c0.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.1p
> Инструменты разработчика. Инструмент: Структура формы
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При независимом открытии Структуры формы возникает ошибка:

```
Преобразование значения к типу Число не может быть выполнено
{ВнешняяОбработка.ирПлатформа.Форма.СтруктураФормы.Форма(214)}:	Интервал = ТекущаяУниверсальнаяДатаВМиллисекундах() - НачалоИндикации;
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(267)}:		РезультатФормы = ФормаНастроек.ОткрытьМодально();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(252)}:		ОткрытьФормуНастроек();

```

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.10.1
