### ISSUE TITLE
Загрузка из Табдокумента со спецсимволом

### ISSUE THREAD

**Issue by Kebzaby** [tormozit/RDT1C#580]
Платформа: 8.3.22.2175
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.12.215)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 7.13.1e
Инструменты разработчика. Инструмент: Таблица значений
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. Расширение_EDISoft (UT_1.02)
Расширения. EF_00_00599259 ()
Расширения. EF_00_00600705 ()
Расширения. EF_00_00600033 ()
Расширения. EF_00_00597907 ()
Расширения. EF_00_00600687 ()
Расширения. EF_10236898 ()
Расширения. EF_30176552 ()
Расширения. EF_60012503 ()
Расширения. EF_00_00591813 ()
Расширения. ...
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Datacenter 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. В инструменте консоль кода создаем параметр ТаблицаЗначений.
2. Открываем параметр и жмем Получить - из табличного документа например
3. На вопрос отвечаем Да.
![image](https://github.com/tormozit/RDT1C/assets/118299315/fa944e09-84ea-41b2-847d-621d73b20d50)
5. В табличном документе в текстовой ячейке присутствует спецсимвол "²" (степень). 
6. Пример текста в ячейке "абыр валг²".
7. При попытке загрузки документа с ячейкой с таким текстом вылезает ошибка преобразования к числу.
![image](https://github.com/tormozit/RDT1C/assets/118299315/fc06f89c-b396-4992-a5e4-d62a38eab9ad)

**Ожидаемое поведение**
Ожидалось загрузка табличного документа.

**Comment by tormozit** [comment]
Нужен полный текст ошибки

**Comment by Kebzaby** [comment]
Преобразование значения к типу Число не может быть выполнено
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(6797)}:		МассивЧастей.Добавить(Число(Сред(Представление, НачалоЧисла)));
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(6820)}:		МассивЧастей = ЧастиПредставленияДаты(Представление, ПозицияГода);
{ИнструментыРазработчикаTormozit Обработка.ирЗагрузкаТабличныхДанных.МодульОбъекта(813)}:									РезультатКонвертации = ирОбщий.СтрокаВДатуЛкс(ТекстЯчейки,, ТекстОшибки);
{ИнструментыРазработчикаTormozit Обработка.ирЗагрузкаТабличныхДанных.МодульОбъекта(170)}:		ОбновитьКолонкиТаблицыЗначений(, ЗначениеЗаполнено(ПолноеИмяТаблицы));
{ИнструментыРазработчикаTormozit Обработка.ирЗагрузкаТабличныхДанных.Форма.Форма.Форма(77)}:	УстановитьИсточник();
{ИнструментыРазработчикаTormozit Обработка.ирЗагрузкаТабличныхДанных.Форма.Форма.Форма(144)}:	УстановитьИсточникВФорме(РазрешитьЗаменуДанныхТДиТЗ, РазрешитьЗаменуДанныхТДиТЗ);
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(742)}:		РезультатФормы = Форма.ОткрытьМодально();
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(760)}:	ТабличныйДокументВТаблицуЗначений(, ТабличныйДокумент);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(5072)}:			РезультатВыбора = выхФорма.ОткрытьМодально();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(5839)}:		Результат = ОткрытьЗначениеЛкс(РасширенноеЗначение, РедактированиеРазрешено, СтандартнаяОбработка, Заголовок,, ПринудительноВОтдельнойФорме,, ТабличноеПоле, СтрокаПоиска, КлючУникальности);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(924)}:			Если ирКлиент.ЯчейкаТабличногоПоляРасширенногоЗначения_ВыборЛкс(ЭтаФорма, Элемент, СтандартнаяОбработка, ВыбраннаяСтрока.Значение,,,, ВыбраннаяСтрока.Имя) Тогда

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/981690

**Comment by tormozit** [comment]
Исправлено в 7.17
