### ISSUE TITLE
Редактор объекта БД. Не находит ссылки на удаленные документы с движениями в регистрах накоплений

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#582]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.23.2040
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.17.1p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
Пользователь обратился с проблемой на некорректные остатки в отчете. По 3-м регистрам накопления я обнаружил движения с регистратором "Объект не найден". Ссылку на регистратор открыл в инструменте Редактор Объекта БД и решил найти места где он используется. На вкладке "Ссылки на объект" ничего не находится ни стандартным поиском ни поиском ссылок на объект. Пришлось ограничиться запросом в консоли запросов по регистрам в которые документ потенциально может делать движения.

**Comment by tormozit** [comment]
Так было всегда и сделано умышленно. С точки зрения поиска ссылок движения документа считаются частью документа. Поэтому не отражаются в результатах поиска ссылок. Но все движения документа отображаются на странице "Движения" при включенном флажке "Вместе с движениями"

**Comment by PerlAmutor** [comment]
Я так и понял.
Хорошо, а почему бы поиск не добавить для целостности картины? Я ведь не последний человек, который такой же вопрос может задать в будущем.

**Comment by tormozit** [comment]
Учись использовать страницу "Связанные колонки БД". Она дает более низкий уровень представления связей данных. Там будет отображаться наличие ссылок в твоем случае.
