### ISSUE TITLE
Передача контекста исполнения из кода консоли запроса

### ISSUE THREAD

**Issue by Kebzaby** [tormozit/RDT1C#584]
При передачи из консоли запросов из Обработки Строки результата или Обработка результата в Консоль кода, передавать контекст выполнения Клиент/Сервер. Приходится переключать вручную.
![изображение](https://github.com/tormozit/RDT1C/assets/118299315/95d50339-a7e1-4176-add7-f42fea0d6bcc)

Сейчас контекст не передается. Но это не точно, последний релиз ИР не смотрел.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/981955

**Comment by tormozit** [comment]
Сделано в 7.18
