### ISSUE TITLE
Исследователь объектов. Дублирование слов

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#585]
**Воспроизведение проблемы**

https://github.com/tormozit/RDT1C/assets/141411224/a0acc6f6-6592-4625-97c5-d2fee41b35e5

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.19.1e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Да
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.19.1e)
<br>Клиент. Приложение: Обычное приложение 32б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details> 

Выгрузка:
[https://disk.yandex.com/d/ZXAYlRBBqbuD-g](url)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/982609

**Comment by tormozit** [comment]
Исправлено в 7.20
