### ISSUE TITLE
Интерфейсная панель. Формы с одинаковым синонимом группируются в одну

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#587]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.23.2157
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.20.1p
Инструменты разработчика. Инструмент: Интерфейсная панель
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В ERP есть справочник "Партнеры" у него 8 форм. Инструмент "Интерфейсная панель" показывает лишь 7 форм в контекстном меню.
2. Как я понимаю это из-за того, что 2 формы с одинаковым синонимом "Форма списка" группируются в одну
3. В конфигурации формы называются "ФормаСписка" и "ФормаСпискаБезПолнотекстовогоПоиска"

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/982796

**Comment by tormozit** [comment]
Исправлено в 7.21
