### ISSUE TITLE
Если обработка заполнения объекта выбрасывает исключение, запись дампа запроса не происходит

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#588]
**Программное окружение**

Платформа: 8.3.23.1997
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.20.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.20.2e)
Расширения. МаркетКоннекторКА2 (1.0.2.2)
Расширения. YAXUNIT (24.01.1)
Расширения. Зооград (1.1.1.10)
Расширения. Оптимизации ()
Расширения. испр_БСП_ОшибкаТипов ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл обработку проведения документа, в котором запрещено заполнять с "Неопределено"
2. При попытке отладить запрос для проведения получил ошибку
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/13d381da-311f-4dd1-ba84-5dae8c2c1d6b)

> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(1977)}: Ошибка при вызове метода контекста (Заполнить)	

3. Связана она с тем, что в обработку заполнения документа передается неопределено, но при этом необходимые реквизиты не заполняются, что вызывает выброс исключения о невозможности заполнения документа.
Данное поведение типовое.
![изображение](https://github.com/tormozit/RDT1C/assets/16429518/5168913a-2e0f-4722-9c74-41a1b4d9d4e3)

**Ожидаемое поведение**
Отсутствие препятствий для записи дампа.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/983742

**Comment by tormozit** [comment]
Исправлено в 7.22
