### ISSUE TITLE
Подбор и обработка объектов БД. Проблема с передачей значения поля "Сумма" из результата Консоли Запросов

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#589]
https://github.com/tormozit/RDT1C/assets/87958986/4cca42e4-c6c1-41d4-9ff5-d0c98dd599fb

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.24.1498
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.13.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.21.1p
Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Да
Расширения. Понижайка ()
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Выполнил запрос в Консоли Запросов:
```
ВЫБРАТЬ ПЕРВЫЕ 1
	Т.Ссылка,
	100 КАК Сумма,
	222 КАК _Сумма
ИЗ
	Справочник.ДоговорыКонтрагентов КАК Т

```
3. Выделил ссылку на договор в результате запроса
4. Вызвал команду " \ Панель \ Результат-коллекция(1) \ Командная панель \ Передать для обработки с параметрами"
5. В открывшемся инструменте "Подбор и обработка объектов БД" на странице "Строки для обработки" колонка "Сумма" передается с пустым значением, чего быть не должно.

**Comment by tormozit** [comment]
Скорее всего в справочнике есть такой реквизит "Сумма". В этом случае колонка связывается с реквизитом справочника и читает значения из него. Выбери другое имя. Предупреждение сделаю.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/984072

**Comment by tormozit** [comment]
Исправлено в 7.22
