### ISSUE TITLE
Удаление объектов с контролем ссылок. Ошибка при открытом Динамическом списке.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#59]
https://user-images.githubusercontent.com/87958986/133464477-6111d4c8-f402-4e81-bbfa-21abdbb23234.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.1p
> Инструменты разработчика. Инструмент: Динамический список
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При удалении объектов с контролем ссылок и открытой формы Динамического списка происходит ошибка:

```
Метод объекта не обнаружен (Обновить)
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(419)}:			ЭлементыФормы.ДинамическийСписок.Значение.Обновить();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(38012)}:			Форма.ОбработкаОповещения(ИмяСобытия, Параметр, Источник);
{ВнешняяОбработка.ирУдалениеОбъектовСКонтролемСсылок.Форма.Форма.Форма(375)}:		ирОбщий.ОповеститьФормыПодсистемыЛкс("ЗаписанОбъект", , ЭтаФорма);
{(1)}:ЭтаФормаИлиОбработка.УдалитьЗавершение(, Результат)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(30826)}:			Выполнить("ЭтаФормаИлиОбработка." + ОбработчикЗавершения + "(, Результат)");
{ВнешняяОбработка.ирУдалениеОбъектовСКонтролемСсылок.Форма.Форма.Форма(352)}:	РезультатЗапуска = ирОбщий.ВыполнитьЗаданиеФормыЛкс("УдалитьОбъектыЛкс",, ЭтаФорма, "УдалитьОбъекты",, Кнопка, "УдалитьЗавершение",, БлокируемыеЭлементыФормы, Истина);
{ВнешняяОбработка.ирУдалениеОбъектовСКонтролемСсылок.Форма.Форма.Форма(327)}:			ОсновныеДействияФормыУдалить(ЭлементыФормы.ОсновныеДействияФормы.Кнопки.Удалить);
{(1)}:ЭтаФормаИлиОбработка.КонтролироватьЗавершение(, Результат)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(30826)}:			Выполнить("ЭтаФормаИлиОбработка." + ОбработчикЗавершения + "(, Результат)");
{ВнешняяОбработка.ирУдалениеОбъектовСКонтролемСсылок.Форма.Форма.Форма(298)}:	РезультатЗапуска = ирОбщий.ВыполнитьЗаданиеФормыЛкс("КонтролироватьСсылкиНаКандидаты", ПараметрыЗадания, ЭтаФорма, "КонтролироватьСсылки",,

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/933471

**Comment by tormozit** [comment]
Исправлено в 6.10.1
