### ISSUE TITLE
Редактор выражения запроса в Конструкторе запроса ИР. Контекстная подсказка появляется только при нажатии CTRL-SPACE

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#590]
**Воспроизведение проблемы**

https://github.com/tormozit/RDT1C/assets/141411224/5bf51713-ff43-4437-b9a5-7587870fcf67

Причем, после использования подсказки по CTRL-SPACE пропадает фокус в поле редактора выражения запроса.
Фокус приходится возвращать туда мышкой.

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.22.1e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Да
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.22.1e)
<br>Клиент. Приложение: Обычное приложение 32б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details> 

Выгрузка:
[https://disk.yandex.com/d/Kj2F3njvppY7sA](url)

**Comment by tormozit** [comment]
Используй страницу "HTML редактор"

**Comment by tormozit** [comment]
В описании флажка "Автоматическое открытие" в настройках компоненты написано:
"Автоматически открывать список автодополнения при вводе текста. В HTML редакторе безусловно. Во встроенном редакторе доступно только в обычном приложении при включенном перехвате клавиатурного ввода **вне модальных групп окон**."

Поэтому используй страницу "HTML редактор"
