### ISSUE TITLE
Передача перечисления для обработки из консоли запросов вызывает ошибку.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#591]
https://github.com/tormozit/RDT1C/assets/87958986/bc676df7-8a02-47ec-8249-918d94995a13

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.24.1498
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.8.369)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_17
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.22.1p
Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При передаче значения перечисления из результата запроса в инструмент Подбор и Обработка объектов БД может возникать ошибка "Таблица БД с именем "" не найдена", если в инструменте предварительно не установлена таблица перечислений.

```
Таблица БД с именем "" не найдена
{ВнешняяОбработка.ирОбщий.МодульОбъекта(11989)}:		ВызватьИсключение "Таблица БД с именем """ + ПолноеИмяТаблицыБД + """ не найдена";
{ВнешняяОбработка.ирОбщий.МодульОбъекта(11120)}:	ТекстЗапроса = ПолучитьТекстЗапросаПолейТаблицыБДЛкс(ПолноеИмяТаблицыБД, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10889)}:		ТаблицаРезультата = ПустаяТаблицаЗначенийИзТаблицыБДЛкс(ПолноеИмяТаблицыБД, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирКэш.МодульОбъекта(72)}:	Результат = ирОбщий.ПоляТаблицыБДЛкс(ПолноеИмяТаблицыБД, НужныТолькоТипы, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10897)}:		Результат = ирКэш.ПоляТаблицыБДЛкс(ПолноеИмяТаблицыБД, Истина, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирКэш.МодульОбъекта(72)}:	Результат = ирОбщий.ПоляТаблицыБДЛкс(ПолноеИмяТаблицыБД, НужныТолькоТипы, ИндексПараметраПериодичность, ВыражениеПараметраПериодичность);
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ПодборИОбработка.Форма(2300)}:		ПоляТаблицыБД = ирКэш.ПоляТаблицыБДЛкс(ОбластьПоиска);
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ПодборИОбработка.Форма(1393)}:		ЗагрузитьСтрокиДляОбработки(ПараметрМассивСсылок,, ПараметрВыбранныеПоля, Истина);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(13204)}:	Форма.Открыть();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(13025)}:	ОткрытьМассивОбъектовВПодбореИОбработкеОбъектовЛкс(МассивСсылок,, ЭтаФорма,, КлючТекущейСтроки);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(11833)}:	ирКлиент.ОткрытьОбъектыИзВыделенныхЯчеекВПодбореИОбработкеОбъектовЛкс(ЭлементыФормы.РезультатКоллекция,, ЭтаФорма,, Истина);

```

**Comment by tormozit** [comment]
Ролик в данном случае лучше было начать записывать с последнего состояния, чтобы было понятно как из безошибочного состояния прийти в ошибочное. 
Ошибку воспроизвел https://www.hostedredmine.com/issues/984231
