### ISSUE TITLE
Анализ логов ТЖ зависает

### ISSUE THREAD

**Issue by AndreyIvanovich** [tormozit/RDT1C#592]
Платформа: 8.3.23.2040
Режим БД: клиент-серверный
Конфигурация. Название: Анализ ТЖ (2.0.9.11)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Режим использования синхронных вызовов: ИспользоватьСПредупреждениями
Инструменты разработчика. Версия: Расширение 7.22.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.22.1e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл инструмент Анализ логов ТЖ в режиме обычного приложения (в толстом управляемом клиенте аналогичное повдение)
2. Указал путь к логам ТЖ (сетевая шара)
3. Запустил загрузку и через какое-то время чтение логов останавливается, клиент зависает намертво (отменить через Ctrl+Alt+E не удается, только прибить через диспетчер задач) .

Пробовал оставлять на ночь, в 10% случаев чтение выполняется (общее время чтения более 8 часов), но чаще всего клиент просто висит. Объем логов примерно 1,5Гб. В логах событие DBPOSTGRS, без планов запросов. Пробовал копировать логи на другую машину (ryzen 5800X, 64GB ОЗУ, SSD) и читать через файловую базу, поведение аналогичное. Архив с логами - https://dropmefiles.com/HRSP0

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/984276

**Comment by tormozit** [comment]
Исправлено в 7.23
