### ISSUE TITLE
Ошибка при попытке выбрать значение внешнего источника данных через динамический список ИР

### ISSUE THREAD

**Issue by JohnyDeath** [tormozit/RDT1C#594]
**Программное окружение**

Платформа: 8.3.24.1368
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия предприятия КОРП, редакция 3.0. БитФинанс (3.0.150.33/3.1.59.6)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.26.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да

**Воспроизведение проблемы**
В конфигурации есть внешний источник данных (ВИД) "Тестовый". В нем прописана объектная таблица "Контрагенты".
В консоли запросов пишу текст:
```bsl
выбрать
тКонтрагенты.Ссылка как Контрагент
из ВнешнийИсточникДанных.Dox.Таблица.Контрагенты как тКонтрагенты
где тКонтрагенты.Ссылка = &Ссылка
```
На вкладке "Параметры" пытаюсь выбрать значение для этого параметра.
Открывается окно списка (вроде бы стандартное), но внизу появляется сообщение об ошибке:

> Ошибка динамического списка ИР: {ОбщийМодуль.ОбщегоНазначения.Модуль(3991)}: Объект метаданных "ВнешнийИсточникДанных.Dox.Таблица.Контрагенты" не имеет менеджера объекта.

Также открывается окно ИР "Текущие сообщения" (пустое).

Если же изменить тип запроса на "Компоновка" и попробовать там установить фильтр по контрагенту, то появляются те же ошибки и выбрать уже ничего не получается. Точнее в поле выбора всегда подставляется строковое представление. Ссылку выбрать никак не получается. 
![image](https://github.com/tormozit/RDT1C/assets/5936030/34946479-6521-4578-a407-b12ae263d64b)

**Ожидаемое поведение**
Хотелось бы, чтобы форма выбора открывалась без ошибок и соот-но выбор значения не приводил к таким последствиям

**Comment by JohnyDeath** [comment]
Также невозможно выбрать отбор по ссылочным типам в консоли компоновки.
Если сбросить тип, то появляется окно выбора типа и далее ничего: нет ни ошибок, ни открытия каких-то окон
![image](https://github.com/tormozit/RDT1C/assets/5936030/f593a01b-2230-4cd1-b6c2-72e98bdc4fd8)

**Comment by tormozit** [comment]
Найди в общем модуле БСП ОбщегоНазначения выброс исключения
`Объект метаданных ""%1"" не имеет менеджера объекта`
Установи там точку останова и повтори тест. Покажи стек желательно в текстовом виде.

**Comment by tormozit** [comment]
Объект метаданных принадлежит расширению или изменен расширением?

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/985469

**Comment by tormozit** [comment]
По полю ввода правого значения отбора создал задачу https://www.hostedredmine.com/issues/985470

**Comment by tormozit** [comment]
Исправлено в 7.27

**Comment by JohnyDeath** [comment]
Обе ошибки ушли.
Спасибо!
