### ISSUE TITLE
Ошибка при попытке открыть форму объекта: "ВнешнийИсточникДанных....Таблица.Контрагенты" не имеет менеджера объекта.

### ISSUE THREAD

**Issue by JohnyDeath** [tormozit/RDT1C#595]
**Программное окружение**

Платформа: 8.3.24.1368
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия предприятия КОРП, редакция 3.0. БитФинанс (3.0.150.33/3.1.59.6)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.27.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да

**Воспроизведение проблемы**
В консоли запросов пишем код:
```
выбрать первые 10
ссылка
из ВнешнийИсточникДанных.Dox.Таблица.Контрагенты
```
пытаемся открыть любую ссылку из результата, получаем ошибку

> Объект метаданных "ВнешнийИсточникДанных.Dox.Таблица.Контрагенты" не имеет менеджера объекта.
> {ОбщийМодуль.ОбщегоНазначения.Модуль(3991)}:ВызватьИсключение СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(
> {ОбщийМодуль.ПодключаемыеКоманды.Модуль(391)}:Менеджер  = ОбщегоНазначения.МенеджерОбъектаПоПолномуИмени(ПолноеИмя);
> {ОбщийМодуль.ПодключаемыеКоманды.Модуль(568)}:Источник = ЗарегистрироватьИсточник(ОбъектМетаданных, Источники, ПодключенныеОбъекты, НастройкиПрограммногоИнтерфейса);
> {ОбщийМодуль.ПодключаемыеКомандыПовтИсп.Модуль(12)}:Возврат Новый ФиксированнаяСтруктура(ПодключаемыеКоманды.КэшФормы(ИмяФормы, ИсточникиЧерезЗапятую, ЭтоФормаОбъекта));
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирСервер.Модуль(1174)}:КомандыБСП = ПодключаемыеКомандыМой.КэшФормы(".", ИмяОсновнойТаблицы, Ложь).Команды.Скопировать();
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(20085)}:КомандыБСП = ирОбщий.ОбъектИзСтрокиXMLЛкс(ирСервер.КомандыБСППоИмениТаблицыЛкс(ИмяТаблицы));
> {ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3554)}:мФормаУпрДляПодключаемыхКоманд = ирКлиент.ДобавитьКнопкиКомандБСПЛкс(ЭлементыФормы.ОсновныеДействияФормы, ИмяОсновнойТаблицы, ЭтоСсылочныйОбъект);
> {ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1171)}:ИмяОсновнойТаблицыПриИзменении(, ЗапретитьЗаполнение);
> {ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1111)}:УстановитьТаблицуБД(НовоеИмяОсновнойТаблицы, Истина); // Здесь будет прочитан объект, если имя таблицы изменилось
> {ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1041)}:ЗагрузитьОбъектПоКлючу(фОбъект.ПараметрКлючИлиОбъект);
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(11823)}:Форма.Открыть(); // В открытой форме платформа при этом тоже выполняет перерисовку табличных текущих страниц панелей формы
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(11727)}:Форма_АктивироватьОткрытьЛкс(ФормаРедактора);
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(11658)}:ФормаРедактора = ОткрытьРедакторОбъектаБДЛкс(ИмяТаблицы, ИмяПоля,, КлючОбъекта,, ДанныеСтрокиТаблицы, КлючОбъекта,, НайденныеСсылки,,,,, ИскомоеЗначение);
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(5237)}:ФормаСсылки = ОткрытьСсылкуВРедактореОбъектаБДЛкс(РедактируемоеЗначение);
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(5914)}:Результат = ОткрытьЗначениеЛкс(РасширенноеЗначение, РедактированиеРазрешено, СтандартнаяОбработка, Заголовок,, ПринудительноВОтдельнойФорме,, ТабличноеПоле, СтрокаПоиска, КлючУникальности);
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(9964)}:ирКлиент.ЯчейкаТабличногоПоляРасширенногоЗначения_ВыборЛкс(ЭтаФорма, Элемент, СтандартнаяОбработка);
> 

У ВнешнийИсточникДанных.Dox.Таблица.Контрагенты пустой модуль менеджера.
Форм, созданных в конфигураторе, тоже нет.

Возможно как-то связано с недавней решенной проблемой https://github.com/tormozit/RDT1C/issues/594

**Comment by tormozit** [comment]
Врядли это следствие каких то недавних изменений в ИР. 
Для обхода проблемы запусти управляемое приложение или создай управляемую форму объекта или открывай ссылку редактором объекта БД

**Comment by JohnyDeath** [comment]
Да, это не следствие недавних изменений. Я имел ввиду, что проблема скорее всего та же, что и в той задаче - БСП для внешних источников.
Я работал в управляемом приложении (толстый клиент).
Открытие в редакторе объекта БД тоже не работает:

> Объект метаданных "ВнешнийИсточникДанных.Dox.Таблица.Контрагенты" не имеет менеджера объекта.
> {ОбщийМодуль.ОбщегоНазначения.Модуль(3991)}:ВызватьИсключение СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(
> {ОбщийМодуль.ПодключаемыеКоманды.Модуль(391)}:Менеджер  = ОбщегоНазначения.МенеджерОбъектаПоПолномуИмени(ПолноеИмя);
> {ОбщийМодуль.ПодключаемыеКоманды.Модуль(568)}:Источник = ЗарегистрироватьИсточник(ОбъектМетаданных, Источники, ПодключенныеОбъекты, НастройкиПрограммногоИнтерфейса);
> {ОбщийМодуль.ПодключаемыеКомандыПовтИсп.Модуль(12)}:Возврат Новый ФиксированнаяСтруктура(ПодключаемыеКоманды.КэшФормы(ИмяФормы, ИсточникиЧерезЗапятую, ЭтоФормаОбъекта));
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирСервер.Модуль(1174)}:КомандыБСП = ПодключаемыеКомандыМой.КэшФормы(".", ИмяОсновнойТаблицы, Ложь).Команды.Скопировать();
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(20085)}:КомандыБСП = ирОбщий.ОбъектИзСтрокиXMLЛкс(ирСервер.КомандыБСППоИмениТаблицыЛкс(ИмяТаблицы));
> {ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(3554)}:мФормаУпрДляПодключаемыхКоманд = ирКлиент.ДобавитьКнопкиКомандБСПЛкс(ЭлементыФормы.ОсновныеДействияФормы, ИмяОсновнойТаблицы, ЭтоСсылочныйОбъект);
> {ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1171)}:ИмяОсновнойТаблицыПриИзменении(, ЗапретитьЗаполнение);
> {ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1111)}:УстановитьТаблицуБД(НовоеИмяОсновнойТаблицы, Истина); // Здесь будет прочитан объект, если имя таблицы изменилось
> {ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1041)}:ЗагрузитьОбъектПоКлючу(фОбъект.ПараметрКлючИлиОбъект);
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(11823)}:Форма.Открыть(); // В открытой форме платформа при этом тоже выполняет перерисовку табличных текущих страниц панелей формы
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(11727)}:Форма_АктивироватьОткрытьЛкс(ФормаРедактора);
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(11658)}:ФормаРедактора = ОткрытьРедакторОбъектаБДЛкс(ИмяТаблицы, ИмяПоля,, КлючОбъекта,, ДанныеСтрокиТаблицы, КлючОбъекта,, НайденныеСсылки,,,,, ИскомоеЗначение);
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(11635)}:ОткрытьСсылкуВРедактореОбъектаБДЛкс(ЗначениеЯчейки);
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(18427)}:ОткрытьСсылкуЯчейкиВРедактореОбъектаБДЛкс(ИсточникДействий);
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(10318)}:ирКлиент.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);

**Comment by tormozit** [comment]
> Я работал в управляемом приложении

Было бы здорово это сразу указывать. Тем более в технической информации по кнопке это сразу есть.

**Comment by JohnyDeath** [comment]
> Было бы здорово это сразу указывать. Тем более в технической информации по кнопке это сразу есть.

Вроде бы всё сразу указал. Как раз из кнопки в тех информации. Вот это разве не то?

> Конфигурация. Основной режим запуска: Управляемое приложение

Еще дополню.
Даже если у объекта ВИД есть форма и менеджер не пустой, то редактор объекта БД (ctrl+q в ячейке результата консоли запросов) отображает ту же самую ошибку.

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/985633

**Comment by JohnyDeath** [comment]
Про режим запуска я только сейчас увидел, что это отдельные строки, которые идут после списка расширений.
Извиняюсь, в первом посте сделал только верхушку тех инфо, чтобы не засорять информацией об установленных расширениях

> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. Отладка разрешена: Да
> Клиент. Постоянный кэш метаданных: Да
> Клиент. ОС Текущая кодовая страница: 866
> Клиент-Сервер. Пинг: 0мс

**Comment by tormozit** [comment]
> Вот это разве не то?

Это не то. Вот то

![изображение](https://github.com/tormozit/RDT1C/assets/11896251/50931d32-7345-4b08-998c-13be504d5f3c)

**Comment by tormozit** [comment]
> Возможно как-то связано с недавней решенной проблемой #594

Да. Проблема та же по сути.

**Comment by tormozit** [comment]
Исправлено в 7.27.2

**Comment by JohnyDeath** [comment]
Ошибка ушла. Но теперь для форму, у которой нет собственной формы, открывается сразу редактор объектов, а не сгенерированная платформой форма. 
Так и задумано?

**Comment by tormozit** [comment]
> Так и задумано?

Платформа не умеет генерировать обычную форму (в режиме обычного приложения) для таблицы внешнего источника.

**Comment by JohnyDeath** [comment]
Но я же в упр режиме нахожусь. При открытии элемента этого справочника из стандартного списка (не из ИР), то вполне себе открывается родная сгенерированная платформой форма.

**Comment by tormozit** [comment]
По открытию формы автоформы объекта исправлю https://www.hostedredmine.com/issues/985788

**Comment by tormozit** [comment]
Исправлено в 7.28

**Comment by JohnyDeath** [comment]
Спасибо!
