### ISSUE TITLE
Ошибка при передать для обработки

### ISSUE THREAD

**Issue by V-Shishov** [tormozit/RDT1C#596]
Комплексная автоматизация 2.4
Платформа 1С:Предприятие 8.3 (8.3.21.1624)

Получить эту информацию можно кнопкой "Техническая информация" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1

**Воспроизведение проблемы**
1. в форме журнала документов(например в списке документы продажи) выдираю несколько документов
2. Нажал кнопку стрл+ё. далее выбираю передать для обработки, Выполнить.
3. Получил окно с ошибкой "Поле не найдено "ДатаДокументаИБ"

**Ожидаемое поведение**
Хотелось б чтобы передавалось для обработки

в моно списках документов это работает

**Comment by tormozit** [comment]
Перейди по ссылке в своем сообщении и передай техническую информацию. Еще нужна картинка формы и самого глобального меню на ее фоне.

**Comment by V-Shishov** [comment]
Платформа: 8.3.21.1624
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.27.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. МаркетКоннекторКА2 (1.0.2.2)
Расширения. ИнструментыРазработчикаTormozit (7.27.2e)
Расширения. времотгрузка_ ()
Расширения. испрскладскиезоны ()
Расширения. НовыйСайтИМ_ОдностадийнаяОплата ()
Расширения. ФиксЦислинкСхемаКомпоновки ()
Расширения. испрфиксприемка ()
Расширения. испр_отчетыБанкаПоЭквайрингу ()
Расширения. Оптимизации ()
Расширения. СвободыеОстаткиНаСкладеПоОрганизациям_НовыйЗапрос ()
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Datacenter 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Comment by V-Shishov** [comment]
![2024-05-16_15-54-09](https://github.com/tormozit/RDT1C/assets/169971005/db215fed-f7cd-4ae7-b3d7-a1c36914b44c)

**Comment by V-Shishov** [comment]
![2024-05-16_15-57-16](https://github.com/tormozit/RDT1C/assets/169971005/134c7b5c-8c50-4fcf-a461-67c0add06193)

**Comment by tormozit** [comment]
Прошу полный **текст** ошибки. Для этого открой окно "О программе" и там снизу нажми на гиперссылку 

![изображение](https://github.com/tormozit/RDT1C/assets/11896251/d64612ef-1126-4d92-a23d-19d1c706946b)

**Comment by V-Shishov** [comment]
Добрый день.

Платформа: 1С:Предприятие 8.3 (8.3.21.1624)
Конфигурация: 1С:Комплексная автоматизация 2 (2.4.13.187) (http://v8.1c.ru/ka2/)
Copyright © ООО "1С-Софт", 2004-2021. Все права защищены
(http://www.1c.ru)

Расширения конфигурации:
- Патч расширение роли этапы доставки
- Патч мобиком загрузка ПКО сейф магазина
- Вр фикс 139151
- Отгрузко фиксы
- Фикс зг наши процедуры сервер получить торговых и сегменты
- Фикс "Обмен с set"
- Фикс QR Оплата
- Зооград (1.1.1.10)
- Зг ЗУП (1.0.2.16)
- ЭР_Обмен_КА_БП (1.0.2.24)
- Оптимизации
- Свободые остатки на складе по организациям новый запрос
- Испр отчеты банка по эквайрингу
- Доп ячейки ПФ
- Испрфиксприемка
- Фикс цислинк схема компоновки
- Новый сайт ИМ (Одностадийная оплата)
- Испрскладскиезоны
- Времотгрузка
- Инструменты разработчика tormozit (7.27.2e)
- МаркетКоннекторКА2 (1.0.2.2)

Режим: Серверный (сжатие: усиленное)
Приложение: Толстый клиент
Локализация: Информационная база: русский (Россия), Сеанс: русский (Россия)
Вариант интерфейса: Такси

Ошибки:
--------------------------------------------------------------------------------
17.05.2024 16:46:34
Ошибка при вызове метода контекста (Выполнить)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(24157)}:МакетКомпоновки = КомпоновщикМакета.Выполнить(Схема, НастройкаКомпоновки, ,, Тип("ГенераторМакетаКомпоновкиДанныхДляКоллекцииЗначений"), ПроверятьДоступностьПолей);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(3055)}:Запрос = ирОбщий.ЗапросИзКомпоновкиЛкс(СхемаКомпоновки, НастройкаКомпоновки, Истина);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(3163)}:КоллекцияСтрок = ДанныеСтрокДинамическогоСпискаЛкс(ТабличноеПоле, ВыделенныеСтроки,,,, ЭтаФорма,, выхТекущаяСтрока);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(18948)}:ВыделенныеСтроки = ВыделенныеСтрокиТабличногоПоляЛкс(ТаблицаФормы, НуженВидимыйПорядок,, ТекущаяСтрока);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирГлобальный.Модуль(573)}:Ссылки = ирКлиент.КлючиСтрокБДИзТаблицыФормыЛкс(Параметры.Форма, КлючТекущейСтроки, ТаблицаФормыДинамическогоСписка);
{(1)}:ОбработатьОбъектыАктивнойФормыЛкс(ПараметрыОбработчикаОжидания)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(2052)}:Выполнить(ПараметрыОбработчикаОжидания.ИмяМетода + "(ПараметрыОбработчикаОжидания)");
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(2047)}:ОбработчикОжиданияСЯвнымиПараметрамиЛкс(ПараметрыОбработчикаОжидания);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирГлобальный.Модуль(424)}:ирКлиент.ОбработчикОжиданияСПараметрамиЛкс();

по причине:
Ошибка компоновки макета
по причине:
Поле не найдено "ДатаДокументаИБ"
--------------------------------------------------------------------------------
17.05.2024 16:45:57
ИспрФиксРасчетСкидокСоСкладом: Низкая: Расширение неактивно и не будет применено

С уважением,
Виктор Шишов
Программист 1С
Тел.: +7 (423) 246-32-86,  доб. 156
Зооград

**Comment by tormozit** [comment]
Мне не удалось повторить ошибку. Выполни этом списке команду "Настроить список" в глобальном меню и покажи все непустые страницы формы настроек списка.

Установи точку останова на ошибочной строке кода 
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(24157)}:МакетКомпоновки = КомпоновщикМакета.Выполнить(Схема, НастройкаКомпоновки, ,, Тип("ГенераторМакетаКомпоновкиДанныхДляКоллекцииЗначений"), ПроверятьДоступностьПолей);

Сделай в этой остановке снимок схемы и настроек компоновки как показано тут https://www.youtube.com/watch?v=-NJJP79TccI&t=417s и передай снимок.

**Comment by V-Shishov** [comment]
Вот такое получилось

![image](https://github.com/tormozit/RDT1C/assets/169971005/cf5f21e5-6c9f-427d-bfcd-03479143b85d)

и Сохранил схему из консоли
[ОтладкаОшибка.zip](https://github.com/tormozit/RDT1C/files/15371100/default.zip)

**Comment by V-Shishov** [comment]
Странно как-то запрос из Реестра документов, там это поле есть.
А когда делаю из списка документов, запрос формируется из документа.

**Comment by tormozit** [comment]
Пока не удается воспроизвести ошибку. Сделал похожий отбор с полем, которое отсутствует у выбранных документов.
Попробуй перенести это поле в родителя и проверить ошибку. Затем в следующего родителя и так до конца.
Желательно найти минимальный отбор, с которым ошибка повторяется - в идеале с одним элементом.
