### ISSUE TITLE
Ошибка открытия консоли запросов  после обновления 7.28.1

### ISSUE THREAD

**Issue by ard-av** [tormozit/RDT1C#597]
**Программное окружение**

Получить эту информацию можно кнопкой "Техническая информация" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-Платформа: 8.3.22.2501
Режим БД: клиент-серверный
Конфигурация. Название: Управление торговлей, редакция 10.3 (10.3.47.3)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_10
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Конфигурация 7.28.1

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Нажал кнопку Открыть консоль запросов, при открытии
3. Получил окно с ошибкой ВВВ

**Ожидаемое поведение**
Какая реакция программы ожидалась?
Открытие консоли запросов без ошибок

**Дополнительно**

Обработка ирОболочкаРегВыражение, модуль объекта

// Заменить вхождения. Replace
Функция Заменить(Знач ТекстГдеИскать, Знач ШаблонЗамены) Экспорт 

Строка
Если  ТекущийДвижок = ДоступныеДвижки._1С Тогда  - выдает ошибку, ругается на _1С, так как при платформе 1с ниже 8.3.22 этот параметр в Структуру не добавляется
...
Возможное решение:
заменить на 

Если ДоступныеДвижки.Свойство("_1С") = Истина и ТекущийДвижок = ДоступныеДвижки._1С Тогда
+ добавил переменную ДоступныеДвижки, чтобы не использовать ДоступныеДвижки()._1С

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/985826

**Comment by tormozit** [comment]
Старайся указывать полный текст ошибки.
Исправлено в 7.28.2
