### ISSUE TITLE
Консоль HTTP запросов. Увеличить таймаут более 99 сек.

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#598]
**Воспроизведение проблемы**
![image](https://github.com/tormozit/RDT1C/assets/141411224/5fe48a0a-d022-42e9-81a9-35a82568f8e5)

**Желаемое поведение**
Добавить возможность в консоли HTTP запросов устанавливать таймаут более 99 сек.
Например, до 20 минут.

<details><summary>Программное окружение</summary>
<br>Платформа: 8.3.22.2283
<br>Режим БД: файловый
<br>Конфигурация. Название: ИР расширение ()
<br>Конфигурация. Основной режим запуска: Обычное приложение
<br>Конфигурация. Вариант встроенного языка: Русский
<br>Конфигурация. Режим управления блокировкой данных: Управляемый
<br>Конфигурация. Режим совместимости: Версия8_3_10
<br>Конфигурация. Режим использования синхронных вызовов: Использовать
<br>Инструменты разработчика. Версия: Расширение 7.27.1e
<br>Инструменты разработчика. Инструмент: Прочее
<br>Инструменты разработчика. Перехват клавиатурного ввода: Да
<br>Инструменты разработчика. Объекты на сервере: Нет
<br>Инструменты разработчика. Асинхронность запрещена: Нет
<br>Инструменты разработчика. Разрешены имитаторы: Да
<br>Расширения. ИнструментыРазработчикаTormozit (7.27.1e)
<br>Клиент. Приложение: Обычное приложение 32б
<br>Клиент. Проверка модальных вызовов: Нет
<br>Клиент. Язык интерфейса конфигурации: ru
<br>Клиент. Язык интерфейса системы: ru
<br>Клиент. Отладка разрешена: Да
<br>Клиент. Постоянный кэш метаданных: Да
<br>Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
<br>Клиент. ОС от имени администратора: Нет
<br>Клиент. ОС выполнение BAT: Да
<br>Клиент. ОС Текущая кодовая страница: 866
</details>

**Comment by tormozit** [comment]
Почему не хватает 99 секунд? Опиши подробнее сценарий, когда это нужно.

**Comment by dmitri-0** [comment]
Мне не хватило 99 секунд в одном из применений.
В тело ответа загружается JSON-строка большой длины (17 Мб).
Генерация данной строки занимает много времени.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/985942

**Comment by tormozit** [comment]
Сделано в 7.29
