### ISSUE TITLE
Подбор и обработка объекта БД. Удалить регистрацию на узле. Недопустимое значение параметра (параметр номер '2')

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#599]
https://github.com/tormozit/RDT1C/assets/87958986/52bf6464-0c0a-4f86-a274-f7429b4d7267

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.24.1548
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.29.1p
Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
Понадобилось обновиться на новый релиз ERP. Для отложенных обработчиков зарегистрировались на узле плана обмена "ОбновлениеИнформационнойБазы" ключи записей регистра накопления нашего (не типового) документа. При этом сам документ не входит в состав ни одного плана обмена, просто имеет движения в обрабатываемом регистре накопления.
Когда от обработчиков посыпались ошибки типа "Таблица "Изменения" не найдена" было решено удалить ссылки на документы из узла, но сделать этого я не смог, т.к. получил подобную ошибку:

```
Обработка объекта DocumentObject.Документ1(Документ1 1 от 28.05.2024 19:50:52,6dd29773-1d12-11ef-84de-6c71d914a43d)
	{ВнешняяОбработка.ирОбщий.МодульОбъекта(2413)}: Ошибка при вызове метода контекста (УдалитьРегистрациюИзменений): Недопустимое значение параметра (параметр номер '2')
*Строк обработано - 1, неуспешно - 1, успешно - 0. Объектов обработано - 1, записано автоматически - 0.
*Обработка 1 потоков завершено за 0:00:00 (0 сек)

```

Как оказалось для удаления необходимо передать не ссылку, а ключи записей регистра. Но вот что непонятно, есть ведь галочка "Вместе с движениями (для документа)", так какая разница передаю я ссылку на документ или ключ записи, если движения должны в любом случае удаляться, даже если сам документ не участвует ни в одном плане. Ну и в любом случае такая ошибка хотя бы должна быть как-то оформлена, если исправлять не планируется.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/986248

**Comment by tormozit** [comment]
Исправлено в 7.30
