### ISSUE TITLE
Консоль запросов. Сравнение текстов не закрывается при завершении работы ИР

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#6]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1363
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.7.151)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_12
> Конфигурация. Версия БСП: 300
> Инструменты разработчика. Версия: Портативный 5.97.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Microsoft Windows 7 Ultimate  64-bit Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 7 version 6.1 Service Pack 1 (Build 7601)

</details>

При завершении работы ИР (вариант Портативный) автоматически не закрывается форма сравнения текстов, что приводит к некоторым ошибкам, если продолжать работать с формой. Информация для технической поддержки предоставлена для версии 5.97.1p, но ошибка воспроизводится и на версии 6.02.1p

https://user-images.githubusercontent.com/87958986/127015024-3ce442c3-4297-4dbb-b0ba-f99c816c1a9b.mp4

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/931231

**Comment by tormozit** [comment]
Исправлено в 6.03
