### ISSUE TITLE
Дополнительные параметры запуска. Очищаются при сохранении настроек ИР

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#60]
https://user-images.githubusercontent.com/87958986/133466391-5290bd51-8cab-44ff-84a5-a2d93efa346f.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.1p
> Инструменты разработчика. Инструмент: Обработка.ирПортативный.Форма.ФормаНастроек
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При сохранении настроек ИР в "Список инструментов и общие настройки" - очищаются Дополнительные параметры запуска у текущей базы.

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/933479

**Comment by tormozit** [comment]
Исправлено в 6.10.1
