### ISSUE TITLE
Редактор объекта БД. Изменения на узлах. Недопустимое значение параметра (параметр номер '2')

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#600]
https://github.com/tormozit/RDT1C/assets/87958986/02963bc1-f7bd-4361-a864-6cbf96ba3771

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.24.1548
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.29.1p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
Если выбрать регистр накопления в Редакторе объекта БД и без установленного отбора по измерениям выполнить регистрацию на узле плана обмена, то выдается такая ошибка:

```
Ошибка при вызове метода контекста (ЗарегистрироватьИзменения)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(2399)}:			ПланыОбмена.ЗарегистрироватьИзменения(НесобственныеУзлы, Объект); 
{ВнешняяОбработка.ирОбщий.МодульОбъекта(2356)}:		ИзменитьРегистрациюОбъектаДляУзлаЛкс(УзлыДляРегистрации, Объект, НовоеЗначение, ОдинУзелОбмена, НомерВерсииПлатформы);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(2778)}:			ирОбщий.ПланыОбменаИзменитьРегистрациюЛкс(СтрокаУзла.УзелОбмена, КлючОбъекта, СтрокаУзла.Пометка, фОбъект.ЛиЧитатьПисатьДвижения, фОбъект.ЛиЧитатьПисатьДвижения);
по причине:
Недопустимое значение параметра (параметр номер '2')

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/990739

**Comment by tormozit** [comment]
Исправлено в 7.40
