### ISSUE TITLE
Список значений. Дополнить список не дополняется при различной комбинации составных типов.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#601]
https://github.com/tormozit/RDT1C/assets/87958986/abd5fe3b-cd64-486d-b1f5-3dcd68bd1d88

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.24.1548
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.29.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

Есть 2 списка значений сохраненных в *.VL файлы со списком ссылок полученных различным путем. Если набор типов обоих файлов отличается, но при этом каждый из них содержит общий тип, то не появляется предложение о дополнении списка значений вместо его полной замены.

![image](https://github.com/tormozit/RDT1C/assets/87958986/9b291f80-c152-47c0-baeb-5597175985bc)

![image](https://github.com/tormozit/RDT1C/assets/87958986/132c4a8d-43f8-4756-82cf-0d6b67626b83)

[СпискиСсылок.zip](https://github.com/tormozit/RDT1C/files/15478089/default.zip)

**Ожидаемое поведение**
Дополнение списка, если ссылки из открываемого файла входят в состав типов списка значений или тип списка значений - произвольный тип.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/986343

**Comment by tormozit** [comment]
Сделано в 7.30
