### ISSUE TITLE
Консоль запросов. Параметры. Вставка периода не добавляет параметр "КонецПериода", если заранее добавлен параметр "НачалоПериода"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#602]
https://github.com/tormozit/RDT1C/assets/87958986/49584e0d-3379-4b16-8633-fd211bd119b0

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.24.1548
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.29.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
Если в Консоли Запросов заранее был добавлен параметр "НачалоПериода", то при вызове команды "Период" не добавляется парный параметр "КонецПериода" и наоборот. Даже если период представлен одной датой, то было бы удобней иметь именно 2 параметра содержащего одну дату (Начало и Конец дня), чтобы в будущем не добавлять его вручную.

При этом даже если в параметрах добавлено заранее сразу 2 параметра НачалоПериода и КонецПериода, то перезаполняется лишь один из них:

![image](https://github.com/tormozit/RDT1C/assets/87958986/84c3d4c9-7667-426b-9388-5d25439e59ef)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/986342

**Comment by tormozit** [comment]
Исправлено в 7.30
