### ISSUE TITLE
Консоль запросов + Техножурнал. Ошибка Метод объекта не обнаружен (ОбновитьТаблицуЖурнала)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#603]
https://github.com/tormozit/RDT1C/assets/87958986/15fe3092-a148-4c09-96ec-e72c66feea92

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.24.1548
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.30.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В инструменте Консоли Запросов вызвать команду " \ Панель \ Запрос результата(14) \ Командная панель \ Техножурнал"
2. Возникает ошибка:

```
Метод объекта не обнаружен (ОбновитьТаблицуЖурнала)
{ВнешняяОбработка.ирАнализТехножурнала.МодульОбъекта(1948)}:	ФормаАнализа.ОбновитьТаблицуЖурнала(УдалитьДополнительныеСобытия, ИменаНеполезныхКолонок, Истина, ЖдатьСекунд, СмещениеБазовогоУровня);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(7617)}:		мАнализТехножурнала.ПоказатьТрассу(, "СтрокаМодуля",, 0, Истина, Ложь, Истина);

```

**Comment by tormozit** [comment]
А если напрямую открыть анализ техножурнала, то он работает?

**Comment by PerlAmutor** [comment]
> А если напрямую открыть анализ техножурнала, то он работает?

Да, работает.

**Comment by tormozit** [comment]
В новом сеансе воспроизводится?

**Comment by tormozit** [comment]
Не удалось воспроизвести 
Платформа: 8.3.24.1368
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_11
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 7.30.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

**Comment by PerlAmutor** [comment]
> В новом сеансе воспроизводится?

Перезапустил. Больше не воспроизводится. Зато теперь другую ошибку пишет:

`Указанный путь "E:\TEMP\File__E__1C_ФайловыеБазы_ИРОтладка__\Администратор" не доступен: {ВнешняяОбработка.ирОбщий.МодульОбъекта(21752)}: Ошибка при вызове метода контекста (ЭтоКаталог): Ошибка доступа к файлу: E:\TEMP\File__E__1C_ФайловыеБазы_ИРОтладка__\Администратор
`

**Comment by tormozit** [comment]
Тогда предлагаю закрыть заявку. Переоткроешь, когда научишься воспроизводить.

**Comment by tormozit** [comment]
Подобная проблема (платформа как бы загружает пустой модуль у обычной формы внешней обработки) была в платформе когда то давно. Тогда был стабильный способ воспроизведения и ее исправили. На форуме https://devtool1c.ucoz.ru/forum/ точно есть темы по ней. Вероятно тут какой то редкий остаток от нее.
