### ISSUE TITLE
Ошибка в подбор и обработка объектов при удалении через СУБД в УНФ

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#604]
**Программное окружение**

Платформа: 8.3.23.1865
Режим БД: клиент-серверный
Конфигурация. Название: Управление нашей фирмой, редакция 1.6 (1.6.26.185)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 7.30.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.30.2e)
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows Server 2022 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ╥хъє∙р  ъюфютр  ёЄЁрэшЎр: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Использую подбор и обработку объектов, чтобы удалить документы за определенный период через СУБД, используя эту возможность https://www.hostedredmine.com/issues/956405
2. Жму кнопку удалить через СУБД
3. Получаю ошибку и удаление дальше не идет.
Текст ошибки:
Ошибка при вызове метода контекста (Выполнить)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(28736)}:Запрос.Выполнить();
{ИнструментыРазработчикаTormozit Обработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(617)}:ТекстСУБД = ирОбщий.ВыполнитьЗапросИНайтиТекстСУБДЛкс(Запрос, ИмяТаблицыХранения, Ложь);
{ИнструментыРазработчикаTormozit Обработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(445)}:УдалитьСтрокиТаблицыСУБДПорциями(Запрос, РегистрМД.ПолноеИмя(), ИмяТаблицыКлючей, ИмяТаблицыКлючейСУБД, "Регистратор", выхОтключенныеИтоги);
{ИнструментыРазработчикаTormozit Обработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(302)}:УдалитьОбъектыЧерезСУБД(Запрос, ИмяТаблицы,, ИмяТаблицыКлючей, ТекстСУБД, ОтключенныеИтоги);

по причине:
{(1, 14)}: Таблица не найдена "РегистрБухгалтерии.Управленческий.Субконто"
ВЫБРАТЬ 1 ИЗ <<?>>РегистрБухгалтерии.Управленческий.Субконто КАК Т

Подозреваю, что это из-за того, что в УНФ урезанный бух.регистр и у него нет таблицы Субконто.

**Ожидаемое поведение**
Ждал, что начнется удаление

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/986847

**Comment by tormozit** [comment]
Исправлено в 7.31
