### ISSUE TITLE
ИР Адаптер команда принудительного подключения приложения ИР

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#605]
Когда я запускаю конфигуратор с ТК, то хотелось бы все необходимые действия выполнять до того, как начинаю работать.
В т.ч. запускать приложение ИР.
А то часто получается, такая ситуация.
Я открыл нужные объекты и модули, все посмотрел, что нужно, осознал, что надо писать.
Начинаю в модуле писать код... И жду, пока приложение ИР запуститься.
Т.е. приходиться ждать, хотя я уже готов работать.

**Comment by tormozit** [comment]
На текущий момент заявки по ИР адаптеру следует создавать тут https://turboconf.ru/Tasks?forumId=28 . Это указано в разделе "Техническая поддержка" в публикации адаптера.
