### ISSUE TITLE
ИР Адаптер команда фонового перезапуска приложения ИР

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#606]
Было бы очень удобно, если бы можно было бы отправить на перезапуск сеанса приложение ИР, а в это время работала бы подсказка от турбоконфа.
А когда приложение ИР перезапуститься, чтобы было переключение той же контекстной подсказки на ИР Адаптер.
Это позволит не останавливать набор кода, а продолжить пользоваться менее удобной по все же более продвинутой, чем стандартная, контекстной подсказкой.
Сейчас при необходимости перезапуска приложения ИР, приходится его принудительно завершать, а потом ждать его запуска после начала набора кода.

**Comment by tormozit** [comment]
На текущий момент заявки по ИР адаптеру следует создавать тут https://turboconf.ru/Tasks?forumId=28 . Это указано в разделе "Техническая поддержка" в публикации адаптера.
