### ISSUE TITLE
Редактор объекта БД. Поиск ссылок. Ошибка при вызове метода контекста (ЗначениеИзСтрокиВнутр)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#607]
https://github.com/tormozit/RDT1C/assets/87958986/97ff7db3-75b2-4700-bc41-34af8bfd6455

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.24.1548
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: НеИспользовать
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.31.2p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При выборе элемента справочника "ОбъектРасчетов" (ERP) помеченного на удаление в инструменте Редактор объекта БД возникает ошибка, если выбрать страницу "Критерии отбора" на вкладке "Ссылки на объект".

```
Ошибка при вызове метода контекста (ЗначениеИзСтрокиВнутр)
{ВнешняяОбработка.ирРедакторОбъектаБД.МодульОбъекта(80)}:		НайденнаяСсылка = ЗначениеИзСтрокиВнутр(СтрокаНайденного.Данные);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4778)}:		ОбработкаОбъект.ОбработатьТаблицуНайденныхСсылок(РезультатЗадания.ТаблицаСсылок, РезультатЗадания.СсылкиНа, СсылкиНаОбъект);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(4734)}:		ПоискСсылокЗавершитьВФорме(, РезультатЗадания);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1740)}:			КП_СсылкиНаОбъектОбновить();
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(703)}:	ПанельОбъектаПриСменеСтраницы();
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(460)}:	ПоместитьДанныеОбъектаВФорму(мСтруктураОбъектаБД,, СсылкаИзменилась);
{ВнешняяОбработка.ирРедакторОбъектаБД.Форма.Форма.Форма(368)}:		ПеречитатьДанные();
{ВнешняяОбработка.ирДинамическийСписок.Форма.Форма.Форма(544)}:		ОповеститьОВыборе(ВыбраннаяСтрока);
по причине:
Несоответствие типов (параметр номер '1')

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/987281

**Comment by tormozit** [comment]
Исправлено в 7.32
