### ISSUE TITLE
Конструктор регулярного выражения: Ошибка при попытке "Сгенерировать код"

### ISSUE THREAD

**Issue by DJRelax** [tormozit/RDT1C#608]
**Программное окружение**

Платформа: 8.3.18.1563
Режим БД: клиент-серверный
Конфигурация. Название: Учет печатной продукции (1.1.24.171)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: АвтоматическийИУправляемый
Конфигурация. Режим совместимости: Версия8_3_15
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Конфигурация 7.31.2
Инструменты разработчика. Инструмент: Конструктор регулярного выражения
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл инструмент "Конструктор регулярного выражения"
2. Открыл свои сохраненные выражения.
3. Проверил работу Выражений(все нормально отробатывает
4. Вариант вычислителя стоит "PCRE2"(нужен именно он, так как используется "Просмотр назад" )
5. Нажал кнопку "Сгенерировать код"
6. Получил окно с ошибкой 
```
{Обработка.ирКонструкторРегулярногоВыражения.Форма.Форма.Форма(454)}: Поле объекта не обнаружено (_1С)
	Если ДвижокВычислителя = ДоступныеДвижки._1С Тогда
```

**Ожидаемое поведение**
Код для модуля

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/987280

**Comment by tormozit** [comment]
Исправлено в 7.32
