### ISSUE TITLE
Вылетает платформа при использовании редактора кода HTML

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#610]
**Программное окружение**

Платформа: 8.3.19.1529
Режим БД: клиент-серверный
Конфигурация. Название: Business automation software for accounting (2.1.16.1)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.25.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ЗапуститьСеансПользователя (2.0)
Расширения. ОграничениеДоступа ()
Расширения. БлокировкаУдобнее (1.2)
Расширения. МониторингОбменаБСП (21.01.06)
Расширения. ИнструментыРазработчикаTormozit (7.25.1e)
Расширения. HF ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: uk
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2019 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Microsoft Windows Server 2019 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл инструмент Консоль компоновки данных
2. Вкладка ресурсы - открыл редактирование ресурса
3. повторил 1-2 раза - клиент закрылся

**Comment by tormozit** [comment]
Автоматический выбор этой вкладки при открытии окна делается из-за этого изменения https://www.hostedredmine.com/issues/984945 . 
Как временное решение, отключи автоматическое открытие окна автодополнения и подсказки по вызову метода. Тогда будет активироваться вкладка "Встроенный редактор". 

Если запустить новое клиентское приложение и сразу открыть в нем консоль компоновки и HTML редактор выражения компоновки, то как быстро удается повторить аварийное завершение программы?

**Comment by tormozit** [comment]
Постараюсь решить проблему основательно в следующей версии

**Comment by marv-ua** [comment]
> Если запустить новое клиентское приложение и сразу открыть в нем консоль компоновки и HTML редактор выражения компоновки, то как быстро удается повторить аварийное завершение программы?

Буквально сразу.

**Comment by marv-ua** [comment]
еще заметил закономерность:
1-е открытие редактора кода в HTML редакторе кода обычно не вылетает, 2-е почти всегда вылетает.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/987712

**Comment by tormozit** [comment]
Сделано в 7.33
