### ISSUE TITLE
Консоль заданий: обновлять список регламентных заданий автоматически после ручного выполнения

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#611]
Некоторые регламентные задания (РЗ) удаляют (отключают) сами себя после успешного завершения.
Пример из типовых - ОтложенноеОбновлениеИБ.
Хочу чтобы после того как я выполнил любое РЗ список этих РЗ обновлялся автоматически. Если с фоновым выполнением такого добиться сложно, то хотя бы для команд синхронного выполнения (на клиенте / на сервере).

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/987922

**Comment by tormozit** [comment]
Сделано в 7.34
