### ISSUE TITLE
Не работает подсказка во встроенном редакторе в редакторе кода, в редакторе запросов

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#612]
**Программное окружение**
Платформа: 8.3.19.1529
Режим БД: клиент-серверный
Конфигурация. Название: Business automation software for accounting (2.1.16.1)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.33.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.33.1e)
Расширения. ОграничениеДоступа ()
Расширения. БлокировкаУдобнее (1.2)
Расширения. МониторингОбменаБСП (21.01.06)
Расширения. ЗапуститьСеансПользователя (2.0)
Расширения. HF ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Да
Клиент. Язык интерфейса конфигурации: uk
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2019 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Microsoft Windows Server 2019 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

Получить эту информацию можно кнопкой "Техническая информация" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1

**Воспроизведение проблемы**
1. Открыл инструмент редактор запросов
2. в запросе к примеру в условии ПО Статусы.ДокументПакет = Пакет.Ссылка после точки нажимаю контрол-пробел
3. ничего не происходит

1. в консоли кода пишу Справочники.
2. нажимаю контрол пробел - ничего не происходит

**Ожидаемое поведение**
ожидалось контекстная подсказка как на версиях ранее

**Comment by marv-ua** [comment]
Дополнение: окно подсказки таки появляется, но прячется на заднем плане

**Comment by tormozit** [comment]
Автооткрытие подсказки включено?

**Comment by marv-ua** [comment]
Как проверить?

**Comment by marv-ua** [comment]
она всплывает сама, просто фокус переключается на основное окно приложения

**Comment by marv-ua** [comment]
она открывается как отдельное окно 
![image](https://github.com/tormozit/RDT1C/assets/81148850/c049bcbc-fac3-4f4f-b278-4b689d3ae676)

**Comment by tormozit** [comment]
Проблему воспроизвел https://www.hostedredmine.com/issues/988037

**Comment by tormozit** [comment]
Исправлено в 7.33.2

**Comment by tormozit** [comment]
Помогло?

**Comment by marv-ua** [comment]
да, спасибо
