### ISSUE TITLE
Настройка форматирования CTRL-ALT-F

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#613]
@Tormozit ИР Адаптер. ИР.

Сделай, пожалуйста, так, чтобы CTRL-ALT-F настраивался. Например, чтобы я мог указать убирать лишние пробелы, строки, а нужные пробелы вокруг операторов, наоборот, расставил.

У тебя форматирование работает по своему алгоритму. Сделай так чтобы форматирование было настраиваемым. Мне нравится, что делает дополнительный отступ для строк, например, для текста запроса. Вот только не убирает пробелы, например, 

```1c-enterprise
А       =Б;

``` 

Также, убрать более двух пустых строк подряд.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/990588

**Comment by tormozit** [comment]
Сделано в 7.39
