### ISSUE TITLE
Консоль кода. CTRL-M не работает в HTML-редакторе

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#614]
Шорткат CTRL-M не работает в режиме HTML-редактора.

<details><summary>Details</summary>
<p>

Платформа: 8.3.22.2283
Режим БД: клиент-серверный
Конфигурация. Название: Зарплата и управление персоналом КОРП, редакция 3.1 (3.1.27.193)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 7.34.3e
Инструменты разработчика. Инструмент: Консоль кода
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.34.3e)
Расширения. КХ_ПуляевскийИП_20240418_ОтключениеПроверкиДатРасчетнаяВедомость ()
Расширения. ...
Клиент. Приложение: Управляемое приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Microsoft Windows Server 2019 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

</p>
</details>

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/988859

**Comment by tormozit** [comment]
Исправлено в 7.35
