### ISSUE TITLE
В редактор реквизита типа "Хранилище значений" невозможно загрузить НастройкиКомпоновкиДанных из строки (внутр)

### ISSUE THREAD

**Issue by JohnyDeath** [tormozit/RDT1C#615]
**Программное окружение**

Платформа: 8.3.24.1368
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия предприятия КОРП, редакция 3.0. БитФинанс (3.0.152.28/3.1.59.8)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.35.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да

**Воспроизведение проблемы**
1. Открыть в редакторе объекта любой элемент справочника "ВариантыОтчетов" (в любой типовой с БСП)
2. Открыть реквизит "Настройки" 
3. В меню выбрать "В строку - Внутр" и скопировать в буфер полученное содержимое 
![image](https://github.com/user-attachments/assets/6c7497de-5113-45bb-94ea-6fa55e3d5220)

Теперь попытаемся загрузить настройки, которые у нас в буфере в этот же реквизит объекта. Для этого
1. Очищаем "Значение" в редакторе ХЗ 
![image](https://github.com/user-attachments/assets/3d6eff43-68fa-4fdc-b000-b992a7c9f5ce)
2. Открываем выбор типов и там в меню "Значение из строки - Внутр" 
![image](https://github.com/user-attachments/assets/f4df0a7f-9645-4615-9480-199ae12014e3)
3. Вставляем содержимое буфера 
![image](https://github.com/user-attachments/assets/e56b6e23-4352-4efb-ba9a-2defdccab132)
4. Внизу получаем сообщение об ошибке:
> Десериализован объект недопустимого для приемника типа (Настройки компоновки данных)

**Ожидаемое поведение**
Ожидал, что загружаемые настройки преобразуются в ХЗ для последующего помещения в реквизит объекта.

P.S. Если попробовать загрузить таблицу значений из строки внутр, то ошибки не возникает и оно нормально схлопывается в ХЗ

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/989179

**Comment by tormozit** [comment]
Сделано в 7.36

**Comment by JohnyDeath** [comment]
Работает. Спасибо!
