### ISSUE TITLE
Консоль запросов. Ошибка при попытке пересоздать временные таблицы внешних источников данных

### ISSUE THREAD

**Issue by JohnyDeath** [tormozit/RDT1C#616]
**Программное окружение**

Платформа: 8.3.24.1368
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия предприятия КОРП, редакция 3.0. БитФинанс (3.0.152.28/3.1.59.8)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.35.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да

**Воспроизведение проблемы**
1. В консоли запросов создать запрос к внешнему источнику данных (ВИД), где будет создаваться временная таблица. Пример
```
//{Запрос: 0, -2 ////////////////////////////////////////
ВЫБРАТЬ ПЕРВЫЕ 10
	АвтомобилиТ.id КАК id,
	АвтомобилиТ.ГосНомер КАК ГосНомер
ПОМЕСТИТЬ ВнешнийИсточникДанных.Dox.ВременнаяТаблица.втАвтомобили
ИЗ
	ВнешнийИсточникДанных.Dox.Таблица.Автомобили КАК АвтомобилиТ
;
//{Запрос: 1, -1 ////////////////////////////////////////
ВЫБРАТЬ
	втАвтомобили.ГосНомер КАК ГосНомер
ИЗ
	ВнешнийИсточникДанных.Dox.ВременнаяТаблица.втАвтомобили КАК втАвтомобили

```
2. Выполнить запрос
3. Через какое-то время появится ошибка:

> Ошибка при вызове метода контекста (ВыполнитьПакет)
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(3674)}:РезультатПакета = мОбъектЗапроса.ВыполнитьПакет();
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольЗапросов.Форма.Форма.Форма(1739)}:ПересоздатьМенеджерВременныхТаблиц(Ответ = "Очистить");
> 
> [ОшибкаВоВремяВыполненияВстроенногоЯзыка]
> по причине:
> {(1, 1)}: Ожидается выражение "ВЫБРАТЬ"

и в строке сообщения видим:

> Временные таблицы внешних источников удалены, т.к. их пересоздание не реализовано

Если оставить такую консоль на длительное время, то ошибок также прибавиться.

**Ожидаемое поведение**
Тут два варианта:
1. Не пытаться что-то делать с временными таблицами ВИД, если работа с их пересозданием не реализовано. Просто чтобы ошибка не выпадала
2. Реализовать пересоздание временных таблиц ВИД

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/989182

**Comment by tormozit** [comment]
Исправлено в 7.36

**Comment by JohnyDeath** [comment]
Спасибо
