### ISSUE TITLE
Локализация "вид параметра" в консоли запроса

### ISSUE THREAD

**Issue by marv-ua** [tormozit/RDT1C#617]
**Программное окружение**
Платформа: 8.3.19.1529
Режим БД: клиент-серверный
Конфигурация. Название: Business automation software for accounting (2.1.16.1)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_12
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 300
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.36.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.36.1e)
Расширения. ЗапуститьСеансПользователя (2.0)
Расширения. ОграничениеДоступа ()
Расширения. БлокировкаУдобнее (1.2)
Расширения. МониторингОбменаБСП (21.01.06)
Расширения. HF ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: uk
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2019 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Microsoft Windows Server 2019 Standard 64-bit Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

Получить эту информацию можно кнопкой "Техническая информация" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. На вкладке параметры в списке параметров выбираю "вид "
![image](https://github.com/user-attachments/assets/90172ac1-388a-49f3-8643-dd4f09151bbf)
Также не отображается текущий "вид"

Язык Украинский

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/989688

**Comment by tormozit** [comment]
Исправлено в 7.37
