### ISSUE TITLE
Консоль компоновки данных. Не работает кнопка скрытия настроек

### ISSUE THREAD

**Issue by froloid** [tormozit/RDT1C#618]
**Программное окружение**

Платформа: 8.3.21.1302
Режим БД: клиент-серверный
Конфигурация. Название: 1С-Логистика: Управление складом 3.0 (Линда) (3.0.10.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_8
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 7.16.1p
Инструменты разработчика. Инструмент: Консоль компоновок данных
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс

**Воспроизведение проблемы**
1. Открыл консоль компоновки данных;
2. Нажал кнопку "Настройки" на главной панели инструмента;
3. Ни чего не произошло.

**Ожидаемое поведение**
При нажатии данной кнопки должна скрываться/отображаться верхняя часть формы, содержащая в в том числе настройки отчёта. Желательно повестить на эту кнопку сочетание клавиш Ctrl+D как в консоли запросов.

Аналогичное поведение желательно реализовать и в консоли кода. Сейчас там вообще нет кнопки "Настройки". При этом при анализе кода (особенно актуально после того как появились алгоритмы с типом Модуль) часть хочется использовать для этого максимальную часть экрана.

**Comment by tormozit** [comment]
Не удалось воспроизвести. Скорее всего имеет место поломка привязок в конкретной сохраненной настройке окна. Используй системную команду "Восстановить положение окна" для сброса этой настройки.

Если не поможет. Запиши видео, начиная с запуска приложения и до нажатия на кнопку. Желательно также показать в нем и вызов команды "Восстановить положение окна".

**Comment by froloid** [comment]
> Если не поможет. Запиши видео,


https://github.com/user-attachments/assets/d254c817-ede3-48ac-b3a6-455488d25a00

**Comment by tormozit** [comment]
Попробуй после команды "Восстановить положение окна" (Alt+Shift+R), максимизировать то же окно и затем восстановить его обычные размеры.

**Comment by froloid** [comment]
Не помогает. Под "восстановить его обычные размеры" я так понял "минимизировать". В моих сценариях обычным размером является как раз максимизированное состояние. Но в любом случае не срабатывает. Трюк с восстановлением положения я часто использую в консоли запросов, когда там едет окно с результатами (ограничивается не всей шириной формы, а её частью примерно в 2/3).

**Comment by froloid** [comment]
В общем нашёлся обход. Положение кнопки фиксированное. По умолчанию настройки отображаются. Если нажать кнопку, то ни чего не меняется, но после "восстановить положение окна" они скрываются. Дальше по нажатию кнопки они отображаются без "восстановить положение окна". Если потом нажать опять не скрываются, но после восстановления скрываются. И так по циклу. 

В итоге на свою боль я нашёл костыль. Но хорошо бы понять, что у меня не так. Потому что такое поведение и в варианте внешней обработки и в варианте расширения, на разных инфраструктурах (у разных клиентов) в разных базах.

**Comment by froloid** [comment]
В принципе в моём посыле можно задачу закрывать. Но в идеале добавить для кнопки сочетание Ctrl+D по аналогии с результатов в консоли запросов (и консоли кода так же как я писал в изначальном описании).

**Comment by tormozit** [comment]
"восстановить его обычные размеры" это отдельная стандартная кнопка в любом разворачиваемом окне

![изображение](https://github.com/user-attachments/assets/bd57bbd4-ca93-4f5e-8416-f22785c98f55)

По сочетанию клавиш создал задачу https://www.hostedredmine.com/issues/989937

**Comment by tormozit** [comment]
Сделано в 7.38
