### ISSUE TITLE
Подбор и обработка объектов. Не работает сочетание F7 для кнопки "Заполнить строки"

### ISSUE THREAD

**Issue by froloid** [tormozit/RDT1C#619]
**Программное окружение**

Платформа: 8.3.21.1302
Режим БД: клиент-серверный
Конфигурация. Название: 1С-Логистика: Управление складом 3.0 (Линда) (3.0.10.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_8
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 7.16.1p
Инструменты разработчика. Инструмент: Консоль компоновок данных
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс

**Воспроизведение проблемы**
1. Открыл инструмент ПиОО
2. Нажал клавишу F7
3. Ни чего не произошло. Хотя у кнопки "Заполнить строки" в подсказке указано, что быстрая клавиша F7

**Ожидаемое поведение**
По нажатию F7 должен сработать обработчик нажатия кнопки "Заполнить строки".

**Comment by tormozit** [comment]
Проблему воспроизвел https://www.hostedredmine.com/issues/946737

**Comment by tormozit** [comment]
Исправлено в 7.37

**Comment by froloid** [comment]
Установил 7.37.2р, но по F7 всё равно ни чего не происходит:

Платформа: 8.3.21.1302
Режим БД: клиент-серверный
Конфигурация. Название: 1С-Логистика: Управление складом 3.0 (Линда) (3.0.10.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_8
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 7.37.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс

**Comment by froloid** [comment]
Навёл мышку на кнопку и увидел, что вместо запрошенных F7 в подсказке сочетание клавиш Ctrl+Enrer - оно действительно работает. Это принципиальнее? Всё таки для ИР F7 более нативно, чем Ctrl-Enter из типовых отчётов. И консоли запросов и в консоли СКД получение результатов по F7  реализовано.

**Comment by tormozit** [comment]
У кнопки по умолчанию (жирный шрифт) платформа не позволяет менять сочетание клавиш.
