### ISSUE TITLE
Удаление с контролем ссылок. Общие модули без флажка Клиент (обычное приложение) препятствуют подбору

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#62]
https://user-images.githubusercontent.com/87958986/133471138-df320ea9-72ff-421f-a6d2-3e8f82166995.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

Платформа: 8.3.19.1229
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.09.1p
Инструменты разработчика. Инструмент: Удаление объектов с контролем ссылок
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

В 1С:ERP Управление предприятием 2 (2.5.6.261) есть модуль Заполнение7РазделаДекларацииПоНДСПереопределяемый без флажка Клиент (обычное приложение), который препятствует поиску помеченных на удаление объектов. Возможно это обойти как-то через вызов поиска на сервере?

```
{Документ.ФормированиеЗаписейРаздела7ДекларацииНДС.МодульМенеджера(21,2)}: Переменная не определена (Заполнение7РазделаДекларацииПоНДСПереопределяемый)
	<<?>>Заполнение7РазделаДекларацииПоНДСПереопределяемый.ЗапросПоДаннымЗаполнения7РазделаДекларацииПоНДС(

```

**Comment by tormozit** [comment]
Это - ошибка конфигурации. К сожалению платформа не позволяет отловить ошибки компиляции модулей попыткой. Поиск перенести на сервер можно но как всегда только в непортативных вариантах. Но и это не сильно поможет, т.к. проблема будет вылезать еще во многих других местах.

**Comment by tormozit** [comment]
Обойти эту проблему можно либо исправлением конфигурации либо переходом на вариант "Расширение" и использование режима запуска "Управляемое приложение"
