### ISSUE TITLE
Консоль компоновки данных. Отображение на вкладках настроек количества элементов

### ISSUE THREAD

**Issue by froloid** [tormozit/RDT1C#620]
Сейчас в настройках на различных закладках отображается количество элементов без учёта их активности (на скрине пример вкладки с отборами):
![2024-07-31_2-14-15](https://github.com/user-attachments/assets/9b3fc105-ebb5-44ad-8e6a-b272851fe1f3)

Хотелось бы оперировать именно количеством активных элементов. Так как только они воздействуют на результат. Поэтому либо в количестве элементов нужно сделать 0/2 (ноль из двух), либо (если места жаль) учитывать только активные.

**Comment by froloid** [comment]
Дополнение сюда же. Во вкладках, где названия обрезаются, всё равно хотелось бы видеть количество действующих элементов. На скрине пример с параметрами:
![image](https://github.com/user-attachments/assets/a26912df-d83b-4ed6-8b7c-79f99af3ccd7)

**Comment by tormozit** [comment]
> названия обрезаются, всё равно хотелось бы видеть количество

Платформа 1С не предоставляет таких возможностей.

**Comment by tormozit** [comment]
> активных элементов

Для информации. Наличие активных настроек каждого вида отображается в табличном поле структуры настроек. Причем в эти ячейки можно кликать для активации соответствующей вкладки настроек.

![изображение](https://github.com/user-attachments/assets/4033ff1b-2bc6-4702-8ca9-26dd2f7dc82d)

**Comment by tormozit** [comment]
С учетом наличия индикаторов наличия включенных настроек в каждой вкладке кажется ли тебе нужным видеть именно количество включенных? Если да, то поясни почему не хватает существующих индикаторов.

**Comment by froloid** [comment]
> С учетом наличия индикаторов наличия включенных настроек в каждой вкладке кажется ли тебе нужным видеть именно количество включенных?

Не обязательно. Буду ориентироваться на пиктограммы в дереве группировок.
