### ISSUE TITLE
Работа хотя бы основных инструментов в режиме внешней обработки управляемого приложения

### ISSUE THREAD

**Issue by froloid** [tormozit/RDT1C#621]
Часто приходится работать с базами клиентов, где не установлены ИР и нельзя добавлять собственные расширения. Иногда можно выкрутиться запуском базы в режиме обычного приложения и использовать портативную версию ИР. Но часто это не срабатывает, так как в конфигурации есть модули у которых нет опции компиляции на клиенте в режиме обычного приложения.

Ну и в принципе - это конечно долгий путь, но когда нибудь его нужно начинать.

В моей версии минимального набора основных инструментов - консоли запросов/СКД/кода, подбор и обработка объектов, навигационная панель.

**Comment by tormozit** [comment]
Такого развития не планируется.
