### ISSUE TITLE
Ошибка при попытке открыть Консоль запросов (и любой другой)

### ISSUE THREAD

**Issue by DJRelax** [tormozit/RDT1C#623]
**Программное окружение**

Платформа: 8.3.18.1563
Режим БД: клиент-серверный
Конфигурация. Название: Учет печатной продукции (1.1.24.225)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: АвтоматическийИУправляемый
Конфигурация. Режим совместимости: Версия8_3_15
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Конфигурация 7.39.1
Инструменты разработчика. Инструмент: Конструктор регулярного выражения
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: Локальный
Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открываю инструмент "Консоль запросов"
2. Получил окно с ошибкой `{ОбщийМодуль.ирОбщий.Модуль(31870,16)}: Переменная не определена (ирПлатформа)
		мПлатформа = <<?>>ирПлатформа;
`

**Ожидаемое поведение**
Открытая консоль запросов

**Comment by tormozit** [comment]
Не воспроизводится. В модулях приложения теперь нужно делать слияние при объединении конфигурации с подсистемой. Рекомендую перейти на вариант "Расширение", т.к. его проще обновлять.

**Comment by tormozit** [comment]
Ошибку для **портативного** варианта подтверждаю https://www.hostedredmine.com/issues/990592

**Comment by tormozit** [comment]
Для портативного варианта исправлено в 7.39.2

**Comment by ard-av** [comment]
![Screenshot_6](https://github.com/user-attachments/assets/63a842ec-e31f-4e35-9851-3fd9f51befa5)
вышло исправление 7.39.2
Ошибка та же при нажатии любого инструмента, в том числе на кнопку "О подсистеме"
{ОбщийМодуль.ирОбщий.Модуль(31871,16)}: Переменная не определена (ирПлатформа)
    мПлатформа = <<?>>ирПлатформа;
    
Временно починил у себя 
![Screenshot_7](https://github.com/user-attachments/assets/fb764076-e9d1-4454-bbe8-472f10f67663)
Пункт 5 прочитал, но ничего не понял https://devtool1c.ucoz.ru/news/obnovlen_porjadok_ustanovki_konfiguracii/2024-08-12-885
Клиент-Сервер, обычное приложение, cf-ка

**Comment by ard-av** [comment]
Спасибо, отбой. В группе подсказали что нужно сделать https://t.me/DevTool1C/26623

**Comment by DJRelax** [comment]
> Не воспроизводится. В модулях приложения ты забыл сделать слияние при объединении конфигурации с подсистемой. Рекомендую перейти на вариант "Расширение", т.к. его проще обновлять.

1. Я не знал что нужно слияние, раньше такого не было.
2. Обдумаю переход. У нас обычное приложение используется, надо посмотреть все ли будет нормально работать.

Спасибо, за подсказку.

**Comment by tormozit** [comment]
Про "ты забыл" я погорячился. Исправил то свое сообщение.
Пункт про слияние модулей приложения очень давно был удален из инструкции по установке. Но я периодически хотел его вернуть и сам забыл уже, что не вернул до сих пор. Ну и вот теперь уже точно вернул.
