### ISSUE TITLE
Ошибка при открытии консоли кода и попытке писать код

### ISSUE THREAD

**Issue by DJRelax** [tormozit/RDT1C#625]
**Программное окружение**

Платформа: 8.3.18.1563
Режим БД: клиент-серверный
Конфигурация. Название: Учет печатной продукции (1.1.24.226)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: АвтоматическийИУправляемый
Конфигурация. Режим совместимости: Версия8_3_15
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Конфигурация 7.39.2
Инструменты разработчика. Инструмент: Консоль кода
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открываем консоль кода
2. Получил окно с ошибкой `{Обработка.ирПлатформа.МодульОбъекта(6946)}: Преобразование значения к типу Число не может быть выполнено
				СтрокаОпределения.ТипЗначения = СтрокаОпределения.ТипЗначения + ", " + ТекстТипаЗначения; // TODO удаление дублей`
3. При попытке написать что либо в окне ввода кода
4. Получил окно с ошибкой `{Обработка.ирПлатформа.МодульОбъекта(6946)}: Преобразование значения к типу Число не может быть выполнено
				СтрокаОпределения.ТипЗначения = СтрокаОпределения.ТипЗначения + ", " + ТекстТипаЗначения; // TODO удаление дублей`

**Ожидаемое поведение**
Без ошибок

https://github.com/user-attachments/assets/d1dd9013-2233-40b8-bc30-4611d5d3640b

**Comment by tormozit** [comment]
Не удается воспроизвести. 
Остановись по ошибке в этой строке. Сообщи значения всех свойств объекта "СтрокаОпределения"

**Comment by DJRelax** [comment]
> Не удается воспроизвести. Остановись по ошибке в этой строке. Выражение "СтрокаОпределения.ТипЗначения" будет иметь числовое значение. Сообщи значения всех свойств объекта "СтрокаОпределения"

Извиняюсь, вчера не получилось сделать.

В "СтрокаОпределения.ТипЗначения" = Неопределено
![image](https://github.com/user-attachments/assets/1ecfa4b6-01e0-4067-aba5-a26920596a94)

В самой строке ТЗ(СтрокаОпределения) в данный момент описание экспортной процедуры модуля обычного приложения.
Эта процедура есть в конфигураторе.
![image](https://github.com/user-attachments/assets/a23ff099-fb63-4065-b825-103796c70d80)

Ну и в ТекстТипаЗначения из строки с ошибкой, комментарий из имени процедуры 
![image](https://github.com/user-attachments/assets/caa2b083-af7f-4173-8860-0d80b452a194)

Скрин самой процедуры:
![image](https://github.com/user-attachments/assets/33a012d5-9409-4dbb-b7da-2b2f0e0c5d3a)

При очистке кеша приложения, соответственно ошибок нет.
Кэш приложения обновляю через конфигуратор.
Через автономный сервер не хочет, но это проблема из другой истории и скорее всего в моей системе платформ, буду пока сам разбираться.

Заранее спасибо!

**Comment by DJRelax** [comment]
> Не удается воспроизвести. Остановись по ошибке в этой строке. Сообщи значения всех свойств объекта "СтрокаОпределения"

Извиняюсь, вчера не получилось сделать.

В "СтрокаОпределения.ТипЗначения" = Неопределено
![image](https://github.com/user-attachments/assets/1ecfa4b6-01e0-4067-aba5-a26920596a94)

В самой строке ТЗ(СтрокаОпределения) в данный момент описание экспортной процедуры модуля обычного приложения.
Эта процедура есть в конфигураторе.
![image](https://github.com/user-attachments/assets/a23ff099-fb63-4065-b825-103796c70d80)

Ну и в ТекстТипаЗначения из строки с ошибкой, комментарий из имени процедуры 
![image](https://github.com/user-attachments/assets/caa2b083-af7f-4173-8860-0d80b452a194)

Скрин самой процедуры:
![image](https://github.com/user-attachments/assets/33a012d5-9409-4dbb-b7da-2b2f0e0c5d3a)

При очистке кеша приложения, соответственно ошибок нет.
Кэш приложения обновляю через конфигуратор.
Через автономный сервер не хочет, но это проблема из другой истории и скорее всего в моей системе платформ, буду пока сам разбираться.

Заранее спасибо!

**Comment by DJRelax** [comment]
Извиняюсь, нечаянно нажал закрыть ветку.
И открыть ее не получается.

**Comment by tormozit** [comment]
Нужен полный текст метода

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/990738
Для ее обхода нужно удалить комментарий после слова "Экспорт".
В будущем старайся предоставлять исходный код **текстом**.

**Comment by tormozit** [comment]
Исправлено в 7.40
