### ISSUE TITLE
Конструктор запросов ИР ломает длинные псевдонимы при отключении Автополя

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#626]
https://github.com/user-attachments/assets/94af3a44-e4a5-4b71-b822-7852e9beec46

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.38.1p
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Написать запрос содержащий длинные Псевдонимы
```ВЫБРАТЬ
    1 КАК МоеДлиннооооооооооооооооооооооооооооооооооооооооооооооеПоле
ПОМЕСТИТЬ ВтДанные
;
ВЫБРАТЬ
    *
ИЗ
    ВтДанные КАК Т
```
3. Вызвать Конструктор Запросов ИР и отключить "Автополе"
4. После этого запрос превращается в такой:
```//{Запрос: 0, -2 ////////////////////////////////////////
ВЫБРАТЬ
	1 КАК МоеДлиннооооооооооооооооооооооооооооооооооооооооооооооеПоле
ПОМЕСТИТЬ ВтДанные
;
//{Запрос: 1, -1 ////////////////////////////////////////
ВЫБРАТЬ
	Т.МоеДлиннооооооооооооооооооооооооооооооооооооооооооооооеПоле КАК МоеДлинноооооооооооооооооооооооооооооооооооооооооо
ИЗ
	ВтДанные КАК Т
```

**Comment by tormozit** [comment]
В твоем текстовом описании шагов поломки нет. На видео поломку вижу.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/990708

**Comment by tormozit** [comment]
Исправлено в 7.40
