### ISSUE TITLE
Конструктор запросов. Автоподсказка. Поле объекта не обнаружено (ТаблицаТипов)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#628]
https://github.com/user-attachments/assets/e5ab966d-a7d5-4368-a9df-f70ce7d52fd4

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.38.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При вводе запроса после нажатия пробела после подстроки "КАК" выдается ошибка вместо подсказки:
```
ВЫБРАТЬ
	*
ИЗ
	РегистрБухгалтерии.Хозрасчетный.ОстаткиИОбороты(&НачалоПериода {&НачалоПериода}, &КонецПериода {&КонецПериода}) КАК 
```
![image](https://github.com/user-attachments/assets/19056813-9b6f-4d78-8439-db8447fedce6)
```
Поле объекта не обнаружено (ТаблицаТипов)
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(7667)}:					НайденныеСтроки[0].ТаблицаТипов = ТаблицаТипов;   
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(11481)}:					мПлатформа.ДобавитьВТаблицуСлов(ТаблицаСлов, ирОбщий.СтрСоединитьЛкс(Фрагменты, ""), "Свойство",, "", "Локальный");
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(11131)}:		Успешно = ЗаполнитьТаблицуСлов(ТаблицаТиповКонтекста,, ЕстьЛучшееСлово, Модально,, Не ЛиАвтовызов);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1422)}:			ОткрытьАвтодополнение(КодКлавиши, Не ЗначениеЗаполнено(КодКлавиши));
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(748)}:		ВыполнитьКоманду("ОткрытьАвтодополнение", мКодКлавишиОткрытияАвтодополнения, Ложь);
{(1)}:ОписаниеОповещения.Модуль.ОткрытьАвтодополнениеПассивно()
{ВнешняяОбработка.ирКлиент.МодульОбъекта(2094)}:	Выполнить("ОписаниеОповещения.Модуль" + "." + ОписаниеОповещения.ИмяПроцедуры + "()");
{(1)}:ирКлиент.ВыполнитьМетодМодуляЛкс(ПараметрыОбработчикаОжидания)
{ВнешняяОбработка.ирКлиент.МодульОбъекта(2083)}:	Выполнить(ПараметрыОбработчикаОжидания.ИмяМетода + "(ПараметрыОбработчикаОжидания)");
{ВнешняяОбработка.ирКлиент.МодульОбъекта(2078)}:	ОбработчикОжиданияСЯвнымиПараметрамиЛкс(ПараметрыОбработчикаОжидания);
{ВнешняяОбработка.ирПортативный.МодульОбъекта(360)}:	ирКлиент.ОбработчикОжиданияСПараметрамиЛкс();
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/990707

**Comment by tormozit** [comment]
Исправлено в 7.40
