### ISSUE TITLE
Загрузка табличных данных. Ошибка при смене типа

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#63]
https://user-images.githubusercontent.com/87958986/133641361-e0cc48d7-cbde-444f-9df4-30bd77d62e2c.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.1p
> Инструменты разработчика. Инструмент: Загрузка табличных данных
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При многократной Загрузке табличных данных ломается смена типа на вкладке Конвертация значений.

```
Ошибка при вызове метода контекста (Индекс)
{ВнешняяОбработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(264)}:		НоваяСтрока = ЭлементыФормы.Коллекция.Значение.Получить(КоллекцияИсточник.Индекс(СтрокаИсточника) + ИндексПервойСтроки);
{ВнешняяОбработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(178)}:			СтрокаПриемник = НайтиСтрокуИзИсточника(ВыделеннаяСтрока, ТабличноеПоле, КоллекцияИсточник, ИндексПервойСтроки);
{ВнешняяОбработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(285)}:		УстановитьРедактируемоеЗначение(НачальноеЗначениеВыбора, ПараметрТабличноеПоле);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(21399)}:			РезультатВыбора = ФормаРедактирования.ОткрытьМодально();
{ВнешняяОбработка.ирЗагрузкаТабличныхДанных.Форма.Форма.Форма(811)}:	Если ирОбщий.ОткрытьЗначениеЛкс(ТаблицаЗначений, Истина,, Заголовок,,, ЭлементыФормы.ТаблицаЗначений) Тогда 
{ВнешняяОбработка.ирЗагрузкаТабличныхДанных.Форма.Форма.Форма(1227)}:			РедактироватьТаблицуЗначений(ВыбраннаяСтрока.ИмяКолонкиПриемника, "Приемник");
{ВнешняяОбработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(847)}:		РезультатКонвертации = Форма.ОткрытьМодально();
по причине:
Несоответствие типов (параметр номер '1')

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/933656

**Comment by tormozit** [comment]
Исправлено в 6.09.3
