### ISSUE TITLE
Консоль запросов. Не работает сочетание клавиш обратного перехода после F12.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#630]
https://github.com/user-attachments/assets/2c04dcc0-6186-438c-855e-c8d66f4ff893

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: 
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В консоли запросов жму горячую клавишу F12 для перехода к определению временной таблицы
2. После перехода жму Ctr+- (Control + Minus) (пробовал оба варианта минуса, слева и справа)
3. Обратно курсор не переходит.
4. При этом если вызывать команду мышкой, то все работает.

Текст запроса:
```
//{Запрос: 0, -3 ////////////////////////////////////////
ВЫБРАТЬ
	1 КАК Поле1
ПОМЕСТИТЬ ВтДанные
;
//{Запрос: 1, -2 ////////////////////////////////////////
ВЫБРАТЬ
	1 КАК Поле1
ПОМЕСТИТЬ ВтДанные2
;
//{Запрос: 2, -1 ////////////////////////////////////////
ВЫБРАТЬ
	ИСТИНА КАК Поле1
ГДЕ 1 В (
	ВЫБРАТЬ
		ВтДанные.Поле1 КАК Поле1
	ИЗ
		ВтДанные КАК ВтДанные
	ОБЪЕДИНИТЬ ВСЕ
	ВЫБРАТЬ
		ВтДанные2.Поле1 КАК Поле1
	ИЗ
		ВтДанные2 КАК ВтДанные2)
```
---
UPDATE:
Разобрался. Работает через **Правый** Control и только с минусом **на числовом ряде.**

**Comment by tormozit** [comment]
Уточню в подсказке про правый Control. Вообще у меня так все сочетания клавиш обрабатываются, которые идут в обход платформы - используется та клавиша модификатора, которая ближе физически на клавиатуре к основной клавише сочетания.

**Comment by tormozit** [comment]
Подсказку улучшил в 7.40
