### ISSUE TITLE
Команда Форматировать

### ISSUE THREAD

**Issue by dmitri-0** [tormozit/RDT1C#631]
![image](https://github.com/user-attachments/assets/f88458d3-2682-417d-806d-cec2c3b8e504)

Изменить код программы.
```1c-enterprise
СерияПустыхСтрок > КоличествоПустыхСтрокПользователя 
``` 
Вывести на форму поле Количество пустых строк. 
Например, я хочу 0.

**Comment by tormozit** [comment]
Создал задачу для более агрессивного сжатия пустых строк https://www.hostedredmine.com/issues/990882

**Comment by tormozit** [comment]
Сделано в 7.40
