### ISSUE TITLE
Таблица значений. Поле не обнаружено "Строки"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#633]
https://github.com/user-attachments/assets/9158031c-4154-4aa4-bf16-0d76fea31b5c

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: 
Инструменты разработчика. Инструмент: Таблица значений
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Если в пустой Таблице Значений вызвать команду "Свернуть остальные", то выходит ошибка:

```
Поле объекта не обнаружено (Строки)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(10380)}:	МассивСтрок = СтрокаИлиДеревоЗначений.Строки.НайтиСтроки(Новый Структура(Идентификатор, Неопределено), Истина);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(12405)}:	ВсеСтрокиДерева = ирОбщий.ВсеСтрокиДереваЗначенийЛкс(ТабличноеПоле.Значение);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(18543)}:				ТабличноеПолеДеревоЗначений_СвернутьВсеСтрокиЛкс(ИсточникДействий, Истина);
{ВнешняяОбработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(820)}:	ирКлиент.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(5216)}:			РезультатВыбора = выхФорма.ОткрытьМодально();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(5985)}:		Результат = ОткрытьЗначениеЛкс(РасширенноеЗначение, РедактированиеРазрешено, СтандартнаяОбработка, Заголовок,, ПринудительноВОтдельнойФорме,, ТабличноеПоле, СтрокаПоиска, КлючУникальности);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(6144)}:				ЗначениеИзменено = ЯчейкаТабличногоПоляРасширенногоЗначения_ВыборЛкс(ЭтаФорма, ТабличноеПоле, СтандартнаяОбработка, РасширенноеЗначение, Истина, Истина, Данные, Заголовок, СтрокаПоиска) Или ЗначениеИзменено;
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(4097)}:	Если ирКлиент.ПолеВводаКолонкиРасширенногоЗначения_НачалоВыбораЛкс(ЭтаФорма, ЭлементыФормы.Параметры, СтандартнаяОбработка, , ИспользоватьОграничениеТипа) Тогда 

```

**Comment by tormozit** [comment]
Исправлено в 7.41
