### ISSUE TITLE
Конструктор запросов ИР. Отбор. Индекс находится за границами массива

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#634]
https://github.com/user-attachments/assets/9191d294-a7fa-4758-abdd-98976cf52b25

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: 
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При вызове "Конструктора запросов ИР" на тексте запроса:
```
ВЫБРАТЬ ПЕРВЫЕ 1 1 КАК Поле ИЗ РегистрБухгалтерии КАК РегистрБухгалтерии
```
И переходе на вкладку "Отбор" выдается ошибка: 

```
Индекс находится за границами массива
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(4664)}:	СтрокаПапки = ТабличноеПолеПолей.Значение.Элементы[0];
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(4642)}:			РазвернутьЕдинственнуюПапкуДоступныхПолей(ЭлементыФормы.ДоступныеПоляУсловия);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(4621)}:	ПанельЧастиОбновитьТекущуюСтраницу();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4526)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1452)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1401)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(324)}:		Результат = Компонента.Нажатие(Кнопка);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/990895

**Comment by tormozit** [comment]
Исправлено в 7.41
