### ISSUE TITLE
Редактор пользователей ИР. Менеджер табличного поля. Значение не является значением объектного типа (ПолноеИмя)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#635]
https://github.com/user-attachments/assets/a8262f9d-33d5-4742-97f8-1b9dbcfcf803

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: 
Инструменты разработчика. Инструмент: Редактор пользователей
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При вызове "Менеджера табличного поля" в Редакторе пользователей ИР возникает ошибка:

```
Значение не является значением объектного типа (ПолноеИмя)
{ВнешняяОбработка.ирПлатформа.Форма.МенеджерТабличногоПоля.Форма(212)}:		ЭтаФорма.ПолноеИмяМД = СтруктураТипаМетаданных.Метаданные.ПолноеИмя();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(18823)}:	ФормаМенеджера.УстановитьСвязь(ТабличноеПоле, , АктивизироватьСтраницу, МетаданныеВыбора);
{ВнешняяОбработка.ирПортативный.МодульОбъекта(628)}:	ирКлиент.ОткрытьМенеджерТабличногоПоляЛкс(, Параметры.Форма);
{(1)}:ирПортативный.ОткрытьМенеджерТабличногоПоляАктивнойФормыЛкс(ПараметрыВызова)
{ВнешняяОбработка.ирПлатформа.Форма.ГлобальноеМеню.Форма(730)}:	Выполнить("ирПортативный." + ЭлементыФормы.Команды.ТекущаяСтрока.Имя + "(ПараметрыВызова)"); // Так окно в управляемом приложении откроется в режиме блокирования владельца
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/991235

**Comment by tormozit** [comment]
Исправлено в 7.41
