### ISSUE TITLE
Конструктор запросов ИР. Предупреждение о большом количестве типов входящих в поле.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#636]
Хочется в Конструкторе запросов ИР сделать проверку, что в запросе используется выражение с использованием составного типа, которое может приводить к неявному формированию множества левых соединений. Например:

```
ВЫБРАТЬ ПЕРВЫЕ 10
	Т.Ссылка.Номер,
	Т.Ссылка.Дата
ИЗ
	РегистрСведений.РеестрДокументов КАК Т
```

![image](https://github.com/user-attachments/assets/fd1c8198-ccbe-46d8-a69d-083745adc81f)

**Comment by tormozit** [comment]
Не понял в какой момент ты хочешь проверку и в каком виде отображать результаты и по какому принципу проверять (больше 2-3-10-100 типов?). Пока слишком расплывчато.

**Comment by PerlAmutor** [comment]
> Не понял в какой момент ты хочешь проверку и в каком виде отображать результаты и по какому принципу проверять (больше 2-3-10-100 типов?). Пока слишком расплывчато.

Можно реализовать например таким образом:
- проверку осуществлять в тот же момент, что и проверка на разные синонимы в текстах объединения
- сделать отдельную вкладку (страницу) - "Предупреждения"
- сделать интерактивную настройку "Порог срабатывания", список значений с вариантами: ">=5", ">=15", и возможность пользователю самому выбрать конкретное значение. По-умолчанию выставить ">=15".
- сделать флажок "дополнительные проверки", чтобы проверка не выполнялась, если это замедляет
- на вкладку предупреждения можно выводить информацию еще и по различным синонимам в запросе через "ОБЪЕДИНИТЬ ВСЕ", сейчас эта проверка выводит информацию в окно сообщений. Вместо этого можно было бы писать что-то типа "Обнаружены возможные проблемы с текстом запроса, см. на вкладку "Предупреждения""

**Comment by tormozit** [comment]
В конструкторе не реализовано универсальных ссылок на выражения. Поэтому выявить такие выражения будет намного проще, чем сделать их открытие из списка предупреждений. Малыми усилиями могу сделать только выброс исключения при на первом же обнаруженном выражении по кнопке "Выполнить все проверки". Но кажется что это будет не достаточно удобно. Поэтому пока отложу эту задачу.

**Comment by tormozit** [comment]
Предположим такая таблица предупреждений появилась. Какие решения она поможет принимать?

**Comment by PerlAmutor** [comment]
> Предположим такая таблица предупреждений появилась. Какие решения она поможет принимать?

По возможности сократить количество типов через доработку текста запроса путем использования конструкции "ВЫБОР КОГДА... ВЫРАЗИТЬ()" там где это допустимо, что может оказать благоприятное воздействие на производительность запроса. Как вариант - пересмотреть реализацию запроса и использовать другие поля и таблицы. В том числе это позволит предотвратить попытку запуска такого запроса на проде, т.к. будет большая вероятность того, что сеанс придется убивать.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/992188

**Comment by tormozit** [comment]
Сделано в 7.44

**Comment by PerlAmutor** [comment]
Спасибо!
