### ISSUE TITLE
Подсказка в консоли кода полей создаваемой в запросе виртуальной таблицы

### ISSUE THREAD

**Issue by froloid** [tormozit/RDT1C#638]
Тут должны в подсказке выходить все поля втРазрезы (сейчас выходит только Организация и это по тому, что я её уже в ручную в предыдущем условии соединения прописал:
![image](https://github.com/user-attachments/assets/6be4a5dc-7438-4b6b-84ac-9443cd858018).

Версия инструментов от куда картинка Расширение 7.41.1e.

**Comment by tormozit** [comment]
Нужен текст полный алгоритма

**Comment by tormozit** [comment]
Укажи полные имена поле в первом запросе. Тогда анализатор их увидит.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/992189

**Comment by tormozit** [comment]
Сделано в 7.44
