### ISSUE TITLE
Консоль кода. Отключить сообщения о 

### ISSUE THREAD

**Issue by froloid** [tormozit/RDT1C#639]
Отключить (дать возможность отключать) вывод сообщений вида "Параметр [ИмяПараметра] на выходе имел мутабельное значение ([ТипЗначенияПараметра) и был очищен"
![image](https://github.com/user-attachments/assets/12ba4e70-c262-440c-9884-8695d4f664a9)

А лучше писать это в его значение, или какой-то пиктограммой с подсказкой отображать в списке.

**Comment by tormozit** [comment]
Зачем это нужно? Какие неудобства вызывает? Желательно указывать текста кода для примера.

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/991933

**Comment by tormozit** [comment]
Сделано в 7.43
