### ISSUE TITLE
Консоль запросов. Дерево связей. Не видит объявление Поле1, если не задан псевдоним основной таблицы

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#642]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.43.1p
Инструменты разработчика. Инструмент: Поле текста программы
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Ввел текст запроса:
```
ВЫБРАТЬ
	1 КАК Поле1
ПОМЕСТИТЬ ВтДанные
;
ВЫБРАТЬ
	Поле1
ИЗ
	ВтДанные
```
2. Установил курсор на "Поле1" во втором запросе
3. Вызвал команду Alt+F12
4. В открывшемся диалоге не вижу ссылок на поле
5. Если поменять запрос таким образом, то связь появляется

```
ВЫБРАТЬ
	1 КАК Поле1
ПОМЕСТИТЬ ВтДанные
;
ВЫБРАТЬ
	Т.Поле1
ИЗ
	ВтДанные КАК Т

```

![image](https://github.com/user-attachments/assets/46a26cb8-9454-477f-a4d8-41924e6b959a)

**Comment by tormozit** [comment]
Так и задумано. Укажу более явно это ограничение. Теперь в окне будет отображаться постоянно подсказка:
_Связь с полем выявляется при наличии явного псевдонима (через КАК) у него и у временной таблицы_
