### ISSUE TITLE
Консоль запросов. Дерево связей. Неопределено. Текущая строка.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#646]
https://github.com/user-attachments/assets/c3747a7a-24d3-4c27-a80e-3ffbf5690051

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.43.1p
Инструменты разработчика. Инструмент: Поле текста программы
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Консоли Запросов вызвал "Дерево связей" установив курсор на значение поля "НЕОПРЕДЕЛЕНО"
2. Получил ошибку:

```
Ошибка при установке значения атрибута контекста (ТекущаяСтрока)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(19)}:	ЭлементыФормы.ДеревоВызовов.ТекущаяСтрока = ДеревоВызовов.Строки.Найти(ПараметрИндексТекущегоЗапроса, "ИндексЗапроса", Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(15492)}:	ДеревоСвязейПоля.Открыть();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1435)}:			ОткрытьДеревоСвязейПоля();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1403)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(324)}:		Результат = Компонента.Нажатие(Кнопка);
по причине:
Отсутствует ключ строки

```

**Comment by tormozit** [comment]
Исправлено в 7.44
