### ISSUE TITLE
Консоль запросов. Дерево связей. Установить граница выделения.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#647]
https://github.com/user-attachments/assets/e382383b-ccb4-4efc-b2c5-e46a77b39533

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.43.1p
Инструменты разработчика. Инструмент: Поле текста программы
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Консоли Запросов вызвал "Дерево связей" для текста запроса:
```
//{Запрос: 0, -64 ////////////////////////////////////////
ВЫБРАТЬ
	1 КАК Поле1
ПОМЕСТИТЬ Вт_перв
;
//{Запрос: 5, -59 ////////////////////////////////////////
ВЫБРАТЬ
	ВТ_перв.Поле1
ПОМЕСТИТЬ ВТ_втор
ИЗ
	Вт_перв КАК ВТ_перв
;
//{Запрос: 6, -58 ////////////////////////////////////////
ВЫБРАТЬ
	ВТ_втор.Поле1 КАК Поле1
ПОМЕСТИТЬ ВТ_предв
ИЗ
	ВТ_втор КАК ВТ_втор
;
//{Запрос: 7, -57 ////////////////////////////////////////
ВЫБРАТЬ
	ВТ_предв.Поле1 КАК Поле1
ПОМЕСТИТЬ ВтДанные
ИЗ
	ВТ_предв КАК ВТ_предв
;
//{Запрос: 10, -54 ////////////////////////////////////////
ВЫБРАТЬ
	Т.Поле1 КАК Поле1
ПОМЕСТИТЬ ВТ_трет
ИЗ
	ВтДанные КАК Т
;
//{Запрос: 11, -53 ////////////////////////////////////////
ВЫБРАТЬ
	Т.Поле1 КАК Поле1
ПОМЕСТИТЬ ВТ_трет_2
ИЗ
	ВТ_трет КАК Т
;
ВЫБРАТЬ
	Т.Поле1 КАК Поле1
ИЗ
	ВтДанные КАК Т


```

3. Попытался раскрыть узел дерева и получил ошибку:

```
Ошибка при вызове метода контекста (УстановитьГраницыВыделения)
{ВнешняяОбработка.ирОболочкаПолеТекста.МодульОбъекта(93)}:			ЭлементФормы.УстановитьГраницыВыделения(НачальнаяСтрокаИлиПозиция, НачальнаяКолонкаИлиКонечнаяПозиция);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(6273)}:		ОболочкаПоля.УстановитьГраницыВыделения(ПозицияВМодуле, ПозицияВМодуле);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(6254)}:	НомерСтроки = ВыделениеДвумерноеИзПозиции(ПозицияВМодуле).КонечнаяСтрока;
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(191)}:	СтрокаМеста.НомерСтроки = НомерСтрокиИзПозиции(СтрокаМеста.Позиция + мПозицияТекстаДляПоискаОпределения);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(149)}:			УточнитьСтрокуРезультата(СтрокаВызова);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(209)}:	НайтиВходящие(Строка);
по причине:
Недопустимое значение параметра (параметр номер '1')
```

Причем если пропустить текст запроса через Конструктор Запросов ИР, то ошибка уходит.
Также ошибка уходит, если предварительно выделить раскрываемую строку

**Comment by tormozit** [comment]
Нужен текст запроса

**Comment by PerlAmutor** [comment]
> Нужен текст запроса

Обновил первое сообщение.

**Comment by tormozit** [comment]
Исправлено в 7.44
