### ISSUE TITLE
Консоль запросов. Дерево связей. Индекс находится за границами массива

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#648]
https://github.com/user-attachments/assets/be7cb036-2af4-44fc-838c-cfa1ad5220e7

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.43.1p
Инструменты разработчика. Инструмент: Поле текста программы
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Консоли Запросов ввел текст запроса:
```
ВЫБРАТЬ
	Т.Контрагент КАК Контрагент
ИЗ
	ВТ_Несуществующая КАК Т
```
3. Вызвал "Дерево связей" и получил ошибку:

```
Индекс находится за границами массива
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(6521)}:	мТекстБлока = ПакетЗапросов.ТекстыЗапросов[ИндексЗапроса];
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(190)}:	ЗагрузитьЗапросПакетаПоИндексу(ПакетЗапросов, ЭлементыФормы.ДеревоВызовов.ТекущаяСтрока.ИндексЗапроса);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(149)}:			УточнитьСтрокуРезультата(СтрокаВызова);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(209)}:	НайтиВходящие(Строка);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(46)}:	ЭлементыФормы.ДеревоВызовов.Развернуть(ДеревоВызовов.Строки[0]); 
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(42)}:	ОбновитьДанные();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(18)}:	ПеренестиВКорень(ПараметрИмяТаблицы, ПараметрПоле);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(15492)}:	ДеревоСвязейПоля.Открыть();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1435)}:			ОткрытьДеревоСвязейПоля();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1403)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(324)}:		Результат = Компонента.Нажатие(Кнопка);

```

**Comment by tormozit** [comment]
Исправлено в 7.44
