### ISSUE TITLE
Отладка не работает в клиент-серверном варианте

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#649]
Данные в "Информации для технической поддержки" не от клиент-серверной базы, просто указываю версию ИР.

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.43.1p
Инструменты разработчика. Инструмент: Функции режима отладки
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1.  В инструменте "Функции режима отладки" для Портативного варианта указан пример:
`
ВнешниеОбработки.Создать("C:\Users\user123\Downloads\7.43.1\ирПортативный.epf", Ложь).ирОбщий.*()
`
![image](https://github.com/user-attachments/assets/911ce29b-0002-4ba0-b914-bf684eb8cfaa)
Попробовал на сервере передать в таком варианте объект Запрос в функцию От(). Обработка не создалась. Почему, ведь в инструменте четко указано "Сервер"? Возможно пример для сервера должен выглядеть иначе?:
2. Сделал общую папку доступную с клиента и с сервера и вызывал обработку в таком формате:
ВнешниеОбработки.Создать("'\\\\server1\share\ИР\7.43.1\ирПортативный.epf", Ложь).ирОбщий.От(Запрос)
Снова ошибка. На этот раз на строке 871 обработки ирОбщий.epf
![image](https://github.com/user-attachments/assets/4c968552-0254-4e8c-9c06-17ce6456de4b)
Что-то вроде свойство "ирКэш.ЛиПортативныйРежимЛкс()" объекта не обнаружено.
3. Ок. Вызвал в таком формате (если что MarkDown в GitHub глючит и вставляет лишний опостроф):
`
ВнешниеОбработки.Создать("'\\server1\share\ИР\7.43.1\ирПортативный.epf", Ложь).ирОбщий.ОтладкаЛкс(Запрос)
`
И тогда заработало.
Раньше работало с таким вызовом до обновления обработки:
`
ВнешниеОбработки.Создать("'\\server1\share\ИР\7.43.1\ирПортативный.epf", Ложь).От(Запрос)
`
4. Попытался воспользоваться функцией помещения объекта отладки в Хранилище Общих Настроек. Но ничего не вышло, настройка серая, не доступна к изменению:
![image](https://github.com/user-attachments/assets/2b4da05d-31a9-4829-8708-2772b3c09936)

Соответственно проблемы 3. Почему не работает из локального каталога как указано в примере для клиент-серверной базы портативного инструмента. Почему не работает даже в сетевой папке. Почему не работает вариант помещения объекта в хранилище общих настроек (всегда сохраняет в сетевую шару) какой бы параметр я не передавал в функции.

**Comment by tormozit** [comment]
1. Портативный вариант имеет много ограничений при работе с сервером (в серверном контексте). Ты не указал описание ошибки. Поэтому могу лишь предположить, что ты указал клиентский путь к файлу в серверном контексте. В этом случае сервер естественно не увидит файл, если он на другом компьютере.

**Comment by tormozit** [comment]
2. Точный полный текст ошибки:
ВнешниеОбработки.Создать("C:\1C\Инструменты разработчика\Портативный\7.43.1\ирПортативный.epf", Ложь).ирОбщий.От(1)	
{ВнешняяОбработка.ирОбщий.МодульОбъекта(871)}: Значение не является значением объектного типа (ЛиПортативныйРежимЛкс)	

Метода ОтладкаЛкс нет в модуле ирОбщий. Есть метод ОтладитьЛкс.

**Comment by PerlAmutor** [comment]
> 1. Портативный вариант имеет много ограничений при работе с сервером (в серверном контексте). Ты не указал описание ошибки. Поэтому могу лишь предположить, что ты указал клиентский путь к файлу в серверном контексте. В этом случае сервер естественно не увидит файл.

Поэтому мне и не понятен пример вызова функции От() в инструменте "Функции режима для отладки". ИР видит, что я сижу в портативном варианте в клиент-серверной базе, почему он предлагает для функции с признаком "Сервер" вариант вызова из локальной папки?

> Метода ОтладкаЛкс нет в модуле ирОбщий. Есть метод ОтладитьЛкс.

Извиняюсь, писал по памяти. Но да, это она.

**Comment by tormozit** [comment]
2. Ошибку подтверждаю https://www.hostedredmine.com/issues/992183

**Comment by tormozit** [comment]
> почему он предлагает для функции с признаком "Сервер" вариант вызова из локальной папки?

А из какой ему предлагать папки? Если запустишь из сетевой, будет предлагать из сетевой. Кажется тут все логично. Других вариантов тут нет. Это - очередная плата за Портативный вариант.
Если хочешь удобно и понятно, используй вариант Расширение.

**Comment by tormozit** [comment]
4. Исправлю описание алгоритма сохранения снимка https://www.hostedredmine.com/issues/992184

**Comment by PerlAmutor** [comment]
> 4. Исправлю описание алгоритма сохранения снимка https://www.hostedredmine.com/issues/992184

>- вариант "Портативный" - делается попытка записи в отдельный файл в подкаталоге ОбъектыДляОтладки рядом с файлом внешней обработки, **иначе в единую для всех пользователей ячейку в хранилище общих настроек в БД**

Вот это описание мне вообще не понятно. Что означает "Иначе"? Вот мне как раз нужно, чтобы наступило "Иначе", хочу через хранилище общих настроек сделать. Какие действия я должен для этого совершить, отобрать у себя права на запись в сетевую папку оставив только просмотр?

> А из какой ему предлагать папки? Если запустишь из сетевой, будет предлагать из сетевой. Кажется тут все логично. Других вариантов тут нет. Это - очередная плата за Портативный вариант.
> Если хочешь удобно и понятно, используй вариант Расширение.

Понятно, что при таких обстоятельствах предлагать в качестве примера использовать локальную папку - нецелесообразно, не будет работать. Поэтому для серверных вызовов предлагаю писать что-то типа "\\имя_сервера\общая_папка\"

**Comment by tormozit** [comment]
> Что означает "Иначе"?

Означает "в случае неуспеха". Какой еще вариант трактовки тебе пришел на ум? Или предлагаешь сочинение писать на каждую функцию? 

> хочу через хранилище общих настроек сделать

Почему нужен именно он?

> Какие действия я должен для этого совершить

Ответ кажется очевидным - установить флажок "Только чтение" в свойствах папки.

**Comment by PerlAmutor** [comment]
> > Что означает "Иначе"?
> 
> Означает "в случае неуспеха". Какой еще вариант трактовки тебе пришел на ум? Или предлагаешь сочинение писать на каждую функцию?
> 
> > хочу через хранилище общих настроек сделать
> 
> Почему нужен именно он?
> 
> > Какие действия я должен для этого совершить
> 
> Ответ кажется очевидным - установить флажок "Только чтение" в свойствах папки.

Понятно. Хотел попробовать механизм через общие настройки, чтобы продемонстрировать коллеге у которого прав на папку нет в отличие от меня. Думал на это поведение можно влиять непосредственно из ИР, оказывается нельзя.

**Comment by tormozit** [comment]
> попробовать механизм через общие настройки, чтобы продемонстрировать коллеге у которого прав на папку нет в отличие от меня

"нет прав на папку", как следует из моего описания, приведет к тому, что написано после "иначе"

**Comment by tormozit** [comment]
Исправлено в 7.44
