### ISSUE TITLE
Таблица значений. Анализ данных. Двойное открытие.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#65]
https://user-images.githubusercontent.com/87958986/133649764-0766056e-5902-46e4-bda6-c2ceffc60790.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.1p
> Инструменты разработчика. Инструмент: Таблица значений
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При использовании команды Передать в Анализ Данных из ТЗ и последующем вызове команды "Анализ данных" в ТЗ возникает ошибка:

```
Ошибка при вызове метода контекста (ОткрытьМодально)
{ВнешняяОбработка.ирПлатформа.Форма.ТаблицаЗначений.Форма(1057)}:	РезультатФормы = ФормаАнализа.ОткрытьМодально();
по причине:
Невозможно открыть форму в модальном режиме, так как она уже открыта!

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/933639

**Comment by tormozit** [comment]
Исправлено в 6.10.1
