### ISSUE TITLE
Консоль запросов. Дерево связей. Ошибка при установке значения атрибута контекста (ТекущаяСтрока)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#652]
https://github.com/user-attachments/assets/4122409e-c8e3-4c98-9a89-55788e747695

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.44.1p
Инструменты разработчика. Инструмент: Поле текста программы
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. При попытке открыть новое окно из формы "Дерево связи" инструмента Консоль Запросов выдается ошибка:

![image](https://github.com/user-attachments/assets/1a3d9581-fe23-4ca6-9194-0824ef16e631)

```
Ошибка при установке значения атрибута контекста (ТекущаяСтрока)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(19)}:	ЭлементыФормы.ДеревоВызовов.ТекущаяСтрока = ДеревоВызовов.Строки.Найти(ПараметрИндексТекущегоЗапроса, "ИндексЗапроса", Истина);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(16682)}:	Результат.Открыть();
{ВнешняяОбработка.ирКлиент.МодульОбъекта(18441)}:		ОткрытьНовоеОкноФормыЛкс(ЭтаФорма);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.ДеревоСвязейПоля.Форма(75)}:	ирКлиент.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);
по причине:
Отсутствует ключ строки

```

**Comment by tormozit** [comment]
Исправлено в 7.44
