### ISSUE TITLE
Консоль запросов. Дерево связей. Ошибка при вызове метода контекста (Добавить). Неверное имя колонки.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#653]
https://github.com/user-attachments/assets/c6bbe204-66b3-4bea-afed-db3f1baee7ea

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.44.1p
Инструменты разработчика. Инструмент: Поле текста программы
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Встать на "Поле1" в последнем запросе и вызвать команду "Дерево связей" в Консоли Запросов

```
ВЫБРАТЬ
	1 КАК Поле1,
	ПОДСТРОКА(Т.Поле2, 1, 4) КАК Поле2
ПОМЕСТИТЬ ВтДанные
ИЗ
	&ТЗ КАК Т
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	Т.Поле1 КАК Поле1
ИЗ
	ВтДанные КАК Т
```
2. Выдается ошибка:

```
Ошибка при вызове метода контекста (Добавить)
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(4461)}:					ЗначениеПараметра.Колонки.Добавить(Вхождение.Группа0);
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(4525)}:		НовыйТекст = ДобавитьВременныеТаблицыПараметровВТекстЗапроса(Текст, ПостроительЗапроса.Параметры);
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(4431)}:	ПодготовитьМетаданныеПостроителяЗапроса(ПостроительЗапроса, ДержательМетаданных);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(6940)}:		ПостроительЗапроса = мПлатформа.ПостроительПакетаЗапросовДоИндекса(выхПакетЗапросовТекущий.ТекстыЗапросов, выхИндексЗапроса, выхПакетЗапросовТекущий.Параметры, ТекущееСлово, МенеджерВременныхТаблиц);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(6354)}:			НайтиЗапросВременнойТаблицы(ПоследнееОпределение,, ПакетЗапросов, ИндексЗапроса);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(15539)}:			ИмяТаблицы = НайтиОпределениеСлова(Фрагменты[0]);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1435)}:			ОткрытьДеревоСвязейПоля();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1403)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(324)}:		Результат = Компонента.Нажатие(Кнопка);
по причине:
Неверное имя колонки

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/992190

**Comment by tormozit** [comment]
Исправлено в 7.44.2

**Comment by PerlAmutor** [comment]
> ВЫБРАТЬ
> 	1 КАК Поле1,
> 	ПОДСТРОКА(Т.Поле2, 1, 4) КАК Поле2
> ПОМЕСТИТЬ ВтДанные
> ИЗ
> 	&ТЗ КАК Т
> ;
> 
> ////////////////////////////////////////////////////////////////////////////////
> ВЫБРАТЬ
> 	Т.Поле1 КАК Поле1
> ИЗ
> 	ВтДанные КАК Т

Теперь выдает другую ошибку:

```
Ошибка при вызове метода контекста (УстановитьГраницыВыделения)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(6371)}:						СлужебноеПолеТекстаДолгое.УстановитьГраницыВыделения(НачальнаяПозицияВхождения, НачальнаяПозицияВхождения + СтрДлина(ПоследнееОпределение));
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(15539)}:			ИмяТаблицы = НайтиОпределениеСлова(Фрагменты[0]);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1435)}:			ОткрытьДеревоСвязейПоля();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1403)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(324)}:		Результат = Компонента.Нажатие(Кнопка);
по причине:
Недопустимое значение параметра (параметр номер '1')

```

**Comment by tormozit** [comment]
Не воспроизводится. Скорее всего ты не сначала сеанса тестировал.
