### ISSUE TITLE
Консоль компоновки данных. Вывод в Дерево Значений. Метод объекта не обнаружен (Количество)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#654]
https://github.com/user-attachments/assets/0c3be2d6-5e77-418b-8158-6275250f9ace

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.44.1p
Инструменты разработчика. Инструмент: Консоль компоновок данных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Попробовал вывести результат .dcf файла из новой функции https://www.hostedredmine.com/issues/992181 в Дерево Значений
2. Получил ошибку

```
Метод объекта не обнаружен (Количество)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(18220)}:	Если (АнализируемыеКолонки.Количество() - ИменаНесужаемыхКолонок.Количество()) * ТаблицаДанных.Количество() > 10000 Тогда
{ВнешняяОбработка.ирОбщий.МодульОбъекта(23786)}:	СузитьТипыКолонокТаблицыБезПотериДанныхЛкс(КоллекцияВывода);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(23669)}:		ВывестиТаблицуКомпоновкиВКоллекциюЛкс(КоллекцияВывода, ПроцессорКомпоновкиДанных, ДанныеРасшифровки, ПоляИтогаТаблицыВКоллекцию);
{ВнешняяОбработка.ирКонсольКомпоновокДанных.МодульОбъекта(35)}:	РезультатВывода = ирОбщий.СкомпоноватьОтчетВКонсолиЛкс(КоллекцияВывода, МакетКомпоновкиДанных, СтруктураВнешниеНаборыДанных, Автофиксация, Параметры.МодальныйРежим, ЛиОтладка, АдресДанныхРасшифровки,
{(1)}:Обработка.ВывестиРезультат(ПараметрыЗадания)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(22875)}:		Результат = Вычислить("Обработка." + ИмяМетодаОбработки + "(ПараметрыЗадания)");
{ВнешняяОбработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(742)}:	Результат = ирОбщий.ВыполнитьЗаданиеФормыЛкс("ВывестиРезультат", ПараметрыЗадания, ЭтаФорма,,, ЭлементыФормы.КоманднаяПанельФормы.Кнопки.ВывестиВТаблицу, "ВывестиРезультатЗавершение",
{ВнешняяОбработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(638)}:	Результат = СкомпоноватьРезультатМой(, СтруктураВнешниеНаборыДанных,, Истина, МенеджерВременныхТаблиц);
{ВнешняяОбработка.ирКонсольКомпоновокДанных.Форма.Форма.Форма(1202)}:	Если ВыполнитьОтчет() Тогда

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/992191

**Comment by tormozit** [comment]
Исправлено в 7.44.2
