### ISSUE TITLE
Консоль запросов. Дерево связей. Ошибка при вызове метода контекста (УстановитьГраницыВыделения)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#655]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.44.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Встать на "Поле1" в последнем запросе и вызвать команду "Дерево связей" в Консоли Запросов

```
ВЫБРАТЬ
	1 КАК Поле1,
	ПОДСТРОКА(Т.Поле2, 1, 4) КАК Поле2
ПОМЕСТИТЬ ВтДанные
ИЗ
	&ТЗ КАК Т
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	Т.Поле1 КАК Поле1
ИЗ
	ВтДанные КАК Т
```
2. Выдается ошибка:

```
Ошибка при вызове метода контекста (УстановитьГраницыВыделения)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(6371)}:						СлужебноеПолеТекстаДолгое.УстановитьГраницыВыделения(НачальнаяПозицияВхождения, НачальнаяПозицияВхождения + СтрДлина(ПоследнееОпределение));
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(15539)}:			ИмяТаблицы = НайтиОпределениеСлова(Фрагменты[0]);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1435)}:			ОткрытьДеревоСвязейПоля();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1403)}:	Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(324)}:		Результат = Компонента.Нажатие(Кнопка);
по причине:
Недопустимое значение параметра (параметр номер '1')

```

**Comment by tormozit** [comment]
Повторил твой сценарий. Ошибки не возникло. Проверь в новом сеансе.

**Comment by PerlAmutor** [comment]
Да, больше не возникает. Значит опять из-за кэша.
