### ISSUE TITLE
Консоль запросов. Техножурнал. Метод объекта не обнаружен (ОбновитьТаблицуЖурнала)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#658]
https://github.com/user-attachments/assets/b053942e-0f7b-4a30-b870-163c8fae0dc5

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1336
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.44.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. В Консоли Запросов выполнил текст запроса:
```
ВЫБРАТЬ
	ВЫРАЗИТЬ(&Подразделение КАК Справочник.СтруктураПредприятия).Родитель КАК Родитель
```
3. Перешел на вкладку "Запрос результата"
4. Вызвал команду "Техножурнал"
5. Получил ошибку:

```
Метод объекта не обнаружен (ОбновитьТаблицуЖурнала)
{ВнешняяОбработка.ирАнализТехножурнала.МодульОбъекта(1954)}:	ФормаАнализа.ОбновитьТаблицуЖурнала(УдалитьДополнительныеСобытия, ИменаНеполезныхКолонок,
```

**Comment by tormozit** [comment]
Ошибка воспроизводится в новом сеансе?

**Comment by PerlAmutor** [comment]
> Ошибка воспроизводится в новом сеансе?

Сейчас в новом сеансе не воспроизводится, но я шаманил с настройками записи тех.журнала до перезапуска после возникновения этой ошибки, может это помогло:

![image](https://github.com/user-attachments/assets/de85a30d-fbef-4a12-a0c5-2d956632e9f0)
