### ISSUE TITLE
Консоль запросов. Отложенный снимок объекта отладки. Таблица не найдена

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#659]
https://github.com/user-attachments/assets/27c32ceb-3ce8-4333-ab59-284a0ed0be8e

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1394
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.44.2p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Отлаживаю запрос получения данных для печатной формы СчетФактураВыданный в ERP 2.5.17.95
2. Вызвал команду формирования снимка отложенного объекта отладки:
```
ВнешниеОбработки.Создать("C:\Users\user123\Downloads\7.44.2\ирПортативный.epf", Ложь).ирОбщий.От(Запрос)
```
4. Скопировал результат функции и вызывал загрузку объекта отладки в ИР
5. Попытался выполнить запрос
6. Получил ошибку

```
Текст запроса: Строка кода 285: {(285,19)}: Таблица не найдена "ПредставлениеВыставленКомиссионеру"
ЛЕВОЕ СОЕДИНЕНИЕ <<?>>ПредставлениеВыставленКомиссионеру КАК ДанныеКомиссионера
```

Вижу, что в Менеджере Временных Таблиц эта таблица присутствует:

![image](https://github.com/user-attachments/assets/a54ad8b0-676a-4f65-8929-2f7b055cce03)

В то время как сама ИР перенесла лишь 16 из 21 временных таблиц:

![image](https://github.com/user-attachments/assets/0b4840eb-5e82-43df-8312-8731e839922d)

Если что код в ERP в СчетФактураВыданны.МодульМенеджера.ПолучитьДанныеДляПечатнойФормыСчетФактура(6316):

![image](https://github.com/user-attachments/assets/8921ed89-ec0b-4c88-b1b1-54545ec19660)

Вызывается при формировании печатной формы Счет Фактуры Выданной

Файл отложенного объекта отладки прилагаю:
[_17_09_202419_17_52ОтладитьСтруктура.zip](https://github.com/user-attachments/files/17031904/_17_09_202419_17_52.zip)

**Comment by PerlAmutor** [comment]
Интересно, что даже через этот вызов ошибка возникает:

`ОбщегоНазначенияУТ.ПоказатьВременнуюТаблицу(Запрос, "ПредставлениеВыставленКомиссионеру")`

Ошибка платформы, которая с 8.3.23 не исправлена?

Вероятно дело в Типе колонки Таблицы Значений:

![image](https://github.com/user-attachments/assets/094494c3-6aac-4156-a166-b80ac77a4037)

Либо где-то тут:

![image](https://github.com/user-attachments/assets/c3b4de3d-87cf-4148-b775-9b52e61f8237)

**Comment by tormozit** [comment]
Пока пример слишком много посторонних данных содержит. Постарайся избавить его от лишнего.
Покажи подробно типы колонок проблемной таблицы например через открытие ее снимка через Ис().

**Comment by PerlAmutor** [comment]
> Пока пример слишком много посторонних данных содержит. Постарайся избавить его от лишнего. Покажи подробно типы колонок проблемной таблицы например через открытие ее снимка через Ис().

![image](https://github.com/user-attachments/assets/2211fa05-b7da-484a-bfaa-8642da8f8ca4)

```
	Запрос.Текст =
	"ВЫБРАТЬ
	|	*
	|ПОМЕСТИТЬ ПредставлениеВыставленКомиссионеру
	|ИЗ
	|	&ПредставлениеВыставленКомиссионеру КАК ДанныеКомиссионера
	|
	|ИНДЕКСИРОВАТЬ ПО
	|	СчетФактура
	|;
	|";
	
	Запрос.УстановитьПараметр("ПредставлениеВыставленКомиссионеру", Результат);
	
	Запрос.Выполнить();
```

[_17_09_202422_15_39ИсследоватьТаблицаЗначений.zip](https://github.com/user-attachments/files/17033880/_17_09_202422_15_39.zip)

**Comment by tormozit** [comment]
У меня с такой таблицей запрос выполняется без ошибки.

**Comment by PerlAmutor** [comment]
> У меня с такой таблицей запрос выполняется без ошибки.

Запрос то выполняется. Из такой временной таблицы невозможна выгрузка данных. Поэтому когда снимок делается, то в файл такие временные таблицы не выгружаются о чем я написал в первом посте. Выгружается всего 16 из 21 временных таблиц.


https://github.com/user-attachments/assets/dde1a423-ba28-4aa2-a39c-b63ab507ae49

//
Сделал тестовую обработку демонстрирующую проблему.

[ТестВыгрузкиВременнойТаблицы.zip](https://github.com/user-attachments/files/17038005/default.zip)

Если её запустить то платформа такую ошибку выдает уже после того как запрос выполнился, на строке где идет попытка выгрузки данных временной таблицы:

![image](https://github.com/user-attachments/assets/4aad87a6-a93d-4598-ab59-7b855727c5fd)

Такой неожиданный эффект "приватной для просмотра временной таблицы" похоже дает комбинация одинаковых наименований поля и самой временной таблицы:

![image](https://github.com/user-attachments/assets/b59df805-8d93-4fe1-b2dd-8d30e1e13a35)

**Comment by PerlAmutor** [comment]
Нашел обходное решение как можно исправить. Достаточно псевдоним другой задать:

```
	ИмяВременнойТаблицы = "ПредставлениеВыставленКомиссионеру";
	ЕстьОдноименнаяКолонка = Запрос.МенеджерВременныхТаблиц.Таблицы[ИмяВременнойТаблицы].Колонки.Найти(ИмяВременнойТаблицы) <> Неопределено;
	
	Если ЕстьОдноименнаяКолонка = Истина Тогда
		ЗапросДляВыгрузки = Новый Запрос;
		ЗапросДляВыгрузки.МенеджерВременныхТаблиц = Запрос.МенеджерВременныхТаблиц;
		ЗапросДляВыгрузки.Текст = СтрШаблон("ВЫБРАТЬ * ИЗ %1 КАК _ОбходОшибки%1", ИмяВременнойТаблицы);
		РезультатЗапроса = ЗапросДляВыгрузки.Выполнить();
		ТЗДанные = РезультатЗапроса.Выгрузить();
	Иначе
		ТЗДанные = Запрос.МенеджерВременныхТаблиц.Таблицы[ИмяВременнойТаблицы].ПолучитьДанные();
	КонецЕсли;
```

В БСП та же самая ошибка будет, т.к. разработчики не учли эту особенность и свой псевдоним не задают:

//ОбщегоНазначенияУТ
```
// Показать временную таблицу из менеджера временных таблиц.
// Используется для просмотра временных таблиц в отладчике.
// Пример вызова функции:
//	ОбщегоНазначенияУТ.ПоказатьВременнуюТаблицу(Запрос, "ТаблицаТоваров")
//
// Параметры:
// 	МенеджерВременныхТаблицИлиЗапрос - МенеджерВременныхТаблиц - 
//	                                 - Запрос -
//  ИмяВременнойТаблицы - Строка - 
//
// Возвращаемое значение:
// 	ТаблицаЗначений - Данные временной таблицы
//
Функция ПоказатьВременнуюТаблицу(МенеджерВременныхТаблицИлиЗапрос, ИмяВременнойТаблицы) Экспорт
	
	ЗакрытьМенеджерВременныхТаблиц = Ложь;
	
	Если ТипЗнч(МенеджерВременныхТаблицИлиЗапрос) = Тип("Запрос") Тогда
		Если МенеджерВременныхТаблицИлиЗапрос.МенеджерВременныхТаблиц = Неопределено Тогда
			МенеджерВременныхТаблиц = Новый МенеджерВременныхТаблиц;
			ЗакрытьМенеджерВременныхТаблиц = Истина;
			МенеджерВременныхТаблицИлиЗапрос.МенеджерВременныхТаблиц = МенеджерВременныхТаблиц; 
		Иначе
			МенеджерВременныхТаблиц = МенеджерВременныхТаблицИлиЗапрос.МенеджерВременныхТаблиц;
		КонецЕсли;
		МенеджерВременныхТаблицИлиЗапрос.Выполнить();
	Иначе
		МенеджерВременныхТаблиц = МенеджерВременныхТаблицИлиЗапрос;
	КонецЕсли; 
	
	ТекстЗапроса = 
	"ВЫБРАТЬ
	|	*
	|ИЗ
	|	&ВременнаяТаблица";
	ТекстЗапроса = СтрЗаменить(ТекстЗапроса, "&ВременнаяТаблица", ИмяВременнойТаблицы);
	
	ДанныеТаблицы = ЗапросВыполнитьВыгрузить(ТекстЗапроса,, МенеджерВременныхТаблиц);
	
	Если ЗакрытьМенеджерВременныхТаблиц Тогда
		МенеджерВременныхТаблиц.Закрыть();
		МенеджерВременныхТаблицИлиЗапрос.МенеджерВременныхТаблиц = Неопределено;
	КонецЕсли; 
	
	Возврат ДанныеТаблицы;
	
КонецФункции
```

Ну и плюс ко всему это тянет на ошибку платформы. Работа метода Запрос.МенеджерВременныхТаблиц.Таблицы[ИмяВременнойТаблицы].ПолучитьДанные() некорректная.

--
И есть пожелание - сверять в ИР количество выгруженных временных таблиц с количеством временных таблиц в МенеджереВременныхТаблиц до выгрузки снимка для отладки, чтобы уже при загрузки в ИР было какое-то сообщение, что не все временные таблицы перенеслись (это на будущее, чтобы понимать что возможно есть еще какие-то ситуации, когда возникает исключение)

**Comment by tormozit** [comment]
>платформа такую ошибку выдает

Старайся текст ошибки сразу указывать и в первую очередь именно текст, а не картинку ошибки. Например до этого сообщения твою заявку не смогли бы быстро найти те, кто будет искать по тексту ошибки, т.к. в заявке этот текст отсутствовал.
Текст ошибки:
```
Ошибка при вызове метода контекста (ПолучитьДанные): Ошибка при получении данных временной таблицы.
по причине:
{(1, 15)}: Неоднозначное поле "ПредставлениеВыставленКомиссионеру.СчетФактура"
Ошибка при получении данных временной таблицы.
по причине:
{(1, 15)}: Неоднозначное поле "ПредставлениеВыставленКомиссионеру.СчетФактура"
SELECT * FROM <<?>>ПредставлениеВыставленКомиссионеру

```

**Comment by tormozit** [comment]
Для решения проблемы в функции ирОбщий.ПолВТ замени текст запроса на такой
```
ТекстЗапроса = "
	|ВЫБРАТЬ ПЕРВЫЕ " + XMLСтрока(ДопустимоеЧислоСтрок) + "
	|	*
	|ИЗ
	|	ИмяВременнойТаблицы КАК Т
	|";
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/992327

**Comment by tormozit** [comment]
> Работа метода Запрос.МенеджерВременныхТаблиц.Таблицы[ИмяВременнойТаблицы].ПолучитьДанные() некорректная

Да. Это ошибка платформы. Нужно отправить это описание ошибки на v8@1c.ru

**Comment by tormozit** [comment]
Исправлено в 7.45
