### ISSUE TITLE
Не открываются различные значения колонки из консоли запросов

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#66]
**Программное окружение**
Платформа: 8.3.17.1549
Режим БД: клиент-серверный
Конфигурация. Название: 1C:Drive, версия 1.3 (1.3.6.5)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: English
Конфигурация. Режим управления блокировкой данных: Managed
Конфигурация. Режим совместимости: Version8_3_14
Инструменты разработчика. Версия: Расширение 6.09.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (6.09.2e)
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная НеРусский-0409
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл инструмент Консоль запросов
2. Выполнил запрос:
SELECT
	Counterparties.Ref AS Ref
FROM
	Catalog.Counterparties AS Counterparties
3. Выделил первую строку, колонку Ref в таблице Результат-коллекция
4. Нажал кнопку "Различные значения колонки"
5. Получил окно с ошибкой:
Поле объекта не обнаружено (_ИмяПоляКоличества3463ПроцентВГруппе)
{ИнструментыРазработчикаTormozit DataProcessor.ирРазличныеЗначенияКолонки.Form.Форма.Form(314)}:		ТаблицаРезультата.Колонки[ИмяПоляКоличества + "ПроцентВГруппе"].Имя = "Вес";
{ИнструментыРазработчикаTormozit DataProcessor.ирРазличныеЗначенияКолонки.Form.Форма.Form(939)}:	Если Не ОбновитьДанные(, Истина) Тогда 
{ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(37754)}:	РезультатФормы = Форма.ОткрытьМодально();
{ИнструментыРазработчикаTormozit CommonModule.ирОбщий.Module(38217)}:				ОткрытьРазличныеЗначенияКолонкиЛкс(ИсточникДействий,,, ЭтаФорма);
{ИнструментыРазработчикаTormozit DataProcessor.ирКонсольЗапросов.Form.Форма.Form(9491)}:	ирОбщий.УниверсальнаяКомандаФормыЛкс(ЭтаФорма, Кнопка);

**Ожидаемое поведение**
Открывается окно "Различные значения колонки".

**Comment by antonsm2011** [comment]
База 1С Drive полностью типовая, та же самая как здесь - https://github.com/tormozit/RDT1C/issues/34.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/933690

**Comment by tormozit** [comment]
Исправлено в 6.09.3
