### ISSUE TITLE
Подбор и обработка объектов БД. Подчиненные справочники

### ISSUE THREAD

**Issue by AlexNash** [tormozit/RDT1C#660]
**Программное окружение**

Платформа: 8.3.19.1264
Режим БД: клиент-серверный
Конфигурация. Название: Управление производственным предприятием, редакция 1.3 (1.3.130.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_2_13
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 102
Инструменты разработчика. Версия: Портативный 7.44.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс

**Воспроизведение проблемы**
1. Открыл инструмент "Подбор и обработка объектов"
2. Указал имя таблицы метаданных (Справочник, который имеет подчиненный справочник) 
3. Указал отбор по организации
4. Заполнил строки в обработке
5. Выбираю обработку "Удалить"
6. В открывшемся окне нажимаю кнопку "Удалить через СУБД"
7. Появляется ошибка, вызванная исключением в коде 
```
Шаблонная строка не найдена в тексте
{ВнешняяОбработка.ирОбщий.МодульОбъекта(7365)}:		ВызватьИсключение "Шаблонная строка не найдена в тексте";
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(352)}:		ТекстСУБД = ирОбщий.ЗаменитьРегВыражениеЛкс(ТекстСУБД, "JOIN\s+#\w+", "JOIN " + ИмяГлавнойВременнойТаблицы);
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(429)}:				УдалитьОбъектыЧерезСУБД(Запрос, МетаСправочник.ПолноеИмя(), ИмяТаблицыКлючейСУБД,,, выхОтключенныеИтоги);
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(298)}:		УдалитьОбъектыЧерезСУБД(Запрос, ИмяТаблицы,, ИмяТаблицыКлючей, ТекстСУБД, ОтключенныеИтоги);
```
![image](https://github.com/user-attachments/assets/6b5de92a-9d59-4695-87fc-8a4c97169667)

**Ожидаемое поведение**
Должны удалиться подчиненные справочники, элементы которых попали в отбор. Проверялось на двух разных справочниках с подчиненными элементами

**Comment by tormozit** [comment]
Нужны значения переменных ТекстСУБД и ИмяГлавнойВременнойТаблицы в момент возникновения ошибки

**Comment by AlexNash** [comment]
В процедуре УдалитьОбъектыЧерезСУБД в строке 352 перед вызовом ирОбщий.ЗаменитьРегВыражениеЛкс(ТекстСУБД, "JOIN\s+#\w+", "JOIN " + ИмяГлавнойВременнойТаблицы);

ТекстСУБД
`INSERT INTO #tt3 WITH(TABLOCK) (_Q_000_F_000RRef) SELECT
T1._IDRRef
FROM dbo._Reference38689 T1 WITH(NOLOCK)
INNER JOIN #tt2 T2 WITH(NOLOCK)
ON (T1._OwnerIDRRef = T2._Q_000_F_000RRef)`

ИмяГлавнойВременнойТаблицы 
#tt2

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/992351

**Comment by tormozit** [comment]
Исправлено в 7.45
