### ISSUE TITLE
Подбор и обработка объектов БД

### ISSUE THREAD

**Issue by AlexNash** [tormozit/RDT1C#661]
**Программное окружение**

Платформа: 8.3.19.1264
Режим БД: клиент-серверный
Конфигурация. Название: Управление производственным предприятием, редакция 1.3 (1.3.130.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_2_13
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 102
Инструменты разработчика. Версия: Портативный 7.44.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс

**Воспроизведение проблемы**
1. Открыл инструмент "Подбор и обработка объектов"
2. Указал имя таблицы метаданных (Документ с движениями по регистру бухгалтерии)
3. Указал отбор по организации
4. Заполнил строки в обработке
5. Выбираю обработку "Удалить"
6. В открывшемся окне нажимаю кнопку "Удалить через СУБД"
7. Появляется ошибка, вызванная исключением в коде

`Не найден сформированный платформой запрос СУБД
{ВнешняяОбработка.ирОбщий.МодульОбъекта(29044)}:		ВызватьИсключение "Не найден сформированный платформой запрос СУБД";
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(616)}:		ТекстСУБД = ирОбщий.ВыполнитьЗапросИНайтиТекстСУБДЛкс(Запрос, ИмяТаблицыХранения, Ложь);
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(441)}:				УдалитьСтрокиТаблицыСУБДПорциями(Запрос, РегистрМД.ПолноеИмя(), ИмяТаблицыКлючей, ИмяТаблицыКлючейСУБД, "Регистратор", выхОтключенныеИтоги);
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(298)}:		УдалитьОбъектыЧерезСУБД(Запрос, ИмяТаблицы,, ИмяТаблицыКлючей, ТекстСУБД, ОтключенныеИтоги);`
![image](https://github.com/user-attachments/assets/ea9b2a18-8877-4096-9a52-2ef4e8b17fa1)

В запросе в отладке при этом обращение к таблице субконто

![image](https://github.com/user-attachments/assets/d6cf78c0-a537-487f-a09a-4f3d31e36a17)

**Comment by tormozit** [comment]
Выгрузи в точке останова в момент возникновения ошибки табличную часть АнализТехножурнала.ТаблицаЖурнала в таблицу значений и затем в файл. Или хотя бы в табличный документ.

**Comment by AlexNash** [comment]
[АнализТехножурнала_ТаблицаЖурнала.xlsx](https://github.com/user-attachments/files/17053111/_.xlsx)

**Comment by tormozit** [comment]
Что в переменной ДолженСодержатьТекст?

В таблице трассы есть такой текст запроса
```
exec sp_executesql N'SELECT
@P1
FROM dbo._AccRgED18195 T1 WITH(NOLOCK)
INNER JOIN #tt2 T2 WITH(NOLOCK)
ON (T1._RecorderTRef = 0x000001D0 AND T1._RecorderRRef = T2._Q_000_F_000RRef)',N'@P1 numeric(10)',1
```

**Comment by AlexNash** [comment]
ДолженСодержатьТекст 
_AccRgAT118191
![image](https://github.com/user-attachments/assets/99996be7-5ca9-44d1-8a70-343427c044b6)

**Comment by AlexNash** [comment]
Структура хранения регистра
![image](https://github.com/user-attachments/assets/ecdb8951-ef79-4946-8d99-a141b56e5754)

**Comment by AlexNash** [comment]
По стеку на вызов ранее процедура УдалитьСтрокиТаблицыСУБДПорциями
![image](https://github.com/user-attachments/assets/f3612e20-dffb-465b-bc18-f99a606523f0)

МассивТаблиц
![image](https://github.com/user-attachments/assets/5896d5b7-c417-492c-ac8b-3d0ae5cffd7e)

СтруктураХраненияТаблицы
![image](https://github.com/user-attachments/assets/305bd2f3-5eb5-4a14-ada0-d9dffc4953a4)

ЛокальныеПеременные
![image](https://github.com/user-attachments/assets/c3a8a111-0cc9-498a-8125-ab71e32d2430)

**Comment by AlexNash** [comment]
По стеку вызовов ранее процедура "УдалитьСтрокиТаблицыСУБДПорциями"
![image](https://github.com/user-attachments/assets/cae31ff8-e4cc-4e32-bcb3-a8a3fdf7f060)

МассивТаблиц
![image](https://github.com/user-attachments/assets/b1f5e828-c3ad-403c-982c-03f1f7987a7c)

СтруктураХраненияТаблицы
![image](https://github.com/user-attachments/assets/7c84413c-7868-4291-ba4f-a134a08bbf5b)

Локальные переменные
![image](https://github.com/user-attachments/assets/75fab135-a584-4550-8f6c-7ef9f7179d65)

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/992432

**Comment by tormozit** [comment]
Исправлено в 7.45
