### ISSUE TITLE
Установка варианта "Расширение" любым способом вызывает ошибку "Переполнение стека встроенного языка на сервере"

### ISSUE THREAD

**Issue by EugeneFalin** [tormozit/RDT1C#662]
**Программное окружение**
Платформа 8.3.18.1289
Конфигурация 1С Страховая компания КОРП  3.0.78.80
Режим совместимости 8.3.12

**Воспроизведение проблемы**
Запустил установщик расширения, или подключил его вручную, объединил с имеющимся расширением
После перезапуска сеанса вылазит ошибка "Переполнение встроенного языка на сервере" с предложением завершить работу.
По кнопке "Подробно" выдается следующая информация:
Переполнение стека встроенного языка на сервере
по причине:

МодульСеанса : 33 : СтандартныеПодсистемыСервер.УстановкаПараметровСеанса(ИменаПараметровСеанса);
ОбщийМодуль.СтандартныеПодсистемыСервер.Модуль : 33 : Справочники.ВерсииРасширений.УстановкаПараметровСеанса(ИменаПараметровСеанса, УстановленныеПараметры);
МодульСеанса : 42 : скОбщиеСтраховыеПроцедурыСерверВнешнееСоединение.УстановкаПараметровСеанса(ИменаПараметровСеанса);
ОбщийМодуль.скОбщиеСтраховыеПроцедурыСерверВнешнееСоединение.Модуль : 52 : СтандартныеПодсистемыСервер.УстановкаПараметровСеанса(ИменаПараметровСеанса);
...
ОбщийМодуль.ВерсионированиеОбъектов.Модуль : 1532 : ВариантВерсионирования = ВариантВерсионированияОбъекта(ОбщегоНазначения.ИдентификаторОбъектаМетаданных(Источник.Метаданные()));
ОбщийМодуль.ОбщегоНазначения.Модуль : 3421 : Возврат Справочники.ИдентификаторыОбъектовМетаданных.ИдентификаторОбъектаМетаданных(
ОбщийМодуль.СтандартныеПодсистемыПовтИсп.Модуль : 215 : Справочники.ИдентификаторыОбъектовМетаданных.ДанныеОбновлены(Истина, ОбъектыРасширений);
Справочник.ИдентификаторыОбъектовРасширений.МодульОбъекта : 0
по причине:
Переполнение стека встроенного языка на сервере

**Ожидаемое поведение**
Ожидается удачный запуск программы с установленным расширением.

**Comment by tormozit** [comment]
Укажи версию ИР, тип клиентского приложения, версию БСП.
Что значит "объединил с имеющимся расширением"? С каким расширением ты его объединял и зачем?

**Comment by tormozit** [comment]
Поставь точку останова на одной из строк:
МодульСеанса : 42 : скОбщиеСтраховыеПроцедурыСерверВнешнееСоединение.УстановкаПараметровСеанса(ИменаПараметровСеанса);
ОбщийМодуль.скОбщиеСтраховыеПроцедурыСерверВнешнееСоединение.Модуль : 52 : 

Вероятнее всего проблема в них. 
Дождись 3-й остановки и покажи полный стек хотя бы в виде картинки. Хочу понять, есть ли там модули ИР.

**Comment by EugeneFalin** [comment]
Версия БСП: 3.1.2.387
Вариант с объединением с имеющимся расширением я решил проверить, подумав, что проблемная операция выполняется только при регистрации нового расширения. Это была последняя попытка и ее можно в расчет не брать. По стеку вызовов и точке останова, я чуть позже смогу посмотреть. Сейчас увы, есть неотложная работа и приходится пользоваться более банальной версией консоли, которая работает. Но я пришел к похожим размышлениям и предположениям, что проблема скорее всего в древней бсп и структурном несоответствии справочников "версии расширений" и "идентификаторы расширений". Но в субботу я найду для этого время и продублирую. Кстати, UI тоже не заработали со схожей ошибкой переполнения. Нюансов не упомню. Я сильно надеялся на них ,т.к. в них вроде было задекларировано избавление от использования БСП, которая пала и под мое подозрение.
