### ISSUE TITLE
Подбор и обработка объектов БД. Документ с движениями по регистру расчетов

### ISSUE THREAD

**Issue by AlexNash** [tormozit/RDT1C#663]
Программное окружение

Платформа: 8.3.19.1264
Режим БД: клиент-серверный
Конфигурация. Название: Управление производственным предприятием, редакция 1.3 (1.3.130.1)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_2_13
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 102
Инструменты разработчика. Версия: Портативный 7.44.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс

Воспроизведение проблемы

1. Открыл инструмент "Подбор и обработка объектов"
2. Указал имя таблицы метаданных (Документ с движениями по регистру расчетов)
3. Указал отбор по организации
4. Заполнил строки в обработке
5. Выбираю обработку "Удалить"
6. В открывшемся окне нажимаю кнопку "Удалить через СУБД"
7. Появляется ошибка, вызванная исключением в коде

```
Индекс находится за границами массива
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(620)}:		ИмяТаблицыХранения = СтруктураХраненияТаблицы[0].ИмяТаблицыХранения;
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(446)}:				УдалитьСтрокиТаблицыСУБДПорциями(Запрос, РегистрМД.ПолноеИмя(), ИмяТаблицыКлючей, ИмяТаблицыКлючейСУБД, "Регистратор", выхОтключенныеИтоги);
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.Удалить.Форма(298)}:		УдалитьОбъектыЧерезСУБД(Запрос, ИмяТаблицы,, ИмяТаблицыКлючей, ТекстСУБД, ОтключенныеИтоги);
```
Процедура
УдалитьСтрокиТаблицыСУБДПорциями

ИмяЧастиТаблицы
РегистрРасчета.ОсновныеНачисленияРаботниковОрганизаций.Перерасчет.ПерерасчетОсновныхНачислений

НачальныйТекст
```
ВЫБРАТЬ 1 ИЗ РегистрРасчета.ОсновныеНачисленияРаботниковОрганизаций.Перерасчет.ПерерасчетОсновныхНачислений КАК Т
ВНУТРЕННЕЕ СОЕДИНЕНИЕ КлючиСтрок1Основные КАК КлючиСтрокТ
ПО ИСТИНА 
	И Т.Регистратор = КлючиСтрокТ.Ссылка
```

ИмяТаблицы
РегистрРасчета.ОсновныеНачисленияРаботниковОрганизаций.Перерасчет.ПерерасчетОсновныхНачислений

ИмяЧастиТаблицы
РегистрРасчета.ОсновныеНачисленияРаботниковОрганизаций.Перерасчет.ПерерасчетОсновныхНачислений

Запрос.Текст
```
ВЫБРАТЬ 1 ИЗ РегистрРасчета.ОсновныеНачисленияРаботниковОрганизаций.Перерасчет.ПерерасчетОсновныхНачислений КАК Т
ВНУТРЕННЕЕ СОЕДИНЕНИЕ КлючиСтрок1Основные КАК КлючиСтрокТ
ПО ИСТИНА 
	И Т.Регистратор = КлючиСтрокТ.Ссылка
```
Структура хранения регистра расчета 
![image](https://github.com/user-attachments/assets/0670d03f-f8bd-4f16-9670-951115882b82)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/992437

**Comment by tormozit** [comment]
Исправлено в 7.45
