### ISSUE TITLE
Ошибка при установке нескольких условий соединения таблиц в запросе

### ISSUE THREAD

**Issue by GreennPingvin** [tormozit/RDT1C#664]
**Программное окружение**

Платформа: 8.3.23.2137
Режим БД: клиент-серверный
Конфигурация. Название: Демонстрационная (1.0.0.1)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_22
Конфигурация. Режим использования синхронных вызовов: ИспользоватьСПредупреждениями
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 7.44.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.44.2e)
Пользователь. Защита от опасных действий: Да
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Домашняя 64-разрядная Русский
Клиент. ОС от имени администратора: Да
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг:  Локальный
Сервер. ОС: Майкрософт Windows 10 Домашняя 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

Добрый день. Есть соединение двух таблиц по 2 условиям. После сохранения и повторного открытия запроса в консоли запроса ИР вылезает ошибка. Рискну предположить, что это из-за добавления слова ИСТИНА в условие соединения так как после его удаления все начинает работать нормально.

https://github.com/user-attachments/assets/a45afe76-d805-4b85-8528-14a73cbf918b

**Comment by tormozit** [comment]
нужен текст запроса и текст ошибки

**Comment by tormozit** [comment]
Исправлено в 7.45
