### ISSUE TITLE
Нет автодополнения из общих модулей экспортных процедур расширений

### ISSUE THREAD

**Issue by nick-ez** [tormozit/RDT1C#665]
Платформа: 8.3.25.1394
Режим БД: файловый
Конфигурация. Название: Демонстрационная конфигурация "Библиотека стандартных подсистем", редакция 3.1 (3.1.9.74)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 7.45.1e
Инструменты разработчика. Инструмент: Консоль кода
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.45.1e)
Расширения. _ДемоРасширение (1.0.1.14)
Расширения. _ДемоПустоеРасширение (1.0.1.1)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 11 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ╥хъє∙р  ъюфютр  ёЄЁрэшЎр: 866

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль кода"
2. Попытаться в коде обратиться к экспортной процедуре общего модуля расширения.
3. Нет автодополнения названия процедур

**Ожидаемое поведение**
После ввода  имени общего модуля и точки получить список процедур в контекстном окне атодополнения

При этом методы общих методов расширения "Инструменты разработчика" отображаются 

https://github.com/user-attachments/assets/ea05f95a-7d10-461a-863e-16d44c2b8a43

**Comment by tormozit** [comment]
Нужен файл расширения _ДемоРасширение

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/992477

**Comment by tormozit** [comment]
Исправлено в 7.45.2

**Comment by nick-ez** [comment]
В версии Расширение 7.46.1e, данная проблема опять присутствует.

**Comment by tormozit** [comment]
В моем тесте проблема по-прежнему не воспроизводится. Поэтому прошу уточнить, проверялся ли тобой показанный на видео тест в версии 7.45.2?

**Comment by nick-ez** [comment]
Извиняюсь, все работает как надо.
