### ISSUE TITLE
Отладка запроса. Не работает на релизе ERP 2.5.19.63

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#666]
<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.23.1912
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.19.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: НеИспользовать
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.45.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2016 Standard 64-bit Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Active code page: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 17763)

</details>

**Воспроизведение проблемы**
1. Отлаживал запрос формирования движений Авансового Отчета в демо-базе ERP 2.5.19.63 в транзакции
2. Не смог загрузить сделанный функцией От() снимок в Портативный ИР
3. Выдалась ошибка на строке Менеджер.СоздатьЭлемент() для параметра запроса Справочник.Пользователи:

```
Ошибка при вызове метода контекста (СоздатьЭлемент)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(1980)}:				Объект = Менеджер.СоздатьЭлемент();
{ВнешняяОбработка.ирОбщий.МодульОбъекта(15810)}:							Объект = СоздатьСсылочныйОбъектПоМетаданнымЛкс(мПолноеИмяМД, ЭтоГруппаДляНового, выхИдентификаторСсылки, ЗаполнитьНовыйСсылочный);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(1012)}:		СтруктураОбъекта = ОбъектБДПоКлючуЛкс(Снимок.ПолноеИмяМД,,, Ложь,,,,, Ложь);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(23421)}:			ОбъектыДанных.Добавить(ОбъектИзСнимкаЛкс(СнимокОбъекта));
{ВнешняяОбработка.ирКлиент.МодульОбъекта(4824)}:			Объект = ирОбщий.ЗапросИзСтруктурыЛкс(Объект, Объект2);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(4756)}:	ОтладитьОбъектПоСтруктуреЛкс(СтруктураПараметров);
{(1)}:ирКлиент.ОтладитьОтложенныйОбъектЛкс()
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(143)}:		Выполнить(СтрокаИнструмента.Команда + "()");
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(136)}:	ОткрытьИнструмент(СтрокаИнструмента);
по причине:
При подписке ЗарегистрироватьИзмененияДляАвтономногоРежима на событие ПриЗаписи произошла ошибка. Обработчик события не найден.
```

Проверил включенность параметра "Объекты на сервере" - флажок включен. Перетыкивал пару раз, результат не поменялся.

**Comment by tormozit** [comment]
Портативная версия имеет ограниченную совместимость с конфигурациями под управляемое приложение. Переходи на вариант "Расширение".

**Comment by PerlAmutor** [comment]
Могу я как-нибудь сказать функции От(), чтобы снимок сделался без транзакции?

**Comment by tormozit** [comment]
Ошибку исправлю путем подавления https://www.hostedredmine.com/issues/992553
Но если твоя транзакция не была в итоге зафиксирована и еще в ряде случае ты можешь получить бесполезный снимок, который не даст увидеть то же поведение запроса.

**Comment by tormozit** [comment]
Исправлено в 7.45.2
