### ISSUE TITLE
Редактор объекта БД. Связанные колонки. Менеджер табличного поля. Автоактивация структуры формы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#668]
https://github.com/user-attachments/assets/0e9b433e-868a-47f1-878b-60654b0016f0

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1394
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.19.63)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_23
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.47.2e
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.47.2e)
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ‘ЁбвҐ¬Ґ ­Ґ г¤ Ґвбп ­ ©вЁ гЄ § ­­л© Їгвм.
’ҐЄгй п Є®¤®ў п бва ­Ёж : 866

</details>

**Воспроизведение проблемы**
1. Открыл "Редактор объекта БД"
2. Выбрал объект редактирования.
3. Перешел на вкладку "Связанные колонки БД"
4. Выполнил поиск
5. Вызвал команду " \ Панель \ Связанные колонки БД(100) \ Командная панель \ Менеджер табличного поля"
6. Вместе с Менеджером табличного поля почему-то вызвалась настройка структуры формы.

P.S.: обрати внимание на иероглифы в "Информация для технической поддержки", не знаю почему но так прямо в 1С показывается:

![image](https://github.com/user-attachments/assets/37c1fcee-c392-4a6d-84ef-41419ff9241c)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/994030

**Comment by tormozit** [comment]
Исправлено в 7.48
