### ISSUE TITLE
Ошибка при перемещении родительского узла в дереве в дочерний (Консоль КД, Консоль запросов)

### ISSUE THREAD

**Issue by GreennPingvin** [tormozit/RDT1C#669]
**Программное окружение**
Платформа: 8.3.23.2137
Режим БД: файловый
Конфигурация. Название: Демонстрационное приложение (1.0.37.2)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_22
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 7.47.2e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. OneDebugger (1.1.0)
Расширения. ИнструментыРазработчикаTormozit (7.47.2e)
Расширения. Колонтитулы ()
Расширения. ФункцияДляОтладки ()
Расширения. ВесТоваров ()
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Домашняя 64-разрядная Русский
Клиент. ОС от имени администратора: Да
Клиент. ОС выполнение BAT: Да
Клиент. ОС ’ҐЄгй п Є®¤®ў п бва ­Ёж : 866

Получить эту информацию можно кнопкой "Техническая информация" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1

**Воспроизведение проблемы**
1. Открыл инструмент ААА
2. Нажал кнопку БББ
3. Получил окно с ошибкой ВВВ

**Ожидаемое поведение**
Какая реакция программы ожидалась?

Запрет такого действия

https://github.com/user-attachments/assets/44493553-71fd-4144-83cd-0332252ef150

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/994058

**Comment by tormozit** [comment]
Исправлено в 7.48
