### ISSUE TITLE
Консоль запросов. Ошибка после прерывания получения структуры бд.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#67]
https://user-images.githubusercontent.com/87958986/133821416-dafb7d8b-0579-4fb4-b7e6-0a3370357c9c.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Если прервать получение "Структуры БД" через Ctrl+Break после вызова Ctrl+Space, то дальнейшая работа с системой Автодополнения становится невозможной из-за ошибки, т.к. кэш становится битым:

```
Значение не является значением объектного типа (Тип)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(12600)}:	Если ирОбщий.ЛиКорневойТипСсылочногоОбъектаБДЛкс(ОписаниеТаблицыБД.Тип) Тогда
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(1273)}:				ирОбщий.ДополнитьТаблицуПолейТаблицыБДВиртуальнымиПолямиЛкс(ПостроительЗапроса.ДоступныеПоля, ирОбщий.ОписаниеТаблицыБДЛкс(ИмяТаблицы));
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(1505)}:			ПостроительЗапросаРодителя = ПостроительЗапросаПоСтруктуреТипа(СтрокаОбщегоТипа, РодительскаяСтруктураТипа.ВиртуальнаяТаблица);
{ВнешняяОбработка.ирПлатформа.МодульОбъекта(3962)}:	ТаблицаСвойств = СвойстваТипаПредопределенные(СтруктураТипа, Слово, ТипСлова,, ЯзыкПрограммы, Конфигурация, ВычислятьТипы, ЛиСерверныйКонтекст);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4795)}:		ВыгрузкаТаблицыСлов = мПлатформа.ПолучитьТаблицуСловСтруктурыТипа(выхСтруктураТипаКонтекста, ЯзыкПрограммы, Конфигурация, ВнешниеФункцииКомпоновкиДанных, ВычислятьТипы,,,
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4253)}:		Успешно = ЗаполнитьТаблицуСлов(ТаблицаСтруктурТиповКонтекста, КонкретныйТип, СтруктураТипаКонтекста);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(905)}:			ОткрытьАвтодополнение(КодКлавиши);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(891)}:	Результат = ВыполнитьКоманду(Команда);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(284)}:		Результат = ЭкземплярКомпоненты.Нажатие(Кнопка);

```

**Comment by tormozit** [comment]
Попробуем исправить так https://www.hostedredmine.com/issues/933697

**Comment by tormozit** [comment]
Исправлено в 6.10.1
