### ISSUE TITLE
Конструктора запросов ИР. Синтаксическая ошибка

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#671]
https://github.com/user-attachments/assets/a22e9ee0-8775-45ab-a9b7-b90f221315fa

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1394
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.45.1p
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Системе не удается найти указанный путь.
Текущая кодовая страница: 866

</details>

**Воспроизведение проблемы**
1. Не открывается Конструктор Запросов ИР на запросе (ВНИМАНИЕ - Точка в конце, должен возвращать Пустую Ссылку):
```
ВЫБРАТЬ
	ЗНАЧЕНИЕ(Справочник.Организации.)
```
3. Возникает ошибка:
```
Текст запроса: Строка 2: {(2,34)}: Синтаксическая ошибка ")", ожидается: <(>, <ADD>, <ALL>, <ALLOWED>, <AND>, <AS>, <ASC>, <AUTOORDER>, <AVG>, <BadID>, <BEGINOFPERIOD>, <BETWEEN>, <BIGINT>, <CASE>, <CAST>, <CHAR>, <COUNT>, <DATASIZE>, <DATE>, <DATEADD>, <DATEDIFF>, <DATETIME>, <DAY>, <DAYOFYEAR>, <DECIMAL>, <DESC>, <DISTINCT>, <DOUBLE>, <DROP>, <ELSE>, <EMPTYTABLE>, <END>, <ENDOFPERIOD>, <ESCAPE>, <FALSE>, <FLOAT>, <FOR>, <FROM>, <FULL>, <GROUP>, <HIERARCHY>, <HIERARCHYIN>, <HIERARCHYON>, <HOUR>, <id>, <IN>, <INNER>, <INT>, <INT64>, <INTEGER>, <INTO>, <IS>, <ISNULL>, <JOIN>, <LEFT>, <LIKE>, <LONGTEXT>, <MAX>, <MEDIUMTEXT>, <MIN>, <MINUTE>, <MONEY>, <MONTH>, <MVARCHAR>, <NCHAR>, <NOT>, <NTEXT>, <NULL>, <NUMBER>, <NUMERIC>, <NVARCHAR>, <OF>, <ON>, <ONLY>, <OR>, <ORDER>, <OUTER>, <PERIODS>, <PRESENTATION>, <PRESENTATIONREFS>, <QUARTER>, <REAL>, <REF>, <REFS>, <RIGHT>, <ROUND>, <SECOND>, <SELECT>, <SMALLINT>, <STRFIND>, <STRING>, <STRINGLENGTH>, <STRLEFT>, <STRREPLACE>, <STRRIGHT>, <SUBSTRING>, <SUM>, <TABLE>, <TEXT>, <THEN>, <TIME>, <TIMESTAMP>, <TINYTEXT>, <TOP>, <TOTALS>, <TRIMALL>, <TRIML>, <TRIMR>, <TRUE>, <TYPE>, <UNDEFINED>, <UNION>, <UPDATE>, <UPPER>, <UUID>, <VALUE>, <VALUETYPE>, <VARCHAR>, <WEEK>, <WEEKDAY>, <WHEN>, <WHERE>, <YEAR>

```
5. При этом такой запрос открывается (возвращает Неопределено):
```
ВЫБРАТЬ
	ЗНАЧЕНИЕ(Справочник.Организации)
```

**Comment by tormozit** [comment]
Такой синтаксис является недокументированным. Укажи строку исходного кода конфигурации, где встретился такой запрос.

**Comment by tormozit** [comment]
Обращение в запросах к предопределенным данным конфигурации и значениям системных перечислений осуществляется с помощью литерала функционального типа ЗНАЧЕНИЕ:

ЗНАЧЕНИЕ(<ПредставлениеЗначения>)

Для системных перечислений <ПредставлениеЗначения> имеет вид:

<ИмяСистемногоПеречисления>.<Значение>

Допустимые имена системных перечислений приведены выше, с перечнем допустимых для каждого из них значений можно ознакомиться в его описании.

Для предопределенных данных конфигурации <ПредставлениеЗначения> имеет вид:

<ТипПредопределенногоЗначения>.<ИмяОбъектаМетаданных>.<Значение>

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/994065

**Comment by PerlAmutor** [comment]
> Такой синтаксис является недокументированным. Укажи строку исходного кода конфигурации, где встретился такой запрос.

В конфигурации ERP поискал, там такого нет. Первое упоминание обнаружил тут от 2015 года. Даже интересно с какого года это тянется...

https://www.mykib.org/article/1s-8-pustaya-ssylka-v-zaprose-nedokumentirovannaya-vozmozhnost

Кстати еще есть такой вариант. Он работает и по сути бесполезен, т.к. конструктор запросов платформы просто убирает точку:

```
ВЫБРАТЬ
	ВЫРАЗИТЬ(&Параметр КАК Справочник.Организации.) КАК Организация
```

**Comment by tormozit** [comment]
Сделано в 7.48
