### ISSUE TITLE
Аварийно закрывается программа при открытии html редактора в консоли запросов

### ISSUE THREAD

**Issue by GreennPingvin** [tormozit/RDT1C#672]
**Программное окружение**

Платформа: 8.3.24.1667
Режим БД: клиент-серверный
Конфигурация. Название: Бухгалтерия предприятия КОРП, редакция 3.0 (3.0.155.21)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.48.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. OneDebugger (1.1.0)
Расширения. Расширение_ПраваДоступа ()
Расширения. Telegram ()
Расширения. ОграничениеКСчетам (230823)
Расширения. СинхронизацияЛС (12.07.2023)
Расширения. ...
Клиент. Приложение: Управляемое приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows Server 2022 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

Получить эту информацию можно кнопкой "Техническая информация" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1

**Воспроизведение проблемы**
1. Открыл инструмент ААА
2. Нажал кнопку БББ
3. Получил окно с ошибкой ВВВ

**Ожидаемое поведение**
Какая реакция программы ожидалась?

https://github.com/user-attachments/assets/1929c916-37cf-4107-bed5-3e26d1761e41

**Comment by tormozit** [comment]
Это следствие ошибки платформы. Пробуй на старшей версии платформы или воздержись от использования HTML редактора кода.
