### ISSUE TITLE
Загрузка табличных данных. Не полностью загружается таблица из Excel в Таблицу Значений.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#674]
https://github.com/user-attachments/assets/33b1e8ff-35b8-49c4-b11a-0f25db7fad88

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1394
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.48.1p
Инструменты разработчика. Инструмент: Загрузка табличных данных
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ‘ЁбвҐ¬Ґ ­Ґ г¤ Ґвбп ­ ©вЁ гЄ § ­­л© Їгвм.
’ҐЄгй п Є®¤®ў п бва ­Ёж : 866

</details>

**Воспроизведение проблемы**
1. При загрузке таблицы из Excel в "Загрузке табличных данных" в результирующую таблицу значений попадают лишь строки с 10-й строки.
2. Проблемный файл приложил
[ДМ_ИиХПизОС.xlsx](https://github.com/user-attachments/files/17449003/_.xlsx)

**Comment by tormozit** [comment]
Смотри внимательнее первое сообщение на 0:25. Если не понятно, то дальше смотри обучающее видео. Там рассказано подробнее.

**Comment by PerlAmutor** [comment]
> Смотри внимательнее первое сообщение на 0:25. Если не понятно, то дальше смотри обучающее видео. Там рассказано подробнее.

Сообщение я видел. Не понимаю я логику автонахождения первой строки с данными. Если вручную выставить номер строки с которой начинаются данные в 2, то все нормально. По какому принципу ИР решил, что данные начинаются не со второй строки, а с 11-й?

**Comment by tormozit** [comment]
Попробую упростить алгоритм. Но допускаю что позже придется откатить эту правку. https://www.hostedredmine.com/issues/994662

**Comment by tormozit** [comment]
Сделано в 7.49
