### ISSUE TITLE
Останавливаться по ошибке

### ISSUE THREAD

**Issue by Wronglane** [tormozit/RDT1C#675]
Платформа: 8.3.22.2208
Режим БД: клиент-серверный
Конфигурация. Название: Зарплата и управление персоналом КОРП, редакция 3.1 (3.1.29.38)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_21
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 7.37.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Пользователь. Защита от опасных действий: Да
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Microsoft Windows Server 2016 Standard 64-bit НеРусский-0409
Сервер. Процесс: 64б
Сервер. Отладка: tcp

Испытаю неудобства, когда выставлю в истину "Останавливаться по ошибке".
Останавливается бесконечное множество раз 
в общем модуле ирКлиент в этом фрагменте
```
Функция Форма_ВводДоступенЛкс(Знач ЭтаФорма, Знач ПроверятьПолеHTML = Ложь) Экспорт 
	
	Попытка
		ВводДоступен = ЭтаФорма.ВводДоступенЛкс();
	Исключение
	КонецПопытки;
```

---
```
Метод объекта не обнаружен (ВводДоступенЛкс)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(20821)}:		ВводДоступен = ЭтаФорма.ВводДоступенЛкс();
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(5398)}:		Если Истина
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирГлобальный.Модуль(376)}:	ирКлиент.ПроверитьФормыСсылокЛкс();

```

Ожидалось, что не будет лишних срабатываний инструмента "Останавливаться по ошибке".

**Comment by tormozit** [comment]
Конкретно этот путь вызовов уберу, т.к. его можно заменить более простой проверкой. Можешь сам заменить в модуле ирКлиент
`И Форма_ВводДоступенЛкс(ФормаСсылки) `
на 
`И ФормаСсылки.ВводДоступен()`

Но проблему в целом это не решит. Учись использовать фильтр по содержанию описания ошибки.

![изображение](https://github.com/user-attachments/assets/ab037a13-cea2-4ed8-9123-934f40320717)

**Comment by tormozit** [comment]
Сделано в 7.50
