### ISSUE TITLE
Анализ техножурнала. Memory/MemoryPeak = 9 999 999 999

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#676]
https://github.com/user-attachments/assets/ab1f0e7a-e207-4407-9945-56e3e7371a73

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1394
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.49.1p
Инструменты разработчика. Инструмент: Анализ техножурнала
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ‘ЁбвҐ¬Ґ ­Ґ г¤ Ґвбп ­ ©вЁ гЄ § ­­л© Їгвм.
’ҐЄгй п Є®¤®ў п бва ­Ёж : 866
</details>

**Воспроизведение проблемы**
1. В инструменте "Анализ Техножурнала" неверно отображаются значения в полях Memory и MemoryPeak
2. ИР показывает значение "9 999 999 999", в то время как реальное значение "17474943872", "17488718712".

[тж_log.zip](https://github.com/user-attachments/files/17509951/_log.zip)

**Comment by tormozit** [comment]
Добавлю емкости этим числовым колонкам https://www.hostedredmine.com/issues/994812

**Comment by tormozit** [comment]
Сделано в 7.50

**Comment by PerlAmutor** [comment]
Такая же проблема была обнаружена в полях InBytes и OutBytes. Создавать новую заявку или так поправишь (если вообще будешь править)?

```
00:02.494001-2203998,CALL,1,process=rmngr,p:processName=RegMngrCntxt,p:processName=ServerJobExecutorContext,OSThread=12688,t:clientID=12425,t:applicationName=ServerProcess,t:computerName=server1,callWait=0,first=0,Interface=43b1b75a-6252-4140-bb78-390b1502e448,IName=IClusterFullText,Method=3,CallID=1965587,MName=getDataForIndexing,Memory=1474637856,MemoryPeak=2361245168,InBytes=983817458,OutBytes=0,CpuTime=1734375
02:36.102001-92789946,CALL,1,process=rmngr,p:processName=RegMngrCntxt,p:processName=ServerJobExecutorContext,OSThread=3752,t:clientID=12443,t:applicationName=ServerProcess,t:computerName=server1,callWait=0,first=0,Interface=43b1b75a-6252-4140-bb78-390b1502e448,IName=IClusterFullText,Method=28,CallID=1966500,MName=mergeReadyForAcceptFiles,Memory=1197472,MemoryPeak=2361416656,InBytes=58979954603,OutBytes=11102528472,CpuTime=82156250
02:36.102003-0,Context,1,process=rmngr,p:processName=RegMngrCntxt,p:processName=ServerJobExecutorContext,OSThread=3752,t:clientID=12443,t:applicationName=ServerProcess,t:computerName=server1,Context="
ОбщийМодуль.ПолнотекстовыйПоискСервер.Модуль : 283 : ОбновлениеИндексаППД();
	ОбщийМодуль.ПолнотекстовыйПоискСервер.Модуль : 14 : ОбновитьИндекс(НСтр(""ru = 'Обновление индекса ППД';
		ОбщийМодуль.ПолнотекстовыйПоискСервер.Модуль : 594 : ПолнотекстовыйПоиск.ОбновитьИндекс(РазрешитьСлияние, Порциями);"

```

**Comment by tormozit** [comment]
Добавлю емкости всем числовым колонкам
