### ISSUE TITLE
В консоли кода не выполняется код, где в переменной есть значение обработка Диадока

### ISSUE THREAD

**Issue by antonsm2011** [tormozit/RDT1C#677]
**Программное окружение**

Платформа: 8.3.24.1586
Режим БД: клиент-серверный
Конфигурация. Название: Управление нашей фирмой, редакция 1.6 (1.6.26.185)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Нет
Инструменты разработчика. Версия: Расширение 7.50.1e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (7.50.1e)

Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows Server 2022 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2016 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: нет

**Воспроизведение проблемы**
1. Открыл инструмент Консоль кода
2. Вставил такой код:
```
ТаблицаКодовМаркировки = илМаркировкаДвижениеКодовСервер.ТаблицаКодовМаркировкиИзПодписанногоДокументаДиадок(Док);

УстановитьПривилегированныйРежим(Истина);

ОбработкаОбъект = Обработки.КонтурЭДО.Создать();
ОбработкаОбъект.ИнициализироватьОбщийКонтекст();

Модуль_Ядро = ОбработкаОбъект.Модуль_Ядро();

ОсновнойМодуль = Модуль_Ядро.Модуль_ВызовыПМ(Неопределено);

КонтентДокумента = ОсновнойМодуль.ЭДО_ПолучитьХранилищеКонтента(ДокументДиадок);
ТекстXML = ОсновнойМодуль.ДвоичныеДанные_В_Текст(КонтентДокумента);
ДеревоКонтента = ОсновнойМодуль.XML_В_XDTO(ТекстXML);
ТабЧасть = ОсновнойМодуль.ЭДО_ПолучитьТабличнуюЧастьИзКонтентаXML(ДеревоКонтента);

Модуль_Ядро.ЗавершитьРаботуЯдра();
ОбработкаОбъект.ЗавершитьРаботуМодуля()
```
2. Нажал кнопку Выполнить
3. Получил окно с ошибкой
![изображение](https://github.com/user-attachments/assets/1179edbe-bdbb-4187-b8d7-39e99d4c6471)

Полный текст ошибки:
```
Ошибка при вызове метода контекста (ВыполнитьАлгоритм)
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.МодульОбъекта(39)}:КонтекстВыполнения.ВыполнитьАлгоритм(Параметры.ТекстДляВыполнения, Параметры.СтруктураПараметров);
{(1)}:Обработка.ВыполнитьАлгоритмВКонтексте(ПараметрыЗадания)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(23034)}:Результат = Вычислить("Обработка." + ИмяМетодаОбработки + "(ПараметрыЗадания)");
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(630)}:ирОбщий.ВыполнитьЗаданиеФормыЛкс("ВыполнитьАлгоритмВКонтексте", ПараметрыЗадания, ЭтаФорма, "ВыполнитьАлгоритм",, Кнопка, "ВыполнитьАлгоритмВФонеЗавершение",
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(570)}:ИнформацияОбОшибке = ВыполнитьЛокальноПоСтруктуреПараметров(ТекстДляВыполнения, СтруктураПараметров, ЛиСинтаксическийКонтроль, ВерсияАлгоритма, выхИнформацияОбОшибке);
{(1)}:КонтекстВыполнения.ВыполнитьЛокально(ТекстДляВыполнения, ЛиСинтаксическийКонтроль)
{ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(10435)}:ИнформацияОбОшибке = Вычислить("КонтекстВыполнения." + МетодВыполнения + "(ТекстДляВыполнения, ЛиСинтаксическийКонтроль)");
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4000)}:мПлатформа.ВыполнитьПрограммныйКодВКонтексте(КонтекстВыполнения, МетодВыполнения, ТекстДляВыполнения, ЛиСинтаксическийКонтроль);
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1525)}:ВыполнитьПрограммныйКод();
{ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1427)}:Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
{ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(82)}:ПолеТекстаАлгоритма.Нажатие(Кнопка, Ложь);

по причине:
Ошибка при вызове серверного метода.
по причине:
Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.
по причине:
Ошибка преобразования данных XDTO:
НачалоСвойства: param	Форма: Элемент	Тип: {http://www.w3.org/2001/XMLSchema}anyType
по причине:
Ошибка преобразования данных XDTO:
Значение: {http://v8.1c.ru/8.2/data/types}ExternalDataProcessorObject.КонтурДиадокЯдро	Тип: {http://v8.1c.ru/8.1/data/core}Type
по причине:
Ошибка отображения типов:
Отсутствует отображение для типа '{http://v8.1c.ru/8.2/data/types}ExternalDataProcessorObject.КонтурДиадокЯдро'
```

**Ожидаемое поведение**
Ожидал, что код выполниться без ошибки.

Я нашел, что последний раз этот код выполнялся без ошибок на версии 7.42.1е.
А в версии 7.43.1е уже возникает указанная ошибка.

**Comment by tormozit** [comment]
Нужен снимок формы консоли

**Comment by antonsm2011** [comment]
Это после выполнения с ошибкой:
![изображение](https://github.com/user-attachments/assets/fbc884d2-3b24-4a01-ba6a-b35f7a5949af)

Так выглядит, когда все корректно выполнилось:
![изображение](https://github.com/user-attachments/assets/974f232c-e578-4260-a36b-3cfb9dfe446c)

**Comment by tormozit** [comment]
Проблема возникает только в управляемом приложении. Поэтому можно обойти ее через обычное приложение.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/995173

**Comment by tormozit** [comment]
Исправлено в 7.51
