### ISSUE TITLE
Консоль запросов: Некорректное поведение анализатора текста запросов в консоли запросов при работе со строковыми выходными полями текст которых похож на SQL запрос

### ISSUE THREAD

**Issue by palsergeich** [tormozit/RDT1C#678]
**Программное окружение**

Платформа: 8.3.24.1667
Режим БД: клиент-серверный
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: НеИспользовать
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Расширение 7.49.1e
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Асинхронность запрещена: Да
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ИнструментыРазработчикаTormozit (31.12.2099 7.49.1e)
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ’ҐЄгй п Є®¤®ў п бва ­Ёж : 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Microsoft Windows Server 2012 R2 Standard 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл консоль запросов.
2. Ввел следующий текст

```
ВЫБРАТЬ 
  "Insert into SKUZN_ROUTEIN_T (LFAEMPFKDNR,ROUTENUM) values ();" КАК запрос
```

3. нажимаю выполнить и получаю сообщение 
```
Текст запроса: Строка кода 2: {(2,15)}: Таблица не найдена "SKUZN_ROUTEIN_T"
SELECT * FROM <<?>>SKUZN_ROUTEIN_T
```

**Ожидаемое поведение**
Ожидалось что как и в более ранних версиях инструментов разработчика текст строковых выходных полей анализу подвергаться не будет. Прошлая используемая версия ИР 7.28.3e там этой ошибки не возникает
Путь обхода. Разделить на строки на которые анализатор не среагирует например так
```
ВЫБРАТЬ 
  "Insert into"+" SKUZN_ROUTEIN_T (LFAEMPFKDNR,ROUTENUM) values ();" КАК запрос
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/995167

**Comment by tormozit** [comment]
Исправлено в 7.51
