### ISSUE TITLE
Конструктор запросов ИР. Неверное имя колонки. Ошибка при вызове метода контекста (Скопировать)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#68]
https://user-images.githubusercontent.com/87958986/133823105-d28fcd84-e2cb-4c3c-b2b8-bbb353b3cee6.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При клике на ячейку в нижней ТЧ на вкладке "Поля объединения" возникает ошибка при установленном флажке "Автоматически отвязывать текущее поле":

```
Ошибка при вызове метода контекста (Скопировать)
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(4141)}:		ИмяПоля = ирОбщий.АвтоУникальноеИмяВКоллекцииЛкс(СтрокаПоля.Владелец().Скопировать(ОтборКонкурентов, "НИмя"), ИмяПоля, "НИмя",,,, Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(8425)}:			АвтоПсевдонимОтвязанногоПоля = ПолучитьАвтоПсевдонимПоля(СтрокаДляОтвязки, ВыбраннаяЧасть);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2760)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(930)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(891)}:	Результат = ВыполнитьКоманду(Команда);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(284)}:		Результат = ЭкземплярКомпоненты.Нажатие(Кнопка);
по причине:
Неверное имя колонки

```

Пример запроса:

```
ВЫБРАТЬ
	"Тест" КАК Поле1,
	NULL КАК Поле2
ОБЪЕДИНИТЬ ВСЕ
ВЫБРАТЬ
	NULL КАК Поле1,
	"Тест" КАК Поле2
```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/933692

**Comment by tormozit** [comment]
Исправлено в 6.09.3
