### ISSUE TITLE
Консоль запросов. Обработка результата. Полный текст. Многострочные параметры

### ISSUE THREAD

**Issue by froloid** [tormozit/RDT1C#680]
Платформа: 8.3.21.1302
Режим БД: клиент-серверный
Конфигурация. Название: 1С-Логистика: Управление складом 3.0 (3.0.10.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_8
Конфигурация. Режим использования синхронных вызовов: Использовать
Инструменты разработчика. Версия: Портативный 7.37.2p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows Server 2019 Standard 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС Текущая кодовая страница: 866
Клиент-Сервер. Пинг: 1мс

**Воспроизведение проблемы**
1. Открыл консоль запросов и задал следующие параметры:
![image](https://github.com/user-attachments/assets/b32ff71f-8bb7-4ddc-b099-b335b47d4e21)

2. Написал запрос и код обработки результата.
3. Нажал кнопку "Сформировать .. полный текст .." на вкладке обработки результата.
4. Получил текст в котором значение многострочного параметра приводит к ошибке в модуле, так как закомментирована только первая строка текста:
![image](https://github.com/user-attachments/assets/7c6704a1-7ea6-41a9-8086-4340a7abbfae)
5. После нажатия кнопки "Сформировать текст .." на закладке "Текст запроса" получаю текст, в котором есть установка только одного из 3-х параметров:
![image](https://github.com/user-attachments/assets/e2e165aa-419e-4089-96a5-608ac3fa229d)

**Ожидаемое поведение**
По пункту 4 ожидаю, что все строки параметра будут закомментированы.

По пункту 5 ожидаю, что как минимуим будет выведено значение параметра "СтрокаТЗ" (с учётом п. 4), так как он используется при вычислении параметра "ТЗ".

**Comment by tormozit** [comment]
По п.4 ошибку воспроизвел https://www.hostedredmine.com/issues/995864

**Comment by tormozit** [comment]
По п. 5 умышленное поведение, т.к. только этот параметр использован в тексте запроса.

**Comment by froloid** [comment]
> По п. 5 умышленное поведение, т.к. только этот параметр использован в тексте запроса.

Логично воспринимать инструмент шире чем просто "текст запроса".

**Comment by tormozit** [comment]
Исправлено в 7.52
