### ISSUE TITLE
Консоль запросов. Ошибка при вызове метода контекста (ПолучитьВремяИзменения)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#681]
https://github.com/user-attachments/assets/a816bdd8-b59f-4ece-8b80-cf9f455e802f

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.25.1394
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.95)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.55.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ‘ЁбвҐ¬Ґ ­Ґ г¤ Ґвбп ­ ©вЁ гЄ § ­­л© Їгвм.
’ҐЄгй п Є®¤®ў п бва ­Ёж : 866

</details>

**Воспроизведение проблемы**
1. При выполнении любых запросов в Консоли Запросов, при сохранении запроса и при событии автосохранения возникает ошибка (как в файловой так и в клиент-серверных базах):

```
Ошибка при вызове метода контекста (ПолучитьВремяИзменения)
{ВнешняяОбработка.ирКлиент.МодульОбъекта(13583)}:		СтруктураВосстановления.ДатаИзменения = ОткрытыйФайл.ПолучитьВремяИзменения();
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(1202)}:		ФайлВыбран = ирКлиент.СохранитьФайлВКонсолиСВосстановлениемЛкс(ДиалогВыбораФайла, ИмяФайла, мИмяОткрытогоФайла, КопияДерева, мСтруктураВосстановления, ЗапрашиватьИмяФайла, ФайлВосстановленияОбрезан);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(1919)}:		СохранитьВФайл(,, "*", Ложь, Истина);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(1946)}:		СохранитьФайлДляВосстановления();
по причине:
Ошибка доступа к файлу: 

```

**Comment by tormozit** [comment]
Не удалось воспроизвести. Нужно видео, начиная с открытия консоли запросов

**Comment by dmitri-0** [comment]
Подтверждаю
Аналогичная ошибка

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/997283

**Comment by tormozit** [comment]
Исправлено в 7.55.2
