### ISSUE TITLE
Редактор объекта. Значение не является значением объектного типа (ИмяСтраницы)

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#682]
**Программное окружение**

Платформа: 8.3.21.1624
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.55.3e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ВремПоднятиеВерсииПротоколаТСД ()
Расширения. Патч_МРМ2 ()
Расширения. ВЛК_Доработки ()
Расширения. ЗакрытиеОрдераСВычеркамиВРучную ()
Расширения. ЭР_Обмен_КА_БП (1.0.2.29)
Расширения. зг_ЗУП (1.0.2.20)
Расширения. ИнструментыРазработчикаTormozit (7.55.3e)
Расширения. Оптимизации ()
Расширения. ФиксПОТ ()
Расширения. ПереходНаЮКасса ()
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ’ҐЄгй п Є®¤®ў п бва ­Ёж : 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Datacenter 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыть любой объект с табличными частями в редакторе объектов
2. Перейти на вкладку "Табличные части" во вкладке "Объект"
3. Тут же получить ошибку 
![изображение](https://github.com/user-attachments/assets/9d6a8a4e-203a-4dec-ba23-108a07179a87)

```
Значение не является значением объектного типа (ИмяСтраницы)
{ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(6107)}:Если ТабличноеПолеРегистра.Имя <> ТекущаяСтрока.ИмяСтраницы Тогда
{ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(6126)}:ОбъектМД =  КонтекстСтрокиРегистра(ТабличноеПолеРегистра, Кнопка, ИмяТаблицыБДРегистра);

```

**Ожидаемое поведение**

Отсутствие ошибки

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/997595

**Comment by tormozit** [comment]
Исправлено в 7.55.4

**Comment by PerlAmutor** [comment]
В Портативном варианте такая же ошибка, но релиза 7.55.4p на сайте не выложено.

**Comment by tormozit** [comment]
Выпуск исправительной версии портативного варианта не планируется.
