### ISSUE TITLE
Консоль кода. Поле объекта не обнаружено (Тип)

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#683]
**Программное окружение**

Платформа: 8.3.21.1624
Режим БД: клиент-серверный
Конфигурация. Название: 1С:Комплексная автоматизация 2 (2.4.13.187)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_14
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Конфигурация. Использовать обычные формы в управляемом приложении: Да
Инструменты разработчика. Версия: Расширение 7.55.3e
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Асинхронность запрещена: Нет
Инструменты разработчика. Разрешены имитаторы: Да
Расширения. ВремПоднятиеВерсииПротоколаТСД ()
Расширения. Патч_МРМ2 ()
Расширения. ВЛК_Доработки ()
Расширения. ЗакрытиеОрдераСВычеркамиВРучную ()
Расширения. ЭР_Обмен_КА_БП (1.0.2.29)
Расширения. зг_ЗУП (1.0.2.20)
Расширения. ИнструментыРазработчикаTormozit (7.55.3e)
Расширения. Оптимизации ()
Расширения. ФиксПОТ ()
Расширения. ПереходНаЮКасса ()
Расширения. ...
Клиент. Приложение: Управляемое приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ’ҐЄгй п Є®¤®ў п бва ­Ёж : 866
Клиент-Сервер. Пинг: 0мс
Сервер. ОС: Майкрософт Windows Server 2019 Datacenter 64-разрядная Русский
Сервер. Процесс: 64б
Сервер. Отладка: tcp

**Воспроизведение проблемы**
1. Открыл консоль кода
2. Добавил код, создающий какой-либо объект метаданных
`Ы = Справочники.Партнеры.СоздатьЭлемент();`
3. Нажал "Выполнить"
![изображение](https://github.com/user-attachments/assets/637abfa9-63fc-4774-8389-644c5b4b9d0d)

> Поле объекта не обнаружено (Тип)
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(385)}:ПредставлениеТипа = СтрокаПараметра.Значение.Тип;
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(671)}:ОбновитьЗначенияПараметровВыхода(СтруктураПараметров, Истина);
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(685)}:ВыполнитьАлгоритмЗавершение(РезультатЗадания.ВремяНачала, РезультатЗадания.СтруктураПараметров);
> {(1)}:ЭтаФормаИлиОбработка.ВыполнитьАлгоритмВФонеЗавершение(, Результат)
> {ИнструментыРазработчикаTormozit ОбщийМодуль.ирОбщий.Модуль(23130)}:Выполнить("ЭтаФормаИлиОбработка." + ОбработчикЗавершения + "(, Результат)");
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(635)}:ирОбщий.ВыполнитьЗаданиеФормыЛкс("ВыполнитьАлгоритмВКонтексте", ПараметрыЗадания, ЭтаФорма, "ВыполнитьАлгоритм",, Кнопка, "ВыполнитьАлгоритмВФонеЗавершение",
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(575)}:ИнформацияОбОшибке = ВыполнитьЛокальноПоСтруктуреПараметров(ТекстДляВыполнения, СтруктураПараметров, ЛиСинтаксическийКонтроль, ВерсияАлгоритма, выхИнформацияОбОшибке);
> {(1)}:КонтекстВыполнения.ВыполнитьЛокально(ТекстДляВыполнения, ЛиСинтаксическийКонтроль)
> {ИнструментыРазработчикаTormozit Обработка.ирПлатформа.МодульОбъекта(10653)}:ИнформацияОбОшибке = Вычислить("КонтекстВыполнения." + МетодВыполнения + "(ТекстДляВыполнения, ЛиСинтаксическийКонтроль)");
> {ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(4067)}:мПлатформа.ВыполнитьПрограммныйКодВКонтексте(КонтекстВыполнения, МетодВыполнения, ТекстДляВыполнения, ЛиСинтаксическийКонтроль);
> {ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1605)}:ВыполнитьПрограммныйКод();
> {ИнструментыРазработчикаTormozit Обработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(1505)}:Результат = ВыполнитьКоманду(Команда,, ОбновитьКонтекст);
> {ИнструментыРазработчикаTormozit Обработка.ирКонсольКода.Форма.Форма.Форма(82)}:ПолеТекстаАлгоритма.Нажатие(Кнопка, Ложь);
> 

**Ожидаемое поведение**

Отсутствие ошибок

**Comment by tormozit** [comment]
Нужна полная картинка инструмента

**Comment by KovAlexey** [comment]
![изображение](https://github.com/user-attachments/assets/d23b3103-6f7a-4085-b158-2c22264ffaf5)

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/997596

**Comment by tormozit** [comment]
Исправлено в 7.55.4
