### ISSUE TITLE
Редактор изменений на узлах. Подбор и обработка объектов БД. Поле не найдено "Т.ОбластьДанныхОсновныеДанные"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#684]
https://github.com/user-attachments/assets/2645ca5c-eb3d-4f25-a3db-bb5fae38a201

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.26.1498
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.162)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.55.2p
Инструменты разработчика. Инструмент: Подбор и обработка объектов БД
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ‘ЁбвҐ¬Ґ ­Ґ г¤ Ґвбп ­ ©вЁ гЄ § ­­л© Їгвм.
’ҐЄгй п Є®¤®ў п бва ­Ёж : 866

</details>

**Воспроизведение проблемы**
1. Открыл "Редактор изменений на узалх"
2. Выделил регистр накопления
3. Вызвал "Открыть обработку объектов выделенных типов"
4. Получил ошибку:

```
Ошибка при вызове метода контекста (НайтиПараметры)
{ВнешняяОбработка.ирОбщий.МодульОбъекта(11018)}:	ОписанияПараметров = Запрос.НайтиПараметры(); // Здесь могут быть ложные ошибки синтаксического контроля
{ВнешняяОбработка.ирОбщий.МодульОбъекта(11078)}:	ЗаполнитьПараметрыСхемыПоЗапросуЛкс(СхемаКомпоновкиДанных, Запрос);
{ВнешняяОбработка.ирОбщий.МодульОбъекта(11096)}:	СоздатьИлиОбновитьНаборДанныхЗапросПоЗапросуЛкс(СхемаКомпоновки, Запрос, ИмяНабораДанных, ПредставленияПолей, АвтоЗаполнениеДоступныхПолей, ПредставленияПапок);
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ПодборИОбработка.Форма(1001)}:	лСхемаКомпоновки = ирОбщий.СоздатьСхемуКомпоновкиПоЗапросу(Запрос);
{ВнешняяОбработка.ирПодборИОбработкаОбъектов.Форма.ПодборИОбработка.Форма(2035)}:		НастроитьКомпоновщик(СохранятьТекущиеНастройки, ЗагружатьТекущиеНастройки, НастройкиНабораТаблицБД);
{ВнешняяОбработка.ирРедакторИзмененийНаУзлах.Форма.Форма.Форма(1878)}:	ФормаОбработки.УстановитьОбластьПоиска(ОбластьПоиска);
по причине:
{(52, 48)}: Поле не найдено "Т.ОбластьДанныхОсновныеДанные"
И _Изменения_.ОбластьДанныхОсновныеДанные = Т.<<?>>ОбластьДанныхОсновныеДанные

```

**Comment by tormozit** [comment]
У меня не воспроизвелось. Лови запрос в отладчике и покажи как он выглядит.

**Comment by PerlAmutor** [comment]
```
ВЫБРАТЬ  
Т.Период КАК Период, 
Т.Регистратор КАК Регистратор, 
Т.НомерСтроки КАК НомерСтроки, 
Т.Активность КАК Активность, 
Т.ВидДвижения КАК ВидДвижения, 
Т.Организация КАК Организация, 
Т.НематериальныйАктив КАК НематериальныйАктив, 
Т.Подразделение КАК Подразделение, 
Т.ГруппаФинансовогоУчета КАК ГруппаФинансовогоУчета, 
Т.НаправлениеДеятельности КАК НаправлениеДеятельности, 
Т.Амортизация КАК Амортизация, 
Т.АмортизацияРегл КАК АмортизацияРегл, 
Т.АмортизацияНУ КАК АмортизацияНУ, 
Т.АмортизацияПР КАК АмортизацияПР, 
Т.АмортизацияВР КАК АмортизацияВР, 
Т.АмортизацияЦФ КАК АмортизацияЦФ, 
Т.АмортизацияНУЦФ КАК АмортизацияНУЦФ, 
Т.АмортизацияПРЦФ КАК АмортизацияПРЦФ, 
Т.АмортизацияВРЦФ КАК АмортизацияВРЦФ, 
Т.РезервПереоценкиАмортизации КАК РезервПереоценкиАмортизации, 
Т.РезервПереоценкиАмортизацииРегл КАК РезервПереоценкиАмортизацииРегл, 
Т.ХозяйственнаяОперация КАК ХозяйственнаяОперация, 
Т.КорОрганизация КАК КорОрганизация, 
Т.КорПодразделение КАК КорПодразделение, 
Т.КорНаправлениеДеятельности КАК КорНаправлениеДеятельности, 
Т.КорСтатьяРасходов КАК КорСтатьяРасходов, 
Т.КорАналитикаРасходов КАК КорАналитикаРасходов, 
Т.КорГруппаФинансовогоУчета КАК КорГруппаФинансовогоУчета, 
Т.РесурсВыработанныйЗаТекущийПериод КАК РесурсВыработанныйЗаТекущийПериод, 
Т.РесурсВыработанныйЗаПрошлыйПериод КАК РесурсВыработанныйЗаПрошлыйПериод, 
Т.РесурсВыработанныйЗаТекущийПериодБУ КАК РесурсВыработанныйЗаТекущийПериодБУ, 
Т.РесурсВыработанныйЗаПрошлыйПериодБУ КАК РесурсВыработанныйЗаПрошлыйПериодБУ, 
Т.СтоимостьДляВычисленияАмортизации КАК СтоимостьДляВычисленияАмортизации, 
Т.СтоимостьДляВычисленияАмортизацииРегл КАК СтоимостьДляВычисленияАмортизацииРегл, 
Т.ОстатокОбесцененияУпр КАК ОстатокОбесцененияУпр, 
Т.ОстатокОбесцененияРегл КАК ОстатокОбесцененияРегл, 
Т.ЭтоДоначисление КАК ЭтоДоначисление, 
Т.ЭтоДоначислениеБУ КАК ЭтоДоначислениеБУ, 
Т.ПорядокУчетаУУ КАК ПорядокУчетаУУ, 
Т.ПорядокУчетаБУ КАК ПорядокУчетаБУ, 
Т.ПорядокНачисленияАмортизацииУУ КАК ПорядокНачисленияАмортизацииУУ, 
Т.ПорядокНачисленияАмортизацииБУ КАК ПорядокНачисленияАмортизацииБУ, 
Т.НастройкаХозяйственнойОперации КАК НастройкаХозяйственнойОперации, 
Т.ИдентификаторФинЗаписи КАК ИдентификаторФинЗаписи, 0 КАК СлужебноеПоле3463
ИЗ
РегистрНакопления.АмортизацияНМА КАК Т

 ВНУТРЕННЕЕ СОЕДИНЕНИЕ РегистрНакопления.АмортизацияНМА.Изменения КАК _Изменения_
	ПО _Изменения_.Узел = &Узел
	И _Изменения_.Регистратор = Т.Регистратор
	И _Изменения_.ОбластьДанныхОсновныеДанные = Т.ОбластьДанныхОсновныеДанные
```

**Comment by PerlAmutor** [comment]
Вообще интересная картина, в состав Общего Реквизита "ОбластьДанныхОсновныеДанные" регистр накопления входит, но это поле невозможно выбрать в конструкторе запросов платформы, но она попадает в выборку полей, если они выбираются "звёздочкой":

![image](https://github.com/user-attachments/assets/9f931b2c-3aeb-497c-b469-f721703eae11)

В тоже время этот реквизит отсутствует в основной таблице регистра.

В структуре SQL таблиц этот реквизит присутствует во всех таблицах регистра накопления. Скорее всего запрос надо переделывать так, чтобы ВНУТРЕННЕЕ СОЕДИНЕНИЕ не связывало реквизиты двух таблиц, а ОбластьДанныхОсновныеДанные передавалось в качестве параметра из Параметра Сеанса. Либо вообще это условие соединения убирать, т.к. платформа обычно сама подставляет эти условия.

P.S.: В ERP напрямую поле вырезается в некоторых участках из запросов:
![image](https://github.com/user-attachments/assets/5b3e36ad-c46f-4d9f-89b8-2c542186bb45)

**Comment by tormozit** [comment]
Можешь проверить на 8.3.25?

**Comment by PerlAmutor** [comment]
> Можешь проверить на 8.3.25?

Проверил на 8.3.24, 8.3.25 - все тоже самое.

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/997740

**Comment by tormozit** [comment]
Исправлено в 7.57
