### ISSUE TITLE
Консоль компоновок данных. Просьба поменять поведение с Alt+F в Таблице значений

### ISSUE THREAD

**Issue by KovAlexey** [tormozit/RDT1C#685]
Консоль компоновок данных.

То, что по нажатию поиска - условие поиска ставится в отборы кажется сильно некорректным и непрозрачным.

1) *Область и назначение* 
В этом поле мы работаем с результатами компоновки, а не с самой компоновкой. А в итоге, получается, поиск в результатах приводит к непрозрачному изменению настроек  схемы компоновки. Кмк на такое поведение нужны отдельные кнопки
2) *Ключевое* 
В компоновке  может банально не иметься тех отборов, по которым хочется отобрать колонку
3) *Производительность, применимость* 
Результаты компоновки могут меняться от отборов, порой в правильную сторону. А задача может требовать разобраться с некорректной информацией, с чем помогает возможность отфильтровать строки.

**Что изменится, если поведение поменять?**
1) Можно будет работать с результатом компоновки данных, как с полноценной таблицей и более удобно ее просматривать.
2) А так же будут работать все условия для отбора.
3) Прозрачность и понятность работы инструмента повысится.
4) Для применения фильтра к результату не надо будет переформировывать схему, что порой бывает довольно тяжелым действием.

Способ обхода:
Копировать таблицу в отдельное окно, но это очень неудобно

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/997727

**Comment by tormozit** [comment]
Сделано в 7.57
