### ISSUE TITLE
Редактор объекта БД. Долгое сохранение документа в режиме обмена данными

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#687]
![image](https://github.com/user-attachments/assets/b94c58fe-d9b3-48a9-a7d8-c2abfe995559)

[ЗаписьДокументаИР_РОБ.zip](https://github.com/user-attachments/files/18114686/_.zip)

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.3.26.1498
Режим БД: файловый
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.17.162)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_24
Конфигурация. Режим использования синхронных вызовов: Использовать
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 7.56.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Да
Инструменты разработчика. Серверный модуль БСП: Да
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Да
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ‘ЁбвҐ¬Ґ ­Ґ г¤ Ґвбп ­ ©вЁ гЄ § ­­л© Їгвм.
’ҐЄгй п Є®¤®ў п бва ­Ёж : 866

</details>

**Воспроизведение проблемы**
1. Есть документ в котором табличная часть содержит около 90к строк и 30 колонок
2. Меняю одну ячейку на определенной строке
3. Жму "Записать все" (это документ не делающий движений, без проведения)
4. Время записи 300 секунд...

Замеры производительности прилагаю. Может получится как-то оптимизировать скорость записи?

**Comment by tormozit** [comment]
Проверь в варианте поставки "Расширение"

**Comment by tormozit** [comment]
Цикл заполнения табличной части заменю на быстрый метод. Но это лишь 15% от общей длительности. Остальное время занимают клиент-серверные операции

1. сериализовали на клиенте
2. передали на сервер
3. десериализовали на сервере
4. записали на сервере
5. сериализовали на сервере
6. передали на клиент
7. десериализовали на клиенте

 Сильно там не наоптимизируешь.

**Comment by tormozit** [comment]
В качестве альтернативы предлагаю использовать инструмент "Подбор и обработка объектов" с флажком "Выполнять на сервере". Он будет выполнять такую операцию значительно быстрее, т.к. пункты 1-3 и 5-7 не выполняет.

**Comment by tormozit** [comment]
В файловой базе в обычном приложении еще можно попробовать отключить в общих параметрах записи флажок "Объекты на сервере", чтобы устранить клиент-серверные операции.

**Comment by PerlAmutor** [comment]
> Проверь в варианте поставки "Расширение"

С Расширением картина немного драматичнее, почти 600 секунд.

![image](https://github.com/user-attachments/assets/1bb19ffc-6fd4-4393-92d8-35437ea517ec)


[ЗаписьДокументаИР_Расширение.zip](https://github.com/user-attachments/files/18127972/_.zip)

**Comment by tormozit** [comment]
создал задачу https://www.hostedredmine.com/issues/998310

**Comment by tormozit** [comment]
Сделано в 7.57
