### ISSUE TITLE
Ошибка в отчете ирАнализПравДоступа - НезависимыеПраваПодчиненныхОбъектов

### ISSUE THREAD

**Issue by msv2244** [tormozit/RDT1C#688]
В отчете ирАнализПравДоступа в модуле объекта при чтении свойств роли из файла xml перепутаны свойства:

					ИначеЕсли ЧтениеXML.ЛокальноеИмя = "**setForAttributesByDefault**" Тогда
						ЧтениеXML.Прочитать();
						СтрокаРоли.**НезависимыеПраваПодчиненныхОбъектов** = Булево(ЧтениеXML.Значение);
					ИначеЕсли ЧтениеXML.ЛокальноеИмя = "**independentRightsOfChildObjects**" Тогда
						ЧтениеXML.Прочитать();
						СтрокаРоли.**УстанавливатьПраваДляРеквизитовИТабличныхЧастейПоУмолчанию** = Булево(ЧтениеXML.Значение);

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/998416

**Comment by tormozit** [comment]
Исправлено в 7.58
