### ISSUE TITLE
Редактор объекта БД: ошибка при открытии

### ISSUE THREAD

**Issue by john-doe-1c** [tormozit/RDT1C#689]
База почти пустая. Пользователей в базе нет - возможно причина в этом.
Открываю редактор объекта БД, получаю ошибку:

```
Значение не является значением объектного типа (ВариантИнтерфейсаКлиентскогоПриложения)
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКэш.Модуль(2106)}:Возврат Настройки.ВариантИнтерфейсаКлиентскогоПриложения = Вычислить("ВариантИнтерфейсаКлиентскогоПриложения").Такси; // В 8.2 нет
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(20975)}:Или Не ирКэш.ЛиСеансТолстогоКлиентаУПЛкс()
{ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Форма.Форма.Форма(1066)}:ирКлиент.УстановитьПрикреплениеФормыВУправляемомПриложенииЛкс(Этаформа);
{ИнструментыРазработчикаTormozit ОбщийМодуль.ирКлиент.Модуль(21295)}:Форма.Открыть();
{ИнструментыРазработчикаTormozit Обработка.ирРедакторОбъектаБД.Команда.Команда1.МодульКоманды(4)}:ирКлиент.ОткрытьФормуЛкс("Обработка.ирРедакторОбъектаБД.Форма");

```

Сис. инфо:
> Платформа: 8.3.24.1691
> Режим БД: файловый
> Конфигурация. Название:  ()
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_9
> Конфигурация. Режим использования синхронных вызовов: ИспользоватьСПредупреждениями
> Конфигурация. Использовать обычные формы в управляемом приложении: Нет
> Инструменты разработчика. Версия: Расширение 7.57.1e
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Асинхронность запрещена: Нет
> Инструменты разработчика. Разрешены имитаторы: Да
> Клиент. Приложение: Управляемое приложение 64б
> Клиент. Проверка модальных вызовов: Да
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. Отладка разрешена: Да
> Клиент. Постоянный кэш метаданных: Да
> Клиент. ОС: Microsoft Windows Server 2019 Standard 64-bit Русский
> Клиент. ОС от имени администратора: Нет
> Клиент. ОС выполнение BAT: Да
> Клиент. ОС Active code page: 866

**Comment by tormozit** [comment]
Ошибку подтверждаю https://www.hostedredmine.com/issues/998419

**Comment by tormozit** [comment]
Исправлено в 7.58
