### ISSUE TITLE
Конструктор Запросов ИР. Добавляются и пропадают новые поля объединений.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#69]
https://user-images.githubusercontent.com/87958986/133914704-c3cf25e4-ccc3-4d00-9047-3bfa4288358c.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.3p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

После исправления ошибок этой задачи: https://github.com/tormozit/RDT1C/issues/68
появилось странное поведение в Конструкторе Запросов ИР на вкладке "Поля объединения".
В некоторых случаях добавляются новые поля к объединению, которые затем исчезают при переключении на другую вкладку. Не вполне понятно ожидаемое это поведение или ошибка.

```
ВЫБРАТЬ
	"Тест" КАК Поле1,
	NULL КАК Поле2
ОБЪЕДИНИТЬ ВСЕ
ВЫБРАТЬ
	NULL КАК Поле1,
	"Тест" КАК Поле2
```

**Comment by tormozit** [comment]
Вроде бы логично работает. Ты отвязываешь поле от существующих полей объединения. Поэтому оно создает новое поле объединения.

**Comment by PerlAmutor** [comment]
Тогда мне не вполне понятно почему некоторые новые поля добавляются в запрос, а некоторые удаляются, хотя были добавлены тем же самым образом:


https://user-images.githubusercontent.com/87958986/133917615-dc3dfc89-993c-4c58-b950-df5991a2db85.mp4

А, ну разобрался. Удаляются поля где не подвязаны поля с псевдонимами. Тогда все логично.

**Comment by tormozit** [comment]
В таблице "Поля объединения" отсутствие связи с выбранным полем показывается картинкой числа. А значение NULL - является явным. Но при сборке текста на места выбранных полей, где связь отсутствует, подставляется тоже NULL, но динамически. Таким образом есть явный NULL, который виден в выбранных полях и есть динамический, который добавляется при сборке текста для полей объединения без связи с конкретной частью объединения. 
Если поле объединения имеет 0 связей с выбранными полями, то оно удаляется автоматически автоматически (при сборке текста, либо при переключении страниц, либо после ответа на вопрос).
