### ISSUE TITLE
Загрузка табличных данных - опциональное заполнение нового объекта методом Заполнить(неопределено)

### ISSUE THREAD

**Issue by 240596448** [tormozit/RDT1C#691]
Просьба: сделать опциональным (не)заполнение объекта при создании методом `Объект.Заполнить(Неопределено)`

Цель: обходить ошибки/особенности метода в типовых конфигурациях без доработок "кода на замке".

Пример из ЕРП (Справочник.Серии): отсуствует обработка значения "Неопределено"
```bsl
Процедура ОбработкаЗаполнения(ДанныеЗаполнения, ТекстЗаполнения, СтандартнаяОбработка)
	ВидНоменклатуры = ДанныеЗаполнения.ВидНоменклатуры;
	...
```

**Comment by tormozit** [comment]
При выполнении какой операции возникает ошибка? Желательно сразу стек.

**Comment by 240596448** [comment]
> При выполнении какой операции возникает ошибка? Желательно сразу стек.

На последней закладке: загрузка или загрузка без записи, т.е. когда выполняется создание объекта.

`.. ирОбщий.Объект.СоздатьСсылочныйОбъектПоМетаданнымЛкс(...)`
`.... Объект.Заполнить(Неопределено);`  (строка 2012)
(это вроде единственное место с заполнением)

**Comment by tormozit** [comment]
Создал задачу https://www.hostedredmine.com/issues/998773

**Comment by tormozit** [comment]
Сделано в 7.58
