### ISSUE TITLE
Журнал Регистрации. Ошибка при открытии.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#697]
https://github.com/user-attachments/assets/0d38201f-db77-4472-a18f-cc0857fe761b

<details>  
<summary>Информация для технической поддержки</summary>  

Платформа: 8.5.1.189
Режим БД: файловый
Конфигурация. Название:  ()
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_20
Конфигурация. Режим использования синхронных вызовов: НеИспользовать
Инструменты разработчика. Версия: Портативный 7.59.1p
Инструменты разработчика. Инструмент: Прочее
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль БСП: Нет
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. Отладка разрешена: Нет
Клиент. Постоянный кэш метаданных: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. ОС от имени администратора: Нет
Клиент. ОС выполнение BAT: Да
Клиент. ОС ‘ЁбвҐ¬Ґ ­Ґ г¤ Ґвбп ­ ©вЁ гЄ § ­­л© Їгвм.
’ҐЄгй п Є®¤®ў п бва ­Ёж : 866

</details>

**Воспроизведение проблемы**
1. При попытке открыть инструмент "Журнал Регистрации" всплывает ошибка:

```
В модуле формы отсуствует экпортный метод ПоследниеОтборыНажатие
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9339)}:		ВызватьИсключение ирОбщий.СтрШаблонЛкс("В модуле формы отсуствует экпортный метод %1", ОбработчикКнопки);
{ВнешняяОбработка.ирКлиент.МодульОбъекта(9123)}:	ПоследниеВыбранныеЗаполнитьПодменюЛкс(ЭтаФорма, КоманднаяПанель.Кнопки.ПоследниеОтборы, ТабличноеПоле, Новый Действие("КлсКомандаНажатие"), "Отборы");
{ВнешняяОбработка.ирАнализЖурналаРегистрации.Форма.Форма.Форма(466)}:	ирКлиент.ОбновитьПодменюПоследнихОтборовЛкс(ЭтаФорма, ЭлементыФормы.КоманднаяПанельЖурнала, ЭлементыФормы.ТаблицаЖурнала);
{ВнешняяОбработка.ирАнализЖурналаРегистрации.Форма.Форма.Форма(167)}:	ОбновитьПодменюПоследнихОтборов();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(154)}:		Форма.Открыть();
{ВнешняяОбработка.ирПортативный.Форма.Форма.Форма(136)}:	ОткрытьИнструмент(СтрокаИнструмента);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/999056

**Comment by tormozit** [comment]
Исправлено в 7.59.2
