### ISSUE TITLE
Консоль запросов. HTML редактор, не работает Enter после подсказки

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#7]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.20.1363
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Расширение 6.02.1e
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Разрешены имитаторы: Да
> Расширения. ИнструментыРазработчикаTormozit (6.02.1e)
> Клиент. ОС: Microsoft Windows 7 Ultimate  64-bit Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

При ручном вводе текста запроса в HTML редакторе на некоторых ключевых словах не работает перенос строки (клавиша Enter). Например такими ключевыми словами являются "ИЗ" и "ГДЕ". Судя по всему клавиша Enter перестает работать после быстро всплывающей подсказки. На видео не видно как я многократно жму Enter на позициях "ИЗ" и "ГДЕ", но "отпускает" только когда я стрелочками "Влево"/"Вправо" перемещаю курсор.

```
ВЫБРАТЬ ПЕРВЫЕ 10
*
ИЗ
	РегистрНакопления.ПрочиеРасходыНезавершенногоПроизводства КАК Т
ГДЕ
	ИСТИНА
```

https://user-images.githubusercontent.com/87958986/127182997-3cec4b48-7012-447b-92e3-903e1b255896.mp4

**Comment by tormozit** [comment]
Напоминаю, что такие видео желательно снимать специализированными инструментами, которые визуализируют клики и нажатия клавиш.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/931313

**Comment by tormozit** [comment]
Исправлено в 6.02.2
