### ISSUE TITLE
Консоль запросов. Конструктор запросов ИР. Прерывание Анализа конфигурации.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#70]
https://user-images.githubusercontent.com/87958986/133917450-23143778-74aa-4f9a-ae96-ab4782267f0f.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.3p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При прерывании "Анализа конфигурации" при вызове Конструктора Запросов ИР - отсутствуют метаданные. Например могут отсутствовать Регистры Сведений, Регистры Накоплений и т.д., в зависимости от того когда было сделано прерывание.

**Comment by tormozit** [comment]
Не знаю, специально ты так делаешь или это такой проигрыватель видео. Но на твоих видео (проверил в разных браузерах) не полностью видно строку состояния - один из важнейших элементов интерфейса. Поэтому сложно анализировать ситуацию. Можно сделать чтобы она была видна полностью?

**Comment by PerlAmutor** [comment]
Поправил. Следующие записи будут со строкой состояния. Видео в этой теме перезалил.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934084

**Comment by tormozit** [comment]
Исправлено в 6.10.1
