### ISSUE TITLE
Конструктор запросов ИР. Группировка с суммированием ресурсов или числовых полей

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#71]
https://user-images.githubusercontent.com/87958986/133915411-c82112d2-f42c-49b6-bb13-6566252adb17.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> 
> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.3p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Хотелось бы добавить функцию автоматического добавления функции СУММ() числовым полям при группировке полей в Конструкторе Запросов ИР. В родном Конструкторе Запросов 1С тоже почему-то не все ресурсы добавляются в нижнюю ТЧ, при этом платформа 1С предлагает просуммировать номера строк, что неверно.

Возможно было бы полезным добавить "шаблон агрегации ресурсов" (для регистров накопления), например:

```
СУММА(ВЫБОР КОГДА Т.ВидДвижения = ЗНАЧЕНИЕ(ВидДвиженияНакопления.Расход) ТОГДА
    -Т.СтоимостьРегл
ИНАЧЕ
    Т.СтоимостьРегл
КОНЕЦ) КАК СтоимостьРегл
```

**Comment by tormozit** [comment]
Согласен. В моем конструкторе эта задача решается менее удобно при большом числе агрегируемых полей. Создал задачу https://www.hostedredmine.com/issues/934182

**Comment by tormozit** [comment]
Реализовано в 6.11
