### ISSUE TITLE
Конструктор запросов ИР. Падает платформа при вызове команды "Все типы ссылок"

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#74]
https://user-images.githubusercontent.com/87958986/133916964-451d6cce-ada0-4f1e-9f26-3edfa6b0ecb4.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.3p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При вызове команды "Все типы ссылок" в Конструкторе Запросов ИР падает платформа.
Аналогично при вызове "Объединение ссылочных таблиц" и "Объединение ссылочных таблиц изменений"

**Comment by tormozit** [comment]
Ошибку воспроизвел
https://www.hostedredmine.com/issues/934085
https://www.hostedredmine.com/issues/934086

**Comment by PerlAmutor** [comment]
Не похоже, что дело в стеке. Т.к. та же самая команда в Консоли Запросов генерирует текст нормально и быстро.

**Comment by tormozit** [comment]
Вроде я четко обозначил в каком действии переполняется стек.  Команда в консоли запросов делает не то, что указано в задачах по исправлению ошибки. Смотри ее раз на исправленную ошибку в консоли запросов. Тогда поймешь, что нужно включить структуру запроса.
Я уже все подробно изучил, исправил и проверил. Просто дождись релиза.

**Comment by tormozit** [comment]
Исправлено в 6.10.1
