### ISSUE TITLE
Конструктор Запросов ИР. Перехват клавиш. Ошибка при вызове метода контекста

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#75]
https://user-images.githubusercontent.com/87958986/133917282-6c02595b-c6a4-4b33-88b3-b73b0a95f34f.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.09.3p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При использовании команды "К полю объединения" в Конструкторе Запросов ИР идет переключение на неактивную вкладку "Поля объединения", если при этом нажать на любую клавишу на клавиатуре (пробовал Лево, Вправо, Вниз, Вверх), то в сообщения выводятся ошибки:

`{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(78)}: Ошибка при вызове метода контекста (Свойство): Задано неправильное имя атрибута структуры`

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.10.1
