### ISSUE TITLE
Конструктор запросов ИР. Падает платформа при вызове команды "Все типы ссылок

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#76]
https://user-images.githubusercontent.com/87958986/133954166-3c4be792-a2d7-40b9-922b-c691a71ddd8d.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

Платформа: 8.3.19.1229
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.10.1p
Инструменты разработчика. Инструмент: Конструктор запроса
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Заявленное исправление ошибки https://github.com/tormozit/RDT1C/issues/74 не произошло. Поэтому повторно.

При вызове команды "Все типы ссылок" в Конструкторе Запросов ИР падает платформа.
Аналогично при вызове "Объединение ссылочных таблиц" и "Объединение ссылочных таблиц изменений"

**Comment by tormozit** [comment]
Думаю нет смысла делать новую заявку. Если проблема в точности такая же, то нужно просто переоткрыть старую. Это будет полезнее.

**Comment by PerlAmutor** [comment]
> Думаю нет смысла делать новую заявку. Если проблема в точности такая же, то нужно просто переоткрыть старую. Это будет полезнее.

А я не нашел как это сделать.

**Comment by tormozit** [comment]
Снизу ленты сообщений заявки должна быть кнопка "Reopen issue"

**Comment by PerlAmutor** [comment]
Что-то не видно такой:

![image](https://user-images.githubusercontent.com/87958986/134044932-ee8872a1-1562-4da3-89a5-eaf5501ff3ce.png)

**Comment by tormozit** [comment]
Ладно. Найди в модуле формы число 1000 и опускай его вниз, пока ошибка не прекратит воспроизводится.
Максимальная емкость стековой области виртуальной машины 1С разнится от разрядности, типа ОС и еще каких то параметров среды исполнения. Обычно эксперименты обнаруживают ее на уровнях 500-1000 элементов. Мой синтаксический анализатор текста запроса использует жадный к стеку метод построения синтаксического дерева (AST), т.е. макс. глубина рекурсии связана с макс. количеством элементов в одном списке (например частей объединения). Желательно найти ближайшее снизу число кратное 100.

**Comment by PerlAmutor** [comment]
Максимум 80 держит (90 и выше нет). Затем валиться на строчке самого исключения. По хорошему функцию ПостроитьНисходящееЗапросы() надо переписывать безрекурсивным методом через 2 массива.

**Comment by tormozit** [comment]
1. 80 - крайне низкое число. Я такое встречаю впервые. Пока у меня нет варианта объяснения настолько низкого значения.  Получается у тебя даже пакетный запрос из 100 запросов вызовет аналогичную проблему. Попробуй написать простейшую рекурсивную функцию с выводом в окно сообщений уровня и посмотри на каком уровне происходит переполнение в ней.
2. Таких функции 2. И они довольно сложные. Предлагаю тебе попробовать переписать код "безрекурсивным методом через 2 массива" (эмуляцией стека через массив). Но я очень сомневаюсь что безрекурсивный вариант кода сохранит свою читаемость. 

Полезные ссылки
https://partners.v8.1c.ru/forum/topic/1804356

**Comment by tormozit** [comment]
> Затем валиться на строчке самого исключения.

Для начала давай найдем уровень до которого выполняется спуск без аварийного завершения.

**Comment by tormozit** [comment]
Я проверил на нескольких компьютерах и разных конфигурациях, включая ERP. Ввезде использовал ИР вариант "Расширение". Везде уровень 1000 достигается и выбрасывается исключение и корректно отображается пользователю.

**Comment by PerlAmutor** [comment]
Может дело в версии платформы? Я попробовал и вариант - расширение. Там тоже до 1000 не доходит, раньше крашится.

**Comment by tormozit** [comment]
Я пробовал на 8.3.18 и 8.3.17. А 8.3.19 я пока не использую и не рекомендую к использованию из-за большого количества привнесенных ошибок.

**Comment by PerlAmutor** [comment]
Написал простую обработку. На уровне вложенности 654 падает.
[ТестРекурсии.zip](https://github.com/tormozit/RDT1C/files/7205027/default.zip)

**Comment by PerlAmutor** [comment]
Переписал функцию с использованием массивов. Не знаю насколько корректно она работает. В консоли запросов дерево выводится, а вот в Конструкторе Запросов ИР падает, но похоже уже в другом месте.
![image](https://user-images.githubusercontent.com/87958986/134234467-59f6cd37-a139-48c4-a4ee-2b126ce828d8.png)
[ПостроитьНисходящееЗапросы.txt](https://github.com/tormozit/RDT1C/files/7205702/default.txt)

**Comment by PerlAmutor** [comment]
Понятно почему падает теперь Конструктор Запросов ИР:

![image](https://user-images.githubusercontent.com/87958986/134237974-a5e49253-0674-4087-aa55-9b272589fa98.png)

**Comment by tormozit** [comment]
Вроде я выше писал, что функции 2. Видимо ты невнимательно читал.

**Comment by tormozit** [comment]
> Переписал функцию с использованием массивов. Не знаю насколько корректно она работает. 

Работает некорректно. Ты нарушил порядок обхода рекурсивного дерева, выстроив проходы по телу функции строго последовательно. В оригинальном цикле возвращаемые снизу параметры влияют на следующие проходы цикла. Иными словами ты упрощенно (не полностью) сэмулировал рекурсивный спуск. В общем случае эта задача довольно сложная.  Без изменения логики работы оригинальной функции ее врядли можно так просто решить. Мое предложение было направлено на то, чтобы ты понял что это не так просто как кажется. К тому же практического смысла в поддержке таких "широких" запросов нет, т.к. многие СУБД (например MS SQL) имеют аналогичные ограничения на количество таблиц/полей/соединений в запросе.

Элементарный запрос уже некорректно отображается
```
выбрать 1
ИЗ Константы КАК Веник

```
![изображение](https://user-images.githubusercontent.com/11896251/134244352-7717e974-504d-49a1-8bab-69fd1846c9f1.png)

**Comment by PerlAmutor** [comment]
Через реализацию LL(1) парсера можно ведь уйти от рекурсивного спуска, или я что-то путаю?
