### ISSUE TITLE
Найти скопированное значение. Индекс находится за границами массива

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#77]
https://user-images.githubusercontent.com/87958986/133954725-d961fb49-4675-4c23-bb97-b2f4ebb3a27f.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

Платформа: 8.3.19.1229
Режим БД: клиент-серверный
Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
Конфигурация. Основной режим запуска: Управляемое приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Управляемый
Конфигурация. Режим совместимости: Версия8_3_16
Конфигурация. Версия БСП: 301
Инструменты разработчика. Версия: Портативный 6.10.1p
Инструменты разработчика. Инструмент: Консоль запросов
Инструменты разработчика. Перехват клавиатурного ввода: Да
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Да
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет
Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При поиске по скопированному значению по ТЧ с установленном отборе возникает ошибка:

```
Индекс находится за границами массива
{ВнешняяОбработка.ирОбщий.МодульОбъекта(37629)}:			СтрокаТаблицыФормы = ДанныеТаблицы[ТаблицаИлиДеревоЗначений.Индекс(НайденнаяСтрока)];
{ВнешняяОбработка.ирПортативный.МодульОбъекта(398)}:	ирОбщий.НайтиСсылкуВТаблицеАктивнойФормыЛкс(Параметры.Форма);
{(1)}:ирПортативный.НайтиСкопированнуюСсылкуАктивнойФормыЛкс(ПараметрыВызова)
{ВнешняяОбработка.ирПлатформа.Форма.ГлобальноеМеню.Форма(534)}:	Выполнить("ирПортативный." + ЭлементыФормы.Команды.ТекущаяСтрока.Имя + "(ПараметрыВызова)"); // Так окно в управляемом приложении откроется в режиме блокирования владельца
```

Запрос для воспроизведения:

```
ВЫБРАТЬ ПЕРВЫЕ 1000
	ТоварыНаСкладах.Период КАК Период,
	ТоварыНаСкладах.Регистратор КАК Регистратор,
	ТоварыНаСкладах.НомерСтроки КАК НомерСтроки,
	ТоварыНаСкладах.Активность КАК Активность,
	ТоварыНаСкладах.ВидДвижения КАК ВидДвижения,
	ТоварыНаСкладах.Номенклатура КАК Номенклатура,
	ТоварыНаСкладах.Характеристика КАК Характеристика,
	ТоварыНаСкладах.Назначение КАК Назначение,
	ТоварыНаСкладах.Склад КАК Склад,
	ТоварыНаСкладах.Помещение КАК Помещение,
	ТоварыНаСкладах.Серия КАК Серия,
	ТоварыНаСкладах.ВНаличии КАК ВНаличии,
	ТоварыНаСкладах.КОтгрузке КАК КОтгрузке,
	ТоварыНаСкладах.КонтролироватьОстатки КАК КонтролироватьОстатки,
	ТоварыНаСкладах.Сторно КАК Сторно,
	ТоварыНаСкладах.МоментВремени КАК МоментВремени
ИЗ
	РегистрНакопления.ТоварыНаСкладах КАК ТоварыНаСкладах

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934090

**Comment by tormozit** [comment]
Исправлено в 6.11.1
