### ISSUE TITLE
Конструктор запросов. Ошибка восстановления временной таблицы

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#78]
![image](https://user-images.githubusercontent.com/87958986/134379051-f573b40a-bf65-4719-9a21-00125344b3aa.png)

<details> 
  <summary>Информация для технической поддержки</summary>

> 
> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Оставил на целый день открытый ИР с открытой структурой запроса. Когда пришел с работы увидел такое:

```
Ошибка восстановления временной таблицы "Константы": {ВнешняяОбработка.ирОбщий.МодульОбъекта(21098)}: Ошибка при вызове метода контекста (Выполнить): {(2, 23)}: Временная таблица уже существует "Константы"
ВЫБРАТЬ Т.* ПОМЕСТИТЬ <<?>>Константы ИЗ &Константы КАК Т
Ошибка восстановления временной таблицы "Константы": {ВнешняяОбработка.ирОбщий.МодульОбъекта(21098)}: Ошибка при вызове метода контекста (Выполнить): {(2, 23)}: Временная таблица уже существует "Константы"
ВЫБРАТЬ Т.* ПОМЕСТИТЬ <<?>>Константы ИЗ &Константы КАК Т
Ошибка восстановления временной таблицы "Константы": {ВнешняяОбработка.ирОбщий.МодульОбъекта(21098)}: Ошибка при вызове метода контекста (Выполнить): {(2, 23)}: Временная таблица уже существует "Константы"
ВЫБРАТЬ Т.* ПОМЕСТИТЬ <<?>>Константы ИЗ &Константы КАК Т

```
```

выбрать 1
ИЗ Константы КАК Веник
```

**Comment by tormozit** [comment]
Текст запроса желательно указывать в оригинальном виде.

**Comment by tormozit** [comment]
Выполнение запроса 
```
ВЫБРАТЬ 1
ПОМЕСТИТЬ Константы
```
Приводит к ошибке "Временная таблица уже существует "Константы"".
Так платформа предотвращает перекрытие доступа к таблице "Константы".

Другое дело, что консоль запросов не должна добавлять это имя в список обнаруженных временных таблиц. Ошибку воспроизвел https://www.hostedredmine.com/issues/934202

**Comment by tormozit** [comment]
Исправлено в 6.11.1
