### ISSUE TITLE
8.2 Консоль HTTP запросов. Ошибка при открытии

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#79]
https://user-images.githubusercontent.com/87958986/134451447-983f233b-b9ea-491f-afdb-997818d82c4d.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

```
{Форма.Форма.Форма(786,134)}: Переменная не определена (СпособКодированияСтроки)
		АдресРесурсаЗакодированный = СтрЗаменить(АдресРесурсаЗакодированный, ПараметрАдреса.Имя, КодироватьСтроку(ПараметрАдреса.Значение, <<?>>СпособКодированияСтроки.КодировкаURL))
{Форма.Форма.Форма(793,71)}: Переменная не определена (СпособКодированияСтроки)
		ФрагментыАдреса[Индекс] = КодироватьСтроку(ФрагментыАдреса[Индекс], <<?>>СпособКодированияСтроки.КодировкаURL);
{Форма.Форма.Форма(806,80)}: Переменная не определена (СпособКодированияСтроки)
			СтрокаПараметров = СтрокаПараметров + КодироватьСтроку(ПараметрЗапроса.Имя, <<?>>СпособКодированияСтроки.КодировкаURL)
{Форма.Форма.Форма(807,56)}: Переменная не определена (СпособКодированияСтроки)
				+ "=" + КодироватьСтроку(ПараметрЗапроса.Значение, <<?>>СпособКодированияСтроки.КодировкаURL);
{Форма.Форма.Форма(1284,54)}: Переменная не определена (СпособКодированияСтроки)
				ИмяПараметра = РаскодироватьСтроку(ИмяПараметра, <<?>>СпособКодированияСтроки.КодировкаURL);
{Форма.Форма.Форма(1285,64)}: Переменная не определена (СпособКодированияСтроки)
				ЗначениеПараметра = РаскодироватьСтроку(ЗначениеПараметра, <<?>>СпособКодированияСтроки.КодировкаURL);
{Форма.Форма.Форма(1297,75)}: Переменная не определена (СпособКодированияСтроки)
			ФрагментыАдреса[Индекс] = РаскодироватьСтроку(ФрагментыАдреса[Индекс], <<?>>СпособКодированияСтроки.КодировкаURL);
{Форма.Форма.Форма(786,92)}: Процедура или функция с указанным именем не определена (КодироватьСтроку)
		АдресРесурсаЗакодированный = СтрЗаменить(АдресРесурсаЗакодированный, ПараметрАдреса.Имя, <<?>>КодироватьСтроку(ПараметрАдреса.Значение, СпособКодированияСтроки.КодировкаURL))
{Форма.Форма.Форма(793,29)}: Процедура или функция с указанным именем не определена (КодироватьСтроку)
		ФрагментыАдреса[Индекс] = <<?>>КодироватьСтроку(ФрагментыАдреса[Индекс], СпособКодированияСтроки.КодировкаURL);
{Форма.Форма.Форма(806,42)}: Процедура или функция с указанным именем не определена (КодироватьСтроку)
			СтрокаПараметров = СтрокаПараметров + <<?>>КодироватьСтроку(ПараметрЗапроса.Имя, СпособКодированияСтроки.КодировкаURL)
{Форма.Форма.Форма(807,13)}: Процедура или функция с указанным именем не определена (КодироватьСтроку)
				+ "=" + <<?>>КодироватьСтроку(ПараметрЗапроса.Значение, СпособКодированияСтроки.КодировкаURL);
{Форма.Форма.Форма(986,51)}: Процедура или функция с указанным именем не определена (ПолучитьДвоичныеДанныеИзСтроки)
		СтрокаАутентификации = СтрЗаменить(Base64Строка(<<?>>ПолучитьДвоичныеДанныеИзСтроки(ПользовательЗапроса + ":" + ПарольЗапроса)), Символы.ВК + Символы.ПС, "");
{Форма.Форма.Форма(1284,20)}: Процедура или функция с указанным именем не определена (РаскодироватьСтроку)
				ИмяПараметра = <<?>>РаскодироватьСтроку(ИмяПараметра, СпособКодированияСтроки.КодировкаURL);
{Форма.Форма.Форма(1285,25)}: Процедура или функция с указанным именем не определена (РаскодироватьСтроку)
				ЗначениеПараметра = <<?>>РаскодироватьСтроку(ЗначениеПараметра, СпособКодированияСтроки.КодировкаURL);
{Форма.Форма.Форма(1297,30)}: Процедура или функция с указанным именем не определена (РаскодироватьСтроку)
			ФрагментыАдреса[Индекс] = <<?>>РаскодироватьСтроку(ФрагментыАдреса[Индекс], СпособКодированияСтроки.КодировкаURL);

```

**Comment by tormozit** [comment]
Формально это конечно ошибка. Но инструмент не поддерживает 8.2. А для того, чтобы вывести сообщение об отсутствии поддержки 8.2 делать отдельную функцию для каждой команды открытия инструмента, кажется неоправдано.

**Comment by PerlAmutor** [comment]
> Формально это конечно ошибка. Но инструмент не поддерживает 8.2. А для того, чтобы вывести сообщение об отсутствии поддержки 8.2 делать отдельную функцию для каждой команды открытия инструмента, кажется неоправдано.

Может быть тогда тут написать минимальную версию поддерживаемой платформы, а не только версию режима совместимости?

![image](https://user-images.githubusercontent.com/87958986/134536184-fd090940-2744-4d77-b0e5-b1c514f125fb.png)

**Comment by tormozit** [comment]
Подсистема "Инструменты разработчика" довольно большая. В ней есть сотни условий на версию платформы или режим совместимости, меняющие поведение инструментов вплоть до запрета открытия некоторых форм. Поэтому в описании указаны минимальная версия платформы, на которой запускается общая/базовая часть функционала инструментов. При этом некоторые инструменты имеют более высокую минимальную версию. Ты предлагаешь лишить пользователей старых версий платформы остальных (большей части от всех) инструментов. Думаю, это не гуманно.

Кстати кажется ты минимальные поддерживаемые версии платформы в описании подсистемы воспринял как режимы совместимости. Это неправильно. Режим совместимости там явно указан и только для варианта "Расширение".

**Comment by PerlAmutor** [comment]
> Кстати кажется ты минимальные поддерживаемые версии платформы в описании подсистемы воспринял как режимы совместимости. Это неправильно. Режим совместимости там явно указан и только для варианта "Расширение".

Нет. Иначе я бы и не стал ставить платформу 8.2 отдельно и создавать эту тему.

**Comment by PerlAmutor** [comment]
Это какое-то непоследовательное решение, т.к. при использовании инструментов "История данных" и "Редактор предопределенных"

Выдаются соответствующие сообщения:

`Инструмент доступен только в режиме совместимости 8.3.11 и выше`
`Инструмент доступен только в режиме совместимости 8.3.4 и выше`

Кроме того установка подобных заглушек избавляет других пользователей от необходимости оставлять багрепорты типа этого и доставать тебя с вопросами типа "почему не работает".

**Comment by tormozit** [comment]
В тех модулях, где на предотвращение ошибок компиляции не уходит много сил, я экранирую компиляцию неизвестных выражений через "вычислить" и "выполнить". В этом инструменте так делать слишком затратно  код превратится в месиво и его станет трудно поддерживать. Других дешевых вариантов платформа 1С мне не предоставляет.

**Comment by PerlAmutor** [comment]
На мой взгляд проблему можно решить достаточно просто. В качестве основной формы создается пустая форма-адаптер, запоминаются переданные параметры, в событии ПриОткрытии эта форма закрывается, вызывается ПолучитьФорму, которая и будет являться основной, в неё уже передаются параметры. В основной (пустой) форме делаются все необходимые проверки, а внутри второй формы, которая будет являться основной содержится некомпилируемый код. Но это так работает во всяком случае с УФ. Возможно ли такое провернуть с обычными не знаю.

**Comment by tormozit** [comment]
Цель должна оправдывать средства. Предложенный тобой способ (средство) породит массу сложностей для поддержки продукта из-за нарушения единого принципа открытия форм. Много лет назад я вдоволь наигрался с подобными приемами (с обычными формами) и очень хорошо знаю к чему это приведет.
Пользователи 8.2 - 5% от всех и эта доля будет неуклонно падать. Считаю очень неоправданным создавать себе такие сложности ради этого того, чтобы столь небольшому проценту пользователей просто не показывалась некрасивая ошибка в случае, если он откроет этот инструмент. В описании на сайте к этому инструменту указана минимальная версия платформы.
