### ISSUE TITLE
Не закрывается автоматически окно элемента Журнала Регистрации при закрытии ИР

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#8]
Портативный вариант ИР 6.03.1.
При двойном клике по выборке из Журнала Регистрации открывается окно с подробностями по событию журнала. Если закрыть основную панель ИР, то окно с деталями события ЖР остается открытым. При этом если вызвать контекстное меню текстового поля в таком окне и выбрать команду "Открыть", то возникнет ошибка связанная с тем, что основные обработки ИР уже прекратили свое существование.

https://user-images.githubusercontent.com/87958986/128065414-6b6cf65f-33a3-4a58-b2b8-632afc30b8b6.mp4

**Comment by tormozit** [comment]
Исправлено в 6.04.1
