### ISSUE TITLE
8.2 Отключить глобальные обработчики ожидания. Превышена допустимая глубина вложенности индикаторов.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#80]
https://user-images.githubusercontent.com/87958986/134451914-5d0e25cb-82b7-41c8-bc8e-17ae358ecd5d.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

При открытии инструмента "Отключить глобальные обработчики ожидания" или "Синтакс помощник" возникает ошибка:

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(8508)}: Превышена допустимая глубина вложенности индикаторов
		ВызватьИсключение "Превышена допустимая глубина вложенности индикаторов";

```

**Comment by tormozit** [comment]
Нужна демонстрация с начала сеанса. Желательно показать стек в момент возникновения ошибки. Покажи состояние кэша модулей в настройках компоненты "Поле текста программы". Также желательно передать конфигурацию.

**Comment by PerlAmutor** [comment]
Наверное и нет смысла, раз ты написал, что инструмент не поддерживает 8.2. А это ошибки 8.2, те же самые, что и тут http://devtool1c.ucoz.ru/forum/2-1963-1
https://github.com/tormozit/RDT1C/issues/79#issue-1004978429

**Comment by tormozit** [comment]
> ты написал, что инструмент не поддерживает 8.2

Не понял. Где я такое писал?
По-прежнему ожидаю запрошенную выше дополнительную информацию по проблеме.

**Comment by PerlAmutor** [comment]
Больше не удается воспроизвести.

**Comment by tormozit** [comment]
В таком случае постарайся вспомнить какие действия или хотя бы работа с какими инструментами и какие ошибки предшествовали тому случаю. Таблица индикаторов является глобальной и потому испортится могла любым предшествующим выполненным кодом.

**Comment by PerlAmutor** [comment]
Последовательно открывал все инструменты слева-направо и закрывал.

**Comment by PerlAmutor** [comment]
Нашел простой способ воспроизведения. Открываем инструмент "Редактор объекта БД" жмем последовательно F4 - ESC, 10 раз, пока не появится ошибка:


https://user-images.githubusercontent.com/87958986/134775983-3558dfa5-5d16-439b-b94a-8e2d81931d06.mp4
