### ISSUE TITLE
Консоль кода. Ошибка при завершении работы системы.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#81]
https://user-images.githubusercontent.com/87958986/134612734-723c2132-d3ba-436c-9cdb-3050599c1931.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Прочее
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

При выполнении следующего кода в консоли кода возникает ошибка (код эмулирует действие "выгонялки" типовых конфигураций):

`
ЗавершитьРаботуСистемы(Ложь);

`

`ирОбщий.СлужебныеДанныеФормыЛкс(ЭтаФорма){(1)}: Значение не является значением объектного типа (СлужебныеДанныеФормыЛкс)`

Ошибка плавающая, может возникать 1 раз за 20 завершений. Видимо как-то связано с порядком уничтожения внешних обработок, который меняется в какой-то момент.

**Comment by tormozit** [comment]
Да. Причина та же. Думаю нет смысла создавать подобные темы без стабильного способа воспроизведения, т.к. возникать подобные ошибки скорее всего могут в большом числе сценариев.
