### ISSUE TITLE
Колонки БД. Константы. Форма списка. Индекс находится за границами массива

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#82]
https://user-images.githubusercontent.com/87958986/134613958-e334d486-d266-439a-8506-517fa8464b24.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Колонки БД
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

При вызове команды "Форма списка" для константы в инструменте "Колонки БД" возникает ошибка:

```
Индекс находится за границами массива
{ВнешняяОбработка.ирОбщий.МодульОбъекта(37248)}:	Если Истина
{ВнешняяОбработка.ирОбщий.МодульОбъекта(24778)}:			ФормаСписка = ПолучитьФормуЛкс(ИмяТаблицы + ".ФормаСписка", ПараметрыФормы, ВладелецФормы, КлючУникальности); 
{ВнешняяОбработка.ирОбщий.МодульОбъекта(24648)}:	ФормаСписка = ПолучитьФормуСпискаЛкс(ИмяТаблицыИлиМДИлиТип, Отбор, ИспользоватьДинамическийСписокИР, ВладелецФормы, РежимВыбора, МножественныйВыбор, ТекущаяСтрока, ПользовательскийОтбор,,
{ВнешняяОбработка.ирКолонкиБД.Форма.Форма.Форма(647)}:		ирОбщий.ОткрытьФормуСпискаЛкс(ВыбраннаяСтрока.ПолноеИмяТаблицы,, ИспользоватьДинамическийСписокИР,,,,,, ПараметрОтбор);
{ВнешняяОбработка.ирКолонкиБД.Форма.Форма.Форма(654)}:	ОткрытьДинамичекийСписокТаблицы(Ложь);

```

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934381

**Comment by tormozit** [comment]
Исправлено в 6.11.1
