### ISSUE TITLE
Колонки БД. Неожиданное открытие инструмента Подбор и обработка объектов.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#83]
https://user-images.githubusercontent.com/87958986/134614408-a5aeaabd-af7c-4c60-8321-54566bab0d07.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Колонки БД
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

При вызове команды "Форма списка" над объектом не имеющего формы списка - открывается инструмент Подбор и обработка объекта БД с ранее сохраненной таблицей. Может есть смысл тогда открывать Динамический Список ИР?

Тоже самое происходит, если вызвать команду " \ Командная панель \ Динамической список (ИР)"

https://user-images.githubusercontent.com/87958986/134614605-9d766acd-4a61-4de7-a04b-57a58b8ce3c1.mp4

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934382

**Comment by PerlAmutor** [comment]
"Исправлена передача имени таблицы БД табличной части командой "Форма списка" в инструмент "Подбор и обработка объектов" - в смысле передача? В 8.2 команда "Динамический список ИР" открывает - Динамический список ИР, а в 8.3 по непонятной причине открывается обработка Подбор и обработка объектов. Т.е. поведение разное. Тут вероятно просто ошибка в выборе инструмента где-то в коде.

**Comment by tormozit** [comment]
Ошибки тут нет. Инструмент "Подбор и обработка объектов" открывается в качестве формы списка по такому условию
```bsl
		Или ирОбщий.ЛиТипВложеннойТаблицыБДЛкс(ТипТаблицы)
		Или ТипТаблицы = "Изменения"
		Или ТипТаблицы = "Перерасчет"
```
Причем программа даже сообщает причину в окне сообщений.

**Comment by PerlAmutor** [comment]
Только сейчас понял, что инструмент воспринимает ТабличныеЧасти отдельно от родительского объекта метаданных и пытается открыть их через "Подбор и обработку объектов", хотя на самом деле тут напрашивается некая доработка Динамического Списка под отображение содержимого табличных частей по аналогии с регистрами и результатом запроса (собственно то, что делает Универсальный Отчет в ERP):

![image](https://user-images.githubusercontent.com/87958986/134719435-f246bb74-f8f7-42b0-b62d-8ca601ac654b.png)

**Comment by tormozit** [comment]
Исправлено в 6.11.1
