### ISSUE TITLE
Анализ метаданных. КритерийОтбора.СсылкиНаПКО

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#84]
https://user-images.githubusercontent.com/87958986/134615631-af35f23f-baa4-4fe4-a5c6-d6a7752a8e9e.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

Платформа: 8.2.19.130
Режим БД: файловый
Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_2_13
Инструменты разработчика. Версия: Портативный 6.10.1p
Инструменты разработчика. Инструмент: Анализ метаданных
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

</details>

Отчет "Анализ метаданных" зачем-то ищет "КритерийОтбора.СсылкиНаПКО"

`
Не удалось найти в структуре хранения БД описание таблицы "КритерийОтбора.СсылкиНаПКО"
`

А в ERP другой критерий отбора:
`
Не удалось найти в структуре хранения БД описание таблицы "КритерийОтбора.ВзаимодействияКонтакта"
`

**Comment by tormozit** [comment]
На видео выводу сообщения предшествовала ошибка. Нужно ее описать либо описать воспроизведение без нее.

**Comment by PerlAmutor** [comment]
Она описана, возникает во многих местах - http://devtool1c.ucoz.ru/forum/2-1963-1
Поэтому предлагаю на нее не обращать внимание в контексте этой ошибки.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934407
