### ISSUE TITLE
Пожелание. Сворачиваемые блоки в репортах.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#85]
Можно ли в шаблон этого текста при создании новых заявок:

> **Программное окружение**
> Получить эту информацию можно по кнопке "Информация для технической поддержки" в окне "О подсистеме" http://devtool1c.ucoz.ru/forum/2-2-1
> 
> **Воспроизведение проблемы**
> 1. Открыл инструмент ААА
> 2. Нажал кнопку БББ
> 3. Получил окно с ошибкой ВВВ
> 
> **Ожидаемое поведение**
> Какая реакция программы ожидалась?
> 

добавить шаблончик?:

```
<details> 
  <summary>Информация для технической поддержки</summary>
...

</details>
```

А то несколько неудобно каждый раз открывать предыдущие репорты, включать редактирование и их копировать...

**Comment by tormozit** [comment]
Да ты же можешь сделать pull request

**Comment by tormozit** [comment]
сделал

**Comment by tormozit** [comment]
Если это то, что ты просил, то закрывай заявку.
