### ISSUE TITLE
Управление профайлами. Неверное определение каталога кэша баз 8.2

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#86]
https://user-images.githubusercontent.com/87958986/134756926-02599f9b-bbee-44e0-9de7-e27ae78b8641.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: клиент-серверный
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.5.6.261)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_16
> Конфигурация. Версия БСП: 301
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Обработка.ирПлатформа.Форма.СписокБазПользователяОС
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> Сервер. ОС: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)

</details>

Если в системе установлено 2 платформы: 8.2 и 8.3, то при использовании инструмента "Управление профайлами" в платформе 8.3 неверно вычисляется каталог кэша баз 8.2. Вместо пути "1cv82" используется "1cv8".
Соответственно и наоборот. Из 8.2 не правильно определяются каталоги кэшей баз 8.3. Не знаю насколько правильно будет определять базу только по ID каталога. Могут ли эти идентификаторы пересекаться в разных платформах?

**Comment by tormozit** [comment]
С чего ты взял это это неправильно? Так работает платформа. Я лишь повторил ее логику.

**Comment by PerlAmutor** [comment]
Была надежда, что инструмент универсальный. Но после того как я удалил строку подключения к базе 8.2 из лаунчера платформы 8.3 и кэш остался на месте, понял, что надежды нет...

**Comment by tormozit** [comment]
Первый раз признаюсь не до конца досмотрел, т.к. показалось что речь про то, что платформа размещает папки кэшей внутри папки с неподходящим номером (1cv8/1cv82). Такое она действительно может делать.
Пересмотрел видео. Ты прав. Проблема есть. Несуществующих папок не должно быть в списке в колонке "Каталог кэша".  https://www.hostedredmine.com/issues/934597

**Comment by tormozit** [comment]
Исправлено в 6.11.1

**Comment by PerlAmutor** [comment]
На самом деле не стоит ориентироваться на версию платформы, которая указана в параметрах подключения базы, в моем случае 1С сама ошибочно туда прописала версию 8.3 из-за чего реальный каталог кэша на самом деле находится в 1cv82 и ИР 6.11.1 этого не видит о чем указывает еще и пустая колонка размера кэша:

![image](https://user-images.githubusercontent.com/87958986/134819042-d6730d48-dacc-4b1b-8781-e8cff1e0a057.png)

![image](https://user-images.githubusercontent.com/87958986/134819155-c9001e11-aa5b-4ab7-b8e7-641eec881914.png)

Эту проблему похоже кроме как последовательным перебором версий каталогов в поисках ключа базы никак не решить:

![image](https://user-images.githubusercontent.com/87958986/134819198-3401802b-8372-41ed-a182-f7f109e1ad35.png)

**Comment by tormozit** [comment]
Строгого способа достоверно узнать этот каталог я не знаю. Одна база может в разное время запускаться через клиентские приложений разных версий платформы (например 8.2 и 8.3) и они будут использовать разные каталоги. Все их перебирать и отображать много колонок с вариантами - кажется не оправдано ради небольшого процента таких баз. Поэтому текущее решение кажется разумным компромиссом между универсальностью, удобством для пользователя и затратами.
