### ISSUE TITLE
Консоль кода. Заполнение параметров других алгоритмов.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#87]
https://user-images.githubusercontent.com/87958986/134773598-12e7bb13-d849-4d79-9b75-f58b307e8b51.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Консоль кода
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент Консоль кода
2. Добавил код:
`тест = 1;`
в алгоритм
3. Добавил новый пустой алгоритм.
4. Вызвал команду "Заполнить"

На место параметров стали параметры первого алгоритма.

**Ожидаемое поведение**
Каждый алгоритм имеет свой набор параметров.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934598

**Comment by tormozit** [comment]
Исправлено в 6.11.1
