### ISSUE TITLE
Конструктор запросов ИР. Синтаксическая ошибка ""

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#88]
https://user-images.githubusercontent.com/87958986/134773813-f9984b3e-d491-4447-b5ec-aba9d6f31e74.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Конструктор запросов ИР"
2. Перешел на вкладку "Построитель"
3. Добавил пустой параметр
4. Перешел на вкладку "Текст выборки"
5. Получил ошибку:

```
Ошибка синтаксического разбора выражения ""
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(2399)}:		ВызватьИсключение "Ошибка синтаксического разбора выражения """ + ВыражениеЗапроса + """";
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(6830)}:				НачальныйТокенВыражения = РазобратьВыражениеЗапроса(ВыражениеЗапроса, ТабличноеПоле = Неопределено);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(3265)}:	ТекстВыражения = ОбновитьВыражениеЗапроса(ПолеПостроителя, ТабличноеПоле, ЗапросПакета, ЧастьОбъединения,,,,,, 0);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(3244)}:		ТекстВыражения = ПолучитьОбновитьВыражениеПоляПостроителя(ПолеПостроителя, ТабличноеПолеПостроителя, ЗапросПакета, ЧастьОбъединения);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(3233)}:	ТекстПостроителя = СобратьТекстПредложенияПостроителя(ЗапросПакета, ТаблицаПолейПостроителя, ТабличноеПолеПостроителя, ЧастьОбъединения, Смещение);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(3434)}:	ДобавитьТекстПредложенияПостроителя(Результат, ПолучитьСловоЯзыкаЗапросов("SELECT"),
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(4204)}:	ТекстЧасти = СобратьТекстЧастиОбъединения(ЭлементыФормы.ЗапросыПакета.ТекущаяСтрока, ЭлементыФормы.ЧастиОбъединения.ТекущаяСтрока);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(4181)}:		ПересобратьВременныйТекстЧасти();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.Форма.КонструкторЗапроса.Форма(4170)}:	ПанельЧастиОбновитьТекущуюСтраницу();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(2759)}:	РезультатФормы = КонструкторЗапроса.ОткрытьМодально();
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(930)}:			Результат = ВызватьКонструкторЗапросов(Истина);
{ВнешняяОбработка.ирКлсПолеТекстаПрограммы.МодульОбъекта(891)}:	Результат = ВыполнитьКоманду(Команда);
{ВнешняяОбработка.ирКонсольЗапросов.Форма.Форма.Форма(284)}:		Результат = ЭкземплярКомпоненты.Нажатие(Кнопка);

```

**Ожидаемое поведение**
Игнорирование незаполненного или некорректного параметра Построителя

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.11.1
