### ISSUE TITLE
Конструктор запросов ИР. Переключение Диалекта языка SQL.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#89]
https://user-images.githubusercontent.com/87958986/134773943-0c3c40c5-da79-40e5-ab4e-47952051fe15.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.3.19.1229
> Режим БД: файловый
> Конфигурация. Название: 1С:ERP Управление предприятием 2 (2.4.5.54)
> Конфигурация. Основной режим запуска: Управляемое приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Управляемый
> Конфигурация. Режим совместимости: Версия8_3_10
> Конфигурация. Версия БСП: 204
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Конструктор запроса
> Инструменты разработчика. Перехват клавиатурного ввода: Да
> Инструменты разработчика. Объекты на сервере: Да
> Инструменты разработчика. Серверный модуль: Да
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 64б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Конструктор запросов ИР"
2. Выбрал Диалект SQL отличный от "1С". Скрылось поле ввода "Источник данных 1С"
3. Очистил поле "Диалект SQL" через "крестик" (или вызов команды "Очистить")
4. В поле обратно встал диалект "1С", но поле "Источник данных 1С" обратно не появилось

**Ожидаемое поведение**
При изменении поля "Диалект SQL" возвращать видимость поля "Источник данных 1С", если в выбранном поле "Диалект SQL" установлен диалект "1С"

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/934599

**Comment by tormozit** [comment]
Исправлено в 6.11.1
