### ISSUE TITLE
Ошибка в "Структура хранения БД" при работе с фильтром метаданных

### ISSUE THREAD

**Issue by Pufilov** [tormozit/RDT1C#9]
Платформа: 8.3.16.1502
Режим БД: клиент-серверный
Конфигурация. Название: MyCfg
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_2_16
Инструменты разработчика. Версия: Портативный 6.03.3p
Инструменты разработчика. Инструмент: Структура хранения БД
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. ОС: Майкрософт Windows 10 Корпоративная LTSC 64-разрядная Русский
Клиент. Приложение: Обычное приложение 64б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

**Воспроизведение проблемы**
![image](https://user-images.githubusercontent.com/88433411/128167493-029f81e6-577a-45c9-b3e6-c18ce8c99799.png)
При нажатии "отображать строки таблицы по метаданным" получаю ошибку.
Отчет системы: 
{ВнешняяОбработка.ирОбщий.МодульОбъекта(14707)}: Итератор для значения не определен
	Для Каждого Фрагмент Из Подстроки Цикл

**Ожидаемое поведение**
Открывается список метаданных, для выбора нужных данных.

**Comment by tormozit** [comment]
Ошибку воспроизвел https://www.hostedredmine.com/issues/931791

**Comment by tormozit** [comment]
Исправлено в 6.03.4
