### ISSUE TITLE
Редактор текста. JSON. (8.2)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#90]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Исследователь объектов
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор текста" (Текст)
2. Ввел текст "тест"
3. Нажал кнопку "JSON"
3. Получил окно с ошибкой:

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(20073)}: Тип не определен (ЧтениеJSON)
	Возврат Новый ("ЧтениеJSON");
```

**Ожидаемое поведение**
Сериализация содержимого в JSON формат.

**Comment by tormozit** [comment]
Ошибку воспроизвел по тексту. Видео ты видимо по ошибке вставил от другой проблемы.

**Comment by tormozit** [comment]
Исправлено в 6.11.1
