### ISSUE TITLE
Исследователь объектов. JSON. (8.2)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#91]
https://user-images.githubusercontent.com/87958986/134774172-9205c75e-2168-4492-a4ae-ac849d6b7703.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Исследователь объектов
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Исследователь объектов"
2. Нажал кнопку "JSON"
3. Получил окно с ошибкой :

```
{Форма.ИсследовательОбъектов.Форма(757)}: Значение не является значением объектного типа (Значение)
	Значение = ЭтаФорма.ЭлементыФормы.ДеревоЗначений.ТекущаяСтрока.Значение;

```

Подобные ошибки идут по всему блоку команд:

![image](https://user-images.githubusercontent.com/87958986/134774248-6837d979-693d-4693-959b-4feaa4d129ce.png)

**Ожидаемое поведение**
Отсутствие каких-либо действий и сообщений.

**Comment by tormozit** [comment]
Ошибку воспроизвел, но только для команд, связанных с JSON.

**Comment by tormozit** [comment]
Исправлено в 6.11.1
