### ISSUE TITLE
Исследователь объектов. XDTO. (8.2, 8.3)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#92]
https://user-images.githubusercontent.com/87958986/134774334-cdd86ec1-10bf-470b-97f3-7654fa805997.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

Платформа: 8.2.19.130
Режим БД: файловый
Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_2_13
Инструменты разработчика. Версия: Портативный 6.10.1p
Инструменты разработчика. Инструмент: Исследователь объектов
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Исследователь объектов"
2. Нажал кнопку "Глобальный"
3. Нажал кнопку "XDTO"
3. Получил окно с ошибкой:

```
Ошибка отображения типов:
Отсутствует отображение для типа 'Неопределено'

```

**Ожидаемое поведение**
Затрудняюсь ответить.

**Comment by tormozit** [comment]
Не все типы имеют отображение в XDTO. Поэтому я не вижу здесь возможности сделать поведение программы более естественным или понятным.
