### ISSUE TITLE
Редактор объекта БД. Тут может быть имитатор!

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#93]
https://user-images.githubusercontent.com/87958986/134774496-b4eee080-df9d-4114-a03e-93700111626e.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

Платформа: 8.2.19.130
Режим БД: файловый
Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_2_13
Инструменты разработчика. Версия: Портативный 6.10.1p
Инструменты разработчика. Инструмент: Редактор объекта БД
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД"
2. Выбрал "Справочник.Конвертации"
3. Перешел на закладку "Табличные части"
4. Установил флажок "Отбор просмотра"
5. Получил ошибку:

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(40612)}: Значение не является значением объектного типа (Имя)
	Префикс = "" + ТабличноеПоле.Имя; // Тут может быть имитатор табличного поля

```

**Ожидаемое поведение**
Недоступный для редактирования флажок "Отбор просмотра" без установленного отбора. Отсутствие ошибки при снятии флажка, если отбор все же установлен.

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.11.1
