### ISSUE TITLE
Редактор объекта БД. Очистить.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#94]
https://user-images.githubusercontent.com/87958986/134774766-aa583947-c408-42a8-b17a-8e546c0fb262.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объектов БД"
2. Выбрал "Справочник.Конвертации"
3. Перешел на вкладку "Табличные части"
4. Нажал кнопку "Очистить"
5. Получил информацию об ошибке:

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(40551)}: Значение не является значением объектного типа (Имя)
			выхПутьКДанным = Элемент.Имя;

```

**Ожидаемое поведение**
Отсутствие каких-либо действий при работе с пустой ссылкой объекта.

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.12.1
