### ISSUE TITLE
Консоль запросов. Превышена допустимая глубина вложенности индикаторов. (8.2)

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#95]
https://user-images.githubusercontent.com/87958986/134775805-1831ff1b-8df9-409f-881b-9209bad10460.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Консоль запросов
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Консоль запросов"
2. Нажал кнопку "Установить текст"->"Объединение ссылочных полей изменений"  10 раз.
3. Получил окно с ошибкой:

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(8508)}: Превышена допустимая глубина вложенности индикаторов
		ВызватьИсключение "Превышена допустимая глубина вложенности индикаторов";

```

**Ожидаемое поведение**
Отсутствие этой ошибки.

Возможно ошибка как-то связана с ошибкой "Представления" (на неё есть отдельная тема). Протестировать получиться лишь после её исправления.

**Comment by tormozit** [comment]
Причина тут та же, что и в https://github.com/tormozit/RDT1C/issues/80
