### ISSUE TITLE
Редактор объекта БД. Очистка менеджера временных таблиц.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#96]
<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Редактор объекта БД
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор объекта БД" (остальные окна были закрыты, в том числе и Консоль Запросов)
2. Ушел спать
3. Утром получил окно с ошибкой (штук 10 друг за другом):

![image](https://user-images.githubusercontent.com/87958986/134792012-2047632e-e1e2-46df-acdb-f42db89550df.png)

```
{ВнешняяОбработка.ирОбщий.МодульОбъекта(29232)}: Значение не является значением объектного типа (РежимОтладкиЛкс)
	Если ирКэш.РежимОтладкиЛкс() Тогда 
```

**Ожидаемое поведение**
Отсутствие поведения либо очистка этого менеджера временных таблиц, если оно повторяется периодически в этом инструменте..

**Comment by tormozit** [comment]
Похоже в памяти залипла (циклом ссылок) форма консоли запросов, которая относилась к закрытой базовой форме, и потому указатели на общие модули в ее общих модулях очищены. Форма консоли запросов в данном случае работает как задумано - очищает свой менеджер временных таблиц с заданной периодичностью. 

Ошибкой является ее залипание. Но из описания непонятно, как оно возникает. Поэтому нужно описывать шаги, приводящие к залипанию. Для этого можно уменьшить частоту пересоздания менеджера временных таблиц до 1 минуты и проводить эксперименты.

**Comment by tormozit** [comment]
Скорее всего эта ошибка должна воспроизводиться и на 8.3. А там в точке останова можно вычислить 
ПроверитьЦиклическиеСсылкиВстроенногоЯзыка(Форма) и увидеть цикл ссылок.

**Comment by PerlAmutor** [comment]
Попробовал на 8.3, там не воспроизводится. Думаю дело в другом:

![image](https://user-images.githubusercontent.com/87958986/134807576-806b0994-c76d-4ff1-8392-454fcc865e5b.png)

Судя по коду, обработчик ожидания отключается лишь после очистки временных таблиц, если форма консоли запроса закрыта. Но из-за того, что между двумя условиями в момент вызова ПересоздатьМенеджерВременныхТаблиц возникает исключение, то выход из процедуры идет раньше ожидаемого и обработчик так и остается выполняться до победного, т.к. до его отключения дело никогда не дойдет...

Чтобы этого избежать есть параметр "Однократно":

![image](https://user-images.githubusercontent.com/87958986/134807735-e0a4eaaf-3272-4bab-aae8-9e8f29551ba2.png)

После удачного вызова очистки временных таблиц просто повторно вызывать следующий однократный.

**Comment by tormozit** [comment]
Так и задумано, чтобы обработчик вызывался до победного. Ведь его он несет важную функцию. Поэтому правильнее, чтобы пользователь видел эти ошибки и перезапустил сеанс.

**Comment by PerlAmutor** [comment]
А вот почему ирКэш побился в ирОбщий, загадка.

**Comment by tormozit** [comment]
Я выше https://github.com/tormozit/RDT1C/issues/96#issuecomment-927233086 постарался объяснить. Очистка этой и подобных переменных модулей выполняется штатно при закрытии базовой формы (панели инструментов).

**Comment by PerlAmutor** [comment]
Эта информация тебе о чем-нибудь говорит?
![image](https://user-images.githubusercontent.com/87958986/134808691-9d1ae207-90e9-430e-b742-daf153887bcf.png)

Любопытную статью нашел https://infostart.ru/1c/articles/89283/?ID=89283&bxajaxid=58f03b476ed57dfe327b1fe43cb65677&PAGEN_2=2

**Comment by tormozit** [comment]
> Эта информация тебе о чем-нибудь говорит?

Нет. Обнаружение этой циклической ссылки в этом случае является формально корректным, но по сути ложным, т.к. этот цикл всегда разрывается платформой. В 1С я сообщал об этой проблеме. Поэтому полезных (для расследования) циклических ссылок на твоем снимке нет.

**Comment by PerlAmutor** [comment]
Ошибка пока не проявляется с версии 6.10.2p
