### ISSUE TITLE
Редактор изменений на узлах. Открыть данные в основной форме.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#98]
https://user-images.githubusercontent.com/87958986/134792410-3fc7ddb8-dcf7-4ff0-92e5-149f862bd25a.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

> Платформа: 8.2.19.130
> Режим БД: файловый
> Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
> Конфигурация. Основной режим запуска: Обычное приложение
> Конфигурация. Вариант встроенного языка: Русский
> Конфигурация. Режим управления блокировкой данных: Автоматический
> Конфигурация. Режим совместимости: Версия8_2_13
> Инструменты разработчика. Версия: Портативный 6.10.1p
> Инструменты разработчика. Инструмент: Редактор изменений на узлах
> Инструменты разработчика. Перехват клавиатурного ввода: Нет
> Инструменты разработчика. Объекты на сервере: Нет
> Инструменты разработчика. Серверный модуль: Нет
> Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
> Клиент. Приложение: Обычное приложение 32б
> Клиент. Проверка модальных вызовов: Нет
> Клиент. Язык интерфейса конфигурации: ru
> Клиент. Язык интерфейса системы: ru
> Клиент. От имени администратора Windows: Нет
> 

</details>

**Воспроизведение проблемы**
**Воспроизведение проблемы**
1. Открыл инструмент "Редактор изменений на узлах"
2. Нажал кнопку "Обновить"
3. Нажал кнопку "Добавить" в ТЧ под полем "Количество"
4. Нажал кнопку "Открыть данные основной формы"
3. Получил окно с ошибкой:

```
{Форма.Форма.Форма(1015)}: Значение не является значением объектного типа (ПолноеИмя)
	ПолноеИмяМД = ЭлементыФормы.ДеревоТаблиц.ТекущаяСтрока.ПолноеИмя;

```

**Ожидаемое поведение**
Отсутствие реакции.

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.12.1
