### ISSUE TITLE
Редактор изменений на узлах. Сбросить номер сообщений для выделенных строк.

### ISSUE THREAD

**Issue by PerlAmutor** [tormozit/RDT1C#99]
https://user-images.githubusercontent.com/87958986/134792496-4680b9d2-d257-45a8-bfca-87f42c0f2c03.mp4

<details> 
  <summary>Информация для технической поддержки</summary>

 Платформа: 8.2.19.130
Режим БД: файловый
Конфигурация. Название: Конвертация данных, редакция 2.1 (2.1.8.2)
Конфигурация. Основной режим запуска: Обычное приложение
Конфигурация. Вариант встроенного языка: Русский
Конфигурация. Режим управления блокировкой данных: Автоматический
Конфигурация. Режим совместимости: Версия8_2_13
Инструменты разработчика. Версия: Портативный 6.10.1p
Инструменты разработчика. Инструмент: Редактор изменений на узлах
Инструменты разработчика. Перехват клавиатурного ввода: Нет
Инструменты разработчика. Объекты на сервере: Нет
Инструменты разработчика. Серверный модуль: Нет
Клиент. ОС: Майкрософт Windows 10 Pro 64-разрядная Русский
Клиент. Приложение: Обычное приложение 32б
Клиент. Проверка модальных вызовов: Нет
Клиент. Язык интерфейса конфигурации: ru
Клиент. Язык интерфейса системы: ru
Клиент. От имени администратора Windows: Нет

</details>

**Воспроизведение проблемы**
1. Открыл инструмент "Редактор изменений на узлах"
2. Нажал кнопку "Добавить" в ТЧ снизу слева
4. Нажал кнопку "Сбросить номер сообщения для выделенных строк"
3. Получил окно с ошибкой:

```
{Форма.Форма.Форма(1468)}: Поле объекта не обнаружено (Узел)
		ирОбщий.ПланыОбменаИзменитьРегистрациюЛкс(ВыделеннаяСтрока.Узел, КлючОбъекта);

```

**Ожидаемое поведение**
Отсутствие поведения.

**Comment by tormozit** [comment]
Ошибку воспроизвел

**Comment by tormozit** [comment]
Исправлено в 6.12.1
